"""Registry-backed AEAT legal calculation authority.

The public surface re-exports every canonical spine type so callers import from
one location. Core structs include :class:`ModeloDefinition` (static modelo
metadata), :class:`ModeloRevision` (one period-scoped revision of a modelo),
:class:`RegistrySnapshot` (validated snapshot for a single filing context),
:class:`ValidatedRegistryAuthority` (the production access point that loads,
validates, and caches registry material), and :class:`CasillaObservation`
(one typed casilla value carrying full legal and source provenance).

Registry definitions are declarative authority, not application workflow state.
:class:`ValidatedRegistryAuthority` loads bundled TOML, validates cross-file
references, and returns snapshots. :func:`calculate_registry_snapshot` evaluates
the snapshot with already-resolved casilla inputs, binding values, enum binding
values, relation values, and date context. The application source mesh resolves
those values before entering this package.

The facade also exposes the typed binding and observation helpers used by mesh
resolvers: ledger observations, invoice observations, previous-filing carries,
relation materialisation, detail-row folds, unsupported-observation diagnostics,
export layout resolution, applicability rules, verification expectations, live
parity/oracle structures, workbook parity helpers, and registry query reports.

See Also:
    :class:`ValidatedRegistryAuthority`
        Production loader, validator, and snapshot cache for bundled registry
        material.
    :func:`calculate_registry_snapshot`
        Formula runtime entry point that emits
        :class:`CasillaObservation` rows with legal and source provenance.
    :class:`DataBindingDefinition`
        Declarative binding contract resolved by application source owners.
    :mod:`aeat.application.aggregation`
        Source-mesh contract that supplies
        :class:`~aeat.application.aggregation.CalculationSourceResolution`
        envelopes before registry calculation.
    :mod:`aeat.application.calculations`
        Prior-filing, relation-prefill, IVA-wallet, and row-set stores that feed
        registry binding and relation inputs.
"""

# ruff: noqa: I001
# Registry identifiers must be re-exported before imports that can re-enter this
# package during validation bootstrap.
from __future__ import annotations

from ._aeat_nif_iva_oracle import AeatNifIvaCheckerOracle, AeatNifIvaObservation
from ._ids import (
    ApplicationLinkId,
    BindingId,
    CasillaId,
    ConstructId,
    CrossReferenceId,
    DeadlineWindowId,
    DependencyClassificationId,
    ExportFieldId,
    ExportLayoutId,
    ExtractionProfileId,
    FormulaId,
    LegalRefId,
    ModeloId,
    OracleId,
    ParameterId,
    RecordId,
    RelationId,
    RevisionId,
    SourceRefId,
    SupportRemovalDecisionId,
    VerificationExpectationId,
    WorkbookFixtureId,
    WorkbookOutputId,
    WorkbookParityRefId,
    is_registry_id,
    validated_casilla_id,
    validated_casilla_id_map,
)

# Applicability is imported after _schema so its transitive import of
# aeat.domain.deadlines (which depends on DeadlineWindowDefinition
# exported above) does not race a partially-initialised registry
# namespace.
from ._applicability import (
    ApplicabilityVerdict,
    Modelo202Modality,
    Modelo202ModalityVerdict,
    ModeloApplicability,
    ModeloApplicabilityRule,
    PayerFact,
    TaxRoute,
    derive_modelo_202_modality,
    derive_modelo_applicability,
    derive_tax_route,
    has_applicability_rule,
    iter_modelo_applicability_rules,
    modelo_202_modality_from_inputs,
    taxpayer_model_is_declared,
)
from ._authority import ValidatedRegistryAuthority, bundled_authority
from ._bindings import (
    INVOICE_BINDING_SOURCE_KINDS,
    LEDGER_BINDING_SOURCE_KINDS,
    AtributionMemberObservation,
    BindingAggregationOp,
    CasillaObservation,
    CounterpartAggregationObservation,
    CounterpartObservationRequirement,
    CounterpartSourceKind,
    InvoiceObservation,
    InvoiceObservationRequirement,
    IvaLedgerObservation,
    Modelo720RowObservation,
    OracleModeloObservation,
    OssIossLedgerObservation,
    RefundOperationObservation,
    RegistryModeloObservation,
    RelatedPartyOperationObservation,
    RentaGastoObservationProtocol,
    RentaIncomeObservationProtocol,
    WithholdingObservation,
    WithholdingObservationRequirement,
    binding_aggregation_op,
    binding_source_casilla_ids,
    counterpart_binding_requirements,
    invoice_binding_requirements,
    previous_filing_observation_requirements,
    previous_filing_source_reference,
    resolve_atribucion_binding_row_values,
    resolve_bound_inputs_by_casilla_id,
    resolve_counterpart_binding_row_values,
    resolve_counterpart_binding_values,
    resolve_foreign_asset_binding_row_values,
    resolve_invoice_binding_row_values,
    resolve_invoice_binding_values,
    resolve_ledger_iva_aggregation_binding_values,
    resolve_ledger_oss_aggregation_binding_values,
    resolve_ledger_renta_expense_aggregation_binding_values,
    resolve_ledger_renta_gasto_aggregation_binding_values,
    resolve_ledger_renta_income_aggregation_binding_values,
    resolve_previous_filing_binding_values,
    resolve_refund_binding_row_values,
    resolve_related_party_binding_row_values,
    resolve_retenciones_aggregation_binding_values,
    resolve_withholding_binding_row_values,
    resolve_withholding_binding_values,
    selector_model_for_source,
    unsupported_ledger_iva_observations,
    unsupported_ledger_oss_observations,
    unsupported_ledger_renta_expense_observations,
    unsupported_ledger_renta_gasto_observations,
    unsupported_ledger_renta_income_observations,
    validate_invoice_binding_definition,
    validate_ledger_iva_aggregation_binding_definition,
    validate_ledger_oss_aggregation_binding_definition,
    validate_ledger_renta_expense_aggregation_binding_definition,
    validate_ledger_renta_gasto_aggregation_binding_definition,
    validate_ledger_renta_income_aggregation_binding_definition,
    validate_retenciones_aggregation_binding,
    withholding_binding_requirements,
)
from ._binding_selector_utils import BindingRowSetSelector, binding_row_set_selector
from ._casilla_membership import (
    casilla_noncanonical_reference_targets,
    casilla_noncanonical_reference_tokens,
    casillas_by_id,
    declared_casilla_ids,
    undeclared_casilla_ids,
)
from ._censo_modelos import (
    CENSO_MODELO_ERROR_CODES,
    CENSO_MODELO_EVENT_KINDS,
    CENSO_MODELO_SERVICE_OWNER,
    CensoModeloEventKind,
    CensoModeloFoundationCommand,
    CensoModeloFoundationContract,
    CensoModeloFoundationLogFields,
    CensoModeloFoundationResult,
    CensoModeloOwnership,
    CensoModeloRole,
    build_censo_modelo_foundation_contract,
    censo_modelo_ownership,
    censo_modelo_ownership_map,
    get_censo_modelo_foundation_contract,
    is_active_censo_modelo,
    resolve_censo_modelo_foundation,
    resolve_censo_modelo_work_unit_foundation,
)
from ._constructs import ResolvedConstruct, ResolvedConstructMember, resolve_construct, resolve_revision_constructs
from ._corpus_catalogue import verify_source_catalogue, verify_source_file
from ._coverage import (
    EvidenceTierCoverageGate,
    ModelLawCoverageLedger,
    RegistryCoverageAudit,
    audit_registry_model_law_coverage,
    build_model_law_coverage_ledger,
)
from ._cross_revision_divergence import CrossRevisionCasillaDivergence
from ._errors import (
    AmbiguousRevisionSelectionError,
    NoRevisionForPeriodError,
    RegistryError,
    RegistryLoadError,
    RegistrySnapshotError,
    RegistryValidationError,
)
from ._export import (
    ResolvedExportLayout,
    derive_export_layouts_from_bindings,
    export_fields_for_casilla,
    resolve_export_layout,
)
from ._export_parse import ParsedExportFieldValue, ParsedExportPayload, parse_export_payload
from ._filed_state import RegistryFiledStateComparison, compare_calculation_to_filed_observation
from ._formula_runtime import (
    M210_CONVENIO_MISSING_SENTINEL,
    M210_DEFERRED_TIPO_SENTINEL,
    M210_RATE_SENTINELS,
    RegistryCalculationEntry,
    RegistryCalculationResult,
    calculate_registry_snapshot,
    read_parameter,
)
from ._groi_oracle import (
    GROI_ORACLE_ID,
    GroiDriver,
    GroiObservation,
    GroiOracle,
    GroiReplayDriver,
)
from ._legal import verify_legal_catalogue, verify_legal_reference
from ._live_parity import (
    CrossReferenceApplicability,
    CrossReferenceApplicabilityDeclaracion,
    LiveParityCatalogue,
    LiveParityOracle,
    OracleEnvironment,
    OracleSurfaceKind,
    ParityFieldComparison,
    ParityResult,
    ParityVerdict,
    audit_registry_oracle_bindings,
    collect_applicability_declarations,
    collect_orphan_oracle_ids,
    evaluate_cross_reference_applicability,
    resolve_cross_reference_oracle,
)
from ._loader import (
    ModeloRevisionSource,
    ModeloSource,
    discover_modelo_sources,
    load_catalogue_file,
    load_legal_parameters_only,
    load_modelo_directory,
    load_modelo_file,
    load_modelo_path,
    load_modelo_source,
    load_registry_tree,
)
from ._observation_fold import (
    fold_observed_requirement_values,
    fold_sum_or_copy,
    gather_observed_requirement_values,
    resolve_observed_requirement_value,
)
from ._parity_tapes import (
    ParityScenario,
    ParityTape,
    ParityTapeReplayReport,
    generate_parity_tape_path,
    load_parity_scenario,
    load_parity_tape,
    replay_parity_tape,
    run_parity_scenario,
    save_parity_scenario,
    save_parity_tape,
)
from ._queries import (
    BindingSelectorQueryEntry,
    BindingSelectorQueryProjection,
    ModeloBindingQueryRow,
    ModeloBindingsReport,
    ModeloCasillaRow,
    ModeloCasillasReport,
    ModeloDescribeReport,
    ModeloFormulaRow,
    ModeloFormulasReport,
    ModeloListReport,
    ModeloListRow,
    RegistryQueryService,
)
from ._record_design import (
    DerivedDisenoCasilla,
    DisenoCoverageReport,
    RecordDesignField,
    RecordDesignSheet,
    build_diseno_coverage_report,
    calculation_closure_casilla_ids,
    calculation_closure_legal_refs,
    calculation_closure_record_design_metadata,
    derive_calculation_completeness_casillas,
    derive_diseno_coverage_casillas,
    extract_record_design,
    extract_record_design_pdf,
    extract_record_design_pdf_bytes,
    extract_record_design_workbook,
)
from ._relation_aggregation import relation_aggregation_op
from ._relations import (
    RegistryFoldRequirement,
    materialize_relation_binding_values,
    relation_source_requirements,
    resolve_relation_values,
    resolve_relation_values_from_observations,
)
from ._remote_state_guard import (
    AEAT_WRITE_FORBIDDEN_ACTIONS,
    AEAT_WRITE_FORBIDDEN_VERB_TOKENS,
    RemoteOperation,
    RemoteStateGuardPolicy,
    RemoteStateGuardResult,
    assert_remote_operation_allowed,
    assert_remote_operations_allowed,
    evaluate_remote_operation,
    remote_state_policy_from_cross_reference,
)
from ._renta_web_open_oracle import (
    RentaWebOpenDisplayOverride,
    RentaWebOpenDriver,
    RentaWebOpenLivePayload,
    RentaWebOpenObservation,
    RentaWebOpenOracle,
    RentaWebOpenReplayDriver,
    RentaWebOpenSyntheticProfile,
    equivalent_renta_web_open_value,
    parse_renta_web_open_live_payload,
    validate_renta_web_open_expected_casilla_ids,
    validate_renta_web_open_expected_casilla_values,
)
from ._runtime_graph import (
    enum_consumed_binding_ids,
    expression_binding_refs,
    expression_casilla_refs,
    expression_date_binding_refs,
    input_casilla_id_map,
    revision_date_binding_ids,
)
from ._schedules import applicable_filing_schedules, evaluate_profile_conditions, profile_condition_matches
from ._schema import (
    KNOWN_VERIFICATION_PREDICATE_OPERATORS,
    ApplicationLinkDefinition,
    BboxAnchorSpec,
    BracketEntry,
    CalculationCompletenessCasilla,
    CalculationCompletenessManifest,
    CasillaContinuidadEvolutionDefinition,
    CasillaDefinition,
    CasillaFieldKind,
    CasillaFieldKindValue,
    ConstructDefinition,
    ConvenioRateRow,
    DataBindingDefinition,
    DeadlineWindowDefinition,
    DecimalValue,
    DependencyClassificationDefinition,
    EvidenceTier,
    ExportFieldDefinition,
    ExportLayoutDefinition,
    ExportRecordDefinition,
    ExtractionProfileDefinition,
    ExtractionTargetDefinition,
    FormulaDefinition,
    FormulaExpression,
    KeyedBracketEntry,
    LegalParameter,
    LegalReference,
    LiveCrossReferenceDecision,
    ModeloDefinition,
    ModeloFilingCapability,
    ModeloRevision,
    ModeloScheduleDefinition,
    ParameterDefinition,
    ProfilePredicateDefinition,
    RegistryCatalogues,
    RegistrySnapshot,
    RegistrySnapshotRef,
    RegistryVerificationPolicy,
    SourceReference,
    SupportRemovalDecisionDefinition,
    VerificationExpectationDefinition,
    VerificationPredicateDefinition,
    WorkbookParityReference,
)
from ._schema_input_kind import InputKind, InputKindValue
from ._schema_rounding import RegistryRoundingCode
from ._snapshot import build_snapshot
from ._validate import RegistryValidator
from ._validate_cross_revision import (
    CrossRevisionCasillaDriftSummary,
    summarize_non_overlapping_cross_revision_casilla_drift,
)
from ._validate_references import (
    CrossDomainSnapshotCheck,
    register_cross_domain_snapshot_check,
)
from ._validate_revision_identity import revision_casilla_identity_failures, revision_reference_identity_failures
from ._workbook_parity import (
    SyntheticInputSet,
    SyntheticInputValue,
    WorkbookArtefactReport,
    WorkbookBackendVerificationReport,
    WorkbookCellRef,
    WorkbookConversionReport,
    WorkbookModeloCoverage,
    WorkbookParityComparison,
    WorkbookParityRunReport,
    WorkbookRunnerAvailability,
    WorkbookScanOptions,
    assert_formula_workbook_runner_ready,
    assert_workbook_scan_clean,
    compare_registry_to_workbook,
    convert_binary_xls_with_libreoffice,
    converted_binary_xls_with_libreoffice,
    detect_workbook_runner,
    discover_workbooks,
    inventory_workbook_coverage,
    parse_workbook_cell_ref,
    run_registry_workbook_parity,
    run_workbook_with_excel_com,
    run_workbook_with_libreoffice,
    scan_workbook,
    verify_workbook_backend,
)

__all__ = [
    "AEAT_WRITE_FORBIDDEN_ACTIONS",
    "AEAT_WRITE_FORBIDDEN_VERB_TOKENS",
    "CENSO_MODELO_ERROR_CODES",
    "CENSO_MODELO_EVENT_KINDS",
    "CENSO_MODELO_SERVICE_OWNER",
    "GROI_ORACLE_ID",
    "INVOICE_BINDING_SOURCE_KINDS",
    "KNOWN_VERIFICATION_PREDICATE_OPERATORS",
    "LEDGER_BINDING_SOURCE_KINDS",
    "M210_CONVENIO_MISSING_SENTINEL",
    "M210_DEFERRED_TIPO_SENTINEL",
    "M210_RATE_SENTINELS",
    "AeatNifIvaCheckerOracle",
    "AeatNifIvaObservation",
    "AmbiguousRevisionSelectionError",
    "ApplicabilityVerdict",
    "ApplicationLinkDefinition",
    "ApplicationLinkId",
    "AtributionMemberObservation",
    "BboxAnchorSpec",
    "BindingAggregationOp",
    "BindingId",
    "BindingRowSetSelector",
    "BindingSelectorQueryEntry",
    "BindingSelectorQueryProjection",
    "BracketEntry",
    "CalculationCompletenessCasilla",
    "CalculationCompletenessManifest",
    "CasillaContinuidadEvolutionDefinition",
    "CasillaDefinition",
    "CasillaFieldKind",
    "CasillaFieldKindValue",
    "CasillaId",
    "CasillaObservation",
    "CensoModeloEventKind",
    "CensoModeloFoundationCommand",
    "CensoModeloFoundationContract",
    "CensoModeloFoundationLogFields",
    "CensoModeloFoundationResult",
    "CensoModeloOwnership",
    "CensoModeloRole",
    "ConstructDefinition",
    "ConstructId",
    "ConvenioRateRow",
    "CounterpartAggregationObservation",
    "CounterpartObservationRequirement",
    "CounterpartSourceKind",
    "CrossDomainSnapshotCheck",
    "CrossReferenceApplicability",
    "CrossReferenceApplicabilityDeclaracion",
    "CrossReferenceId",
    "CrossRevisionCasillaDivergence",
    "CrossRevisionCasillaDriftSummary",
    "DataBindingDefinition",
    "DeadlineWindowDefinition",
    "DeadlineWindowId",
    "DecimalValue",
    "DependencyClassificationDefinition",
    "DependencyClassificationId",
    "DerivedDisenoCasilla",
    "DisenoCoverageReport",
    "EvidenceTier",
    "EvidenceTierCoverageGate",
    "ExportFieldDefinition",
    "ExportFieldId",
    "ExportLayoutDefinition",
    "ExportLayoutId",
    "ExportRecordDefinition",
    "ExtractionProfileDefinition",
    "ExtractionProfileId",
    "ExtractionTargetDefinition",
    "FormulaDefinition",
    "FormulaExpression",
    "FormulaId",
    "GroiDriver",
    "GroiObservation",
    "GroiOracle",
    "GroiReplayDriver",
    "InputKind",
    "InputKindValue",
    "InvoiceObservation",
    "InvoiceObservationRequirement",
    "IvaLedgerObservation",
    "KeyedBracketEntry",
    "LegalParameter",
    "LegalRefId",
    "LegalReference",
    "LiveCrossReferenceDecision",
    "LiveParityCatalogue",
    "LiveParityOracle",
    "ModelLawCoverageLedger",
    "Modelo202Modality",
    "Modelo202ModalityVerdict",
    "Modelo720RowObservation",
    "ModeloApplicability",
    "ModeloApplicabilityRule",
    "ModeloBindingQueryRow",
    "ModeloBindingsReport",
    "ModeloCasillaRow",
    "ModeloCasillasReport",
    "ModeloDefinition",
    "ModeloDescribeReport",
    "ModeloFilingCapability",
    "ModeloFormulaRow",
    "ModeloFormulasReport",
    "ModeloId",
    "ModeloListReport",
    "ModeloListRow",
    "ModeloRevision",
    "ModeloRevisionSource",
    "ModeloScheduleDefinition",
    "ModeloSource",
    "NoRevisionForPeriodError",
    "OracleEnvironment",
    "OracleId",
    "OracleModeloObservation",
    "OracleSurfaceKind",
    "OssIossLedgerObservation",
    "ParameterDefinition",
    "ParameterId",
    "ParityFieldComparison",
    "ParityResult",
    "ParityScenario",
    "ParityTape",
    "ParityTapeReplayReport",
    "ParityVerdict",
    "ParsedExportFieldValue",
    "ParsedExportPayload",
    "PayerFact",
    "ProfilePredicateDefinition",
    "RecordDesignField",
    "RecordDesignSheet",
    "RecordId",
    "RefundOperationObservation",
    "RegistryCalculationEntry",
    "RegistryCalculationResult",
    "RegistryCatalogues",
    "RegistryCoverageAudit",
    "RegistryError",
    "RegistryFiledStateComparison",
    "RegistryFoldRequirement",
    "RegistryLoadError",
    "RegistryModeloObservation",
    "RegistryQueryService",
    "RegistryRoundingCode",
    "RegistrySnapshot",
    "RegistrySnapshotError",
    "RegistrySnapshotRef",
    "RegistryValidationError",
    "RegistryValidator",
    "RegistryVerificationPolicy",
    "RelatedPartyOperationObservation",
    "RelationId",
    "RemoteOperation",
    "RemoteStateGuardPolicy",
    "RemoteStateGuardResult",
    "RentaGastoObservationProtocol",
    "RentaIncomeObservationProtocol",
    "RentaWebOpenDisplayOverride",
    "RentaWebOpenDriver",
    "RentaWebOpenLivePayload",
    "RentaWebOpenObservation",
    "RentaWebOpenOracle",
    "RentaWebOpenReplayDriver",
    "RentaWebOpenSyntheticProfile",
    "ResolvedConstruct",
    "ResolvedConstructMember",
    "ResolvedExportLayout",
    "RevisionId",
    "SourceRefId",
    "SourceReference",
    "SupportRemovalDecisionDefinition",
    "SupportRemovalDecisionId",
    "SyntheticInputSet",
    "SyntheticInputValue",
    "TaxRoute",
    "ValidatedRegistryAuthority",
    "VerificationExpectationDefinition",
    "VerificationExpectationId",
    "VerificationPredicateDefinition",
    "WithholdingObservation",
    "WithholdingObservationRequirement",
    "WorkbookArtefactReport",
    "WorkbookBackendVerificationReport",
    "WorkbookCellRef",
    "WorkbookConversionReport",
    "WorkbookFixtureId",
    "WorkbookModeloCoverage",
    "WorkbookOutputId",
    "WorkbookParityComparison",
    "WorkbookParityRefId",
    "WorkbookParityReference",
    "WorkbookParityRunReport",
    "WorkbookRunnerAvailability",
    "WorkbookScanOptions",
    "applicable_filing_schedules",
    "assert_formula_workbook_runner_ready",
    "assert_remote_operation_allowed",
    "assert_remote_operations_allowed",
    "assert_workbook_scan_clean",
    "audit_registry_model_law_coverage",
    "audit_registry_oracle_bindings",
    "binding_aggregation_op",
    "binding_row_set_selector",
    "binding_source_casilla_ids",
    "build_censo_modelo_foundation_contract",
    "build_diseno_coverage_report",
    "build_model_law_coverage_ledger",
    "build_snapshot",
    "bundled_authority",
    "calculate_registry_snapshot",
    "calculation_closure_casilla_ids",
    "calculation_closure_legal_refs",
    "calculation_closure_record_design_metadata",
    "casilla_noncanonical_reference_targets",
    "casilla_noncanonical_reference_tokens",
    "casillas_by_id",
    "censo_modelo_ownership",
    "censo_modelo_ownership_map",
    "collect_applicability_declarations",
    "collect_orphan_oracle_ids",
    "compare_calculation_to_filed_observation",
    "compare_registry_to_workbook",
    "convert_binary_xls_with_libreoffice",
    "converted_binary_xls_with_libreoffice",
    "counterpart_binding_requirements",
    "declared_casilla_ids",
    "derive_calculation_completeness_casillas",
    "derive_diseno_coverage_casillas",
    "derive_export_layouts_from_bindings",
    "derive_modelo_202_modality",
    "derive_modelo_applicability",
    "derive_tax_route",
    "detect_workbook_runner",
    "discover_modelo_sources",
    "discover_workbooks",
    "enum_consumed_binding_ids",
    "equivalent_renta_web_open_value",
    "evaluate_cross_reference_applicability",
    "evaluate_profile_conditions",
    "evaluate_remote_operation",
    "export_fields_for_casilla",
    "expression_binding_refs",
    "expression_casilla_refs",
    "expression_date_binding_refs",
    "extract_record_design",
    "extract_record_design_pdf",
    "extract_record_design_pdf_bytes",
    "extract_record_design_workbook",
    "fold_observed_requirement_values",
    "fold_sum_or_copy",
    "gather_observed_requirement_values",
    "generate_parity_tape_path",
    "get_censo_modelo_foundation_contract",
    "has_applicability_rule",
    "input_casilla_id_map",
    "inventory_workbook_coverage",
    "invoice_binding_requirements",
    "is_active_censo_modelo",
    "is_registry_id",
    "iter_modelo_applicability_rules",
    "load_catalogue_file",
    "load_legal_parameters_only",
    "load_modelo_directory",
    "load_modelo_file",
    "load_modelo_path",
    "load_modelo_source",
    "load_parity_scenario",
    "load_parity_tape",
    "load_registry_tree",
    "materialize_relation_binding_values",
    "modelo_202_modality_from_inputs",
    "parse_export_payload",
    "parse_renta_web_open_live_payload",
    "parse_workbook_cell_ref",
    "previous_filing_observation_requirements",
    "previous_filing_source_reference",
    "profile_condition_matches",
    "read_parameter",
    "register_cross_domain_snapshot_check",
    "relation_aggregation_op",
    "relation_source_requirements",
    "remote_state_policy_from_cross_reference",
    "replay_parity_tape",
    "resolve_atribucion_binding_row_values",
    "resolve_bound_inputs_by_casilla_id",
    "resolve_censo_modelo_foundation",
    "resolve_censo_modelo_work_unit_foundation",
    "resolve_construct",
    "resolve_counterpart_binding_row_values",
    "resolve_counterpart_binding_values",
    "resolve_cross_reference_oracle",
    "resolve_export_layout",
    "resolve_foreign_asset_binding_row_values",
    "resolve_invoice_binding_row_values",
    "resolve_invoice_binding_values",
    "resolve_ledger_iva_aggregation_binding_values",
    "resolve_ledger_oss_aggregation_binding_values",
    "resolve_ledger_renta_expense_aggregation_binding_values",
    "resolve_ledger_renta_gasto_aggregation_binding_values",
    "resolve_ledger_renta_income_aggregation_binding_values",
    "resolve_observed_requirement_value",
    "resolve_previous_filing_binding_values",
    "resolve_refund_binding_row_values",
    "resolve_related_party_binding_row_values",
    "resolve_relation_values",
    "resolve_relation_values_from_observations",
    "resolve_retenciones_aggregation_binding_values",
    "resolve_revision_constructs",
    "resolve_withholding_binding_row_values",
    "resolve_withholding_binding_values",
    "revision_casilla_identity_failures",
    "revision_date_binding_ids",
    "revision_reference_identity_failures",
    "run_parity_scenario",
    "run_registry_workbook_parity",
    "run_workbook_with_excel_com",
    "run_workbook_with_libreoffice",
    "save_parity_scenario",
    "save_parity_tape",
    "scan_workbook",
    "selector_model_for_source",
    "summarize_non_overlapping_cross_revision_casilla_drift",
    "taxpayer_model_is_declared",
    "undeclared_casilla_ids",
    "unsupported_ledger_iva_observations",
    "unsupported_ledger_oss_observations",
    "unsupported_ledger_renta_expense_observations",
    "unsupported_ledger_renta_gasto_observations",
    "unsupported_ledger_renta_income_observations",
    "validate_invoice_binding_definition",
    "validate_ledger_iva_aggregation_binding_definition",
    "validate_ledger_oss_aggregation_binding_definition",
    "validate_ledger_renta_expense_aggregation_binding_definition",
    "validate_ledger_renta_gasto_aggregation_binding_definition",
    "validate_ledger_renta_income_aggregation_binding_definition",
    "validate_renta_web_open_expected_casilla_ids",
    "validate_renta_web_open_expected_casilla_values",
    "validate_retenciones_aggregation_binding",
    "validated_casilla_id",
    "validated_casilla_id_map",
    "verify_legal_catalogue",
    "verify_legal_reference",
    "verify_source_catalogue",
    "verify_source_file",
    "verify_workbook_backend",
    "withholding_binding_requirements",
]
