"""Registry-backed AEAT legal calculation authority."""

from __future__ import annotations

from ._bindings import (
    RegistryFilingObservation,
    RegistryFilingObservationRequirement,
    previous_filing_observation_requirements,
    resolve_bound_casilla_inputs,
    resolve_previous_filing_binding_values,
)
from ._coverage import EvidenceTierCoverageGate, ModelLawCoverageLedger, build_model_law_coverage_ledger
from ._errors import RegistryError, RegistryLoadError, RegistrySnapshotError, RegistryValidationError
from ._export import ResolvedExportLayout, export_fields_for_casilla, resolve_export_layout
from ._export_parse import ParsedExportFieldValue, ParsedExportPayload, parse_export_payload
from ._formula_runtime import RegistryCalculationEntry, RegistryCalculationResult, calculate_registry_snapshot
from ._legal import verify_legal_catalogue, verify_legal_reference
from ._loader import load_catalogue_file, load_modelo_file, load_registry_tree
from ._relations import (
    relation_source_requirements,
    resolve_relation_values,
    resolve_relation_values_from_observations,
)
from ._remote_state_guard import (
    RemoteOperation,
    RemoteStateGuardPolicy,
    RemoteStateGuardResult,
    assert_remote_operation_allowed,
    evaluate_remote_operation,
    remote_state_policy_from_cross_reference,
)
from ._runtime_graph import expression_casilla_refs
from ._schedules import applicable_filing_schedules, evaluate_profile_conditions, profile_condition_matches
from ._schema import (
    ApplicationLinkDefinition,
    CasillaDefinition,
    DataBindingDefinition,
    DeadlineApplicabilityCondition,
    DeadlineWindowDefinition,
    EvidenceTier,
    ExportFieldDefinition,
    ExportLayoutDefinition,
    ExportRecordDefinition,
    ExtractionProfileDefinition,
    FilingScheduleDefinition,
    FormulaDefinition,
    FormulaExpression,
    LegalReference,
    LiveCrossReferenceDecision,
    ModeloDefinition,
    ModeloRevision,
    ParameterDefinition,
    ProfilePredicateDefinition,
    RegistryCatalogues,
    RegistrySnapshot,
    SourceReference,
    SupportRemovalDecisionDefinition,
    VerificationExpectationDefinition,
    WorkbookParityReference,
)
from ._snapshot import build_snapshot
from ._sources import verify_source_catalogue, verify_source_file
from ._validate import RegistryValidator
from ._workbook_parity import (
    SyntheticInputSet,
    SyntheticInputValue,
    WorkbookArtefactReport,
    WorkbookBackendVerificationReport,
    WorkbookCellRef,
    WorkbookConversionReport,
    WorkbookModeloCoverage,
    WorkbookParityComparison,
    WorkbookParityRunReport,
    WorkbookRunnerAvailability,
    WorkbookScanOptions,
    assert_formula_workbook_runner_ready,
    assert_workbook_scan_clean,
    compare_registry_to_workbook,
    convert_binary_xls_with_libreoffice,
    detect_workbook_runner,
    discover_workbooks,
    inventory_workbook_coverage,
    parse_workbook_cell_ref,
    run_registry_workbook_parity,
    run_workbook_with_excel_com,
    run_workbook_with_libreoffice,
    scan_workbook,
    verify_workbook_backend,
)

__all__ = [
    "ApplicationLinkDefinition",
    "CasillaDefinition",
    "DataBindingDefinition",
    "DeadlineApplicabilityCondition",
    "DeadlineWindowDefinition",
    "EvidenceTier",
    "EvidenceTierCoverageGate",
    "ExportFieldDefinition",
    "ExportLayoutDefinition",
    "ExportRecordDefinition",
    "ExtractionProfileDefinition",
    "FilingScheduleDefinition",
    "FormulaDefinition",
    "FormulaExpression",
    "LegalReference",
    "LiveCrossReferenceDecision",
    "ModelLawCoverageLedger",
    "ModeloDefinition",
    "ModeloRevision",
    "ParameterDefinition",
    "ParsedExportFieldValue",
    "ParsedExportPayload",
    "ProfilePredicateDefinition",
    "RegistryCalculationEntry",
    "RegistryCalculationResult",
    "RegistryCatalogues",
    "RegistryError",
    "RegistryFilingObservation",
    "RegistryFilingObservationRequirement",
    "RegistryLoadError",
    "RegistrySnapshot",
    "RegistrySnapshotError",
    "RegistryValidationError",
    "RegistryValidator",
    "RemoteOperation",
    "RemoteStateGuardPolicy",
    "RemoteStateGuardResult",
    "ResolvedExportLayout",
    "SourceReference",
    "SupportRemovalDecisionDefinition",
    "SyntheticInputSet",
    "SyntheticInputValue",
    "VerificationExpectationDefinition",
    "WorkbookArtefactReport",
    "WorkbookBackendVerificationReport",
    "WorkbookCellRef",
    "WorkbookConversionReport",
    "WorkbookModeloCoverage",
    "WorkbookParityComparison",
    "WorkbookParityReference",
    "WorkbookParityRunReport",
    "WorkbookRunnerAvailability",
    "WorkbookScanOptions",
    "applicable_filing_schedules",
    "assert_formula_workbook_runner_ready",
    "assert_remote_operation_allowed",
    "assert_workbook_scan_clean",
    "build_model_law_coverage_ledger",
    "build_snapshot",
    "calculate_registry_snapshot",
    "compare_registry_to_workbook",
    "convert_binary_xls_with_libreoffice",
    "detect_workbook_runner",
    "discover_workbooks",
    "evaluate_profile_conditions",
    "evaluate_remote_operation",
    "export_fields_for_casilla",
    "expression_casilla_refs",
    "inventory_workbook_coverage",
    "load_catalogue_file",
    "load_modelo_file",
    "load_registry_tree",
    "parse_export_payload",
    "parse_workbook_cell_ref",
    "previous_filing_observation_requirements",
    "relation_source_requirements",
    "profile_condition_matches",
    "remote_state_policy_from_cross_reference",
    "resolve_bound_casilla_inputs",
    "resolve_export_layout",
    "resolve_previous_filing_binding_values",
    "resolve_relation_values",
    "resolve_relation_values_from_observations",
    "run_registry_workbook_parity",
    "run_workbook_with_excel_com",
    "run_workbook_with_libreoffice",
    "scan_workbook",
    "verify_legal_catalogue",
    "verify_legal_reference",
    "verify_source_catalogue",
    "verify_source_file",
    "verify_workbook_backend",
]
