"""Registry-backed AEAT legal calculation authority.

The public surface re-exports every canonical spine type so callers import from
one location. Core structs include :class:`ModeloDefinition` (static modelo
metadata), :class:`ModeloRevision` (one period-scoped revision of a modelo),
:class:`RegistrySnapshot` (validated snapshot for a single filing context),
:class:`ValidatedRegistryAuthority` (the production access point that loads,
validates, and caches registry material), and :class:`CasillaObservation`
(one typed casilla value carrying full legal and source provenance).

Registry definitions are declarative authority, not application workflow state.
:class:`ValidatedRegistryAuthority` loads bundled TOML, validates cross-file
references, and returns snapshots. :func:`calculate_registry_snapshot` evaluates
the snapshot with already-resolved casilla inputs, binding values, enum binding
values, relation values, and date context. The application source mesh resolves
those values before entering this package.

The facade also exposes the typed binding and observation helpers used by mesh
resolvers: ledger observations, invoice observations, previous-filing carries,
relation materialisation, detail-row folds, unsupported-observation diagnostics,
export layout resolution, applicability rules, verification expectations, live
parity/oracle structures, workbook parity helpers, and registry query reports.

See Also:
    :class:`ValidatedRegistryAuthority`
        Production loader, validator, and snapshot cache for bundled registry
        material.
    :func:`calculate_registry_snapshot`
        Formula runtime entry point that emits
        :class:`CasillaObservation` rows with legal and source provenance.
    :class:`DataBindingDefinition`
        Declarative binding contract resolved by application source owners.
    :mod:`application.aggregation`
        Source-mesh contract that supplies
        :class:`application.aggregation.CalculationSourceResolution`
        envelopes before registry calculation.
    :mod:`application.calculations`
        Prior-filing, relation-prefill, IVA-wallet, and row-set stores that feed
        registry binding and relation inputs.
"""

# ruff: noqa: I001
# Registry identifiers must be re-exported before imports that can re-enter this
# package during validation bootstrap.
from __future__ import annotations

from collections.abc import Callable
from functools import partial
from importlib import import_module
from types import ModuleType
from typing import TYPE_CHECKING

from ....core import FilingProducerKey, FilingProjectionRef
from ._aeat_hosts import REMOTE_READ_SCHEME, canonical_remote_hostname
from ._export_value_policy import (
    ExportValuePolicy,
    ExportValuePolicyValue,
    ParsedExportPolicyValue,
    ParsedExportPolicyWireValue,
    RequiredExportValuePolicyValue,
    coerce_export_value_policy,
    export_value_policy_wire_length,
    normalize_parsed_export_policy_value,
    project_export_value,
    validate_export_wire_value,
)
from ._fixed_width_codec import (
    ExportEncoding,
    ExportJustification,
    ExportPadding,
    FixedWidthRecordRenderError,
    pad_fixed_width_text,
    parse_fixed_width_export_field,
    render_fixed_width_export_field,
    render_fixed_width_export_record_body,
    render_fixed_width_export_record_payload,
    validate_fixed_width_shape,
)
from ._ids import (
    ApplicabilityRuleId,
    ApplicationLinkId,
    BindingId,
    ConstructId,
    CrossReferenceId,
    DeadlineWindowId,
    DependencyClassificationId,
    ExportFieldId,
    ExportLayoutId,
    ExtractionProfileId,
    FormulaId,
    LegalRefId,
    ModeloId,
    OracleId,
    ParameterId,
    RecordId,
    RelationId,
    RevisionId,
    SourceRefId,
    VerificationExpectationId,
    WorkbookFixtureId,
    WorkbookOutputId,
    WorkbookParityRefId,
    is_registry_id,
)

# Applicability is imported after _schema so its transitive import of
# cadrumo.domain.deadlines (which depends on DeadlineWindowDefinition
# exported above) does not race a partially-initialised registry
# namespace.
from ._applicability import (
    ApplicabilityVerdict,
    Modelo202Modality,
    Modelo202ModalityVerdict,
    ModeloApplicability,
    ModeloApplicabilityRule,
    PayerFact,
    TaxRoute,
    derive_modelo_202_modality,
    derive_modelo_applicability,
    derive_not_applicable_source_modelos,
    derive_tax_route,
    derive_taxpayer_files_economic_activity,
    REGISTRY_RESOLVED_APPLICABILITY_MODELOS,
    has_applicability_rule,
    hydrate_applicability_rule,
    iter_modelo_applicability_rules,
    modelo_202_modality_from_inputs,
    resolve_applicability_rule_from_authority,
    taxpayer_model_is_declared,
)
from ._authority import (
    RegistryAuthorityCapture,
    RegistryAuthorityLifecycleObserver,
    RegistryDiagnosticFilingRevision,
    StampedRegistryRelease,
    ValidatedRegistryAuthority,
    bundled_authority,
    bundled_revision_inspection,
    collect_registry_identity_fingerprints,
    derive_filing_revision_classifications,
    load_registry_diagnostic_classification,
    reset_registry_caches,
    stamp_bundled_registry_release,
    UnvalidatedRegistryClassification,
)
from ._deadline_coordinate import (
    DeadlineSemanticCoordinate,
    deadline_semantic_coordinate,
    deadline_window_semantic_coordinates,
)
from ._identity import (
    REGISTRY_IDENTITY_SCHEMA_VERSION,
    REGISTRY_IDENTITY_STAMP_FILENAME,
    RegistryIdentity,
    RegistryIdentityOrigin,
    RegistryIdentityStamp,
    compute_installed_tree_digest,
    compute_walked_tree_digest,
    read_registry_identity_stamp,
    registry_identity_stamp_location,
    resolve_registry_identity,
)
from ._verdict_cache import shipped_verdict_location
from ._bindings import (
    INVOICE_BINDING_SOURCE_KINDS,
    LEDGER_BINDING_SOURCE_KINDS,
    AtributionMemberObservation,
    BindingAggregationOp,
    CasillaObservation,
    CounterpartAggregationObservation,
    CounterpartObservationRequirement,
    CounterpartSourceKind,
    DonativoDonorObservation,
    Gasto193Observation,
    InvoiceObservation,
    Withholding296Observation,
    InvoiceObservationRequirement,
    InventoryProjectionOperation,
    InventorySelector,
    IvaLedgerObservation,
    IvaCompensationAnnualPartitionRequirement,
    M303RegimenSimplificadoAnnualSummaryRequirement,
    Modelo349OperadorClaveTotal,
    Modelo349OperadorTotalsParity,
    Modelo720RowObservation,
    OracleModeloObservation,
    OssIossLedgerObservation,
    ProfileSelector,
    RefundOperationObservation,
    RegistryModeloObservation,
    ImpatriadoIncomeObservationProtocol,
    IrnrIncomeObservationProtocol,
    RelatedPartyOperationObservation,
    RentaGastosPagoFraccionadoObservationProtocol,
    RentaIncomeObservationProtocol,
    WithholdingClaveBreakdown,
    WithholdingObservation,
    WithholdingObservationRequirement,
    WithholdingTotalsParity,
    aggregate_withholding_by_clave,
    binding_aggregation_op,
    bound_casilla_binding_ids,
    binding_source_casilla_ids,
    casillas_by_binding,
    compute_modelo_349_operador_totals_parity,
    compute_withholding_totals_parity,
    counterpart_binding_requirements,
    foreign_asset_binding_row_field,
    invoice_binding_requirements,
    is_m347_declarante_summary_invoice_binding,
    iva_compensation_annual_partition_requirement,
    m303_regimen_simplificado_annual_summary_requirement,
    previous_filing_binding_source_casilla_ids,
    previous_filing_observation_requirements,
    previous_filing_source_reference,
    resolve_atribucion_binding_row_values,
    resolve_available_bound_inputs_by_casilla_id,
    resolve_bound_casilla_binding_value,
    resolve_counterpart_binding_row_values,
    resolve_counterpart_binding_values,
    resolve_donativo_binding_row_values,
    resolve_foreign_asset_binding_row_values,
    resolve_gasto193_binding_row_values,
    resolve_withholding296_binding_row_values,
    resolve_gasto193_binding_values,
    resolve_invoice_binding_row_values,
    resolve_invoice_binding_values,
    resolve_ledger_impatriado_income_aggregation_binding_values,
    resolve_ledger_irnr_income_aggregation_binding_values,
    resolve_ledger_iva_aggregation_binding_values,
    resolve_ledger_oss_aggregation_binding_values,
    resolve_ledger_renta_gastos_estimacion_directa_aggregation_binding_values,
    resolve_ledger_renta_gastos_pago_fraccionado_aggregation_binding_values,
    resolve_ledger_renta_income_aggregation_binding_values,
    resolve_previous_filing_binding_values,
    resolve_refund_binding_row_values,
    resolve_related_party_binding_row_values,
    resolve_retenciones_aggregation_binding_values,
    resolve_withholding_binding_row_values,
    resolve_withholding_binding_values,
    renta_first_slice_binding_target_casillas,
    selector_model_for_source,
    structurally_unroutable_iva_base_categories,
    UngroundedRentaIncome,
    UnroutedLedgerQuantity,
    ungrounded_ledger_renta_income_observations,
    unrouted_ledger_iva_quantities,
    unrouted_ledger_renta_income_quantities,
    unsupported_ledger_impatriado_income_observations,
    unsupported_ledger_irnr_income_observations,
    unsupported_ledger_iva_observations,
    unsupported_ledger_oss_observations,
    unsupported_ledger_renta_gastos_estimacion_directa_observations,
    unsupported_ledger_renta_gastos_pago_fraccionado_observations,
    unsupported_ledger_renta_income_observations,
    validate_invoice_binding_definition,
    validate_ledger_impatriado_income_aggregation_binding_definition,
    validate_ledger_irnr_income_aggregation_binding_definition,
    validate_ledger_iva_aggregation_binding_definition,
    validate_ledger_oss_aggregation_binding_definition,
    validate_ledger_renta_gastos_estimacion_directa_aggregation_binding_definition,
    validate_ledger_renta_gastos_pago_fraccionado_aggregation_binding_definition,
    validate_ledger_renta_income_aggregation_binding_definition,
    validate_retenciones_aggregation_binding,
    withholding_binding_requirements,
)
from ._binding_selector_utils import (
    BindingRowSetSelector,
    BooleanBindingEncodedValue,
    ManualInputRecordFieldSelector,
    binding_row_set_selector,
    boolean_binding_encoded_values,
    manual_input_record_field_selector,
    selector_as_dict,
)
from ._casilla_membership import (
    casilla_noncanonical_reference_targets,
    casilla_noncanonical_reference_tokens,
    casillas_by_id,
    declared_casilla_ids,
    format_noncanonical_casilla_reference,
    undeclared_casilla_ids,
)
from ._profile_grounding import (
    ProfileKeyGrounding,
    binding_profile_keys,
    build_profile_grounding_index,
)
from ._censo_modelos import (
    CENSO_MODELO_ERROR_CODES,
    CENSO_MODELO_EVENT_KINDS,
    CENSO_MODELO_SERVICE_OWNER,
    CensoModeloEventKind,
    CensoModeloFoundationCommand,
    CensoModeloFoundationContract,
    CensoModeloFoundationLogFields,
    CensoModeloFoundationResult,
    CensoModeloOwnership,
    CensoModeloRole,
    build_censo_modelo_foundation_contract,
    censo_modelo_ownership,
    censo_modelo_ownership_map,
    get_censo_modelo_foundation_contract,
    is_active_censo_modelo,
    resolve_censo_modelo_foundation,
    resolve_censo_modelo_work_unit_foundation,
)
from ._classification_coherence import (
    ClassificationCoherenceFinding,
    ClassificationFindingKind,
    DeclaredAxis,
    DeclaredAxisStatus,
    DeclaredAxisUsage,
    ModeloClassificationRow,
    RegistryClassificationAudit,
    audit_bundled_classification_coherence,
    build_classification_coherence_audit,
)
from ._constructs import ResolvedConstruct, ResolvedConstructMember, resolve_construct, resolve_revision_constructs
from ._convenio import (
    ConvenioAuthority,
    ConvenioOverride,
    ConvenioOverrideRow,
    ConvenioTreaty,
    load_convenio_authority,
)
from ._corpus_catalogue import (
    ResolvedRecordDesignBinary,
    resolve_record_design_binary,
    verify_source_catalogue,
    verify_source_file,
)
from ._coverage import (
    REQUIRED_COVERAGE_TIERS,
    ConstructEvidenceKind,
    ConstructEvidenceLedger,
    ConstructEvidenceRow,
    ConstructEvidenceStatus,
    EvidenceTierCoverageGate,
    ModelLawCoverageLedger,
    RegistryConstructEvidenceAudit,
    RegistryCoverageAudit,
    RequiredCoverageTier,
    audit_registry_construct_evidence,
    audit_registry_model_law_coverage,
    build_construct_evidence_ledger,
    build_model_law_coverage_ledger,
)
from ._cross_revision_divergence import CrossRevisionCasillaDivergence
from ._errors import (
    AmbiguousRevisionSelectionError,
    NoRevisionForPeriodError,
    RegistryError,
    RegistryFailureClassification,
    RegistryFailureCondition,
    RegistryLoadError,
    RegistrySnapshotError,
    RegistryValidationError,
)
from ._period_offset_math import same_ejercicio_prior_quarter_anchors
from ._period_selector_match import selector_period_matches_request
from ._export import (
    ResolvedExportLayout,
    clasificar_casillas_oficiales,
    derive_export_layouts_from_bindings,
    fixed_width_record_casilla_ids,
    export_fields_for_casilla,
    export_fields_overlap,
    resolve_export_layout,
)
from ._export_parse import (
    LOGICAL_DICTIONARY_TYPE,
    SINO_DICTIONARY_TYPE,
    XML_DICTIONARY_BOOLEAN_TYPES,
    ParsedExportFieldValue,
    ParsedExportPayload,
    XmlDictionaryEntry,
    parse_export_payload,
    xml_dictionary_entries,
)
from ._filed_state import RegistryFiledStateComparison, compare_calculation_to_filed_observation
from ._verification_tolerance import verification_tolerance_or_exact
from ._formula_runtime import (
    RegistryCalculationEntry,
    RegistryCalculationResult,
    RegistryCalculationUnresolvedOutcome,
    RegistryUnresolvedOutcomeReason,
    calculate_registry_snapshot,
    read_parameter,
)
from ._formula_initial_values import initial_value_casilla_ids
from ._formula_runtime_ops import resolve_keyed_bracket, resolve_parameter
from ._formula_text_inputs import validate_text_input_targets, validated_text_input_casilla_ids
from ._ledger_binding_resolution import screened_quantity_families
from ._m303_differentiated_deduction_projection import (
    M303DifferentiatedDeductionEndpointValue,
    M303DifferentiatedDeductionRowProjection,
    project_m303_differentiated_deduction_rows,
)
from ._m303_exonerado_390_projection import (
    M303Exonerado390FieldProjection,
    M303Exonerado390RecordProjection,
    project_m303_exonerado_390_activity_rows,
)
from ._m303_orden_manifest import (
    check_m303_annual_orden_census_artefact,
    check_m303_annual_orden_manifest,
    collect_m303_annual_orden_fingerprints,
    load_m303_annual_orden_authority,
    render_m303_annual_orden_census_artefact,
    render_m303_annual_orden_manifest,
)
from ._m303_orden_census_artefact import (
    M303_ORDEN_CENSUS_ARTEFACT_FILENAME,
    load_m303_annual_orden_censuses,
    m303_orden_census_artefact_path,
    render_m303_annual_orden_censuses,
)
from ._m303_orden_projection_compiler import compile_m303_annual_orden_projection
from ._m303_orden_projection_models import (
    ActividadOrdenAnualRef,
    M303AnnualOrdenAuthority,
    M303AnnualOrdenProjection,
    M303AnnualOrdenSnapshot,
    M303RegimenSimplificadoSnapshot,
)
from ._m303_orden_raw_models import M303AnnualOrdenRawActivity, M303AnnualOrdenRawModule, M303AnnualOrdenSourceCensus
from ._m303_orden_resolution import (
    m303_annual_orden_snapshot_from_projection,
    resolve_m303_regimen_simplificado_snapshot,
)
from ._m303_orden_source import (
    extract_m303_annual_orden_source,
    extract_m303_annual_orden_tables,
    m303_annual_orden_activity_anchor,
    m303_annual_orden_table_text,
)
from ._m303_prorrata_activity_projection import (
    M303ProrrataActivityEndpointValue,
    M303ProrrataActivityRowProjection,
    project_m303_prorrata_activity_rows,
)
from ._m303_regimen_simplificado_projection import (
    M303RegimenSimplificadoFieldProjection,
    M303RegimenSimplificadoRecordProjection,
    project_m303_regimen_simplificado_rows,
    validate_m303_regimen_simplificado_endpoint_epoch,
)
from ._legal import (
    assert_legal_ref_ids_resolve,
    legal_reference_quotes_corpus,
    verify_legal_catalogue,
    verify_legal_catalogue_grounding,
    verify_legal_reference,
    verify_legal_reference_grounding,
)

# ModeloRevisionSource, ModeloSource, discover_modelo_sources and
# load_modelo_source stay imported here (no external caller needs the
# demotion to break) but are not in __all__ below: the raw-loader facade is
# demoted per W01.P04.S10, and the import-hygiene scanner reds a new
# production import of these four (each had zero cross-package production OR
# test consumers, confirmed by an AST scan, not a grep). The remaining raw
# loaders below (load_registry_tree, load_legal_parameters_only,
# load_catalogue_file, load_modelo_directory, load_modelo_file, load_modelo_path,
# clear_fingerprint_cache, collect_registry_tree_fingerprints) keep their facade
# export: each has a documented, per-caller architectural need a narrower or
# authority-routed replacement cannot serve today (import-time cycle avoidance
# for legal/IRPF/IVA parameter readers, a deliberate unvalidated-tree read for
# conformance auditing, or the runtime schema loader's own TTL cache layered
# atop the canonical fingerprint collector).
from ._loader import ModeloRevisionSource as ModeloRevisionSource
from ._loader import ModeloSource as ModeloSource
from ._loader import discover_modelo_sources as discover_modelo_sources
from ._loader import load_modelo_source as load_modelo_source
from ._loader import (
    clear_fingerprint_cache,
    collect_registry_tree_fingerprints,
    load_catalogue_file,
    load_legal_parameters_only,
    load_modelo_directory,
    load_modelo_file,
    load_modelo_path,
    load_registry_tree,
)
from ._modelo_localization import (
    casilla_continuity_locale_key,
    casilla_occurrence_locale_key,
    modelo_locale_key,
    revision_locale_key,
)
from ._observation_fold import (
    fold_observed_requirement_values,
    fold_sum_or_copy,
    gather_observed_requirement_values,
    resolve_observed_requirement_value,
)
from ._queries import (
    BindingSelectorQueryEntry,
    BindingSelectorQueryProjection,
    ModeloBindingQueryRow,
    ModeloBindingsReport,
    ModeloCasillaRow,
    ModeloCasillasReport,
    ModeloDescribeReport,
    ModeloFormulaRow,
    ModeloFormulasReport,
    ModeloListReport,
    ModeloListRow,
    ModeloSupportMatrixReport,
    RegistryQueryService,
    RegistrySourceInventoryReport,
    RegistrySourceInventoryRow,
    RegistrySourceSite,
    relations_by_target_binding,
)
from ._support_matrix import (
    ModeloEntry,
    ModeloPortalCompatibilityRef,
    ModeloRenameRecord,
    RevisionCapabilityProbe,
    build_support_matrix,
    revision_capability_probe,
)
from ._rate_box_partition import (
    RateBoxPartition,
    RateBoxShortfall,
    RateBoxUnscreenedGroup,
    derive_rate_box_partitions,
    rate_box_coverage_shortfalls,
    rate_box_unscreened_groups,
)
from ._record_design import (
    ABSENT_NATURALEZA_TYPE_CODE,
    AUXILIARY_ENVELOPE_HEADER_CONTENT,
    AUXILIARY_ENVELOPE_HEADER_LENGTHS,
    AUXILIARY_ENVELOPE_HEADER_ORDINALS,
    AUXILIARY_ENVELOPE_HEADER_ROWS,
    RecordDesignAuxiliaryEnvelopeHeader,
    RecordDesignAuxiliaryEnvelopeHeaderField,
    RecordDesignAuxiliaryEnvelopeHeaderRole,
    RecordDesignCompositeRelativeClosing,
    RecordDesignCorrection,
    DerivedDisenoCasilla,
    DisenoCoverageReport,
    RecordDesignExtraction,
    RecordDesignField,
    RecordDesignFieldTypeCorrection,
    RecordDesignHeaderCellCorrection,
    RecordDesignSinglePositionCorrection,
    RecordDesignRelativeSuffixMarker,
    RecordDesignSheet,
    RecordDesignSkippedSheet,
    RecordDesignVariableBodyMarker,
    RecordDesignVariableEnvelope,
    RecordDesignVariableTotalMarker,
    build_diseno_coverage_report,
    calculation_closure_casilla_ids,
    calculation_closure_legal_refs,
    calculation_closure_record_design_metadata,
    derive_calculation_completeness_casillas,
    derive_diseno_coverage_casillas,
    extract_record_design,
    validate_auxiliary_envelope_header_contents,
    extract_record_design_pdf,
    extract_record_design_pdf_bytes,
    extract_record_design_workbook,
)
from ._record_spec import ENCODING_ALIAS_MAP
from ._relation_aggregation import relation_aggregation_op
from ._handoffs import (
    RegistryRelationHandoffApplicabilityAudit,
    RegistryRelationHandoffAudit,
    RelationConsumptionChannel,
    RelationHandoffApplicabilityRecord,
    RelationHandoffRecord,
    audit_registry_relation_handoff_applicability,
    audit_registry_relation_handoffs,
    relation_consumption_channels,
    relation_consumption_index,
    relation_is_consumed,
)
from ._handoff_paths import (
    HandoffPathClassification,
    RegistryHandoffPathAudit,
    RelationHandoffPathRecord,
    audit_registry_handoff_paths,
)
from ._relations import (
    RegistryFoldRequirement,
    materialize_relation_binding_values,
    relation_requirement_index,
    relation_source_requirements,
    source_presence_gaps,
    resolve_relation_values,
    resolve_relation_values_from_observations,
)
from ._iva_wallet_relation_targets import (
    MODELO_303_IVA_COMPENSATION_BINDING_ID,
    is_iva_wallet_owned_relation_target,
    iva_wallet_owned_binding_ids_for_revision,
    iva_wallet_owned_relation_targets_for_revision,
)
from ._remote_state_guard import (
    AEAT_WRITE_FORBIDDEN_ACTIONS,
    AEAT_WRITE_FORBIDDEN_VERB_TOKENS,
    RemoteOperation,
    RemoteStateGuardPolicy,
    RemoteStateGuardResult,
    assert_remote_operation_allowed,
    assert_remote_operations_allowed,
    evaluate_remote_operation,
    remote_state_policy_from_cross_reference,
)
from ._runtime_graph import (
    enum_consumed_binding_ids,
    expression_binding_refs,
    expression_casilla_refs,
    expression_date_binding_refs,
    expression_parameter_refs,
    expression_relation_refs,
    input_casilla_id_map,
    revision_date_binding_ids,
)
from ._schedules import applicable_filing_schedules, evaluate_profile_conditions, profile_condition_matches
from ._schema import (
    REVISION_GOVERNANCE_FIELDS,
    REVISION_MANIFEST_ONLY_FIELDS,
    ApplicabilityRuleDefinition,
    ApplicationLinkDefinition,
    BboxAnchorSpec,
    BracketEntry,
    CalculationCompletenessCasilla,
    CalculationCompletenessManifest,
    CasillaContinuidadEvolutionDefinition,
    CasillaConstraints,
    CasillaDefinition,
    CasillaFieldKind,
    CasillaFieldKindValue,
    ConstructDefinition,
    DataBindingDefinition,
    DeadlineWindowDefinition,
    DecimalValue,
    DependencyClassificationDefinition,
    EvidenceTier,
    ExportComputedKey,
    ExportDraftAttribute,
    ExportFieldDefinition,
    ExportLayoutDefinition,
    ExportRecordDefinition,
    ExportSemanticPayloadAxis,
    AuxiliaryEnvelopeHeaderDefinition,
    FilingEnvelopeCloserDerivation,
    FilingEnvelopeDefinition,
    FilingEnvelopePrefixFieldDeclaration,
    FilingEnvelopePrefixRole,
    FilingEnvelopeTotalDerivation,
    ExtractionProfileDefinition,
    ExtractionTargetDefinition,
    FormulaDefinition,
    FormulaExpression,
    KeyedBracketEntry,
    LegalParameter,
    LegalReference,
    LegalRefs,
    LiveCrossReferenceDecision,
    ModeloDefinition,
    ModeloFilingCapability,
    ModeloRevision,
    ModeloScheduleDefinition,
    OneBasedExportOffset,
    ParameterDefinition,
    PeriodSelector,
    ProjectionEndpointDeclaration,
    ProfilePredicateDefinition,
    RegistryCatalogues,
    RegistryExternalLink,
    RegistrySnapshot,
    RegistrySnapshotRef,
    RelationDefinition,
    SourceReference,
    SourceRefs,
    SupportedFilingYearsCatalogue,
    export_semantic_payload_axis,
    WorkbookParityReference,
)
from ._supported_filing_years import SupportedFilingYearGap, audit_supported_filing_years
from ._schema_scalars import registry_scalar_value_type, validate_registry_text_scalar
from ._static_inspection import RegistryRevisionInspection
from ._schema_input_kind import InputKind, InputKindValue
from ._schema_rounding import RegistryRoundingCode
from ._schema_verification import (
    KNOWN_PROFILE_FLAG_ADVISORY_FIELDS,
    KNOWN_VERIFICATION_PREDICATE_OPERATORS,
    VERIFICATION_PREDICATE_SPECIFICATIONS,
    DiscrepancyCause,
    ParsedVerificationPredicate,
    RegistryVerificationPolicy,
    VerificationExpectationDefinition,
    VerificationPredicateDefinition,
    VerificationPredicateOperator,
    VerificationPredicateSpecification,
    VerificationPredicateSyntax,
    fold_reconciliation_total_casilla_ids,
    parse_verification_predicate_expression,
    verification_predicate_operator_name,
)

# build_snapshot stays imported here but is not in __all__: demoted per
# W01.P04.S34, the same unguarded-entry-point class as the raw-loader family
# S10 already demoted -- it has zero production callers outside this package,
# confirmed by an AST scan, and the import-hygiene scanner reds a new
# production import. Cross-package TEST callers resolve it through the
# tests-support facade (domain.calculations.registry.tests.build_snapshot)
# instead of reaching into this demoted attribute directly, so it stays a
# single resolution point rather than N direct imports of a non-__all__ name.
from ._snapshot import build_snapshot as build_snapshot
from ._snapshot_coordinate import registry_snapshot_id, registry_snapshot_id_for
from ._temporal import (
    coverage_assessment_horizon,
    revision_selection_coordinates,
    select_revision,
    select_revision_for_year,
)
from ._validate import RegistryValidator
from ._validate_cross_revision import (
    CrossRevisionCasillaDriftSummary,
    summarize_non_overlapping_cross_revision_casilla_drift,
)
from ._validate_references import (
    CrossDomainSnapshotCheck,
    register_cross_domain_snapshot_check,
)
from ._validate_registry_scope import validate_registry_scope
from ._validate_revision_identity import revision_casilla_identity_failures, revision_reference_identity_failures

if TYPE_CHECKING:
    from ._aeat_nif_iva_oracle import AeatNifIvaCheckerOracle
    from ._checker_oracle_flow import CheckerDriver, CheckerObservation, CheckerReplayDriver
    from ._external_grounding import (
        ExternalGroundingFinding,
        DeclaredScenarioInputs,
        ExternalGroundingFindingKind,
        ExternalOracleEvidence,
        ExternalOracleInventory,
        ManualWorkedExamplePayload,
        OracleAttributionGap,
        RegistryExternalGroundingAudit,
        RevisionExternalGroundingRow,
        UnattributedOraclePayload,
        audit_bundled_external_grounding,
        build_external_grounding_audit,
        load_bundled_external_oracle_inventory,
    )
    from ._groi_oracle import (
        GROI_ORACLE_ID,
        GroiOracle,
    )
    from ._live_parity import (
        CrossReferenceApplicability,
        CrossReferenceApplicabilityDeclaracion,
        LiveParityCatalogue,
        LiveParityOracle,
        OracleEnvironment,
        OracleSurfaceKind,
        ParityFieldComparison,
        ParityResult,
        ParityVerdict,
        audit_registry_oracle_bindings,
        collect_applicability_declarations,
        collect_orphan_oracle_ids,
        evaluate_cross_reference_applicability,
        resolve_cross_reference_oracle,
    )
    from ._renta_web_open_oracle import (
        RentaWebOpenDisplayOverride,
        RentaWebOpenDriver,
        RentaWebOpenLivePayload,
        RentaWebOpenObservation,
        RentaWebOpenOracle,
        RentaWebOpenReplayDriver,
        RentaWebOpenSyntheticProfile,
        equivalent_renta_web_open_value,
        parse_renta_web_open_live_payload,
        serialize_renta_web_open_replay_decimal,
        validate_renta_web_open_expected_casilla_ids,
        validate_renta_web_open_expected_casilla_values,
    )


#: Public name -> owning submodule, resolved on first attribute access.
#:
#: Scoped to the live-network/browser-driven "oracle" tail only (GROI,
#: NIF-IVA, Renta WEB Open, live-parity, external-grounding) -- the rest of
#: this package's ~470 names stay eagerly imported above. Importing
#: ANY name from this package, even the lightweight identifiers in `._ids`,
#: executes this whole `__init__.py` first (Python always runs a package's
#: `__init__.py` before any of its submodules), so a fully-eager facade
#: charges every one of this package's 225+ production consumers for this
#: tail even when they only want a type alias for a pydantic field
#: annotation. Measured: importing `cadrumo.domain.calculations.registry`
#: cost ~1.77M us cumulative, of which the oracle tail
#: (`_aeat_nif_iva_oracle` -> `_checker_oracle_flow` -> `_live_parity` ->
#: `_external_grounding` -> `_loader`/`_compiled_cache`, plus `_groi_oracle`
#: and `_renta_web_open_oracle`) accounted for roughly 330,000-560,000 us of
#: it. None of these six modules performs live-AEAT-participating work (a
#: browser session, an HTTP call, a live-test gate) at IMPORT time -- every
#: `RemoteOperation`/browser reference lives inside a method body, called
#: only when an oracle's `.collect()`/`.planned_operations()` actually runs;
#: deferring the import changes only WHEN the class definitions execute,
#: never WHEN a live call happens. Outside this package, only the three sede
#: live-drivers (`adapters.outbound.aeat.sede._groi_check`/`_nif_iva_check`/
#: `_renta_web_open`) and the `aeat app registry` CLI group
#: (`entrypoints.cli.registry`/`_registry_payloads`) import any of these 45
#: names in production; confirmed by grepping every name individually
#: against the whole tree, not inferred from the module names alone.
_LAZY_EXPORTS: dict[str, str] = {
    "AeatNifIvaCheckerOracle": "._aeat_nif_iva_oracle",
    "CheckerDriver": "._checker_oracle_flow",
    "CheckerObservation": "._checker_oracle_flow",
    "CheckerReplayDriver": "._checker_oracle_flow",
    "ExternalGroundingFinding": "._external_grounding",
    "DeclaredScenarioInputs": "._external_grounding",
    "ExternalGroundingFindingKind": "._external_grounding",
    "ExternalOracleEvidence": "._external_grounding",
    "ExternalOracleInventory": "._external_grounding",
    "ManualWorkedExamplePayload": "._external_grounding",
    "OracleAttributionGap": "._external_grounding",
    "RegistryExternalGroundingAudit": "._external_grounding",
    "RevisionExternalGroundingRow": "._external_grounding",
    "UnattributedOraclePayload": "._external_grounding",
    "audit_bundled_external_grounding": "._external_grounding",
    "build_external_grounding_audit": "._external_grounding",
    "load_bundled_external_oracle_inventory": "._external_grounding",
    "GROI_ORACLE_ID": "._groi_oracle",
    "GroiOracle": "._groi_oracle",
    "CrossReferenceApplicability": "._live_parity",
    "CrossReferenceApplicabilityDeclaracion": "._live_parity",
    "LiveParityCatalogue": "._live_parity",
    "LiveParityOracle": "._live_parity",
    "OracleEnvironment": "._live_parity",
    "OracleSurfaceKind": "._live_parity",
    "ParityFieldComparison": "._live_parity",
    "ParityResult": "._live_parity",
    "ParityVerdict": "._live_parity",
    "audit_registry_oracle_bindings": "._live_parity",
    "collect_applicability_declarations": "._live_parity",
    "collect_orphan_oracle_ids": "._live_parity",
    "evaluate_cross_reference_applicability": "._live_parity",
    "resolve_cross_reference_oracle": "._live_parity",
    "RentaWebOpenDisplayOverride": "._renta_web_open_oracle",
    "RentaWebOpenDriver": "._renta_web_open_oracle",
    "RentaWebOpenLivePayload": "._renta_web_open_oracle",
    "RentaWebOpenObservation": "._renta_web_open_oracle",
    "RentaWebOpenOracle": "._renta_web_open_oracle",
    "RentaWebOpenReplayDriver": "._renta_web_open_oracle",
    "RentaWebOpenSyntheticProfile": "._renta_web_open_oracle",
    "equivalent_renta_web_open_value": "._renta_web_open_oracle",
    "parse_renta_web_open_live_payload": "._renta_web_open_oracle",
    "serialize_renta_web_open_replay_decimal": "._renta_web_open_oracle",
    "validate_renta_web_open_expected_casilla_ids": "._renta_web_open_oracle",
    "validate_renta_web_open_expected_casilla_values": "._renta_web_open_oracle",
}


# Every loader target is a closed literal from the map above.  The attribute
# name selects one of these pre-bound loaders; it never becomes an import path.
_LAZY_MODULE_LOADERS: dict[str, Callable[[], ModuleType]] = {
    module_path: partial(import_module, module_path, __name__) for module_path in frozenset(_LAZY_EXPORTS.values())
}


def __getattr__(name: str) -> object:
    """Resolve one oracle-tail name by importing only the submodule that owns it.

    Every other name in this package's ``__all__`` resolves through the
    ordinary eager imports above and never reaches this hook -- PEP 562's
    ``__getattr__`` fires only for a name Python did not already find as a
    module attribute. The resolved value is written into module globals, so
    only the first access to a lazy name goes through this hook; every later
    one is an ordinary global lookup with no import machinery in the path.

    Ownership is unchanged: every name still has exactly one canonical home
    in this package's ``__all__``, and consumers still import it from here.
    Only WHEN the owning submodule executes has moved.
    """
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    loader = _LAZY_MODULE_LOADERS.get(module_name)
    if loader is None:
        raise RuntimeError(f"missing lazy loader for {module_name!r}")
    value = getattr(loader(), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Report the full public surface, including oracle-tail names not yet resolved."""
    return sorted(set(__all__) | set(globals()))


__all__ = [
    "ABSENT_NATURALEZA_TYPE_CODE",
    "AEAT_WRITE_FORBIDDEN_ACTIONS",
    "AEAT_WRITE_FORBIDDEN_VERB_TOKENS",
    "AUXILIARY_ENVELOPE_HEADER_CONTENT",
    "AUXILIARY_ENVELOPE_HEADER_LENGTHS",
    "AUXILIARY_ENVELOPE_HEADER_ORDINALS",
    "AUXILIARY_ENVELOPE_HEADER_ROWS",
    "CENSO_MODELO_ERROR_CODES",
    "CENSO_MODELO_EVENT_KINDS",
    "CENSO_MODELO_SERVICE_OWNER",
    "ENCODING_ALIAS_MAP",
    "GROI_ORACLE_ID",
    "INVOICE_BINDING_SOURCE_KINDS",
    "KNOWN_PROFILE_FLAG_ADVISORY_FIELDS",
    "KNOWN_VERIFICATION_PREDICATE_OPERATORS",
    "LEDGER_BINDING_SOURCE_KINDS",
    "LOGICAL_DICTIONARY_TYPE",
    "M303_ORDEN_CENSUS_ARTEFACT_FILENAME",
    "MODELO_303_IVA_COMPENSATION_BINDING_ID",
    "REGISTRY_IDENTITY_SCHEMA_VERSION",
    "REGISTRY_IDENTITY_STAMP_FILENAME",
    "REGISTRY_RESOLVED_APPLICABILITY_MODELOS",
    "REMOTE_READ_SCHEME",
    "REQUIRED_COVERAGE_TIERS",
    "REVISION_GOVERNANCE_FIELDS",
    "REVISION_MANIFEST_ONLY_FIELDS",
    "SINO_DICTIONARY_TYPE",
    "VERIFICATION_PREDICATE_SPECIFICATIONS",
    "XML_DICTIONARY_BOOLEAN_TYPES",
    "ActividadOrdenAnualRef",
    "AeatNifIvaCheckerOracle",
    "AmbiguousRevisionSelectionError",
    "ApplicabilityRuleDefinition",
    "ApplicabilityRuleId",
    "ApplicabilityVerdict",
    "ApplicationLinkDefinition",
    "ApplicationLinkId",
    "AtributionMemberObservation",
    "AuxiliaryEnvelopeHeaderDefinition",
    "BboxAnchorSpec",
    "BindingAggregationOp",
    "BindingId",
    "BindingRowSetSelector",
    "BindingSelectorQueryEntry",
    "BindingSelectorQueryProjection",
    "BooleanBindingEncodedValue",
    "BracketEntry",
    "CalculationCompletenessCasilla",
    "CalculationCompletenessManifest",
    "CasillaConstraints",
    "CasillaContinuidadEvolutionDefinition",
    "CasillaDefinition",
    "CasillaFieldKind",
    "CasillaFieldKindValue",
    "CasillaObservation",
    "CensoModeloEventKind",
    "CensoModeloFoundationCommand",
    "CensoModeloFoundationContract",
    "CensoModeloFoundationLogFields",
    "CensoModeloFoundationResult",
    "CensoModeloOwnership",
    "CensoModeloRole",
    "CheckerDriver",
    "CheckerObservation",
    "CheckerReplayDriver",
    "ClassificationCoherenceFinding",
    "ClassificationFindingKind",
    "ConstructDefinition",
    "ConstructEvidenceKind",
    "ConstructEvidenceLedger",
    "ConstructEvidenceRow",
    "ConstructEvidenceStatus",
    "ConstructId",
    "ConvenioAuthority",
    "ConvenioOverride",
    "ConvenioOverrideRow",
    "ConvenioTreaty",
    "CounterpartAggregationObservation",
    "CounterpartObservationRequirement",
    "CounterpartSourceKind",
    "CrossDomainSnapshotCheck",
    "CrossReferenceApplicability",
    "CrossReferenceApplicabilityDeclaracion",
    "CrossReferenceId",
    "CrossRevisionCasillaDivergence",
    "CrossRevisionCasillaDriftSummary",
    "DataBindingDefinition",
    "DeadlineSemanticCoordinate",
    "DeadlineWindowDefinition",
    "DeadlineWindowId",
    "DecimalValue",
    "DeclaredAxis",
    "DeclaredAxisStatus",
    "DeclaredAxisUsage",
    "DeclaredScenarioInputs",
    "DependencyClassificationDefinition",
    "DependencyClassificationId",
    "DerivedDisenoCasilla",
    "DiscrepancyCause",
    "DisenoCoverageReport",
    "DonativoDonorObservation",
    "EvidenceTier",
    "EvidenceTierCoverageGate",
    "ExportComputedKey",
    "ExportDraftAttribute",
    "ExportEncoding",
    "ExportFieldDefinition",
    "ExportFieldId",
    "ExportJustification",
    "ExportLayoutDefinition",
    "ExportLayoutId",
    "ExportPadding",
    "ExportRecordDefinition",
    "ExportSemanticPayloadAxis",
    "ExportValuePolicy",
    "ExportValuePolicyValue",
    "ExternalGroundingFinding",
    "ExternalGroundingFindingKind",
    "ExternalOracleEvidence",
    "ExternalOracleInventory",
    "ExtractionProfileDefinition",
    "ExtractionProfileId",
    "ExtractionTargetDefinition",
    "FilingEnvelopeCloserDerivation",
    "FilingEnvelopeDefinition",
    "FilingEnvelopePrefixFieldDeclaration",
    "FilingEnvelopePrefixRole",
    "FilingEnvelopeTotalDerivation",
    "FilingProducerKey",
    "FilingProjectionRef",
    "FixedWidthRecordRenderError",
    "FormulaDefinition",
    "FormulaExpression",
    "FormulaId",
    "Gasto193Observation",
    "GroiOracle",
    "HandoffPathClassification",
    "ImpatriadoIncomeObservationProtocol",
    "InputKind",
    "InputKindValue",
    "InventoryProjectionOperation",
    "InventorySelector",
    "InvoiceObservation",
    "InvoiceObservationRequirement",
    "IrnrIncomeObservationProtocol",
    "IvaCompensationAnnualPartitionRequirement",
    "IvaLedgerObservation",
    "KeyedBracketEntry",
    "LegalParameter",
    "LegalRefId",
    "LegalReference",
    "LegalRefs",
    "LiveCrossReferenceDecision",
    "LiveParityCatalogue",
    "LiveParityOracle",
    "M303AnnualOrdenAuthority",
    "M303AnnualOrdenProjection",
    "M303AnnualOrdenRawActivity",
    "M303AnnualOrdenRawModule",
    "M303AnnualOrdenSnapshot",
    "M303AnnualOrdenSourceCensus",
    "M303DifferentiatedDeductionEndpointValue",
    "M303DifferentiatedDeductionRowProjection",
    "M303Exonerado390FieldProjection",
    "M303Exonerado390RecordProjection",
    "M303ProrrataActivityEndpointValue",
    "M303ProrrataActivityRowProjection",
    "M303RegimenSimplificadoAnnualSummaryRequirement",
    "M303RegimenSimplificadoFieldProjection",
    "M303RegimenSimplificadoRecordProjection",
    "M303RegimenSimplificadoSnapshot",
    "ManualInputRecordFieldSelector",
    "ManualWorkedExamplePayload",
    "ModelLawCoverageLedger",
    "Modelo202Modality",
    "Modelo202ModalityVerdict",
    "Modelo349OperadorClaveTotal",
    "Modelo349OperadorTotalsParity",
    "Modelo720RowObservation",
    "ModeloApplicability",
    "ModeloApplicabilityRule",
    "ModeloBindingQueryRow",
    "ModeloBindingsReport",
    "ModeloCasillaRow",
    "ModeloCasillasReport",
    "ModeloClassificationRow",
    "ModeloDefinition",
    "ModeloDescribeReport",
    "ModeloEntry",
    "ModeloFilingCapability",
    "ModeloFormulaRow",
    "ModeloFormulasReport",
    "ModeloId",
    "ModeloListReport",
    "ModeloListRow",
    "ModeloPortalCompatibilityRef",
    "ModeloRenameRecord",
    "ModeloRevision",
    "ModeloScheduleDefinition",
    "ModeloSupportMatrixReport",
    "NoRevisionForPeriodError",
    "OneBasedExportOffset",
    "OracleAttributionGap",
    "OracleEnvironment",
    "OracleId",
    "OracleModeloObservation",
    "OracleSurfaceKind",
    "OssIossLedgerObservation",
    "ParameterDefinition",
    "ParameterId",
    "ParityFieldComparison",
    "ParityResult",
    "ParityVerdict",
    "ParsedExportFieldValue",
    "ParsedExportPayload",
    "ParsedExportPolicyValue",
    "ParsedExportPolicyWireValue",
    "ParsedVerificationPredicate",
    "PayerFact",
    "PeriodSelector",
    "ProfileKeyGrounding",
    "ProfilePredicateDefinition",
    "ProfileSelector",
    "ProjectionEndpointDeclaration",
    "RateBoxPartition",
    "RateBoxShortfall",
    "RateBoxUnscreenedGroup",
    "RecordDesignAuxiliaryEnvelopeHeader",
    "RecordDesignAuxiliaryEnvelopeHeaderField",
    "RecordDesignAuxiliaryEnvelopeHeaderRole",
    "RecordDesignCompositeRelativeClosing",
    "RecordDesignCorrection",
    "RecordDesignExtraction",
    "RecordDesignField",
    "RecordDesignFieldTypeCorrection",
    "RecordDesignHeaderCellCorrection",
    "RecordDesignRelativeSuffixMarker",
    "RecordDesignSheet",
    "RecordDesignSinglePositionCorrection",
    "RecordDesignSkippedSheet",
    "RecordDesignVariableBodyMarker",
    "RecordDesignVariableEnvelope",
    "RecordDesignVariableTotalMarker",
    "RecordId",
    "RefundOperationObservation",
    "RegistryAuthorityCapture",
    "RegistryAuthorityLifecycleObserver",
    "RegistryCalculationEntry",
    "RegistryCalculationResult",
    "RegistryCalculationUnresolvedOutcome",
    "RegistryCatalogues",
    "RegistryClassificationAudit",
    "RegistryConstructEvidenceAudit",
    "RegistryCoverageAudit",
    "RegistryDiagnosticFilingRevision",
    "RegistryError",
    "RegistryExternalGroundingAudit",
    "RegistryExternalLink",
    "RegistryFailureClassification",
    "RegistryFailureCondition",
    "RegistryFiledStateComparison",
    "RegistryFoldRequirement",
    "RegistryHandoffPathAudit",
    "RegistryIdentity",
    "RegistryIdentityOrigin",
    "RegistryIdentityStamp",
    "RegistryLoadError",
    "RegistryModeloObservation",
    "RegistryQueryService",
    "RegistryRelationHandoffApplicabilityAudit",
    "RegistryRelationHandoffAudit",
    "RegistryRevisionInspection",
    "RegistryRoundingCode",
    "RegistrySnapshot",
    "RegistrySnapshotError",
    "RegistrySnapshotRef",
    "RegistrySourceInventoryReport",
    "RegistrySourceInventoryRow",
    "RegistrySourceSite",
    "RegistryUnresolvedOutcomeReason",
    "RegistryValidationError",
    "RegistryValidator",
    "RegistryVerificationPolicy",
    "RelatedPartyOperationObservation",
    "RelationConsumptionChannel",
    "RelationDefinition",
    "RelationHandoffApplicabilityRecord",
    "RelationHandoffPathRecord",
    "RelationHandoffRecord",
    "RelationId",
    "RemoteOperation",
    "RemoteStateGuardPolicy",
    "RemoteStateGuardResult",
    "RentaGastosPagoFraccionadoObservationProtocol",
    "RentaIncomeObservationProtocol",
    "RentaWebOpenDisplayOverride",
    "RentaWebOpenDriver",
    "RentaWebOpenLivePayload",
    "RentaWebOpenObservation",
    "RentaWebOpenOracle",
    "RentaWebOpenReplayDriver",
    "RentaWebOpenSyntheticProfile",
    "RequiredCoverageTier",
    "RequiredExportValuePolicyValue",
    "ResolvedConstruct",
    "ResolvedConstructMember",
    "ResolvedExportLayout",
    "ResolvedRecordDesignBinary",
    "RevisionCapabilityProbe",
    "RevisionExternalGroundingRow",
    "RevisionId",
    "SourceRefId",
    "SourceReference",
    "SourceRefs",
    "StampedRegistryRelease",
    "SupportedFilingYearGap",
    "SupportedFilingYearsCatalogue",
    "TaxRoute",
    "UnattributedOraclePayload",
    "UngroundedRentaIncome",
    "UnroutedLedgerQuantity",
    "UnvalidatedRegistryClassification",
    "ValidatedRegistryAuthority",
    "VerificationExpectationDefinition",
    "VerificationExpectationId",
    "VerificationPredicateDefinition",
    "VerificationPredicateOperator",
    "VerificationPredicateSpecification",
    "VerificationPredicateSyntax",
    "Withholding296Observation",
    "WithholdingClaveBreakdown",
    "WithholdingObservation",
    "WithholdingObservationRequirement",
    "WithholdingTotalsParity",
    "WorkbookFixtureId",
    "WorkbookOutputId",
    "WorkbookParityRefId",
    "WorkbookParityReference",
    "XmlDictionaryEntry",
    "aggregate_withholding_by_clave",
    "applicable_filing_schedules",
    "assert_legal_ref_ids_resolve",
    "assert_remote_operation_allowed",
    "assert_remote_operations_allowed",
    "audit_bundled_classification_coherence",
    "audit_bundled_external_grounding",
    "audit_registry_construct_evidence",
    "audit_registry_handoff_paths",
    "audit_registry_model_law_coverage",
    "audit_registry_oracle_bindings",
    "audit_registry_relation_handoff_applicability",
    "audit_registry_relation_handoffs",
    "audit_supported_filing_years",
    "binding_aggregation_op",
    "binding_profile_keys",
    "binding_row_set_selector",
    "binding_source_casilla_ids",
    "boolean_binding_encoded_values",
    "bound_casilla_binding_ids",
    "build_censo_modelo_foundation_contract",
    "build_classification_coherence_audit",
    "build_construct_evidence_ledger",
    "build_diseno_coverage_report",
    "build_external_grounding_audit",
    "build_model_law_coverage_ledger",
    "build_profile_grounding_index",
    "build_support_matrix",
    "bundled_authority",
    "bundled_revision_inspection",
    "calculate_registry_snapshot",
    "calculation_closure_casilla_ids",
    "calculation_closure_legal_refs",
    "calculation_closure_record_design_metadata",
    "canonical_remote_hostname",
    "casilla_continuity_locale_key",
    "casilla_noncanonical_reference_targets",
    "casilla_noncanonical_reference_tokens",
    "casilla_occurrence_locale_key",
    "casillas_by_binding",
    "casillas_by_id",
    "censo_modelo_ownership",
    "censo_modelo_ownership_map",
    "check_m303_annual_orden_census_artefact",
    "check_m303_annual_orden_manifest",
    "clasificar_casillas_oficiales",
    "clear_fingerprint_cache",
    "coerce_export_value_policy",
    "collect_applicability_declarations",
    "collect_m303_annual_orden_fingerprints",
    "collect_orphan_oracle_ids",
    "collect_registry_identity_fingerprints",
    "collect_registry_tree_fingerprints",
    "compare_calculation_to_filed_observation",
    "compile_m303_annual_orden_projection",
    "compute_installed_tree_digest",
    "compute_modelo_349_operador_totals_parity",
    "compute_walked_tree_digest",
    "compute_withholding_totals_parity",
    "counterpart_binding_requirements",
    "coverage_assessment_horizon",
    "deadline_semantic_coordinate",
    "deadline_window_semantic_coordinates",
    "declared_casilla_ids",
    "derive_calculation_completeness_casillas",
    "derive_diseno_coverage_casillas",
    "derive_export_layouts_from_bindings",
    "derive_filing_revision_classifications",
    "derive_modelo_202_modality",
    "derive_modelo_applicability",
    "derive_not_applicable_source_modelos",
    "derive_rate_box_partitions",
    "derive_tax_route",
    "derive_taxpayer_files_economic_activity",
    "enum_consumed_binding_ids",
    "equivalent_renta_web_open_value",
    "evaluate_cross_reference_applicability",
    "evaluate_profile_conditions",
    "evaluate_remote_operation",
    "export_fields_for_casilla",
    "export_fields_overlap",
    "export_semantic_payload_axis",
    "export_value_policy_wire_length",
    "expression_binding_refs",
    "expression_casilla_refs",
    "expression_date_binding_refs",
    "expression_parameter_refs",
    "expression_relation_refs",
    "extract_m303_annual_orden_source",
    "extract_m303_annual_orden_tables",
    "extract_record_design",
    "extract_record_design_pdf",
    "extract_record_design_pdf_bytes",
    "extract_record_design_workbook",
    "fixed_width_record_casilla_ids",
    "fold_observed_requirement_values",
    "fold_reconciliation_total_casilla_ids",
    "fold_sum_or_copy",
    "foreign_asset_binding_row_field",
    "format_noncanonical_casilla_reference",
    "gather_observed_requirement_values",
    "get_censo_modelo_foundation_contract",
    "has_applicability_rule",
    "hydrate_applicability_rule",
    "initial_value_casilla_ids",
    "input_casilla_id_map",
    "invoice_binding_requirements",
    "is_active_censo_modelo",
    "is_iva_wallet_owned_relation_target",
    "is_m347_declarante_summary_invoice_binding",
    "is_registry_id",
    "iter_modelo_applicability_rules",
    "iva_compensation_annual_partition_requirement",
    "iva_wallet_owned_binding_ids_for_revision",
    "iva_wallet_owned_relation_targets_for_revision",
    "legal_reference_quotes_corpus",
    "load_bundled_external_oracle_inventory",
    "load_catalogue_file",
    "load_convenio_authority",
    "load_legal_parameters_only",
    "load_m303_annual_orden_authority",
    "load_m303_annual_orden_censuses",
    "load_modelo_directory",
    "load_modelo_file",
    "load_modelo_path",
    "load_registry_diagnostic_classification",
    "load_registry_tree",
    "m303_annual_orden_activity_anchor",
    "m303_annual_orden_snapshot_from_projection",
    "m303_annual_orden_table_text",
    "m303_orden_census_artefact_path",
    "m303_regimen_simplificado_annual_summary_requirement",
    "manual_input_record_field_selector",
    "materialize_relation_binding_values",
    "modelo_202_modality_from_inputs",
    "modelo_locale_key",
    "normalize_parsed_export_policy_value",
    "pad_fixed_width_text",
    "parse_export_payload",
    "parse_fixed_width_export_field",
    "parse_renta_web_open_live_payload",
    "parse_verification_predicate_expression",
    "previous_filing_binding_source_casilla_ids",
    "previous_filing_observation_requirements",
    "previous_filing_source_reference",
    "profile_condition_matches",
    "project_export_value",
    "project_m303_differentiated_deduction_rows",
    "project_m303_exonerado_390_activity_rows",
    "project_m303_prorrata_activity_rows",
    "project_m303_regimen_simplificado_rows",
    "rate_box_coverage_shortfalls",
    "rate_box_unscreened_groups",
    "read_parameter",
    "read_registry_identity_stamp",
    "register_cross_domain_snapshot_check",
    "registry_identity_stamp_location",
    "registry_scalar_value_type",
    "registry_snapshot_id",
    "registry_snapshot_id_for",
    "relation_aggregation_op",
    "relation_consumption_channels",
    "relation_consumption_index",
    "relation_is_consumed",
    "relation_requirement_index",
    "relation_source_requirements",
    "relations_by_target_binding",
    "remote_state_policy_from_cross_reference",
    "render_fixed_width_export_field",
    "render_fixed_width_export_record_body",
    "render_fixed_width_export_record_payload",
    "render_m303_annual_orden_census_artefact",
    "render_m303_annual_orden_censuses",
    "render_m303_annual_orden_manifest",
    "renta_first_slice_binding_target_casillas",
    "reset_registry_caches",
    "resolve_applicability_rule_from_authority",
    "resolve_atribucion_binding_row_values",
    "resolve_available_bound_inputs_by_casilla_id",
    "resolve_bound_casilla_binding_value",
    "resolve_censo_modelo_foundation",
    "resolve_censo_modelo_work_unit_foundation",
    "resolve_construct",
    "resolve_counterpart_binding_row_values",
    "resolve_counterpart_binding_values",
    "resolve_cross_reference_oracle",
    "resolve_donativo_binding_row_values",
    "resolve_export_layout",
    "resolve_foreign_asset_binding_row_values",
    "resolve_gasto193_binding_row_values",
    "resolve_gasto193_binding_values",
    "resolve_invoice_binding_row_values",
    "resolve_invoice_binding_values",
    "resolve_keyed_bracket",
    "resolve_ledger_impatriado_income_aggregation_binding_values",
    "resolve_ledger_irnr_income_aggregation_binding_values",
    "resolve_ledger_iva_aggregation_binding_values",
    "resolve_ledger_oss_aggregation_binding_values",
    "resolve_ledger_renta_gastos_estimacion_directa_aggregation_binding_values",
    "resolve_ledger_renta_gastos_pago_fraccionado_aggregation_binding_values",
    "resolve_ledger_renta_income_aggregation_binding_values",
    "resolve_m303_regimen_simplificado_snapshot",
    "resolve_observed_requirement_value",
    "resolve_parameter",
    "resolve_previous_filing_binding_values",
    "resolve_record_design_binary",
    "resolve_refund_binding_row_values",
    "resolve_registry_identity",
    "resolve_related_party_binding_row_values",
    "resolve_relation_values",
    "resolve_relation_values_from_observations",
    "resolve_retenciones_aggregation_binding_values",
    "resolve_revision_constructs",
    "resolve_withholding296_binding_row_values",
    "resolve_withholding_binding_row_values",
    "resolve_withholding_binding_values",
    "revision_capability_probe",
    "revision_casilla_identity_failures",
    "revision_date_binding_ids",
    "revision_locale_key",
    "revision_reference_identity_failures",
    "revision_selection_coordinates",
    "same_ejercicio_prior_quarter_anchors",
    "screened_quantity_families",
    "select_revision",
    "select_revision_for_year",
    "selector_as_dict",
    "selector_model_for_source",
    "selector_period_matches_request",
    "serialize_renta_web_open_replay_decimal",
    "shipped_verdict_location",
    "source_presence_gaps",
    "stamp_bundled_registry_release",
    "structurally_unroutable_iva_base_categories",
    "summarize_non_overlapping_cross_revision_casilla_drift",
    "taxpayer_model_is_declared",
    "undeclared_casilla_ids",
    "ungrounded_ledger_renta_income_observations",
    "unrouted_ledger_iva_quantities",
    "unrouted_ledger_renta_income_quantities",
    "unsupported_ledger_impatriado_income_observations",
    "unsupported_ledger_irnr_income_observations",
    "unsupported_ledger_iva_observations",
    "unsupported_ledger_oss_observations",
    "unsupported_ledger_renta_gastos_estimacion_directa_observations",
    "unsupported_ledger_renta_gastos_pago_fraccionado_observations",
    "unsupported_ledger_renta_income_observations",
    "validate_auxiliary_envelope_header_contents",
    "validate_export_wire_value",
    "validate_fixed_width_shape",
    "validate_invoice_binding_definition",
    "validate_ledger_impatriado_income_aggregation_binding_definition",
    "validate_ledger_irnr_income_aggregation_binding_definition",
    "validate_ledger_iva_aggregation_binding_definition",
    "validate_ledger_oss_aggregation_binding_definition",
    "validate_ledger_renta_gastos_estimacion_directa_aggregation_binding_definition",
    "validate_ledger_renta_gastos_pago_fraccionado_aggregation_binding_definition",
    "validate_ledger_renta_income_aggregation_binding_definition",
    "validate_m303_regimen_simplificado_endpoint_epoch",
    "validate_registry_scope",
    "validate_registry_text_scalar",
    "validate_renta_web_open_expected_casilla_ids",
    "validate_renta_web_open_expected_casilla_values",
    "validate_retenciones_aggregation_binding",
    "validate_text_input_targets",
    "validated_text_input_casilla_ids",
    "verification_predicate_operator_name",
    "verification_tolerance_or_exact",
    "verify_legal_catalogue",
    "verify_legal_catalogue_grounding",
    "verify_legal_reference",
    "verify_legal_reference_grounding",
    "verify_source_catalogue",
    "verify_source_file",
    "withholding_binding_requirements",
    "xml_dictionary_entries",
]
