"""Manifest generation and authority loading for annual Orden registry data."""

from __future__ import annotations

from collections.abc import Iterable, Mapping, Sequence
from datetime import date
from pathlib import Path
from typing import TYPE_CHECKING

from ....core import Modelo
from ._errors import RegistryLoadError, RegistryValidationError
from ._ids import LegalRefId, SourceRefId
from ._loader_cache import toml_file_fingerprint
from ._m303_orden_constants import EXTRACTOR_VERSION, SUPPORTED_EJERCICIOS
from ._m303_orden_legal import compile_annual_orden_legal_references
from ._m303_orden_projection_compiler import compile_m303_annual_orden_projection
from ._m303_orden_projection_models import (
    M303AnnualOrdenAuthority,
    M303AnnualOrdenCompilation,
    M303AnnualOrdenGeneratedManifest,
    M303AnnualOrdenGeneratedSource,
    M303AnnualOrdenProjection,
)
from ._m303_orden_raw_models import M303AnnualOrdenSourceCensus
from ._m303_orden_source import extract_m303_annual_orden_source
from ._schema_references import LegalReference, SourceReference

if TYPE_CHECKING:
    from ._schema import ModeloDefinition


def generate_m303_annual_orden_manifest(
    *,
    source_root: Path,
    sources: Mapping[SourceRefId, SourceReference],
) -> M303AnnualOrdenGeneratedManifest:
    """Derive the exact source-integrity manifest from the pinned BOE corpus."""
    generated_sources: list[M303AnnualOrdenGeneratedSource] = []
    for ejercicio in SUPPORTED_EJERCICIOS:
        source = _single_annual_orden_source_for_year(sources, ejercicio=ejercicio)
        census = extract_m303_annual_orden_source(
            ejercicio=ejercicio,
            source=source,
            source_root=source_root,
        )
        generated_sources.append(
            M303AnnualOrdenGeneratedSource(
                ejercicio=ejercicio,
                source_ref=source.id,
                source_content_digest=census.source_content_digest,
                activity_table_count=len(census.activities),
                module_row_count=sum(len(activity.modules) for activity in census.activities),
                module_distribution=tuple(
                    sum(len(activity.modules) == size for activity in census.activities) for size in range(1, 8)
                ),
                agricultural_index_row_count=len(census.agricultural_indexes),
                agricultural_ingreso_a_cuenta_row_count=len(census.agricultural_ingresos_a_cuenta),
                non_agricultural_ingreso_a_cuenta_row_count=len(census.non_agricultural_ingresos_a_cuenta),
                seasonal_index_day_bands=tuple(
                    (item.minimum_days, item.maximum_days) for item in census.seasonal_indexes
                ),
                seasonal_index_coefficients=tuple(item.coefficient for item in census.seasonal_indexes),
                difficult_justification_pct=census.difficult_justification.percentage,
            ),
        )
    return M303AnnualOrdenGeneratedManifest(
        extractor_version=EXTRACTOR_VERSION,
        sources=tuple(generated_sources),
    )


def render_m303_annual_orden_manifest(
    *,
    source_root: Path,
    sources: Mapping[SourceRefId, SourceReference],
) -> str:
    """Render the generated registry artefact in canonical TOML order."""
    manifest = generate_m303_annual_orden_manifest(source_root=source_root, sources=sources)
    lines = [
        "# Generated by dev.registry.m303_orden_anual; do not edit by hand.",
        "[generator]",
        f'extractor_version = "{manifest.extractor_version}"',
        "",
    ]
    for source in manifest.sources:
        lines.extend(
            (
                "[[sources]]",
                f"ejercicio = {source.ejercicio}",
                f'source_ref = "{source.source_ref}"',
                f'source_content_digest = "{source.source_content_digest}"',
                f"activity_table_count = {source.activity_table_count}",
                f"module_row_count = {source.module_row_count}",
                "module_distribution = [" + ", ".join(str(value) for value in source.module_distribution) + "]",
                f"agricultural_index_row_count = {source.agricultural_index_row_count}",
                f"agricultural_ingreso_a_cuenta_row_count = {source.agricultural_ingreso_a_cuenta_row_count}",
                f"non_agricultural_ingreso_a_cuenta_row_count = {source.non_agricultural_ingreso_a_cuenta_row_count}",
                "seasonal_index_day_bands = ["
                + ", ".join(f"[{start}, {end}]" for start, end in source.seasonal_index_day_bands)
                + "]",
                "seasonal_index_coefficients = ["
                + ", ".join(f'"{value}"' for value in source.seasonal_index_coefficients)
                + "]",
                f'difficult_justification_pct = "{source.difficult_justification_pct}"',
                "",
            ),
        )
    return "\n".join(lines)


def check_m303_annual_orden_manifest(
    *,
    manifest_path: Path,
    source_root: Path,
    sources: Mapping[SourceRefId, SourceReference],
) -> M303AnnualOrdenGeneratedManifest:
    """Refuse a missing, manually edited, or stale generated annual Orden artefact."""
    try:
        directory_entries = tuple(manifest_path.parent.iterdir())
    except OSError as exc:
        raise RegistryLoadError(f"annual Orden generated directory cannot be read: {manifest_path.parent}") from exc
    unexpected_entries = tuple(entry for entry in directory_entries if entry.name != manifest_path.name)
    if unexpected_entries:
        names = ", ".join(sorted(entry.name for entry in unexpected_entries))
        raise RegistryLoadError(f"annual Orden generated directory contains unexpected entries: {names}")
    if not manifest_path.is_file():
        raise RegistryLoadError(f"annual Orden generated manifest is missing: {manifest_path}")
    expected = render_m303_annual_orden_manifest(source_root=source_root, sources=sources)
    try:
        actual = manifest_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise RegistryLoadError(f"annual Orden generated manifest cannot be read: {manifest_path}") from exc
    if actual != expected:
        raise RegistryLoadError(f"annual Orden generated manifest is stale: regenerate {manifest_path}")
    return generate_m303_annual_orden_manifest(source_root=source_root, sources=sources)


def load_m303_annual_orden_authority(
    root: Path,
    *,
    source_root: Path,
    modelos: Sequence[ModeloDefinition],
    sources: Mapping[SourceRefId, SourceReference],
) -> M303AnnualOrdenCompilation:
    """Compile source-pinned annual Orden rows and legal provisions into the registry."""
    manifest_path = root.resolve() / "m303_orden_anual" / "manifest.toml"
    manifest = check_m303_annual_orden_manifest(
        manifest_path=manifest_path,
        source_root=source_root,
        sources=sources,
    )
    modelo_303 = _single_m303_modelo(modelos)
    annual_source_refs = frozenset(source.source_ref for source in manifest.sources)
    legal: dict[LegalRefId, LegalReference] = {}
    projections: list[M303AnnualOrdenProjection] = []
    for generated_source in manifest.sources:
        source, census, table_legal_refs = _compile_generated_annual_orden_source(
            generated_source,
            source_root=source_root,
            sources=sources,
        )
        _merge_annual_orden_legal_refs(legal, table_legal_refs.values())
        projections.extend(
            _annual_orden_projections_for_source(
                census=census,
                source=source,
                modelo_303=modelo_303,
                annual_source_refs=annual_source_refs,
                table_legal_refs=table_legal_refs,
            )
        )
    return M303AnnualOrdenCompilation(authority=M303AnnualOrdenAuthority(projections=tuple(projections)), legal=legal)


def _compile_generated_annual_orden_source(
    generated_source: M303AnnualOrdenGeneratedSource,
    *,
    source_root: Path,
    sources: Mapping[SourceRefId, SourceReference],
) -> tuple[SourceReference, M303AnnualOrdenSourceCensus, dict[str, LegalReference]]:
    source = sources.get(generated_source.source_ref)
    if source is None:
        raise RegistryLoadError(f"annual Orden manifest names unknown source {generated_source.source_ref!r}")
    census = extract_m303_annual_orden_source(
        ejercicio=generated_source.ejercicio,
        source=source,
        source_root=source_root,
    )
    _validate_generated_source_matches_census(generated_source, census)
    legal_refs = compile_annual_orden_legal_references(census, source=source)
    return source, census, legal_refs


def _annual_orden_projections_for_source(
    *,
    census: M303AnnualOrdenSourceCensus,
    source: SourceReference,
    modelo_303: ModeloDefinition,
    annual_source_refs: frozenset[SourceRefId],
    table_legal_refs: Mapping[str, LegalReference],
) -> tuple[M303AnnualOrdenProjection, ...]:
    projections: list[M303AnnualOrdenProjection] = []
    for revision in modelo_303.revisions.values():
        if not revision.period_selector.includes_year(census.ejercicio):
            continue
        if source.id not in revision.source_refs:
            raise RegistryValidationError(
                f"Modelo 303 revision {revision.id!r} does not cite annual Orden source {source.id!r}",
            )
        cited_annual_sources = frozenset(revision.source_refs).intersection(annual_source_refs)
        if cited_annual_sources != frozenset({source.id}):
            raise RegistryValidationError(
                f"Modelo 303 revision {revision.id!r} must cite exactly its filing-year annual Orden source",
            )
        projections.append(
            compile_m303_annual_orden_projection(
                census=census,
                registry_revision_id=revision.id,
                legal_refs={identity: legal_ref.id for identity, legal_ref in table_legal_refs.items()},
            ),
        )
    return tuple(projections)


def _merge_annual_orden_legal_refs(
    legal: dict[LegalRefId, LegalReference],
    generated_refs: Iterable[LegalReference],
) -> None:
    for legal_ref in generated_refs:
        if legal_ref.id in legal:
            raise RegistryValidationError(f"annual Orden compiler generated duplicate legal ref {legal_ref.id!r}")
        legal[legal_ref.id] = legal_ref


def collect_m303_annual_orden_fingerprints(root: Path) -> tuple[tuple[str, int, int, str], ...]:
    """Fingerprint the generated manifest and no hand-authored annual rows."""
    directory = root.resolve() / "m303_orden_anual"
    if not directory.is_dir():
        return ()
    return tuple(toml_file_fingerprint(path.resolve()) for path in sorted(directory.glob("*.toml")))


def _single_annual_orden_source_for_year(
    sources: Mapping[SourceRefId, SourceReference],
    *,
    ejercicio: int,
) -> SourceReference:
    filing_start = date(ejercicio, 1, 1)
    filing_end = date(ejercicio, 12, 31)
    candidates = tuple(
        source
        for source in sources.values()
        if source.id.endswith("-iva-authority")
        and source.authority == "boe"
        and source.kind == "instructions"
        and source.applies_from == filing_start
        and source.applies_to == filing_end
    )
    if len(candidates) != 1:
        raise RegistryValidationError(
            f"annual Orden compiler requires exactly one pinned BOE source for ejercicio {ejercicio}, "
            f"got {len(candidates)}",
        )
    return candidates[0]


def _single_m303_modelo(modelos: Sequence[ModeloDefinition]) -> ModeloDefinition:
    candidates = tuple(modelo for modelo in modelos if modelo.id == Modelo.M303)
    if len(candidates) != 1:
        raise RegistryValidationError(f"annual Orden compiler requires exactly one Modelo 303, got {len(candidates)}")
    return candidates[0]


def _validate_generated_source_matches_census(
    generated: M303AnnualOrdenGeneratedSource,
    census: M303AnnualOrdenSourceCensus,
) -> None:
    actual_distribution = tuple(
        sum(len(activity.modules) == size for activity in census.activities) for size in range(1, 8)
    )
    if generated.source_ref != census.source_ref or generated.source_content_digest != census.source_content_digest:
        raise RegistryValidationError("annual Orden generated source no longer matches its pinned source identity")
    if generated.activity_table_count != len(census.activities):
        raise RegistryValidationError("annual Orden generated source activity count no longer matches the BOE HTML")
    if generated.module_row_count != sum(len(activity.modules) for activity in census.activities):
        raise RegistryValidationError("annual Orden generated source module count no longer matches the BOE HTML")
    if generated.module_distribution != actual_distribution:
        raise RegistryValidationError(
            "annual Orden generated source module distribution no longer matches the BOE HTML",
        )
    if generated.agricultural_index_row_count != len(census.agricultural_indexes):
        raise RegistryValidationError(
            "annual Orden generated source agricultural-index count no longer matches the BOE HTML"
        )
    if generated.agricultural_ingreso_a_cuenta_row_count != len(census.agricultural_ingresos_a_cuenta):
        raise RegistryValidationError(
            "annual Orden generated source agricultural ingreso-a-cuenta count no longer matches the BOE HTML",
        )
    if generated.non_agricultural_ingreso_a_cuenta_row_count != len(census.non_agricultural_ingresos_a_cuenta):
        raise RegistryValidationError(
            "annual Orden generated source IAE ingreso-a-cuenta count no longer matches the BOE HTML",
        )
    if generated.seasonal_index_day_bands != tuple(
        (item.minimum_days, item.maximum_days) for item in census.seasonal_indexes
    ) or generated.seasonal_index_coefficients != tuple(item.coefficient for item in census.seasonal_indexes):
        raise RegistryValidationError("annual Orden generated source seasonal indexes no longer match the BOE HTML")
    if generated.difficult_justification_pct != census.difficult_justification.percentage:
        raise RegistryValidationError(
            "annual Orden generated source difficult-justification percentage no longer matches the BOE HTML",
        )
