"""Compiled annual Orden projection and snapshot models."""

from __future__ import annotations

from collections.abc import Mapping
from decimal import Decimal

from pydantic import Field, model_validator

from ....core.identity import ContentDigest
from ....domain.iva import (
    ActividadOrdenAnual,
    ActividadOrdenAnualId,
    AutoridadAgricolaOrdenAnualNoResuelta,
    DificilJustificacionOrdenAnual,
    IndiceTemporadaOrdenAnual,
    M303RegimenSimplificadoScopeDecision,
    PorcentajeIngresoCuentaIaeOrdenAnual,
)
from ._errors import RegistryValidationError
from ._ids import LegalRefId, RevisionId, SourceRefId
from ._m303_orden_constants import (
    EXPECTED_ACTIVITY_COUNT,
    EXPECTED_AGRICULTURAL_AXIS_COUNTS,
    EXPECTED_DIFFICULT_JUSTIFICATION_PCT,
    EXPECTED_MODULE_COUNT,
    EXPECTED_MODULE_DISTRIBUTION_VECTOR,
    EXPECTED_NON_AGRICULTURAL_INGRESO_A_CUENTA_COUNT,
    EXPECTED_SEASONAL_INDEXES,
    EXTRACTOR_VERSION,
    SUPPORTED_EJERCICIOS,
)
from ._schema_base import RegistryModel
from ._schema_references import LegalReference, SourceReference


class ActividadOrdenAnualRef(RegistryModel):
    """Immutable reference to one source-pinned annual-Orden activity row."""

    orden_id: ActividadOrdenAnualId
    ejercicio: int = Field(ge=2000, le=2099)
    registry_revision_id: RevisionId
    source_ref: SourceRefId
    source_content_digest: ContentDigest


class M303AnnualOrdenGeneratedSource(RegistryModel):
    """One source-level invariant emitted by the annual Orden generator."""

    ejercicio: int = Field(ge=2000, le=2099)
    source_ref: SourceRefId
    source_content_digest: ContentDigest
    activity_table_count: int = Field(ge=1)
    module_row_count: int = Field(ge=1)
    module_distribution: tuple[int, ...] = Field(min_length=7, max_length=7)
    agricultural_index_row_count: int = Field(ge=1)
    agricultural_ingreso_a_cuenta_row_count: int = Field(ge=1)
    non_agricultural_ingreso_a_cuenta_row_count: int = Field(ge=1)
    seasonal_index_day_bands: tuple[tuple[int, int], ...] = Field(min_length=3, max_length=3)
    seasonal_index_coefficients: tuple[Decimal, ...] = Field(min_length=3, max_length=3)
    difficult_justification_pct: Decimal = Field(ge=Decimal("0"), le=Decimal("100"))

    @model_validator(mode="after")
    def _is_the_exact_supported_annual_quota_shape(self) -> M303AnnualOrdenGeneratedSource:
        if self.activity_table_count != EXPECTED_ACTIVITY_COUNT:
            raise RegistryValidationError("annual Orden manifest has the wrong activity table count")
        if self.module_row_count != EXPECTED_MODULE_COUNT:
            raise RegistryValidationError("annual Orden manifest has the wrong module row count")
        if self.module_distribution != EXPECTED_MODULE_DISTRIBUTION_VECTOR:
            raise RegistryValidationError("annual Orden manifest has the wrong module distribution")
        expected_agricultural_count = EXPECTED_AGRICULTURAL_AXIS_COUNTS.get(self.ejercicio)
        if (
            expected_agricultural_count is None
            or self.agricultural_index_row_count != expected_agricultural_count
            or self.agricultural_ingreso_a_cuenta_row_count != expected_agricultural_count
        ):
            raise RegistryValidationError("annual Orden manifest has the wrong agricultural axis row count")
        if self.non_agricultural_ingreso_a_cuenta_row_count != EXPECTED_NON_AGRICULTURAL_INGRESO_A_CUENTA_COUNT:
            raise RegistryValidationError("annual Orden manifest has the wrong IAE ingreso-a-cuenta row count")
        if self.seasonal_index_day_bands != tuple((start, end) for start, end, _ in EXPECTED_SEASONAL_INDEXES):
            raise RegistryValidationError("annual Orden manifest has the wrong seasonal index day bands")
        if self.seasonal_index_coefficients != tuple(value for _, _, value in EXPECTED_SEASONAL_INDEXES):
            raise RegistryValidationError("annual Orden manifest has the wrong seasonal index coefficients")
        if self.difficult_justification_pct != EXPECTED_DIFFICULT_JUSTIFICATION_PCT:
            raise RegistryValidationError("annual Orden manifest has the wrong difficult-justification percentage")
        return self


class M303AnnualOrdenGeneratedManifest(RegistryModel):
    """Checked registry artefact that pins the source compiler's exact output."""

    extractor_version: str = Field(min_length=1)
    sources: tuple[M303AnnualOrdenGeneratedSource, ...] = Field(min_length=4, max_length=4)

    @model_validator(mode="after")
    def _has_one_complete_source_per_supported_year(self) -> M303AnnualOrdenGeneratedManifest:
        if self.extractor_version != EXTRACTOR_VERSION:
            raise RegistryValidationError("annual Orden manifest was generated by an incompatible extractor")
        if tuple(item.ejercicio for item in self.sources) != SUPPORTED_EJERCICIOS:
            raise RegistryValidationError(
                "annual Orden manifest must list each supported ejercicio exactly once in order",
            )
        if len({item.source_ref for item in self.sources}) != len(self.sources):
            raise RegistryValidationError("annual Orden manifest cannot reuse a source across annual exercises")
        return self


class M303AnnualOrdenCompilation(RegistryModel):
    """Transient compiler output folded directly onto the registry catalogues."""

    authority: M303AnnualOrdenAuthority
    legal: Mapping[LegalRefId, LegalReference]


class M303AnnualOrdenProjection(RegistryModel):
    """Immutable taxonomy for one Modelo 303 year/revision/source coordinate."""

    ejercicio: int = Field(ge=2000, le=2099)
    registry_revision_id: RevisionId
    source_ref: SourceRefId
    source_content_digest: ContentDigest
    activities: tuple[ActividadOrdenAnual, ...] = Field(min_length=EXPECTED_ACTIVITY_COUNT)
    agricultural_authority: AutoridadAgricolaOrdenAnualNoResuelta
    non_agricultural_ingresos_a_cuenta: tuple[PorcentajeIngresoCuentaIaeOrdenAnual, ...] = Field(min_length=1)
    seasonal_indexes: tuple[IndiceTemporadaOrdenAnual, ...] = Field(min_length=1)
    difficult_justification: DificilJustificacionOrdenAnual

    @model_validator(mode="after")
    def _rows_are_complete_and_year_scoped(self) -> M303AnnualOrdenProjection:
        if len(self.activities) != EXPECTED_ACTIVITY_COUNT:
            raise RegistryValidationError("annual Orden projection is incomplete")
        if any(activity.ejercicio != self.ejercicio for activity in self.activities):
            raise RegistryValidationError("annual Orden activities must match their projection ejercicio")
        ids = tuple(activity.orden_id for activity in self.activities)
        if len(set(ids)) != len(ids):
            raise RegistryValidationError("annual Orden projection contains duplicate orden_id values")
        by_iae: dict[str, list[str | None]] = {}
        for activity in self.activities:
            if activity.kind == "no_agricola" and activity.iae_epigrafe is not None:
                by_iae.setdefault(activity.iae_epigrafe, []).append(activity.auxiliary_activity_indicator)
        for indicators in by_iae.values():
            if len(indicators) > 1 and (None in indicators or len(set(indicators)) != len(indicators)):
                raise RegistryValidationError("annual Orden projection contains ambiguous non-agricultural activity identities")
        if len(self.non_agricultural_ingresos_a_cuenta) != EXPECTED_NON_AGRICULTURAL_INGRESO_A_CUENTA_COUNT:
            raise RegistryValidationError("annual Orden projection has the wrong IAE ingreso-a-cuenta row count")
        seasonal_shape = tuple(
            (item.minimum_days, item.maximum_days, item.coefficient) for item in self.seasonal_indexes
        )
        if seasonal_shape != EXPECTED_SEASONAL_INDEXES:
            raise RegistryValidationError("annual Orden projection has the wrong seasonal index bands")
        return self


class M303AnnualOrdenAuthority(RegistryModel):
    """Compiled annual-Orden projections, retained solely by registry snapshots."""

    projections: tuple[M303AnnualOrdenProjection, ...] = ()

    @classmethod
    def empty(cls) -> M303AnnualOrdenAuthority:
        """Return an explicitly unresolved state; production M303 resolution refuses it."""
        return cls(projections=())

    @model_validator(mode="after")
    def _projection_coordinates_are_unique(self) -> M303AnnualOrdenAuthority:
        coordinates = tuple((item.ejercicio, item.registry_revision_id) for item in self.projections)
        if len(set(coordinates)) != len(coordinates):
            raise RegistryValidationError("annual Orden authority contains ambiguous year/revision projections")
        return self


class M303AnnualOrdenSnapshot(RegistryModel):
    """The source-bound annual Orden resolved for one filing snapshot."""

    ejercicio: int = Field(ge=2000, le=2099)
    registry_revision_id: RevisionId
    source_ref: SourceRefId
    source_content_digest: ContentDigest
    activities: tuple[ActividadOrdenAnual, ...] = Field(min_length=EXPECTED_ACTIVITY_COUNT)
    activity_refs: tuple[ActividadOrdenAnualRef, ...] = Field(min_length=EXPECTED_ACTIVITY_COUNT)
    agricultural_authority: AutoridadAgricolaOrdenAnualNoResuelta
    non_agricultural_ingresos_a_cuenta: tuple[PorcentajeIngresoCuentaIaeOrdenAnual, ...] = Field(min_length=1)
    seasonal_indexes: tuple[IndiceTemporadaOrdenAnual, ...] = Field(min_length=1)
    difficult_justification: DificilJustificacionOrdenAnual

    @model_validator(mode="after")
    def _references_match_the_activity_rows(self) -> M303AnnualOrdenSnapshot:
        if tuple(item.orden_id for item in self.activities) != tuple(item.orden_id for item in self.activity_refs):
            raise RegistryValidationError("annual Orden snapshot refs must exactly match its activity rows")
        expected_coordinate = (
            self.ejercicio,
            self.registry_revision_id,
            self.source_ref,
            self.source_content_digest,
        )
        if any(
            (
                item.ejercicio,
                item.registry_revision_id,
                item.source_ref,
                item.source_content_digest,
            )
            != expected_coordinate
            for item in self.activity_refs
        ):
            raise RegistryValidationError("annual Orden snapshot refs must retain its exact source coordinate")
        if any(
            activity.ejercicio != self.ejercicio or self.source_ref not in activity.source_refs
            for activity in self.activities
        ):
            raise RegistryValidationError("annual Orden snapshot activities must retain its exact source coordinate")
        return self


class M303RegimenSimplificadoSnapshot(RegistryModel):
    """One resolved M303 annual-Orden, scope, and record-design coordinate."""

    scope_decision: M303RegimenSimplificadoScopeDecision
    orden: M303AnnualOrdenSnapshot
    record_design: SourceReference

    @model_validator(mode="after")
    def _requires_complete_s59_coordinates(self) -> M303RegimenSimplificadoSnapshot:
        if self.record_design.kind != "record_design" or self.record_design.record_design_epoch is None:
            raise RegistryValidationError("M303 regimen simplificado snapshot requires an epoch-pinned record design")
        return self
