"""Compiled annual Orden projection and snapshot models."""

from __future__ import annotations

from collections.abc import Mapping
from decimal import Decimal

from pydantic import Field, model_validator

from ....core.identity import ContentDigest
from ....domain.iva import (
    ActividadOrdenAnual,
    ActividadOrdenAnualId,
    AutoridadAgricolaOrdenAnualNoResuelta,
    DificilJustificacionOrdenAnual,
    IndiceTemporadaOrdenAnual,
    M303RegimenSimplificadoScopeDecision,
    PorcentajeIngresoCuentaIaeOrdenAnual,
    ReduccionLorcaOrdenAnual,
)
from ._m303_orden_constants import (
    EXPECTED_ACTIVITY_COUNT,
    EXPECTED_NON_AGRICULTURAL_INGRESO_A_CUENTA_COUNT,
    EXPECTED_SEASONAL_INDEXES,
    EXTRACTOR_VERSION,
)
from ._m303_orden_constants import (
    validate_2022_annual_orden_coordinate as _validate_2022_annual_orden_coordinate,
)
from ._m303_orden_constants import (
    validate_generated_source_axis_shape as _validate_generated_source_axis_shape,
)
from ._m303_orden_constants import (
    validate_generated_source_counts as _validate_generated_source_counts,
)
from .errors import RegistryValidationError
from .ids import LegalRefId, RevisionId, SourceRefId
from .schema_base import RegistryModel
from .schema_references import LegalReference, SourceReference

_M303_2022_RECORD_DESIGN_SOURCE_REF = "aeat-dr-303-2022"
_M303_2022_RECORD_DESIGN_SOURCE_DIGEST = "6648f6b319579e49cd5bfdaae69e7451db75767e7f19da0b90383b25b79b3f60"


def _require_invariant(condition: bool, message: str) -> None:
    if not condition:
        raise RegistryValidationError(message)


class ActividadOrdenAnualRef(RegistryModel):
    """Immutable reference to one source-pinned annual-Orden activity row."""

    orden_id: ActividadOrdenAnualId
    ejercicio: int = Field(ge=2000, le=2099)
    registry_revision_id: RevisionId
    source_ref: SourceRefId
    source_content_digest: ContentDigest


class M303AnnualOrdenGeneratedSource(RegistryModel):
    """One source-level invariant emitted by the annual Orden generator."""

    ejercicio: int = Field(ge=2000, le=2099)
    source_ref: SourceRefId
    source_content_digest: ContentDigest
    activity_table_count: int = Field(ge=1)
    module_row_count: int = Field(ge=1)
    module_distribution: tuple[int, ...] = Field(min_length=7, max_length=7)
    agricultural_index_row_count: int = Field(ge=1)
    agricultural_ingreso_a_cuenta_row_count: int = Field(ge=1)
    non_agricultural_ingreso_a_cuenta_row_count: int = Field(ge=1)
    seasonal_index_day_bands: tuple[tuple[int, int], ...] = Field(min_length=3, max_length=3)
    seasonal_index_coefficients: tuple[Decimal, ...] = Field(min_length=3, max_length=3)
    difficult_justification_pct: Decimal = Field(ge=Decimal("0"), le=Decimal("100"))
    lorca_2022_reduction_pct: Decimal | None = None

    @model_validator(mode="after")
    def _is_the_exact_supported_annual_quota_shape(self) -> M303AnnualOrdenGeneratedSource:
        _validate_generated_source_counts(self)
        _validate_generated_source_axis_shape(self)
        return self


class M303AnnualOrdenGeneratedManifest(RegistryModel):
    """Checked registry artefact that pins the source compiler's exact output."""

    extractor_version: str = Field(min_length=1)
    sources: tuple[M303AnnualOrdenGeneratedSource, ...] = Field(min_length=1)

    @model_validator(mode="after")
    def _has_one_complete_source_per_supported_year(self) -> M303AnnualOrdenGeneratedManifest:
        _require_invariant(
            self.extractor_version == EXTRACTOR_VERSION,
            "annual Orden manifest was generated by an incompatible extractor",
        )
        _require_invariant(
            tuple(item.ejercicio for item in self.sources) == tuple(sorted({item.ejercicio for item in self.sources})),
            "annual Orden manifest must list ejercicios exactly once in ascending order",
        )
        _require_invariant(
            len({item.source_ref for item in self.sources}) == len(self.sources),
            "annual Orden manifest cannot reuse a source across annual exercises",
        )
        return self


class M303AnnualOrdenCompilation(RegistryModel):
    """Transient compiler output folded directly onto the registry catalogues."""

    authority: M303AnnualOrdenAuthority
    legal: Mapping[LegalRefId, LegalReference]


class M303AnnualOrdenProjection(RegistryModel):
    """Immutable taxonomy for one Modelo 303 year/revision/source coordinate."""

    ejercicio: int = Field(ge=2000, le=2099)
    registry_revision_id: RevisionId
    source_ref: SourceRefId
    source_content_digest: ContentDigest
    activities: tuple[ActividadOrdenAnual, ...] = Field(min_length=EXPECTED_ACTIVITY_COUNT)
    agricultural_authority: AutoridadAgricolaOrdenAnualNoResuelta
    non_agricultural_ingresos_a_cuenta: tuple[PorcentajeIngresoCuentaIaeOrdenAnual, ...] = Field(min_length=1)
    seasonal_indexes: tuple[IndiceTemporadaOrdenAnual, ...] = Field(min_length=1)
    difficult_justification: DificilJustificacionOrdenAnual
    lorca_2022_reduction: ReduccionLorcaOrdenAnual | None

    @model_validator(mode="after")
    def _rows_are_complete_and_year_scoped(self) -> M303AnnualOrdenProjection:
        _validate_projection_activity_rows(self)
        _validate_projection_activity_ids(self)
        _validate_projection_iae_identity(self)
        _validate_projection_axis_shape(self)
        _validate_projection_lorca_2022_reduction(self)
        return self


def _validate_projection_activity_rows(projection: M303AnnualOrdenProjection) -> None:
    _require_invariant(
        len(projection.activities) == EXPECTED_ACTIVITY_COUNT,
        "annual Orden projection is incomplete",
    )
    _require_invariant(
        not any(activity.ejercicio != projection.ejercicio for activity in projection.activities),
        "annual Orden activities must match their projection ejercicio",
    )


def _validate_projection_activity_ids(projection: M303AnnualOrdenProjection) -> None:
    ids = tuple(activity.orden_id for activity in projection.activities)
    _require_invariant(
        len(set(ids)) == len(ids),
        "annual Orden projection contains duplicate orden_id values",
    )


def _validate_projection_iae_identity(projection: M303AnnualOrdenProjection) -> None:
    by_iae: dict[str, list[str | None]] = {}
    for activity in projection.activities:
        if activity.kind == "no_agricola" and activity.iae_epigrafe is not None:
            by_iae.setdefault(activity.iae_epigrafe, []).append(activity.auxiliary_activity_indicator)
    for indicators in by_iae.values():
        _require_invariant(
            len(indicators) <= 1 or (None not in indicators and len(set(indicators)) == len(indicators)),
            "annual Orden projection contains ambiguous non-agricultural activity identities",
        )


def _validate_projection_axis_shape(projection: M303AnnualOrdenProjection) -> None:
    seasonal_shape = tuple(
        (item.minimum_days, item.maximum_days, item.coefficient) for item in projection.seasonal_indexes
    )
    _require_invariant(
        len(projection.non_agricultural_ingresos_a_cuenta) == EXPECTED_NON_AGRICULTURAL_INGRESO_A_CUENTA_COUNT,
        "annual Orden projection has the wrong IAE ingreso-a-cuenta row count",
    )
    _require_invariant(
        seasonal_shape == EXPECTED_SEASONAL_INDEXES,
        "annual Orden projection has the wrong seasonal index bands",
    )
    _require_invariant(
        projection.agricultural_authority.annual_orden_source_ref == projection.source_ref,
        "annual Orden agricultural refusal must retain its exact annual source reference",
    )
    if projection.ejercicio == 2022 and (
        projection.agricultural_authority.record_design_source_ref != _M303_2022_RECORD_DESIGN_SOURCE_REF
        or projection.agricultural_authority.record_design_source_content_digest
        != _M303_2022_RECORD_DESIGN_SOURCE_DIGEST
    ):
        raise RegistryValidationError("annual Orden 2022 agricultural refusal must retain its exact AEAT design source")


def _validate_projection_lorca_2022_reduction(projection: M303AnnualOrdenProjection) -> None:
    reduction = projection.lorca_2022_reduction
    if projection.ejercicio == 2022:
        _validate_2022_annual_orden_coordinate(
            ejercicio=projection.ejercicio,
            registry_revision_id=projection.registry_revision_id,
            source_ref=projection.source_ref,
            source_content_digest=projection.source_content_digest,
            scope="projection",
        )
        if reduction is None:
            raise RegistryValidationError("annual Orden 2022 projection lacks its Lorca reduction authority")
        _require_invariant(
            reduction.percentage == Decimal("20"),
            "annual Orden 2022 projection lacks its Lorca reduction authority",
        )
        _require_invariant(
            reduction.source_refs == (projection.source_ref,),
            "annual Orden Lorca reduction must retain its exact source reference",
        )
    elif reduction is not None:
        raise RegistryValidationError("only the 2022 annual Orden projection may carry the Lorca reduction")


class M303AnnualOrdenAuthority(RegistryModel):
    """Compiled annual-Orden projections, retained solely by registry snapshots."""

    projections: tuple[M303AnnualOrdenProjection, ...] = ()

    @classmethod
    def empty(cls) -> M303AnnualOrdenAuthority:
        """Return an explicitly unresolved state; production M303 resolution refuses it."""
        return cls(projections=())

    @model_validator(mode="after")
    def _projection_coordinates_are_unique(self) -> M303AnnualOrdenAuthority:
        coordinates = tuple((item.ejercicio, item.registry_revision_id) for item in self.projections)
        _require_invariant(
            len(set(coordinates)) == len(coordinates),
            "annual Orden authority contains ambiguous year/revision projections",
        )
        return self

    def require_projection(self, *, ejercicio: int, registry_revision_id: RevisionId) -> M303AnnualOrdenProjection:
        """Resolve the sole projection for an exact filing-year/revision coordinate."""
        candidates = tuple(
            item
            for item in self.projections
            if item.ejercicio == ejercicio and item.registry_revision_id == registry_revision_id
        )
        if len(candidates) != 1:
            raise RegistryValidationError(
                "modelo 303 annual Orden authority requires exactly one projection for "
                f"ejercicio {ejercicio} revision {registry_revision_id!r}; found {len(candidates)}",
            )
        return candidates[0]


class M303AnnualOrdenSnapshot(RegistryModel):
    """The source-bound annual Orden resolved for one filing snapshot."""

    ejercicio: int = Field(ge=2000, le=2099)
    registry_revision_id: RevisionId
    source_ref: SourceRefId
    source_content_digest: ContentDigest
    activities: tuple[ActividadOrdenAnual, ...] = Field(min_length=EXPECTED_ACTIVITY_COUNT)
    activity_refs: tuple[ActividadOrdenAnualRef, ...] = Field(min_length=EXPECTED_ACTIVITY_COUNT)
    agricultural_authority: AutoridadAgricolaOrdenAnualNoResuelta
    non_agricultural_ingresos_a_cuenta: tuple[PorcentajeIngresoCuentaIaeOrdenAnual, ...] = Field(min_length=1)
    seasonal_indexes: tuple[IndiceTemporadaOrdenAnual, ...] = Field(min_length=1)
    difficult_justification: DificilJustificacionOrdenAnual
    lorca_2022_reduction: ReduccionLorcaOrdenAnual | None

    @model_validator(mode="after")
    def _references_match_the_activity_rows(self) -> M303AnnualOrdenSnapshot:
        _validate_snapshot_activity_refs(self)
        _validate_snapshot_activity_coordinates(self)
        _validate_snapshot_source_authority(self)
        return self


def _validate_snapshot_activity_refs(snapshot: M303AnnualOrdenSnapshot) -> None:
    _require_invariant(
        tuple(item.orden_id for item in snapshot.activities) == tuple(item.orden_id for item in snapshot.activity_refs),
        "annual Orden snapshot refs must exactly match its activity rows",
    )


def _validate_snapshot_activity_coordinates(snapshot: M303AnnualOrdenSnapshot) -> None:
    expected_coordinate = (
        snapshot.ejercicio,
        snapshot.registry_revision_id,
        snapshot.source_ref,
        snapshot.source_content_digest,
    )
    _require_invariant(
        not any(
            (
                item.ejercicio,
                item.registry_revision_id,
                item.source_ref,
                item.source_content_digest,
            )
            != expected_coordinate
            for item in snapshot.activity_refs
        ),
        "annual Orden snapshot refs must retain its exact source coordinate",
    )
    _require_invariant(
        not any(
            activity.ejercicio != snapshot.ejercicio or snapshot.source_ref not in activity.source_refs
            for activity in snapshot.activities
        ),
        "annual Orden snapshot activities must retain its exact source coordinate",
    )


def _validate_snapshot_source_authority(snapshot: M303AnnualOrdenSnapshot) -> None:
    _validate_snapshot_lorca_2022_reduction(snapshot)
    _require_invariant(
        snapshot.agricultural_authority.annual_orden_source_ref == snapshot.source_ref,
        "annual Orden snapshot agricultural refusal must retain its exact source reference",
    )
    if snapshot.ejercicio == 2022:
        _validate_snapshot_2022_authority(snapshot)


def _validate_snapshot_2022_authority(snapshot: M303AnnualOrdenSnapshot) -> None:
    _validate_2022_annual_orden_coordinate(
        ejercicio=snapshot.ejercicio,
        registry_revision_id=snapshot.registry_revision_id,
        source_ref=snapshot.source_ref,
        source_content_digest=snapshot.source_content_digest,
        scope="snapshot",
    )
    _require_invariant(
        snapshot.agricultural_authority.record_design_source_ref == _M303_2022_RECORD_DESIGN_SOURCE_REF
        and snapshot.agricultural_authority.record_design_source_content_digest
        == _M303_2022_RECORD_DESIGN_SOURCE_DIGEST,
        "annual Orden 2022 snapshot agricultural refusal must retain its exact AEAT design source",
    )


def _validate_snapshot_lorca_2022_reduction(snapshot: M303AnnualOrdenSnapshot) -> None:
    reduction = snapshot.lorca_2022_reduction
    if snapshot.ejercicio == 2022:
        _require_invariant(
            reduction is not None and reduction.percentage == Decimal("20"),
            "annual Orden 2022 snapshot lacks its Lorca reduction authority",
        )
        if reduction is not None:
            _require_invariant(
                reduction.source_refs == (snapshot.source_ref,),
                "annual Orden snapshot Lorca reduction must retain its exact source reference",
            )
    elif reduction is not None:
        raise RegistryValidationError("only the 2022 annual Orden snapshot may carry the Lorca reduction")


class M303RegimenSimplificadoSnapshot(RegistryModel):
    """One resolved M303 annual-Orden, scope, and record-design coordinate."""

    filing_year: int = Field(ge=2000, le=2099)
    registry_revision_id: RevisionId
    scope_decision: M303RegimenSimplificadoScopeDecision
    orden: M303AnnualOrdenSnapshot
    record_design: SourceReference

    @model_validator(mode="after")
    def _coordinates_are_complete_and_source_pinned(self) -> M303RegimenSimplificadoSnapshot:
        _validate_regimen_simplificado_record_design(self)
        _validate_regimen_simplificado_coordinate(self)
        _validate_regimen_simplificado_agricultural_authority(self)
        if self.filing_year == 2022:
            _validate_regimen_simplificado_2022_coordinate(self)
        return self


def _validate_regimen_simplificado_record_design(snapshot: M303RegimenSimplificadoSnapshot) -> None:
    _require_invariant(
        snapshot.record_design.kind == "record_design" and snapshot.record_design.record_design_epoch is not None,
        "M303 regimen simplificado snapshot requires an epoch-pinned record design",
    )


def _validate_regimen_simplificado_coordinate(snapshot: M303RegimenSimplificadoSnapshot) -> None:
    _require_invariant(
        snapshot.filing_year == snapshot.orden.ejercicio
        and snapshot.registry_revision_id == snapshot.orden.registry_revision_id,
        "M303 regimen simplificado snapshot must retain its filing year and revision coordinate",
    )


def _validate_regimen_simplificado_agricultural_authority(snapshot: M303RegimenSimplificadoSnapshot) -> None:
    agricultural = snapshot.orden.agricultural_authority
    _require_invariant(
        agricultural.record_design_source_ref == snapshot.record_design.id
        and agricultural.record_design_source_content_digest == snapshot.record_design.sha256,
        "M303 regimen simplificado snapshot agricultural refusal must retain its resolved record-design source",
    )


def _validate_regimen_simplificado_2022_coordinate(snapshot: M303RegimenSimplificadoSnapshot) -> None:
    _validate_2022_annual_orden_coordinate(
        ejercicio=snapshot.orden.ejercicio,
        registry_revision_id=snapshot.orden.registry_revision_id,
        source_ref=snapshot.orden.source_ref,
        source_content_digest=snapshot.orden.source_content_digest,
        scope="resolved snapshot",
    )
    _require_invariant(
        snapshot.record_design.id == _M303_2022_RECORD_DESIGN_SOURCE_REF
        and snapshot.record_design.sha256 == _M303_2022_RECORD_DESIGN_SOURCE_DIGEST
        and snapshot.record_design.record_design_epoch == "2022",
        "M303 regimen simplificado 2022 snapshot must retain its exact AEAT design source",
    )
