from __future__ import annotations

import pytest

from .....core.casilla_id import validated_casilla_id
from ._verification_chain_support import (
    _COMPUTED_CASILLAS_M390,
    CasillaId,
    Decimal,
    _calculate_engine_values_from_inputs,
    _decimal_inputs_from_extracted_values,
    _parse_extracted_declaracion_values,
)

pytestmark = [pytest.mark.unit, pytest.mark.hex_inbound_adapter]

_M390_CUOTA_DEVENGADA_TOTAL_CASILLA: CasillaId = validated_casilla_id("iva.anual.cuota-devengada-total")
_M390_CUOTA_DEDUCIBLE_TOTAL_CASILLA: CasillaId = validated_casilla_id("iva.anual.cuota-deducible-total")
_M390_RESULTADO_REGIMEN_GENERAL_CASILLA: CasillaId = validated_casilla_id("iva.anual.resultado-regimen-general")
_M390_COMPENSACION_ULTIMO_PERIODO_97_CASILLA: CasillaId = validated_casilla_id(
    "iva.anual.compensacion-ultimo-periodo-97"
)
_M390_COMPENSACION_GENERADA_NO_97_CASILLA: CasillaId = validated_casilla_id(
    "iva.anual.compensacion-generada-ejercicio-no-97"
)
_M390_REPERCUTIDO_GENERAL_CASILLA: CasillaId = validated_casilla_id("iva.anual.repercutido.general")
_M390_REPERCUTIDO_REDUCIDO_CASILLA: CasillaId = validated_casilla_id("iva.anual.repercutido.reducido")
_M390_REPERCUTIDO_SUPER_REDUCIDO_CASILLA: CasillaId = validated_casilla_id("iva.anual.repercutido.super-reducido")
_M390_AUTOREPERCUTIDO_INTRACOMUNITARIA_CASILLA: CasillaId = validated_casilla_id(
    "iva.anual.autorepercutido.intracomunitaria"
)
_M390_SOPORTADO_INTERIORES_CASILLA: CasillaId = validated_casilla_id("iva.anual.soportado.interiores")
_M390_REQUIRED_CASILLAS: tuple[CasillaId, ...] = (
    _M390_CUOTA_DEVENGADA_TOTAL_CASILLA,
    _M390_CUOTA_DEDUCIBLE_TOTAL_CASILLA,
)


@pytest.mark.parametrize(
    "pdf_stem,year",
    [
        ("2022-0A", 2022),
        ("2023-0A", 2023),
    ],
)
def test_verification_chain_m390_engine_recomputes_cuota_devengada_deducible(pdf_stem: str, year: int) -> None:
    """Engine recomputes all three M390 closure casillas and they match the printed values.

    FIXTURE, NOT ORACLE: the specimens are synthetic formula-consistent corpus
    fixtures generated by _generate.py (_Modelo390CorpusFixture) at
    src/cadrumo/tests/fixtures/justificantes/390/. They replaced the
    sanitised-real-form PDFs, whose uniform 1.000,00 placeholder amounts made
    resultado-regimen-general arithmetically inconsistent. The replacement
    amounts are hand-authored and internally consistent; they carry no AEAT
    authority, so the closures below prove the formula DAG sums its own
    operands correctly, not that the totals match AEAT.

    Formula DAG:
      iva.anual.cuota-devengada-total =
          iva.anual.repercutido.general (box 06, 21% regimen ordinario)
          + iva.anual.repercutido.reducido (box 04, 10% regimen ordinario)
          + iva.anual.repercutido.super-reducido (box 02, 4% regimen ordinario)
          + iva.anual.autorepercutido.intracomunitaria (box 26, adq.intracom 21%)

      iva.anual.cuota-deducible-total =
          iva.anual.soportado.interiores (box 49, total cuotas ded. corrientes)
          + iva.anual.autorepercutido.intracomunitaria (box 26, same binding)

      iva.anual.resultado-regimen-general =
          iva.anual.cuota-devengada-total - iva.anual.cuota-deducible-total

    The leaf casillas (boxes 02/04/06/26/49) are extracted via bbox_anchored
    targets in the declaracion_pdf profile and supplied as engine inputs.

    Verdict per casilla (both 2022-0A and 2023-0A specimens):
      iva.anual.cuota-devengada-total  (box 47): VERIFIED
      iva.anual.cuota-deducible-total  (box 64): VERIFIED
      iva.anual.resultado-regimen-general (box 65): VERIFIED
    """
    extracted = _parse_extracted_declaracion_values(modelo="390", fixture_stem=pdf_stem, year=year, period="0A")

    for required_id in _M390_REQUIRED_CASILLAS:
        assert required_id in extracted, (
            f"PARSER-GAP [{pdf_stem}]: closure casilla {required_id!r} "
            f"not in extracted values - parser did not capture it.\n  got: {sorted(extracted)}"
        )

    inputs = _decimal_inputs_from_extracted_values(extracted, excluding=_COMPUTED_CASILLAS_M390)

    _extracted_comp_97 = extracted.get(_M390_COMPENSACION_ULTIMO_PERIODO_97_CASILLA, Decimal("0"))
    _comp_97 = _extracted_comp_97 if isinstance(_extracted_comp_97, Decimal) else Decimal("0")
    _extracted_comp_662 = extracted.get(_M390_COMPENSACION_GENERADA_NO_97_CASILLA, Decimal("0"))
    _comp_662 = _extracted_comp_662 if isinstance(_extracted_comp_662, Decimal) else Decimal("0")
    binding_values = {
        "modelo-390-prev-303-cuota-devengada-total": Decimal("0"),
        "modelo-390-prev-303-cuota-deducible-total": Decimal("0"),
        "modelo-390-prev-303-resultado-regimen-general": Decimal("0"),
        "modelo-390-prev-303-compensacion-ultimo-periodo": _comp_97,
        "modelo-390-prev-303-compensacion-generada-ejercicio-no-97": _comp_662,
    }
    engine_values = _calculate_engine_values_from_inputs(
        modelo="390",
        year=year,
        period="0A",
        label=pdf_stem,
        inputs=inputs,
        binding_values=binding_values,
    )

    extracted_devengada = extracted[_M390_CUOTA_DEVENGADA_TOTAL_CASILLA]
    engine_devengada = engine_values.get(_M390_CUOTA_DEVENGADA_TOTAL_CASILLA)
    assert isinstance(extracted_devengada, Decimal)
    assert engine_devengada is not None, (
        f"FORMULA-MISMATCH [{pdf_stem}]: 'iva.anual.cuota-devengada-total' absent from engine result"
    )
    assert engine_devengada == extracted_devengada, (
        f"FORMULA-MISMATCH [{pdf_stem}]: engine recomputed cuota-devengada-total as "
        f"{engine_devengada!r} but corpus printed form shows {extracted_devengada!r}.\n"
        f"  leaf inputs: repercutido.general={inputs.get(_M390_REPERCUTIDO_GENERAL_CASILLA, Decimal('0'))!r} "
        f"reducido={inputs.get(_M390_REPERCUTIDO_REDUCIDO_CASILLA, Decimal('0'))!r} "
        f"super-reducido={inputs.get(_M390_REPERCUTIDO_SUPER_REDUCIDO_CASILLA, Decimal('0'))!r} "
        f"autorepercutido={inputs.get(_M390_AUTOREPERCUTIDO_INTRACOMUNITARIA_CASILLA, Decimal('0'))!r}"
    )

    extracted_deducible = extracted[_M390_CUOTA_DEDUCIBLE_TOTAL_CASILLA]
    engine_deducible = engine_values.get(_M390_CUOTA_DEDUCIBLE_TOTAL_CASILLA)
    assert isinstance(extracted_deducible, Decimal)
    assert engine_deducible is not None, (
        f"FORMULA-MISMATCH [{pdf_stem}]: 'iva.anual.cuota-deducible-total' absent from engine result"
    )
    assert engine_deducible == extracted_deducible, (
        f"FORMULA-MISMATCH [{pdf_stem}]: engine recomputed cuota-deducible-total as "
        f"{engine_deducible!r} but corpus printed form shows {extracted_deducible!r}.\n"
        f"  leaf inputs: soportado.interiores={inputs.get(_M390_SOPORTADO_INTERIORES_CASILLA, Decimal('0'))!r} "
        f"autorepercutido={inputs.get(_M390_AUTOREPERCUTIDO_INTRACOMUNITARIA_CASILLA, Decimal('0'))!r}"
    )

    engine_resultado = engine_values.get(_M390_RESULTADO_REGIMEN_GENERAL_CASILLA)
    extracted_resultado = extracted.get(_M390_RESULTADO_REGIMEN_GENERAL_CASILLA)
    assert engine_resultado is not None, (
        f"VERIFIED-FAIL [{pdf_stem}]: 'iva.anual.resultado-regimen-general' absent from engine result"
    )
    assert isinstance(extracted_resultado, Decimal), (
        f"VERIFIED-FAIL [{pdf_stem}]: extracted resultado-regimen-general is not Decimal: {extracted_resultado!r}"
    )
    assert engine_resultado == extracted_resultado, (
        f"VERIFIED-FAIL [{pdf_stem}]: engine resultado-regimen-general "
        f"{engine_resultado!r} != extracted printed box65 {extracted_resultado!r}.\n"
        f"  engine devengada={engine_devengada!r} engine deducible={engine_deducible!r}"
    )
