"""Public application facade for modelo work-unit services.

This package is the canonical application-layer import boundary for modelo
CLI transports and cross-package application services. Callers import from
``cadrumo.application.modelo`` instead of private ``_...`` modules so work
selection, registry revision checks, calculation, verification, filing,
export, reconciliation, and storage orchestration stay behind one facade.

Bucket scoping is explicit at the API boundary. Services accept a caller
provided ``bucket_id`` or a resolved work target; CLI modules may derive that
value from the active profile, but the application surface itself does not read
implicit workflow state.

The facade carries :class:`domain.modelos.CalculationRevision` and
:class:`domain.modelos.WorkUnit` through
the operator lifecycle: work-unit creation and addressing, calculation-revision
creation, verification, filing, export, history, reconciliation, registry
discovery, M036 declaration records, IVA-wallet decisions, projections, and
advisory helpers. It also re-exports the status and finding vocabulary used by
those services, including :class:`CalculationRevisionState`,
:class:`ModeloRecordStatus`, :class:`ModeloVerificationFindingKind`, and
:class:`VerificationCompletenessStatus`. ``CalculationRevision``, ``WorkUnit``,
``CalculationRevisionAmendmentKind``, and ``ExternalEvidenceKind`` are
NOT re-exported here; :mod:`domain.modelos` is their sole canonical source.

Verification, filing, and export remain owned by their focused service modules.
:func:`verify_modelo_revision` persists a verification
report for one
:class:`domain.modelos.CalculationRevision`; filing and export then consume the
same persisted revision rather than rebuilding parallel workflow state.

Local filing and external evidence are deliberately separate.
:func:`file_modelo_revision` creates an internal
current :class:`domain.modelos.ModeloRecord` without
:class:`domain.modelos.ExternalEvidence`;
:func:`import_external_filing_evidence` creates the
AEAT-attested evidence baseline, and
:func:`amend_modelo_revision` requires that baseline
before recording a :class:`domain.modelos.CalculationRevisionAmendmentKind`.

See Also:
    :mod:`application.modelo._work_lifecycle`:
        Work-unit creation, listing, rename, discard, and lookup services.
    :mod:`application.modelo._work_addressing`:
        Visible modelo/year/period addressing and exact-id resolution.
    :mod:`application.modelo._calculation_actions`:
        Calculation revision creation, lookup, and completion services.
    :mod:`application.modelo._verification_actions`:
        Verification findings and report persistence for draft revisions.
    :mod:`application.modelo._filing_actions`:
        Local filing-record transitions and verification-report reads.
    :mod:`application.modelo._external_import_actions`:
        External-evidence import path that stamps official AEAT evidence on
        current filing records.
    :mod:`application.modelo._amendment_actions`:
        Amendment path for current externally evidenced filing records.
    :mod:`application.modelo._workflow_gate`:
        Workflow preflight adapter used by verification and filing services.
    :mod:`application.modelo._export`:
        Local official-file export for verified or filed revisions.
"""

from __future__ import annotations

from ...domain.modelos import (
    CalculationRevisionState,
    Modelo184MemberRow,
    Modelo232VinculadaRow,
    Modelo347ContraparteRow,
    Modelo349CountryPrefixContextError,
    Modelo349OperadorRow,
    Modelo349RectificacionRow,
    ModeloDetailRow,
    ModeloError,
    ModeloRecordStatus,
    ModeloVerificationFindingKind,
    ModeloVerificationFindingSeverity,
    VerificationCompletenessStatus,
    validate_m349_country_prefix_context,
    validate_m349_nif_format,
)
from ._action_errors import (
    AmendmentComplementariaLiabilityDecreaseError,
    AmendmentEvidenceMissingError,
    AmendmentKindNotPermittedError,
    AmendmentM303RectificativaMotiveError,
    AmendmentOverrideCasillaError,
    AmendmentTargetStateError,
    AmendmentVerificationRefusedError,
    CalculationRegistryUnavailableError,
    CalculationRevisionNotFoundError,
    CalculationRevisionStateError,
    CasillaProvenanceMissingError,
    ExternalModeloImportError,
    ModeloAggregationBindingError,
    ModeloApplicabilityFilterError,
    ModeloChargeAccountMissingError,
    ModeloCrossPeriodCleanStateError,
    ModeloLocalObservationError,
    ModeloPaymentElectionCapabilityRefusedError,
    ModeloPaymentElectionIncompatibleError,
    ModeloPriorDomiciliationElectionRefusedError,
    ModeloProfileReadinessError,
    ModeloRecordNotFoundError,
    ModeloRefundElectionNotEligibleError,
    ModeloRequiredBindingsMissingError,
    ModeloWorkflowGateError,
    StoredCalculationDriftError,
    VerificationReportNotFoundError,
    WorkUnitAlreadyDiscardedError,
    WorkUnitMutationRefusedError,
    WorkUnitNotFoundError,
    WorkUnitRevisionDivergenceError,
)
from ._amendment_actions import amend_modelo_revision
from ._binding_readiness import profile_resolvable_binding_ids
from ._binding_resolution import DeclarationPeriodInputs, resolve_declaration_period_inputs
from ._borrador_binding import (
    Modelo100BorradorBindingCommand,
    Modelo100BorradorBindingError,
    Modelo100BorradorSourceResolver,
    resolve_modelo_100_borrador_bindings,
)
from ._calculate_input import (
    Modelo202ModalitySummary,
    ModeloAuthorizationAdvisorySummary,
    ModeloWorkCalculationServiceResult,
    WorkCalculateInputBundle,
    apply_calculation_shortcut_inputs,
    authorization_advisory_for_modelo,
    build_work_calculate_input_bundle,
    calculate_modelo_work_revision,
    is_detail_casilla_override_key,
    modelo_202_modality_for_work_unit,
)
from ._calculation_actions import (
    BucketAggregationCalculationResult,
    assert_no_novel_source_kinds,
    calculate_modelo_revision,
    calculate_modelo_revision_from_bucket_aggregation,
    calculate_modelo_revision_from_bucket_aggregation_with_diagnostics,
    get_calculation_revision,
    list_calculation_revisions,
    mark_revision_verificado_completo,
)
from ._calculation_resolution import resolve_calculation_binding_channels
from ._calculation_route import (
    CALCULATION_ROUTE_ENROLLED_SOURCES,
    CALCULATION_ROUTE_PRE_MESH_SOURCES,
    CALCULATION_ROUTE_RESOLVER_OWNERSHIP,
    CALCULATION_ROUTE_SOURCE_DISPOSITIONS,
    CalculationRouteResolverOwnership,
    validate_calculation_route_resolver_ownership,
)
from ._calculation_source_policy import (
    BUCKET_AGGREGATION_LOCK_SOURCES,
    CALLER_OVERRIDABLE_CARRY_SOURCES,
)
from ._data_inventory import (
    DataInventoryCasilla,
    DataInventoryChecklist,
    data_inventory_checklist,
    profile_requirements_for_binding,
)
from ._export import (
    ModeloExportCommand,
    ModeloExportCrossBucketRefusedError,
    ModeloExportNoActiveBucketError,
    ModeloExportOutputPathError,
    ModeloExportResult,
    ModeloExportUnsupportedError,
    export_modelo_revision,
)
from ._external_import_actions import import_external_filing_evidence
from ._filed_revision_observation import (
    APP_FILING_SOURCE_KIND,
    persist_filed_revision_observation,
)
from ._filing_actions import (
    file_modelo_revision,
    get_filing_record,
    get_verification_report,
    list_filing_records,
    list_verification_reports,
)
from ._history import (
    WorkUnitHistory,
    WorkUnitHistoryEvent,
    assemble_work_unit_history,
)
from ._iva_wallet_gate import (
    ModeloIvaWalletReconciliationBlocked,
    ModeloIvaWalletReconciliationBlockedError,
    apply_iva_compensation_decision_binding,
    require_persisted_iva_compensation_decision_matches_revision,
)
from ._iva_wallet_seed import (
    ModeloIvaWalletCorrectionNoRecordError,
    ModeloIvaWalletCorrectionSealedError,
    ModeloIvaWalletOverrideFreshWalletError,
    ModeloIvaWalletOverrideSealedError,
    ModeloIvaWalletSeedError,
    ModeloIvaWalletSeedNegativeAmountError,
    ModeloIvaWalletSeedNoTaxpayerError,
    correct_iva_compensation_period_for_bucket,
    record_iva_compensation_override_for_bucket,
    seed_iva_compensation_period_for_bucket,
)
from ._local_observation_actions import (
    OPERATOR_MANUAL_OBSERVATION_SOURCE_KIND,
    ModeloLocalObservationResult,
    record_operator_local_observation,
)
from ._local_observation_spreadsheet import parse_casilla_value_spreadsheet
from ._m036_lifecycle import (
    M036DeclarationCommand,
    M036DeclarationResult,
    derive_m036_declaration_id,
    list_m036_declarations,
    m036_declaration_object_key,
    read_m036_declaration,
    record_m036_declaration,
)
from ._m145_communication import (
    M145_COMMUNICATION_MODELO,
    M145_COMMUNICATION_PERIOD,
    M145_COMMUNICATION_SERVICE_OWNER,
    M145CommunicationAction,
    M145CommunicationServiceContract,
    build_m145_communication_service_contract,
)
from ._m145_communication_records import (
    M145CommunicationCreateCommand,
    M145CommunicationExportResult,
    M145CommunicationPeriod,
    M145CommunicationRecord,
    M145CommunicationRecordAmbiguousError,
    M145CommunicationRecordExportError,
    M145CommunicationRecordNotFoundError,
    M145CommunicationRecordState,
    M145CommunicationRecordTransitionError,
    M145CommunicationRecordValidationError,
    M145CommunicationServiceError,
    M145CommunicationValidationIssue,
    M145CommunicationValidationIssueKind,
    M145CommunicationValidationResult,
    create_m145_communication_record,
    derive_m145_communication_record_id,
    export_m145_communication_record,
    list_m145_communication_records,
    m145_communication_record_object_key,
    mark_m145_communication_record_delivered_to_payer,
    mark_m145_communication_record_locally_completed,
    read_m145_communication_record,
    validate_m145_communication_record,
)
from ._maritime_preview import (
    ModeloMaritimeExemptionPreview,
    maritime_facts_from_active_profile,
    preview_maritime_exemption_for_active_profile,
)
from ._participation_index_rebuild import (
    ParticipationRebuildStats,
    rebuild_participation_index,
)
from ._preconditions import (
    MODELO_PRECONDITION_PROFILE_REGISTRY,
    MODELO_PRECONDITION_PROFILES,
    ModeloPreconditionFailure,
    build_modelo_precondition_failure,
)
from ._profile_binding import (
    ProfileBindingResolutionError,
    profile_resolved_binding_ids,
    resolve_maternidad_meses,
    resolve_profile_sourced_bindings,
)
from ._profile_export_binding import (
    compose_legal_full_name,
    resolve_export_identity,
    resolve_profile_export_values,
)
from ._profile_readiness_gate import (
    modelo_applicability_refusal,
    modelo_work_profile_baseline_missing_paths,
    modelo_work_profile_baseline_validation_issues,
    modelo_work_profile_preflight_report,
    pre_activity_period_refusal,
    require_existing_profile_baseline_ready_for_modelo_work,
    require_profile_ready_for_modelo_work,
    require_profile_ready_for_work_unit,
)
from ._projection import (
    ModeloCompareDeltaRow,
    ModeloCompareNeedTwoYearsError,
    ModeloCompareNoRevisionsError,
    ModeloCompareNoUsableRevisionsError,
    ModeloCompareNoWorkUnitsError,
    ModeloCompareSection,
    ModeloCompareServiceResult,
    ModeloProjectInvalidDecimalOverrideError,
    ModeloProjectionCasillaObservation,
    ModeloProjectionError,
    ModeloProjectM100Projection,
    ModeloProjectM130Accumulated,
    ModeloProjectNoM130RevisionsError,
    ModeloProjectNoM130UnitsError,
    ModeloProjectServiceResult,
    compare_modelo_years,
    project_modelo_100_from_m130,
)
from ._pulled_filing_reconcile import pulled_filing_divergence_findings
from ._quickfile import (
    QUICKFILE_STAGE_ORDER,
    QuickfileCommand,
    QuickfileResult,
    QuickfileStage,
    QuickfileStageOutcome,
    QuickfileStageStatus,
    run_modelo_quickfile,
)
from ._reconcile import (
    ModeloReconciliationBytesCommand,
    ModeloReconciliationCommand,
    ModeloReconciliationReport,
    ReconciliationCrossBucketRefusedError,
    ReconciliationDeclaracionSourceUnsupportedError,
    ReconciliationEvidenceInvalidError,
    modelo_reconcile,
    modelo_reconcile_bytes,
)
from ._reconcile_casilla import (
    CasillaDivergence,
    CasillaDivergenceKind,
    detect_casilla_divergences,
)
from ._reconcile_population import (
    CasillaPopulationScope,
    resolve_casilla_population_scope,
)
from ._reconciliation_records import (
    ModeloReconciliationAdvisory,
    ModeloReconciliationDiff,
    ModeloReconciliationDiffKind,
    ModeloReconciliationEvidenceKind,
    ModeloReconciliationHistoryEntry,
    ModeloReconciliationRecord,
    ModeloReconciliationRecordRepository,
    ModeloReconciliationVerdict,
    list_modelo_reconciliations,
)
from ._registry_discovery import (
    declared_modelo_period_tokens,
    registry_bindings,
    registry_bindings_for_scope,
    registry_bindings_for_year,
    registry_casilla,
    registry_casilla_for_registry_scope,
    registry_casillas,
    registry_casillas_for_registry_scope,
    registry_casillas_for_scope,
    registry_describe_modelo,
    registry_describe_modelo_for_registry_scope,
    registry_describe_modelo_for_scope,
    registry_formulas,
    registry_formulas_for_registry_scope,
    registry_formulas_for_scope,
    registry_list_modelos,
    registry_modelo_codes,
    registry_support_matrix,
)
from ._result_summary import (
    CalculationResultSummary,
    ResultSummaryRole,
    ResultSummaryRow,
    calculation_result_summary,
)
from ._review_package import (
    ReviewPackageBuildResult,
    ReviewPackageError,
    ReviewPackageIntegrityError,
    ReviewPackageManifest,
    ReviewPackageRevisionStateError,
    ReviewPackageVerification,
    assert_review_package_verifies,
    build_review_package,
    verify_review_package,
)
from ._review_package_collab_audit import (
    emit_collab_feedback_countersign_attached_event,
    emit_collab_package_counter_signed_event,
    emit_collab_package_decrypted_event,
    emit_collab_package_encrypted_event,
    emit_collab_recipient_registered_event,
    emit_collab_recipient_removed_event,
    emit_collab_review_only_workspace_opened_event,
)
from ._review_package_counter_sign import (
    CounterSignedReceipt,
    ReviewPackageCounterSigningError,
    counter_sign_review_package,
    verify_counter_signed_receipt,
)
from ._review_package_feedback import (
    FeedbackCounterSignatureInvalidError,
    FeedbackPackage,
    ImportedFeedback,
    ReviewPackageFeedbackError,
    build_feedback_package,
    decrypt_feedback_package_from_originator_envelope,
    encrypt_feedback_package_for_originator,
    import_feedback_package,
)
from ._review_package_recipient_encryption import (
    RecipientDecryptedPackage,
    RecipientDecryptionError,
    RecipientEncryptedPackage,
    RecipientEncryptionError,
    RecipientEncryptionKeyNotFoundError,
    RecipientEncryptionKeypair,
    RecipientEncryptionPublicKey,
    RecipientPackageExpiredError,
    decrypt_review_package_for_recipient,
    encrypt_review_package_for_recipient,
    ensure_recipient_encryption_keypair,
    load_recipient_encryption_keypair,
    recipient_encryption_public_key,
)
from ._review_package_recipient_registry import (
    RecipientAlreadyRegisteredError,
    RecipientFingerprintRecord,
    RecipientFingerprintRegister,
    RecipientFingerprintRegistryError,
    RecipientFingerprintRegistryRepository,
    RecipientNotRegisteredError,
    public_key_hex_from_raw_bytes,
)
from ._review_package_recipient_replay_guard import (
    ConsumedNonceLedger,
    ConsumedNonceRecord,
    RecipientPackageReplayedError,
    RecipientReplayGuardError,
    RecipientReplayGuardRepository,
)
from ._review_package_review_only_workspace import (
    ReviewOnlyWorkspace,
    ReviewOnlyWorkspaceAuthorityError,
    ReviewOnlyWorkspaceError,
    assert_workspace_permits_official_action,
    open_review_only_workspace,
)
from ._review_package_signing import (
    ReviewPackageSigningError,
    ReviewPackageSigningKeyNotFoundError,
    ReviewPackageSigningKeypair,
    ReviewPackageSigningPublicKey,
    SignedReviewPackage,
    ensure_review_package_signing_keypair,
    load_review_package_signing_keypair,
    review_package_signing_public_key,
    sign_review_package,
    verify_review_package_signature,
)
from ._revision_persistence import persist_filed_revision, require_filing_instance_evidence_for_work_unit
from ._selectors import (
    ModeloCalculationRevisionCandidate,
    ModeloCalculationRevisionDefault,
    ModeloCalculationRevisionSelection,
    ModeloCalculationRevisionSelector,
    ModeloCalculationRevisionSelectorAmbiguousError,
    ModeloCalculationRevisionSelectorError,
    ModeloCalculationRevisionSelectorNotFoundError,
    ModeloCalculationRevisionSelectorStateError,
    ModeloVerifySelector,
    ModeloWorkNoActiveBucketError,
    ModeloWorkResolution,
    ModeloWorkRevisionConflictError,
    ModeloWorkSelectorContradictionError,
    ModeloWorkSelectorError,
    ModeloWorkSelectorRequest,
    ModeloWorkSelectorState,
    ModeloWorkUnitCandidate,
    ModeloWorkUnitNotFoundError,
    ModeloWorkVisibleTargetAmbiguousError,
    active_natural_target_work_units,
    natural_target_work_units,
    resolve_active_natural_modelo_work_unit,
    resolve_modelo_calculation_revision_pick,
    resolve_modelo_work_bucket,
    resolve_modelo_work_unit,
    select_current_verified_revision,
    select_exportable_revision,
    select_modelo_calculation_revision,
)
from ._semantic_role_resolution import casilla_id_for_unique_revision_semantic_role
from ._taxation_comparison import (
    TaxationComparisonError,
    TaxationComparisonResult,
    TaxationRecommendation,
    compare_taxation_for_work_address,
    compare_taxation_for_work_unit,
    compare_taxation_modes,
)
from ._verification_actions import verify_modelo_revision, verify_modelo_revision_with_preconditions
from ._verification_preconditions import (
    ModeloVerificationResult,
    VerificationFindingPreconditionProjection,
    build_verification_precondition_failure,
    project_verification_findings,
)
from ._work_addressing import (
    ModeloExactWorkUnitTarget,
    ModeloResolvedRevisionProjection,
    ModeloResolvedWorkProjection,
    ModeloRevisionPick,
    ModeloVisibleFilingTarget,
    ModeloWorkAddress,
    ModeloWorkAddressNotFoundError,
    ModeloWorkEnsureResult,
    ModeloWorkPeriodTokenError,
    ModeloWorkRegistryYearMismatchError,
    ModeloWorkTarget,
    ensure_modelo_work_unit_for_active_target,
    modelo_work_address_from_operator_target,
    project_modelo_work_target,
    project_modelo_work_unit,
    resolve_exportable_modelo_calculation_revision_address,
    resolve_fileable_modelo_calculation_revision_address,
    resolve_modelo_calculation_revision_address,
    resolve_modelo_revision_for_operator_target,
    resolve_modelo_revision_pick,
    resolve_modelo_work_address,
    resolve_modelo_work_address_unit,
    resolve_modelo_work_target,
    resolve_modelo_work_unit_for_operator_target,
    resolve_modelo_work_unit_id,
    resolve_optional_modelo_work_address,
    resolve_registry_revision_for_work_target,
    resolve_verifiable_modelo_calculation_revision_address,
    work_address_for_modelo_target,
)
from ._work_create_policy import (
    CEDED_AUTONOMIC_MODELO_LOCALE_KEYS,
    CEDED_AUTONOMIC_MODELOS,
    STUB_MODELO_LOCALE_KEYS,
    STUB_ONLY_MODELOS,
    ModeloWorkCreateApplicabilityRefusal,
    ceded_autonomic_modelo_locale_key,
    guard_active_profile_foral_ccaa,
    modelo_work_create_applicability_refusal,
    modelo_work_create_refusal_locale_key,
)
from ._work_lifecycle import (
    ModeloWorkLifecycleContinuation,
    create_work_unit,
    discard_work_unit,
    get_work_unit,
    lifecycle_continuation_for_work_history,
    lifecycle_continuation_for_work_list,
    lifecycle_continuation_for_work_status,
    list_work_units,
    rename_work_unit,
)
from ._work_plazo import (
    ModeloWorkConditionalRecargoPreview,
    ModeloWorkDeadlinePosture,
    modelo_work_deadline_posture,
    validate_modelo_work_deadline_posture,
)
from ._work_review import (
    BlockerRef,
    ModeloWorkBindingOrigin,
    ModeloWorkOriginAnomaly,
    ModeloWorkProgress,
    ModeloWorkProgressDenominator,
    ModeloWorkRelationConsumption,
    ModeloWorkReview,
    ModeloWorkReviewCasilla,
)
from ._work_review_projection import build_modelo_work_review
from ._workflow_gate import build_revision_deadline_window_checker, workflow_period_for_work_unit

__all__ = [
    "APP_FILING_SOURCE_KIND",
    "BUCKET_AGGREGATION_LOCK_SOURCES",
    "CALCULATION_ROUTE_ENROLLED_SOURCES",
    "CALCULATION_ROUTE_PRE_MESH_SOURCES",
    "CALCULATION_ROUTE_RESOLVER_OWNERSHIP",
    "CALCULATION_ROUTE_SOURCE_DISPOSITIONS",
    "CALLER_OVERRIDABLE_CARRY_SOURCES",
    "CEDED_AUTONOMIC_MODELOS",
    "CEDED_AUTONOMIC_MODELO_LOCALE_KEYS",
    "M145_COMMUNICATION_MODELO",
    "M145_COMMUNICATION_PERIOD",
    "M145_COMMUNICATION_SERVICE_OWNER",
    "MODELO_PRECONDITION_PROFILES",
    "MODELO_PRECONDITION_PROFILE_REGISTRY",
    "OPERATOR_MANUAL_OBSERVATION_SOURCE_KIND",
    "QUICKFILE_STAGE_ORDER",
    "STUB_MODELO_LOCALE_KEYS",
    "STUB_ONLY_MODELOS",
    "AmendmentComplementariaLiabilityDecreaseError",
    "AmendmentEvidenceMissingError",
    "AmendmentKindNotPermittedError",
    "AmendmentM303RectificativaMotiveError",
    "AmendmentOverrideCasillaError",
    "AmendmentTargetStateError",
    "AmendmentVerificationRefusedError",
    "BlockerRef",
    "BucketAggregationCalculationResult",
    "CalculationRegistryUnavailableError",
    "CalculationResultSummary",
    "CalculationRevisionNotFoundError",
    "CalculationRevisionState",
    "CalculationRevisionStateError",
    "CalculationRouteResolverOwnership",
    "CasillaDivergence",
    "CasillaDivergenceKind",
    "CasillaPopulationScope",
    "CasillaProvenanceMissingError",
    "ConsumedNonceLedger",
    "ConsumedNonceRecord",
    "CounterSignedReceipt",
    "DataInventoryCasilla",
    "DataInventoryChecklist",
    "DeclarationPeriodInputs",
    "ExternalModeloImportError",
    "FeedbackCounterSignatureInvalidError",
    "FeedbackPackage",
    "ImportedFeedback",
    "M036DeclarationCommand",
    "M036DeclarationResult",
    "M145CommunicationAction",
    "M145CommunicationCreateCommand",
    "M145CommunicationExportResult",
    "M145CommunicationPeriod",
    "M145CommunicationRecord",
    "M145CommunicationRecordAmbiguousError",
    "M145CommunicationRecordExportError",
    "M145CommunicationRecordNotFoundError",
    "M145CommunicationRecordState",
    "M145CommunicationRecordTransitionError",
    "M145CommunicationRecordValidationError",
    "M145CommunicationServiceContract",
    "M145CommunicationServiceError",
    "M145CommunicationValidationIssue",
    "M145CommunicationValidationIssueKind",
    "M145CommunicationValidationResult",
    "Modelo100BorradorBindingCommand",
    "Modelo100BorradorBindingError",
    "Modelo100BorradorSourceResolver",
    "Modelo184MemberRow",
    "Modelo202ModalitySummary",
    "Modelo232VinculadaRow",
    "Modelo347ContraparteRow",
    "Modelo349CountryPrefixContextError",
    "Modelo349OperadorRow",
    "Modelo349RectificacionRow",
    "ModeloAggregationBindingError",
    "ModeloApplicabilityFilterError",
    "ModeloAuthorizationAdvisorySummary",
    "ModeloCalculationRevisionCandidate",
    "ModeloCalculationRevisionDefault",
    "ModeloCalculationRevisionSelection",
    "ModeloCalculationRevisionSelector",
    "ModeloCalculationRevisionSelectorAmbiguousError",
    "ModeloCalculationRevisionSelectorError",
    "ModeloCalculationRevisionSelectorNotFoundError",
    "ModeloCalculationRevisionSelectorStateError",
    "ModeloChargeAccountMissingError",
    "ModeloCompareDeltaRow",
    "ModeloCompareNeedTwoYearsError",
    "ModeloCompareNoRevisionsError",
    "ModeloCompareNoUsableRevisionsError",
    "ModeloCompareNoWorkUnitsError",
    "ModeloCompareSection",
    "ModeloCompareServiceResult",
    "ModeloCrossPeriodCleanStateError",
    "ModeloDetailRow",
    "ModeloError",
    "ModeloExactWorkUnitTarget",
    "ModeloExportCommand",
    "ModeloExportCrossBucketRefusedError",
    "ModeloExportNoActiveBucketError",
    "ModeloExportOutputPathError",
    "ModeloExportResult",
    "ModeloExportUnsupportedError",
    "ModeloIvaWalletCorrectionNoRecordError",
    "ModeloIvaWalletCorrectionSealedError",
    "ModeloIvaWalletOverrideFreshWalletError",
    "ModeloIvaWalletOverrideSealedError",
    "ModeloIvaWalletReconciliationBlocked",
    "ModeloIvaWalletReconciliationBlockedError",
    "ModeloIvaWalletSeedError",
    "ModeloIvaWalletSeedNegativeAmountError",
    "ModeloIvaWalletSeedNoTaxpayerError",
    "ModeloLocalObservationError",
    "ModeloLocalObservationResult",
    "ModeloMaritimeExemptionPreview",
    "ModeloPaymentElectionCapabilityRefusedError",
    "ModeloPaymentElectionIncompatibleError",
    "ModeloPreconditionFailure",
    "ModeloPriorDomiciliationElectionRefusedError",
    "ModeloProfileReadinessError",
    "ModeloProjectInvalidDecimalOverrideError",
    "ModeloProjectM100Projection",
    "ModeloProjectM130Accumulated",
    "ModeloProjectNoM130RevisionsError",
    "ModeloProjectNoM130UnitsError",
    "ModeloProjectServiceResult",
    "ModeloProjectionCasillaObservation",
    "ModeloProjectionError",
    "ModeloReconciliationAdvisory",
    "ModeloReconciliationBytesCommand",
    "ModeloReconciliationCommand",
    "ModeloReconciliationDiff",
    "ModeloReconciliationDiffKind",
    "ModeloReconciliationEvidenceKind",
    "ModeloReconciliationHistoryEntry",
    "ModeloReconciliationRecord",
    "ModeloReconciliationRecordRepository",
    "ModeloReconciliationReport",
    "ModeloReconciliationVerdict",
    "ModeloRecordNotFoundError",
    "ModeloRecordStatus",
    "ModeloRefundElectionNotEligibleError",
    "ModeloRequiredBindingsMissingError",
    "ModeloResolvedRevisionProjection",
    "ModeloResolvedWorkProjection",
    "ModeloRevisionPick",
    "ModeloVerificationFindingKind",
    "ModeloVerificationFindingSeverity",
    "ModeloVerificationResult",
    "ModeloVerifySelector",
    "ModeloVisibleFilingTarget",
    "ModeloWorkAddress",
    "ModeloWorkAddressNotFoundError",
    "ModeloWorkBindingOrigin",
    "ModeloWorkCalculationServiceResult",
    "ModeloWorkConditionalRecargoPreview",
    "ModeloWorkCreateApplicabilityRefusal",
    "ModeloWorkDeadlinePosture",
    "ModeloWorkEnsureResult",
    "ModeloWorkLifecycleContinuation",
    "ModeloWorkNoActiveBucketError",
    "ModeloWorkOriginAnomaly",
    "ModeloWorkPeriodTokenError",
    "ModeloWorkProgress",
    "ModeloWorkProgressDenominator",
    "ModeloWorkRegistryYearMismatchError",
    "ModeloWorkRelationConsumption",
    "ModeloWorkResolution",
    "ModeloWorkReview",
    "ModeloWorkReviewCasilla",
    "ModeloWorkRevisionConflictError",
    "ModeloWorkSelectorContradictionError",
    "ModeloWorkSelectorError",
    "ModeloWorkSelectorRequest",
    "ModeloWorkSelectorState",
    "ModeloWorkTarget",
    "ModeloWorkUnitCandidate",
    "ModeloWorkUnitNotFoundError",
    "ModeloWorkVisibleTargetAmbiguousError",
    "ModeloWorkflowGateError",
    "ParticipationRebuildStats",
    "ProfileBindingResolutionError",
    "QuickfileCommand",
    "QuickfileResult",
    "QuickfileStage",
    "QuickfileStageOutcome",
    "QuickfileStageStatus",
    "RecipientAlreadyRegisteredError",
    "RecipientDecryptedPackage",
    "RecipientDecryptionError",
    "RecipientEncryptedPackage",
    "RecipientEncryptionError",
    "RecipientEncryptionKeyNotFoundError",
    "RecipientEncryptionKeypair",
    "RecipientEncryptionPublicKey",
    "RecipientFingerprintRecord",
    "RecipientFingerprintRegister",
    "RecipientFingerprintRegistryError",
    "RecipientFingerprintRegistryRepository",
    "RecipientNotRegisteredError",
    "RecipientPackageExpiredError",
    "RecipientPackageReplayedError",
    "RecipientReplayGuardError",
    "RecipientReplayGuardRepository",
    "ReconciliationCrossBucketRefusedError",
    "ReconciliationDeclaracionSourceUnsupportedError",
    "ReconciliationEvidenceInvalidError",
    "ResultSummaryRole",
    "ResultSummaryRow",
    "ReviewOnlyWorkspace",
    "ReviewOnlyWorkspaceAuthorityError",
    "ReviewOnlyWorkspaceError",
    "ReviewPackageBuildResult",
    "ReviewPackageCounterSigningError",
    "ReviewPackageError",
    "ReviewPackageFeedbackError",
    "ReviewPackageIntegrityError",
    "ReviewPackageManifest",
    "ReviewPackageRevisionStateError",
    "ReviewPackageSigningError",
    "ReviewPackageSigningKeyNotFoundError",
    "ReviewPackageSigningKeypair",
    "ReviewPackageSigningPublicKey",
    "ReviewPackageVerification",
    "SignedReviewPackage",
    "StoredCalculationDriftError",
    "TaxationComparisonError",
    "TaxationComparisonResult",
    "TaxationRecommendation",
    "VerificationCompletenessStatus",
    "VerificationFindingPreconditionProjection",
    "VerificationReportNotFoundError",
    "WorkCalculateInputBundle",
    "WorkUnitAlreadyDiscardedError",
    "WorkUnitHistory",
    "WorkUnitHistoryEvent",
    "WorkUnitMutationRefusedError",
    "WorkUnitNotFoundError",
    "WorkUnitRevisionDivergenceError",
    "active_natural_target_work_units",
    "amend_modelo_revision",
    "apply_calculation_shortcut_inputs",
    "apply_iva_compensation_decision_binding",
    "assemble_work_unit_history",
    "assert_no_novel_source_kinds",
    "assert_review_package_verifies",
    "assert_workspace_permits_official_action",
    "authorization_advisory_for_modelo",
    "build_feedback_package",
    "build_m145_communication_service_contract",
    "build_modelo_precondition_failure",
    "build_modelo_work_review",
    "build_review_package",
    "build_revision_deadline_window_checker",
    "build_verification_precondition_failure",
    "build_work_calculate_input_bundle",
    "calculate_modelo_revision",
    "calculate_modelo_revision_from_bucket_aggregation",
    "calculate_modelo_revision_from_bucket_aggregation_with_diagnostics",
    "calculate_modelo_work_revision",
    "calculation_result_summary",
    "casilla_id_for_unique_revision_semantic_role",
    "ceded_autonomic_modelo_locale_key",
    "compare_modelo_years",
    "compare_taxation_for_work_address",
    "compare_taxation_for_work_unit",
    "compare_taxation_modes",
    "compose_legal_full_name",
    "correct_iva_compensation_period_for_bucket",
    "counter_sign_review_package",
    "create_m145_communication_record",
    "create_work_unit",
    "data_inventory_checklist",
    "declared_modelo_period_tokens",
    "decrypt_feedback_package_from_originator_envelope",
    "decrypt_review_package_for_recipient",
    "derive_m036_declaration_id",
    "derive_m145_communication_record_id",
    "detect_casilla_divergences",
    "discard_work_unit",
    "emit_collab_feedback_countersign_attached_event",
    "emit_collab_package_counter_signed_event",
    "emit_collab_package_decrypted_event",
    "emit_collab_package_encrypted_event",
    "emit_collab_recipient_registered_event",
    "emit_collab_recipient_removed_event",
    "emit_collab_review_only_workspace_opened_event",
    "encrypt_feedback_package_for_originator",
    "encrypt_review_package_for_recipient",
    "ensure_modelo_work_unit_for_active_target",
    "ensure_recipient_encryption_keypair",
    "ensure_review_package_signing_keypair",
    "export_m145_communication_record",
    "export_modelo_revision",
    "file_modelo_revision",
    "get_calculation_revision",
    "get_filing_record",
    "get_verification_report",
    "get_work_unit",
    "guard_active_profile_foral_ccaa",
    "import_external_filing_evidence",
    "import_feedback_package",
    "is_detail_casilla_override_key",
    "lifecycle_continuation_for_work_history",
    "lifecycle_continuation_for_work_list",
    "lifecycle_continuation_for_work_status",
    "list_calculation_revisions",
    "list_filing_records",
    "list_m036_declarations",
    "list_m145_communication_records",
    "list_modelo_reconciliations",
    "list_verification_reports",
    "list_work_units",
    "load_recipient_encryption_keypair",
    "load_review_package_signing_keypair",
    "m036_declaration_object_key",
    "m145_communication_record_object_key",
    "maritime_facts_from_active_profile",
    "mark_m145_communication_record_delivered_to_payer",
    "mark_m145_communication_record_locally_completed",
    "mark_revision_verificado_completo",
    "modelo_202_modality_for_work_unit",
    "modelo_applicability_refusal",
    "modelo_reconcile",
    "modelo_reconcile_bytes",
    "modelo_work_address_from_operator_target",
    "modelo_work_create_applicability_refusal",
    "modelo_work_create_refusal_locale_key",
    "modelo_work_deadline_posture",
    "modelo_work_profile_baseline_missing_paths",
    "modelo_work_profile_baseline_validation_issues",
    "modelo_work_profile_preflight_report",
    "natural_target_work_units",
    "open_review_only_workspace",
    "parse_casilla_value_spreadsheet",
    "persist_filed_revision",
    "persist_filed_revision_observation",
    "pre_activity_period_refusal",
    "preview_maritime_exemption_for_active_profile",
    "profile_requirements_for_binding",
    "profile_resolvable_binding_ids",
    "profile_resolved_binding_ids",
    "project_modelo_100_from_m130",
    "project_modelo_work_target",
    "project_modelo_work_unit",
    "project_verification_findings",
    "public_key_hex_from_raw_bytes",
    "pulled_filing_divergence_findings",
    "read_m036_declaration",
    "read_m145_communication_record",
    "rebuild_participation_index",
    "recipient_encryption_public_key",
    "record_iva_compensation_override_for_bucket",
    "record_m036_declaration",
    "record_operator_local_observation",
    "registry_bindings",
    "registry_bindings_for_scope",
    "registry_bindings_for_year",
    "registry_casilla",
    "registry_casilla_for_registry_scope",
    "registry_casillas",
    "registry_casillas_for_registry_scope",
    "registry_casillas_for_scope",
    "registry_describe_modelo",
    "registry_describe_modelo_for_registry_scope",
    "registry_describe_modelo_for_scope",
    "registry_formulas",
    "registry_formulas_for_registry_scope",
    "registry_formulas_for_scope",
    "registry_list_modelos",
    "registry_modelo_codes",
    "registry_support_matrix",
    "rename_work_unit",
    "require_existing_profile_baseline_ready_for_modelo_work",
    "require_filing_instance_evidence_for_work_unit",
    "require_persisted_iva_compensation_decision_matches_revision",
    "require_profile_ready_for_modelo_work",
    "require_profile_ready_for_work_unit",
    "resolve_active_natural_modelo_work_unit",
    "resolve_calculation_binding_channels",
    "resolve_casilla_population_scope",
    "resolve_declaration_period_inputs",
    "resolve_export_identity",
    "resolve_exportable_modelo_calculation_revision_address",
    "resolve_fileable_modelo_calculation_revision_address",
    "resolve_maternidad_meses",
    "resolve_modelo_100_borrador_bindings",
    "resolve_modelo_calculation_revision_address",
    "resolve_modelo_calculation_revision_pick",
    "resolve_modelo_revision_for_operator_target",
    "resolve_modelo_revision_pick",
    "resolve_modelo_work_address",
    "resolve_modelo_work_address_unit",
    "resolve_modelo_work_bucket",
    "resolve_modelo_work_target",
    "resolve_modelo_work_unit",
    "resolve_modelo_work_unit_for_operator_target",
    "resolve_modelo_work_unit_id",
    "resolve_optional_modelo_work_address",
    "resolve_profile_export_values",
    "resolve_profile_sourced_bindings",
    "resolve_registry_revision_for_work_target",
    "resolve_verifiable_modelo_calculation_revision_address",
    "review_package_signing_public_key",
    "run_modelo_quickfile",
    "seed_iva_compensation_period_for_bucket",
    "select_current_verified_revision",
    "select_exportable_revision",
    "select_modelo_calculation_revision",
    "sign_review_package",
    "validate_calculation_route_resolver_ownership",
    "validate_m145_communication_record",
    "validate_m349_country_prefix_context",
    "validate_m349_nif_format",
    "validate_modelo_work_deadline_posture",
    "verify_counter_signed_receipt",
    "verify_modelo_revision",
    "verify_modelo_revision_with_preconditions",
    "verify_review_package",
    "verify_review_package_signature",
    "work_address_for_modelo_target",
    "workflow_period_for_work_unit",
]
