"""Shared operation identities, phase coordinates and bounded aggregate contracts."""

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from ..aggregation.withholding_filing_cadence import (
    PERIODIC_WITHHOLDING_MODELOS,
)

MODELO_AGGREGATE_OPERATION_DEFINITION_ID = "modelo.aggregate"


MODELO_AGGREGATE_UNSUPPORTED_MODELO_REFUSAL_CODE = "REFUSED_FINANCIAL_AGGREGATION_UNSUPPORTED_MODELO"


MODELO_AGGREGATE_LEDGER_PAYMENT_REFUSAL_CODE = "REFUSED_LEDGER_PAYMENT_WITHHOLDING_EVIDENCE"


MODELO_AGGREGATE_CADENCE_REFUSAL_CODE = "REFUSED_WITHHOLDING_FILING_CADENCE"


MODELO_AGGREGATE_PRODUCER_REFUSAL_CODE = "REFUSED_WITHHOLDING_PRODUCER"


MODELO_AGGREGATE_RECOGNITION_REFUSAL_CODE = "REFUSED_WITHHOLDING_RECOGNITION"


MODELO_AGGREGATE_REFUSAL_CODES = frozenset(
    {
        MODELO_AGGREGATE_UNSUPPORTED_MODELO_REFUSAL_CODE,
        MODELO_AGGREGATE_LEDGER_PAYMENT_REFUSAL_CODE,
        MODELO_AGGREGATE_CADENCE_REFUSAL_CODE,
        MODELO_AGGREGATE_PRODUCER_REFUSAL_CODE,
        MODELO_AGGREGATE_RECOGNITION_REFUSAL_CODE,
    }
)


AGGREGATE_PREPARE_PHASE = "modelo-aggregate.prepare"


AGGREGATE_COMMIT_PHASE = "modelo-aggregate.commit"


AGGREGATE_RESULT_PHASE = "modelo-aggregate.result"


AGGREGATE_PHASES = (AGGREGATE_PREPARE_PHASE, AGGREGATE_COMMIT_PHASE, AGGREGATE_RESULT_PHASE)


AGGREGATE_MAX_RESULT_BYTES = 16 * 1024


AGGREGATE_MAX_CLAVE_ROWS = 64


AGGREGATE_WITHHOLDING_MODELOS = frozenset(modelo.value for modelo in PERIODIC_WITHHOLDING_MODELOS)


AGGREGATE_LEDGER_PAYMENT_MODELOS = frozenset({"111", "123"})


AGGREGATE_SAFE_REFUSAL_REASON = Annotated[
    str,
    Field(min_length=1, max_length=96, pattern=r"^[a-z][a-z0-9_]*$"),
]
