"""Mul/Div scalar-leaf mutation harness (#338).

For every :class:`MulFormula` and :class:`DivFormula` node whose
direct operand is a :class:`Literal` scalar in a landed ruleset, the
harness multiplies the literal by 1.01 / 0.99 and asserts the engine
surfaces a discrepancy `≥ 0.02 €`.

Today's populated surface (per the audit grep at the time of
authorship of issue #338):

- Modelo 303 casilla 66 (2024 + 2025) — ``div_op(percent(...), lit("100"))``
  is the explicit ``/100`` normaliser of the % atribuible al estado.
- Modelo 200 casilla 00562 — ``percent_from_whole(ref("00558"), ref("00552"))``
  expands to ``percent(div_op(ref("00558"), Literal("100"), ...), ref("00552"))``;
  the inner ``Literal("100")`` is the whole-percent normaliser.
- Modelo 202 casilla 18 — same shape as M200 via ``percent_from_whole``.

A future ruleset that introduces additional ``MulFormula`` /
``DivFormula`` leaves automatically extends this harness because the
parameter table is generated by walking ``_FORMULAS`` of the
imported rulesets at import time.
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal

import pytest

from .._engine import Engine
from .._ruleset import Ruleset
from . import (
    MODELO_200_2024,
    MODELO_202_2025,
    MODELO_303_2024,
    MODELO_303_2025,
    MODELO_303_2026,
)
from ._mutators import iter_scalar_leaf_paths, mutate_scalar_leaf

pytestmark = [pytest.mark.unit, pytest.mark.domain_submission]


@dataclass(frozen=True)
class _ScalarCase:
    """One enumerated mutation case for the mul/div scalar mutator."""

    ruleset: Ruleset
    casilla_id: str
    formula_id: str
    leaf_path: tuple[int, ...]
    parent_op: str
    factor: Decimal
    fixture: dict[str, Decimal]
    direction_id: str


def _f303_general_for_scalar() -> dict[str, Decimal]:
    """Modelo 303 — drives casilla 66 = (65/100) * 64 = 21 €.

    Casilla 09 = 21% * 07 = 21 € on base 100 €. 45 = 21 + 0 + 0 -
    44 = 21. 64 = 45 + 0 = 21. 66 = (65/100) * 64 = (100/100) * 21
    = 21. After mutating the ``Literal("100")`` denominator by ±1 %:
    66 = (100 / 99) * 21 ≈ 21.21 (vs 21.00 baseline) — delta ≥ 0.21 €
    on casilla 66, well above the floor.
    """
    return {
        "01": Decimal("0.00"),
        "04": Decimal("0.00"),
        "07": Decimal("100.00"),
        "65": Decimal("100"),
        "67": Decimal("0.00"),
    }


def _f200_for_scalar() -> dict[str, Decimal]:
    """Modelo 200 — drives casilla 00562 = (00558/100) * 00552.

    With 00552=100 000 € (base) and 00558=25 (rate-as-whole-percent),
    casilla 00562 baseline = 25 000 €. Mutating the inner ``Literal("100")``
    by ±1 % moves 00562 by ~250 €.
    """
    return {
        "00547": Decimal("0.00"),
        "00550": Decimal("100000.00"),
        "00552": Decimal("100000.00"),
        "00558": Decimal("25.00"),
        "00560": Decimal("0.00"),
        "00582": Decimal("0.00"),
        "00592": Decimal("0.00"),
        "00599": Decimal("0.00"),
        "00601": Decimal("0.00"),
        "00603": Decimal("0.00"),
        "00605": Decimal("0.00"),
        "00615": Decimal("0.00"),
        "00619": Decimal("0.00"),
    }


def _f202_for_scalar() -> dict[str, Decimal]:
    """Modelo 202 — drives casilla 18 = (17/100) * 16 with an asymmetric base.

    With 16=200 000 € and 17=17 (rate-as-whole-percent), casilla 18
    baseline = 34 000 €. Mutating the inner Literal("100") by ±1 %
    moves casilla 18 by ~340 €.
    """
    return {
        "16": Decimal("200000.00"),
        "17": Decimal("17.00"),
        "27": Decimal("0.00"),
        "28": Decimal("0.00"),
        "30": Decimal("0.00"),
        "33": Decimal("0.00"),
    }


def _build_test_params() -> list:
    """Generate one pytest.param per (ruleset * leaf * direction).

    Walks every landed ruleset and yields a case for every direct
    Mul/Div literal leaf. The fixture for each ruleset is selected by
    a small dispatch table — adding a new ruleset to the harness
    requires adding a fixture entry; this is intentional, so a future
    author cannot quietly extend the harness without thinking about
    the test inputs.
    """
    fixture_for_ruleset: dict[str, dict[str, Decimal]] = {
        MODELO_303_2024.ruleset_id: _f303_general_for_scalar(),
        MODELO_303_2025.ruleset_id: _f303_general_for_scalar(),
        MODELO_303_2026.ruleset_id: _f303_general_for_scalar(),
        MODELO_200_2024.ruleset_id: _f200_for_scalar(),
        MODELO_202_2025.ruleset_id: _f202_for_scalar(),
    }
    rulesets = (MODELO_303_2024, MODELO_303_2025, MODELO_303_2026, MODELO_200_2024, MODELO_202_2025)
    params: list = []
    for ruleset in rulesets:
        for fd in ruleset.formulas:
            for leaf_path, _leaf, parent_op in iter_scalar_leaf_paths(fd.formula):
                for direction_id, factor in (("plus_1pct", Decimal("1.01")), ("minus_1pct", Decimal("0.99"))):
                    params.append(
                        pytest.param(
                            _ScalarCase(
                                ruleset=ruleset,
                                casilla_id=fd.casilla_id,
                                formula_id=fd.formula_id,
                                leaf_path=leaf_path,
                                parent_op=parent_op,
                                factor=factor,
                                fixture=fixture_for_ruleset[ruleset.ruleset_id],
                                direction_id=direction_id,
                            ),
                            id=(f"{ruleset.ruleset_id}:casilla_{fd.casilla_id}:{parent_op}_leaf:{direction_id}"),
                        )
                    )
    return params


def test_landed_rulesets_expose_some_scalar_leaves() -> None:
    """Smoke-check the harness has a non-empty parameter table.

    Today's expected surface: at least one ``Mul`` or ``Div`` leaf
    per ruleset across the four rulesets registered above.
    """
    assert _build_test_params(), "expected at least one scalar-leaf mutation case"


@pytest.mark.parametrize("case", _build_test_params())
def test_scalar_leaf_mutation_is_detected(case: _ScalarCase) -> None:
    """Mutating a Mul/Div literal leaf MUST produce a downstream discrepancy."""
    engine = Engine()
    user_inputs = {cid: v for cid, v in case.fixture.items() if not case.ruleset.casilla(cid).computed}
    baseline_ledger = engine.derive(ruleset=case.ruleset, inputs=user_inputs)
    baseline_values = {entry.casilla_id: entry.value for entry in baseline_ledger.entries}
    full_baseline = {**case.fixture, **baseline_values}

    baseline = engine.audit_against(
        ruleset=case.ruleset,
        provided=full_baseline,
        tolerance=Decimal("0.01"),
    )
    assert baseline.is_clean(), (
        f"baseline must be clean before mutation; saw {[d.casilla_id for d in baseline.discrepancies]}"
    )

    mutated = mutate_scalar_leaf(
        case.ruleset,
        case.casilla_id,
        case.leaf_path,
        factor=case.factor,
    )
    report = engine.audit_against(
        ruleset=mutated,
        provided=full_baseline,
        tolerance=Decimal("0.01"),
    )
    affected = {d.casilla_id for d in report.discrepancies}
    assert affected, (
        f"scalar-leaf {case.parent_op} mutation on {case.ruleset.ruleset_id} "
        f"casilla {case.casilla_id} ({case.direction_id}) was NOT detected"
    )
    max_delta = max(abs(d.delta) for d in report.discrepancies)
    assert max_delta >= Decimal("0.02"), (
        f"scalar-leaf {case.parent_op} mutation on {case.ruleset.ruleset_id} "
        f"casilla {case.casilla_id} produced max |delta|={max_delta}, below "
        f"the 0.02 € detection floor"
    )


def test_iter_scalar_leaf_paths_finds_div_leaves_in_modelo_303() -> None:
    """Modelo 303 casilla 66 has exactly one Div literal leaf (the /100)."""
    fd = MODELO_303_2025.formula_for("66")
    assert fd is not None
    leaves = list(iter_scalar_leaf_paths(fd.formula))
    # The body is ``RoundFormula(DivFormula(PercentFormula, Literal("100")))``.
    # Walker descends RoundFormula → DivFormula and yields the
    # ``Literal("100")`` at index 1.
    assert len(leaves) == 1
    leaf_path, leaf, parent_op = leaves[0]
    assert parent_op == "div"
    assert leaf.value == Decimal("100")
    assert leaf_path == (0, 1)


def test_mutate_scalar_leaf_rejects_non_literal_path() -> None:
    """Harness integrity: targeting a non-Literal raises TypeError."""
    fd = MODELO_303_2025.formula_for("66")
    assert fd is not None
    # Path (0, 0) inside casilla 66 is the PercentFormula numerator —
    # a compound node, not a literal. The mutator must refuse.
    with pytest.raises(TypeError):
        mutate_scalar_leaf(
            MODELO_303_2025,
            "66",
            (0, 0),
            factor=Decimal("1.01"),
        )
