"""Catalogue entry for the AEAT *Consulta de pagos / NRC* procedure page.

Exposes :data:`ENTRY`, a frozen :class:`PortalMetadata` record identified
by the :class:`Portal` code ``PORTAL_CONSULTA_PAGOS`` under the
:class:`PortalCategory` member
:attr:`cadrumo.domain.portals.PortalCategory.PAYMENT`. Used to query the
status of past payments and recover the NRC tokens generated by each
settlement.
"""

from __future__ import annotations

from ..categories import AuthMethod, PortalCategory, PortalHost, UrlStability
from ..codes import Portal
from ..metadata import PortalMetadata
from .common import build_entry, portal_path

ENTRY: PortalMetadata = build_entry(
    portal=Portal.PORTAL_CONSULTA_PAGOS,
    path=portal_path(Portal.PORTAL_CONSULTA_PAGOS),
    subdomain=PortalHost.SEDE,
    category=PortalCategory.PAYMENT,
    auth_methods=(
        AuthMethod.CERTIFICATE,
        AuthMethod.CLAVE_PIN,
        AuthMethod.CLAVE_PERMANENTE,
        AuthMethod.DNIE,
    ),
    url_stability=UrlStability.STABLE_WITHIN_CAMPAIGN,
    label="entries.portal_consulta_pagos.label",
    purpose="entries.portal_consulta_pagos.purpose",
)
"""Frozen :class:`cadrumo.domain.portals.PortalMetadata` for the payment / NRC enquiry page."""
