"""Build-time compilers projecting registry data into docs search records.

This package is dev build tooling (alongside ``dev/docs/cli_reference.py``
and ``dev/docs/apidocs``), not shippable ``src/cadrumo`` code: the projected
records are a build-time artifact consumed by the downstream Pagefind
injection, never committed (like the generated CLI reference). The casilla
records are MACHINE-GENERATED from registry snapshots and never hand-curated,
distinct from the curated ``dev.docs.terminology_handbook`` concept Handbook.
"""

from __future__ import annotations

from ._casilla_projection import (
    CasillaProjectionStats,
    project_casilla_search_records,
    project_modelo_casillas,
)
from ._cli_projection import (
    CliOptionRecord,
    CliProjectionStats,
    CliSurfaceRecord,
    project_cli_search_records,
)
from ._concept_cards import (
    ConceptCardProjectionStats,
    ConceptCardRecord,
    LegalGroundingLink,
    LocalisedDefinition,
    TermAlias,
    project_concept_cards,
)
from ._content_manifest import (
    RAW_BYTE_MANIFEST_SCHEMA_VERSION,
    RawByteManifest,
    RawByteManifestEntry,
    RawByteManifestError,
    build_raw_byte_manifest,
    verify_raw_byte_manifest,
)
from ._jcs import CANONICAL_JSON_CONTRACT, CanonicalJsonError, canonical_json_bytes
from ._legal_projection import LegalSearchRecord, project_legal_search_records
from ._miss_rate import (
    HeldOutQueryCase,
    HeldOutQuerySet,
    MissRateEvaluation,
    MissRateRow,
    MissReason,
    evaluate_held_out_miss_rate,
    held_out_query_set_path,
    load_committed_relevance,
    load_held_out_query_set,
    relevance_mapping_path,
)
from ._query_aliases import (
    QUERY_ALIAS_AUTHORITY_RELPATH,
    QUERY_ALIAS_AUTHORITY_SCHEMA_VERSION,
    QueryAliasAuthority,
    QueryAliasAuthorityError,
    QueryAliasAuthorityProvenance,
    QueryAliasEntry,
    build_query_alias_authority_provenance,
    load_query_alias_authority,
    query_alias_authority_path,
    validate_query_alias_authority,
)
from ._resolution import (
    ChunkHit,
    DroppedHit,
    DropReason,
    GroundingSurface,
    ResolutionResult,
    ResolvedTarget,
    TargetResolver,
    resolve_chunk_hits,
)
from ._search_record import (
    CasillaSearchRecord,
    ResultDisplayClass,
    SearchRecordBase,
    SearchRecordKind,
)
from ._sweep import (
    DEFAULT_MAX_RESULTS,
    RagSearchClient,
    ServiceRagSearchClient,
    SweepError,
    SweepQuery,
    SweepResult,
    TermRelevanceMapping,
    TermTargetRef,
    enumerate_query_vocabulary,
    run_sweep,
)
from ._synonym_mining import (
    DEFAULT_RELATIVE_COSINE_THRESHOLDS,
    RatificationAction,
    RatificationStatus,
    RatificationValidationResult,
    RatificationViolation,
    RelativeCosineThresholds,
    SynonymCandidateEntry,
    SynonymCandidateObservation,
    SynonymRatificationQueue,
    load_synonym_ratification_queue,
    mine_synonym_candidates,
    synonym_ratification_queue_path,
    validate_ratification_queue,
)
from ._unified_record import (
    RankingTier,
    SearchRecord,
    SearchRecordMetadata,
    derive_display_class,
    display_class_base_weight,
    kind_base_weight,
    normalise_display_class_weight,
    normalise_ranking_weight,
    to_search_record,
)
from ._wrangle import (
    STRONG_SIGNAL_SCORE_FLOOR,
    CollapsedHit,
    CollapseReason,
    DirectoryCluster,
    WrangledResult,
    read_clusters,
    wrangle,
)

__all__ = [
    "CANONICAL_JSON_CONTRACT",
    "DEFAULT_MAX_RESULTS",
    "DEFAULT_RELATIVE_COSINE_THRESHOLDS",
    "RAW_BYTE_MANIFEST_SCHEMA_VERSION",
    "STRONG_SIGNAL_SCORE_FLOOR",
    "CanonicalJsonError",
    "CasillaProjectionStats",
    "CasillaSearchRecord",
    "ChunkHit",
    "CliOptionRecord",
    "CliProjectionStats",
    "CliSurfaceRecord",
    "CollapseReason",
    "CollapsedHit",
    "ConceptCardProjectionStats",
    "ConceptCardRecord",
    "DirectoryCluster",
    "DropReason",
    "DroppedHit",
    "GroundingSurface",
    "HeldOutQueryCase",
    "HeldOutQuerySet",
    "LegalGroundingLink",
    "LegalSearchRecord",
    "LocalisedDefinition",
    "MissRateEvaluation",
    "MissRateRow",
    "MissReason",
    "QueryAliasAuthorityProvenance",
    "RagSearchClient",
    "RankingTier",
    "RatificationAction",
    "RatificationStatus",
    "RatificationValidationResult",
    "RatificationViolation",
    "RawByteManifest",
    "RawByteManifestEntry",
    "RawByteManifestError",
    "RelativeCosineThresholds",
    "ResolutionResult",
    "ResolvedTarget",
    "ResultDisplayClass",
    "SearchRecord",
    "SearchRecordBase",
    "SearchRecordKind",
    "SearchRecordMetadata",
    "ServiceRagSearchClient",
    "SweepError",
    "SweepQuery",
    "SweepResult",
    "SynonymCandidateEntry",
    "SynonymCandidateObservation",
    "SynonymRatificationQueue",
    "TargetResolver",
    "TermAlias",
    "TermRelevanceMapping",
    "TermTargetRef",
    "WrangledResult",
    "build_raw_byte_manifest",
    "canonical_json_bytes",
    "derive_display_class",
    "display_class_base_weight",
    "enumerate_query_vocabulary",
    "evaluate_held_out_miss_rate",
    "held_out_query_set_path",
    "kind_base_weight",
    "load_committed_relevance",
    "load_held_out_query_set",
    "load_synonym_ratification_queue",
    "mine_synonym_candidates",
    "normalise_display_class_weight",
    "normalise_ranking_weight",
    "project_casilla_search_records",
    "project_cli_search_records",
    "project_concept_cards",
    "project_legal_search_records",
    "project_modelo_casillas",
    "read_clusters",
    "relevance_mapping_path",
    "resolve_chunk_hits",
    "run_sweep",
    "synonym_ratification_queue_path",
    "to_search_record",
    "validate_ratification_queue",
    "verify_raw_byte_manifest",
    "wrangle",
]
