"""Focused adapter contract tests split from the original monolith."""

from __future__ import annotations

import pytest

from ._verification_chain_support import (
    _COMPUTED_CASILLAS_M111,
    _COMPUTED_CASILLAS_M130,
    _COMPUTED_CASILLAS_M303,
    _DR303_PROJECTION_CASILLAS,
    _M303_2023_ONWARDS_PARAMS,
    FIXTURES_DIR,
    Decimal,
    DeclaracionParseError,
    RegistryValidationError,
    _build_m303_engine_result,
    _period_to_date,
    _registry_snapshot,
    calculate_registry_snapshot,
    date,
    parse_declaracion,
)

pytestmark = [pytest.mark.unit, pytest.mark.hex_inbound_adapter]


@pytest.mark.parametrize(
    "pdf_stem,year,period",
    [
        ("2021-2T", 2021, "2T"),
        ("2021-3T", 2021, "3T"),
        ("2021-4T", 2021, "4T"),
        ("2022-1T", 2022, "1T"),
        ("2022-2T", 2022, "2T"),
        ("2022-3T", 2022, "3T"),
        ("2022-4T", 2022, "4T"),
        ("2023-1T", 2023, "1T"),
        ("2023-2T", 2023, "2T"),
        ("2023-3T", 2023, "3T"),
        ("2023-4T", 2023, "4T"),
        ("2024-1T", 2024, "1T"),
        ("2024-2T", 2024, "2T"),
        ("2024-3T", 2024, "3T"),
        ("2024-4T", 2024, "4T"),
    ],
)
def test_verification_chain_m130_engine_recomputes_closure_casilla_19(pdf_stem: str, year: int, period: str) -> None:
    """Engine recomputes casilla 19 (resultado final) from extracted leaf inputs.

    GROUNDED authority: synthetic formula-consistent fixtures generated by
    src/aeat/tests/fixtures/justificantes/_generate.py and committed at
    src/aeat/tests/fixtures/justificantes/130/. Each fixture prints casilla 03
    (rendimiento neto) and casilla 19 (resultado final, engine-derived closure).
    Values satisfy the M130 formula chain (see _MODELO_130_CORPUS_FIXTURES).

    The fixtures pre-date the rendimiento-neto formula landing (box 03 = 01 - 02).
    They print c03 directly as the leaf rendimiento neto with all other casillas
    absent.  The test reconstructs the canonical leaf decomposition as:
      c01 (ingresos) = extracted c03   (all income, zero expenses)
      c02 (gastos)   = 0
    so the engine computes c03 = c01 - c02 = extracted c03.  The art-110.3.b
    high-retention branch fires only when c06/c01 >= 0.70; with c06=0 both the
    c01=0 and c01>0 paths of the c17 formula reduce to (c14 - c15) - c16,
    giving identical c19 output.

    Chain:
      1. parse_declaracion → DeclaracionObservation (extracts c03 and c19 only)
      2. Reconstruct leaf inputs: c01 = extracted_c03, c02 = 0
      3. Supply previous-filing binding values:
         - modelo-130-pagos-fraccionados-anteriores = 0 (no prior payments)
         - modelo-130-resultados-negativos-anteriores = 0 (no prior negative)
         - irpf.previous_year_economic_activity_net_income = 0
           (unknown from corpus → conservative 0 → casilla 13 = 0)
      4. calculate_registry_snapshot with inputs + binding_values
      5. Assert engine.values["03"] == c01 - c02 == extracted["03"] (formula check)
      6. Assert engine.values["19"] == extracted["19"]

    Verdict: VERIFIED when engine == extracted; PARSER-GAP when parse fails;
    BINDING-GAP when engine raises RegistryValidationError; FORMULA-MISMATCH
    when engine value differs from extracted value (reported as assertion failure).
    """
    pdf_path = FIXTURES_DIR / "justificantes" / "130" / f"{pdf_stem}.pdf"

    # Parse the declaration.
    try:
        filing = parse_declaracion(
            pdf_path,
            modelo_override="130",
            año_override=year,
            period_override=period,
        )
    except DeclaracionParseError as exc:
        # PARSER-GAP: extraction failed for this corpus specimen
        pytest.fail(
            f"PARSER-GAP [{pdf_stem}]: parse_declaracion raised DeclaracionParseError — "
            f"extraction coverage failure prevents engine recomputation.\n"
            f"  error: {exc}",
        )

    extracted = {v.casilla_id: v.printed_value for v in filing.values}

    # Skip specimens where casilla 19 was not extracted.
    if "19" not in extracted:
        # The corpus PDF is a partial filing — casilla 19 blank.
        # Still run the engine so BINDING-GAP and FORMULA-MISMATCH can be
        # detected on other extracted casillas; skip the 19-equality assertion.
        closure_extracted = None
    else:
        assert isinstance(extracted["19"], Decimal), (
            f"{pdf_stem}: casilla '19' expected Decimal, got {type(extracted['19']).__name__}"
        )
        closure_extracted = extracted["19"]

    # Build leaf inputs.
    # The fixture prints only c03 (rendimiento neto) and c19 (closure).  Box 03 is
    # now computed (03 = 01 - 02) so it cannot go into engine inputs.  Reconstruct
    # the canonical leaf decomposition: c01 = extracted_c03 (all income, no expenses),
    # c02 = 0 (gastos absent from fixture).  The art-110.3.b branch of c17 is safe:
    # with c06=0 both paths yield (c14 - c15) - c16, so c19 is unaffected.
    # Other extracted non-computed casillas (absent in these fixtures) pass through.
    extracted_c03 = extracted.get("03")
    inputs: dict[str, Decimal] = {}
    for casilla_id, value in extracted.items():
        if casilla_id in _COMPUTED_CASILLAS_M130:
            continue
        if not isinstance(value, Decimal):
            continue
        inputs[casilla_id] = value
    # Inject the reconstructed leaf decomposition for box 03.
    if isinstance(extracted_c03, Decimal):
        inputs["01"] = extracted_c03  # c01 = rendimiento neto (c03), no gastos
        # c02 defaults to 0 (absent from fixture — not injected here)

    # Only previous_filing bindings must be supplied via binding_values:
    binding_values: dict[str, Decimal] = {
        # Prior-quarter payments and negative-result carry-forward; 0 = no prior
        # values (safe default for corpus specimens where we don't know prior
        # quarter saldo or payments).
        "modelo-130-pagos-fraccionados-anteriores": Decimal("0"),
        "modelo-130-resultados-negativos-anteriores": Decimal("0"),
        # Prior-year net income; 0 → casilla 13 = 0 (minoración rendimientos netos).
        # Conservative but honest: corpus PDFs don't print casilla 13 (computed).
        "irpf.previous_year_economic_activity_net_income": Decimal("0"),
    }

    # Resolve snapshot and run engine.
    snapshot = _registry_snapshot("130", year, period)
    filing_period_date = _period_to_date(year, period)

    try:
        result = calculate_registry_snapshot(
            snapshot,
            inputs=inputs,
            date_context={"filing_period": filing_period_date},
            binding_values=binding_values,
        )
    except RegistryValidationError as exc:
        # BINDING-GAP: engine could not compute because a required binding value
        # is missing. This is a structural defect — the verification chain cannot
        # be closed without that binding.
        pytest.fail(
            f"BINDING-GAP [{pdf_stem}]: calculate_registry_snapshot raised "
            f"RegistryValidationError — a required binding is missing.\n"
            f"  error: {exc}\n"
            f"  inputs supplied: {sorted(inputs)}\n"
            f"  binding_values supplied: {sorted(binding_values)}",
        )

    # Verify engine computes casilla 03 = 01 - 02.
    engine_values = dict(result.values)

    input_01 = inputs.get("01", Decimal("0"))
    input_02 = inputs.get("02", Decimal("0"))
    engine_03 = engine_values.get("03")
    assert engine_03 is not None, (
        f"FORMULA-MISMATCH [{pdf_stem}]: casilla '03' absent from engine result "
        f"— formula modelo-130-rendimiento-neto evaluation failed."
    )
    assert engine_03 == input_01 - input_02, (
        f"FORMULA-MISMATCH [{pdf_stem}]: engine casilla '03' = {engine_03!r}, "
        f"expected 01({input_01!r}) - 02({input_02!r}) = {input_01 - input_02!r}"
    )

    # Compare engine casilla 19 against extracted value.
    if closure_extracted is not None:
        engine_19 = engine_values.get("19")
        assert engine_19 is not None, (
            f"FORMULA-MISMATCH [{pdf_stem}]: casilla '19' absent from engine result "
            f"— formula evaluation order issue or casilla missing from revision."
        )
        assert engine_19 == closure_extracted, (
            f"FORMULA-MISMATCH [{pdf_stem}]: engine recomputed casilla '19' as "
            f"{engine_19!r} but AEAT-printed form shows {closure_extracted!r}.\n"
            f"  diff: {engine_19 - closure_extracted!r}\n"
            f"  extracted inputs: {dict((k, v) for k, v in extracted.items() if k not in _COMPUTED_CASILLAS_M130)}\n"
            f"  engine values for formula chain: "
            f"03={engine_values.get('03')!r} 04={engine_values.get('04')!r} "
            f"05={engine_values.get('05')!r} 06={engine_values.get('06')!r} "
            f"07={engine_values.get('07')!r} 13={engine_values.get('13')!r} "
            f"14={engine_values.get('14')!r} 15={engine_values.get('15')!r} "
            f"17={engine_values.get('17')!r} 18={engine_values.get('18')!r} "
            f"19={engine_19!r}"
        )


@pytest.mark.parametrize(
    "pdf_stem,year,period",
    [
        ("2024-1T", 2024, "1T"),
        ("2024-2T", 2024, "2T"),
        ("2024-3T", 2024, "3T"),
        ("2024-4T", 2024, "4T"),
    ],
)
def test_verification_chain_m111_engine_recomputes_closure_casillas_28_and_30(
    pdf_stem: str,
    year: int,
    period: str,
) -> None:
    """Engine recomputes casilla 28 (total retenciones) and 30 (resultado) from leaf inputs.

    GROUNDED authority: AEAT corpus PDFs from the sanitised real-form fixture
    set committed at src/aeat/tests/fixtures/justificantes/111/.

    Chain:
      1. parse_declaracion → DeclaracionObservation with extracted casillas
      2. Filter to non-computed casillas (01-27, 29) → inputs
      3. calculate_registry_snapshot
      4. Assert engine.values["28"] == extracted["28"] (when present)
         Assert engine.values["30"] == extracted["30"] (when present)

    Formula:
      28 = sum(03, 06, 09, 12, 15, 18, 21, 24, 27)  [total retenciones]
      30 = 28 - 29                                   [resultado a ingresar]

    2024-1T/2T/3T: VERIFIED — leaf casilla 09 (retenciones actividades economicas
    dinerarias) is extracted; engine recomputes 28 = 09 = 1000, 30 = 28 - 0 = 1000.

    2024-4T: NEGATIVA/SIN ACTIVIDAD/RESULTADO CERO corpus PDF.  All col-C leaf
    casillas are zero; the printed box 30 comes from the real filing's settlement
    section (not derivable from current-period inputs).  has_leaf_inputs=False,
    so formula-consistency assertions are skipped — the test PASSES correctly.
    No formula gap, no bbox gap.  This is the expected path for a nil filing.

    Casilla 29 (anteriores autoliquidaciones) is absent from the corpus (zero);
    the engine defaults it to 0, so 30 = 28 - 0 = 28 for the non-nil quarters.
    """
    pdf_path = FIXTURES_DIR / "justificantes" / "111" / f"{pdf_stem}.pdf"

    # Parse the declaration.
    try:
        filing = parse_declaracion(
            pdf_path,
            modelo_override="111",
            año_override=year,
            period_override=period,
        )
    except DeclaracionParseError as exc:
        pytest.fail(f"PARSER-GAP [{pdf_stem}]: parse_declaracion raised DeclaracionParseError.\n  error: {exc}")

    extracted = {v.casilla_id: v.printed_value for v in filing.values}

    # Build inputs: exclude computed casillas 28 and 30.
    inputs: dict[str, Decimal] = {}
    for casilla_id, value in extracted.items():
        if casilla_id in _COMPUTED_CASILLAS_M111:
            continue
        if isinstance(value, Decimal):
            inputs[casilla_id] = value

    # Resolve snapshot and run engine.
    snapshot = _registry_snapshot("111", year, period)
    filing_period_date = _period_to_date(year, period)

    try:
        result = calculate_registry_snapshot(
            snapshot,
            inputs=inputs,
            date_context={"filing_period": filing_period_date},
        )
    except RegistryValidationError as exc:
        pytest.fail(
            f"BINDING-GAP [{pdf_stem}]: calculate_registry_snapshot raised "
            f"RegistryValidationError — a required binding is missing.\n"
            f"  error: {exc}\n"
            f"  inputs supplied: {sorted(inputs)}",
        )

    engine_values = dict(result.values)

    # Leaf inputs for formula 28 = sum(03,06,09,12,15,18,21,24,27).
    # When none of the leaf casillas are present in the corpus PDF (data-sparse
    # filing where only the totals were printed), the engine correctly computes
    # 28=0 and 30=0 — these cannot be compared against the extracted totals
    # without the breakdown.  Skip formula-consistency checks in that case.
    _CASILLA_28_LEAVES = frozenset({"03", "06", "09", "12", "15", "18", "21", "24", "27"})
    has_leaf_inputs = bool(inputs.keys() & _CASILLA_28_LEAVES)

    # Verify casilla 28 when extracted and leaf inputs are present.
    if "28" in extracted and has_leaf_inputs:
        extracted_28 = extracted["28"]
        assert isinstance(extracted_28, Decimal)
        engine_28 = engine_values.get("28")
        assert engine_28 is not None, f"FORMULA-MISMATCH [{pdf_stem}]: casilla '28' absent from engine result."
        assert engine_28 == extracted_28, (
            f"FORMULA-MISMATCH [{pdf_stem}]: engine casilla '28' = {engine_28!r}, "
            f"AEAT-printed = {extracted_28!r}.\n"
            f"  diff: {engine_28 - extracted_28!r}\n"
            f"  inputs: {inputs}"
        )

    # Verify casilla 30 when extracted and leaf inputs are present.
    if "30" in extracted and has_leaf_inputs:
        extracted_30 = extracted["30"]
        assert isinstance(extracted_30, Decimal)
        engine_30 = engine_values.get("30")
        assert engine_30 is not None, f"FORMULA-MISMATCH [{pdf_stem}]: casilla '30' absent from engine result."
        assert engine_30 == extracted_30, (
            f"FORMULA-MISMATCH [{pdf_stem}]: engine casilla '30' = {engine_30!r}, "
            f"AEAT-printed = {extracted_30!r}.\n"
            f"  diff: {engine_30 - extracted_30!r}\n"
            f"  inputs: {inputs}"
        )


@pytest.mark.parametrize(
    "pdf_stem,year,period",
    [
        ("2023-1T", 2023, "1T"),
        ("2023-2T", 2023, "2T"),
        ("2023-3T", 2023, "3T"),
        ("2023-4T", 2023, "4T"),
        ("2024-1T", 2024, "1T"),
        ("2024-2T", 2024, "2T"),
        ("2024-3T", 2024, "3T"),
        ("2024-4T", 2024, "4T"),
    ],
)
def test_verification_chain_m303_parser_extracts_all_profile_casillas(pdf_stem: str, year: int, period: str) -> None:
    """Parser extracts all 12 M303 profile casillas from corpus PDFs.

    GROUNDED authority: AEAT corpus PDFs from the sanitised real-form fixture
    set committed at src/aeat/tests/fixtures/justificantes/303/.

    Verdict: PARSER-GAP when extraction fails. This test verifies the
    extraction side of the chain only. The companion test
    test_verification_chain_m303_engine_recomputes_resultado_regimen_general
    exercises the formula engine (box 46 = box 27 − box 45, Orden
    EHA/3786/2008 art. 1).

    The M303 2009-y-siguientes revision (2021-2022 PDFs) is excluded here;
    it covers a different profile.
    """
    pdf_path = FIXTURES_DIR / "justificantes" / "303" / f"{pdf_stem}.pdf"

    try:
        filing = parse_declaracion(
            pdf_path,
            modelo_override="303",
            año_override=year,
            period_override=period,
        )
    except DeclaracionParseError as exc:
        pytest.fail(
            f"PARSER-GAP [{pdf_stem}]: parse_declaracion raised — M303 2023+ extraction failed.\n  error: {exc}",
        )

    extracted = {v.casilla_id: v.printed_value for v in filing.values}

    assert set(extracted.keys()) == {
        # Primitive cuota leaves: the engine sums these into iva.cuota-devengada-total
        # and iva.cuota-deducible-total so resultado-regimen-general is
        # recomputed from primitives rather than copied from the printed total.
        "iva.repercutido.general",
        "iva.repercutido.reducido",
        "iva.repercutido.super-reducido",
        "iva.autorepercutido.intracomunitaria",
        "iva.soportado.interiores",
        "iva.autoconsumo.promotor.base",
        # Form-page totals retained for AEAT-form fidelity and the engine
        # resultado == c27 - c45 internal-consistency assertion.
        "27",
        "29",
        "37",
        "45",
        "iva.resultado-regimen-general",
        "64",
        "66",
        "iva.compensacion-pendiente-periodos-anteriores",
        "iva.compensacion-aplicada-periodo",
        "iva.compensacion-pendiente-periodos-posteriores",
        "iva.resultado",
        "71",
    }, (
        f"PARSER-GAP [{pdf_stem}]: M303 2023+ profile extraction did not produce "
        f"the expected 18 casilla IDs (6 primitives + 12 form-page totals).\n"
        f"  got: {sorted(extracted)}"
    )
    # All extracted values must be Decimal instances (amount fields).
    for casilla_id, value in extracted.items():
        assert isinstance(value, Decimal), (
            f"PARSER-GAP [{pdf_stem}]: casilla {casilla_id!r} should be Decimal, "
            f"got {type(value).__name__!r} = {value!r}"
        )


@pytest.mark.parametrize(
    "pdf_stem,year,period",
    [
        ("2023-1T", 2023, "1T"),
        ("2023-2T", 2023, "2T"),
        ("2023-3T", 2023, "3T"),
        ("2023-4T", 2023, "4T"),
        ("2024-1T", 2024, "1T"),
        ("2024-2T", 2024, "2T"),
        ("2024-3T", 2024, "3T"),
        ("2024-4T", 2024, "4T"),
    ],
)
def test_verification_chain_m303_engine_recomputes_resultado_regimen_general(
    pdf_stem: str,
    year: int,
    period: str,
) -> None:
    """Engine resultado-regimen-general matches the extracted printed box 46.

    GROUNDED authority: Orden EHA/3786/2008 art. 1 — box 46 = box 27 − box 45.
      box 27 = Total cuota devengada (LIVA art. 88)
      box 45 = Total a deducir (LIVA arts. 92-94)
      box 46 = Resultado régimen general

    The 2023-y-siguientes corpus PDFs are synthetic fixtures generated by
    _generate.py with formula-consistent values: c46 = c27 - c45, so the
    engine result matches the printed value exactly.

    Verdict: VERIFIED — engine resultado == extracted resultado for all
    8 new-template specimens (2023-2024). Corpus-regenerated with
    formula-consistent synthetic values.
    """
    pdf_path = FIXTURES_DIR / "justificantes" / "303" / f"{pdf_stem}.pdf"

    try:
        filing = parse_declaracion(
            pdf_path,
            modelo_override="303",
            año_override=year,
            period_override=period,
        )
    except DeclaracionParseError as exc:
        pytest.fail(f"PARSER-GAP [{pdf_stem}]: parse_declaracion raised — M303 extraction failed.\n  error: {exc}")

    extracted = {v.casilla_id: v.printed_value for v in filing.values}

    for required_id in ("27", "45", "iva.resultado-regimen-general"):
        assert required_id in extracted, (
            f"PARSER-GAP [{pdf_stem}]: required casilla {required_id!r} not in extracted values.\n"
            f"  got: {sorted(extracted)}"
        )

    # Build inputs — supply only non-computed Decimal casillas.
    inputs: dict[str, Decimal] = {}
    for casilla_id, value in extracted.items():
        if casilla_id in _COMPUTED_CASILLAS_M303:
            continue
        if not isinstance(value, Decimal):
            continue
        inputs[casilla_id] = value

    # Box 65 (porcentaje atribuible Estado) is bound to the profile-derived
    # ``tax_residence.state_attribution_ratio`` via casilla.binding. The engine's
    # _initial_values only auto-hydrates BOUND casillas from binding_values for
    # ``previous_filing`` source; profile-sourced bound casillas expect the
    # application-layer resolver to have populated ``inputs`` before reaching
    # the calculator. Supply C65 via both channels for the engine-direct test
    # path.
    inputs["65"] = Decimal("100")

    # The previous_filing binding for compensacion-pendiente-anteriores is
    # required by the engine. Supply the extracted value from the corpus PDF
    # if available (box iva.compensacion-pendiente-periodos-anteriores), else zero.
    _extracted_comp = extracted.get("iva.compensacion-pendiente-periodos-anteriores", Decimal("0"))
    _comp = _extracted_comp if isinstance(_extracted_comp, Decimal) else Decimal("0")
    binding_values: dict[str, Decimal] = {
        "modelo-303-compensacion-pendiente-anteriores": _comp,
        "modelo-303-profile-state-attribution-ratio": Decimal("100"),
    }

    # filing_period: first day of the period's quarter.
    _period_month = {"1T": 1, "2T": 4, "3T": 7, "4T": 10}[period]
    snapshot = _registry_snapshot("303", year, period)

    try:
        result = calculate_registry_snapshot(
            snapshot,
            inputs=inputs,
            date_context={"filing_period": date(year, _period_month, 1)},
            binding_values=binding_values,
        )
    except RegistryValidationError as exc:
        pytest.fail(
            f"BINDING-GAP [{pdf_stem}]: calculate_registry_snapshot raised "
            f"RegistryValidationError — a required binding is missing.\n"
            f"  error: {exc}\n"
            f"  inputs supplied: {sorted(inputs)}\n"
            f"  binding_values supplied: {sorted(binding_values)}",
        )

    engine_values = dict(result.values)

    # VERIFIED gate: engine resultado must equal extracted printed box 46.
    # The synthetic corpus PDFs were generated with c46 = c27 - c45, matching
    # the registry formula. Any future registry formula change that breaks this
    # will cause a loud test failure.
    engine_resultado = engine_values.get("iva.resultado-regimen-general")
    assert engine_resultado is not None, (
        f"VERIFIED-FAIL [{pdf_stem}]: 'iva.resultado-regimen-general' absent from engine result"
    )
    extracted_resultado = extracted.get("iva.resultado-regimen-general")
    assert isinstance(extracted_resultado, Decimal), (
        f"VERIFIED-FAIL [{pdf_stem}]: extracted 'iva.resultado-regimen-general' is not Decimal: {extracted_resultado!r}"
    )
    assert engine_resultado == extracted_resultado, (
        f"VERIFIED-FAIL [{pdf_stem}]: engine resultado-regimen-general "
        f"{engine_resultado!r} != extracted {extracted_resultado!r}\n"
        f"  (engine formula or fixture inconsistency — box 46 = box 27 − box 45,\n"
        f"   Orden EHA/3786/2008 art. 1)"
    )
    # Internal consistency cross-check: engine resultado == computed c27 - c45.
    engine_27 = engine_values.get("27")
    engine_45 = engine_values.get("45")
    assert isinstance(engine_27, Decimal), (
        f"VERIFIED-FAIL [{pdf_stem}]: engine-computed box 27 missing or non-Decimal: {engine_27!r}"
    )
    assert isinstance(engine_45, Decimal), (
        f"VERIFIED-FAIL [{pdf_stem}]: engine-computed box 45 missing or non-Decimal: {engine_45!r}"
    )
    expected_resultado = engine_27 - engine_45
    assert engine_resultado == expected_resultado, (
        f"VERIFIED-FAIL [{pdf_stem}]: engine resultado-regimen-general "
        f"{engine_resultado!r} != box27({engine_27!r}) - box45({engine_45!r}) = {expected_resultado!r}\n"
        f"  (internal formula consistency broken — registry formula defect)"
    )


@pytest.mark.parametrize("pdf_stem,year,period", _M303_2023_ONWARDS_PARAMS)
def test_verification_chain_m303_engine_recomputes_box_64_suma_resultados(
    pdf_stem: str,
    year: int,
    period: str,
) -> None:
    """Engine box 64 (suma de resultados) matches the extracted printed value.

    GROUNDED authority: Orden HAC/819/2024 art. 1 §4 — box 64 = box 46 + box 58 + box 76.
    For the synthetic corpus PDFs: c58 = 0, c76 = 0, so box 64 = box 46.

    Verdict: VERIFIED — engine box 64 == extracted box 64 for all 8 new-template
    specimens (2023-2024). Closure DAG (Orden HAC/819/2024 art. 1).
    """
    extracted, engine_values, _inputs = _build_m303_engine_result(pdf_stem, year, period)

    engine_64 = engine_values.get("64")
    assert engine_64 is not None, f"VERIFIED-FAIL [{pdf_stem}]: '64' (suma de resultados) absent from engine result"
    extracted_64 = extracted.get("64")
    assert isinstance(extracted_64, Decimal), (
        f"VERIFIED-FAIL [{pdf_stem}]: extracted '64' is not Decimal: {extracted_64!r}"
    )
    assert engine_64 == extracted_64, (
        f"VERIFIED-FAIL [{pdf_stem}]: engine box 64 {engine_64!r} != extracted {extracted_64!r}\n"
        f"  (Orden HAC/819/2024 art. 1 §4: box 64 = box 46 + box 58 + box 76)"
    )
    # Internal cross-check: for synthetic PDFs c58=0, c76=0 → box 64 == box 46.
    box_46 = engine_values.get("iva.resultado-regimen-general", Decimal("0"))
    assert engine_64 == box_46, (
        f"VERIFIED-FAIL [{pdf_stem}]: engine box 64 {engine_64!r} != engine box 46 {box_46!r}\n"
        f"  (c58=0, c76=0 in corpus PDFs — expected 64 == 46)"
    )


@pytest.mark.parametrize("pdf_stem,year,period", _M303_2023_ONWARDS_PARAMS)
def test_verification_chain_m303_engine_recomputes_box_66_atribuible_estado(
    pdf_stem: str,
    year: int,
    period: str,
) -> None:
    """Engine box 66 (atribuible Administración del Estado) matches the extracted printed value.

    GROUNDED authority: Orden HAC/819/2024 art. 1 §4 — box 66 = box 64 × box 65 / 100.
    For territorio común: box 65 = 100 → box 66 = box 64.
    Grounded in RD 1624/1992 art. 71 (régimen de tributación conjunta).

    Verdict: VERIFIED — engine box 66 == extracted box 66 for all 8 new-template
    specimens (2023-2024). Closure DAG (Orden HAC/819/2024 art. 1).
    """
    extracted, engine_values, _inputs = _build_m303_engine_result(pdf_stem, year, period)

    engine_66 = engine_values.get("66")
    assert engine_66 is not None, f"VERIFIED-FAIL [{pdf_stem}]: '66' (atribuible Estado) absent from engine result"
    extracted_66 = extracted.get("66")
    assert isinstance(extracted_66, Decimal), (
        f"VERIFIED-FAIL [{pdf_stem}]: extracted '66' is not Decimal: {extracted_66!r}"
    )
    assert engine_66 == extracted_66, (
        f"VERIFIED-FAIL [{pdf_stem}]: engine box 66 {engine_66!r} != extracted {extracted_66!r}\n"
        f"  (Orden HAC/819/2024 art. 1 §4: box 66 = box 64 × box 65 / 100)"
    )
    # Internal cross-check: box 65 = 100 → box 66 == box 64.
    box_64 = engine_values.get("64", Decimal("0"))
    assert engine_66 == box_64, (
        f"VERIFIED-FAIL [{pdf_stem}]: engine box 66 {engine_66!r} != engine box 64 {box_64!r}\n"
        f"  (box 65 = 100 in territorio común — expected 66 == 64)"
    )


@pytest.mark.parametrize("pdf_stem,year,period", _M303_2023_ONWARDS_PARAMS)
def test_verification_chain_m303_engine_recomputes_box_69_resultado_autoliquidacion(
    pdf_stem: str,
    year: int,
    period: str,
) -> None:
    """Engine box 69 (resultado autoliquidación) matches the extracted printed value.

    GROUNDED authority: Orden HAC/819/2024 art. 1 §5 — box 69 = box 66 + box 77 + box 68 - box 78.
    For the synthetic corpus PDFs: c77 = 0, c68 = 0, c78 = 0 → box 69 = box 66.
    Grounded in LIVA arts. 99, 115, 116; RD 1624/1992 arts. 29, 30, 71.

    Verdict: VERIFIED — engine box 69 == extracted box 69 for all 8 new-template
    specimens (2023-2024). Closure DAG (Orden HAC/819/2024 art. 1).
    """
    extracted, engine_values, _inputs = _build_m303_engine_result(pdf_stem, year, period)

    engine_69 = engine_values.get("iva.resultado")
    assert engine_69 is not None, f"VERIFIED-FAIL [{pdf_stem}]: 'iva.resultado' (box 69) absent from engine result"
    extracted_69 = extracted.get("iva.resultado")
    assert isinstance(extracted_69, Decimal), (
        f"VERIFIED-FAIL [{pdf_stem}]: extracted 'iva.resultado' (box 69) is not Decimal: {extracted_69!r}"
    )
    assert engine_69 == extracted_69, (
        f"VERIFIED-FAIL [{pdf_stem}]: engine box 69 {engine_69!r} != extracted {extracted_69!r}\n"
        f"  (Orden HAC/819/2024 art. 1 §5: box 69 = box 66 + box 77 + box 68 − box 78)"
    )
    # Internal cross-check: c77=0, c68=0, c78=0 → box 69 == box 66.
    box_66 = engine_values.get("66", Decimal("0"))
    assert engine_69 == box_66, (
        f"VERIFIED-FAIL [{pdf_stem}]: engine box 69 {engine_69!r} != engine box 66 {box_66!r}\n"
        f"  (c77=0, c68=0, c78=0 in corpus PDFs — expected 69 == 66)"
    )


@pytest.mark.parametrize("pdf_stem,year,period", _M303_2023_ONWARDS_PARAMS)
def test_verification_chain_m303_engine_recomputes_box_71_resultado_final(
    pdf_stem: str,
    year: int,
    period: str,
) -> None:
    """Engine box 71 (resultado final) matches the extracted printed value.

    GROUNDED authority: Orden HAC/819/2024 art. 1 §6 — box 71 = box 69 − box 70 + box 109.
    For the synthetic corpus PDFs: c70 = 0, c109 = 0 → box 71 = box 69.
    Grounded in LIVA arts. 99, 115, 116; RD 1624/1992 arts. 29, 30, 71.

    Verdict: VERIFIED — engine box 71 == extracted box 71 for all 8 new-template
    specimens (2023-2024). Closure DAG (Orden HAC/819/2024 art. 1).
    """
    extracted, engine_values, _inputs = _build_m303_engine_result(pdf_stem, year, period)

    engine_71 = engine_values.get("71")
    assert engine_71 is not None, f"VERIFIED-FAIL [{pdf_stem}]: '71' (resultado final) absent from engine result"
    extracted_71 = extracted.get("71")
    assert isinstance(extracted_71, Decimal), (
        f"VERIFIED-FAIL [{pdf_stem}]: extracted '71' is not Decimal: {extracted_71!r}"
    )
    assert engine_71 == extracted_71, (
        f"VERIFIED-FAIL [{pdf_stem}]: engine box 71 {engine_71!r} != extracted {extracted_71!r}\n"
        f"  (Orden HAC/819/2024 art. 1 §6: box 71 = box 69 − box 70 + box 109)"
    )
    # Internal cross-check: c70=0, c109=0 → box 71 == box 69.
    box_69 = engine_values.get("iva.resultado", Decimal("0"))
    assert engine_71 == box_69, (
        f"VERIFIED-FAIL [{pdf_stem}]: engine box 71 {engine_71!r} != engine box 69 {box_69!r}\n"
        f"  (c70=0, c109=0 in corpus PDFs — expected 71 == 69)"
    )


@pytest.mark.parametrize(
    "pdf_stem,year,period",
    [
        ("2021-2T", 2021, "2T"),
        ("2021-3T", 2021, "3T"),
        ("2021-4T", 2021, "4T"),
        ("2022-1T", 2022, "1T"),
        ("2022-2T", 2022, "2T"),
        ("2022-3T", 2022, "3T"),
        ("2022-4T", 2022, "4T"),
    ],
)
def test_verification_chain_m303_legacy_engine_recomputes_resultado_regimen_general(
    pdf_stem: str,
    year: int,
    period: str,
) -> None:
    """Engine resultado-regimen-general matches the extracted printed box 46 (legacy revision).

    GROUNDED authority: Orden EHA/3786/2008 art. 1 — box 46 = box 27 − box 45.
    The 2009-y-siguientes revision covers ejercicios 2009-2022 and uses the same
    formula. The legacy extraction profile extracts 4 casillas: 27, 29, 45, and
    iva.resultado-regimen-general.

    The legacy corpus PDFs are synthetic fixtures generated by _generate.py
    with formula-consistent values: c46 = c27 - c45.

    Verdict: VERIFIED — engine resultado == extracted resultado for all 7
    legacy specimens (2021-2022). Corpus-regenerated with
    formula-consistent synthetic values.
    """
    pdf_path = FIXTURES_DIR / "justificantes" / "303" / f"{pdf_stem}.pdf"

    try:
        filing = parse_declaracion(
            pdf_path,
            modelo_override="303",
            año_override=year,
            period_override=period,
        )
    except DeclaracionParseError as exc:
        pytest.fail(
            f"PARSER-GAP [{pdf_stem}]: parse_declaracion raised — M303 legacy extraction failed.\n  error: {exc}",
        )

    extracted = {v.casilla_id: v.printed_value for v in filing.values}

    for required_id in ("27", "45", "iva.resultado-regimen-general"):
        assert required_id in extracted, (
            f"PARSER-GAP [{pdf_stem}]: required casilla {required_id!r} not in extracted values.\n"
            f"  got: {sorted(extracted)}"
        )

    # Build inputs — supply only non-computed Decimal casillas.
    inputs: dict[str, Decimal] = {}
    for casilla_id, value in extracted.items():
        if casilla_id in _COMPUTED_CASILLAS_M303 and casilla_id not in _DR303_PROJECTION_CASILLAS:
            continue
        if not isinstance(value, Decimal):
            continue
        inputs[casilla_id] = value

    _extracted_comp = extracted.get("iva.compensacion-pendiente-periodos-anteriores", Decimal("0"))
    _comp = _extracted_comp if isinstance(_extracted_comp, Decimal) else Decimal("0")
    binding_values: dict[str, Decimal] = {
        "modelo-303-compensacion-pendiente-anteriores": _comp,
    }

    _period_month = {"1T": 1, "2T": 4, "3T": 7, "4T": 10}[period]
    snapshot = _registry_snapshot("303", year, period)

    try:
        result = calculate_registry_snapshot(
            snapshot,
            inputs=inputs,
            date_context={"filing_period": date(year, _period_month, 1)},
            binding_values=binding_values,
        )
    except RegistryValidationError as exc:
        pytest.fail(
            f"BINDING-GAP [{pdf_stem}]: calculate_registry_snapshot raised "
            f"RegistryValidationError — a required binding is missing.\n"
            f"  error: {exc}\n"
            f"  inputs supplied: {sorted(inputs)}\n"
            f"  binding_values supplied: {sorted(binding_values)}",
        )

    engine_values = dict(result.values)

    # VERIFIED gate: engine resultado must equal extracted printed box 46.
    engine_resultado = engine_values.get("iva.resultado-regimen-general")
    assert engine_resultado is not None, (
        f"VERIFIED-FAIL [{pdf_stem}]: 'iva.resultado-regimen-general' absent from engine result"
    )
    extracted_resultado = extracted.get("iva.resultado-regimen-general")
    assert isinstance(extracted_resultado, Decimal), (
        f"VERIFIED-FAIL [{pdf_stem}]: extracted 'iva.resultado-regimen-general' is not Decimal: {extracted_resultado!r}"
    )
    assert engine_resultado == extracted_resultado, (
        f"VERIFIED-FAIL [{pdf_stem}]: engine resultado-regimen-general "
        f"{engine_resultado!r} != extracted {extracted_resultado!r}\n"
        f"  (engine formula or fixture inconsistency — box 46 = box 27 − box 45,\n"
        f"   Orden EHA/3786/2008 art. 1)"
    )
    engine_27 = engine_values.get("27")
    engine_45 = engine_values.get("45")
    assert isinstance(engine_27, Decimal), (
        f"VERIFIED-FAIL [{pdf_stem}]: engine-computed box 27 missing or non-Decimal: {engine_27!r}"
    )
    assert isinstance(engine_45, Decimal), (
        f"VERIFIED-FAIL [{pdf_stem}]: engine-computed box 45 missing or non-Decimal: {engine_45!r}"
    )
    expected_resultado = engine_27 - engine_45
    assert engine_resultado == expected_resultado, (
        f"VERIFIED-FAIL [{pdf_stem}]: engine resultado-regimen-general "
        f"{engine_resultado!r} != box27({engine_27!r}) - box45({engine_45!r}) = {expected_resultado!r}\n"
        f"  (internal formula consistency broken — registry formula defect)"
    )
