from __future__ import annotations

import pytest

from ._verification_chain_support import (
    _COMPUTED_CASILLAS_M303,
    _DR303_PROJECTION_CASILLAS,
    _M303_COMPENSACION_PENDIENTE_ANTERIORES_CASILLA,
    _M303_CUOTA_DEDUCIBLE_TOTAL_CASILLA,
    _M303_CUOTA_DEVENGADA_TOTAL_CASILLA,
    _M303_ENGINE_REQUIRED_CASILLAS,
    _M303_RESULTADO_REGIMEN_GENERAL_CASILLA,
    BindingId,
    Decimal,
    RegistryValidationError,
    _assert_m303_engine_matches_extracted_decimal,
    _decimal_inputs_from_extracted_values,
    _parse_extracted_declaracion_values,
    _registry_snapshot,
    calculate_registry_snapshot,
    date,
)

pytestmark = [pytest.mark.unit, pytest.mark.hex_inbound_adapter]


@pytest.mark.parametrize(
    "pdf_stem,year,period",
    [
        ("2021-2T", 2021, "2T"),
        ("2021-3T", 2021, "3T"),
        ("2021-4T", 2021, "4T"),
        ("2022-1T", 2022, "1T"),
        ("2022-2T", 2022, "2T"),
        ("2022-3T", 2022, "3T"),
        ("2022-4T", 2022, "4T"),
    ],
)
def test_verification_chain_m303_historical_engine_recomputes_resultado_regimen_general(
    pdf_stem: str,
    year: int,
    period: str,
) -> None:
    """Engine resultado-regimen-general matches extracted box 46 for historical fixtures.

    GROUNDED authority: Orden EHA/3786/2008 art. 1 - box 46 = box 27 - box 45.
    The 2009-y-siguientes revision covers ejercicios 2009-2022 and uses the same
    formula. The historical extraction profile extracts 4 casillas: 27, 29, 45, and
    iva.resultado-regimen-general.

    The historical corpus PDFs are synthetic fixtures generated by _generate.py
    with formula-consistent values: c46 = c27 - c45.

    Verdict: VERIFIED - engine resultado == extracted resultado for all 7
    historical specimens (2021-2022). Corpus-regenerated with
    formula-consistent synthetic values.
    """
    extracted = _parse_extracted_declaracion_values(modelo="303", fixture_stem=pdf_stem, year=year, period=period)

    for required_id in _M303_ENGINE_REQUIRED_CASILLAS:
        assert required_id in extracted, (
            f"PARSER-GAP [{pdf_stem}]: required casilla {required_id!r} not in extracted values.\n"
            f"  got: {sorted(extracted)}"
        )

    inputs = _decimal_inputs_from_extracted_values(
        extracted,
        excluding=_COMPUTED_CASILLAS_M303 - _DR303_PROJECTION_CASILLAS,
    )

    _extracted_comp = extracted.get(_M303_COMPENSACION_PENDIENTE_ANTERIORES_CASILLA, Decimal("0"))
    _comp = _extracted_comp if isinstance(_extracted_comp, Decimal) else Decimal("0")
    binding_values: dict[BindingId, Decimal] = {
        "modelo-303-compensacion-pendiente-anteriores": _comp,
    }

    _period_month = {"1T": 1, "2T": 4, "3T": 7, "4T": 10}[period]
    snapshot = _registry_snapshot("303", year, period)

    try:
        result = calculate_registry_snapshot(
            snapshot,
            inputs=inputs,
            date_context={"filing_period": date(year, _period_month, 1)},
            binding_values=binding_values,
        )
    except RegistryValidationError as exc:
        pytest.fail(
            f"BINDING-GAP [{pdf_stem}]: calculate_registry_snapshot raised "
            f"RegistryValidationError - a required binding is missing.\n"
            f"  error: {exc}\n"
            f"  inputs supplied: {sorted(inputs)}\n"
            f"  binding_values supplied: {sorted(binding_values)}",
        )

    engine_values = dict(result.values)

    engine_resultado = _assert_m303_engine_matches_extracted_decimal(
        pdf_stem=pdf_stem,
        engine_values=engine_values,
        extracted=extracted,
        casilla_id=_M303_RESULTADO_REGIMEN_GENERAL_CASILLA,
        label="box 46 (resultado regimen general)",
        formula_context="box 46 = box 27 - box 45, Orden EHA/3786/2008 art. 1",
    )
    engine_27 = engine_values.get(_M303_CUOTA_DEVENGADA_TOTAL_CASILLA)
    engine_45 = engine_values.get(_M303_CUOTA_DEDUCIBLE_TOTAL_CASILLA)
    assert isinstance(engine_27, Decimal), (
        f"VERIFIED-FAIL [{pdf_stem}]: engine-computed box 27 missing or non-Decimal: {engine_27!r}"
    )
    assert isinstance(engine_45, Decimal), (
        f"VERIFIED-FAIL [{pdf_stem}]: engine-computed box 45 missing or non-Decimal: {engine_45!r}"
    )
    expected_resultado = engine_27 - engine_45
    assert engine_resultado == expected_resultado, (
        f"VERIFIED-FAIL [{pdf_stem}]: engine resultado-regimen-general "
        f"{engine_resultado!r} != box27({engine_27!r}) - box45({engine_45!r}) = {expected_resultado!r}\n"
        f"  (internal formula consistency broken - registry formula defect)"
    )
