"""Focused adapter contract tests split from the original monolith."""

from __future__ import annotations

import pytest

from ._verification_chain_support import (
    _COMPUTED_CASILLAS_M115,
    _COMPUTED_CASILLAS_M123_2019,
    _COMPUTED_CASILLAS_M123_2024,
    _COMPUTED_CASILLAS_M131,
    _COMPUTED_CASILLAS_M390,
    FIXTURES_DIR,
    CasillaObservation,
    Decimal,
    DeclaracionParseError,
    RegistryModeloObservation,
    RegistryValidationError,
    _period_to_date,
    _registry_snapshot,
    calculate_registry_snapshot,
    date,
    parse_declaracion,
    resolve_relation_values_from_observations,
)

pytestmark = [pytest.mark.unit, pytest.mark.hex_inbound_adapter]


@pytest.mark.parametrize(
    "pdf_stem,year",
    [
        ("2022-0A", 2022),
        ("2023-0A", 2023),
    ],
)
def test_verification_chain_m390_engine_recomputes_cuota_devengada_deducible(pdf_stem: str, year: int) -> None:
    """Engine recomputes all three M390 closure casillas and they match the printed values.

    GROUNDED authority: synthetic formula-consistent corpus fixtures generated by
    _generate.py (_Modelo390CorpusFixture) at src/aeat/tests/fixtures/justificantes/390/.
    Fixtures replaced the sanitised-real-form PDFs (which had uniform 1.000,00
    for all amounts, making resultado-regimen-general arithmetically inconsistent).

    Formula DAG:
      iva.anual.cuota-devengada-total =
          iva.anual.repercutido.general (box 06, 21% régimen ordinario)
          + iva.anual.repercutido.reducido (box 04, 10% régimen ordinario)
          + iva.anual.repercutido.super-reducido (box 02, 4% régimen ordinario)
          + iva.anual.autorepercutido.intracomunitaria (box 26, adq.intracom 21%)

      iva.anual.cuota-deducible-total =
          iva.anual.soportado.interiores (box 49, total cuotas ded. corrientes)
          + iva.anual.autorepercutido.intracomunitaria (box 26, same binding)

      iva.anual.resultado-regimen-general =
          iva.anual.cuota-devengada-total - iva.anual.cuota-deducible-total

    The leaf casillas (boxes 02/04/06/26/49) are extracted via bbox_anchored
    targets in the declaracion_pdf profile and supplied as engine inputs.

    Verdict per casilla (both 2022-0A and 2023-0A specimens):
      iva.anual.cuota-devengada-total  (box 47): VERIFIED
      iva.anual.cuota-deducible-total  (box 64): VERIFIED
      iva.anual.resultado-regimen-general (box 65): VERIFIED
    """
    pdf_path = FIXTURES_DIR / "justificantes" / "390" / f"{pdf_stem}.pdf"

    try:
        filing = parse_declaracion(
            pdf_path,
            modelo_override="390",
            año_override=year,
            period_override="0A",
        )
    except DeclaracionParseError as exc:
        pytest.fail(f"PARSER-GAP [{pdf_stem}]: parse_declaracion raised — M390 extraction failed.\n  error: {exc}")

    extracted = {v.casilla_id: v.printed_value for v in filing.values}

    # Verify the profile captured the required closure casillas.
    for required_id in ("iva.anual.cuota-devengada-total", "iva.anual.cuota-deducible-total"):
        assert required_id in extracted, (
            f"PARSER-GAP [{pdf_stem}]: closure casilla {required_id!r} "
            f"not in extracted values — parser did not capture it.\n  got: {sorted(extracted)}"
        )

    # Build inputs — supply only non-computed Decimal casillas.
    # Leaf bound casillas (repercutido.general, etc.) are non-previous_filing
    # and therefore go into inputs (engine defaults absent ones to ZERO).
    inputs: dict[str, Decimal] = {}
    for casilla_id, value in extracted.items():
        if casilla_id in _COMPUTED_CASILLAS_M390:
            continue
        if not isinstance(value, Decimal):
            continue
        inputs[casilla_id] = value

    # The five previous_filing bindings must be explicitly supplied or the engine
    # raises RegistryValidationError. For the two compensation casillas whose values
    # were extracted from the corpus PDF (boxes 97 and 662), use the extracted value
    # as the binding value — the consistency check requires inputs and
    # binding_values to agree when both are populated. For the three reconciliation
    # casillas (devengada/deducible/resultado from M303), supply zero because no
    # M303 quarterly filings exist for the sanitised corpus specimens.
    _extracted_comp_97 = extracted.get("iva.anual.compensacion-ultimo-periodo-97", Decimal("0"))
    _comp_97 = _extracted_comp_97 if isinstance(_extracted_comp_97, Decimal) else Decimal("0")
    _extracted_comp_662 = extracted.get("iva.anual.compensacion-generada-ejercicio-no-97", Decimal("0"))
    _comp_662 = _extracted_comp_662 if isinstance(_extracted_comp_662, Decimal) else Decimal("0")
    binding_values: dict[str, Decimal] = {
        "modelo-390-prev-303-cuota-devengada-total": Decimal("0"),
        "modelo-390-prev-303-cuota-deducible-total": Decimal("0"),
        "modelo-390-prev-303-resultado-regimen-general": Decimal("0"),
        "modelo-390-prev-303-compensacion-ultimo-periodo": _comp_97,
        "modelo-390-prev-303-compensacion-generada-ejercicio-no-97": _comp_662,
    }

    snapshot = _registry_snapshot("390", year, "0A")

    try:
        result = calculate_registry_snapshot(
            snapshot,
            inputs=inputs,
            date_context={"filing_period": date(year, 12, 31)},
            binding_values=binding_values,
        )
    except RegistryValidationError as exc:
        pytest.fail(
            f"BINDING-GAP [{pdf_stem}]: calculate_registry_snapshot raised "
            f"RegistryValidationError — a required binding is missing.\n"
            f"  error: {exc}\n"
            f"  inputs supplied: {sorted(inputs)}\n"
            f"  binding_values supplied: {sorted(binding_values)}",
        )

    engine_values = dict(result.values)

    # VERIFIED: cuota-devengada-total (box 47).
    extracted_devengada = extracted["iva.anual.cuota-devengada-total"]
    engine_devengada = engine_values.get("iva.anual.cuota-devengada-total")
    assert isinstance(extracted_devengada, Decimal)
    assert engine_devengada is not None, (
        f"FORMULA-MISMATCH [{pdf_stem}]: 'iva.anual.cuota-devengada-total' absent from engine result"
    )
    assert engine_devengada == extracted_devengada, (
        f"FORMULA-MISMATCH [{pdf_stem}]: engine recomputed cuota-devengada-total as "
        f"{engine_devengada!r} but corpus printed form shows {extracted_devengada!r}.\n"
        f"  leaf inputs: repercutido.general={inputs.get('iva.anual.repercutido.general', Decimal('0'))!r} "
        f"reducido={inputs.get('iva.anual.repercutido.reducido', Decimal('0'))!r} "
        f"super-reducido={inputs.get('iva.anual.repercutido.super-reducido', Decimal('0'))!r} "
        f"autorepercutido={inputs.get('iva.anual.autorepercutido.intracomunitaria', Decimal('0'))!r}"
    )

    # VERIFIED: cuota-deducible-total (box 64).
    extracted_deducible = extracted["iva.anual.cuota-deducible-total"]
    engine_deducible = engine_values.get("iva.anual.cuota-deducible-total")
    assert isinstance(extracted_deducible, Decimal)
    assert engine_deducible is not None, (
        f"FORMULA-MISMATCH [{pdf_stem}]: 'iva.anual.cuota-deducible-total' absent from engine result"
    )
    assert engine_deducible == extracted_deducible, (
        f"FORMULA-MISMATCH [{pdf_stem}]: engine recomputed cuota-deducible-total as "
        f"{engine_deducible!r} but corpus printed form shows {extracted_deducible!r}.\n"
        f"  leaf inputs: soportado.interiores={inputs.get('iva.anual.soportado.interiores', Decimal('0'))!r} "
        f"autorepercutido={inputs.get('iva.anual.autorepercutido.intracomunitaria', Decimal('0'))!r}"
    )

    # VERIFIED: resultado-regimen-general (box 65).
    # The synthetic fixtures are formula-consistent: leaf inputs are chosen so that
    # resultado = devengada - deducible matches the printed box 65 value exactly.
    engine_resultado = engine_values.get("iva.anual.resultado-regimen-general")
    extracted_resultado = extracted.get("iva.anual.resultado-regimen-general")
    assert engine_resultado is not None, (
        f"VERIFIED-FAIL [{pdf_stem}]: 'iva.anual.resultado-regimen-general' absent from engine result"
    )
    assert isinstance(extracted_resultado, Decimal), (
        f"VERIFIED-FAIL [{pdf_stem}]: extracted resultado-regimen-general is not Decimal: {extracted_resultado!r}"
    )
    assert engine_resultado == extracted_resultado, (
        f"VERIFIED-FAIL [{pdf_stem}]: engine resultado-regimen-general "
        f"{engine_resultado!r} ≠ extracted printed box65 {extracted_resultado!r}.\n"
        f"  engine devengada={engine_devengada!r} engine deducible={engine_deducible!r}"
    )


def test_verification_chain_m180_parser_extracts_declaracion_pdf_casillas() -> None:
    """Parser extracts the 3 M180 summary casillas from the synthetic corpus fixture.

    GROUNDED authority: synthetic fixture generated from AEAT-published printed
    form text (src/aeat/tests/fixtures/justificantes/180/2024-0A.pdf).

    The M180 formulas aggregate M115 quarterly relation values — the
    decl.retenciones-total formula uses { relation = "modelo-180-rel-115-retenciones-anual" }.
    Extraction verdict: VERIFIED.  Engine verdict: see the companion test
    test_verification_chain_m180_engine_recomputes_closure_casillas_from_m115_relation_values.
    """
    pdf_path = FIXTURES_DIR / "justificantes" / "180" / "2024-0A.pdf"

    try:
        filing = parse_declaracion(
            pdf_path,
            modelo_override="180",
            año_override=2024,
            period_override="0A",
        )
    except DeclaracionParseError as exc:
        pytest.fail(f"PARSER-GAP [M180/2024-0A]: parse_declaracion raised.\n  error: {exc}")

    extracted = {v.casilla_id: v.printed_value for v in filing.values}
    assert set(extracted.keys()) == {
        "decl.total-perceptores",
        "decl.base-total",
        "decl.retenciones-total",
    }, f"PARSER-GAP [M180/2024-0A]: unexpected casilla set.\n  got: {sorted(extracted)}"
    for casilla_id, value in extracted.items():
        assert isinstance(value, Decimal), (
            f"PARSER-GAP [M180/2024-0A]: casilla {casilla_id!r} not Decimal: {type(value).__name__!r}"
        )


def test_verification_chain_m180_engine_recomputes_closure_casillas_from_m115_relation_values() -> None:
    """Engine recomputes M180 annual closure casillas from M115 quarterly relation values.

    GROUNDED authority: synthetic M180 fixture at
    src/aeat/tests/fixtures/justificantes/180/2024-0A.pdf, derived from
    AEAT Orden HAP/1732/2014 printed form structure.  The fixture prints:
      decl.total-perceptores = 3    (sum of M115 casilla 01 across 4 quarters)
      decl.base-total        = 12 000.00  (sum of M115 casilla 02 across 4 quarters)
      decl.retenciones-total =  2 280.00  (sum of M115 casilla 03 across 4 quarters)

    Legal grounding: Ley 35/2006 art.99; RD 439/2007 arts.100,108,109;
    Orden HAP/1732/2014 art.2; Orden HFP/1284/2023 art.7.

    Chain:
      1. Parse the 2024-0A M180 fixture → extracted closure values.
      2. Build M115 quarterly observations (4 quarters, filing year 2024)
         whose sum matches each extracted M180 total:
           Q1 casilla 01=1, 02=3 000.00, 03=570.00
           Q2 casilla 01=1, 02=3 000.00, 03=570.00
           Q3 casilla 01=1, 02=3 000.00, 03=570.00
           Q4 casilla 01=0, 02=3 000.00, 03=570.00   ← sum 01=3, 02=12000, 03=2280
      3. Resolve relation_values via resolve_relation_values_from_observations.
      4. calculate_registry_snapshot(M180 snapshot, inputs={}, relation_values=...).
      5. Assert engine values == extracted values for all 3 closure casillas.

    Verdict: VERIFIED — the M115→M180 cross-modelo relation binding resolves
    and the engine aggregation formula chain is functionally correct.
    """
    pdf_path = FIXTURES_DIR / "justificantes" / "180" / "2024-0A.pdf"

    # Parse the printed M180 form: these are the AEAT-grounded expected values.
    try:
        filing = parse_declaracion(
            pdf_path,
            modelo_override="180",
            año_override=2024,
            period_override="0A",
        )
    except DeclaracionParseError as exc:
        pytest.fail(f"PARSER-GAP [M180/2024-0A engine]: parse_declaracion raised.\n  error: {exc}")

    extracted = {v.casilla_id: v.printed_value for v in filing.values}

    # Build M115 quarterly observations whose sum matches the M180 fixture totals.
    # Values chosen so that sum(Q1..Q4) equals each extracted M180 closure value.
    # M115 casilla 01 (integer): 1+1+1+0 = 3 == extracted["decl.total-perceptores"]
    # M115 casilla 02 (money):   3000+3000+3000+3000 = 12000.00 == extracted["decl.base-total"]
    # M115 casilla 03 (money):   570+570+570+570 = 2280.00 == extracted["decl.retenciones-total"]
    _m115_quarterly: dict[str, dict[str, Decimal]] = {
        "1T": {"01": Decimal("1"), "02": Decimal("3000.00"), "03": Decimal("570.00")},
        "2T": {"01": Decimal("1"), "02": Decimal("3000.00"), "03": Decimal("570.00")},
        "3T": {"01": Decimal("1"), "02": Decimal("3000.00"), "03": Decimal("570.00")},
        "4T": {"01": Decimal("0"), "02": Decimal("3000.00"), "03": Decimal("570.00")},
    }
    observations = tuple(
        RegistryModeloObservation(
            modelo="115",
            filing_year=2024,
            period=period,
            observations=tuple(CasillaObservation(casilla_id=cid, value=val) for cid, val in casilla_values.items()),
        )
        for period, casilla_values in sorted(_m115_quarterly.items())
    )

    # Resolve relation_values for the M180 2023-y-siguientes snapshot.
    snapshot = _registry_snapshot("180", 2024, "0A")
    try:
        relation_values = resolve_relation_values_from_observations(
            snapshot.revision,
            observations,
            filing_year=2024,
            period="0A",
        )
    except RegistryValidationError as exc:
        pytest.fail(
            f"BINDING-GAP [M180/2024-0A engine]: resolve_relation_values_from_observations raised "
            f"RegistryValidationError — M115→M180 relation chain is structurally broken.\n"
            f"  error: {exc}",
        )

    # Run the calculation engine.
    try:
        result = calculate_registry_snapshot(
            snapshot,
            inputs={},
            date_context={"filing_period": date(2024, 12, 31)},
            relation_values=relation_values,
        )
    except RegistryValidationError as exc:
        pytest.fail(
            f"BINDING-GAP [M180/2024-0A engine]: calculate_registry_snapshot raised "
            f"RegistryValidationError — engine could not recompute from supplied relation_values.\n"
            f"  error: {exc}\n"
            f"  relation_values keys: {sorted(relation_values)}",
        )

    # Assert engine closure values match AEAT-grounded extracted values.
    engine_values = dict(result.values)

    for casilla_id in ("decl.total-perceptores", "decl.base-total", "decl.retenciones-total"):
        extracted_value = extracted.get(casilla_id)
        engine_value = engine_values.get(casilla_id)
        assert extracted_value is not None, (
            f"PARSER-GAP [M180/2024-0A engine]: closure casilla {casilla_id!r} absent from extracted values"
        )
        assert isinstance(extracted_value, Decimal), (
            f"PARSER-GAP [M180/2024-0A engine]: {casilla_id!r} is not Decimal: {type(extracted_value).__name__!r}"
        )
        assert engine_value is not None, (
            f"FORMULA-MISMATCH [M180/2024-0A engine]: casilla {casilla_id!r} absent from engine result — "
            f"formula evaluation order issue or casilla missing from revision."
        )
        assert engine_value == extracted_value, (
            f"FORMULA-MISMATCH [M180/2024-0A engine]: engine recomputed {casilla_id!r} as "
            f"{engine_value!r} but AEAT-printed fixture shows {extracted_value!r}.\n"
            f"  diff: {engine_value - extracted_value!r}\n"
            f"  relation_values supplied: {relation_values}"
        )


def test_verification_chain_m190_parser_extracts_declaracion_pdf_casillas() -> None:
    """Parser extracts the 3 M190 summary casillas from the real corpus PDF.

    GROUNDED authority: real AEAT corpus PDF (sanitised) committed at
    src/aeat/tests/fixtures/justificantes/190/2024-0A.pdf.

    The M190 registry has no formulas — retenciones-total is an aggregation of
    perceptor-level withholding records, not a computed formula. Verdict:
    BINDING-GAP for formula verification — no formula to exercise. This test
    verifies the extraction side of the chain.
    """
    pdf_path = FIXTURES_DIR / "justificantes" / "190" / "2024-0A.pdf"

    try:
        filing = parse_declaracion(
            pdf_path,
            modelo_override="190",
            año_override=2024,
            period_override="0A",
        )
    except DeclaracionParseError as exc:
        pytest.fail(f"PARSER-GAP [M190/2024-0A]: parse_declaracion raised.\n  error: {exc}")

    extracted = {v.casilla_id: v.printed_value for v in filing.values}
    assert "decl.retenciones-total" in extracted, (
        f"PARSER-GAP [M190/2024-0A]: 'decl.retenciones-total' not extracted.\n  got: {sorted(extracted)}"
    )
    assert isinstance(extracted["decl.retenciones-total"], Decimal), (
        "PARSER-GAP [M190/2024-0A]: 'decl.retenciones-total' not Decimal"
    )


def test_verification_chain_m115_engine_recomputes_retenciones_and_resultado() -> None:
    """Engine recomputes casilla 03 (retenciones) and 05 (resultado) from leaf inputs.

    GROUNDED authority: synthetic fixture generated from AEAT-published Diseno de
    Registro DR xls (aeat-dr-115-2019-v13) committed at
    src/aeat/tests/fixtures/justificantes/115/2024-1T.pdf.

    Chain:
      1. parse_declaracion → extracted casillas 01 (perceptores), 02 (base),
         03 (retenciones), 04 (anteriores declaraciones), 05 (resultado a ingresar).
      2. Filter to non-computed casillas (01, 02, 04) → inputs.
      3. calculate_registry_snapshot with no binding_values (no previous_filing bindings).
      4. Assert engine.values["03"] == extracted["03"] (VERIFIED).
         Assert engine.values["05"] == extracted["05"] (VERIFIED).

    Legal grounding: RD 439/2007 art.100, art.108; Ley 35/2006 art.99, art.101;
    Orden 2000-11-20 apartado primero.

    Verdict: VERIFIED — the percent formula for retenciones and the subtract formula
    for resultado both match the synthetic AEAT-grounded fixture.
    """
    pdf_path = FIXTURES_DIR / "justificantes" / "115" / "2024-1T.pdf"

    try:
        filing = parse_declaracion(
            pdf_path,
            modelo_override="115",
            año_override=2024,
            period_override="1T",
        )
    except DeclaracionParseError as exc:
        pytest.fail(f"PARSER-GAP [M115/2024-1T]: parse_declaracion raised.\n  error: {exc}")

    extracted = {v.casilla_id: v.printed_value for v in filing.values}

    for required_id in ("01", "02", "03", "04", "05"):
        assert required_id in extracted, (
            f"PARSER-GAP [M115/2024-1T]: casilla {required_id!r} not extracted.\n  got: {sorted(extracted)}"
        )

    inputs: dict[str, Decimal] = {
        cid: val for cid, val in extracted.items() if cid not in _COMPUTED_CASILLAS_M115 and isinstance(val, Decimal)
    }

    snapshot = _registry_snapshot("115", 2024, "1T")
    filing_period_date = _period_to_date(2024, "1T")

    try:
        result = calculate_registry_snapshot(
            snapshot,
            inputs=inputs,
            date_context={"filing_period": filing_period_date},
        )
    except RegistryValidationError as exc:
        pytest.fail(
            f"BINDING-GAP [M115/2024-1T]: calculate_registry_snapshot raised "
            f"RegistryValidationError.\n  error: {exc}\n  inputs: {sorted(inputs)}",
        )

    engine_values = dict(result.values)

    for closure_id in ("03", "05"):
        extracted_val = extracted[closure_id]
        assert isinstance(extracted_val, Decimal)
        engine_val = engine_values.get(closure_id)
        assert engine_val is not None, (
            f"FORMULA-MISMATCH [M115/2024-1T]: casilla {closure_id!r} absent from engine result."
        )
        assert engine_val == extracted_val, (
            f"FORMULA-MISMATCH [M115/2024-1T]: engine casilla {closure_id!r} = {engine_val!r}, "
            f"AEAT-printed = {extracted_val!r}.\n"
            f"  inputs: {inputs}"
        )


@pytest.mark.parametrize(
    "pdf_stem,year,period,computed_set,closure_ids",
    [
        ("2023-1T", 2023, "1T", _COMPUTED_CASILLAS_M123_2019, ("06-legacy", "08-legacy")),
        ("2024-1T", 2024, "1T", _COMPUTED_CASILLAS_M123_2024, ("03", "06", "09", "12", "14")),
    ],
)
def test_verification_chain_m123_engine_recomputes_closure_casillas(
    pdf_stem: str,
    year: int,
    period: str,
    computed_set: frozenset[str],
    closure_ids: tuple[str, ...],
) -> None:
    """Engine recomputes M123 closure casillas from leaf inputs.

    GROUNDED authority: synthetic fixtures from AEAT-published Diseno de Registro
    committed at src/aeat/tests/fixtures/justificantes/123/.

    2023-1T (2019-2023 revision):
      06-legacy = 03-legacy + 05-legacy  (total liquidación)
      08-legacy = 06-legacy - 07-legacy  (resultado a ingresar)
      Fixture prints: 01=4, 02=8000, 03=1520, 04=0, 05=0, 06=1520, 07=0, 08=1520.

    2024-1T (2024-y-siguientes revision):
      03 = 01 + 02   (total rentas categoría 1)
      06 = 04 + 05   (total base)
      09 = 07 + 08   (total retenciones)
      12 = 10 + 11   (total cuota)
      14 = 12 - 13   (resultado a ingresar)
      Fixture prints: 01=5, 02=3, 03=8, 04=10000, 05=5000, 06=15000, 07=1900,
        08=950, 09=2850, 10=0, 11=0, 12=2850, 13=0, 14=2850.

    Legal grounding: Ley 35/2006 art.25, art.99; RD 439/2007 art.109, art.108,
    art.90, art.101; Orden EHA/3435/2007 Anexo II.

    Verdict: VERIFIED for all closure casillas in both revisions.
    """
    pdf_path = FIXTURES_DIR / "justificantes" / "123" / f"{pdf_stem}.pdf"

    try:
        filing = parse_declaracion(
            pdf_path,
            modelo_override="123",
            año_override=year,
            period_override=period,
        )
    except DeclaracionParseError as exc:
        pytest.fail(f"PARSER-GAP [M123/{pdf_stem}]: parse_declaracion raised.\n  error: {exc}")

    extracted = {v.casilla_id: v.printed_value for v in filing.values}

    inputs: dict[str, Decimal] = {
        cid: val for cid, val in extracted.items() if cid not in computed_set and isinstance(val, Decimal)
    }

    snapshot = _registry_snapshot("123", year, period)
    filing_period_date = _period_to_date(year, period)

    try:
        result = calculate_registry_snapshot(
            snapshot,
            inputs=inputs,
            date_context={"filing_period": filing_period_date},
        )
    except RegistryValidationError as exc:
        pytest.fail(
            f"BINDING-GAP [M123/{pdf_stem}]: calculate_registry_snapshot raised "
            f"RegistryValidationError.\n  error: {exc}\n  inputs: {sorted(inputs)}",
        )

    engine_values = dict(result.values)

    for closure_id in closure_ids:
        if closure_id not in extracted:
            continue
        extracted_val = extracted[closure_id]
        assert isinstance(extracted_val, Decimal), (
            f"PARSER-GAP [M123/{pdf_stem}]: casilla {closure_id!r} is not Decimal: {type(extracted_val).__name__!r}"
        )
        engine_val = engine_values.get(closure_id)
        assert engine_val is not None, (
            f"FORMULA-MISMATCH [M123/{pdf_stem}]: casilla {closure_id!r} absent from engine result."
        )
        assert engine_val == extracted_val, (
            f"FORMULA-MISMATCH [M123/{pdf_stem}]: engine casilla {closure_id!r} = {engine_val!r}, "
            f"AEAT-printed = {extracted_val!r}.\n  inputs: {inputs}"
        )


def test_verification_chain_m131_engine_recomputes_closure_casillas() -> None:
    """Engine recomputes M131 closure casillas from leaf inputs.

    GROUNDED authority: synthetic fixture committed at
    src/aeat/tests/fixtures/justificantes/131/2024-1T.pdf.
    The fixture encodes filing year 2026 (detected from PDF header).
    Registry revision '2026' is used.

    Chain:
      1. parse_declaracion with año_override=2026, period_override='1T'.
      2. Filter to non-computed casillas (01, 02, 03, 05, 08, 09, 12, 14) → inputs.
      3. Supply binding_values for casilla 11 (previous-filing bound):
         modelo-131-2026-resultados-negativos-anteriores = 0.
      4. calculate_registry_snapshot.
      5. Assert engine computes:
         07 = 02 + 04 + 06
         10 = 07 - 08 - 09
         13 = 10 - 11 - 12
         15 = 13 - 14

    Fixture values: 01=5000, 02=100, 03=0, 05=0, 07=100 (computed), 08=0, 09=0,
      10=100 (computed), 11=0, 12=0, 13=100 (computed), 14=0, 15=100 (computed).

    Legal grounding: RD 439/2007 art.110, art.95; Orden EHA/672/2007 art.1;
    Orden HFP/1359/2023 art.4.

    Verdict: VERIFIED — all four formula closure casillas match fixture values.
    """
    pdf_path = FIXTURES_DIR / "justificantes" / "131" / "2024-1T.pdf"

    try:
        filing = parse_declaracion(
            pdf_path,
            modelo_override="131",
            año_override=2026,
            template_revision_override="2026",
            period_override="1T",
        )
    except DeclaracionParseError as exc:
        detail = exc.translated_message or str(exc) or type(exc).__name__
        context = exc.context if exc.context else {}
        pytest.fail(
            f"PARSER-GAP [M131/2024-1T.pdf/yr=2026]: parse_declaracion raised.\n  error: {detail} (context={context})",
        )

    extracted = {v.casilla_id: v.printed_value for v in filing.values}

    inputs: dict[str, Decimal] = {
        cid: val for cid, val in extracted.items() if cid not in _COMPUTED_CASILLAS_M131 and isinstance(val, Decimal)
    }

    binding_values: dict[str, Decimal] = {
        "modelo-131-2026-resultados-negativos-anteriores": Decimal("0"),
    }

    snapshot = _registry_snapshot("131", 2026, "1T")
    filing_period_date = _period_to_date(2026, "1T")

    try:
        result = calculate_registry_snapshot(
            snapshot,
            inputs=inputs,
            date_context={"filing_period": filing_period_date},
            binding_values=binding_values,
        )
    except RegistryValidationError as exc:
        pytest.fail(
            f"BINDING-GAP [M131/yr=2026-1T]: calculate_registry_snapshot raised "
            f"RegistryValidationError.\n  error: {exc}\n"
            f"  inputs: {sorted(inputs)}\n  binding_values: {sorted(binding_values)}",
        )

    engine_values = dict(result.values)

    for closure_id in ("07", "10", "13", "15"):
        if closure_id not in extracted:
            continue
        extracted_val = extracted[closure_id]
        assert isinstance(extracted_val, Decimal)
        engine_val = engine_values.get(closure_id)
        assert engine_val is not None, (
            f"FORMULA-MISMATCH [M131/yr=2026-1T]: casilla {closure_id!r} absent from engine result."
        )
        assert engine_val == extracted_val, (
            f"FORMULA-MISMATCH [M131/yr=2026-1T]: engine casilla {closure_id!r} = {engine_val!r}, "
            f"AEAT-printed = {extracted_val!r}.\n  inputs: {inputs}"
        )


def test_verification_chain_m193_parser_extracts_declaracion_pdf_casillas() -> None:
    """Parser extracts the 3 M193 summary casillas from the synthetic corpus fixture.

    GROUNDED authority: synthetic fixture generated from AEAT-published Diseno de
    Registro DR_Modelo_193_2024.pdf committed at
    src/aeat/tests/fixtures/justificantes/193/2024-0A.pdf.

    Extraction verdict: VERIFIED. Engine verdict: see the companion test
    test_verification_chain_m193_engine_recomputes_closure_casillas_from_m123_relation_values.
    """
    pdf_path = FIXTURES_DIR / "justificantes" / "193" / "2024-0A.pdf"

    try:
        filing = parse_declaracion(
            pdf_path,
            modelo_override="193",
            año_override=2024,
            period_override="0A",
        )
    except DeclaracionParseError as exc:
        pytest.fail(f"PARSER-GAP [M193/2024-0A]: parse_declaracion raised.\n  error: {exc}")

    extracted = {v.casilla_id: v.printed_value for v in filing.values}
    assert set(extracted.keys()) == {
        "decl.total-perceptores",
        "decl.base-total",
        "decl.retenciones-total",
    }, f"PARSER-GAP [M193/2024-0A]: unexpected casilla set.\n  got: {sorted(extracted)}"
    for casilla_id, value in extracted.items():
        assert isinstance(value, Decimal), (
            f"PARSER-GAP [M193/2024-0A]: casilla {casilla_id!r} not Decimal: {type(value).__name__!r}"
        )


def test_verification_chain_m193_engine_recomputes_closure_casillas_from_m123_relation_values() -> None:
    """Engine recomputes M193 annual closure casillas from M123 quarterly relation values.

    GROUNDED authority: synthetic M193 fixture at
    src/aeat/tests/fixtures/justificantes/193/2024-0A.pdf.  The fixture prints:
      decl.total-perceptores = 2     (sum of M123 casilla 03 across 4 quarters)
      decl.base-total        = 8 000.00  (sum of M123 casilla 06 across 4 quarters)
      decl.retenciones-total = 1 520.00  (sum of M123 casilla 09 across 4 quarters)

    Legal grounding: Ley 35/2006 art.25, art.99; RD 439/2007 art.109, art.108,
    art.90, art.101; Orden EHA/3377/2011 art.1; Ley 58/2003 art.93.

    Chain:
      1. Parse the 2024-0A M193 fixture → extracted closure values.
      2. Build M123 quarterly observations (4 quarters, filing year 2024)
         whose sum matches each extracted M193 total:
           Q1 casilla 03=2, 06=2000.00, 09=380.00
           Q2 casilla 03=0, 06=2000.00, 09=380.00
           Q3 casilla 03=0, 06=2000.00, 09=380.00
           Q4 casilla 03=0, 06=2000.00, 09=380.00  ← sum 03=2, 06=8000, 09=1520
      3. Resolve relation_values via resolve_relation_values_from_observations.
      4. calculate_registry_snapshot(M193 snapshot, inputs={}, relation_values=...).
      5. Assert engine values == extracted values for all 3 closure casillas.

    NOTE: The relation uses M123 2024-y-siguientes casillas 03, 06, 09 which are
    all computed by the engine (not manual inputs). The observations must supply
    them directly as CasillaObservation (representing engine-computed outputs from
    prior quarterly filing runs), not as engine inputs for the current run.

    Verdict: VERIFIED — the M123→M193 cross-modelo relation binding resolves
    and the engine aggregation formula chain is functionally correct.
    """
    pdf_path = FIXTURES_DIR / "justificantes" / "193" / "2024-0A.pdf"

    try:
        filing = parse_declaracion(
            pdf_path,
            modelo_override="193",
            año_override=2024,
            period_override="0A",
        )
    except DeclaracionParseError as exc:
        pytest.fail(f"PARSER-GAP [M193/2024-0A engine]: parse_declaracion raised.\n  error: {exc}")

    extracted = {v.casilla_id: v.printed_value for v in filing.values}

    # Build M123 quarterly observations whose sum matches the M193 fixture totals.
    # M123 casilla 03 = total-rentas (01+02); casilla 06 = total-base (04+05);
    # casilla 09 = total-retenciones (07+08).
    # Q1: 03=2, 06=2000.00, 09=380.00  (all values in decl.total-perceptores come from 1Q here)
    # Q2-Q4: 03=0, 06=2000.00, 09=380.00
    # Sums: 03 → 2, 06 → 8000.00, 09 → 1520.00
    _m123_quarterly: dict[str, dict[str, Decimal]] = {
        "1T": {"03": Decimal("2"), "06": Decimal("2000.00"), "09": Decimal("380.00")},
        "2T": {"03": Decimal("0"), "06": Decimal("2000.00"), "09": Decimal("380.00")},
        "3T": {"03": Decimal("0"), "06": Decimal("2000.00"), "09": Decimal("380.00")},
        "4T": {"03": Decimal("0"), "06": Decimal("2000.00"), "09": Decimal("380.00")},
    }
    observations = tuple(
        RegistryModeloObservation(
            modelo="123",
            filing_year=2024,
            period=period,
            observations=tuple(CasillaObservation(casilla_id=cid, value=val) for cid, val in casilla_values.items()),
        )
        for period, casilla_values in sorted(_m123_quarterly.items())
    )

    snapshot = _registry_snapshot("193", 2024, "0A")
    try:
        relation_values = resolve_relation_values_from_observations(
            snapshot.revision,
            observations,
            filing_year=2024,
            period="0A",
        )
    except RegistryValidationError as exc:
        pytest.fail(
            f"BINDING-GAP [M193/2024-0A engine]: resolve_relation_values_from_observations raised "
            f"RegistryValidationError — M123→M193 relation chain is structurally broken.\n"
            f"  error: {exc}",
        )

    try:
        result = calculate_registry_snapshot(
            snapshot,
            inputs={},
            date_context={"filing_period": date(2024, 12, 31)},
            relation_values=relation_values,
        )
    except RegistryValidationError as exc:
        pytest.fail(
            f"BINDING-GAP [M193/2024-0A engine]: calculate_registry_snapshot raised "
            f"RegistryValidationError — engine could not recompute from supplied relation_values.\n"
            f"  error: {exc}\n"
            f"  relation_values keys: {sorted(relation_values)}",
        )

    engine_values = dict(result.values)

    for casilla_id in ("decl.total-perceptores", "decl.base-total", "decl.retenciones-total"):
        extracted_value = extracted.get(casilla_id)
        engine_value = engine_values.get(casilla_id)
        assert extracted_value is not None, (
            f"PARSER-GAP [M193/2024-0A engine]: closure casilla {casilla_id!r} absent from extracted values"
        )
        assert isinstance(extracted_value, Decimal), (
            f"PARSER-GAP [M193/2024-0A engine]: {casilla_id!r} is not Decimal: {type(extracted_value).__name__!r}"
        )
        assert engine_value is not None, (
            f"FORMULA-MISMATCH [M193/2024-0A engine]: casilla {casilla_id!r} absent from engine result — "
            f"formula evaluation order issue or casilla missing from revision."
        )
        assert engine_value == extracted_value, (
            f"FORMULA-MISMATCH [M193/2024-0A engine]: engine recomputed {casilla_id!r} as "
            f"{engine_value!r} but AEAT-printed fixture shows {extracted_value!r}.\n"
            f"  diff: {engine_value - extracted_value!r}\n"
            f"  relation_values supplied: {relation_values}"
        )
