"""Focused adapter contract tests split from the original monolith."""

from __future__ import annotations

import pytest

from ._verification_chain_support import (
    _M303_2023_ONWARDS_PARAMS,
    _M303_CUOTA_DEDUCIBLE_TOTAL_CASILLA,
    _M303_CUOTA_DEVENGADA_TOTAL_CASILLA,
    _M303_RESULTADO_REGIMEN_GENERAL_CASILLA,
    CasillaId,
    Decimal,
    _assert_m303_engine_matches_extracted_decimal,
    _build_m303_engine_result,
    validated_casilla_id,
)

pytestmark = [pytest.mark.unit, pytest.mark.hex_inbound_adapter]


def _casilla_id(value: object) -> CasillaId:
    try:
        return validated_casilla_id(value, surface="test casilla id")
    except ValueError as exc:
        raise AssertionError(f"test fixture casilla key {value!r} is not a canonical casilla.id") from exc


_M303_SUMA_RESULTADOS_CASILLA: CasillaId = _casilla_id("64")
_M303_ATRIBUIBLE_ESTADO_CASILLA: CasillaId = _casilla_id("66")
_M303_RESULTADO_AUTOLIQUIDACION_CASILLA: CasillaId = _casilla_id("iva.resultado")
_M303_RESULTADO_FINAL_CASILLA: CasillaId = _casilla_id("71")
_M303_SYNTHETIC_CLOSURE_CASES: tuple[tuple[CasillaId, str, CasillaId, str, str], ...] = (
    (
        _M303_SUMA_RESULTADOS_CASILLA,
        "box 64 (suma de resultados)",
        _M303_RESULTADO_REGIMEN_GENERAL_CASILLA,
        "box 46 (resultado regimen general)",
        "Orden HAC/819/2024 art. 1 §4: box 64 = box 46 + box 58 + box 76; c58=0 and c76=0",
    ),
    (
        _M303_ATRIBUIBLE_ESTADO_CASILLA,
        "box 66 (atribuible Estado)",
        _M303_SUMA_RESULTADOS_CASILLA,
        "box 64 (suma de resultados)",
        "Orden HAC/819/2024 art. 1 §4: box 66 = box 64 x box 65 / 100; box 65=100",
    ),
    (
        _M303_RESULTADO_AUTOLIQUIDACION_CASILLA,
        "box 69 (resultado autoliquidacion)",
        _M303_ATRIBUIBLE_ESTADO_CASILLA,
        "box 66 (atribuible Estado)",
        "Orden HAC/819/2024 art. 1 §5: box 69 = box 66 + box 77 + box 68 - box 78; c77=c68=c78=0",
    ),
    (
        _M303_RESULTADO_FINAL_CASILLA,
        "box 71 (resultado final)",
        _M303_RESULTADO_AUTOLIQUIDACION_CASILLA,
        "box 69 (resultado autoliquidacion)",
        "Orden HAC/819/2024 art. 1 §6: box 71 = box 69 - box 70 + box 109; c70=0 and c109=0",
    ),
)
_M303_SYNTHETIC_CLOSURE_CASE_IDS: tuple[str, ...] = (
    "box-64-suma-resultados",
    "box-66-atribuible-estado",
    "box-69-resultado-autoliquidacion",
    "box-71-resultado-final",
)


@pytest.mark.parametrize(
    "pdf_stem,year,period",
    [
        ("2023-1T", 2023, "1T"),
        ("2023-2T", 2023, "2T"),
        ("2023-3T", 2023, "3T"),
        ("2023-4T", 2023, "4T"),
        ("2024-1T", 2024, "1T"),
        ("2024-2T", 2024, "2T"),
        ("2024-3T", 2024, "3T"),
        ("2024-4T", 2024, "4T"),
    ],
)
def test_verification_chain_m303_engine_recomputes_resultado_regimen_general(
    pdf_stem: str,
    year: int,
    period: str,
) -> None:
    """Engine resultado-regimen-general matches the extracted printed box 46.

    GROUNDED authority: Orden EHA/3786/2008 art. 1 — box 46 = box 27 − box 45.
      box 27 = Total cuota devengada (LIVA art. 88)
      box 45 = Total a deducir (LIVA arts. 92-94)
      box 46 = Resultado régimen general

    The 2023-y-siguientes corpus PDFs are synthetic fixtures generated by
    _generate.py with formula-consistent values: c46 = c27 - c45, so the
    engine result matches the printed value exactly.

    Verdict: VERIFIED — engine resultado == extracted resultado for all
    8 new-template specimens (2023-2024). Corpus-regenerated with
    formula-consistent synthetic values.
    """
    extracted, engine_values, _inputs = _build_m303_engine_result(pdf_stem, year, period)

    # VERIFIED gate: engine resultado must equal extracted printed box 46.
    # The synthetic corpus PDFs were generated with c46 = c27 - c45, matching
    # the registry formula. Any future registry formula change that breaks this
    # will cause a loud test failure.
    engine_resultado = _assert_m303_engine_matches_extracted_decimal(
        pdf_stem=pdf_stem,
        engine_values=engine_values,
        extracted=extracted,
        casilla_id=_M303_RESULTADO_REGIMEN_GENERAL_CASILLA,
        label="box 46 (resultado regimen general)",
        formula_context="box 46 = box 27 - box 45, Orden EHA/3786/2008 art. 1",
    )
    # Internal consistency cross-check: engine resultado == computed c27 - c45.
    engine_27 = engine_values.get(_M303_CUOTA_DEVENGADA_TOTAL_CASILLA)
    engine_45 = engine_values.get(_M303_CUOTA_DEDUCIBLE_TOTAL_CASILLA)
    assert isinstance(engine_27, Decimal), (
        f"VERIFIED-FAIL [{pdf_stem}]: engine-computed box 27 missing or non-Decimal: {engine_27!r}"
    )
    assert isinstance(engine_45, Decimal), (
        f"VERIFIED-FAIL [{pdf_stem}]: engine-computed box 45 missing or non-Decimal: {engine_45!r}"
    )
    expected_resultado = engine_27 - engine_45
    assert engine_resultado == expected_resultado, (
        f"VERIFIED-FAIL [{pdf_stem}]: engine resultado-regimen-general "
        f"{engine_resultado!r} != box27({engine_27!r}) - box45({engine_45!r}) = {expected_resultado!r}\n"
        f"  (internal formula consistency broken — registry formula defect)"
    )


@pytest.mark.parametrize(
    "target_casilla,target_label,base_casilla,base_label,formula_context",
    _M303_SYNTHETIC_CLOSURE_CASES,
    ids=_M303_SYNTHETIC_CLOSURE_CASE_IDS,
)
@pytest.mark.parametrize("pdf_stem,year,period", _M303_2023_ONWARDS_PARAMS)
def test_verification_chain_m303_engine_recomputes_synthetic_closure_boxes(
    pdf_stem: str,
    year: int,
    period: str,
    target_casilla: CasillaId,
    target_label: str,
    base_casilla: CasillaId,
    base_label: str,
    formula_context: str,
) -> None:
    """Engine M303 2023+ closure boxes match extracted values and synthetic zero relations.

    GROUNDED authority: Orden HAC/819/2024 art. 1 closure formulas for boxes
    64, 66, 69, and 71. The synthetic corpus PDFs set the non-base terms to
    zero for these closure formulas, so each target box must equal its immediate
    base box after the engine recomputes the registry DAG.
    """
    extracted, engine_values, _inputs = _build_m303_engine_result(pdf_stem, year, period)

    target_value = _assert_m303_engine_matches_extracted_decimal(
        pdf_stem=pdf_stem,
        engine_values=engine_values,
        extracted=extracted,
        casilla_id=target_casilla,
        label=target_label,
        formula_context=formula_context,
    )
    base_value = engine_values.get(base_casilla)
    assert isinstance(base_value, Decimal), (
        f"VERIFIED-FAIL [{pdf_stem}]: engine {base_label} missing or non-Decimal: {base_value!r}"
    )
    assert target_value == base_value, (
        f"VERIFIED-FAIL [{pdf_stem}]: engine {target_label} {target_value!r} != "
        f"engine {base_label} {base_value!r}\n"
        f"  ({formula_context} in corpus PDFs)"
    )
