"""Minimal type stubs for ``pypdfium2`` covering the surface used in this repo.

The runtime package does not ship ``py.typed``. We stub only the symbols
``aeat.domain.calculations.registry._record_design`` calls; expand this
file when new call sites are added.
"""

from collections.abc import Iterator

class _TextPage:
    def get_text_range(self) -> str: ...
    def close(self) -> None: ...

class _Page:
    def get_textpage(self) -> _TextPage: ...
    def close(self) -> None: ...

class PdfDocument:
    def __init__(self, source: bytes | str) -> None: ...
    def __iter__(self) -> Iterator[_Page]: ...
    def close(self) -> None: ...
