"""Authored CommandSpec declarations for the ledger rule surface."""

# ruff: noqa: S106 - command tokens are operator verbs, never credentials

from __future__ import annotations

from ._app_ledger_command_spec_policies import (
    _POLICY_3,
    _POLICY_4,
    _POLICY_5,
)
from .command_spec import (
    CommandNodeKind,
    CommandSpec,
    DeferredTarget,
    InvocationSpec,
    LazyBinding,
    OptionSpec,
    ParameterConstraint,
    ParameterDefault,
    ResultSchemaSpec,
    SchemaState,
    TranslationKey,
    ValueContract,
)

LEDGER_RULE_COMMAND_SPECS: tuple[CommandSpec, ...] = (
    CommandSpec(
        key="app_ledger_rule_add",
        parent_key="app_ledger_rule",
        token="add",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.ledger.rule.add_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="description_pattern",
                declarations=("--description-pattern",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.rule.description_pattern_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="classification",
                declarations=("--classification",),
                value=ValueContract(DeferredTarget("cadrumo.domain.transactions.enums", "BusinessClassification")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.rule.classification_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="category_id",
                declarations=("--category-id",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.rule.category_id_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="priority",
                declarations=("--priority",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(100),
                help_key=TranslationKey("cli.app.ledger.rule.priority_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="actor",
                declarations=("--actor",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.rule.actor_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_4,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._ledger_rules_cli", "rule_add")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_rule_payloads", "RuleAddResult"),
            identity="ledger.rule.add",
        ),
    ),
    CommandSpec(
        key="app_ledger_rule_apply",
        parent_key="app_ledger_rule",
        token="apply",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.ledger.rule.apply_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="reaffirm",
                declarations=("--reaffirm",),
                value=ValueContract(DeferredTarget("builtins", "bool")),
                default=ParameterDefault.value(False),
                help_key=TranslationKey("cli.app.ledger.rule.apply_reaffirm_help"),
                metavar=None,
                is_flag=True,
                flag_value=True,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="dry_run",
                declarations=("--dry-run",),
                value=ValueContract(DeferredTarget("builtins", "bool")),
                default=ParameterDefault.value(False),
                help_key=TranslationKey("cli.app.ledger.rule.apply_dry_run_help"),
                metavar=None,
                is_flag=True,
                flag_value=True,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="actor",
                declarations=("--actor",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.rule.actor_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_3,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._ledger_rules_cli", "rule_apply")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_rule_payloads", "RuleApplyResult"),
            identity="ledger.rule.apply",
        ),
    ),
    CommandSpec(
        key="app_ledger_rule_list",
        parent_key="app_ledger_rule",
        token="list",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.ledger.rule.list_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(),
        policy=_POLICY_5,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._ledger_rules_cli", "rule_list")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_rule_payloads", "RuleListResult"),
            identity="ledger.rule.list",
        ),
    ),
)

__all__ = ["LEDGER_RULE_COMMAND_SPECS"]
