"""Authored CommandSpec declarations for the ledger counterparty surface."""

# ruff: noqa: S106 - command tokens are operator verbs, never credentials

from __future__ import annotations

from ._app_ledger_command_spec_policies import (
    _POLICY_4,
    _POLICY_5,
)
from .command_spec import (
    ArgumentSpec,
    CommandNodeKind,
    CommandSpec,
    DeferredTarget,
    InvocationSpec,
    LazyBinding,
    OptionSpec,
    ParameterConstraint,
    ParameterDefault,
    ResultSchemaSpec,
    SchemaState,
    TranslationKey,
    ValueContract,
)

LEDGER_COUNTERPARTY_COMMAND_SPECS: tuple[CommandSpec, ...] = (
    CommandSpec(
        key="app_ledger_counterparty_confirm",
        parent_key="app_ledger_counterparty",
        token="confirm",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.ledger.counterparty.confirm_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="tax_identifier",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.counterparty.tax_identifier_help"),
                metavar=None,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="scope",
                declarations=("--scope",),
                value=ValueContract(DeferredTarget("cadrumo.domain.iva.classification", "IvaTerritorialScope")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.counterparty.scope_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="identification_state",
                declarations=("--identification-state",),
                value=ValueContract(DeferredTarget("cadrumo.domain.iva.schema", "EUMemberState")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.counterparty.identification_state_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="country_code",
                declarations=("--country-code",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.counterparty.country_code_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="note",
                declarations=("--note",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(""),
                help_key=TranslationKey("cli.app.ledger.counterparty.note_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="actor",
                declarations=("--actor",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.counterparty.actor_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_4,
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._ledger_counterparty_cli", "counterparty_confirm")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_counterparty_payloads", "CounterpartyConfirmResult"),
            identity="ledger.counterparty.confirm",
        ),
    ),
    CommandSpec(
        key="app_ledger_counterparty_view",
        parent_key="app_ledger_counterparty",
        token="view",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.ledger.counterparty.view_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="tax_identifier",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.counterparty.tax_identifier_help"),
                metavar=None,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="country_code",
                declarations=("--country-code",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.counterparty.country_code_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="evidenced_scope",
                declarations=("--evidenced-scope",),
                value=ValueContract(DeferredTarget("cadrumo.domain.iva.classification", "IvaTerritorialScope")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.counterparty.evidenced_scope_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_5,
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._ledger_counterparty_cli", "counterparty_view")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_counterparty_payloads", "CounterpartyViewResult"),
            identity="ledger.counterparty.view",
        ),
    ),
    CommandSpec(
        key="app_ledger_counterparty_withdraw",
        parent_key="app_ledger_counterparty",
        token="withdraw",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.ledger.counterparty.withdraw_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="tax_identifier",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.counterparty.tax_identifier_help"),
                metavar=None,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="country_code",
                declarations=("--country-code",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.counterparty.country_code_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_4,
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._ledger_counterparty_cli", "counterparty_withdraw")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget(
                "cadrumo.entrypoints.cli._ledger_counterparty_payloads", "CounterpartyWithdrawResult"
            ),
            identity="ledger.counterparty.withdraw",
        ),
    ),
)

__all__ = ["LEDGER_COUNTERPARTY_COMMAND_SPECS"]
