"""Authored CommandSpec declarations for the live foundation service."""

# ruff: noqa: S106 - command tokens are operator verbs, never credentials

from __future__ import annotations

from ...core.transport_locus import TransportLocus, TransportRole, TransportShape
from ._app_live_command_spec_support import (
    _ENCRYPTED_LOCAL_READ_POLICY,
    _LEAF_INVOCATION,
    _METADATA_GROUP_INVOCATION,
    _METADATA_POLICY,
    _OPTIONAL_YEAR_FROM_OPTION,
    _OPTIONAL_YEAR_TO_OPTION,
    _OUTPUT_ROOT_OPTION,
    _PROFILE_BOUND_NETWORK_CAPTURE_POLICY,
    _REQUIRED_MODELO_OPTION,
    _REQUIRED_PERIOD_OPTION,
    _REQUIRED_YEAR_OPTION,
    NO_RESULT_SCHEMA,
    _key,
)
from .command_spec import (
    CommandNodeKind,
    CommandSpec,
    CommandWriteRoute,
    DeferredTarget,
    ExecutionPolicySpec,
    LazyBinding,
    OptionSpec,
    ParameterConstraint,
    ParameterDefault,
    ResultSchemaSpec,
    SchemaState,
    ValueContract,
)

LIVE_FOUNDATION_COMMAND_SPECS: tuple[CommandSpec, ...] = (
    CommandSpec(
        key="app_live",
        parent_key="app",
        token="live",
        kind=CommandNodeKind.GROUP,
        help_key=_key("cli.app.live.app_help"),
        short_help_key=None,
        invocation=_METADATA_GROUP_INVOCATION,
        parameters=(),
        policy=_METADATA_POLICY,
        handler=None,
        result_schema=NO_RESULT_SCHEMA,
    ),
    CommandSpec(
        key="app_live_filed",
        parent_key="app_live",
        token="filed",
        kind=CommandNodeKind.GROUP,
        help_key=_key("cli.app.live.filed_app_help"),
        short_help_key=None,
        invocation=_METADATA_GROUP_INVOCATION,
        parameters=(),
        policy=_METADATA_POLICY,
        handler=None,
        result_schema=NO_RESULT_SCHEMA,
    ),
    CommandSpec(
        key="app_live_filed_list",
        parent_key="app_live_filed",
        token="list",
        kind=CommandNodeKind.LEAF,
        help_key=_key("cli.app.live.filed.list_help"),
        short_help_key=None,
        invocation=_LEAF_INVOCATION,
        parameters=(
            OptionSpec(
                name="modelo",
                declarations=("--modelo",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.modelo_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            _OPTIONAL_YEAR_FROM_OPTION,
            _OPTIONAL_YEAR_TO_OPTION,
        ),
        policy=_ENCRYPTED_LOCAL_READ_POLICY,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live", "filed_list_cmd")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_filed_payloads", "FiledListResult"),
            identity="app.live.filed.list",
        ),
    ),
    CommandSpec(
        key="app_live_filed_discover",
        parent_key="app_live_filed",
        token="discover",
        kind=CommandNodeKind.LEAF,
        help_key=_key("cli.app.live.filed.discover_help"),
        short_help_key=None,
        invocation=_LEAF_INVOCATION,
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts", "network"]),
            side_effects=frozenset(["network"]),
            performance="external-io",
            write_route=CommandWriteRoute.NONE,
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live", "filed_discover_cmd")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_filed_payloads", "FiledDiscoverResult"),
            identity="app.live.filed.discover",
        ),
    ),
    CommandSpec(
        key="app_live_filed_pull_all",
        parent_key="app_live_filed",
        token="pull-all",
        kind=CommandNodeKind.LEAF,
        help_key=_key("cli.app.live.filed.pull_all_help"),
        short_help_key=None,
        invocation=_LEAF_INVOCATION,
        parameters=(
            _OUTPUT_ROOT_OPTION,
            OptionSpec(
                name="limit",
                declarations=("--limit",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.filed.pull_all_limit_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=1, maximum=None),
            ),
        ),
        policy=_PROFILE_BOUND_NETWORK_CAPTURE_POLICY,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live", "filed_pull_all_cmd")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_filed_payloads", "FiledHistoryOnboardingResult"),
            identity="app.live.filed.pull_all",
        ),
    ),
    CommandSpec(
        key="app_live_filed_pull",
        parent_key="app_live_filed",
        token="pull",
        kind=CommandNodeKind.LEAF,
        help_key=_key("cli.app.live.filed.pull_help"),
        short_help_key=None,
        invocation=_LEAF_INVOCATION,
        parameters=(
            OptionSpec(
                name="modelos",
                declarations=("--modelo",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(()),
                help_key=_key("cli.app.live.filed.pull_modelo_help"),
                multiple=True,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="year",
                declarations=("--year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            _OPTIONAL_YEAR_FROM_OPTION,
            _OPTIONAL_YEAR_TO_OPTION,
            _OUTPUT_ROOT_OPTION,
            OptionSpec(
                name="period",
                declarations=("--period",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.period_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="expediente_id",
                declarations=("--expediente",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.expediente_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="limit",
                declarations=("--limit",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.limit_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=1, maximum=None),
            ),
            OptionSpec(
                name="dry_run",
                declarations=("--dry-run",),
                value=ValueContract(DeferredTarget("builtins", "bool")),
                default=ParameterDefault.value(False),
                help_key=_key("cli.app.live.filed.pull_dry_run_help"),
                multiple=False,
                is_flag=True,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=_PROFILE_BOUND_NETWORK_CAPTURE_POLICY,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live", "filed_pull_cmd")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_filed_payloads", "FiledCaptureResult"),
            identity="app.live.filed.pull",
        ),
    ),
    CommandSpec(
        key="app_live_filed_pull_sources",
        parent_key="app_live_filed",
        token="pull-sources",
        kind=CommandNodeKind.LEAF,
        help_key=_key("cli.app.live.filed.pull_sources_help"),
        short_help_key=None,
        invocation=_LEAF_INVOCATION,
        parameters=(
            _REQUIRED_MODELO_OPTION,
            _REQUIRED_YEAR_OPTION,
            _REQUIRED_PERIOD_OPTION,
            _OUTPUT_ROOT_OPTION,
            OptionSpec(
                name="registry_root",
                declarations=("--registry-root",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.registry_root_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
                transport_locus=TransportLocus.LOCAL_IN,
                transport_shape=TransportShape.ROOT,
                transport_role=TransportRole.AUXILIARY,
            ),
            OptionSpec(
                name="source_root",
                declarations=("--source-root",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.source_root_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
                transport_locus=TransportLocus.LOCAL_IN,
                transport_shape=TransportShape.ROOT,
                transport_role=TransportRole.AUXILIARY,
            ),
        ),
        policy=_PROFILE_BOUND_NETWORK_CAPTURE_POLICY,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live", "filed_pull_sources_cmd")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_filed_payloads", "FiledCaptureSourcesResult"),
            identity="app.live.filed.pull_sources",
        ),
    ),
)

__all__ = ["LIVE_FOUNDATION_COMMAND_SPECS"]
