"""Authored CommandSpec declarations for the ledger operations surface."""

# ruff: noqa: S106 - command tokens are operator verbs, never credentials

from __future__ import annotations

from ...core.transport_locus import TransportLocus, TransportRole, TransportShape
from ._app_ledger_command_spec_policies import (
    _POLICY_1,
    _POLICY_2,
    _POLICY_4,
    _POLICY_5,
    _POLICY_8,
    _POLICY_10,
)
from ._app_ledger_command_spec_support import (
    _EVIDENCE_ACTOR_OPTION,
    _EVIDENCE_TRANSACTION_ID_ARGUMENT,
    _GROUP_INVOCATION,
    _LEAF_INVOCATION,
    _LEDGER_ACTOR_OPTION,
    _NO_RESULT_SCHEMA,
    _OPTIONAL_PERIOD_OPTION,
    _OPTIONAL_YEAR_OPTION,
    _blank_default_text_option,
    _boolean_flag_option,
    _optional_text_option,
    _repeatable_text_option,
    _required_text_argument,
)
from .command_spec import (
    CommandNodeKind,
    CommandSpec,
    DeferredTarget,
    LazyBinding,
    OptionSpec,
    ParameterConstraint,
    ParameterDefault,
    ResultSchemaSpec,
    SchemaState,
    TranslationKey,
    ValueContract,
)

LEDGER_OPERATIONS_COMMAND_SPECS: tuple[CommandSpec, ...] = (
    CommandSpec(
        key="app_ledger_counterparty",
        parent_key="app_ledger",
        token="counterparty",
        kind=CommandNodeKind.GROUP,
        help_key=TranslationKey("cli.app.ledger.counterparty.group_help"),
        short_help_key=None,
        invocation=_GROUP_INVOCATION,
        parameters=(),
        policy=_POLICY_1,
        handler=None,
        result_schema=_NO_RESULT_SCHEMA,
    ),
    CommandSpec(
        key="app_ledger_detach",
        parent_key="app_ledger",
        token="detach",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.detach.help"),
        short_help_key=None,
        invocation=_LEAF_INVOCATION,
        parameters=(
            _required_text_argument("transaction_id", "cli.ledger.detach.id_help"),
            _repeatable_text_option("attachment_ids", ("--attachment-id",), "cli.ledger.detach.attachment_help"),
            _optional_text_option("actor", ("--actor",), "cli.ledger.detach.actor_help"),
        ),
        policy=_POLICY_4,
        handler=LazyBinding.available(DeferredTarget(".ledger_lifecycle_cli", "ledger_detach", __package__)),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("._ledger_payloads", "LedgerDetachResult", __package__),
            identity="ledger.detach",
        ),
    ),
    CommandSpec(
        key="app_ledger_evidence_pull",
        parent_key="app_ledger_evidence",
        token="pull",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.ledger.evidence.pull_help"),
        short_help_key=None,
        invocation=_LEAF_INVOCATION,
        parameters=(
            _EVIDENCE_TRANSACTION_ID_ARGUMENT,
            OptionSpec(
                name="source",
                declarations=("--source",),
                value=ValueContract(DeferredTarget("...domain.attachments.enums", "DocumentLinkSource", __package__)),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.evidence.pull_source_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="reference",
                declarations=("--reference",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.evidence.pull_reference_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
                transport_locus=TransportLocus.REMOTE_HANDLE,
                transport_shape=TransportShape.NOT_APPLICABLE,
                transport_role=TransportRole.NOT_APPLICABLE,
            ),
            _blank_default_text_option("note", ("--note",), "cli.app.ledger.evidence.pull_note_help"),
            _EVIDENCE_ACTOR_OPTION,
        ),
        policy=_POLICY_8,
        handler=LazyBinding.available(DeferredTarget(".ledger_lifecycle_cli", "ledger_evidence_pull", __package__)),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("._ledger_payloads", "LedgerAttachResult", __package__),
            identity="ledger.evidence.pull",
        ),
    ),
    CommandSpec(
        key="app_ledger_evidence",
        parent_key="app_ledger",
        token="evidence",
        kind=CommandNodeKind.GROUP,
        help_key=TranslationKey("cli.app.ledger.evidence.group_help"),
        short_help_key=None,
        invocation=_GROUP_INVOCATION,
        parameters=(),
        policy=_POLICY_1,
        handler=None,
        result_schema=_NO_RESULT_SCHEMA,
    ),
    CommandSpec(
        key="app_ledger_exclude",
        parent_key="app_ledger",
        token="exclude",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.exclude.help"),
        short_help_key=None,
        invocation=_LEAF_INVOCATION,
        parameters=(
            _EVIDENCE_TRANSACTION_ID_ARGUMENT,
            _blank_default_text_option("reason", ("--reason",), "cli.ledger.exclude.reason_help"),
            _boolean_flag_option("yes", ("--yes",), "cli.ledger.exclude.yes_help"),
            _EVIDENCE_ACTOR_OPTION,
        ),
        policy=_POLICY_4,
        handler=LazyBinding.available(DeferredTarget(".ledger_lifecycle_cli", "ledger_exclude", __package__)),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("._ledger_payloads", "LedgerExcludeResult", __package__),
            identity="ledger.exclude",
        ),
    ),
    CommandSpec(
        key="app_ledger_export",
        parent_key="app_ledger",
        token="export",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.export.help"),
        short_help_key=None,
        invocation=_LEAF_INVOCATION,
        parameters=(
            OptionSpec(
                name="output",
                declarations=("--output",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.ledger.export.output_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
                transport_locus=TransportLocus.LOCAL_OUT,
                transport_shape=TransportShape.FILE,
                transport_role=TransportRole.PRIMARY,
            ),
            OptionSpec(
                name="export_kind",
                declarations=("--export-format",),
                value=ValueContract(
                    DeferredTarget("...application.export.tabular", "ExportSerializationFormat", __package__)
                ),
                default=ParameterDefault.value("csv"),
                help_key=TranslationKey("cli.ledger.export.format_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            _boolean_flag_option(
                "include_inactive", ("--include-inactive",), "cli.ledger.export.include_inactive_help"
            ),
            _OPTIONAL_PERIOD_OPTION,
            _OPTIONAL_YEAR_OPTION,
            _LEDGER_ACTOR_OPTION,
        ),
        policy=_POLICY_10,
        handler=LazyBinding.available(DeferredTarget("._ledger_read_cli", "ledger_export", __package__)),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("._ledger_payloads", "LedgerExportPayload", __package__),
            identity="ledger.export",
        ),
    ),
    CommandSpec(
        key="app_ledger_history",
        parent_key="app_ledger",
        token="history",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.history.help"),
        short_help_key=None,
        invocation=_LEAF_INVOCATION,
        parameters=(
            _required_text_argument("transaction_id", "cli.ledger.history.id_help"),
            _boolean_flag_option(
                "include_split_siblings",
                ("--include-split-siblings",),
                "cli.ledger.history.include_split_siblings_help",
            ),
        ),
        policy=_POLICY_5,
        handler=LazyBinding.available(DeferredTarget("._ledger_read_cli", "ledger_history", __package__)),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("._ledger_payloads", "LedgerHistoryResult", __package__),
            identity="ledger.history",
        ),
    ),
    CommandSpec(
        key="app_ledger_import",
        parent_key="app_ledger",
        token="import",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.import.help"),
        short_help_key=None,
        invocation=_LEAF_INVOCATION,
        parameters=(
            OptionSpec(
                name="file",
                declarations=("--file",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.ledger.import.file_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
                transport_locus=TransportLocus.LOCAL_IN,
                transport_shape=TransportShape.FILE,
                transport_role=TransportRole.PRIMARY,
            ),
            OptionSpec(
                name="provider",
                declarations=("--provider",),
                value=ValueContract(
                    DeferredTarget("...application.ledger.actions_import", "LedgerProviderID", __package__)
                ),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.ledger.import.provider_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            _boolean_flag_option("dry_run", ("--dry-run",), "cli.ledger.import.dry_run_help"),
            _boolean_flag_option("verify", ("--verify",), "cli.ledger.import.verify_help"),
            OptionSpec(
                name="verify_source",
                declarations=("--verify-source",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.import.verify_source_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
                transport_locus=TransportLocus.LOCAL_IN,
                transport_shape=TransportShape.FILE,
                transport_role=TransportRole.AUXILIARY,
            ),
            _boolean_flag_option("verbose", ("--verbose",), "cli.ledger.import.verbose_help"),
            _OPTIONAL_PERIOD_OPTION,
            _OPTIONAL_YEAR_OPTION,
        ),
        policy=_POLICY_2,
        handler=LazyBinding.available(DeferredTarget("._ledger_import_cli", "ledger_import", __package__)),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("._ledger_payloads", "LedgerImportPayload", __package__),
            identity="ledger.import",
        ),
    ),
)

__all__ = ["LEDGER_OPERATIONS_COMMAND_SPECS"]
