"""Authored CommandSpec declarations for the ledger lifecycle surface."""

# ruff: noqa: S106 - command tokens are operator verbs, never credentials

from __future__ import annotations

from ._app_ledger_command_spec_policies import (
    _POLICY_1,
    _POLICY_4,
    _POLICY_5,
    _POLICY_7,
    _POLICY_9,
)
from ._app_ledger_command_spec_support import (
    _ARCHIVE_REASON_OPTION,
    _LEDGER_ACTOR_OPTION,
    _MERGE_REASON_OPTION,
    _OPTIONAL_PERIOD_OPTION,
    _OPTIONAL_YEAR_OPTION,
    _blank_default_text_option,
    _boolean_flag_option,
    _optional_text_option,
    _repeatable_text_option,
    _required_text_argument,
)
from .command_spec import (
    CommandNodeKind,
    CommandSpec,
    DeferredTarget,
    InvocationSpec,
    LazyBinding,
    OptionSpec,
    ParameterConstraint,
    ParameterDefault,
    ResultSchemaSpec,
    SchemaState,
    TranslationKey,
    ValueContract,
)

LEDGER_LIFECYCLE_COMMAND_SPECS: tuple[CommandSpec, ...] = (
    CommandSpec(
        key="app_ledger_remove",
        parent_key="app_ledger",
        token="remove",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.remove.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            _required_text_argument("transaction_id", "cli.ledger.remove.id_help"),
            _blank_default_text_option("reason", ("--reason",), "cli.ledger.remove.reason_help"),
            _boolean_flag_option("dry_run", ("--dry-run",), "cli.ledger.remove.dry_run_help"),
            _boolean_flag_option("yes", ("--yes",), "cli.ledger.remove.yes_help"),
            _LEDGER_ACTOR_OPTION,
        ),
        policy=_POLICY_9,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli.ledger_lifecycle_cli", "ledger_remove")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerRemoveResult"),
            identity="ledger.remove",
        ),
    ),
    CommandSpec(
        key="app_ledger_reset",
        parent_key="app_ledger",
        token="reset",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.reset.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            _blank_default_text_option("reason", ("--reason",), "cli.ledger.reset.reason_help"),
            _boolean_flag_option("dry_run", ("--dry-run",), "cli.ledger.reset.dry_run_help"),
            _boolean_flag_option("yes", ("--yes",), "cli.ledger.reset.yes_help"),
            _LEDGER_ACTOR_OPTION,
        ),
        policy=_POLICY_9,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli.ledger_lifecycle_cli", "ledger_reset")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerResetResult"),
            identity="ledger.reset",
        ),
    ),
    CommandSpec(
        key="app_ledger_restore",
        parent_key="app_ledger",
        token="restore",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.restore.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            _required_text_argument("transaction_id", "cli.ledger.restore.id_help"),
            _ARCHIVE_REASON_OPTION,
            _boolean_flag_option("yes", ("--yes",), "cli.ledger.restore.yes_help"),
            _LEDGER_ACTOR_OPTION,
        ),
        policy=_POLICY_4,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli.ledger_lifecycle_cli", "ledger_restore")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerRestoreResult"),
            identity="ledger.restore",
        ),
    ),
    CommandSpec(
        key="app_ledger_review",
        parent_key="app_ledger",
        token="review",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.review.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            _repeatable_text_option("filters", ("--filter",), "cli.ledger.review.filter_help"),
            _boolean_flag_option("verbose", ("--verbose",), "cli.ledger.review.verbose_help"),
        ),
        policy=_POLICY_5,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._ledger_review_cli", "ledger_review")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerReviewResult"),
            identity="ledger.review",
        ),
    ),
    CommandSpec(
        key="app_ledger_rule",
        parent_key="app_ledger",
        token="rule",
        kind=CommandNodeKind.GROUP,
        help_key=TranslationKey("cli.app.ledger.rule.group_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=_POLICY_1,
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_ledger_split",
        parent_key="app_ledger",
        token="split",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.split.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            _required_text_argument("transaction_id", "cli.ledger.split.id_help"),
            _repeatable_text_option("child_amount", ("--child-amount",), "cli.ledger.split.child_amount_help"),
            _repeatable_text_option(
                "child_description", ("--child-description",), "cli.ledger.split.child_description_help"
            ),
            _boolean_flag_option("llm", ("--llm",), "cli.ledger.split.llm_help"),
            _boolean_flag_option("apply", ("--apply",), "cli.ledger.split.apply_help"),
            _boolean_flag_option("read_evidence", ("--read-evidence",), "cli.ledger.split.read_evidence_help"),
            _optional_text_option("vision_model", ("--vision-model",), "cli.ledger.classify.vision_model_help"),
            _MERGE_REASON_OPTION,
            _boolean_flag_option("yes", ("--yes",), "cli.ledger.split.yes_help"),
            _optional_text_option("actor", ("--actor",), "cli.ledger.split.actor_help"),
        ),
        policy=_POLICY_7,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli.ledger_lifecycle_cli", "ledger_split")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerSplitResult"),
            identity="ledger.split",
        ),
    ),
    CommandSpec(
        key="app_ledger_stash",
        parent_key="app_ledger",
        token="stash",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.stash.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            _required_text_argument("transaction_id", "cli.ledger.stash.id_help"),
            _ARCHIVE_REASON_OPTION,
            _boolean_flag_option("yes", ("--yes",), "cli.ledger.stash.yes_help"),
            _LEDGER_ACTOR_OPTION,
        ),
        policy=_POLICY_4,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli.ledger_lifecycle_cli", "ledger_stash")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerStashResult"),
            identity="ledger.stash",
        ),
    ),
    CommandSpec(
        key="app_ledger_status",
        parent_key="app_ledger",
        token="status",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.status.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            _OPTIONAL_PERIOD_OPTION,
            _OPTIONAL_YEAR_OPTION,
        ),
        policy=_POLICY_5,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._ledger_read_cli", "ledger_status")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerStatusResult"),
            identity="ledger.status",
        ),
    ),
    CommandSpec(
        key="app_ledger_track",
        parent_key="app_ledger",
        token="track",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.track.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(_required_text_argument("transaction_id", "cli.ledger.track.transaction_id_help"),),
        policy=_POLICY_5,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._ledger_read_cli", "ledger_track")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerTrackResult"),
            identity="ledger.track",
        ),
    ),
    CommandSpec(
        key="app_ledger_update",
        parent_key="app_ledger",
        token="update",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.update.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            _required_text_argument("transaction_id", "cli.ledger.update.id_help"),
            _optional_text_option("booked_date", ("--date",), "cli.ledger.update.date_help"),
            _optional_text_option("value_date", ("--value-date",), "cli.ledger.update.value_date_help"),
            _optional_text_option("amount", ("--amount",), "cli.ledger.update.amount_help"),
            OptionSpec(
                name="direction",
                declarations=("--direction",),
                value=ValueContract(DeferredTarget("cadrumo.domain.transactions.enums", "TransactionDirection")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.update.direction_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            _optional_text_option("currency", ("--currency",), "cli.ledger.update.currency_help"),
            _optional_text_option("counterparty", ("--counterparty",), "cli.ledger.update.counterparty_help"),
            _optional_text_option("description", ("--description",), "cli.ledger.update.description_help"),
            _optional_text_option("taxable_base", ("--taxable-base",), "cli.ledger.update.taxable_base_help"),
            _optional_text_option("iva_rate", ("--iva-rate",), "cli.ledger.update.iva_rate_help"),
            _optional_text_option("iva_amount", ("--iva-amount",), "cli.ledger.update.iva_amount_help"),
            _optional_text_option("irpf_category", ("--irpf-category",), "cli.ledger.update.irpf_category_help"),
            _optional_text_option("notes", ("--notes",), "cli.ledger.update.notes_help"),
            _optional_text_option("group", ("--group",), "cli.ledger.update.group_help"),
            _LEDGER_ACTOR_OPTION,
        ),
        policy=_POLICY_4,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._ledger", "ledger_update")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerUpdateResult"),
            identity="ledger.update",
        ),
    ),
    CommandSpec(
        key="app_ledger_view",
        parent_key="app_ledger",
        token="view",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.view.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(_required_text_argument("transaction_id", "cli.ledger.view.transaction_id_help"),),
        policy=_POLICY_5,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._ledger_read_cli", "ledger_view")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerViewResult"),
            identity="ledger.view",
        ),
    ),
)

__all__ = ["LEDGER_LIFECYCLE_COMMAND_SPECS"]
