"""Authored CommandSpec declarations for the live iva wallet service."""

# ruff: noqa: S106 - command tokens are operator verbs, never credentials

from __future__ import annotations

from ...core.transport_locus import TransportLocus, TransportRole, TransportShape
from ._app_live_command_spec_support import _key
from .command_spec import (
    CommandSpec,
    CommandWriteRoute,
    DeferredTarget,
    ExecutionPolicySpec,
    InvocationSpec,
    LazyBinding,
    OptionSpec,
    ParameterConstraint,
    ParameterDefault,
    ResultSchemaSpec,
    SchemaState,
    ValueContract,
)

LIVE_IVA_WALLET_COMMAND_SPECS: tuple[CommandSpec, ...] = (
    CommandSpec(
        key="app_live_iva_wallet",
        parent_key="app_live",
        token="iva-wallet",
        kind="group",
        help_key=_key("cli.app.live.iva_wallet.app_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["state-free"]),
            side_effects=frozenset(["none"]),
            performance="metadata",
            write_route=CommandWriteRoute.NONE,
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_live_iva_wallet_pull",
        parent_key="app_live_iva_wallet",
        token="pull",
        kind="leaf",
        help_key=_key("cli.app.live.iva_wallet.pull_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="year",
                declarations=("--year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            OptionSpec(
                name="period",
                declarations=("--period",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.period_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="taxpayer_nif",
                declarations=("--taxpayer-nif",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.iva_wallet.taxpayer_nif_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts", "network"]),
            side_effects=frozenset(["local-state", "network"]),
            performance="external-io",
            write_route=CommandWriteRoute.PROFILE_BOUND,
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live", "iva_wallet_pull_cmd")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_iva_wallet_payloads", "IvaWalletPullResult"),
            identity="app.live.iva_wallet.pull",
        ),
    ),
    CommandSpec(
        key="app_live_iva_wallet_history",
        parent_key="app_live_iva_wallet",
        token="history",
        kind="leaf",
        help_key=_key("cli.app.live.iva_wallet.history_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="as_of_year",
                declarations=("--as-of-year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.iva_wallet.as_of_year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route=CommandWriteRoute.NONE,
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live", "iva_wallet_history_cmd")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_iva_wallet_payloads", "IvaWalletHistoryResult"),
            identity="app.live.iva_wallet.history",
        ),
    ),
    CommandSpec(
        key="app_live_iva_wallet_pull_history",
        parent_key="app_live_iva_wallet",
        token="pull-history",
        kind="leaf",
        help_key=_key("cli.app.live.iva_wallet.pull_history_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="year_from",
                declarations=("--from-year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.from_year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            OptionSpec(
                name="year_to",
                declarations=("--to-year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.to_year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            OptionSpec(
                name="output_root",
                declarations=("--output-root",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.output_root_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
                transport_locus=TransportLocus.LOCAL_OUT,
                transport_shape=TransportShape.DIRECTORY,
                transport_role=TransportRole.PRIMARY,
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts", "network"]),
            side_effects=frozenset(["local-state", "network"]),
            performance="external-io",
            write_route=CommandWriteRoute.PROFILE_BOUND,
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live", "iva_wallet_pull_history_cmd")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget(
                "cadrumo.entrypoints.cli._app_live_iva_wallet_payloads", "IvaWalletCaptureHistoryResult"
            ),
            identity="app.live.iva_wallet.pull_history",
        ),
    ),
    CommandSpec(
        key="app_live_iva_wallet_pull_evidence",
        parent_key="app_live_iva_wallet",
        token="pull-evidence",
        kind="leaf",
        help_key=_key("cli.app.live.iva_wallet.pull_evidence_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="year_from",
                declarations=("--from-year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.from_year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            OptionSpec(
                name="year_to",
                declarations=("--to-year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.to_year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            OptionSpec(
                name="target_year",
                declarations=("--target-year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            OptionSpec(
                name="target_period",
                declarations=("--target-period",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.period_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="taxpayer_nif",
                declarations=("--taxpayer-nif",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.iva_wallet.taxpayer_nif_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="output_root",
                declarations=("--output-root",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.output_root_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
                transport_locus=TransportLocus.LOCAL_OUT,
                transport_shape=TransportShape.DIRECTORY,
                transport_role=TransportRole.PRIMARY,
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["browser", "encrypted-facts", "subprocess"]),
            side_effects=frozenset(["browser", "local-state", "network"]),
            performance="external-io",
            write_route=CommandWriteRoute.PROFILE_BOUND,
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live", "iva_wallet_pull_evidence_cmd")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget(
                "cadrumo.entrypoints.cli._app_live_iva_wallet_payloads", "IvaWalletPullEvidenceResult"
            ),
            identity="app.live.iva_wallet.pull_evidence",
        ),
    ),
)

__all__ = ["LIVE_IVA_WALLET_COMMAND_SPECS"]
