"""Authored CommandSpec declarations for the ledger classification surface."""

# ruff: noqa: S106 - command tokens are operator verbs, never credentials

from __future__ import annotations

from ...core.transport_locus import TransportLocus, TransportRole, TransportShape
from ._app_ledger_command_spec_policies import (
    _POLICY_7,
)
from ._app_ledger_command_spec_support import (
    _boolean_flag_option,
    _optional_text_option,
)
from .command_spec import (
    ArgumentSpec,
    CommandNodeKind,
    CommandSpec,
    DeferredTarget,
    InvocationSpec,
    LazyBinding,
    OptionSpec,
    ParameterConstraint,
    ParameterDefault,
    ResultSchemaSpec,
    SchemaState,
    TranslationKey,
    ValueContract,
)

LEDGER_CLASSIFICATION_COMMAND_SPECS: tuple[CommandSpec, ...] = (
    CommandSpec(
        key="app_ledger_classify",
        parent_key="app_ledger",
        token="classify",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.classify.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="transaction_id",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.classify.id_help"),
                metavar=None,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="classification",
                declarations=("--classification",),
                value=ValueContract(DeferredTarget("cadrumo.domain.transactions.enums", "BusinessClassification")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.classify.classification_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="file",
                declarations=("--file",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.classify.file_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
                transport_locus=TransportLocus.LOCAL_IN,
                transport_shape=TransportShape.FILE,
                transport_role=TransportRole.PRIMARY,
            ),
            _optional_text_option("business_pct", ("--business-pct",), "cli.ledger.classify.business_pct_help"),
            _optional_text_option("category_id", ("--category-id",), "cli.ledger.add.category_help"),
            _optional_text_option("taxable_base", ("--taxable-base",), "cli.ledger.classify.taxable_base_help"),
            _optional_text_option("iva_rate", ("--iva-rate",), "cli.ledger.classify.iva_rate_help"),
            _optional_text_option("iva_amount", ("--iva-amount",), "cli.ledger.classify.iva_amount_help"),
            _optional_text_option("irpf_category", ("--irpf-category",), "cli.ledger.classify.irpf_category_help"),
            _optional_text_option(
                "m210_tipo_renta_code", ("--m210-tipo-renta-code",), "cli.ledger.classify.m210_tipo_renta_code_help"
            ),
            _optional_text_option(
                "m210_gross_income_amount",
                ("--m210-gross-income-amount",),
                "cli.ledger.classify.m210_gross_income_amount_help",
            ),
            _optional_text_option(
                "m210_applicable_rate", ("--m210-applicable-rate",), "cli.ledger.classify.m210_applicable_rate_help"
            ),
            OptionSpec(
                name="m210_payer_mode",
                declarations=("--m210-payer-mode",),
                value=ValueContract(DeferredTarget("cadrumo.core.irnr", "M210PayerMode")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.classify.m210_payer_mode_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            _optional_text_option("m210_payer_id", ("--m210-payer-id",), "cli.ledger.classify.m210_payer_id_help"),
            _optional_text_option(
                "m210_asset_or_right_id",
                ("--m210-asset-or-right-id",),
                "cli.ledger.classify.m210_asset_or_right_id_help",
            ),
            OptionSpec(
                name="iva_category",
                declarations=("--iva-category",),
                value=ValueContract(DeferredTarget("cadrumo.domain.iva.schema", "IvaCategory")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.classify.iva_category_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="deduction_fact_kind",
                declarations=("--deduction-kind",),
                value=ValueContract(DeferredTarget("cadrumo.core.iva_deduction_fact", "IvaDeductionFactKind")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.classify.deduction_fact_kind_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            _optional_text_option(
                "counterparty_country", ("--counterparty-country",), "cli.ledger.classify.counterparty_country_help"
            ),
            OptionSpec(
                name="counterparty_identification_state",
                declarations=("--counterparty-identification-state",),
                value=ValueContract(DeferredTarget("cadrumo.domain.iva.schema", "EUMemberState")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.classify.counterparty_identification_state_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            _optional_text_option("actor", ("--actor",), "cli.ledger.add.actor_help"),
            _boolean_flag_option("reaffirm", ("--reaffirm",), "cli.ledger.classify.reaffirm_help"),
            _boolean_flag_option("llm", ("--llm",), "cli.ledger.classify.llm_help"),
            _boolean_flag_option("apply", ("--apply",), "cli.ledger.classify.apply_help"),
            _boolean_flag_option("saturate", ("--saturate",), "cli.ledger.classify.saturate_help"),
            _boolean_flag_option("read_evidence", ("--read-evidence",), "cli.ledger.classify.read_evidence_help"),
            _optional_text_option("vision_model", ("--vision-model",), "cli.ledger.classify.vision_model_help"),
            _boolean_flag_option("auto_split", ("--auto-split",), "cli.ledger.classify.auto_split_help"),
            _boolean_flag_option("reject", ("--reject",), "cli.ledger.classify.reject_help"),
            _optional_text_option("reason", ("--reason",), "cli.ledger.classify.reason_help"),
        ),
        policy=_POLICY_7,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._ledger", "ledger_classify")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerClassifyResult"),
            identity="ledger.classify",
        ),
    ),
)

__all__ = ["LEDGER_CLASSIFICATION_COMMAND_SPECS"]
