"""Authored CommandSpec declarations for the ledger evidence followup surface."""

# ruff: noqa: S106 - command tokens are operator verbs, never credentials

from __future__ import annotations

from ._app_ledger_command_spec_policies import (
    _POLICY_2,
    _POLICY_5,
)
from ._command_spec import (
    ArgumentSpec,
    CommandSpec,
    DeferredTarget,
    InvocationSpec,
    LazyBinding,
    OptionSpec,
    ParameterConstraint,
    ParameterDefault,
    ResultSchemaSpec,
    SchemaState,
    TranslationKey,
    ValueContract,
)

LEDGER_EVIDENCE_FOLLOWUP_COMMAND_SPECS: tuple[CommandSpec, ...] = (
    CommandSpec(
        key="app_ledger_evidence_consent_list",
        parent_key="app_ledger_evidence_consent",
        token="list",
        kind="leaf",
        help_key=TranslationKey("cli.app.ledger.evidence.consent.list_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(),
        policy=_POLICY_5,
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._ledger_evidence_consent_cli", "consent_list")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_business_payloads", "EvidenceConsentListResult"),
            identity="ledger.evidence.consent.list",
        ),
    ),
    CommandSpec(
        key="app_ledger_evidence_consent_rederive",
        parent_key="app_ledger_evidence_consent",
        token="rederive",
        kind="leaf",
        help_key=TranslationKey("cli.app.ledger.evidence.consent.rederive_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="evidence_reference",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.evidence.consent.evidence_reference_help"),
                metavar=None,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="content_address",
                declarations=("--content-address",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.evidence.consent.content_address_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="transcriber",
                declarations=("--transcriber",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.evidence.consent.transcriber_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_2,
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._ledger_evidence_consent_cli", "consent_rederive")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_business_payloads", "EvidenceConsentRederiveResult"),
            identity="ledger.evidence.consent.rederive",
        ),
    ),
    CommandSpec(
        key="app_ledger_evidence_review_list",
        parent_key="app_ledger_evidence_review",
        token="list",
        kind="leaf",
        help_key=TranslationKey("cli.app.ledger.evidence.review.list_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="reason",
                declarations=("--reason",),
                value=ValueContract(DeferredTarget("cadrumo.core", "ConfirmationBlockReason")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.evidence.review.reason_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="finding",
                declarations=("--finding",),
                value=ValueContract(DeferredTarget("cadrumo.core", "DraftDiscrepancyKind")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.evidence.review.finding_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="advisory",
                declarations=("--advisory",),
                value=ValueContract(DeferredTarget("cadrumo.core", "ReviewAdvisoryKind")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.evidence.review.advisory_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="blocking_only",
                declarations=("--blocking",),
                value=ValueContract(DeferredTarget("builtins", "bool")),
                default=ParameterDefault.value(False),
                help_key=TranslationKey("cli.app.ledger.evidence.review.blocking_help"),
                metavar=None,
                is_flag=True,
                flag_value=True,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_5,
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._ledger_evidence_review_cli", "review_list")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_business_payloads", "EvidenceReviewListResult"),
            identity="ledger.evidence.review.list",
        ),
    ),
    CommandSpec(
        key="app_ledger_evidence_review_view",
        parent_key="app_ledger_evidence_review",
        token="view",
        kind="leaf",
        help_key=TranslationKey("cli.app.ledger.evidence.review.view_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="reference",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.evidence.review.reference_help"),
                metavar=None,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_5,
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._ledger_evidence_review_cli", "review_view")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_business_payloads", "EvidenceReviewViewResult"),
            identity="ledger.evidence.review.view",
        ),
    ),
)

__all__ = ["LEDGER_EVIDENCE_FOLLOWUP_COMMAND_SPECS"]
