"""Import-light CommandSpec authority for the complete app live family."""

# ruff: noqa: S106 - ``token`` fields are public CLI tokens, never credentials.

from __future__ import annotations

from ._command_spec import (
    ArgumentSpec,
    CommandSpec,
    DeferredTarget,
    ExecutionPolicySpec,
    InvocationSpec,
    LazyBinding,
    OptionSpec,
    ParameterConstraint,
    ParameterDefault,
    ResultSchemaSpec,
    SchemaState,
    TranslationKey,
    ValueContract,
)


def _key(value: str) -> TranslationKey:
    return TranslationKey(value)


LIVE_COMMAND_SPECS: tuple[CommandSpec, ...] = (
    CommandSpec(
        key="app_live",
        parent_key="app",
        token="live",
        kind="group",
        help_key=_key("cli.app.live.app_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["state-free"]),
            side_effects=frozenset(["none"]),
            performance="metadata",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_live_filed",
        parent_key="app_live",
        token="filed",
        kind="group",
        help_key=_key("cli.app.live.filed_app_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["state-free"]),
            side_effects=frozenset(["none"]),
            performance="metadata",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_live_filed_list",
        parent_key="app_live_filed",
        token="list",
        kind="leaf",
        help_key=_key("cli.app.live.filed.list_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="modelo",
                declarations=("--modelo",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.modelo_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="year_from",
                declarations=("--from-year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.from_year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            OptionSpec(
                name="year_to",
                declarations=("--to-year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.to_year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live", "filed_list_cmd")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "FiledListResult"),
            identity="app.live.filed.list",
        ),
    ),
    CommandSpec(
        key="app_live_filed_discover",
        parent_key="app_live_filed",
        token="discover",
        kind="leaf",
        help_key=_key("cli.app.live.filed.discover_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts", "network"]),
            side_effects=frozenset(["network"]),
            performance="external-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live", "filed_discover_cmd")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "FiledDiscoverResult"),
            identity="app.live.filed.discover",
        ),
    ),
    CommandSpec(
        key="app_live_filed_pull_all",
        parent_key="app_live_filed",
        token="pull-all",
        kind="leaf",
        help_key=_key("cli.app.live.filed.pull_all_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="output_root",
                declarations=("--output-root",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.output_root_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="limit",
                declarations=("--limit",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.filed.pull_all_limit_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=1, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts", "network"]),
            side_effects=frozenset(["local-state", "network"]),
            performance="external-io",
            write_route="profile-bound",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live", "filed_pull_all_cmd")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "FiledHistoryOnboardingResult"),
            identity="app.live.filed.pull_all",
        ),
    ),
    CommandSpec(
        key="app_live_filed_pull",
        parent_key="app_live_filed",
        token="pull",
        kind="leaf",
        help_key=_key("cli.app.live.filed.pull_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="modelos",
                declarations=("--modelo",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(()),
                help_key=_key("cli.app.live.filed.pull_modelo_help"),
                multiple=True,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="year",
                declarations=("--year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            OptionSpec(
                name="year_from",
                declarations=("--from-year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.from_year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            OptionSpec(
                name="year_to",
                declarations=("--to-year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.to_year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            OptionSpec(
                name="output_root",
                declarations=("--output-root",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.output_root_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="period",
                declarations=("--period",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.period_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="expediente_id",
                declarations=("--expediente",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.expediente_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="limit",
                declarations=("--limit",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.limit_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=1, maximum=None),
            ),
            OptionSpec(
                name="dry_run",
                declarations=("--dry-run",),
                value=ValueContract(DeferredTarget("builtins", "bool")),
                default=ParameterDefault.value(False),
                help_key=_key("cli.app.live.filed.pull_dry_run_help"),
                multiple=False,
                is_flag=True,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts", "network"]),
            side_effects=frozenset(["local-state", "network"]),
            performance="external-io",
            write_route="profile-bound",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live", "filed_pull_cmd")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "FiledCaptureResult"),
            identity="app.live.filed.pull",
        ),
    ),
    CommandSpec(
        key="app_live_filed_pull_sources",
        parent_key="app_live_filed",
        token="pull-sources",
        kind="leaf",
        help_key=_key("cli.app.live.filed.pull_sources_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="modelo",
                declarations=("--modelo",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.modelo_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="year",
                declarations=("--year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            OptionSpec(
                name="period",
                declarations=("--period",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.period_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="output_root",
                declarations=("--output-root",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.output_root_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="registry_root",
                declarations=("--registry-root",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.registry_root_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="source_root",
                declarations=("--source-root",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.source_root_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts", "network"]),
            side_effects=frozenset(["local-state", "network"]),
            performance="external-io",
            write_route="profile-bound",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live", "filed_pull_sources_cmd")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "FiledCaptureSourcesResult"),
            identity="app.live.filed.pull_sources",
        ),
    ),
    CommandSpec(
        key="app_live_iva_wallet",
        parent_key="app_live",
        token="iva-wallet",
        kind="group",
        help_key=_key("cli.app.live.iva_wallet.app_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["state-free"]),
            side_effects=frozenset(["none"]),
            performance="metadata",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_live_iva_wallet_pull",
        parent_key="app_live_iva_wallet",
        token="pull",
        kind="leaf",
        help_key=_key("cli.app.live.iva_wallet.pull_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="year",
                declarations=("--year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            OptionSpec(
                name="period",
                declarations=("--period",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.period_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="taxpayer_nif",
                declarations=("--taxpayer-nif",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.iva_wallet.taxpayer_nif_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts", "network"]),
            side_effects=frozenset(["local-state", "network"]),
            performance="external-io",
            write_route="profile-bound",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live", "iva_wallet_pull_cmd")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "IvaWalletPullResult"),
            identity="app.live.iva_wallet.pull",
        ),
    ),
    CommandSpec(
        key="app_live_iva_wallet_history",
        parent_key="app_live_iva_wallet",
        token="history",
        kind="leaf",
        help_key=_key("cli.app.live.iva_wallet.history_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="as_of_year",
                declarations=("--as-of-year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.iva_wallet.as_of_year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live", "iva_wallet_history_cmd")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "IvaWalletHistoryResult"),
            identity="app.live.iva_wallet.history",
        ),
    ),
    CommandSpec(
        key="app_live_iva_wallet_pull_history",
        parent_key="app_live_iva_wallet",
        token="pull-history",
        kind="leaf",
        help_key=_key("cli.app.live.iva_wallet.pull_history_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="year_from",
                declarations=("--from-year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.from_year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            OptionSpec(
                name="year_to",
                declarations=("--to-year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.to_year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            OptionSpec(
                name="output_root",
                declarations=("--output-root",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.output_root_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts", "network"]),
            side_effects=frozenset(["local-state", "network"]),
            performance="external-io",
            write_route="profile-bound",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live", "iva_wallet_pull_history_cmd")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "IvaWalletCaptureHistoryResult"),
            identity="app.live.iva_wallet.pull_history",
        ),
    ),
    CommandSpec(
        key="app_live_iva_wallet_pull_evidence",
        parent_key="app_live_iva_wallet",
        token="pull-evidence",
        kind="leaf",
        help_key=_key("cli.app.live.iva_wallet.pull_evidence_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="year_from",
                declarations=("--from-year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.from_year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            OptionSpec(
                name="year_to",
                declarations=("--to-year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.to_year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            OptionSpec(
                name="target_year",
                declarations=("--target-year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            OptionSpec(
                name="target_period",
                declarations=("--target-period",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.period_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="taxpayer_nif",
                declarations=("--taxpayer-nif",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.iva_wallet.taxpayer_nif_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="output_root",
                declarations=("--output-root",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.output_root_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["browser", "encrypted-facts", "subprocess"]),
            side_effects=frozenset(["browser", "local-state", "network"]),
            performance="external-io",
            write_route="profile-bound",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live", "iva_wallet_pull_evidence_cmd")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "IvaWalletPullEvidenceResult"),
            identity="app.live.iva_wallet.pull_evidence",
        ),
    ),
    CommandSpec(
        key="app_live_notifications",
        parent_key="app_live",
        token="notifications",
        kind="group",
        help_key=_key("cli.app.live.notifications.app_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["state-free"]),
            side_effects=frozenset(["none"]),
            performance="metadata",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_live_notifications_pull",
        parent_key="app_live_notifications",
        token="pull",
        kind="leaf",
        help_key=_key("cli.app.live.notifications.pull_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts", "network"]),
            side_effects=frozenset(["local-state", "network"]),
            performance="external-io",
            write_route="profile-bound",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live_notifications_cli", "notifications_pull")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "NotificationsCaptureResult"),
            identity="app.live.notifications.pull",
        ),
    ),
    CommandSpec(
        key="app_live_notifications_list",
        parent_key="app_live_notifications",
        token="list",
        kind="leaf",
        help_key=_key("cli.app.live.notifications.list_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live_notifications_cli", "notifications_list")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "NotificationsListResult"),
            identity="app.live.notifications.list",
        ),
    ),
    CommandSpec(
        key="app_live_notifications_view",
        parent_key="app_live_notifications",
        token="view",
        kind="leaf",
        help_key=_key("cli.app.live.notifications.view_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="snapshot_id",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.notifications.snapshot_id_help"),
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live_notifications_cli", "notifications_show")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "NotificationsViewResult"),
            identity="app.live.notifications.view",
        ),
    ),
    CommandSpec(
        key="app_live_notifications_latest",
        parent_key="app_live_notifications",
        token="latest",
        kind="leaf",
        help_key=_key("cli.app.live.notifications.latest_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live_notifications_cli", "notifications_latest")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "NotificationsLatestResult"),
            identity="app.live.notifications.latest",
        ),
    ),
    CommandSpec(
        key="app_live_notifications_document",
        parent_key="app_live_notifications",
        token="document",
        kind="group",
        help_key=_key("cli.app.live.notifications.document.app_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["state-free"]),
            side_effects=frozenset(["none"]),
            performance="metadata",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_live_notifications_document_pull",
        parent_key="app_live_notifications_document",
        token="pull",
        kind="leaf",
        help_key=_key("cli.app.live.notifications.document.pull_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="certificado_id",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.notifications.document.certificado_id_help"),
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts", "network"]),
            side_effects=frozenset(["local-state", "network"]),
            performance="external-io",
            write_route="profile-bound",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live_notifications_cli", "notifications_document_pull")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "NotificationDocumentPullResult"),
            identity="app.live.notifications.document.pull",
        ),
    ),
    CommandSpec(
        key="app_live_notifications_document_view",
        parent_key="app_live_notifications_document",
        token="view",
        kind="leaf",
        help_key=_key("cli.app.live.notifications.document.view_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="certificado_id",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.notifications.document.certificado_id_help"),
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live_notifications_cli", "notifications_document_view")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "NotificationDocumentViewResult"),
            identity="app.live.notifications.document.view",
        ),
    ),
    CommandSpec(
        key="app_live_notifications_document_history",
        parent_key="app_live_notifications_document",
        token="history",
        kind="leaf",
        help_key=_key("cli.app.live.notifications.document.history_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live_notifications_cli", "notifications_document_history")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "NotificationDocumentHistoryResult"),
            identity="app.live.notifications.document.history",
        ),
    ),
    CommandSpec(
        key="app_live_portals",
        parent_key="app_live",
        token="portals",
        kind="group",
        help_key=_key("cli.app.live.portals.app_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["state-free"]),
            side_effects=frozenset(["none"]),
            performance="metadata",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_live_portals_list",
        parent_key="app_live_portals",
        token="list",
        kind="leaf",
        help_key=_key("cli.app.live.portals.list_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="category",
                declarations=("--category",),
                value=ValueContract(DeferredTarget("cadrumo.domain.portals", "PortalCategory")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.portals.category_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="modelo",
                declarations=("--modelo",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.portals.modelo_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["state-free"]),
            side_effects=frozenset(["none"]),
            performance="metadata",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live_portals_cli", "portals_list")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "PortalsListResult"),
            identity="app.live.portals.list",
        ),
    ),
    CommandSpec(
        key="app_live_portals_view",
        parent_key="app_live_portals",
        token="view",
        kind="leaf",
        help_key=_key("cli.app.live.portals.view_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="portal_id",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.portals.portal_id_help"),
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["state-free"]),
            side_effects=frozenset(["none"]),
            performance="metadata",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live_portals_cli", "portals_show")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "PortalsViewResult"),
            identity="app.live.portals.view",
        ),
    ),
    CommandSpec(
        key="app_live_deudas",
        parent_key="app_live",
        token="deudas",
        kind="group",
        help_key=_key("cli.app.live.deudas.app_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["state-free"]),
            side_effects=frozenset(["none"]),
            performance="metadata",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_live_deudas_list",
        parent_key="app_live_deudas",
        token="list",
        kind="leaf",
        help_key=_key("cli.app.live.deudas.list_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live_deudas_cli", "deudas_list")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "DeudasListResult"),
            identity="app.live.deudas.list",
        ),
    ),
    CommandSpec(
        key="app_live_deudas_view",
        parent_key="app_live_deudas",
        token="view",
        kind="leaf",
        help_key=_key("cli.app.live.deudas.view_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="snapshot_id",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.deudas.snapshot_id_help"),
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live_deudas_cli", "deudas_view")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "DeudasViewResult"),
            identity="app.live.deudas.view",
        ),
    ),
    CommandSpec(
        key="app_live_deudas_latest",
        parent_key="app_live_deudas",
        token="latest",
        kind="leaf",
        help_key=_key("cli.app.live.deudas.latest_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live_deudas_cli", "deudas_latest")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "DeudasLatestResult"),
            identity="app.live.deudas.latest",
        ),
    ),
    CommandSpec(
        key="app_live_expedientes",
        parent_key="app_live",
        token="expedientes",
        kind="group",
        help_key=_key("cli.app.live.expedientes.app_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["state-free"]),
            side_effects=frozenset(["none"]),
            performance="metadata",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_live_expedientes_pull",
        parent_key="app_live_expedientes",
        token="pull",
        kind="leaf",
        help_key=_key("cli.app.live.expedientes.pull_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="modelos",
                declarations=("--modelo",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(()),
                help_key=_key("cli.app.live.filed.pull_modelo_help"),
                multiple=True,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="year",
                declarations=("--year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            OptionSpec(
                name="year_from",
                declarations=("--from-year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.from_year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            OptionSpec(
                name="year_to",
                declarations=("--to-year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.to_year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts", "network"]),
            side_effects=frozenset(["local-state", "network"]),
            performance="external-io",
            write_route="profile-bound",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live_expedientes_cli", "expedientes_pull")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "ExpedientesCaptureResult"),
            identity="app.live.expedientes.pull",
        ),
    ),
    CommandSpec(
        key="app_live_expedientes_list",
        parent_key="app_live_expedientes",
        token="list",
        kind="leaf",
        help_key=_key("cli.app.live.expedientes.list_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live_expedientes_cli", "expedientes_list")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "ExpedientesListResult"),
            identity="app.live.expedientes.list",
        ),
    ),
    CommandSpec(
        key="app_live_expedientes_view",
        parent_key="app_live_expedientes",
        token="view",
        kind="leaf",
        help_key=_key("cli.app.live.expedientes.view_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="snapshot_id",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.expedientes.snapshot_id_help"),
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live_expedientes_cli", "expedientes_show")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "ExpedientesViewResult"),
            identity="app.live.expedientes.view",
        ),
    ),
    CommandSpec(
        key="app_live_expedientes_latest",
        parent_key="app_live_expedientes",
        token="latest",
        kind="leaf",
        help_key=_key("cli.app.live.expedientes.latest_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live_expedientes_cli", "expedientes_latest")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "ExpedientesLatestResult"),
            identity="app.live.expedientes.latest",
        ),
    ),
    CommandSpec(
        key="app_live_justificante",
        parent_key="app_live",
        token="justificante",
        kind="group",
        help_key=_key("cli.app.live.justificante.app_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["state-free"]),
            side_effects=frozenset(["none"]),
            performance="metadata",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_live_justificante_pull",
        parent_key="app_live_justificante",
        token="pull",
        kind="leaf",
        help_key=_key("cli.app.live.justificante.pull_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="modelo",
                declarations=("--modelo",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.modelo_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="year",
                declarations=("--year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
            OptionSpec(
                name="period",
                declarations=("--period",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.period_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts", "network"]),
            side_effects=frozenset(["local-state", "network"]),
            performance="external-io",
            write_route="profile-bound",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live_justificante_cli", "justificante_pull")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "JustificanteCaptureResult"),
            identity="app.live.justificante.pull",
        ),
    ),
    CommandSpec(
        key="app_live_justificante_list",
        parent_key="app_live_justificante",
        token="list",
        kind="leaf",
        help_key=_key("cli.app.live.justificante.list_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live_justificante_cli", "justificante_list")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "JustificanteListResult"),
            identity="app.live.justificante.list",
        ),
    ),
    CommandSpec(
        key="app_live_justificante_view",
        parent_key="app_live_justificante",
        token="view",
        kind="leaf",
        help_key=_key("cli.app.live.justificante.view_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="snapshot_id",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.justificante.snapshot_id_help"),
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live_justificante_cli", "justificante_view")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "JustificanteViewResult"),
            identity="app.live.justificante.view",
        ),
    ),
    CommandSpec(
        key="app_live_verify",
        parent_key="app_live",
        token="verify",
        kind="group",
        help_key=_key("cli.app.live.verify.app_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["state-free"]),
            side_effects=frozenset(["none"]),
            performance="metadata",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_live_verify_list",
        parent_key="app_live_verify",
        token="list",
        kind="leaf",
        help_key=_key("cli.app.live.verify.list_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="surface",
                declarations=("--surface",),
                value=ValueContract(DeferredTarget("cadrumo.application.live", "VerifySurface")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.verify.surface_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="nif",
                declarations=("--nif",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.verify.nif_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live_verify_cli", "verify_list")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "VerifyListResult"),
            identity="app.live.verify.list",
        ),
    ),
    CommandSpec(
        key="app_live_verify_view",
        parent_key="app_live_verify",
        token="view",
        kind="leaf",
        help_key=_key("cli.app.live.verify.view_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="observation_id",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.verify.observation_id_help"),
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live_verify_cli", "verify_show")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "VerifyViewResult"),
            identity="app.live.verify.view",
        ),
    ),
    CommandSpec(
        key="app_live_verify_latest",
        parent_key="app_live_verify",
        token="latest",
        kind="leaf",
        help_key=_key("cli.app.live.verify.latest_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="surface",
                declarations=("--surface",),
                value=ValueContract(DeferredTarget("cadrumo.application.live", "VerifySurface")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.verify.latest_surface_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="nif",
                declarations=("--nif",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.verify.latest_nif_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live_verify_cli", "verify_latest")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "VerifyLatestResult"),
            identity="app.live.verify.latest",
        ),
    ),
    CommandSpec(
        key="app_live_verify_nif_iva",
        parent_key="app_live_verify",
        token="nif-iva",
        kind="leaf",
        help_key=_key("cli.app.live.verify.nif_iva_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="nif",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.verify.nif_iva_arg_help"),
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="expected",
                declarations=("--expected",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.verify.expected_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts", "network"]),
            side_effects=frozenset(["local-state", "network"]),
            performance="external-io",
            write_route="profile-bound",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live_verify_cli", "verify_nif_iva")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "VerifyNifIvaResult"),
            identity="app.live.verify.nif_iva",
        ),
    ),
    CommandSpec(
        key="app_live_verify_tgvi",
        parent_key="app_live_verify",
        token="tgvi",
        kind="leaf",
        help_key=_key("cli.app.live.verify.tgvi_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="nif",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.verify.tgvi_arg_help"),
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
            OptionSpec(
                name="expected",
                declarations=("--expected",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=_key("cli.app.live.verify.expected_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts", "network"]),
            side_effects=frozenset(["local-state", "network"]),
            performance="external-io",
            write_route="profile-bound",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._app_live_verify_cli", "verify_tgvi")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "VerifyTgviResult"),
            identity="app.live.verify.tgvi",
        ),
    ),
    CommandSpec(
        key="app_live_borrador",
        parent_key="app_live",
        token="borrador",
        kind="group",
        help_key=_key("cli.app.live.borrador.app_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["state-free"]),
            side_effects=frozenset(["none"]),
            performance="metadata",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_live_borrador_100",
        parent_key="app_live_borrador",
        token="100",
        kind="group",
        help_key=_key("cli.app.live.borrador.modelo_100_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["state-free"]),
            side_effects=frozenset(["none"]),
            performance="metadata",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_live_borrador_100_list",
        parent_key="app_live_borrador_100",
        token="list",
        kind="leaf",
        help_key=_key("cli.app.live.borrador.list_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="state",
                declarations=("--state",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value("active"),
                help_key=_key("cli.app.live.borrador.state_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live_borrador_cli", "borrador_100_list")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "Borrador100ListResult"),
            identity="app.live.borrador.100.list",
        ),
    ),
    CommandSpec(
        key="app_live_borrador_100_view",
        parent_key="app_live_borrador_100",
        token="view",
        kind="leaf",
        help_key=_key("cli.app.live.borrador.view_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="snapshot_id",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.borrador.snapshot_id_help"),
                constraint=ParameterConstraint(minimum=None, maximum=None),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live_borrador_cli", "borrador_100_show")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "Borrador100ViewResult"),
            identity="app.live.borrador.100.view",
        ),
    ),
    CommandSpec(
        key="app_live_borrador_100_latest",
        parent_key="app_live_borrador_100",
        token="latest",
        kind="leaf",
        help_key=_key("cli.app.live.borrador.latest_help"),
        short_help_key=None,
        invocation=InvocationSpec(no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="filing_year",
                declarations=("--filing-year",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=_key("cli.app.live.borrador.filing_year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(minimum=2000, maximum=2099),
            ),
        ),
        policy=ExecutionPolicySpec(
            capabilities=frozenset(["encrypted-facts"]),
            side_effects=frozenset(["none"]),
            performance="local-io",
            write_route="none",
            destructive=False,
            handoff=False,
            live_write=False,
        ),
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._app_live_borrador_cli", "borrador_100_latest")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._app_live_payloads", "Borrador100LatestResult"),
            identity="app.live.borrador.100.latest",
        ),
    ),
)

__all__ = ["LIVE_COMMAND_SPECS"]
