"""Authored CommandSpec declarations for the ledger foundation surface."""

# ruff: noqa: S106 - command tokens are operator verbs, never credentials

from __future__ import annotations

from ._app_ledger_command_spec_policies import (
    _POLICY_1,
    _POLICY_2,
    _POLICY_3,
    _POLICY_4,
    _POLICY_6,
)
from ._app_ledger_command_spec_support import (
    _ARCHIVE_REASON_OPTION,
    _LEDGER_ACTOR_OPTION,
    _LEDGER_ADD_CATEGORY_ID_OPTION,
    _LEDGER_USAGE_RATIO_ID_OPTION,
    _OPTIONAL_YEAR_OPTION,
    _blank_default_text_option,
    _boolean_flag_option,
    _optional_text_option,
    _repeatable_text_option,
    _required_text_argument,
    _required_text_option,
)
from .command_spec import (
    CommandNodeKind,
    CommandSpec,
    DeferredTarget,
    InvocationSpec,
    LazyBinding,
    OptionSpec,
    ParameterConstraint,
    ParameterDefault,
    ResultSchemaSpec,
    SchemaState,
    TranslationKey,
    ValueContract,
)

LEDGER_FOUNDATION_COMMAND_SPECS: tuple[CommandSpec, ...] = (
    CommandSpec(
        key="app_ledger",
        parent_key="app",
        token="ledger",
        kind=CommandNodeKind.GROUP,
        help_key=TranslationKey("cli.ledger.app_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=_POLICY_1,
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_ledger_add",
        parent_key="app_ledger",
        token="add",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.add.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            _required_text_option("booked_date", ("--date",), "cli.ledger.add.date_help"),
            _required_text_option("amount", ("--amount",), "cli.ledger.add.amount_help"),
            OptionSpec(
                name="direction",
                declarations=("--direction",),
                value=ValueContract(DeferredTarget("cadrumo.domain.transactions.enums", "TransactionDirection")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.ledger.add.direction_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            _required_text_option("description", ("--description",), "cli.ledger.add.description_help"),
            _optional_text_option("value_date", ("--value-date",), "cli.ledger.add.value_date_help"),
            OptionSpec(
                name="currency",
                declarations=("--currency",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value("EUR"),
                help_key=TranslationKey("cli.ledger.add.currency_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            _optional_text_option("counterparty", ("--counterparty",), "cli.ledger.add.counterparty_help"),
            OptionSpec(
                name="business_classification",
                declarations=("--classification",),
                value=ValueContract(DeferredTarget("cadrumo.domain.transactions.enums", "BusinessClassification")),
                default=ParameterDefault.value("NOT_YET_PROCESSED"),
                help_key=TranslationKey("cli.ledger.add.classification_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            _optional_text_option("business_pct", ("--business-pct",), "cli.ledger.add.business_pct_help"),
            _LEDGER_ADD_CATEGORY_ID_OPTION,
            _optional_text_option("taxable_base", ("--taxable-base",), "cli.ledger.add.taxable_base_help"),
            _optional_text_option("iva_rate", ("--iva-rate",), "cli.ledger.add.iva_rate_help"),
            _optional_text_option("iva_amount", ("--iva-amount",), "cli.ledger.add.iva_amount_help"),
            OptionSpec(
                name="iva_category",
                declarations=("--iva-category",),
                value=ValueContract(DeferredTarget("cadrumo.domain.iva.schema", "IvaCategory")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.classify.iva_category_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="deduction_fact_kind",
                declarations=("--deduction-kind",),
                value=ValueContract(DeferredTarget("cadrumo.core.iva_deduction_fact", "IvaDeductionFactKind")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.classify.deduction_fact_kind_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            _optional_text_option(
                "counterparty_country", ("--counterparty-country",), "cli.ledger.classify.counterparty_country_help"
            ),
            OptionSpec(
                name="counterparty_identification_state",
                declarations=("--counterparty-identification-state",),
                value=ValueContract(DeferredTarget("cadrumo.domain.iva.schema", "EUMemberState")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.classify.counterparty_identification_state_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            _optional_text_option("recargo_amount", ("--recargo-amount",), "cli.ledger.add.recargo_amount_help"),
            _optional_text_option("irpf_category", ("--irpf-category",), "cli.ledger.add.irpf_category_help"),
            _LEDGER_USAGE_RATIO_ID_OPTION,
            _optional_text_option(
                "prorrata_reference", ("--prorrata-reference",), "cli.ledger.add.prorrata_reference_help"
            ),
            OptionSpec(
                name="art_104_tres_exclusion",
                declarations=("--art-104-tres-exclusion",),
                value=ValueContract(DeferredTarget("cadrumo.core.prorrata_exclusions", "Art104TresExclusion")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.add.art_104_tres_exclusion_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="input_classification",
                declarations=("--input-classification",),
                value=ValueContract(DeferredTarget("cadrumo.domain.iva.prorrata", "InputClassification")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.add.input_classification_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            _optional_text_option("prorrata_sector", ("--sector",), "cli.ledger.add.prorrata_sector_help"),
            _optional_text_option(
                "purchase_invoice_evidence_id",
                ("--purchase-invoice-evidence-id",),
                "cli.ledger.add.purchase_invoice_evidence_help",
            ),
            _repeatable_text_option("attachment_ids", ("--attachment-id",), "cli.ledger.add.attachment_help"),
            _blank_default_text_option("notes", ("--notes",), "cli.ledger.add.notes_help"),
            _LEDGER_ACTOR_OPTION,
            _optional_text_option("idempotency_key", ("--idempotency-key",), "cli.ledger.add.idempotency_key_help"),
            _optional_text_option(
                "source_jurisdiction", ("--source-jurisdiction",), "cli.ledger.add.source_jurisdiction_help"
            ),
        ),
        policy=_POLICY_2,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._ledger", "ledger_add")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerAddResult"),
            identity="ledger.add",
        ),
    ),
    CommandSpec(
        key="app_ledger_allocate",
        parent_key="app_ledger",
        token="allocate",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.allocate.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            _required_text_argument("transaction_id", "cli.ledger.allocate.id_help"),
            _required_text_option("business_pct", ("--business-pct",), "cli.ledger.allocate.business_pct_help"),
            _LEDGER_ADD_CATEGORY_ID_OPTION,
            _LEDGER_USAGE_RATIO_ID_OPTION,
            _optional_text_option(
                "prorrata_reference", ("--prorrata-reference",), "cli.ledger.allocate.prorrata_reference_help"
            ),
            _LEDGER_ACTOR_OPTION,
        ),
        policy=_POLICY_3,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._ledger", "ledger_allocate")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerAllocateResult"),
            identity="ledger.allocate",
        ),
    ),
    CommandSpec(
        key="app_ledger_archive",
        parent_key="app_ledger",
        token="archive",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.archive.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            _required_text_argument("transaction_id", "cli.ledger.archive.id_help"),
            _ARCHIVE_REASON_OPTION,
            _boolean_flag_option("yes", ("--yes",), "cli.ledger.archive.yes_help"),
            _LEDGER_ACTOR_OPTION,
        ),
        policy=_POLICY_4,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli.ledger_lifecycle_cli", "ledger_archive")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerArchiveResult"),
            identity="ledger.archive",
        ),
    ),
    CommandSpec(
        key="app_ledger_attach",
        parent_key="app_ledger",
        token="attach",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.attach.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            _required_text_argument("transaction_id", "cli.ledger.attach.id_help"),
            _optional_text_option(
                "purchase_invoice_evidence_id",
                ("--purchase-invoice-evidence-id",),
                "cli.ledger.attach.purchase_invoice_evidence_help",
            ),
            _repeatable_text_option("attachment_ids", ("--attachment-id",), "cli.ledger.attach.attachment_help"),
            _LEDGER_ACTOR_OPTION,
        ),
        policy=_POLICY_4,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli.ledger_lifecycle_cli", "ledger_attach")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerAttachResult"),
            identity="ledger.attach",
        ),
    ),
    CommandSpec(
        key="app_ledger_bienes_inversion",
        parent_key="app_ledger",
        token="bienes-inversion",
        kind=CommandNodeKind.GROUP,
        help_key=TranslationKey("cli.app.ledger.bienes_inversion.group_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=_POLICY_1,
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_ledger_categories",
        parent_key="app_ledger",
        token="categories",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.categories.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(),
        policy=_POLICY_6,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._ledger_read_cli", "ledger_categories")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerCategoriesResult"),
            identity="ledger.categories",
        ),
    ),
    CommandSpec(
        key="app_ledger_check",
        parent_key="app_ledger",
        token="check",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.ledger.check.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            _optional_text_option("bucket_id_option", ("--bucket-id",), "cli.ledger.check.bucket_id_help"),
            _optional_text_option("period", ("--period",), "cli.ledger.check.period_help"),
            _OPTIONAL_YEAR_OPTION,
        ),
        policy=_POLICY_6,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._ledger_read_cli", "ledger_check")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerCheckResult"),
            identity="ledger.check",
        ),
    ),
)

__all__ = ["LEDGER_FOUNDATION_COMMAND_SPECS"]
