"""Authored CommandSpec declarations for the ledger management surface."""

# ruff: noqa: S106 - command tokens are operator verbs, never credentials

from __future__ import annotations

from ...core.transport_locus import TransportLocus, TransportRole, TransportShape
from ._app_ledger_command_spec_policies import (
    _POLICY_1,
    _POLICY_3,
    _POLICY_5,
    _POLICY_6,
    _POLICY_8,
    _POLICY_9,
)
from ._command_spec import (
    ArgumentSpec,
    CommandSpec,
    DeferredTarget,
    InvocationSpec,
    LazyBinding,
    OptionSpec,
    ParameterConstraint,
    ParameterDefault,
    ResultSchemaSpec,
    SchemaState,
    TranslationKey,
    ValueContract,
)

LEDGER_MANAGEMENT_COMMAND_SPECS: tuple[CommandSpec, ...] = (
    CommandSpec(
        key="app_ledger_inventory",
        parent_key="app_ledger",
        token="inventory",
        kind="group",
        help_key=TranslationKey("cli.app.ledger.inventory.group_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=_POLICY_1,
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_ledger_invoice",
        parent_key="app_ledger",
        token="invoice",
        kind="group",
        help_key=TranslationKey("cli.app.ledger.invoice.group_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=_POLICY_1,
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_ledger_link",
        parent_key="app_ledger",
        token="link",
        kind="leaf",
        help_key=TranslationKey("cli.ledger.link.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="transaction_id",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.ledger.link.id_help"),
                metavar=None,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="invoice_id",
                declarations=("--invoice-id",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.ledger.link.invoice_id_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="actor",
                declarations=("--by",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.link.actor_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_3,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._ledger", "ledger_link")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerLinkResult"),
            identity="ledger.link",
        ),
    ),
    CommandSpec(
        key="app_ledger_list",
        parent_key="app_ledger",
        token="list",
        kind="leaf",
        help_key=TranslationKey("cli.ledger.list.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="filters",
                declarations=("--filter",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(()),
                help_key=TranslationKey("cli.ledger.list.filter_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=True,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="period",
                declarations=("--period",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.export.period_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="year",
                declarations=("--year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.check.year_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="limit",
                declarations=("--limit",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.list.limit_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(minimum=1),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="offset",
                declarations=("--offset",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(0),
                help_key=TranslationKey("cli.ledger.list.offset_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(minimum=0),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="group",
                declarations=("--group",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.list.group_filter_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="by_group",
                declarations=("--by-group",),
                value=ValueContract(DeferredTarget("builtins", "bool")),
                default=ParameterDefault.value(False),
                help_key=TranslationKey("cli.ledger.list.by_group_help"),
                metavar=None,
                is_flag=True,
                flag_value=True,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="sort_by",
                declarations=("--sort-by",),
                value=ValueContract(DeferredTarget("cadrumo.core", "LedgerSortField")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.list.sort_by_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="sort_order",
                declarations=("--sort-order",),
                value=ValueContract(DeferredTarget("cadrumo.core", "LedgerSortOrder")),
                default=ParameterDefault.value("asc"),
                help_key=TranslationKey("cli.ledger.list.sort_order_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="hide_llm_rejected",
                declarations=("--hide-llm-rejected",),
                value=ValueContract(DeferredTarget("builtins", "bool")),
                default=ParameterDefault.value(False),
                help_key=TranslationKey("cli.ledger.list.hide_llm_rejected_help"),
                metavar=None,
                is_flag=True,
                flag_value=True,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_5,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._ledger_read_cli", "ledger_list")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerListResult"),
            identity="ledger.list",
        ),
    ),
    CommandSpec(
        key="app_ledger_llm_diagnostics",
        parent_key="app_ledger",
        token="llm-diagnostics",
        kind="leaf",
        help_key=TranslationKey("cli.ledger.llm_diagnostics.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="since",
                declarations=("--since",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.llm_diagnostics.since_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="until",
                declarations=("--until",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.llm_diagnostics.until_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="low_confidence_below",
                declarations=("--low-confidence-below",),
                value=ValueContract(DeferredTarget("builtins", "float")),
                default=ParameterDefault.value(0.5),
                help_key=TranslationKey("cli.ledger.llm_diagnostics.threshold_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_5,
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._ledger_read_cli", "ledger_llm_diagnostics")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_rule_payloads", "LedgerLlmDiagnosticsResult"),
            identity="ledger.llm_diagnostics",
        ),
    ),
    CommandSpec(
        key="app_ledger_merge",
        parent_key="app_ledger",
        token="merge",
        kind="leaf",
        help_key=TranslationKey("cli.ledger.merge.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="child_id",
                declarations=("--child-id",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(()),
                help_key=TranslationKey("cli.ledger.merge.child_id_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=True,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="reason",
                declarations=("--reason",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(""),
                help_key=TranslationKey("cli.ledger.merge.reason_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="yes",
                declarations=("--yes",),
                value=ValueContract(DeferredTarget("builtins", "bool")),
                default=ParameterDefault.value(False),
                help_key=TranslationKey("cli.ledger.merge.yes_help"),
                metavar=None,
                is_flag=True,
                flag_value=True,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="actor",
                declarations=("--actor",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.merge.actor_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_9,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._ledger_lifecycle_cli", "ledger_merge")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerMergeResult"),
            identity="ledger.merge",
        ),
    ),
    CommandSpec(
        key="app_ledger_participation",
        parent_key="app_ledger",
        token="participation",
        kind="group",
        help_key=TranslationKey("cli.ledger.participation.help"),
        short_help_key=None,
        invocation=InvocationSpec(
            invoke_without_command=True,
            no_args_is_help=False,
            context_parameter="ctx",
            terminal_behavior="executable",
        ),
        parameters=(
            ArgumentSpec(
                name="transaction_id",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.participation.transaction_id_help"),
                metavar=None,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_5,
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._participation_cli", "participation_lookup")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerTransactionParticipationPayload"),
            identity="ledger.participation",
        ),
    ),
    CommandSpec(
        key="app_ledger_preflight",
        parent_key="app_ledger",
        token="preflight",
        kind="leaf",
        help_key=TranslationKey("cli.ledger.preflight.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="period",
                declarations=("--period",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.ledger.export.period_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="year",
                declarations=("--year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.ledger.preflight.year_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_6,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._ledger_read_cli", "ledger_preflight")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerPreflightResult"),
            identity="ledger.preflight",
        ),
    ),
    CommandSpec(
        key="app_ledger_prorrata",
        parent_key="app_ledger",
        token="prorrata",
        kind="group",
        help_key=TranslationKey("cli.app.ledger.prorrata.group_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=_POLICY_1,
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_ledger_evidence_pull_all",
        parent_key="app_ledger_evidence",
        token="pull-all",
        kind="leaf",
        help_key=TranslationKey("cli.app.ledger.evidence.pull_all_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="folder",
                declarations=("--folder",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.evidence.pull_all_folder_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
                transport_locus=TransportLocus.REMOTE_HANDLE,
                transport_shape=TransportShape.NOT_APPLICABLE,
                transport_role=TransportRole.NOT_APPLICABLE,
            ),
            OptionSpec(
                name="note",
                declarations=("--note",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(""),
                help_key=TranslationKey("cli.app.ledger.evidence.pull_all_note_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_8,
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._ledger_lifecycle_cli", "ledger_evidence_pull_all")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerDocLinkPullFolderResult"),
            identity="ledger.evidence.pull_all",
        ),
    ),
    CommandSpec(
        key="app_ledger_ratios",
        parent_key="app_ledger",
        token="ratios",
        kind="group",
        help_key=TranslationKey("cli.app.ledger.ratios.group_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=_POLICY_1,
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
)

__all__ = ["LEDGER_MANAGEMENT_COMMAND_SPECS"]
