"""Authored CommandSpec declarations for the ledger operations surface."""

# ruff: noqa: S106 - command tokens are operator verbs, never credentials

from __future__ import annotations

from ...core.transport_locus import TransportLocus, TransportRole, TransportShape
from ._app_ledger_command_spec_policies import (
    _POLICY_1,
    _POLICY_2,
    _POLICY_4,
    _POLICY_5,
    _POLICY_8,
    _POLICY_10,
)
from .command_spec import (
    ArgumentSpec,
    CommandSpec,
    DeferredTarget,
    InvocationSpec,
    LazyBinding,
    OptionSpec,
    ParameterConstraint,
    ParameterDefault,
    ResultSchemaSpec,
    SchemaState,
    TranslationKey,
    ValueContract,
)

LEDGER_OPERATIONS_COMMAND_SPECS: tuple[CommandSpec, ...] = (
    CommandSpec(
        key="app_ledger_counterparty",
        parent_key="app_ledger",
        token="counterparty",
        kind="group",
        help_key=TranslationKey("cli.app.ledger.counterparty.group_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=_POLICY_1,
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_ledger_detach",
        parent_key="app_ledger",
        token="detach",
        kind="leaf",
        help_key=TranslationKey("cli.ledger.detach.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="transaction_id",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.ledger.detach.id_help"),
                metavar=None,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="attachment_ids",
                declarations=("--attachment-id",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(()),
                help_key=TranslationKey("cli.ledger.detach.attachment_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=True,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="actor",
                declarations=("--actor",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.detach.actor_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_4,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli.ledger_lifecycle_cli", "ledger_detach")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerDetachResult"),
            identity="ledger.detach",
        ),
    ),
    CommandSpec(
        key="app_ledger_evidence_pull",
        parent_key="app_ledger_evidence",
        token="pull",
        kind="leaf",
        help_key=TranslationKey("cli.app.ledger.evidence.pull_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="transaction_id",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.evidence.pull_id_help"),
                metavar=None,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="source",
                declarations=("--source",),
                value=ValueContract(DeferredTarget("cadrumo.domain.attachments.enums", "DocumentLinkSource")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.evidence.pull_source_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="reference",
                declarations=("--reference",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.evidence.pull_reference_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
                transport_locus=TransportLocus.REMOTE_HANDLE,
                transport_shape=TransportShape.NOT_APPLICABLE,
                transport_role=TransportRole.NOT_APPLICABLE,
            ),
            OptionSpec(
                name="note",
                declarations=("--note",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(""),
                help_key=TranslationKey("cli.app.ledger.evidence.pull_note_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="actor",
                declarations=("--actor",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.evidence.pull_actor_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_8,
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli.ledger_lifecycle_cli", "ledger_evidence_pull")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerAttachResult"),
            identity="ledger.evidence.pull",
        ),
    ),
    CommandSpec(
        key="app_ledger_evidence",
        parent_key="app_ledger",
        token="evidence",
        kind="group",
        help_key=TranslationKey("cli.app.ledger.evidence.group_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=True, context_parameter=None),
        parameters=(),
        policy=_POLICY_1,
        handler=None,
        result_schema=ResultSchemaSpec(SchemaState.NOT_SUPPORTED),
    ),
    CommandSpec(
        key="app_ledger_exclude",
        parent_key="app_ledger",
        token="exclude",
        kind="leaf",
        help_key=TranslationKey("cli.ledger.exclude.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="transaction_id",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.evidence.pull_id_help"),
                metavar=None,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="reason",
                declarations=("--reason",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(""),
                help_key=TranslationKey("cli.ledger.exclude.reason_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="yes",
                declarations=("--yes",),
                value=ValueContract(DeferredTarget("builtins", "bool")),
                default=ParameterDefault.value(False),
                help_key=TranslationKey("cli.ledger.exclude.yes_help"),
                metavar=None,
                is_flag=True,
                flag_value=True,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="actor",
                declarations=("--actor",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.evidence.pull_actor_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_4,
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli.ledger_lifecycle_cli", "ledger_exclude")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerExcludeResult"),
            identity="ledger.exclude",
        ),
    ),
    CommandSpec(
        key="app_ledger_export",
        parent_key="app_ledger",
        token="export",
        kind="leaf",
        help_key=TranslationKey("cli.ledger.export.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="output",
                declarations=("--output",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.ledger.export.output_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
                transport_locus=TransportLocus.LOCAL_OUT,
                transport_shape=TransportShape.FILE,
                transport_role=TransportRole.PRIMARY,
            ),
            OptionSpec(
                name="export_kind",
                declarations=("--export-format",),
                value=ValueContract(DeferredTarget("cadrumo.application.export.tabular", "ExportSerializationFormat")),
                default=ParameterDefault.value("csv"),
                help_key=TranslationKey("cli.ledger.export.format_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="include_inactive",
                declarations=("--include-inactive",),
                value=ValueContract(DeferredTarget("builtins", "bool")),
                default=ParameterDefault.value(False),
                help_key=TranslationKey("cli.ledger.export.include_inactive_help"),
                metavar=None,
                is_flag=True,
                flag_value=True,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="period",
                declarations=("--period",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.export.period_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="year",
                declarations=("--year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.check.year_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="actor",
                declarations=("--actor",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.add.actor_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_10,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._ledger_read_cli", "ledger_export")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerExportPayload"),
            identity="ledger.export",
        ),
    ),
    CommandSpec(
        key="app_ledger_history",
        parent_key="app_ledger",
        token="history",
        kind="leaf",
        help_key=TranslationKey("cli.ledger.history.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="transaction_id",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.ledger.history.id_help"),
                metavar=None,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="include_split_siblings",
                declarations=("--include-split-siblings",),
                value=ValueContract(DeferredTarget("builtins", "bool")),
                default=ParameterDefault.value(False),
                help_key=TranslationKey("cli.ledger.history.include_split_siblings_help"),
                metavar=None,
                is_flag=True,
                flag_value=True,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_5,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._ledger_read_cli", "ledger_history")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerHistoryResult"),
            identity="ledger.history",
        ),
    ),
    CommandSpec(
        key="app_ledger_import",
        parent_key="app_ledger",
        token="import",
        kind="leaf",
        help_key=TranslationKey("cli.ledger.import.help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="file",
                declarations=("--file",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.ledger.import.file_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
                transport_locus=TransportLocus.LOCAL_IN,
                transport_shape=TransportShape.FILE,
                transport_role=TransportRole.PRIMARY,
            ),
            OptionSpec(
                name="provider",
                declarations=("--provider",),
                value=ValueContract(DeferredTarget("cadrumo.application.ledger.actions_import", "LedgerProviderID")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.ledger.import.provider_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="dry_run",
                declarations=("--dry-run",),
                value=ValueContract(DeferredTarget("builtins", "bool")),
                default=ParameterDefault.value(False),
                help_key=TranslationKey("cli.ledger.import.dry_run_help"),
                metavar=None,
                is_flag=True,
                flag_value=True,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="verify",
                declarations=("--verify",),
                value=ValueContract(DeferredTarget("builtins", "bool")),
                default=ParameterDefault.value(False),
                help_key=TranslationKey("cli.ledger.import.verify_help"),
                metavar=None,
                is_flag=True,
                flag_value=True,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="verify_source",
                declarations=("--verify-source",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.import.verify_source_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
                transport_locus=TransportLocus.LOCAL_IN,
                transport_shape=TransportShape.FILE,
                transport_role=TransportRole.AUXILIARY,
            ),
            OptionSpec(
                name="verbose",
                declarations=("--verbose",),
                value=ValueContract(DeferredTarget("builtins", "bool")),
                default=ParameterDefault.value(False),
                help_key=TranslationKey("cli.ledger.import.verbose_help"),
                metavar=None,
                is_flag=True,
                flag_value=True,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="period",
                declarations=("--period",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.export.period_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="year",
                declarations=("--year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.ledger.check.year_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_2,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._ledger_import_cli", "ledger_import")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._ledger_payloads", "LedgerImportPayload"),
            identity="ledger.import",
        ),
    ),
)

__all__ = ["LEDGER_OPERATIONS_COMMAND_SPECS"]
