"""Authored CommandSpec declarations for the ledger prorrata surface."""

# ruff: noqa: S106 - command tokens are operator verbs, never credentials

from __future__ import annotations

from ._app_ledger_command_spec_policies import (
    _POLICY_4,
    _POLICY_5,
)
from .command_spec import (
    CommandSpec,
    DeferredTarget,
    InvocationSpec,
    LazyBinding,
    OptionSpec,
    ParameterConstraint,
    ParameterDefault,
    ResultSchemaSpec,
    SchemaState,
    TranslationKey,
    ValueContract,
)

LEDGER_PRORRATA_COMMAND_SPECS: tuple[CommandSpec, ...] = (
    CommandSpec(
        key="app_ledger_prorrata_declare_sector",
        parent_key="app_ledger_prorrata",
        token="declare-sector",
        kind="leaf",
        help_key=TranslationKey("cli.app.ledger.prorrata.declare_sector_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="sector_id",
                declarations=("--sector-id",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.prorrata.sector_id_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="letra",
                declarations=("--letra",),
                value=ValueContract(DeferredTarget("cadrumo.core.prorrata_register", "SectorDiferenciadoLetra")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.prorrata.letra_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="activity_code",
                declarations=("--activity-code",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(()),
                help_key=TranslationKey("cli.app.ledger.prorrata.activity_code_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=True,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_4,
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._prorrata_register_cli", "prorrata_declare_sector")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._prorrata_register_payloads", "ProrrataDeclareSectorResult"),
            identity="ledger.prorrata.declare_sector",
        ),
    ),
    CommandSpec(
        key="app_ledger_prorrata_elect_especial",
        parent_key="app_ledger_prorrata",
        token="elect-especial",
        kind="leaf",
        help_key=TranslationKey("cli.app.ledger.prorrata.elect_especial_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="ejercicio",
                declarations=("--ejercicio",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.prorrata.ejercicio_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="percentage",
                declarations=("--percentage",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.prorrata.percentage_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="evidence_reference",
                declarations=("--evidence-reference",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.prorrata.optional_evidence_reference_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="provenance",
                declarations=("--provenance",),
                value=ValueContract(DeferredTarget("cadrumo.core.prorrata_register", "ProrrataProvisionalProvenance")),
                default=ParameterDefault.value("carried_prior_definitiva"),
                help_key=TranslationKey("cli.app.ledger.prorrata.provenance_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="reference",
                declarations=("--reference",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.prorrata.reference_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="sector",
                declarations=("--sector",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.prorrata.sector_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_4,
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._prorrata_register_cli", "prorrata_elect_especial")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._prorrata_register_payloads", "ProrrataElectEspecialResult"),
            identity="ledger.prorrata.elect_especial",
        ),
    ),
    CommandSpec(
        key="app_ledger_prorrata_elect_general",
        parent_key="app_ledger_prorrata",
        token="elect-general",
        kind="leaf",
        help_key=TranslationKey("cli.app.ledger.prorrata.elect_general_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="ejercicio",
                declarations=("--ejercicio",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.prorrata.ejercicio_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="percentage",
                declarations=("--percentage",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.prorrata.general_percentage_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="provenance",
                declarations=("--provenance",),
                value=ValueContract(DeferredTarget("cadrumo.core.prorrata_register", "ProrrataProvisionalProvenance")),
                default=ParameterDefault.value("carried_prior_definitiva"),
                help_key=TranslationKey("cli.app.ledger.prorrata.provenance_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="reference",
                declarations=("--reference",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.prorrata.reference_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="sector",
                declarations=("--sector",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.prorrata.sector_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_4,
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._prorrata_register_cli", "prorrata_elect_general")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._prorrata_register_payloads", "ProrrataElectGeneralResult"),
            identity="ledger.prorrata.elect_general",
        ),
    ),
    CommandSpec(
        key="app_ledger_prorrata_list",
        parent_key="app_ledger_prorrata",
        token="list",
        kind="leaf",
        help_key=TranslationKey("cli.app.ledger.prorrata.list_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(),
        policy=_POLICY_5,
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._prorrata_register_cli", "prorrata_list")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget("cadrumo.entrypoints.cli._prorrata_register_payloads", "ProrrataListResult"),
            identity="ledger.prorrata.list",
        ),
    ),
    CommandSpec(
        key="app_ledger_prorrata_revoke_especial",
        parent_key="app_ledger_prorrata",
        token="revoke-especial",
        kind="leaf",
        help_key=TranslationKey("cli.app.ledger.prorrata.revoke_especial_help"),
        short_help_key=None,
        invocation=InvocationSpec(invoke_without_command=False, no_args_is_help=False, context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="ejercicio",
                declarations=("--ejercicio",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.prorrata.ejercicio_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="evidence_reference",
                declarations=("--evidence-reference",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.prorrata.evidence_reference_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="percentage",
                declarations=("--percentage",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.ledger.prorrata.general_percentage_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="provenance",
                declarations=("--provenance",),
                value=ValueContract(DeferredTarget("cadrumo.core.prorrata_register", "ProrrataProvisionalProvenance")),
                default=ParameterDefault.value("carried_prior_definitiva"),
                help_key=TranslationKey("cli.app.ledger.prorrata.provenance_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="reference",
                declarations=("--reference",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.prorrata.reference_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
            OptionSpec(
                name="sector",
                declarations=("--sector",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.ledger.prorrata.sector_help"),
                metavar=None,
                is_flag=False,
                flag_value=None,
                multiple=False,
                count=False,
                eager=False,
                constraint=ParameterConstraint(),
                show_default=True,
                hidden=False,
            ),
        ),
        policy=_POLICY_4,
        handler=LazyBinding.available(
            DeferredTarget("cadrumo.entrypoints.cli._prorrata_register_cli", "prorrata_revoke_especial")
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            target=DeferredTarget(
                "cadrumo.entrypoints.cli._prorrata_register_payloads", "ProrrataRevokeEspecialResult"
            ),
            identity="ledger.prorrata.revoke_especial",
        ),
    ),
)

__all__ = ["LEDGER_PRORRATA_COMMAND_SPECS"]
