from __future__ import annotations

from typing import Final

from ...core.transport_locus import TransportLocus, TransportRole, TransportShape
from ._modelo_nonwork_command_spec_policies import (
    _CALCULATION_WRITE,
    _CRYPTO_FACT_FILE_WRITE,
    _CRYPTO_PROFILE_WRITE,
    _CRYPTO_READ,
)
from ._modelo_nonwork_common_command_parameters import (
    CALCULATION_REVISION_SELECTOR_OPTIONS,
    FILING_ELECTION_OPTIONS,
)
from .command_spec import (
    ArgumentSpec,
    CommandNodeKind,
    CommandSpec,
    DeferredTarget,
    InvocationSpec,
    LazyBinding,
    OptionSpec,
    ParameterConstraint,
    ParameterDefault,
    ResultSchemaSpec,
    SchemaState,
    TranslationKey,
    ValueContract,
)

_REVIEW_PACKAGE_INPUT: Final[ArgumentSpec] = ArgumentSpec(
    name="package",
    value=ValueContract(DeferredTarget("pathlib", "Path")),
    default=ParameterDefault.required(),
    help_key=TranslationKey("cli.app.modelo.review_package.package_path_help"),
    transport_locus=TransportLocus.LOCAL_IN,
    transport_shape=TransportShape.FILE,
    transport_role=TransportRole.PRIMARY,
)

_SIGNATURE_INPUT: Final[ArgumentSpec] = ArgumentSpec(
    name="signature",
    value=ValueContract(DeferredTarget("pathlib", "Path")),
    default=ParameterDefault.required(),
    help_key=TranslationKey("cli.app.modelo.review_package.signature_path_help"),
    transport_locus=TransportLocus.LOCAL_IN,
    transport_shape=TransportShape.FILE,
    transport_role=TransportRole.AUXILIARY,
)

_REVIEW_PACKAGE_BUCKET_ID_OPTION: Final[OptionSpec] = OptionSpec(
    name="bucket_id",
    declarations=("--bucket-id",),
    value=ValueContract(DeferredTarget("builtins", "str")),
    default=ParameterDefault.value(None),
    help_key=TranslationKey("cli.app.modelo.review_package.bucket_id_help"),
    multiple=False,
    is_flag=False,
    flag_value=None,
    constraint=ParameterConstraint(),
)

MODELO_NONWORK_REVIEW_PACKAGE_COMMAND_SPECS: tuple[CommandSpec, ...] = (
    CommandSpec(
        "app_modelo_review_package_build",
        "app_modelo_review_package",
        "build",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.modelo.review_package.build_help"),
        short_help_key=None,
        invocation=InvocationSpec(context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="work_unit_id",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.modelo.review_package.work_unit_id_help"),
            ),
            *CALCULATION_REVISION_SELECTOR_OPTIONS,
            OptionSpec(
                name="output",
                declarations=("--output",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.modelo.review_package.output_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
                transport_locus=TransportLocus.LOCAL_OUT,
                transport_shape=TransportShape.FILE,
                transport_role=TransportRole.PRIMARY,
            ),
            OptionSpec(
                name="revision",
                declarations=("--revision",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.modelo.review_package.revision_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="actor",
                declarations=("--by",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.modelo.review_package.actor_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            *FILING_ELECTION_OPTIONS,
            OptionSpec(
                name="notes",
                declarations=("--notes",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(""),
                help_key=TranslationKey("cli.app.modelo.review_package.notes_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
        ),
        policy=_CALCULATION_WRITE,
        handler=LazyBinding.available(
            DeferredTarget("._modelo_review_package_cli", "review_package_build", __package__)
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            DeferredTarget("._modelo_review_package_payloads", "ModeloReviewPackageBuildResult", __package__),
            identity="modelo.review_package.build",
        ),
    ),
    CommandSpec(
        "app_modelo_review_package_verify",
        "app_modelo_review_package",
        "verify",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.modelo.review_package.verify_help"),
        short_help_key=None,
        invocation=InvocationSpec(context_parameter="ctx"),
        parameters=(_REVIEW_PACKAGE_INPUT,),
        policy=_CRYPTO_READ,
        handler=LazyBinding.available(
            DeferredTarget("._modelo_review_package_cli", "review_package_verify", __package__)
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            DeferredTarget("._modelo_review_package_payloads", "ModeloReviewPackageVerifyResult", __package__),
            identity="modelo.review_package.verify",
        ),
    ),
    CommandSpec(
        "app_modelo_review_package_sign",
        "app_modelo_review_package",
        "sign",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.modelo.review_package.sign_help"),
        short_help_key=None,
        invocation=InvocationSpec(context_parameter="ctx"),
        parameters=(
            _REVIEW_PACKAGE_INPUT,
            OptionSpec(
                name="output",
                declarations=("--output",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.review_package.sign_output_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
                transport_locus=TransportLocus.LOCAL_OUT,
                transport_shape=TransportShape.FILE,
                transport_role=TransportRole.PRIMARY,
            ),
            _REVIEW_PACKAGE_BUCKET_ID_OPTION,
        ),
        policy=_CRYPTO_PROFILE_WRITE,
        handler=LazyBinding.available(
            DeferredTarget("._modelo_review_package_cli", "review_package_sign", __package__)
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            DeferredTarget("._modelo_review_package_payloads", "ModeloReviewPackageSignResult", __package__),
            identity="modelo.review_package.sign",
        ),
    ),
    CommandSpec(
        "app_modelo_review_package_verify_signature",
        "app_modelo_review_package",
        "verify-signature",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.modelo.review_package.verify_signature_help"),
        short_help_key=None,
        invocation=InvocationSpec(context_parameter="ctx"),
        parameters=(
            _REVIEW_PACKAGE_INPUT,
            _SIGNATURE_INPUT,
            OptionSpec(
                name="public_key",
                declarations=("--public-key",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.review_package.public_key_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
        ),
        policy=_CRYPTO_READ,
        handler=LazyBinding.available(
            DeferredTarget("._modelo_review_package_cli", "review_package_verify_signature", __package__)
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            DeferredTarget("._modelo_review_package_payloads", "ModeloReviewPackageVerifySignatureResult", __package__),
            identity="modelo.review_package.verify_signature",
        ),
    ),
    CommandSpec(
        "app_modelo_review_package_counter_sign",
        "app_modelo_review_package",
        "counter-sign",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.modelo.review_package.counter_sign_help"),
        short_help_key=None,
        invocation=InvocationSpec(context_parameter="ctx"),
        parameters=(
            _REVIEW_PACKAGE_INPUT,
            _SIGNATURE_INPUT,
            OptionSpec(
                name="output",
                declarations=("--output",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.review_package.counter_sign_output_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
                transport_locus=TransportLocus.LOCAL_OUT,
                transport_shape=TransportShape.FILE,
                transport_role=TransportRole.PRIMARY,
            ),
            OptionSpec(
                name="note",
                declarations=("--note",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(""),
                help_key=TranslationKey("cli.app.modelo.review_package.counter_sign_note_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            _REVIEW_PACKAGE_BUCKET_ID_OPTION,
        ),
        policy=_CRYPTO_PROFILE_WRITE,
        handler=LazyBinding.available(
            DeferredTarget("._modelo_review_package_cli", "review_package_counter_sign", __package__)
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            DeferredTarget("._modelo_review_package_payloads", "ModeloReviewPackageCounterSignResult", __package__),
            identity="modelo.review_package.counter_sign",
        ),
    ),
    CommandSpec(
        "app_modelo_review_package_verify_receipt",
        "app_modelo_review_package",
        "verify-receipt",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.modelo.review_package.verify_receipt_help"),
        short_help_key=None,
        invocation=InvocationSpec(context_parameter="ctx"),
        parameters=(
            _REVIEW_PACKAGE_INPUT,
            ArgumentSpec(
                name="receipt_path",
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.review_package.receipt_path_help"),
                transport_locus=TransportLocus.LOCAL_IN,
                transport_shape=TransportShape.FILE,
                transport_role=TransportRole.AUXILIARY,
            ),
            OptionSpec(
                name="operator_public_key",
                declarations=("--operator-public-key",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.review_package.operator_public_key_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="counter_signer_public_key",
                declarations=("--counter-signer-public-key",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.review_package.counter_signer_public_key_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
        ),
        policy=_CRYPTO_READ,
        handler=LazyBinding.available(
            DeferredTarget("._modelo_review_package_cli", "review_package_verify_receipt", __package__)
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            DeferredTarget("._modelo_review_package_payloads", "ModeloReviewPackageVerifyReceiptResult", __package__),
            identity="modelo.review_package.verify_receipt",
        ),
    ),
    CommandSpec(
        "app_modelo_review_package_encrypt_for_recipient",
        "app_modelo_review_package",
        "encrypt-for-recipient",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.modelo.review_package.encrypt_for_recipient_help"),
        short_help_key=None,
        invocation=InvocationSpec(context_parameter="ctx"),
        parameters=(
            _REVIEW_PACKAGE_INPUT,
            OptionSpec(
                name="recipient_id",
                declarations=("--recipient",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.review_package.recipient_id_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="output",
                declarations=("--output",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.review_package.encrypt_output_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
                transport_locus=TransportLocus.LOCAL_OUT,
                transport_shape=TransportShape.FILE,
                transport_role=TransportRole.PRIMARY,
            ),
            OptionSpec(
                name="review_only",
                declarations=("--review-only/--filing-grade",),
                value=ValueContract(DeferredTarget("builtins", "bool")),
                default=ParameterDefault.value(False),
                help_key=TranslationKey("cli.app.modelo.review_package.review_only_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="valid_for_days",
                declarations=("--valid-for-days",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.modelo.review_package.valid_for_days_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            _REVIEW_PACKAGE_BUCKET_ID_OPTION,
        ),
        policy=_CRYPTO_PROFILE_WRITE,
        handler=LazyBinding.available(
            DeferredTarget("._modelo_review_package_cli", "review_package_encrypt_for_recipient", __package__)
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            DeferredTarget(
                "._modelo_review_package_payloads",
                "ModeloReviewPackageEncryptForRecipientResult",
                __package__,
            ),
            identity="modelo.review_package.encrypt_for_recipient",
        ),
    ),
    CommandSpec(
        "app_modelo_review_package_decrypt",
        "app_modelo_review_package",
        "decrypt",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.modelo.review_package.decrypt_help"),
        short_help_key=None,
        invocation=InvocationSpec(context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="envelope_path",
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.review_package.envelope_path_help"),
                transport_locus=TransportLocus.LOCAL_IN,
                transport_shape=TransportShape.FILE,
                transport_role=TransportRole.PRIMARY,
            ),
            OptionSpec(
                name="output",
                declarations=("--output",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.review_package.decrypt_output_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
                transport_locus=TransportLocus.LOCAL_OUT,
                transport_shape=TransportShape.FILE,
                transport_role=TransportRole.PRIMARY,
            ),
            _REVIEW_PACKAGE_BUCKET_ID_OPTION,
        ),
        policy=_CRYPTO_PROFILE_WRITE,
        handler=LazyBinding.available(
            DeferredTarget("._modelo_review_package_cli", "review_package_decrypt", __package__)
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            DeferredTarget("._modelo_review_package_payloads", "ModeloReviewPackageDecryptResult", __package__),
            identity="modelo.review_package.decrypt",
        ),
    ),
    CommandSpec(
        "app_modelo_review_package_encrypt_feedback",
        "app_modelo_review_package",
        "encrypt-feedback",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.modelo.review_package.encrypt_feedback_help"),
        short_help_key=None,
        invocation=InvocationSpec(context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="originator_id",
                declarations=("--originator",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.review_package.originator_id_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="work_unit_id",
                declarations=("--work-unit-id",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.review_package.feedback_work_unit_id_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="calculation_revision_id",
                declarations=("--calculation-revision-id",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.review_package.feedback_revision_id_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="submitted_by",
                declarations=("--by",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.review_package.feedback_submitted_by_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="output",
                declarations=("--output",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.review_package.feedback_output_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
                transport_locus=TransportLocus.LOCAL_OUT,
                transport_shape=TransportShape.FILE,
                transport_role=TransportRole.PRIMARY,
            ),
            OptionSpec(
                name="note",
                declarations=("--note",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(""),
                help_key=TranslationKey("cli.app.modelo.review_package.feedback_note_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="receipt",
                declarations=("--receipt",),
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.modelo.review_package.feedback_receipt_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
                transport_locus=TransportLocus.LOCAL_IN,
                transport_shape=TransportShape.FILE,
                transport_role=TransportRole.AUXILIARY,
            ),
            _REVIEW_PACKAGE_BUCKET_ID_OPTION,
        ),
        policy=_CRYPTO_FACT_FILE_WRITE,
        handler=LazyBinding.available(
            DeferredTarget("._modelo_review_package_cli", "review_package_encrypt_feedback", __package__)
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            DeferredTarget("._modelo_review_package_payloads", "ModeloReviewPackageEncryptFeedbackResult", __package__),
            identity="modelo.review_package.encrypt_feedback",
        ),
    ),
    CommandSpec(
        "app_modelo_review_package_import_feedback",
        "app_modelo_review_package",
        "import-feedback",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.modelo.review_package.import_feedback_help"),
        short_help_key=None,
        invocation=InvocationSpec(context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="envelope_path",
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.review_package.feedback_envelope_path_help"),
                transport_locus=TransportLocus.LOCAL_IN,
                transport_shape=TransportShape.FILE,
                transport_role=TransportRole.PRIMARY,
            ),
            ArgumentSpec(
                name="package",
                value=ValueContract(DeferredTarget("pathlib", "Path")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.review_package.feedback_package_help"),
                transport_locus=TransportLocus.LOCAL_IN,
                transport_shape=TransportShape.FILE,
                transport_role=TransportRole.AUXILIARY,
            ),
            OptionSpec(
                name="operator_public_key_hex",
                declarations=("--operator-public-key",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.review_package.feedback_operator_public_key_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="counter_signer_public_key_hex",
                declarations=("--counter-signer-public-key",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.modelo.review_package.feedback_counter_signer_public_key_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            _REVIEW_PACKAGE_BUCKET_ID_OPTION,
        ),
        policy=_CRYPTO_PROFILE_WRITE,
        handler=LazyBinding.available(
            DeferredTarget("._modelo_review_package_cli", "review_package_import_feedback", __package__)
        ),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            DeferredTarget("._modelo_review_package_payloads", "ModeloReviewPackageImportFeedbackResult", __package__),
            identity="modelo.review_package.import_feedback",
        ),
    ),
)

__all__ = ["MODELO_NONWORK_REVIEW_PACKAGE_COMMAND_SPECS"]
"""Authored CommandSpec declarations for the Modelo non-work review package family."""
"""Authored CommandSpec declarations for the Modelo non-work review package family."""
