"""Authored CommandSpec declarations for the Modelo non-work m036 family."""

# ruff: noqa: S106 - command tokens are operator verbs, never credentials

from __future__ import annotations

from ._command_spec import (
    ArgumentSpec,
    CommandSpec,
    DeferredTarget,
    InvocationSpec,
    LazyBinding,
    OptionSpec,
    ParameterConstraint,
    ParameterDefault,
    ResultSchemaSpec,
    SchemaState,
    TranslationKey,
    ValueContract,
)
from ._modelo_nonwork_command_spec_policies import (
    _MODEL_READ,
    _MODEL_WRITE,
)

MODELO_NONWORK_M036_COMMAND_SPECS: tuple[CommandSpec, ...] = (
    CommandSpec(
        key="app_modelo_m036_alta",
        parent_key="app_modelo_m036",
        token="alta",
        kind="leaf",
        help_key=TranslationKey("cli.app.modelo.m036.alta_help"),
        short_help_key=None,
        invocation=InvocationSpec(context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="declared_on",
                declarations=("--declared-on",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.m036.declared_on_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="sede_justificante",
                declarations=("--sede-justificante",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.modelo.m036.justificante_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="note",
                declarations=("--note",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.modelo.m036.note_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
        ),
        policy=_MODEL_WRITE,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._modelo_m036_cli", "m036_alta")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            DeferredTarget("cadrumo.entrypoints.cli._modelo_payloads_m036", "M036DeclarationRecordResult"),
            identity="modelo.m036.alta",
        ),
    ),
    CommandSpec(
        key="app_modelo_m036_modificacion",
        parent_key="app_modelo_m036",
        token="modificacion",
        kind="leaf",
        help_key=TranslationKey("cli.app.modelo.m036.modificacion_help"),
        short_help_key=None,
        invocation=InvocationSpec(context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="declared_on",
                declarations=("--declared-on",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.m036.declared_on_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="sede_justificante",
                declarations=("--sede-justificante",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.modelo.m036.justificante_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="note",
                declarations=("--note",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.modelo.m036.note_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
        ),
        policy=_MODEL_WRITE,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._modelo_m036_cli", "m036_modificacion")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            DeferredTarget("cadrumo.entrypoints.cli._modelo_payloads_m036", "M036DeclarationRecordResult"),
            identity="modelo.m036.modificacion",
        ),
    ),
    CommandSpec(
        key="app_modelo_m036_baja",
        parent_key="app_modelo_m036",
        token="baja",
        kind="leaf",
        help_key=TranslationKey("cli.app.modelo.m036.baja_help"),
        short_help_key=None,
        invocation=InvocationSpec(context_parameter="ctx"),
        parameters=(
            OptionSpec(
                name="declared_on",
                declarations=("--declared-on",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.m036.declared_on_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="sede_justificante",
                declarations=("--sede-justificante",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.modelo.m036.justificante_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="note",
                declarations=("--note",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.modelo.m036.note_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
        ),
        policy=_MODEL_WRITE,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._modelo_m036_cli", "m036_baja")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            DeferredTarget("cadrumo.entrypoints.cli._modelo_payloads_m036", "M036DeclarationRecordResult"),
            identity="modelo.m036.baja",
        ),
    ),
    CommandSpec(
        key="app_modelo_m036_list",
        parent_key="app_modelo_m036",
        token="list",
        kind="leaf",
        help_key=TranslationKey("cli.app.modelo.m036.list_help"),
        short_help_key=None,
        invocation=InvocationSpec(context_parameter="ctx"),
        parameters=(),
        policy=_MODEL_READ,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._modelo_m036_cli", "m036_list")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            DeferredTarget("cadrumo.entrypoints.cli._modelo_payloads_m036", "M036DeclarationListResult"),
            identity="modelo.m036.list",
        ),
    ),
    CommandSpec(
        key="app_modelo_m036_view",
        parent_key="app_modelo_m036",
        token="view",
        kind="leaf",
        help_key=TranslationKey("cli.app.modelo.m036.view_help"),
        short_help_key=None,
        invocation=InvocationSpec(context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="declaration_id",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.m036.declaration_id_help"),
            ),
        ),
        policy=_MODEL_READ,
        handler=LazyBinding.available(DeferredTarget("cadrumo.entrypoints.cli._modelo_m036_cli", "m036_view")),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            DeferredTarget("cadrumo.entrypoints.cli._modelo_payloads_m036", "M036DeclarationShowResult"),
            identity="modelo.m036.view",
        ),
    ),
)

__all__ = ["MODELO_NONWORK_M036_COMMAND_SPECS"]
