"""Authored CommandSpec declarations for the Modelo non-work discovery family."""

# ruff: noqa: S106 - command tokens are operator verbs, never credentials

from __future__ import annotations

from typing import Final

from ._modelo_nonwork_command_spec_policies import (
    _REGISTRY_MODEL_READ,
    _REGISTRY_READ,
)
from .command_spec import (
    ArgumentSpec,
    CommandNodeKind,
    CommandSpec,
    DeferredTarget,
    InvocationSpec,
    LazyBinding,
    OptionSpec,
    ParameterConstraint,
    ParameterDefault,
    ResultSchemaSpec,
    SchemaState,
    TranslationKey,
    ValueContract,
)

_REGISTRY_YEAR_OPTION: Final[OptionSpec] = OptionSpec(
    name="year",
    declarations=("--year",),
    value=ValueContract(DeferredTarget("builtins", "int")),
    default=ParameterDefault.value(None),
    help_key=TranslationKey("cli.app.modelo.list.year_help"),
    multiple=False,
    is_flag=False,
    flag_value=None,
    constraint=ParameterConstraint(),
)

CASILLA_LOOKUP_SCOPE: Final[tuple[ArgumentSpec | OptionSpec, ...]] = (
    ArgumentSpec(
        name="modelo",
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.required(),
        help_key=TranslationKey("cli.app.modelo.casillas.modelo_help"),
    ),
    _REGISTRY_YEAR_OPTION,
    OptionSpec(
        name="period",
        declarations=("--period",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.value(None),
        help_key=TranslationKey("cli.app.modelo.casillas.period_help"),
        multiple=False,
        is_flag=False,
        flag_value=None,
        constraint=ParameterConstraint(),
    ),
    OptionSpec(
        name="as_of",
        declarations=("--as-of",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.value(None),
        help_key=TranslationKey("cli.app.modelo.casillas.as_of_help"),
        multiple=False,
        is_flag=False,
        flag_value=None,
        constraint=ParameterConstraint(),
    ),
)

MODELO_NONWORK_DISCOVERY_COMMAND_SPECS: tuple[CommandSpec, ...] = (
    CommandSpec(
        key="app_modelo_list",
        parent_key="app_modelo",
        token="list",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.modelo.list.help"),
        short_help_key=None,
        invocation=InvocationSpec(context_parameter="ctx"),
        parameters=(
            _REGISTRY_YEAR_OPTION,
            OptionSpec(
                name="domain",
                declarations=("--domain",),
                value=ValueContract(DeferredTarget("...core.tax_domain", "TaxDomain", __package__)),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.modelo.list.domain_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
        ),
        policy=_REGISTRY_READ,
        handler=LazyBinding.available(DeferredTarget("._modelo_discovery_cli", "list_modelos", __package__)),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            DeferredTarget(".modelo_aux_payloads", "ModeloListResult", __package__),
            identity="modelo.list",
        ),
    ),
    CommandSpec(
        key="app_modelo_describe",
        parent_key="app_modelo",
        token="describe",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.modelo.describe.help"),
        short_help_key=None,
        invocation=InvocationSpec(context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="modelo",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.describe.modelo_help"),
            ),
            _REGISTRY_YEAR_OPTION,
            OptionSpec(
                name="period",
                declarations=("--period",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.modelo.describe.period_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="as_of",
                declarations=("--as-of",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.modelo.describe.as_of_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
        ),
        policy=_REGISTRY_READ,
        handler=LazyBinding.available(DeferredTarget("._modelo_discovery_cli", "describe_modelo", __package__)),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            DeferredTarget(".modelo_aux_payloads", "ModeloDescribeResult", __package__),
            identity="modelo.describe",
        ),
    ),
    CommandSpec(
        key="app_modelo_casillas",
        parent_key="app_modelo",
        token="casillas",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.modelo.casillas.help"),
        short_help_key=None,
        invocation=InvocationSpec(context_parameter="ctx"),
        parameters=(
            *CASILLA_LOOKUP_SCOPE,
            OptionSpec(
                name="input_kind",
                declarations=("--input-kind",),
                value=ValueContract(
                    DeferredTarget("...domain.calculations.registry.schema_input_kind", "InputKind", __package__)
                ),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.modelo.casillas.input_kind_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="required",
                declarations=("--required",),
                value=ValueContract(DeferredTarget("builtins", "bool")),
                default=ParameterDefault.value(False),
                help_key=TranslationKey("cli.app.modelo.casillas.required_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="form_number",
                declarations=("--form-number",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.modelo.casillas.form_number_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="casilla_number",
                declarations=("--number",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.value(None),
                help_key=TranslationKey("cli.app.modelo.casillas.number_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="explain",
                declarations=("--explain",),
                value=ValueContract(DeferredTarget("builtins", "bool")),
                default=ParameterDefault.value(False),
                help_key=TranslationKey("cli.app.modelo.casillas.explain_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
        ),
        policy=_REGISTRY_READ,
        handler=LazyBinding.available(DeferredTarget("._modelo_discovery_cli", "casillas", __package__)),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            DeferredTarget("._modelo_payloads", "ModeloCasillasResult", __package__),
            identity="modelo.casillas",
        ),
    ),
    CommandSpec(
        key="app_modelo_casilla",
        parent_key="app_modelo",
        token="casilla",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.modelo.casilla.help"),
        short_help_key=None,
        invocation=InvocationSpec(context_parameter="ctx"),
        parameters=(
            CASILLA_LOOKUP_SCOPE[0],
            ArgumentSpec(
                name="casilla_id",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.casilla.casilla_help"),
            ),
            *CASILLA_LOOKUP_SCOPE[1:],
        ),
        policy=_REGISTRY_READ,
        handler=LazyBinding.available(DeferredTarget("._modelo_discovery_cli", "casilla", __package__)),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            DeferredTarget("._modelo_payloads", "ModeloCasillaResult", __package__),
            identity="modelo.casilla",
        ),
    ),
    CommandSpec(
        key="app_modelo_requires",
        parent_key="app_modelo",
        token="requires",
        kind=CommandNodeKind.LEAF,
        help_key=TranslationKey("cli.app.modelo.requires.help"),
        short_help_key=None,
        invocation=InvocationSpec(context_parameter="ctx"),
        parameters=(
            ArgumentSpec(
                name="modelo",
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.requires.modelo_help"),
            ),
            OptionSpec(
                name="year",
                declarations=("--year",),
                value=ValueContract(DeferredTarget("builtins", "int")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.list.year_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
            OptionSpec(
                name="period",
                declarations=("--period",),
                value=ValueContract(DeferredTarget("builtins", "str")),
                default=ParameterDefault.required(),
                help_key=TranslationKey("cli.app.modelo.requires.period_help"),
                multiple=False,
                is_flag=False,
                flag_value=None,
                constraint=ParameterConstraint(),
            ),
        ),
        policy=_REGISTRY_MODEL_READ,
        handler=LazyBinding.available(DeferredTarget("._modelo_discovery_cli", "requires", __package__)),
        result_schema=ResultSchemaSpec(
            SchemaState.TARGET,
            DeferredTarget("._modelo_payloads", "ModeloRequiresResult", __package__),
            identity="modelo.requires",
        ),
    ),
)

__all__ = ["MODELO_NONWORK_DISCOVERY_COMMAND_SPECS"]
