"""Frozen IVA and lifecycle metadata parameters shared by invoice commands."""

from __future__ import annotations

from typing import Final

from .command_spec import (
    DeferredTarget,
    OptionSpec,
    ParameterConstraint,
    ParameterDefault,
    TranslationKey,
    ValueContract,
)

OPTIONAL_IVA_CATEGORY_OPTION: Final[OptionSpec] = OptionSpec(
    name="iva_category",
    declarations=("--iva-category",),
    value=ValueContract(DeferredTarget("cadrumo.domain.iva.schema", "IvaCategory")),
    default=ParameterDefault.value(None),
    help_key=TranslationKey("cli.app.ledger.invoice.iva_category_help"),
    metavar=None,
    is_flag=False,
    flag_value=None,
    multiple=False,
    count=False,
    eager=False,
    constraint=ParameterConstraint(),
    show_default=True,
    hidden=False,
)

INVOICE_LIFECYCLE_METADATA_OPTIONS: Final[tuple[OptionSpec, ...]] = (
    OptionSpec(
        name="operation_type",
        declarations=("--operation-type",),
        value=ValueContract(DeferredTarget("cadrumo.core.aggregation", "IntracomOperationType")),
        default=ParameterDefault.value(None),
        help_key=TranslationKey("cli.app.ledger.invoice.operation_type_help"),
        metavar=None,
        is_flag=False,
        flag_value=None,
        multiple=False,
        count=False,
        eager=False,
        constraint=ParameterConstraint(),
        show_default=True,
        hidden=False,
    ),
    OptionSpec(
        name="operation_date",
        declarations=("--operation-date",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.value(None),
        help_key=TranslationKey("cli.app.ledger.invoice.operation_date_help"),
        metavar=None,
        is_flag=False,
        flag_value=None,
        multiple=False,
        count=False,
        eager=False,
        constraint=ParameterConstraint(),
        show_default=True,
        hidden=False,
    ),
    OptionSpec(
        name="retention_rate",
        declarations=("--retention-rate",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.value(None),
        help_key=TranslationKey("cli.app.ledger.invoice.retention_rate_help"),
        metavar=None,
        is_flag=False,
        flag_value=None,
        multiple=False,
        count=False,
        eager=False,
        constraint=ParameterConstraint(),
        show_default=True,
        hidden=False,
    ),
    OptionSpec(
        name="retention_amount",
        declarations=("--retention-amount",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.value(None),
        help_key=TranslationKey("cli.app.ledger.invoice.retention_amount_help"),
        metavar=None,
        is_flag=False,
        flag_value=None,
        multiple=False,
        count=False,
        eager=False,
        constraint=ParameterConstraint(),
        show_default=True,
        hidden=False,
    ),
    OptionSpec(
        name="invoice_class",
        declarations=("--invoice-class",),
        value=ValueContract(DeferredTarget("cadrumo.domain.invoices.enums", "InvoiceClass")),
        default=ParameterDefault.value(None),
        help_key=TranslationKey("cli.app.ledger.invoice.invoice_class_help"),
        metavar=None,
        is_flag=False,
        flag_value=None,
        multiple=False,
        count=False,
        eager=False,
        constraint=ParameterConstraint(),
        show_default=True,
        hidden=False,
    ),
    OptionSpec(
        name="series",
        declarations=("--series",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.value(None),
        help_key=TranslationKey("cli.app.ledger.invoice.series_help"),
        metavar=None,
        is_flag=False,
        flag_value=None,
        multiple=False,
        count=False,
        eager=False,
        constraint=ParameterConstraint(),
        show_default=True,
        hidden=False,
    ),
    OptionSpec(
        name="rectifies_invoice_number",
        declarations=("--rectifies-invoice-number",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.value(None),
        help_key=TranslationKey("cli.app.ledger.invoice.rectifies_help"),
        metavar=None,
        is_flag=False,
        flag_value=None,
        multiple=False,
        count=False,
        eager=False,
        constraint=ParameterConstraint(),
        show_default=True,
        hidden=False,
    ),
)

__all__ = ["INVOICE_LIFECYCLE_METADATA_OPTIONS", "OPTIONAL_IVA_CATEGORY_OPTION"]
