"""Frozen IVA and lifecycle metadata parameters shared by invoice commands."""

from __future__ import annotations

from typing import Final

from .command_spec import (
    DeferredTarget,
    OptionSpec,
    ParameterConstraint,
    ParameterDefault,
    TranslationKey,
    ValueContract,
)

OPTIONAL_IVA_CATEGORY_OPTION: Final[OptionSpec] = OptionSpec(
    name="iva_category",
    declarations=("--iva-category",),
    value=ValueContract(DeferredTarget("cadrumo.domain.iva.schema", "IvaCategory")),
    default=ParameterDefault.value(None),
    help_key=TranslationKey("cli.app.ledger.invoice.iva_category_help"),
    metavar=None,
    is_flag=False,
    flag_value=None,
    multiple=False,
    count=False,
    eager=False,
    constraint=ParameterConstraint(),
    show_default=True,
    hidden=False,
)

INVOICE_LIFECYCLE_METADATA_OPTIONS: Final[tuple[OptionSpec, ...]] = (
    OptionSpec(
        name="operation_type",
        declarations=("--operation-type",),
        value=ValueContract(DeferredTarget("cadrumo.core.aggregation", "IntracomOperationType")),
        default=ParameterDefault.value(None),
        help_key=TranslationKey("cli.app.ledger.invoice.operation_type_help"),
        metavar=None,
        is_flag=False,
        flag_value=None,
        multiple=False,
        count=False,
        eager=False,
        constraint=ParameterConstraint(),
        show_default=True,
        hidden=False,
    ),
    OptionSpec(
        name="operation_date",
        declarations=("--operation-date",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.value(None),
        help_key=TranslationKey("cli.app.ledger.invoice.operation_date_help"),
        metavar=None,
        is_flag=False,
        flag_value=None,
        multiple=False,
        count=False,
        eager=False,
        constraint=ParameterConstraint(),
        show_default=True,
        hidden=False,
    ),
    OptionSpec(
        name="retention_rate",
        declarations=("--retention-rate",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.value(None),
        help_key=TranslationKey("cli.app.ledger.invoice.retention_rate_help"),
        metavar=None,
        is_flag=False,
        flag_value=None,
        multiple=False,
        count=False,
        eager=False,
        constraint=ParameterConstraint(),
        show_default=True,
        hidden=False,
    ),
    OptionSpec(
        name="retention_amount",
        declarations=("--retention-amount",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.value(None),
        help_key=TranslationKey("cli.app.ledger.invoice.retention_amount_help"),
        metavar=None,
        is_flag=False,
        flag_value=None,
        multiple=False,
        count=False,
        eager=False,
        constraint=ParameterConstraint(),
        show_default=True,
        hidden=False,
    ),
    OptionSpec(
        name="invoice_class",
        declarations=("--invoice-class",),
        value=ValueContract(DeferredTarget("cadrumo.domain.invoices.enums", "InvoiceClass")),
        default=ParameterDefault.value(None),
        help_key=TranslationKey("cli.app.ledger.invoice.invoice_class_help"),
        metavar=None,
        is_flag=False,
        flag_value=None,
        multiple=False,
        count=False,
        eager=False,
        constraint=ParameterConstraint(),
        show_default=True,
        hidden=False,
    ),
    OptionSpec(
        name="series",
        declarations=("--series",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.value(None),
        help_key=TranslationKey("cli.app.ledger.invoice.series_help"),
        metavar=None,
        is_flag=False,
        flag_value=None,
        multiple=False,
        count=False,
        eager=False,
        constraint=ParameterConstraint(),
        show_default=True,
        hidden=False,
    ),
    OptionSpec(
        name="rectifies_invoice_number",
        declarations=("--rectifies-invoice-number",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.value(None),
        help_key=TranslationKey("cli.app.ledger.invoice.rectifies_help"),
        metavar=None,
        is_flag=False,
        flag_value=None,
        multiple=False,
        count=False,
        eager=False,
        constraint=ParameterConstraint(),
        show_default=True,
        hidden=False,
    ),
)

INVOICE_INTAKE_WIZARD_CORE_OPTIONS: Final[tuple[OptionSpec, ...]] = (
    OptionSpec(
        name="kind",
        declarations=("--kind",),
        value=ValueContract(DeferredTarget("cadrumo.domain.iva.classification", "InvoiceKind")),
        default=ParameterDefault.required(),
        help_key=TranslationKey("cli.app.ledger.invoice.kind_help"),
    ),
    OptionSpec(
        name="counterparty_name",
        declarations=("--counterparty-name",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.required(),
        help_key=None,
    ),
    OptionSpec(
        name="invoice_number",
        declarations=("--invoice-number",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.required(),
        help_key=None,
    ),
    OptionSpec(
        name="invoice_date",
        declarations=("--invoice-date",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.required(),
        help_key=TranslationKey("cli.app.ledger.evidence.invoice_date_help"),
    ),
    OptionSpec(
        name="taxable_base",
        declarations=("--taxable-base",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.required(),
        help_key=None,
    ),
    OptionSpec(
        name="country_code",
        declarations=("--country-code",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.required(),
        help_key=TranslationKey("cli.app.ledger.invoice.country_code_help"),
    ),
    OptionSpec(
        name="iva_rate",
        declarations=("--iva-rate",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.value(None),
        help_key=None,
    ),
    OptionSpec(
        name="currency",
        declarations=("--currency",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.value("EUR"),
        help_key=None,
    ),
)

INVOICE_INTAKE_WIZARD_TRAILING_OPTIONS: Final[tuple[OptionSpec, ...]] = (
    OptionSpec(
        name="recargo",
        declarations=("--recargo",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.value(None),
        help_key=TranslationKey("cli.app.ledger.invoice.recargo_help"),
    ),
    OptionSpec(
        name="notes",
        declarations=("--notes",),
        value=ValueContract(DeferredTarget("builtins", "str")),
        default=ParameterDefault.value(""),
        help_key=None,
    ),
)

__all__ = [
    "INVOICE_INTAKE_WIZARD_CORE_OPTIONS",
    "INVOICE_INTAKE_WIZARD_TRAILING_OPTIONS",
    "INVOICE_LIFECYCLE_METADATA_OPTIONS",
    "OPTIONAL_IVA_CATEGORY_OPTION",
]
