"""DR spec → Python module generator (EPIC #305).

Given an :class:`IngestedSpec` from the JSON ingestion pipeline,
emit a Python source module that declares the per-modelo envelope
as Python constants. The generated module is committed to git
alongside a "generated from" header that pins the provenance
(Orden / BOE-ID / xlsx / retrieval date) so the audit trail is
self-contained.

## Round-trip contract

::

    DR*.xlsx (agent download)
      → JSON fixture (tests/fixtures/dr_specs/*.json, committed)
      → IngestedSpec (parsed via _ingest)
      → Python module (generated via _generate, committed)

The generated Python module is byte-identical to what a human
would hand-author but without the transcription errors that hit
.

## Regeneration discipline

AEAT publishes DR*.xlsx updates annually. The regeneration flow:

1. Agent downloads DR303eNN.xlsx, emits new JSON.
2. Human reviews JSON diff vs prior year's JSON.
3. ``python -m aeat.adapters.outbound.aeat.export._formats._generate <json> <out.py>``
   regenerates the module.
4. ``pytest`` guards the shape + round-trip + golden fixture.

Step 2 is the critical review gate — JSON diffs are human-readable.
"""

from __future__ import annotations

from datetime import date
from textwrap import dedent

from ._ingest import IngestedSpec, ingest_dr_spec_path
from ._record_spec import (
    FieldKind,
    Justification,
    RecordFieldSpec,
    SegmentSpec,
    SignedMode,
)


def _field_to_source(field: RecordFieldSpec) -> str:
    """Render one :class:`RecordFieldSpec` as a ``record_field(...)`` call."""
    parts: list[str] = [
        f"offset={field.offset}",
        f"length={field.length}",
        f"field_id={field.field_id!r}",
    ]
    if field.casilla_id is not None:
        parts.append(f"casilla_id={field.casilla_id!r}")
    parts.append(f"kind=FieldKind.{field.kind.name}")
    if field.kind is FieldKind.RESERVED and field.literal_value is not None:
        parts.append(f"literal_value={field.literal_value!r}")
    if field.signed_mode is SignedMode.INLINE_SIGN:
        parts.append("signed_mode=SignedMode.INLINE_SIGN")
    if field.date_fmt is not None:
        parts.append(f"date_fmt=DateFmt.{field.date_fmt.name}")
    # Only emit non-default justification/pad_char so the source
    # reads cleanly — the factory applies kind-aware defaults.
    expected_justification = (
        Justification.RIGHT if field.kind in {FieldKind.NUMERIC, FieldKind.CURRENCY} else Justification.LEFT
    )
    if field.justification is not expected_justification:
        parts.append(f"justification=Justification.{field.justification.name}")
    expected_pad = "0" if field.kind in {FieldKind.NUMERIC, FieldKind.CURRENCY} else " "
    if field.pad_char != expected_pad:
        parts.append(f"pad_char={field.pad_char!r}")
    return "record_field(" + ", ".join(parts) + ")"


def _segment_to_source(segment: SegmentSpec, *, var_name: str) -> str:
    """Render one :class:`SegmentSpec` as a Python constant assignment."""
    lines = [
        f"{var_name} = SegmentSpec(",
        f"    segment_id={segment.segment_id!r},",
        "    specs=(",
    ]
    for field in segment.specs:
        lines.append(f"        {_field_to_source(field)},")
    lines.append("    ),")
    lines.append(f"    total_length={segment.total_length},")
    lines.append(")")
    return "\n".join(lines)


def generate_module_source(
    ingested: IngestedSpec,
    *,
    module_identifier: str,
    generator_iso_date: str | None = None,
) -> str:
    """Render a full Python module source from an :class:`IngestedSpec`.

    Args:
        ingested: parsed spec document (see :mod:`_ingest`).
        module_identifier: human-readable identifier for the generated
            module (e.g., ``"Modelo 303 ejercicio 2024"``). Inserted
            into the module docstring and ``__all__`` block.
        generator_iso_date: ISO-format date stamp to embed in the
            provenance header. Defaults to today (UTC).

    Returns:
        Fully-formed Python source ready to write to ``.py``.
    """
    source = ingested["source"]
    stamp = generator_iso_date or date.today().isoformat()

    provenance_lines: list[str] = [
        f"Generated by aeat.adapters.outbound.aeat.export._formats._generate on {stamp}.",
        "",
        "DO NOT hand-edit. To regenerate after an AEAT DR update:",
        "",
        "    python -m aeat.adapters.outbound.aeat.export._formats._generate <json> <out.py>",
        "",
        "Provenance (from the JSON spec fixture's ``source`` block):",
    ]
    for key, value in source.items():
        provenance_lines.append(f"- {key}: {value}")

    docstring_body = "\n".join(provenance_lines)
    indent = "    "
    docstring_body_indented = "\n".join(indent + ln if ln else "" for ln in docstring_body.splitlines())

    segment_decls: list[str] = []
    envelope_refs: list[str] = []
    for idx, segment in enumerate(ingested["segments"]):
        var = f"_SEGMENT_{idx}_{segment.segment_id}"
        segment_decls.append(_segment_to_source(segment, var_name=var))
        envelope_refs.append(var)

    required_field_ids = _collect_required_field_ids(ingested)

    body = dedent(
        """\
        # ruff: noqa: E501
        \"\"\"{identifier}.

        {docstring}
        \"\"\"

        from __future__ import annotations

        from ._record_spec import (
            DateFmt,
            FicheroBoeEncoding,
            FieldKind,
            Justification,
            SegmentSpec,
            SignedMode,
            record_field,
            validate_segment_specs,
        )

        ENCODING: FicheroBoeEncoding = {encoding!r}

        REQUIRED_HEADER_FIELDS: frozenset[str] = frozenset({required!r})

        {segments}

        ENVELOPE: tuple[SegmentSpec, ...] = (
        {envelope_entries}
        )

        validate_segment_specs(ENVELOPE)


        __all__ = ["ENCODING", "ENVELOPE", "REQUIRED_HEADER_FIELDS"]
        """
    ).format(
        identifier=module_identifier,
        docstring=docstring_body_indented.lstrip(),
        encoding=ingested["encoding"],
        required=sorted(required_field_ids),
        segments="\n\n".join(segment_decls),
        envelope_entries="\n".join(f"    {name}," for name in envelope_refs),
    )
    return body


def _collect_required_field_ids(ingested: IngestedSpec) -> frozenset[str]:
    """Heuristic: treat header-level ALPHANUMERIC/NUMERIC fields that
    are neither RESERVED nor DATE as required header inputs.

    The spec's ``source.extra_required_fields`` list is unioned in
    to capture per-modelo header fields that live outside segment 0
    (e.g., Modelo 303's DP30301 page-identification fields like
    TIPO_DECLARACION, NIF, APELLIDOS_Y_NOMBRE, DEVENGO_PERIODO).
    """
    required: set[str] = set()
    # Interpret the first segment as the envelope header + mark its
    # user-supplied fields as required. Later segments tend to be
    # per-page data payloads where missing fields are legitimately
    # optional.
    for segment in ingested["segments"][:1]:
        for field in segment.specs:
            if (
                field.kind in {FieldKind.ALPHANUMERIC, FieldKind.NUMERIC}
                and field.literal_value is None
                and field.casilla_id is None
            ):
                required.add(field.field_id)
    # Explicit overrides declared in the fixture's source block.
    extras = ingested["source"].get("extra_required_fields") if "extra_required_fields" in ingested["source"] else None  # type: ignore[misc]
    if extras:
        for fid in extras:
            required.add(str(fid))
    return frozenset(required)


def _main() -> None:
    """CLI: ``python -m aeat.adapters.outbound.aeat.export._formats._generate <json> <out.py>``."""
    import argparse
    from pathlib import Path

    parser = argparse.ArgumentParser(
        description="Generate a fichero-BOE schema module from a DR JSON fixture.",
    )
    parser.add_argument("json_path", type=Path, help="Path to the DR JSON fixture.")
    parser.add_argument("out_path", type=Path, help="Path for the generated .py module.")
    parser.add_argument(
        "--identifier",
        default=None,
        help="Human-readable identifier (defaults to the xlsx filename).",
    )
    args = parser.parse_args()

    ingested = ingest_dr_spec_path(args.json_path)
    identifier = args.identifier or ingested["source"].get("xlsx", args.json_path.stem)
    source = generate_module_source(ingested, module_identifier=identifier)
    args.out_path.write_text(source, encoding="utf-8")


__all__ = ["generate_module_source"]


if __name__ == "__main__":  # pragma: no cover — CLI entrypoint
    _main()
