"""Define the fichero-BOE envelope spec for Modelo 303 ejercicio 2024.

Generated by :mod:`aeat.adapters.outbound.aeat.export._formats._generate`. Do
not hand-edit. To regenerate after an AEAT DR update::

    python -m aeat.adapters.outbound.aeat.export._formats._generate <json> <out.py>

Provenance:
    - modelo: 303
    - ejercicio: 2024
    - orden: Orden HAC/819/2024
    - boe_id: BOE-A-2024-16129
    - xlsx: DR303e24.xlsx
    - extra_required_fields: ``DP30301_F006_TIPO_DECLARACI_N``,
      ``DP30301_F007_IDENTIFICACI_N_NIF``,
      ``DP30301_F008_IDENTIFICACI_N_APELLIDOS_Y_N``,
      ``DP30301_F009_DEVENGO_EJERCICIO``,
      ``DP30301_F010_DEVENGO_PER_ODO``.

Envelope shape:
    Full 8-segment envelope: ``DP30300`` header (328 B fixed) plus
    ``DP30301`` through ``DP30305`` fixed pages plus ``DP303DID`` (823 B
    SEPA devolución) plus ``DP30300_TRAILER`` (18 B close). Total envelope
    is 7994 bytes plus CRLF. Auto-extracted from ``DR303e24.xlsx``;
    casilla_id / field_id duplicates within a segment are disambiguated via
    ``_N`` suffix. All 17-byte casilla-bearing NUMERIC fields are classified
    as CURRENCY (40 reclassifications) and ``DP30301_F010_DEVENGO_PER_ODO``
    is ALPHANUMERIC user-supplied rather than a RESERVED literal.

Known registry-vs-schema gap:
    Casillas 45, 64, 67, and 71 require registry-backed review before this
    fixture can become filing-grade. They currently have no corresponding
    ``RecordFieldSpec`` in this fixture. The
    ``_2``-suffix duplicates ``DP30303_CAS66_2`` at offset 323,
    ``DP30303_CAS110_2`` at offset 289, and ``DP30304_CAS80_2`` at offset
    370 are suspected mislabelings from the ``DR303e24.xlsx`` extraction —
    they occupy the 17-byte CURRENCY slots where the missing casillas
    belong. Resolving the gap requires cross-referencing the AEAT DR303
    PDF column headers and registry export definitions.

Rate-row layouts:
    Régimen general at 4 %, 5 %, 10 %, and 21 %, plus recargo equivalencia
    at 1.75 %, 1.40 %, and 5.20 %. Layouts are pinned by
    ``test_dp30301_rate_rows_layout.py`` and ``test_dp30301_recargo_layout.py``.
    Casilla 17 is observed with the 5-byte RESERVED literal ``"00000"`` at
    ``DP30301`` offset 483 — a zero-percent rate in a column position,
    likely an xlsx-extraction artefact where the intended field was not a
    rate literal. The observed state is preserved so any change to this
    slot fails loud; resolving requires DR303 PDF cross-reference.
"""

from __future__ import annotations

from ._record_spec import (
    FicheroBoeEncoding,
    FieldKind,
    SegmentSpec,
    SignedMode,
    record_field,
    validate_segment_specs,
)

ENCODING: FicheroBoeEncoding = "iso-8859-1"

REQUIRED_HEADER_FIELDS: frozenset[str] = frozenset(
    [
        "DP30300_F004_EJERCICIO_DE_DEVENGO",
        "DP30300_F008_RESERVADO_PARA_LA_ADMINISTRA",
        "DP30300_F009_VERSI_N_DEL_PROGRAMA",
        "DP30300_F010_RESERVADO_PARA_LA_ADMINISTRA",
        "DP30300_F011_NIF_EMPRESA_DESARROLLO",
        "DP30300_F012_RESERVADO_PARA_LA_ADMINISTRA",
        "DP30301_F006_TIPO_DECLARACI_N",
        "DP30301_F007_IDENTIFICACI_N_NIF",
        "DP30301_F008_IDENTIFICACI_N_APELLIDOS_Y_N",
        "DP30301_F009_DEVENGO_EJERCICIO",
        "DP30301_F010_DEVENGO_PER_ODO",
    ]
)

_SEGMENT_0_DP30300 = SegmentSpec(
    segment_id="DP30300",
    specs=(
        record_field(
            offset=1, length=2, field_id="DP30300_F001_CONSTANTE", kind=FieldKind.RESERVED, literal_value="<T"
        ),
        record_field(offset=3, length=3, field_id="DP30300_F002_MODELO", kind=FieldKind.RESERVED, literal_value="303"),
        record_field(
            offset=6, length=1, field_id="DP30300_F003_DISCRIMINANTE", kind=FieldKind.RESERVED, literal_value="0"
        ),
        record_field(offset=7, length=4, field_id="DP30300_F004_EJERCICIO_DE_DEVENGO", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=11, length=2, field_id="DP30300_F005_PER_ODO", kind=FieldKind.RESERVED, literal_value="01"),
        record_field(
            offset=13, length=5, field_id="DP30300_F006_TIPO_Y_CIERRE", kind=FieldKind.RESERVED, literal_value="0000>"
        ),
        record_field(
            offset=18, length=5, field_id="DP30300_F007_CONSTANTE", kind=FieldKind.RESERVED, literal_value="<AUX>"
        ),
        record_field(
            offset=23, length=70, field_id="DP30300_F008_RESERVADO_PARA_LA_ADMINISTRA", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(offset=93, length=4, field_id="DP30300_F009_VERSI_N_DEL_PROGRAMA", kind=FieldKind.ALPHANUMERIC),
        record_field(
            offset=97, length=4, field_id="DP30300_F010_RESERVADO_PARA_LA_ADMINISTRA", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(offset=101, length=9, field_id="DP30300_F011_NIF_EMPRESA_DESARROLLO", kind=FieldKind.ALPHANUMERIC),
        record_field(
            offset=110, length=213, field_id="DP30300_F012_RESERVADO_PARA_LA_ADMINISTRA", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=323, length=6, field_id="DP30300_F013_CONSTANTE", kind=FieldKind.RESERVED, literal_value="</AUX>"
        ),
    ),
    total_length=328,
)

_SEGMENT_1_DP30301 = SegmentSpec(
    segment_id="DP30301",
    specs=(
        record_field(
            offset=1,
            length=2,
            field_id="DP30301_F001_INICIO_DEL_IDENTIFICADOR_DE",
            kind=FieldKind.RESERVED,
            literal_value="<T",
        ),
        record_field(offset=3, length=3, field_id="DP30301_F002_MODELO", kind=FieldKind.RESERVED, literal_value="303"),
        record_field(
            offset=6, length=5, field_id="DP30301_F003_P_GINA", kind=FieldKind.RESERVED, literal_value="01000"
        ),
        record_field(
            offset=11,
            length=1,
            field_id="DP30301_F004_FIN_DE_IDENTIFICADOR_DE_MODE",
            kind=FieldKind.RESERVED,
            literal_value=">",
        ),
        record_field(
            offset=12, length=1, field_id="DP30301_F005_INDICADOR_DE_P_GINA_COMPLEME", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(offset=13, length=1, field_id="DP30301_F006_TIPO_DECLARACI_N", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=14, length=9, field_id="DP30301_F007_IDENTIFICACI_N_NIF", kind=FieldKind.ALPHANUMERIC),
        record_field(
            offset=23, length=80, field_id="DP30301_F008_IDENTIFICACI_N_APELLIDOS_Y_N", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(offset=103, length=4, field_id="DP30301_F009_DEVENGO_EJERCICIO", kind=FieldKind.NUMERIC),
        record_field(offset=107, length=2, field_id="DP30301_F010_DEVENGO_PER_ODO", kind=FieldKind.ALPHANUMERIC),
        record_field(
            offset=109, length=1, field_id="DP30301_F011_IDENTIFICACI_N_TRIBUTACI_N_E", kind=FieldKind.NUMERIC
        ),
        record_field(
            offset=110, length=1, field_id="DP30301_F012_IDENTIFICACI_N_SUJETO_PASIVO", kind=FieldKind.NUMERIC
        ),
        record_field(
            offset=111, length=1, field_id="DP30301_F013_IDENTIFICACI_N_SUJETO_PASIVO", kind=FieldKind.NUMERIC
        ),
        record_field(
            offset=112, length=1, field_id="DP30301_F014_IDENTIFICACI_N_AUTOLIQUIDACI", kind=FieldKind.NUMERIC
        ),
        record_field(
            offset=113, length=1, field_id="DP30301_F015_IDENTIFICACI_N_SUJETO_PASIVO", kind=FieldKind.NUMERIC
        ),
        record_field(
            offset=114, length=1, field_id="DP30301_F016_IDENTIFICACI_N_SUJETO_PASIVO", kind=FieldKind.NUMERIC
        ),
        record_field(
            offset=115, length=1, field_id="DP30301_F017_IDENTIFICACI_N_OPCI_N_POR_LA", kind=FieldKind.NUMERIC
        ),
        record_field(
            offset=116, length=1, field_id="DP30301_F018_IDENTIFICACI_N_REVOCACI_N_DE", kind=FieldKind.NUMERIC
        ),
        record_field(
            offset=117, length=1, field_id="DP30301_F019_IDENTIFICACI_N_SUJETO_PASIVO", kind=FieldKind.NUMERIC
        ),
        record_field(
            offset=118, length=8, field_id="DP30301_F020_IDENTIFICACI_N_FECHA_EN_QUE", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=126, length=1, field_id="DP30301_F021_IDENTIFICACI_N_TIPO_DE_AUTOL", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=127, length=1, field_id="DP30301_F022_IDENTIFICACI_N_SUJETO_PASIVO", kind=FieldKind.NUMERIC
        ),
        record_field(
            offset=128, length=1, field_id="DP30301_F023_IDENTIFICACI_N_SUJETO_PASIVO", kind=FieldKind.NUMERIC
        ),
        record_field(
            offset=129, length=1, field_id="DP30301_F024_IDENTIFICACI_N_SUJETO_PASIVO", kind=FieldKind.NUMERIC
        ),
        record_field(offset=130, length=17, field_id="DP30301_CAS150", casilla_id="150", kind=FieldKind.CURRENCY),
        record_field(
            offset=147,
            length=5,
            field_id="DP30301_CAS151",
            casilla_id="151",
            kind=FieldKind.RESERVED,
            literal_value="00000",
        ),
        record_field(offset=152, length=17, field_id="DP30301_CAS152", casilla_id="152", kind=FieldKind.CURRENCY),
        record_field(offset=169, length=17, field_id="DP30301_CAS01", casilla_id="01", kind=FieldKind.CURRENCY),
        record_field(
            offset=186,
            length=5,
            field_id="DP30301_CAS02",
            casilla_id="02",
            kind=FieldKind.RESERVED,
            literal_value="00400",
        ),
        record_field(offset=191, length=17, field_id="DP30301_CAS03", casilla_id="03", kind=FieldKind.CURRENCY),
        record_field(offset=208, length=17, field_id="DP30301_CAS153", casilla_id="153", kind=FieldKind.CURRENCY),
        record_field(
            offset=225,
            length=5,
            field_id="DP30301_CAS154",
            casilla_id="154",
            kind=FieldKind.RESERVED,
            literal_value="00500",
        ),
        record_field(offset=230, length=17, field_id="DP30301_CAS155", casilla_id="155", kind=FieldKind.CURRENCY),
        record_field(offset=247, length=17, field_id="DP30301_CAS04", casilla_id="04", kind=FieldKind.CURRENCY),
        record_field(
            offset=264,
            length=5,
            field_id="DP30301_CAS05",
            casilla_id="05",
            kind=FieldKind.RESERVED,
            literal_value="01000",
        ),
        record_field(offset=269, length=17, field_id="DP30301_CAS06", casilla_id="06", kind=FieldKind.CURRENCY),
        record_field(offset=286, length=17, field_id="DP30301_CAS07", casilla_id="07", kind=FieldKind.CURRENCY),
        record_field(
            offset=303,
            length=5,
            field_id="DP30301_CAS08",
            casilla_id="08",
            kind=FieldKind.RESERVED,
            literal_value="02100",
        ),
        record_field(offset=308, length=17, field_id="DP30301_CAS09", casilla_id="09", kind=FieldKind.CURRENCY),
        record_field(offset=325, length=17, field_id="DP30301_CAS10", casilla_id="10", kind=FieldKind.CURRENCY),
        record_field(offset=342, length=17, field_id="DP30301_CAS11", casilla_id="11", kind=FieldKind.CURRENCY),
        record_field(offset=359, length=17, field_id="DP30301_CAS12", casilla_id="12", kind=FieldKind.CURRENCY),
        record_field(offset=376, length=17, field_id="DP30301_CAS13", casilla_id="13", kind=FieldKind.CURRENCY),
        record_field(
            offset=393,
            length=17,
            field_id="DP30301_CAS14",
            casilla_id="14",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=410,
            length=17,
            field_id="DP30301_CAS15",
            casilla_id="15",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(offset=427, length=17, field_id="DP30301_CAS156", casilla_id="156", kind=FieldKind.CURRENCY),
        record_field(
            offset=444,
            length=5,
            field_id="DP30301_CAS157",
            casilla_id="157",
            kind=FieldKind.RESERVED,
            literal_value="00175",
        ),
        record_field(offset=449, length=17, field_id="DP30301_CAS158", casilla_id="158", kind=FieldKind.CURRENCY),
        record_field(offset=466, length=17, field_id="DP30301_CAS16", casilla_id="16", kind=FieldKind.CURRENCY),
        record_field(
            offset=483,
            length=5,
            field_id="DP30301_CAS17",
            casilla_id="17",
            kind=FieldKind.RESERVED,
            literal_value="00000",
        ),
        record_field(offset=488, length=17, field_id="DP30301_CAS18", casilla_id="18", kind=FieldKind.CURRENCY),
        record_field(offset=505, length=17, field_id="DP30301_CAS19", casilla_id="19", kind=FieldKind.CURRENCY),
        record_field(
            offset=522,
            length=5,
            field_id="DP30301_CAS20",
            casilla_id="20",
            kind=FieldKind.RESERVED,
            literal_value="00140",
        ),
        record_field(offset=527, length=17, field_id="DP30301_CAS21", casilla_id="21", kind=FieldKind.CURRENCY),
        record_field(offset=544, length=17, field_id="DP30301_CAS22", casilla_id="22", kind=FieldKind.CURRENCY),
        record_field(
            offset=561,
            length=5,
            field_id="DP30301_CAS23",
            casilla_id="23",
            kind=FieldKind.RESERVED,
            literal_value="00520",
        ),
        record_field(offset=566, length=17, field_id="DP30301_CAS24", casilla_id="24", kind=FieldKind.CURRENCY),
        record_field(
            offset=583,
            length=17,
            field_id="DP30301_CAS25",
            casilla_id="25",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=600,
            length=17,
            field_id="DP30301_CAS26",
            casilla_id="26",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=617,
            length=17,
            field_id="DP30301_CAS152_2",
            casilla_id="152_2",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(offset=634, length=17, field_id="DP30301_CAS28", casilla_id="28", kind=FieldKind.CURRENCY),
        record_field(offset=651, length=17, field_id="DP30301_CAS29", casilla_id="29", kind=FieldKind.CURRENCY),
        record_field(offset=668, length=17, field_id="DP30301_CAS30", casilla_id="30", kind=FieldKind.CURRENCY),
        record_field(offset=685, length=17, field_id="DP30301_CAS31", casilla_id="31", kind=FieldKind.CURRENCY),
        record_field(offset=702, length=17, field_id="DP30301_CAS32", casilla_id="32", kind=FieldKind.CURRENCY),
        record_field(offset=719, length=17, field_id="DP30301_CAS33", casilla_id="33", kind=FieldKind.CURRENCY),
        record_field(offset=736, length=17, field_id="DP30301_CAS34", casilla_id="34", kind=FieldKind.CURRENCY),
        record_field(offset=753, length=17, field_id="DP30301_CAS35", casilla_id="35", kind=FieldKind.CURRENCY),
        record_field(offset=770, length=17, field_id="DP30301_CAS36", casilla_id="36", kind=FieldKind.CURRENCY),
        record_field(offset=787, length=17, field_id="DP30301_CAS37", casilla_id="37", kind=FieldKind.CURRENCY),
        record_field(offset=804, length=17, field_id="DP30301_CAS38", casilla_id="38", kind=FieldKind.CURRENCY),
        record_field(offset=821, length=17, field_id="DP30301_CAS39", casilla_id="39", kind=FieldKind.CURRENCY),
        record_field(
            offset=838,
            length=17,
            field_id="DP30301_CAS40",
            casilla_id="40",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=855,
            length=17,
            field_id="DP30301_CAS41",
            casilla_id="41",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=872,
            length=17,
            field_id="DP30301_CAS42",
            casilla_id="42",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=889,
            length=17,
            field_id="DP30301_CAS43",
            casilla_id="43",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=906,
            length=17,
            field_id="DP30301_CAS44",
            casilla_id="44",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=923,
            length=17,
            field_id="DP30301_CAS29_2",
            casilla_id="29_2",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=940,
            length=17,
            field_id="DP30301_CAS27",
            casilla_id="27",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=957, length=600, field_id="DP30301_F080_RESERVADO_PARA_LA_AEAT", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=1557, length=13, field_id="DP30301_F081_RESERVADO_PARA_LA_AEAT_SELLO", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=1570,
            length=12,
            field_id="DP30301_F082_INDICADOR_DE_FIN_DE_REGISTRO",
            kind=FieldKind.RESERVED,
            literal_value="</T30301000>",
        ),
    ),
    total_length=1581,
)

_SEGMENT_2_DP30302 = SegmentSpec(
    segment_id="DP30302",
    specs=(
        record_field(offset=1, length=2, field_id="DP30302_F001", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=3, length=3, field_id="DP30302_F002", kind=FieldKind.NUMERIC),
        record_field(offset=6, length=5, field_id="DP30302_F003", kind=FieldKind.NUMERIC),
        record_field(offset=11, length=1, field_id="DP30302_F004", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=12, length=1, field_id="DP30302_F005_C", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=13, length=2, field_id="DP30302_F006_C", kind=FieldKind.NUMERIC),
        record_field(offset=15, length=17, field_id="DP30302_F007_C", kind=FieldKind.NUMERIC),
        record_field(offset=32, length=6, field_id="DP30302_F008_C", kind=FieldKind.NUMERIC),
        record_field(offset=38, length=17, field_id="DP30302_F009_C", kind=FieldKind.NUMERIC),
        record_field(offset=55, length=5, field_id="DP30302_F010_C", kind=FieldKind.NUMERIC),
        record_field(offset=60, length=17, field_id="DP30302_F011_C", kind=FieldKind.NUMERIC),
        record_field(offset=77, length=17, field_id="DP30302_F012_C", kind=FieldKind.NUMERIC),
        record_field(
            offset=94, length=17, field_id="DP30302_F013_C", kind=FieldKind.CURRENCY, signed_mode=SignedMode.INLINE_SIGN
        ),
        record_field(offset=111, length=2, field_id="DP30302_F014_C", kind=FieldKind.NUMERIC),
        record_field(offset=113, length=17, field_id="DP30302_F015_C", kind=FieldKind.NUMERIC),
        record_field(offset=130, length=6, field_id="DP30302_F016_C", kind=FieldKind.NUMERIC),
        record_field(offset=136, length=17, field_id="DP30302_F017_C", kind=FieldKind.NUMERIC),
        record_field(offset=153, length=5, field_id="DP30302_F018_C", kind=FieldKind.NUMERIC),
        record_field(offset=158, length=17, field_id="DP30302_F019_C", kind=FieldKind.NUMERIC),
        record_field(offset=175, length=17, field_id="DP30302_F020_C", kind=FieldKind.NUMERIC),
        record_field(
            offset=192,
            length=17,
            field_id="DP30302_F021_C",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(offset=209, length=4, field_id="DP30302_F022_C", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=213, length=1, field_id="DP30302_F023_C", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=214, length=10, field_id="DP30302_F024_C", kind=FieldKind.NUMERIC),
        record_field(offset=224, length=17, field_id="DP30302_F025_C", kind=FieldKind.NUMERIC),
        record_field(offset=241, length=10, field_id="DP30302_F026_C", kind=FieldKind.NUMERIC),
        record_field(offset=251, length=17, field_id="DP30302_F027_C", kind=FieldKind.NUMERIC),
        record_field(offset=268, length=10, field_id="DP30302_F028_C", kind=FieldKind.NUMERIC),
        record_field(offset=278, length=17, field_id="DP30302_F029_C", kind=FieldKind.NUMERIC),
        record_field(offset=295, length=10, field_id="DP30302_F030_C", kind=FieldKind.NUMERIC),
        record_field(offset=305, length=17, field_id="DP30302_F031_C", kind=FieldKind.NUMERIC),
        record_field(offset=322, length=10, field_id="DP30302_F032_C", kind=FieldKind.NUMERIC),
        record_field(offset=332, length=17, field_id="DP30302_F033_C", kind=FieldKind.NUMERIC),
        record_field(offset=349, length=10, field_id="DP30302_F034_C", kind=FieldKind.NUMERIC),
        record_field(offset=359, length=17, field_id="DP30302_F035_C", kind=FieldKind.NUMERIC),
        record_field(offset=376, length=10, field_id="DP30302_F036_C", kind=FieldKind.NUMERIC),
        record_field(offset=386, length=17, field_id="DP30302_F037_C", kind=FieldKind.NUMERIC),
        record_field(offset=403, length=17, field_id="DP30302_F038_C", kind=FieldKind.NUMERIC),
        record_field(offset=420, length=17, field_id="DP30302_F039_C", kind=FieldKind.NUMERIC),
        record_field(offset=437, length=3, field_id="DP30302_F040_C", kind=FieldKind.NUMERIC),
        record_field(offset=440, length=5, field_id="DP30302_F041_C", kind=FieldKind.NUMERIC),
        record_field(offset=445, length=17, field_id="DP30302_F042_C", kind=FieldKind.NUMERIC),
        record_field(offset=462, length=17, field_id="DP30302_F043_C", kind=FieldKind.NUMERIC),
        record_field(offset=479, length=3, field_id="DP30302_F044_C", kind=FieldKind.NUMERIC),
        record_field(
            offset=482,
            length=17,
            field_id="DP30302_F045_C",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(offset=499, length=5, field_id="DP30302_F046_C", kind=FieldKind.NUMERIC),
        record_field(offset=504, length=17, field_id="DP30302_F047_C", kind=FieldKind.NUMERIC),
        record_field(offset=521, length=17, field_id="DP30302_F048_C", kind=FieldKind.NUMERIC),
        record_field(offset=538, length=17, field_id="DP30302_F049_C", kind=FieldKind.NUMERIC),
        record_field(offset=555, length=4, field_id="DP30302_F050_C", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=559, length=1, field_id="DP30302_F051_C", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=560, length=10, field_id="DP30302_F052_C", kind=FieldKind.NUMERIC),
        record_field(offset=570, length=17, field_id="DP30302_F053_C", kind=FieldKind.NUMERIC),
        record_field(offset=587, length=10, field_id="DP30302_F054_C", kind=FieldKind.NUMERIC),
        record_field(offset=597, length=17, field_id="DP30302_F055_C", kind=FieldKind.NUMERIC),
        record_field(offset=614, length=10, field_id="DP30302_F056_C", kind=FieldKind.NUMERIC),
        record_field(offset=624, length=17, field_id="DP30302_F057_C", kind=FieldKind.NUMERIC),
        record_field(offset=641, length=10, field_id="DP30302_F058_C", kind=FieldKind.NUMERIC),
        record_field(offset=651, length=17, field_id="DP30302_F059_C", kind=FieldKind.NUMERIC),
        record_field(offset=668, length=10, field_id="DP30302_F060_C", kind=FieldKind.NUMERIC),
        record_field(offset=678, length=17, field_id="DP30302_F061_C", kind=FieldKind.NUMERIC),
        record_field(offset=695, length=10, field_id="DP30302_F062_C", kind=FieldKind.NUMERIC),
        record_field(offset=705, length=17, field_id="DP30302_F063_C", kind=FieldKind.NUMERIC),
        record_field(offset=722, length=10, field_id="DP30302_F064_C", kind=FieldKind.NUMERIC),
        record_field(offset=732, length=17, field_id="DP30302_F065_C", kind=FieldKind.NUMERIC),
        record_field(offset=749, length=17, field_id="DP30302_F066_C", kind=FieldKind.NUMERIC),
        record_field(offset=766, length=17, field_id="DP30302_F067_C", kind=FieldKind.NUMERIC),
        record_field(offset=783, length=3, field_id="DP30302_F068_C", kind=FieldKind.NUMERIC),
        record_field(offset=786, length=5, field_id="DP30302_F069_C", kind=FieldKind.NUMERIC),
        record_field(offset=791, length=17, field_id="DP30302_F070_C", kind=FieldKind.NUMERIC),
        record_field(offset=808, length=17, field_id="DP30302_F071_C", kind=FieldKind.NUMERIC),
        record_field(offset=825, length=3, field_id="DP30302_F072_C", kind=FieldKind.NUMERIC),
        record_field(
            offset=828,
            length=17,
            field_id="DP30302_F073_C",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(offset=845, length=5, field_id="DP30302_F074_C", kind=FieldKind.NUMERIC),
        record_field(offset=850, length=17, field_id="DP30302_F075_C", kind=FieldKind.NUMERIC),
        record_field(offset=867, length=17, field_id="DP30302_F076_C", kind=FieldKind.NUMERIC),
        record_field(offset=884, length=17, field_id="DP30302_F077_C", kind=FieldKind.NUMERIC),
        record_field(offset=901, length=17, field_id="DP30302_F078", kind=FieldKind.NUMERIC),
        record_field(
            offset=918, length=17, field_id="DP30302_F079", kind=FieldKind.CURRENCY, signed_mode=SignedMode.INLINE_SIGN
        ),
        record_field(offset=935, length=17, field_id="DP30302_F080", kind=FieldKind.NUMERIC),
        record_field(
            offset=952, length=17, field_id="DP30302_F081", kind=FieldKind.CURRENCY, signed_mode=SignedMode.INLINE_SIGN
        ),
        record_field(
            offset=969, length=17, field_id="DP30302_F082", kind=FieldKind.CURRENCY, signed_mode=SignedMode.INLINE_SIGN
        ),
        record_field(
            offset=986, length=17, field_id="DP30302_F083", kind=FieldKind.CURRENCY, signed_mode=SignedMode.INLINE_SIGN
        ),
        record_field(
            offset=1003, length=17, field_id="DP30302_F084", kind=FieldKind.CURRENCY, signed_mode=SignedMode.INLINE_SIGN
        ),
        record_field(
            offset=1020, length=17, field_id="DP30302_F085", kind=FieldKind.CURRENCY, signed_mode=SignedMode.INLINE_SIGN
        ),
        record_field(
            offset=1037, length=17, field_id="DP30302_F086", kind=FieldKind.CURRENCY, signed_mode=SignedMode.INLINE_SIGN
        ),
        record_field(
            offset=1054, length=17, field_id="DP30302_F087", kind=FieldKind.CURRENCY, signed_mode=SignedMode.INLINE_SIGN
        ),
        record_field(
            offset=1071, length=17, field_id="DP30302_F088", kind=FieldKind.CURRENCY, signed_mode=SignedMode.INLINE_SIGN
        ),
        record_field(
            offset=1088, length=17, field_id="DP30302_F089", kind=FieldKind.CURRENCY, signed_mode=SignedMode.INLINE_SIGN
        ),
        record_field(offset=1105, length=3, field_id="DP30302_F090_C", kind=FieldKind.NUMERIC),
        record_field(offset=1108, length=2, field_id="DP30302_F091_C", kind=FieldKind.NUMERIC),
        record_field(offset=1110, length=3, field_id="DP30302_F092_C", kind=FieldKind.NUMERIC),
        record_field(offset=1113, length=3, field_id="DP30302_F093_C", kind=FieldKind.NUMERIC),
        record_field(offset=1116, length=3, field_id="DP30302_F094_C", kind=FieldKind.NUMERIC),
        record_field(offset=1119, length=1, field_id="DP30302_F095_C", kind=FieldKind.NUMERIC),
        record_field(offset=1120, length=17, field_id="DP30302_F096_C", kind=FieldKind.NUMERIC),
        record_field(offset=1137, length=17, field_id="DP30302_F097_C", kind=FieldKind.NUMERIC),
        record_field(offset=1154, length=7, field_id="DP30302_F098_C", kind=FieldKind.NUMERIC),
        record_field(offset=1161, length=7, field_id="DP30302_F099_C", kind=FieldKind.NUMERIC),
        record_field(offset=1168, length=7, field_id="DP30302_F100_C", kind=FieldKind.NUMERIC),
        record_field(offset=1175, length=4, field_id="DP30302_F101_C", kind=FieldKind.NUMERIC),
        record_field(offset=1179, length=4, field_id="DP30302_F102_C", kind=FieldKind.NUMERIC),
        record_field(offset=1183, length=1, field_id="DP30302_F103_C", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=1184, length=4, field_id="DP30302_F104_C", kind=FieldKind.NUMERIC),
        record_field(offset=1188, length=7, field_id="DP30302_F105_C", kind=FieldKind.NUMERIC),
        record_field(offset=1195, length=2, field_id="DP30302_F106_C", kind=FieldKind.NUMERIC),
        record_field(offset=1197, length=4, field_id="DP30302_F107_C", kind=FieldKind.NUMERIC),
        record_field(offset=1201, length=3, field_id="DP30302_F108_C", kind=FieldKind.NUMERIC),
        record_field(offset=1204, length=2, field_id="DP30302_F109_C", kind=FieldKind.NUMERIC),
        record_field(offset=1206, length=4, field_id="DP30302_F110_C", kind=FieldKind.NUMERIC),
        record_field(offset=1210, length=3, field_id="DP30302_F111_C", kind=FieldKind.NUMERIC),
        record_field(offset=1213, length=2, field_id="DP30302_F112_C", kind=FieldKind.NUMERIC),
        record_field(offset=1215, length=4, field_id="DP30302_F113_C", kind=FieldKind.NUMERIC),
        record_field(offset=1219, length=3, field_id="DP30302_F114_C", kind=FieldKind.NUMERIC),
        record_field(offset=1222, length=2, field_id="DP30302_F115_C", kind=FieldKind.NUMERIC),
        record_field(offset=1224, length=4, field_id="DP30302_F116_C", kind=FieldKind.NUMERIC),
        record_field(offset=1228, length=3, field_id="DP30302_F117_C", kind=FieldKind.NUMERIC),
        record_field(offset=1231, length=3, field_id="DP30302_F118_C", kind=FieldKind.NUMERIC),
        record_field(offset=1234, length=2, field_id="DP30302_F119_C", kind=FieldKind.NUMERIC),
        record_field(offset=1236, length=3, field_id="DP30302_F120_C", kind=FieldKind.NUMERIC),
        record_field(offset=1239, length=3, field_id="DP30302_F121_C", kind=FieldKind.NUMERIC),
        record_field(offset=1242, length=3, field_id="DP30302_F122_C", kind=FieldKind.NUMERIC),
        record_field(offset=1245, length=1, field_id="DP30302_F123_C", kind=FieldKind.NUMERIC),
        record_field(offset=1246, length=17, field_id="DP30302_F124_C", kind=FieldKind.NUMERIC),
        record_field(offset=1263, length=17, field_id="DP30302_F125_C", kind=FieldKind.NUMERIC),
        record_field(offset=1280, length=7, field_id="DP30302_F126_C", kind=FieldKind.NUMERIC),
        record_field(offset=1287, length=7, field_id="DP30302_F127_C", kind=FieldKind.NUMERIC),
        record_field(offset=1294, length=7, field_id="DP30302_F128_C", kind=FieldKind.NUMERIC),
        record_field(offset=1301, length=4, field_id="DP30302_F129_C", kind=FieldKind.NUMERIC),
        record_field(offset=1305, length=4, field_id="DP30302_F130_C", kind=FieldKind.NUMERIC),
        record_field(offset=1309, length=1, field_id="DP30302_F131_C", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=1310, length=4, field_id="DP30302_F132_C", kind=FieldKind.NUMERIC),
        record_field(offset=1314, length=7, field_id="DP30302_F133_C", kind=FieldKind.NUMERIC),
        record_field(offset=1321, length=2, field_id="DP30302_F134_C", kind=FieldKind.NUMERIC),
        record_field(offset=1323, length=4, field_id="DP30302_F135_C", kind=FieldKind.NUMERIC),
        record_field(offset=1327, length=3, field_id="DP30302_F136_C", kind=FieldKind.NUMERIC),
        record_field(offset=1330, length=2, field_id="DP30302_F137_C", kind=FieldKind.NUMERIC),
        record_field(offset=1332, length=4, field_id="DP30302_F138_C", kind=FieldKind.NUMERIC),
        record_field(offset=1336, length=3, field_id="DP30302_F139_C", kind=FieldKind.NUMERIC),
        record_field(offset=1339, length=2, field_id="DP30302_F140_C", kind=FieldKind.NUMERIC),
        record_field(offset=1341, length=4, field_id="DP30302_F141_C", kind=FieldKind.NUMERIC),
        record_field(offset=1345, length=3, field_id="DP30302_F142_C", kind=FieldKind.NUMERIC),
        record_field(offset=1348, length=2, field_id="DP30302_F143_C", kind=FieldKind.NUMERIC),
        record_field(offset=1350, length=4, field_id="DP30302_F144_C", kind=FieldKind.NUMERIC),
        record_field(offset=1354, length=3, field_id="DP30302_F145_C", kind=FieldKind.NUMERIC),
        record_field(offset=1357, length=17, field_id="DP30302_F146_C", kind=FieldKind.NUMERIC),
        record_field(offset=1374, length=17, field_id="DP30302_F147_C", kind=FieldKind.NUMERIC),
        record_field(offset=1391, length=17, field_id="DP30302_F148_C", kind=FieldKind.NUMERIC),
        record_field(offset=1408, length=17, field_id="DP30302_F149_C", kind=FieldKind.NUMERIC),
        record_field(offset=1425, length=3, field_id="DP30302_F150_C", kind=FieldKind.NUMERIC),
        record_field(offset=1428, length=3, field_id="DP30302_F151_C", kind=FieldKind.NUMERIC),
        record_field(offset=1431, length=264, field_id="DP30302_F152", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=1695, length=12, field_id="DP30302_F153", kind=FieldKind.ALPHANUMERIC),
    ),
    total_length=1706,
)

_SEGMENT_3_DP30303 = SegmentSpec(
    segment_id="DP30303",
    specs=(
        record_field(
            offset=1,
            length=2,
            field_id="DP30303_F001_INICIO_DEL_IDENTIFICADOR_DE",
            kind=FieldKind.RESERVED,
            literal_value="<T",
        ),
        record_field(offset=3, length=3, field_id="DP30303_F002_MODELO", kind=FieldKind.RESERVED, literal_value="303"),
        record_field(
            offset=6, length=5, field_id="DP30303_F003_P_GINA", kind=FieldKind.RESERVED, literal_value="03000"
        ),
        record_field(
            offset=11,
            length=1,
            field_id="DP30303_F004_FIN_DE_IDENTIFICADOR_DE_MODE",
            kind=FieldKind.RESERVED,
            literal_value=">",
        ),
        record_field(
            offset=12,
            length=17,
            field_id="DP30303_CAS59",
            casilla_id="59",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=29,
            length=17,
            field_id="DP30303_CAS60",
            casilla_id="60",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=46,
            length=17,
            field_id="DP30303_CAS120",
            casilla_id="120",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=63,
            length=17,
            field_id="DP30303_CAS122",
            casilla_id="122",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=80,
            length=17,
            field_id="DP30303_CAS123",
            casilla_id="123",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=97,
            length=17,
            field_id="DP30303_CAS124",
            casilla_id="124",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=114,
            length=17,
            field_id="DP30303_CAS62",
            casilla_id="62",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=131,
            length=17,
            field_id="DP30303_CAS63",
            casilla_id="63",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=148,
            length=17,
            field_id="DP30303_CAS74",
            casilla_id="74",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=165,
            length=17,
            field_id="DP30303_CAS75",
            casilla_id="75",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=182,
            length=17,
            field_id="DP30303_CAS76",
            casilla_id="76",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=199,
            length=17,
            field_id="DP30303_CAS46",
            casilla_id="46",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(offset=216, length=5, field_id="DP30303_CAS65", casilla_id="65", kind=FieldKind.NUMERIC),
        record_field(
            offset=221,
            length=17,
            field_id="DP30303_CAS66",
            casilla_id="66",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(offset=238, length=17, field_id="DP30303_CAS77", casilla_id="77", kind=FieldKind.CURRENCY),
        record_field(offset=255, length=17, field_id="DP30303_CAS110", casilla_id="110", kind=FieldKind.CURRENCY),
        record_field(offset=272, length=17, field_id="DP30303_CAS78", casilla_id="78", kind=FieldKind.CURRENCY),
        record_field(offset=289, length=17, field_id="DP30303_CAS110_2", casilla_id="110_2", kind=FieldKind.CURRENCY),
        record_field(
            offset=306,
            length=17,
            field_id="DP30303_CAS68",
            casilla_id="68",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=323,
            length=17,
            field_id="DP30303_CAS66_2",
            casilla_id="66_2",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(offset=340, length=17, field_id="DP30303_CAS70", casilla_id="70", kind=FieldKind.CURRENCY),
        record_field(offset=357, length=17, field_id="DP30303_CAS109", casilla_id="109", kind=FieldKind.CURRENCY),
        record_field(
            offset=374,
            length=17,
            field_id="DP30303_CAS69",
            casilla_id="69",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=391, length=1, field_id="DP30303_F028_DECLARACI_N_SIN_ACTIVIDAD", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=392, length=1, field_id="DP30303_F029_DECLARACI_N_COMPLEMENTARIA", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=393, length=13, field_id="DP30303_F030_N_MERO_JUSTIFICANTE_DECLARAC", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=406, length=35, field_id="DP30303_F031_RESERVADO_PARA_LA_AEAT", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=441, length=86, field_id="DP30303_F032_RESERVADO_PARA_LA_AEAT", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=527, length=479, field_id="DP30303_F033_RESERVADO_PARA_LA_AEAT", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=1006,
            length=12,
            field_id="DP30303_F034_INDICADOR_DE_FIN_DE_REGISTRO",
            kind=FieldKind.RESERVED,
            literal_value="</T30303000>",
        ),
    ),
    total_length=1017,
)

_SEGMENT_4_DP30304 = SegmentSpec(
    segment_id="DP30304",
    specs=(
        record_field(
            offset=1,
            length=2,
            field_id="DP30304_F001_INICIO_DEL_IDENTIFICADOR_DE",
            kind=FieldKind.RESERVED,
            literal_value="<T",
        ),
        record_field(offset=3, length=3, field_id="DP30304_F002_MODELO", kind=FieldKind.RESERVED, literal_value="303"),
        record_field(
            offset=6, length=5, field_id="DP30304_F003_P_GINA", kind=FieldKind.RESERVED, literal_value="04000"
        ),
        record_field(
            offset=11,
            length=1,
            field_id="DP30304_F004_FIN_DE_IDENTIFICADOR_DE_MODE",
            kind=FieldKind.RESERVED,
            literal_value=">",
        ),
        record_field(
            offset=12, length=1, field_id="DP30304_F005_INDICADOR_DE_P_GINA_COMPLEME", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=13, length=3, field_id="DP30304_F006_EXCLUSIVAMENTE_A_CUMPLIMENTA", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=16, length=4, field_id="DP30304_F007_EXCLUSIVAMENTE_A_CUMPLIMENTA", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=20, length=3, field_id="DP30304_F008_EXCLUSIVAMENTE_A_CUMPLIMENTA", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=23, length=4, field_id="DP30304_F009_EXCLUSIVAMENTE_A_CUMPLIMENTA", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=27, length=3, field_id="DP30304_F010_EXCLUSIVAMENTE_A_CUMPLIMENTA", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=30, length=4, field_id="DP30304_F011_EXCLUSIVAMENTE_A_CUMPLIMENTA", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=34, length=3, field_id="DP30304_F012_EXCLUSIVAMENTE_A_CUMPLIMENTA", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=37, length=4, field_id="DP30304_F013_EXCLUSIVAMENTE_A_CUMPLIMENTA", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=41, length=3, field_id="DP30304_F014_EXCLUSIVAMENTE_A_CUMPLIMENTA", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=44, length=4, field_id="DP30304_F015_EXCLUSIVAMENTE_A_CUMPLIMENTA", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=48, length=3, field_id="DP30304_F016_EXCLUSIVAMENTE_A_CUMPLIMENTA", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=51, length=4, field_id="DP30304_F017_EXCLUSIVAMENTE_A_CUMPLIMENTA", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=55, length=1, field_id="DP30304_F018_EXCLUSIVAMENTE_A_CUMPLIMENTA", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(offset=56, length=5, field_id="DP30304_CAS89", casilla_id="89", kind=FieldKind.NUMERIC),
        record_field(offset=61, length=5, field_id="DP30304_CAS90", casilla_id="90", kind=FieldKind.NUMERIC),
        record_field(offset=66, length=5, field_id="DP30304_CAS91", casilla_id="91", kind=FieldKind.NUMERIC),
        record_field(offset=71, length=5, field_id="DP30304_CAS92", casilla_id="92", kind=FieldKind.NUMERIC),
        record_field(offset=76, length=5, field_id="DP30304_CAS107", casilla_id="107", kind=FieldKind.NUMERIC),
        record_field(
            offset=81,
            length=17,
            field_id="DP30304_CAS80",
            casilla_id="80",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=98,
            length=17,
            field_id="DP30304_CAS81",
            casilla_id="81",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=115,
            length=17,
            field_id="DP30304_CAS93",
            casilla_id="93",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=132,
            length=17,
            field_id="DP30304_CAS94",
            casilla_id="94",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=149,
            length=17,
            field_id="DP30304_CAS83",
            casilla_id="83",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=166,
            length=17,
            field_id="DP30304_CAS84",
            casilla_id="84",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=183,
            length=17,
            field_id="DP30304_CAS125",
            casilla_id="125",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=200,
            length=17,
            field_id="DP30304_CAS126",
            casilla_id="126",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=217,
            length=17,
            field_id="DP30304_CAS127",
            casilla_id="127",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=234,
            length=17,
            field_id="DP30304_CAS128",
            casilla_id="128",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=251,
            length=17,
            field_id="DP30304_CAS86",
            casilla_id="86",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=268,
            length=17,
            field_id="DP30304_CAS95",
            casilla_id="95",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=285,
            length=17,
            field_id="DP30304_CAS96",
            casilla_id="96",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=302,
            length=17,
            field_id="DP30304_CAS97",
            casilla_id="97",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=319,
            length=17,
            field_id="DP30304_CAS98",
            casilla_id="98",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=336,
            length=17,
            field_id="DP30304_CAS79",
            casilla_id="79",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=353,
            length=17,
            field_id="DP30304_CAS99",
            casilla_id="99",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=370,
            length=17,
            field_id="DP30304_CAS80_2",
            casilla_id="80_2",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=387, length=600, field_id="DP30304_F042_RESERVADO_PARA_LA_AEAT", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=987,
            length=12,
            field_id="DP30304_F043_INDICADOR_DE_FIN_DE_REGISTRO",
            kind=FieldKind.RESERVED,
            literal_value="</T30304000>",
        ),
    ),
    total_length=998,
)

_SEGMENT_5_DP30305 = SegmentSpec(
    segment_id="DP30305",
    specs=(
        record_field(offset=1, length=2, field_id="DP30305_F001", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=3, length=3, field_id="DP30305_F002", kind=FieldKind.NUMERIC),
        record_field(offset=6, length=5, field_id="DP30305_F003", kind=FieldKind.NUMERIC),
        record_field(offset=11, length=1, field_id="DP30305_F004", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=12, length=1, field_id="DP30305_F005_C", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=13, length=3, field_id="DP30305_F006_C", kind=FieldKind.ALPHANUMERIC),
        record_field(
            offset=16, length=17, field_id="DP30305_F007_C", kind=FieldKind.CURRENCY, signed_mode=SignedMode.INLINE_SIGN
        ),
        record_field(
            offset=33, length=17, field_id="DP30305_F008_C", kind=FieldKind.CURRENCY, signed_mode=SignedMode.INLINE_SIGN
        ),
        record_field(offset=50, length=1, field_id="DP30305_F009_C", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=51, length=5, field_id="DP30305_F010_C", kind=FieldKind.NUMERIC),
        record_field(offset=56, length=3, field_id="DP30305_F011_C", kind=FieldKind.ALPHANUMERIC),
        record_field(
            offset=59, length=17, field_id="DP30305_F012_C", kind=FieldKind.CURRENCY, signed_mode=SignedMode.INLINE_SIGN
        ),
        record_field(
            offset=76, length=17, field_id="DP30305_F013_C", kind=FieldKind.CURRENCY, signed_mode=SignedMode.INLINE_SIGN
        ),
        record_field(offset=93, length=1, field_id="DP30305_F014_C", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=94, length=5, field_id="DP30305_F015_C", kind=FieldKind.NUMERIC),
        record_field(offset=99, length=3, field_id="DP30305_F016_C", kind=FieldKind.ALPHANUMERIC),
        record_field(
            offset=102,
            length=17,
            field_id="DP30305_F017_C",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=119,
            length=17,
            field_id="DP30305_F018_C",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(offset=136, length=1, field_id="DP30305_F019_C", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=137, length=5, field_id="DP30305_F020_C", kind=FieldKind.NUMERIC),
        record_field(offset=142, length=3, field_id="DP30305_F021_C", kind=FieldKind.ALPHANUMERIC),
        record_field(
            offset=145,
            length=17,
            field_id="DP30305_F022_C",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=162,
            length=17,
            field_id="DP30305_F023_C",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(offset=179, length=1, field_id="DP30305_F024_C", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=180, length=5, field_id="DP30305_F025_C", kind=FieldKind.NUMERIC),
        record_field(offset=185, length=3, field_id="DP30305_F026_C", kind=FieldKind.ALPHANUMERIC),
        record_field(
            offset=188,
            length=17,
            field_id="DP30305_F027_C",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=205,
            length=17,
            field_id="DP30305_F028_C",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(offset=222, length=1, field_id="DP30305_F029_C", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=223, length=5, field_id="DP30305_F030_C", kind=FieldKind.NUMERIC),
        record_field(offset=228, length=17, field_id="DP30305_F031_C", kind=FieldKind.NUMERIC),
        record_field(offset=245, length=17, field_id="DP30305_F032_C", kind=FieldKind.NUMERIC),
        record_field(offset=262, length=17, field_id="DP30305_F033_C", kind=FieldKind.NUMERIC),
        record_field(offset=279, length=17, field_id="DP30305_F034_C", kind=FieldKind.NUMERIC),
        record_field(offset=296, length=17, field_id="DP30305_F035_C", kind=FieldKind.NUMERIC),
        record_field(offset=313, length=17, field_id="DP30305_F036_C", kind=FieldKind.NUMERIC),
        record_field(offset=330, length=17, field_id="DP30305_F037_C", kind=FieldKind.NUMERIC),
        record_field(offset=347, length=17, field_id="DP30305_F038_C", kind=FieldKind.NUMERIC),
        record_field(offset=364, length=17, field_id="DP30305_F039_C", kind=FieldKind.NUMERIC),
        record_field(offset=381, length=17, field_id="DP30305_F040_C", kind=FieldKind.NUMERIC),
        record_field(offset=398, length=17, field_id="DP30305_F041_C", kind=FieldKind.NUMERIC),
        record_field(offset=415, length=17, field_id="DP30305_F042_C", kind=FieldKind.NUMERIC),
        record_field(offset=432, length=17, field_id="DP30305_F043_C", kind=FieldKind.NUMERIC),
        record_field(offset=449, length=17, field_id="DP30305_F044_C", kind=FieldKind.NUMERIC),
        record_field(
            offset=466,
            length=17,
            field_id="DP30305_F045_C",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=483,
            length=17,
            field_id="DP30305_F046_C",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=500,
            length=17,
            field_id="DP30305_F047_C",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=517,
            length=17,
            field_id="DP30305_F048_C",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(offset=534, length=17, field_id="DP30305_F049_C", kind=FieldKind.NUMERIC),
        record_field(offset=551, length=17, field_id="DP30305_F050_C", kind=FieldKind.NUMERIC),
        record_field(offset=568, length=17, field_id="DP30305_F051_C", kind=FieldKind.NUMERIC),
        record_field(offset=585, length=17, field_id="DP30305_F052_C", kind=FieldKind.NUMERIC),
        record_field(offset=602, length=17, field_id="DP30305_F053_C", kind=FieldKind.NUMERIC),
        record_field(offset=619, length=17, field_id="DP30305_F054_C", kind=FieldKind.NUMERIC),
        record_field(offset=636, length=17, field_id="DP30305_F055_C", kind=FieldKind.NUMERIC),
        record_field(offset=653, length=17, field_id="DP30305_F056_C", kind=FieldKind.NUMERIC),
        record_field(offset=670, length=17, field_id="DP30305_F057_C", kind=FieldKind.NUMERIC),
        record_field(offset=687, length=17, field_id="DP30305_F058_C", kind=FieldKind.NUMERIC),
        record_field(offset=704, length=17, field_id="DP30305_F059_C", kind=FieldKind.NUMERIC),
        record_field(offset=721, length=17, field_id="DP30305_F060_C", kind=FieldKind.NUMERIC),
        record_field(offset=738, length=17, field_id="DP30305_F061_C", kind=FieldKind.NUMERIC),
        record_field(offset=755, length=17, field_id="DP30305_F062_C", kind=FieldKind.NUMERIC),
        record_field(
            offset=772,
            length=17,
            field_id="DP30305_F063_C",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=789,
            length=17,
            field_id="DP30305_F064_C",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=806,
            length=17,
            field_id="DP30305_F065_C",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(
            offset=823,
            length=17,
            field_id="DP30305_F066_C",
            kind=FieldKind.CURRENCY,
            signed_mode=SignedMode.INLINE_SIGN,
        ),
        record_field(offset=840, length=672, field_id="DP30305_F067", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=1512, length=12, field_id="DP30305_F068", kind=FieldKind.ALPHANUMERIC),
    ),
    total_length=1523,
)

_SEGMENT_6_DP303DID = SegmentSpec(
    segment_id="DP303DID",
    specs=(
        record_field(
            offset=1,
            length=2,
            field_id="DP303DID_F001_INICIO_DEL_IDENTIFICADOR_DE",
            kind=FieldKind.RESERVED,
            literal_value="<T",
        ),
        record_field(offset=3, length=3, field_id="DP303DID_F002_MODELO", kind=FieldKind.RESERVED, literal_value="303"),
        record_field(
            offset=6, length=5, field_id="DP303DID_F003_P_GINA", kind=FieldKind.RESERVED, literal_value="DID00"
        ),
        record_field(
            offset=11,
            length=1,
            field_id="DP303DID_F004_FIN_DE_IDENTIFICADOR_DE_MODE",
            kind=FieldKind.RESERVED,
            literal_value=">",
        ),
        record_field(offset=12, length=11, field_id="DP303DID_F005_DEVOLUCI_N_SWIFT_BIC", kind=FieldKind.ALPHANUMERIC),
        record_field(
            offset=23, length=34, field_id="DP303DID_F006_DOMICILIACI_N_DEVOLUCI_N_IBA", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=57, length=70, field_id="DP303DID_F007_DEVOLUCI_N_BANCO_BANK_NAME", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=127, length=35, field_id="DP303DID_F008_DEVOLUCI_N_DIRECCI_N_DEL_BAN", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=162, length=30, field_id="DP303DID_F009_DEVOLUCI_N_CIUDAD_CITY", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=192, length=2, field_id="DP303DID_F010_DEVOLUCI_N_C_DIGO_PA_S_COUNT", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(offset=194, length=1, field_id="DP303DID_F011_DEVOLUCI_N_MARCA_SEPA", kind=FieldKind.NUMERIC),
        record_field(
            offset=195, length=617, field_id="DP303DID_F012_RESERVADO_PARA_LA_AEAT", kind=FieldKind.ALPHANUMERIC
        ),
        record_field(
            offset=812,
            length=12,
            field_id="DP303DID_F013_INDICADOR_DE_FIN_DE_REGISTRO",
            kind=FieldKind.RESERVED,
            literal_value="</T303DID00>",
        ),
    ),
    total_length=823,
)

_SEGMENT_7_DP30300_TRAILER = SegmentSpec(
    segment_id="DP30300_TRAILER",
    specs=(
        record_field(
            offset=1, length=6, field_id="DP30300_TRAILER_OPEN", kind=FieldKind.RESERVED, literal_value="</T303"
        ),
        record_field(
            offset=7, length=1, field_id="DP30300_TRAILER_DISCRIMINANTE", kind=FieldKind.RESERVED, literal_value="0"
        ),
        record_field(offset=8, length=4, field_id="DP30300_F004_EJERCICIO_DE_DEVENGO", kind=FieldKind.ALPHANUMERIC),
        record_field(offset=12, length=2, field_id="DP30300_F005_PER_ODO", kind=FieldKind.RESERVED, literal_value="01"),
        record_field(
            offset=14, length=4, field_id="DP30300_TRAILER_FILLER", kind=FieldKind.RESERVED, literal_value="0000"
        ),
        record_field(offset=18, length=1, field_id="DP30300_TRAILER_CLOSE", kind=FieldKind.RESERVED, literal_value=">"),
    ),
    total_length=18,
)

ENVELOPE: tuple[SegmentSpec, ...] = (
    _SEGMENT_0_DP30300,
    _SEGMENT_1_DP30301,
    _SEGMENT_2_DP30302,
    _SEGMENT_3_DP30303,
    _SEGMENT_4_DP30304,
    _SEGMENT_5_DP30305,
    _SEGMENT_6_DP303DID,
    _SEGMENT_7_DP30300_TRAILER,
)

validate_segment_specs(ENVELOPE)


__all__ = ["ENCODING", "ENVELOPE", "REQUIRED_HEADER_FIELDS"]
