"""Stream A citation audit for generated schema modules.

Every ``modelo_{n}_{year}.py`` module that is GENERATED from a
JSON fixture must carry a provenance block in its docstring
citing:

1. The AEAT Orden ministerial (e.g. ``Orden HAC/819/2024``).
2. The BOE-ID (e.g. ``BOE-A-2024-16129``).
3. The DR xlsx filename (e.g. ``DR303e24.xlsx``).

The xlsx filename must follow AEAT's canonical naming convention
``DR{modelo}e{YY}.xlsx`` where ``YY`` is the 2-digit ejercicio
tail — otherwise a reviewer cannot mechanically locate the source
document AEAT published. The year in the Orden and BOE-ID must
also match the ejercicio so a typo can't silently mis-cite an
unrelated year's document.

Clone modules (e.g. modelo_303_2025 that re-exports 2024's
ENVELOPE) are intentionally not generated; they live with a
hand-authored docstring explaining the clone relationship and
are excluded from this audit by module selection.

Stream A perpetual — any future-generator change that drops or
corrupts the provenance block fails here before it reaches a
compliance audit.
"""

from __future__ import annotations

import re
from types import ModuleType

import pytest

from . import modelo_130_2024, modelo_130_2025, modelo_303_2024, modelo_303_2025

pytestmark = [pytest.mark.unit, pytest.mark.domain_outbound, pytest.mark.domain_export]


_ORDEN_RE = re.compile(r"Orden\s+[A-Z]{2,4}/\d+/\d{4}")
_BOE_ID_RE = re.compile(r"BOE-A-\d{4}-\d+")
_XLSX_RE = re.compile(r"DR(\d{3})e(\d{2})(?:v\d+)?\.xlsx", re.IGNORECASE)


def _extract(pattern: re.Pattern[str], text: str) -> list[str]:
    return pattern.findall(text) if pattern.groups == 0 else [m.group(0) for m in pattern.finditer(text)]


class TestProvenanceCitations:
    @pytest.mark.parametrize(
        "module, expected_modelo, expected_ejercicio",
        [(modelo_303_2024, "303", "2024")],
        ids=lambda v: str(v) if not isinstance(v, ModuleType) else v.__name__.rsplit(".", 1)[-1],
    )
    def test_module_docstring_carries_provenance(
        self,
        module: ModuleType,
        expected_modelo: str,
        expected_ejercicio: str,
    ) -> None:
        """Every generator-emitted module must cite Orden + BOE-ID + xlsx."""
        doc = module.__doc__ or ""
        assert "Generated by aeat.submission._formats._generate" in doc, (
            f"{module.__name__}: missing 'Generated by' provenance header."
        )

        orden_hits = _extract(_ORDEN_RE, doc)
        assert orden_hits, f"{module.__name__}: no 'Orden XXX/NNN/YYYY' citation."

        boe_hits = _extract(_BOE_ID_RE, doc)
        assert boe_hits, f"{module.__name__}: no 'BOE-A-YYYY-NNNNN' citation."

        xlsx_match = _XLSX_RE.search(doc)
        assert xlsx_match, f"{module.__name__}: no 'DR{{modelo}}e{{YY}}.xlsx' citation."

        xlsx_modelo, xlsx_yy = xlsx_match.group(1), xlsx_match.group(2)
        assert xlsx_modelo == expected_modelo, (
            f"{module.__name__}: xlsx filename says modelo {xlsx_modelo!r}, module is for {expected_modelo!r}."
        )
        assert xlsx_yy == expected_ejercicio[-2:], (
            f"{module.__name__}: xlsx filename ejercicio tail {xlsx_yy!r} does not "
            f"match expected {expected_ejercicio[-2:]!r}."
        )

    def test_303_2024_orden_and_boe_agree_on_year(self) -> None:
        """The Orden and BOE-ID must cite the same year so a typo can't
        silently mis-cite an unrelated year's publication."""
        doc = modelo_303_2024.__doc__ or ""
        orden_match = re.search(r"Orden\s+[A-Z]{2,4}/(\d+)/(\d{4})", doc)
        boe_match = re.search(r"BOE-A-(\d{4})-\d+", doc)
        assert orden_match and boe_match
        assert orden_match.group(2) == boe_match.group(1), (
            f"Orden year {orden_match.group(2)} != BOE-ID year {boe_match.group(1)} in {modelo_303_2024.__name__}."
        )

    def test_303_2024_cites_expected_orden(self) -> None:
        """Lock the specific Orden + BOE-ID so a regeneration pointed at the
        wrong fixture can't silently rewrite the provenance to a different
        legal basis."""
        doc = modelo_303_2024.__doc__ or ""
        assert "Orden HAC/819/2024" in doc
        assert "BOE-A-2024-16129" in doc


class TestHandAuthoredProvenance:
    """extend Stream A's citation audit to the hand-authored
    record-style schemas (Modelo 130 2024 / 2025) + the 303 2025 clone.

    These modules don't come from the generator so they don't carry the
    ``Generated by aeat.submission._formats._generate`` header; they
    carry prose citations in the module docstring instead. This test
    asserts the prose contains the expected Orden + BOE-ID + DR
    references so a future rewrite of the docstring can't silently
    drop the legal basis."""

    def test_130_2024_cites_orden_eha_2007(self) -> None:
        """Modelo 130's governing norma is Orden EHA/672/2007
        (BOE-A-2007-6032); the layout has not been superseded since the
        2015 DR revision (dr130.09.pdf + DR130e15v12.xls)."""
        doc = modelo_130_2024.__doc__ or ""
        assert "Orden EHA/672/2007" in doc, "missing governing Orden"
        assert "BOE-A-2007-6032" in doc, "missing BOE-ID"
        assert "dr130.09.pdf" in doc, "missing DR PDF reference"
        assert "DR130e15v12" in doc, "missing DR xlsx reference"

    def test_130_2024_explicitly_rejects_wrong_orden(self) -> None:
        """Lock the defensive assertion that Orden HAC/819/2024 is
        IVA-scoped, not 130. A past miscitation waves ago crossed
        these wires; the docstring's explicit disclaimer blocks a
        repeat."""
        doc = modelo_130_2024.__doc__ or ""
        assert "Orden HAC/819/2024 is" in doc
        assert "IVA-scoped" in doc or "not 130" in doc

    def test_130_2025_documents_clone_relationship(self) -> None:
        """The 2025 clone must explicitly name its 2024 source + the
        governing Orden so a reader lands on the legal basis without
        chasing :mod: references."""
        doc = modelo_130_2025.__doc__ or ""
        # Normalise whitespace so line-breaks inside the docstring don't
        # break substring matches — we care that the tokens co-occur,
        # not about paragraph formatting.
        flat = " ".join(doc.split())
        assert "Structural clone of :mod:`modelo_130_2024`" in flat
        assert "Orden EHA/672/2007" in flat
        assert "BOE-A-2007-6032" in flat

    def test_303_2025_documents_clone_relationship(self) -> None:
        """303 2025 clone must cite Orden HAC/819/2024 + BOE-A-2024-16129
        (the 2024 source) to make the clone contract auditable."""
        doc = modelo_303_2025.__doc__ or ""
        flat = " ".join(doc.split())
        assert "Structural clone of :mod:`modelo_303_2024`" in flat
        assert "Orden HAC/819/2024" in flat
        assert "BOE-A-2024-16129" in flat
