"""Backend-owned operator surface contract for the redesigned command tree."""

from __future__ import annotations

from ._contract import (
    ACCEPTED_ROOTS,
    MOUNTED_COMMAND_FAMILIES,
    RETIRED_OPERATOR_SURFACES,
    SOURCE_KIND_ALIASES,
    build_operator_surface_contract,
    get_operator_surface_contract,
    require_accepted_root,
    resolve_source_kind_alias,
    retired_surface_suggestion,
)
from ._errors import OperatorSurfaceContractError
from ._help import (
    build_help_document,
    build_root_landing_report,
    render_help_text,
    render_root_landing_text,
)
from ._models import (
    HelpDocument,
    HelpEntry,
    HelpSection,
    HelpSurface,
    LifecycleContract,
    ModeloLifecycleStep,
    MountedCommandDomain,
    MountedCommandFamily,
    OperatorMutability,
    OperatorSurfaceContract,
    OperatorSurfaceLogFields,
    RetiredOperatorSurface,
    RootLandingReport,
    RootSurface,
    RootSurfaceName,
    ServiceOwner,
    SourceKind,
    SourceKindAlias,
)

__all__ = [
    "ACCEPTED_ROOTS",
    "MOUNTED_COMMAND_FAMILIES",
    "RETIRED_OPERATOR_SURFACES",
    "SOURCE_KIND_ALIASES",
    "HelpDocument",
    "HelpEntry",
    "HelpSection",
    "HelpSurface",
    "LifecycleContract",
    "ModeloLifecycleStep",
    "MountedCommandDomain",
    "MountedCommandFamily",
    "OperatorMutability",
    "OperatorSurfaceContract",
    "OperatorSurfaceContractError",
    "OperatorSurfaceLogFields",
    "RetiredOperatorSurface",
    "RootLandingReport",
    "RootSurface",
    "RootSurfaceName",
    "ServiceOwner",
    "SourceKind",
    "SourceKindAlias",
    "build_help_document",
    "build_operator_surface_contract",
    "build_root_landing_report",
    "get_operator_surface_contract",
    "render_help_text",
    "render_root_landing_text",
    "require_accepted_root",
    "resolve_source_kind_alias",
    "retired_surface_suggestion",
]
