"""Verification chain: M100 borrador surface → parser → calculation engine.

M100 borrador-surface verification chain.

Unlike the declaracion_pdf surface (CORPUS-LIMITED: all amounts sanitised to
1.001.000,00), the borrador surface uses synthetic fixtures whose casilla
values are derived directly from the registry engine.  This makes the
end-to-end chain verifiable:

    parse_borrador(borrador_pdf)
        → InboundBorradorObservation.values (ExtractedCasilla)
        → inputs = {0505: extracted_0505}
        → calculate_registry_snapshot(snapshot, inputs, binding_values, ...)
        → engine_result.values[closure_casilla_id]
        → assert engine_value == extracted_value  (VERIFIED)

Corpus fixtures live at src/cadrumo/tests/fixtures/borrador/modelo_100_{year}.pdf.
They are generated by _generate.py with values anchored to the registry's
committed bracket tables (renta-{year}-escala-estatal-base-general and the
autonomic equivalents for Cataluña), via the same calculate_registry_snapshot
call that this test exercises.

Anti-tautology rationale:
  - The fixture value for 0545 was frozen at generation time.
  - If the registry formula ``renta-{year}-cuota-integra-estatal`` or the
    bracket parameter ``renta-{year}-escala-estatal-base-general`` changes,
    the engine will produce a different value → test FAILS loudly.
  - A parser regression that mis-extracts 0505 will propagate to a different
    engine output → test FAILS loudly.
  - The CCAA binding must resolve correctly; if it is dropped or misrouted,
    the autonomic closure (0546/0586) will differ → test FAILS loudly.

Legal grounding:
    Ley 35/2006 art.50    — base liquidable general
    Ley 35/2006 art.62-63 — cuota íntegra estatal (escala general)
    Ley 35/2006 art.73-74 — cuota íntegra autonómica (escala general autonómica)
    Ley 35/2006 art.67/77, with art.68 deductions
        -- cuota liquida = cuota integra - deducciones

Verdict taxonomy per casilla:
    VERIFIED  — engine_value == extracted_value
    MISMATCH  — formula or parser regression; reported as assertion failure.

Corpus fixtures use:
    CCAA:            Cataluña
    Modalidad:       Estimación directa simplificada (casilla 0168 = S → boolean 0)
    Base liquidable: 30 000,00 EUR (0505)
    Retenciones:     0 (simplest verifiable scenario; no prior-period bindings)
    Pagos fracc.:    0 (no prior M130/M131 quarterly filings in fixture)

Comprehensive M100 borrador verdict:

| Year | 0545 (cuota integra estatal) | 0546 (cuota integra autonomica) | Verdict  |
|------|-----------------------------|---------------------------------|----------|
| 2021 | 3 582,75 EUR                | 3 845,85 EUR                    | VERIFIED |
| 2022 | 3 582,75 EUR                | 3 749,10 EUR                    | VERIFIED |
| 2023 | 3 582,75 EUR                | 3 749,10 EUR                    | VERIFIED |

The autonomic bracket for 2021 differs from 2022/2023 because Cataluña
published updated tariffs for IRPF 2022 (Llei 5/2020 CG reform effective
from FY2022 declarations).
"""

from __future__ import annotations

from datetime import date
from decimal import Decimal

import pytest

from .....core.casilla_id import CasillaId, validated_casilla_id
from .....domain.calculations.registry.authority import bundled_authority
from .....domain.calculations.registry.errors import RegistryValidationError
from .....domain.calculations.registry.formula_runtime import calculate_registry_snapshot
from .....tests import FIXTURES_DIR
from ..parser import parse_borrador
from ..schema import ArtefactKind, BorradorParseMode
from ..errors import BorradorParseError

pytestmark = [
    pytest.mark.unit,
    pytest.mark.hex_inbound_adapter,
]

_BORRADOR_FIXTURES_DIR = FIXTURES_DIR / "borrador"

# Casilla 0505 (base liquidable general sometida a gravamen) is computed from
# the 2020-2023 revisions onward (max(0, 0500)), so it can no
# longer be supplied as a leaf input. The verification chain feeds the trabajo
# leaf 0003 (ingresos íntegros) instead and lets the engine derive 0500 -> 0505.
# In the fixture scenario the only work-income adjustment is the art. 19.2.f
# LIRPF "otros gastos" deduction (min(2.000, rendimiento)), so the leaf is the
# extracted 0505 inflated by 2.000 EUR to net back to the fixture's base
# liquidable general; the engine then recomputes 0505 == extracted 0505.
_TRABAJO_INGRESOS_INTEGROS_CASILLA: CasillaId = validated_casilla_id(
    "0003",
    surface="_TRABAJO_INGRESOS_INTEGROS_CASILLA",
)
_OTROS_GASTOS_ART_19_2_F: Decimal = Decimal("2000")
_BASE_LIQUIDABLE_GENERAL_CASILLA: CasillaId = validated_casilla_id("0505", surface="_BASE_LIQUIDABLE_GENERAL_CASILLA")
_CUOTA_INTEGRA_ESTATAL_CASILLA: CasillaId = validated_casilla_id("0545", surface="_CUOTA_INTEGRA_ESTATAL_CASILLA")
_CUOTA_INTEGRA_AUTONOMICA_CASILLA: CasillaId = validated_casilla_id(
    "0546",
    surface="_CUOTA_INTEGRA_AUTONOMICA_CASILLA",
)
_CUOTA_LIQUIDA_ESTATAL_CASILLA: CasillaId = validated_casilla_id("0585", surface="_CUOTA_LIQUIDA_ESTATAL_CASILLA")
_CUOTA_LIQUIDA_AUTONOMICA_CASILLA: CasillaId = validated_casilla_id(
    "0586",
    surface="_CUOTA_LIQUIDA_AUTONOMICA_CASILLA",
)
_COMPUTED_CASILLAS_M100: frozenset[CasillaId] = frozenset(
    {
        _CUOTA_INTEGRA_ESTATAL_CASILLA,
        _CUOTA_INTEGRA_AUTONOMICA_CASILLA,
        _CUOTA_LIQUIDA_ESTATAL_CASILLA,
        _CUOTA_LIQUIDA_AUTONOMICA_CASILLA,
    },
)


def _registry_snapshot_m100(year: int):
    """Resolve the M100 validated registry snapshot for the given filing year."""
    return bundled_authority().snapshot("100", filing_year=year, period="0A")


def _borrador_extraction_profile(snapshot):
    profiles = tuple(profile for profile in snapshot.extraction_profiles.values() if profile.surface == "borrador_pdf")
    assert len(profiles) == 1, (
        f"expected one M100 borrador extraction profile, got {[profile.id for profile in profiles]}"
    )
    return profiles[0]


def _binding_values_for_year(year: int) -> dict[str, Decimal]:
    """Return the Decimal-channel binding values for the given M100 filing year.

    Supplies zero values for the retenciones bindings (no prior-period filings
    in the corpus scenario) and SimplificadaModalidad (casilla 0168 = S → 0).
    """
    pfx = f"renta-{year}-"
    return {
        f"{pfx}modelo-100-estimacion-directa-es-normal": Decimal("0"),
        f"{pfx}modelo-111-retenciones-periodicas": Decimal("0"),
        f"{pfx}modelo-123-retenciones-periodicas": Decimal("0"),
        # Childless borrador fixture: Art. 58/61 LIRPF mínimo por descendientes
        # aggregate is zero for a childless profile.
        f"{pfx}profile-minimo-descendientes-estatal": Decimal("0"),
        # Parte autonómica: non-Madrid corpus fixture mirrors the estatal zero.
        f"{pfx}profile-minimo-descendientes-autonomico": Decimal("0"),
    }


def _enum_binding_values_for_year(year: int) -> dict[str, str]:
    """Return the string-enum-channel binding values for the given M100 year.

    The CCAA dispatch uses Cataluña for all fixtures; the autonomic tariff is
    sourced from the committed registry parameter table.
    """
    return {f"renta-{year}-profile-tax-residence-ccaa": "cataluna"}


def _relation_values_for_year(year: int) -> dict[str, Decimal]:
    """Return relation-channel values for absent quarterly pago fraccionado evidence."""
    pfx = f"renta-{year}-"
    return {
        f"{pfx}rel-130-pagos-fraccionados": Decimal("0"),
        f"{pfx}rel-131-pagos-fraccionados": Decimal("0"),
    }


@pytest.mark.parametrize(
    "year",
    [2021, 2022, 2023],
)
def test_verification_chain_m100_borrador_engine_recomputes_cuota_integra(year: int) -> None:
    """Engine recomputes cuota íntegra estatal and autonómica from the extracted leaf input.

    FIXTURE, NOT ORACLE — and circular by construction: the synthetic fixtures
    at src/cadrumo/tests/fixtures/borrador/modelo_100_{year}.pdf are generated
    by _generate.py with values anchored to THE REGISTRY'S OWN committed
    bracket tables (Ley 35/2006 art.62-63 escala general estatal; art.73-74
    escala general autonómica). The expected cuota is therefore derived from
    the same tables the engine applies, so this test cannot detect a bracket
    table that is wrong against AEAT — only one the engine applies
    inconsistently with its own declaration. What it genuinely proves is that
    the borrador parse feeds 0505 through to 0545/0546 and that the bracket
    lookup is wired to the CCAA binding.

    Chain:
      1. parse_borrador(corpus_pdf) → InboundBorradorObservation with 5 casillas.
      2. Supply 0505 (base liquidable general) as engine leaf input.
      3. calculate_registry_snapshot with CCAA=cataluna binding.
      4. Assert engine.values["0545"] == extracted["0545"]  (cuota íntegra estatal).
         Assert engine.values["0546"] == extracted["0546"]  (cuota íntegra autonómica).
         Assert engine.values["0585"] == extracted["0585"]  (cuota líquida estatal incrementada).
         Assert engine.values["0586"] == extracted["0586"]  (cuota líquida autonómica incrementada).

    Fixtures use Cataluña CCAA and zero-deduction scenario so that:
      cuota líquida = cuota íntegra  (no deducciones, no incrementos)
      → 0585 == 0545, 0586 == 0546

    Verdict: VERIFIED — engine recomputes all four closure casillas for all
    three annual revisions (2021, 2022, 2023).  M100 x3 revisions transition
    EXTRACTION-ONLY (CORPUS-LIMITED) → VERIFIED via the borrador surface.
    """
    pdf_path = _BORRADOR_FIXTURES_DIR / f"modelo_100_{year}.pdf"
    snapshot = _registry_snapshot_m100(year)
    extraction_profile = _borrador_extraction_profile(snapshot)

    # Parse the borrador PDF.
    try:
        borrador = parse_borrador(
            pdf_path,
            artefact_kind_override=ArtefactKind.BORRADOR,
            año_override=year,
            extraction_profile=extraction_profile,
            parse_mode=BorradorParseMode.REGISTRY_PROFILE,
        )
    except BorradorParseError as exc:
        pytest.fail(f"PARSER-GAP [M100-borrador/{year}]: parse_borrador raised BorradorParseError.\n  error: {exc}")

    assert borrador.registry_extraction_profile_id == extraction_profile.id
    assert borrador.extraction_coverage == Decimal("1")
    extracted = {v.casilla_id: v.printed_value for v in borrador.values}

    # Verify leaf input 0505 is present and is a Decimal.
    assert _BASE_LIQUIDABLE_GENERAL_CASILLA in extracted, (
        f"PARSER-GAP [M100-borrador/{year}]: leaf casilla '0505' not extracted.\n  got: {sorted(extracted)}"
    )
    assert isinstance(extracted[_BASE_LIQUIDABLE_GENERAL_CASILLA], Decimal), (
        f"PARSER-GAP [M100-borrador/{year}]: casilla '0505' is not Decimal: "
        f"{type(extracted[_BASE_LIQUIDABLE_GENERAL_CASILLA]).__name__!r}"
    )

    # Build engine inputs: supply the trabajo leaf 0003 derived from the
    # extracted 0505 (0505 is computed from 0500 in these revisions and cannot
    # be fed). 0003 = extracted 0505 + 2.000 EUR nets, through the art. 19.2.f
    # otros-gastos deduction, back to 0500 == 0505 == extracted 0505; the engine
    # then recomputes the closure casillas (0545, 0546, 0585, 0586).
    base_liquidable = extracted[_BASE_LIQUIDABLE_GENERAL_CASILLA]
    assert isinstance(base_liquidable, Decimal)
    inputs: dict[CasillaId, Decimal] = {
        _TRABAJO_INGRESOS_INTEGROS_CASILLA: base_liquidable + _OTROS_GASTOS_ART_19_2_F,
    }

    try:
        result = calculate_registry_snapshot(
            snapshot,
            inputs=inputs,
            date_context={"filing_period": date(year, 6, 30)},
            binding_values=_binding_values_for_year(year),
            enum_binding_values=_enum_binding_values_for_year(year),
            relation_values=_relation_values_for_year(year),
        )
    except RegistryValidationError as exc:
        pytest.fail(
            f"BINDING-GAP [M100-borrador/{year}]: calculate_registry_snapshot raised "
            f"RegistryValidationError — a required binding is missing.\n"
            f"  error: {exc}\n"
            f"  inputs supplied: {sorted(inputs)}\n"
            f"  binding_values supplied: {sorted(_binding_values_for_year(year))}\n"
            f"  relation_values supplied: {sorted(_relation_values_for_year(year))}",
        )

    engine_values = dict(result.values)

    # The engine must recompute 0505 (now a computed casilla) back to the
    # extracted base liquidable general from the 0003 leaf.
    engine_base_liquidable = engine_values.get(_BASE_LIQUIDABLE_GENERAL_CASILLA)
    assert engine_base_liquidable == base_liquidable, (
        f"VERIFIED-FAIL [M100-borrador/{year}]: engine recomputed 0505 as "
        f"{engine_base_liquidable!r} but fixture base liquidable is {base_liquidable!r}; "
        f"leaf 0003={inputs[_TRABAJO_INGRESOS_INTEGROS_CASILLA]!r}."
    )

    # VERIFIED gate: all four closure casillas must match.
    for closure_id in _COMPUTED_CASILLAS_M100:
        if closure_id not in extracted:
            pytest.fail(
                f"PARSER-GAP [M100-borrador/{year}]: closure casilla {closure_id!r} "
                f"not extracted from fixture.\n  got: {sorted(extracted)}",
            )

        extracted_val = extracted[closure_id]
        assert isinstance(extracted_val, Decimal), (
            f"PARSER-GAP [M100-borrador/{year}]: casilla {closure_id!r} is not Decimal: "
            f"{type(extracted_val).__name__!r}"
        )

        engine_val = engine_values.get(closure_id)
        assert engine_val is not None, (
            f"FORMULA-MISMATCH [M100-borrador/{year}]: casilla {closure_id!r} absent from "
            f"engine result — formula evaluation order issue or casilla missing from revision."
        )

        assert engine_val == extracted_val, (
            f"VERIFIED-FAIL [M100-borrador/{year}]: engine recomputed casilla {closure_id!r} as "
            f"{engine_val!r} but corpus fixture shows {extracted_val!r}.\n"
            f"  diff: {engine_val - extracted_val!r}\n"
            f"  leaf input 0003={inputs.get(_TRABAJO_INGRESOS_INTEGROS_CASILLA)!r}\n"
            f"  engine chain: 0505={engine_values.get(_BASE_LIQUIDABLE_GENERAL_CASILLA)!r} "
            f"0545={engine_values.get(_CUOTA_INTEGRA_ESTATAL_CASILLA)!r} "
            f"0546={engine_values.get(_CUOTA_INTEGRA_AUTONOMICA_CASILLA)!r}"
        )
