"""Real-filesystem proofs for generated export-directory publication."""

from __future__ import annotations

import ast
import inspect
import os
from pathlib import Path
from shutil import rmtree
from types import SimpleNamespace

import pytest

from cadrumo.core.directory_scan import DirectoryEntryKind, scan_directory
from cadrumo.domain.calculations.registry.errors import RegistryValidationError
from cadrumo.domain.calculations.registry.loader import load_modelo_directory

from ..pipeline import _tree_publication
from ..pipeline._provenance_manifest import (
    EXPORT_FRAGMENT_PROVENANCE_FILENAME,
    export_fragment_provenance_manifest_json_bytes,
    load_export_fragment_provenance_manifest,
)
from ..pipeline._tree_publication import (
    GeneratedExportTreePublicationContext,
    GeneratedExportTreeTargetStateReceipt,
    publish_validated_generated_export_tree,
)
from ..pipeline._tree_validation import validate_generated_export_tree
from ..pipeline.render_check import RevisionRenderInputs
from .test_export_tree import (
    _ISOLATED_TREE,
    _isolated_render_profile,
    _wire_evidence,
    _wire_profile,
    _write_isolated_generated_authority_tree,
)

pytestmark = [pytest.mark.unit, pytest.mark.hex_core]


#: Substring of the registry's filing-grade review refusal. Publication selects a
#: filing-grade snapshot partway through, so an unreviewed target revision raises the
#: same exception type a drift case expects, before the drift under test is reached.
#: Substring of the registry's filing-grade review refusal. Pinned to the
#: message the refusal ACTUALLY raises: it once read "requires
#: operator_reviewed" and was relaxed to admit any reviewed status, agent or
#: operator, because demanding the operator stamp made a filing-grade
#: snapshot unreachable by construction. This pin was not swept with it, so
#: the guard below matched nothing and silently stopped distinguishing a
#: review-gate refusal from the injected defect -- an anti-tautology check
#: that cannot fire is worse than none, because it reads as coverage.
_REVIEW_GATE_REFUSAL = "filing-grade snapshot requires a reviewed revision"


# Modelo 130 throughout: `_write_isolated_generated_authority_tree` in
# `test_export_tree` builds its isolated tree for modelo 130, because the
# modelo 200 revision it used to target now declares 578 projection endpoints
# that semantic-map validation checks as a bijection, which a synthetic map
# cannot satisfy. These modules consume that helper, so their own paths and
# snapshot must name the same modelo or the tree and the paths disagree.
def _require_the_drift_was_reached(refusal: BaseException, drift: str) -> None:
    """Refuse a pass earned by the review gate rather than by the injected drift."""
    assert _REVIEW_GATE_REFUSAL not in str(refusal), (
        f"drift {drift!r} was not detected on its own terms: publication refused on the "
        f"registry's filing-grade review gate before reaching the recovery check this case "
        f"exercises, so a green result here would prove nothing about the injected drift"
    )


def _tree_bytes(root: Path) -> dict[str, bytes]:
    """Capture actual generated bytes for non-tautological filesystem assertions."""
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in scan_directory(root, recursive=True, select=DirectoryEntryKind.FILES)
    }


def _non_export_authority_bytes(revision_root: Path) -> dict[str, bytes]:
    """Capture revision-owned TOML authority that publication must never rewrite."""
    return {
        path.relative_to(revision_root).as_posix(): path.read_bytes()
        for path in scan_directory(revision_root, pattern="*.toml", recursive=True)
        if "export" not in path.relative_to(revision_root).parts
    }


def _publication_inputs(tmp_path: Path, snapshot, *, existing_export: bool, legacy_export: bool = False):
    """Build independent candidates through the export-tree renderer, never from a shipped tree."""
    temporary_root = tmp_path / "temporary-root"
    validation, joined, semantic_map, rendered, _candidate_export = _write_isolated_generated_authority_tree(
        temporary_root,
        snapshot,
    )
    target_root = tmp_path / "publication-root" / "registry" / "aeat"
    target_revision_root = target_root / "modelos" / _ISOLATED_TREE.modelo / "revisions" / _ISOLATED_TREE.revision
    target_revision_root.parent.mkdir(parents=True)
    prior = _write_isolated_generated_authority_tree(tmp_path / "prior-root", snapshot)
    prior_context = prior[0]
    prior_model_root = prior_context.registry_root / "modelos" / _ISOLATED_TREE.modelo
    os.replace(prior_model_root / "manifest.toml", target_root / "modelos" / _ISOLATED_TREE.modelo / "manifest.toml")
    prior_revision_root = prior_model_root / "revisions" / _ISOLATED_TREE.revision
    os.replace(prior_revision_root, target_revision_root)
    if not existing_export:
        rmtree(target_revision_root / "export")
    elif legacy_export:
        (target_revision_root / "export" / EXPORT_FRAGMENT_PROVENANCE_FILENAME).unlink()
    context = GeneratedExportTreePublicationContext(
        validation=validation,
        temporary_root=temporary_root,
        target_root=target_root,
        target_export_root=target_revision_root / "export",
    )
    candidate_export_root = (
        validation.registry_root / "modelos" / _ISOLATED_TREE.modelo / "revisions" / _ISOLATED_TREE.revision / "export"
    )
    return context, joined, semantic_map, rendered, candidate_export_root


def _rollback_siblings(target_export_root: Path) -> tuple[Path, ...]:
    target_root = target_export_root.parents[4]
    return scan_directory(target_root, pattern=".generated-export-backup-200-2025-*")


def _stage_interrupted_verified_candidate(
    context: GeneratedExportTreePublicationContext,
    candidate_export_root: Path,
) -> Path:
    candidate_manifest = _tree_publication._verify_generated_export_package(candidate_export_root)
    staged_candidate_export_root = _tree_publication._stage_verified_candidate_package(
        candidate_export_root=candidate_export_root,
        target_export_root=context.target_export_root,
        expected_manifest_sha256=_tree_publication._sha256(
            candidate_export_root / EXPORT_FRAGMENT_PROVENANCE_FILENAME,
        ),
        expected_manifest=candidate_manifest,
    )
    backup_export_root = _tree_publication._rollback_sibling(
        target_root=context.target_root.resolve(),
        modelo=_ISOLATED_TREE.modelo,
        revision_id=_ISOLATED_TREE.revision,
    )
    journal = _tree_publication._PublicationJournal(
        schema_version=1,
        state="backup_staged",
        modelo=_ISOLATED_TREE.modelo,
        revision_id=_ISOLATED_TREE.revision,
        candidate_export=str(staged_candidate_export_root),
        backup_export=str(backup_export_root),
        candidate_manifest_sha256=_tree_publication._sha256(
            staged_candidate_export_root / EXPORT_FRAGMENT_PROVENANCE_FILENAME,
        ),
    )
    os.replace(context.target_export_root, backup_export_root)
    _tree_publication._write_journal(
        _tree_publication._journal_path(context),
        journal,
    )
    return backup_export_root


def _legacy_orphan_context(tmp_path: Path) -> GeneratedExportTreePublicationContext:
    target_root = tmp_path / "publication-root" / "registry" / "aeat"
    target_export_root = target_root / "modelos" / "200" / "revisions" / "2025" / "export"
    target_export_root.parent.mkdir(parents=True)
    return GeneratedExportTreePublicationContext(
        validation=SimpleNamespace(target=SimpleNamespace(modelo="200", revision_id="2025")),  # type: ignore[arg-type]
        temporary_root=tmp_path / "temporary-root",
        target_root=target_root,
        target_export_root=target_export_root,
        expected_target_state=GeneratedExportTreeTargetStateReceipt(manifest_sha256=None, output_files=()),
    )


def _legacy_orphan_journal(
    context: GeneratedExportTreePublicationContext,
    *,
    candidate_export: Path,
    backup_export: Path,
    state: str = "intent",
) -> Path:
    journal = _tree_publication._PublicationJournal(
        schema_version=1,
        state=state,
        modelo="200",
        revision_id="2025",
        candidate_export=str(candidate_export),
        backup_export=str(backup_export),
        candidate_manifest_sha256="a" * 64,
    )
    path = _tree_publication._journal_path(context)
    _tree_publication._write_journal(path, journal)
    return path


def test_recovery_retires_only_a_provably_completed_legacy_cross_volume_orphan(tmp_path) -> None:
    context = _legacy_orphan_context(tmp_path)
    candidate_export = tmp_path / "former-system-temporary" / "export"
    backup_export = _tree_publication._rollback_sibling(
        target_root=context.target_root,
        modelo="200",
        revision_id="2025",
    )
    journal_path = _legacy_orphan_journal(
        context,
        candidate_export=candidate_export,
        backup_export=backup_export,
    )

    assert not _tree_publication._recover_interrupted_publication(
        context=context,
        target_export_root=context.target_export_root,
        journal_path=journal_path,
        joined=None,  # type: ignore[arg-type]
        semantic_map=None,  # type: ignore[arg-type]
        rendered=None,  # type: ignore[arg-type]
        render_profile=None,  # type: ignore[arg-type]
        render_profile_source_evidence=None,  # type: ignore[arg-type]
    )
    assert not journal_path.exists()
    assert not context.target_export_root.exists()


@pytest.mark.parametrize(
    ("case", "state"),
    (
        ("candidate-survives", "intent"),
        ("backup-survives", "intent"),
        ("target-survives", "intent"),
        ("outside-backup", "intent"),
        ("non-intent", "backup_staged"),
    ),
)
def test_recovery_refuses_unsafe_legacy_orphan_shapes(tmp_path, case: str, state: str) -> None:
    context = _legacy_orphan_context(tmp_path)
    candidate_export = tmp_path / "former-system-temporary" / "export"
    backup_export = _tree_publication._rollback_sibling(
        target_root=context.target_root,
        modelo="200",
        revision_id="2025",
    )
    if case == "candidate-survives":
        candidate_export.mkdir(parents=True)
    elif case == "backup-survives":
        backup_export.mkdir()
    elif case == "target-survives":
        context.target_export_root.mkdir()
    elif case == "outside-backup":
        backup_export = tmp_path / ".generated-export-backup-200-2025-outside"
    elif case != "non-intent":
        raise AssertionError(f"unexpected legacy orphan case: {case}")
    journal_path = _legacy_orphan_journal(
        context,
        candidate_export=candidate_export,
        backup_export=backup_export,
        state=state,
    )

    with pytest.raises(RegistryValidationError):
        _tree_publication._recover_interrupted_publication(
            context=context,
            target_export_root=context.target_export_root,
            journal_path=journal_path,
            joined=None,  # type: ignore[arg-type]
            semantic_map=None,  # type: ignore[arg-type]
            rendered=None,  # type: ignore[arg-type]
            render_profile=None,  # type: ignore[arg-type]
            render_profile_source_evidence=None,  # type: ignore[arg-type]
        )
    assert journal_path.exists()


def test_publication_replaces_only_export_and_removes_opaque_backup(m130_inspection_snapshot, tmp_path) -> None:
    """Revision authority survives byte-identically while export+manifest cut over together."""
    context, joined, semantic_map, rendered, candidate_export_root = _publication_inputs(
        tmp_path,
        m130_inspection_snapshot,
        existing_export=True,
        legacy_export=True,
    )
    expected_export = _tree_bytes(candidate_export_root)
    revision_root = context.target_export_root.parent
    before_authority = _non_export_authority_bytes(revision_root)

    published = publish_validated_generated_export_tree(
        context=context,
        joined=joined,
        semantic_map=semantic_map,
        rendered=rendered,
        render_profile=_isolated_render_profile()[0],
        render_profile_source_evidence=_isolated_render_profile()[1],
    )

    assert published.export_root == context.target_export_root
    assert published.provenance_manifest_path == context.target_export_root / EXPORT_FRAGMENT_PROVENANCE_FILENAME
    assert _tree_bytes(context.target_export_root) == expected_export
    assert _non_export_authority_bytes(revision_root) == before_authority
    assert candidate_export_root.exists()
    assert not _rollback_siblings(context.target_export_root)
    assert not (revision_root / "export.lock").exists()
    assert not _tree_publication._journal_path(context).exists()


def test_publication_creates_missing_export_without_touching_revision_authority(
    m130_inspection_snapshot, tmp_path
) -> None:
    """A revision can retain all non-export authority while gaining a generated export tree."""
    context, joined, semantic_map, rendered, candidate_export_root = _publication_inputs(
        tmp_path,
        m130_inspection_snapshot,
        existing_export=False,
    )
    expected_export = _tree_bytes(candidate_export_root)
    revision_root = context.target_export_root.parent
    before_authority = _non_export_authority_bytes(revision_root)

    publish_validated_generated_export_tree(
        context=context,
        joined=joined,
        semantic_map=semantic_map,
        rendered=rendered,
        render_profile=_isolated_render_profile()[0],
        render_profile_source_evidence=_isolated_render_profile()[1],
    )

    assert _tree_bytes(context.target_export_root) == expected_export
    assert _non_export_authority_bytes(revision_root) == before_authority
    assert not _rollback_siblings(context.target_export_root)


@pytest.mark.parametrize("defect", ("missing", "extra"))
def test_publication_refuses_invalid_candidate_without_changing_live_export(
    m130_inspection_snapshot,
    tmp_path,
    defect: str,
) -> None:
    """The final validation gate leaves a live export byte-identical on incomplete or extra output."""
    context, joined, semantic_map, rendered, candidate_export_root = _publication_inputs(
        tmp_path,
        m130_inspection_snapshot,
        existing_export=True,
    )
    before = _tree_bytes(context.target_export_root)
    before_authority = _non_export_authority_bytes(context.target_export_root.parent)
    if defect == "missing":
        (candidate_export_root / rendered.output_files[-1]).unlink()
    else:
        (candidate_export_root / "0003-unreviewed-layout.toml").write_text("unreviewed = true\n", encoding="utf-8")

    with pytest.raises(RegistryValidationError, match="exactly the current rendered outputs"):
        publish_validated_generated_export_tree(
            context=context,
            joined=joined,
            semantic_map=semantic_map,
            rendered=rendered,
            render_profile=_isolated_render_profile()[0],
            render_profile_source_evidence=_isolated_render_profile()[1],
        )

    assert _tree_bytes(context.target_export_root) == before
    assert _non_export_authority_bytes(context.target_export_root.parent) == before_authority
    assert candidate_export_root.exists()
    assert not _rollback_siblings(context.target_export_root)
    assert not _tree_publication._journal_path(context).exists()


@pytest.mark.parametrize(
    ("defect", "error"),
    (
        ("offset", "loader semantics do not equal the current rendered layout"),
        ("length", "loader semantics do not equal the current rendered layout"),
        ("source-anchor", "field derivations do not match the rendered tree"),
        ("target-revision", "current generation authorities"),
        ("generated-file", "output-file digests"),
    ),
)
def test_publication_refuses_coordinate_authority_and_output_mutations_before_cutover(
    m130_inspection_snapshot,
    tmp_path,
    defect: str,
    error: str,
) -> None:
    """Every mutated candidate rejects as a whole while the live revision stays byte-identical."""
    context, joined, semantic_map, rendered, candidate_export_root = _publication_inputs(
        tmp_path,
        m130_inspection_snapshot,
        existing_export=True,
    )
    before_export = _tree_bytes(context.target_export_root)
    before_authority = _non_export_authority_bytes(context.target_export_root.parent)
    fragment = candidate_export_root / rendered.output_files[1]
    manifest_path = candidate_export_root / EXPORT_FRAGMENT_PROVENANCE_FILENAME

    if defect == "offset":
        original = fragment.read_bytes()
        mutated = original.replace(b"offset = 1\n", b"offset = 2\n", 1)
        assert mutated != original
        fragment.write_bytes(mutated)
    elif defect == "length":
        original = fragment.read_bytes()
        mutated = original.replace(b"length = 2\n", b"length = 3\n", 1)
        assert mutated != original
        fragment.write_bytes(mutated)
    elif defect == "source-anchor":
        manifest = load_export_fragment_provenance_manifest(manifest_path.read_bytes())
        first_derivation = manifest.field_derivations[0]
        mutated_derivation = first_derivation.model_copy(
            update={
                "parser_field": first_derivation.parser_field.model_copy(update={"source_cell": "A999"}),
                "semantic_entry": first_derivation.semantic_entry.model_copy(
                    update={
                        "anchor": first_derivation.semantic_entry.anchor.model_copy(
                            update={"source_cell": "A999"},
                        ),
                    },
                ),
            },
        )
        manifest_path.write_bytes(
            export_fragment_provenance_manifest_json_bytes(
                manifest.model_copy(
                    update={
                        "field_derivations": (mutated_derivation, *manifest.field_derivations[1:]),
                    },
                ),
            ),
        )
    elif defect == "target-revision":
        manifest = load_export_fragment_provenance_manifest(manifest_path.read_bytes())
        manifest_path.write_bytes(
            export_fragment_provenance_manifest_json_bytes(
                manifest.model_copy(update={"revision_id": "2026"}),
            ),
        )
    elif defect == "generated-file":
        fragment.write_bytes(fragment.read_bytes() + b"# candidate mutation\n")
    else:
        raise AssertionError(f"unknown candidate mutation {defect!r}")

    with pytest.raises(RegistryValidationError, match=error):
        publish_validated_generated_export_tree(
            context=context,
            joined=joined,
            semantic_map=semantic_map,
            rendered=rendered,
            render_profile=_isolated_render_profile()[0],
            render_profile_source_evidence=_isolated_render_profile()[1],
        )

    assert _tree_bytes(context.target_export_root) == before_export
    assert _non_export_authority_bytes(context.target_export_root.parent) == before_authority
    assert candidate_export_root.exists()
    assert not _rollback_siblings(context.target_export_root)


def test_publication_restores_live_export_after_staged_cutover_refusal(
    m130_inspection_snapshot, monkeypatch, tmp_path
) -> None:
    """A same-volume staged candidate cannot leave the old export displaced."""
    context, joined, semantic_map, rendered, candidate_export_root = _publication_inputs(
        tmp_path,
        m130_inspection_snapshot,
        existing_export=True,
    )
    before = _tree_bytes(context.target_export_root)
    before_authority = _non_export_authority_bytes(context.target_export_root.parent)
    real_replace = os.replace

    def refuse_staged_cutover(source: str | os.PathLike[str], destination: str | os.PathLike[str]) -> None:
        if Path(source).name.startswith(".export.generated-stage-") and Path(destination) == context.target_export_root:
            raise OSError(17, "cross-device link")
        real_replace(source, destination)

    monkeypatch.setattr(_tree_publication.os, "replace", refuse_staged_cutover)

    with pytest.raises(RegistryValidationError, match="previous target was restored"):
        publish_validated_generated_export_tree(
            context=context,
            joined=joined,
            semantic_map=semantic_map,
            rendered=rendered,
            render_profile=_isolated_render_profile()[0],
            render_profile_source_evidence=_isolated_render_profile()[1],
        )

    assert _tree_bytes(context.target_export_root) == before
    assert _non_export_authority_bytes(context.target_export_root.parent) == before_authority
    assert candidate_export_root.exists()
    assert not tuple(context.target_export_root.parent.glob(".export.generated-stage-*"))
    assert not _rollback_siblings(context.target_export_root)
    assert not _tree_publication._journal_path(context).exists()


def test_publication_discards_only_a_completed_rollback_journal_from_an_abandoned_candidate(
    m130_inspection_snapshot, tmp_path
) -> None:
    """A prior rollback never blocks a fresh caller-owned candidate from publishing."""
    context, joined, semantic_map, rendered, candidate_export_root = _publication_inputs(
        tmp_path,
        m130_inspection_snapshot,
        existing_export=True,
    )
    expected_export = _tree_bytes(candidate_export_root)
    abandoned_candidate = tmp_path / "abandoned-candidate" / "export"
    backup_export_root = _tree_publication._rollback_sibling(
        target_root=context.target_root.resolve(),
        modelo=_ISOLATED_TREE.modelo,
        revision_id=_ISOLATED_TREE.revision,
    )
    journal = _tree_publication._PublicationJournal(
        schema_version=1,
        state="backup_staged",
        modelo=_ISOLATED_TREE.modelo,
        revision_id=_ISOLATED_TREE.revision,
        candidate_export=str(abandoned_candidate),
        backup_export=str(backup_export_root),
        candidate_manifest_sha256="a" * 64,
    )
    journal_path = _tree_publication._journal_path(context)
    _tree_publication._write_journal(journal_path, journal)

    published = publish_validated_generated_export_tree(
        context=context,
        joined=joined,
        semantic_map=semantic_map,
        rendered=rendered,
        render_profile=_isolated_render_profile()[0],
        render_profile_source_evidence=_isolated_render_profile()[1],
    )

    assert published.validated is not None
    assert _tree_bytes(context.target_export_root) == expected_export
    assert not candidate_export_root.exists()
    assert not backup_export_root.exists()
    assert not journal_path.exists()


def test_publication_completes_a_real_interrupted_verified_candidate(m130_inspection_snapshot, tmp_path) -> None:
    """Journal recovery completes a candidate validation had already proved before a crash."""
    context, joined, semantic_map, rendered, candidate_export_root = _publication_inputs(
        tmp_path,
        m130_inspection_snapshot,
        existing_export=True,
    )
    validate_generated_export_tree(
        context=context.validation,
        joined=joined,
        semantic_map=semantic_map,
        rendered=rendered,
        render_profile=_isolated_render_profile()[0],
        render_profile_source_evidence=_isolated_render_profile()[1],
    )
    expected_export = _tree_bytes(candidate_export_root)
    before_authority = _non_export_authority_bytes(context.target_export_root.parent)
    backup_export_root = _stage_interrupted_verified_candidate(context, candidate_export_root)

    recovered = publish_validated_generated_export_tree(
        context=context,
        joined=joined,
        semantic_map=semantic_map,
        rendered=rendered,
        render_profile=_isolated_render_profile()[0],
        render_profile_source_evidence=_isolated_render_profile()[1],
    )

    assert recovered.validated is None
    assert _tree_bytes(context.target_export_root) == expected_export
    assert _non_export_authority_bytes(context.target_export_root.parent) == before_authority
    assert not backup_export_root.exists()
    assert not _tree_publication._journal_path(context).exists()


@pytest.mark.parametrize("drift", ("profile", "evidence"))
def test_interrupted_recovery_refuses_current_profile_or_evidence_drift_without_mutation(
    m130_inspection_snapshot,
    tmp_path,
    drift: str,
) -> None:
    context, joined, semantic_map, rendered, candidate_export_root = _publication_inputs(
        tmp_path,
        m130_inspection_snapshot,
        existing_export=True,
    )
    backup_export_root = _stage_interrupted_verified_candidate(context, candidate_export_root)
    os.replace(candidate_export_root, context.target_export_root)
    journal_path = _tree_publication._journal_path(context)
    journal = _tree_publication._load_journal(journal_path)
    _tree_publication._write_journal(
        journal_path,
        journal.model_copy(update={"state": "candidate_live"}),
    )
    profile = _wire_profile()
    evidence = _wire_evidence()
    if drift == "profile":
        profile = profile.model_copy(update={"fragment_ids": ("current-profile-drift",)})
    else:
        evidence = evidence.model_copy(
            update={
                "design_identity": evidence.design_identity.model_copy(update={"source_sha256": "b" * 64}),
            },
        )
    target_before = _tree_bytes(context.target_export_root)
    backup_before = _tree_bytes(backup_export_root)
    journal_before = journal_path.read_bytes()

    with pytest.raises(RegistryValidationError) as refusal:
        publish_validated_generated_export_tree(
            context=context,
            joined=joined,
            semantic_map=semantic_map,
            rendered=rendered,
            render_profile=profile,
            render_profile_source_evidence=evidence,
        )

    _require_the_drift_was_reached(refusal.value, drift)
    assert not candidate_export_root.exists()
    assert _tree_bytes(context.target_export_root) == target_before
    assert _tree_bytes(backup_export_root) == backup_before
    assert journal_path.read_bytes() == journal_before


def test_internal_json_provenance_is_required_but_ignored_by_toml_loader(m130_inspection_snapshot, tmp_path) -> None:
    """The loader accepts the generated tree while validation refuses a missing internal attestation."""
    context, joined, semantic_map, rendered, candidate_export_root = _publication_inputs(
        tmp_path,
        m130_inspection_snapshot,
        existing_export=False,
    )
    loaded = load_modelo_directory(candidate_export_root.parent.parent.parent)
    assert loaded.revisions[_ISOLATED_TREE.revision].export_layouts == (rendered.layout,)
    (candidate_export_root / EXPORT_FRAGMENT_PROVENANCE_FILENAME).unlink()

    with pytest.raises(RegistryValidationError, match="provenance manifest"):
        publish_validated_generated_export_tree(
            context=context,
            joined=joined,
            semantic_map=semantic_map,
            rendered=rendered,
            render_profile=_isolated_render_profile()[0],
            render_profile_source_evidence=_isolated_render_profile()[1],
        )


def test_publication_refuses_stale_sibling_provenance_before_cutover(m130_inspection_snapshot, tmp_path) -> None:
    """The old outside-export manifest surface cannot silently survive a generated target."""
    context, joined, semantic_map, rendered, _candidate_export_root = _publication_inputs(
        tmp_path,
        m130_inspection_snapshot,
        existing_export=True,
    )
    stale = context.target_export_root.parent / "export.provenance.json"
    stale.write_text("{}\n", encoding="utf-8")

    with pytest.raises(RegistryValidationError, match="stale sibling provenance"):
        publish_validated_generated_export_tree(
            context=context,
            joined=joined,
            semantic_map=semantic_map,
            rendered=rendered,
            render_profile=_isolated_render_profile()[0],
            render_profile_source_evidence=_isolated_render_profile()[1],
        )


def test_publication_module_has_no_old_tree_read_merge_or_copy_surface() -> None:
    """Legacy exports cannot return as readers, mergers, copies, or fallback APIs."""
    module = ast.parse(inspect.getsource(_tree_publication))
    referenced_names = {node.id for node in ast.walk(module) if isinstance(node, ast.Name)}
    attribute_names = {node.attr for node in ast.walk(module) if isinstance(node, ast.Attribute)}

    assert not {
        "copytree",
        "copy2",
        "read_text",
        "bundled_authority",
        "resolve_export_layout",
    }.intersection(referenced_names)
    assert not {"copytree", "copy2", "read_text"}.intersection(attribute_names)
    publish_source = inspect.getsource(_tree_publication.publish_validated_generated_export_tree)
    assert "_verify_generated_export_package(target_export_root)" not in publish_source


def test_derived_render_inputs_supply_every_value_publication_needs_from_the_authority() -> None:
    """The derivation and the publication limb still meet.

    Publication takes six values. Two are publication's own concern - where the
    tree goes and what was rendered - and the other four describe the revision
    and must come from the validated authority. Those four had no name until
    recently: they were assembled inside the render comparison, so anything
    wanting them had to call a comparison it did not want or derive them a second
    time.

    Naming them is only half the fix. This is the half that keeps them meeting: if
    publication grows a seventh parameter describing the revision, or the derived
    inputs stop carrying one, the seam breaks silently and the next caller writes
    the second derivation after all.
    """
    publication_parameters = set(inspect.signature(publish_validated_generated_export_tree).parameters)
    derived_fields = set(RevisionRenderInputs.__dataclass_fields__)

    publication_owned = {"context", "rendered"}
    revision_described = publication_parameters - publication_owned

    assert revision_described <= derived_fields, (
        "publication needs these values from the authority and the derived inputs do not carry them, "
        f"so a caller would have to derive them again: {sorted(revision_described - derived_fields)}"
    )


def test_the_seam_check_is_reading_a_real_signature() -> None:
    """A signature read as empty would make the containment above vacuously true."""
    publication_parameters = set(inspect.signature(publish_validated_generated_export_tree).parameters)

    assert {"context", "rendered"} <= publication_parameters
    assert len(publication_parameters) >= 6
    assert len(RevisionRenderInputs.__dataclass_fields__) >= 4
