"""Generated environment-overrides reference for the Cadrumo settings surface.

Introspects the live :class:`cadrumo.core.config.Settings` model — the single
declarative home of every environment override the application supports — and
renders ``docs/reference/environment-overrides.md``. The page is generated in
full; hand edits are overwritten on the next run, mirroring the
``generated-reference-is-cli-owned`` discipline the CLI reference follows.

Environment overrides are advanced deployment and development configuration.
User-facing guides must not cite them (the CLI is fully operable through
prompts, flags, and config commands); this page is the one sanctioned home,
and the drift gate in :mod:`dev.docs.tests.test_env_reference` keeps it —
plus the hand-annotated ``env/.env.example`` template — in lock-step with the
:class:`~cadrumo.core.config.Settings` fields.

Defaults are rendered only for plain scalars. Machine-derived values (paths
resolved from the project root or storage root) and secrets are shown as
``(derived)`` and ``(secret)`` so the generated bytes are identical on every
machine and the freshness gate cannot flake.
"""

from __future__ import annotations

import argparse
import os
import sys
from enum import Enum
from pathlib import Path
from typing import TYPE_CHECKING, Final

from pydantic import SecretStr
from pydantic_core import PydanticUndefined

from cadrumo.core.external_constants import OutputLanguage

from .._paths import REPO_ROOT, UTF_8
from ._locale_chrome import docs_chrome
from .build import docs_build_language

_UTF_8: Final[str] = UTF_8

if TYPE_CHECKING:
    from pydantic.fields import FieldInfo

_HEADER = """<!-- GENERATED FILE - DO NOT EDIT.
Regenerate with: uv run --no-sync python -m dev.docs.env_reference
Source of truth: cadrumo.core.config.Settings -->

# Environment overrides

This page covers every environment variable the application reads, generated
from the live settings model. Environment overrides are advanced deployment
and development configuration: every user workflow works without them through
prompts, command flags, and `aeat config` commands. Set an override only when
you administer a deployment and know why the default does not fit.

An annotated template with the same variables lives at `env/.env.example` in
the repository. The application itself reads only the process environment;
`env/.env` is not a production source. For local development and the test
suite, the repository's `conftest.py` bridges `env/.env` into the process
environment before tests run, filling only variables not already set; a
value already present in your shell always wins.

| Variable | Type | Default | What it controls |
| --- | --- | --- | --- |
"""


def _default_cell(field: FieldInfo, language: OutputLanguage) -> str:
    """Render a machine-independent default cell for one settings field."""
    annotation = field.annotation
    if annotation is SecretStr or "SecretStr" in str(annotation):
        return "(secret)"
    default = field.default
    if default is PydanticUndefined or field.default_factory is not None:
        return "(derived)"
    if default is None:
        return docs_chrome("docs.cli.env.default_unset", language)
    if isinstance(default, bool):
        return "`true`" if default else "`false`"
    if isinstance(default, Enum):
        return f"`{default.value}`"
    if isinstance(default, (int, float)):
        return f"`{default}`"
    if isinstance(default, str):
        return f"`{default}`" if default else docs_chrome("docs.cli.env.default_empty", language)
    if isinstance(default, Path):
        return "(derived)"
    return "(derived)"


def _type_cell(field: FieldInfo) -> str:
    """Render a short human type name for one settings field."""
    annotation = field.annotation
    name = getattr(annotation, "__name__", None) or str(annotation)
    name = name.replace(" | None", "")
    # Keep only the leaf class name; module paths are internal detail.
    return name.split(".")[-1].strip()


def _escape(text: str) -> str:
    """Flatten a field description onto one markdown table cell."""
    return " ".join(text.split()).replace("|", "\\|")


def render_environment_reference() -> str:
    """Render the full generated page from the live settings model."""
    from cadrumo.core.config import Settings

    # Keyed on the model's own environment inventory rather than every field:
    # a field whose environment source has been severed is still a field, but
    # no variable reaches it, so an environment reference must not list it.
    language = docs_build_language(os.environ)
    environment_names = Settings.env_var_names()
    rows = []
    for name, field in sorted(Settings.model_fields.items()):
        if name.upper() not in environment_names:
            continue
        description = field.description or ""
        rows.append(
            f"| `{name.upper()}` | {_type_cell(field)} | {_default_cell(field, language)} | {_escape(description)} |",
        )
    footer = "\n" + docs_chrome("docs.cli.env.secrets_note", language) + "\n"
    return _HEADER + "\n".join(rows) + "\n" + footer


def target_path(repo_root: Path | None = None) -> Path:
    """Return the generated page's path under ``docs/reference``."""
    root = repo_root or REPO_ROOT
    return root / "docs" / "reference" / "environment-overrides.md"


def main(argv: list[str] | None = None) -> int:
    """Write the generated page, or verify freshness with ``--check``."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 when the on-disk page differs from fresh output.",
    )
    args = parser.parse_args(argv)
    path = target_path()
    fresh = render_environment_reference()
    if args.check:
        on_disk = path.read_bytes() if path.is_file() else b""
        if on_disk != fresh.encode(_UTF_8):
            print(f"DRIFT: {path} is stale; regenerate with python -m dev.docs.env_reference", file=sys.stderr)
            return 1
        print(f"OK: {path} is fresh.")
        return 0
    path.write_text(fresh, encoding=_UTF_8, newline="\n")
    print(f"Wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
