"""Error code registry for aeat.adapters."""

from aeat.core.errors._registry import ErrorCategory, ErrorCode

_DECLARED_ERROR_CODES: tuple[tuple[str, ErrorCode], ...] = (
    (
        "aeat.adapters.inbound.pdf._scrub.ScrubError",
        ErrorCode(
            code="ERROR_PDF_IMPORT_SCRUB",
            category=ErrorCategory.ERROR,
            default_message_es="Error de limpieza.",
            default_message_en="Raised when scrubbing cannot produce a safe output.",
            default_message_hu="Tisztitas hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.aeat.auth._authenticator._PersistedSessionInvalidError",
        ErrorCode(
            code="AUTH_AUTH_AUTHENTICATOR_PERSISTED_SESSION_INVALID",
            category=ErrorCategory.AUTH,
            default_message_es="La sesion persistida de AEAT no es valida.",
            default_message_en="Raised when a persisted AEAT browser session cannot be trusted.",
            default_message_hu="A tarolt AEAT munkamenet nem megbizhato.",
            default_suggestion=None,
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.aeat.auth._clave_movil.ClaveMovilApprovalTimeoutError",
        ErrorCode(
            code="AUTH_AUTH_CLAVE_MOVIL_CLAVE_MOVIL_APPROVAL_TIMEOUT",
            category=ErrorCategory.AUTH,
            default_message_es="La aprobacion de Clave Movil agoto el tiempo de espera.",
            default_message_en="Raised when the operator does not approve the Cl@ve push within the time window.",
            default_message_hu="Clave movil jovahagyas idotullepessel vegzodott.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.aeat.auth._clave_movil.ClaveMovilConfigurationError",
        ErrorCode(
            code="AUTH_AUTH_CLAVE_MOVIL_CLAVE_MOVIL_CONFIGURATION",
            category=ErrorCategory.AUTH,
            default_message_es="Clave movil no esta configurado correctamente.",
            default_message_en="Raised when required Cl@ve M\xf3vil settings are missing or malformed.",
            default_message_hu="Clave movil nincs megfeleloen beallitva.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.aeat.auth.certificate.AeatLoginAssertionError",
        ErrorCode(
            code="AUTH_AUTH_CERTIFICATE_AEAT_LOGIN_ASSERTION",
            category=ErrorCategory.AUTH,
            default_message_es="No se pudo completar la verificacion posterior al inicio de sesion de AEAT.",
            default_message_en="Raised when a post-auth verification attempt cannot be produced.",
            default_message_hu="Az AEAT bejelentkezes utani ellenorzes nem keszult el.",
            default_suggestion="aeat setup auth login",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.aeat.auth.certificate.AeatSessionExpiredError",
        ErrorCode(
            code="AUTH_AUTH_CERTIFICATE_AEAT_SESSION_EXPIRED",
            category=ErrorCategory.AUTH,
            default_message_es="La sesi\xf3n autenticada de AEAT ha caducado.",
            default_message_en="The authenticated AEAT session expired.",
            default_message_hu="Az AEAT hiteles\xedtett munkamenet lej\xe1rt.",
            default_suggestion="aeat setup auth login",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.aeat.auth.certificate.CertificateError",
        ErrorCode(
            code="AUTH_AUTH_CERTIFICATE",
            category=ErrorCategory.AUTH,
            default_message_es="Error de certificado.",
            default_message_en="Base class for every certificate-auth domain error.",
            default_message_hu="Tanusitvany hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.aeat.auth.certificate.CertificateExpiredError",
        ErrorCode(
            code="AUTH_AUTH_CERTIFICATE_EXPIRED",
            category=ErrorCategory.AUTH,
            default_message_es="Certificado caducado.",
            default_message_en="The loaded certificate is already expired.",
            default_message_hu="Tanusitvany lejart.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.aeat.auth.certificate.CertificateHandshakeError",
        ErrorCode(
            code="AUTH_AUTH_CERTIFICATE_HANDSHAKE",
            category=ErrorCategory.AUTH,
            default_message_es="Error de certificado handshake.",
            default_message_en="Raised when handshake input is structurally invalid.",
            default_message_hu="Tanusitvany kezfogas hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.aeat.auth.certificate.CertificateLoadError",
        ErrorCode(
            code="AUTH_AUTH_CERTIFICATE_LOAD",
            category=ErrorCategory.AUTH,
            default_message_es="No se pudo cargar certificado.",
            default_message_en="Raised when PKCS#12 bytes cannot be parsed at all.",
            default_message_hu="Tanusitvany betoltese sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.aeat.auth.certificate.CertificateNifParseError",
        ErrorCode(
            code="AUTH_AUTH_CERTIFICATE_NIF_PARSE",
            category=ErrorCategory.AUTH,
            default_message_es="No se pudo analizar certificado nif.",
            default_message_en="Raised when no NIF / NIE can be parsed from a certificate subject.",
            default_message_hu="Tanusitvany nif feldolgozasa sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.aeat.auth.certificate.CertificatePasswordError",
        ErrorCode(
            code="AUTH_AUTH_CERTIFICATE_PASSWORD",
            category=ErrorCategory.AUTH,
            default_message_es="Error de contrasena del certificado.",
            default_message_en="Raised when the passphrase env var is missing/empty or wrong.",
            default_message_hu="Tanusitvany jelszo hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.aeat.auth.certificate.CertificatePreExpiryError",
        ErrorCode(
            code="AUTH_AUTH_CERTIFICATE_PRE_EXPIRY",
            category=ErrorCategory.AUTH,
            default_message_es="Error de certificado pre expiry.",
            default_message_en="Raised when a certificate is within the pre-expiry danger window.",
            default_message_hu="Tanusitvany elo expiry hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.inbound.borrador._errors.ArtefactNotRecognisedError",
        ErrorCode(
            code="ERROR_BORRADOR_ARTEFACT_NOT_RECOGNISED",
            category=ErrorCategory.ERROR,
            default_message_es="El artefacto del PDF no coincide con un formato conocido.",
            default_message_en="Raised when the PDF does not match any known Modelo 100 artefact shape.",
            default_message_hu="A PDF artefaktuma nem egyezik ismert formatummal.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.inbound.borrador._errors.BorradorParseError",
        ErrorCode(
            code="FAIL_BORRADOR_PARSE",
            category=ErrorCategory.FAIL,
            default_message_es="No se pudo analizar borrador.",
            default_message_en="The Modelo 100 PDF could not be parsed into a draft filing.",
            default_message_hu="Tervezet feldolgozasa sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.aeat.browser.session.BrowserError",
        ErrorCode(
            code="FAIL_BROWSER_SESSION_BROWSER",
            category=ErrorCategory.FAIL,
            default_message_es="Error de navegador.",
            default_message_en="Base class for browser-related errors.",
            default_message_hu="Bongeszo hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.aeat.browser.evasion.BrowserEvasionError",
        ErrorCode(
            code="FAIL_BROWSER_EVASION",
            category=ErrorCategory.FAIL,
            default_message_es="No se pudo preparar la evasion del navegador.",
            default_message_en="Browser evasion setup could not be applied.",
            default_message_hu="A bongeszo elkerules beallitasa sikertelen.",
            default_suggestion="aeat setup status",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.inbound.declaracion._errors.DeclaracionParseError",
        ErrorCode(
            code="FAIL_DECLARACION_PARSE",
            category=ErrorCategory.FAIL,
            default_message_es="No se pudo analizar declaracion.",
            default_message_en="The PDF could not be parsed into a declaration filing.",
            default_message_hu="Bevallas feldolgozasa sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.inbound.declaracion._errors.NoExtractorRegisteredError",
        ErrorCode(
            code="ERROR_DECLARACION_NO_EXTRACTOR_REGISTERED",
            category=ErrorCategory.ERROR,
            default_message_es="No hay un extractor registrado para la plantilla detectada.",
            default_message_en="Raised when no concrete extractor exists for the detected template.",
            default_message_hu="A felismert sablonhoz nincs regisztralt kinyero.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.inbound.declaracion._errors.TemplateNotDetectedError",
        ErrorCode(
            code="ERROR_DECLARACION_TEMPLATE_NOT_DETECTED",
            category=ErrorCategory.ERROR,
            default_message_es="No se pudo detectar la plantilla del PDF.",
            default_message_en="The declaration template could not be identified from the PDF.",
            default_message_hu="A bevallasi sablon nem volt felismerheto a PDF-bol.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.inbound.financial.providers._base.FinancialProviderError",
        ErrorCode(
            code="ERROR_FINANCIAL_PROVIDERS_BASE_FINANCIAL_PROVIDER",
            category=ErrorCategory.ERROR,
            default_message_es="Error de financiero proveedor.",
            default_message_en="Base error raised by financial-ingest providers.",
            default_message_hu="Penzugyi szolgaltato hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.inbound.financial.providers._base.InvalidFinancialSourceError",
        ErrorCode(
            code="ERROR_FINANCIAL_PROVIDERS_BASE_INVALID_FINANCIAL_SOURCE",
            category=ErrorCategory.ERROR,
            default_message_es="Error de invalid financiero origen.",
            default_message_en="Raised when a source document is unreadable or structurally invalid.",
            default_message_hu="Invalid penzugyi forras hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.inbound.financial.providers._base.UnsupportedFinancialSourceError",
        ErrorCode(
            code="ERROR_FINANCIAL_PROVIDERS_BASE_UNSUPPORTED_FINANCIAL_SOURCE",
            category=ErrorCategory.ERROR,
            default_message_es="No hay un proveedor compatible para el origen financiero indicado.",
            default_message_en="Raised when no provider can interpret a source document.",
            default_message_hu="A megadott penzugyi forrashoz nincs tamogatott szolgaltato.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.llm._errors.LLMCacheError",
        ErrorCode(
            code="FAIL_LLM_L_M_CACHE",
            category=ErrorCategory.FAIL,
            default_message_es="Error de cache del cliente LLM.",
            default_message_en="Raised when a cache entry cannot be read, written, or parsed.",
            default_message_hu="Az LLM gyorsitotar hibas.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.llm._errors.LLMConfigError",
        ErrorCode(
            code="FAIL_LLM_L_M_CONFIG",
            category=ErrorCategory.FAIL,
            default_message_es="Error de configuracion del cliente LLM.",
            default_message_en="Raised when the LLM client configuration is invalid or incomplete.",
            default_message_hu="Az LLM kliens beallitasa hibas vagy hianyos.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.llm._errors.LLMError",
        ErrorCode(
            code="FAIL_LLM_L_M",
            category=ErrorCategory.FAIL,
            default_message_es="Error del subsistema LLM.",
            default_message_en="Base exception for LLM package failures.",
            default_message_hu="LLM alrendszerhiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.llm._errors.LLMProviderError",
        ErrorCode(
            code="FAIL_LLM_L_M_PROVIDER",
            category=ErrorCategory.FAIL,
            default_message_es="Error del proveedor LLM.",
            default_message_en="Raised when a provider returns an unrecoverable error.",
            default_message_hu="Az LLM szolgaltato helyrehozhatatlan hibaval valaszolt.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.llm._errors.LLMRateLimitError",
        ErrorCode(
            code="FAIL_LLM_L_M_RATE_LIMIT",
            category=ErrorCategory.FAIL,
            default_message_es="El proveedor LLM rechazo la solicitud por limite de uso.",
            default_message_en="Raised when a provider rejects a request because of rate limits.",
            default_message_hu="Az LLM szolgaltato sebessegkorlat miatt utasitotta el a kerest.",
            default_suggestion=None,
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.aeat.sede._errors.ExpedienteNotFoundError",
        ErrorCode(
            code="ERROR_SEDE_EXPEDIENTE_NOT_FOUND",
            category=ErrorCategory.ERROR,
            default_message_es="No se encontro expediente.",
            default_message_en="Raised when no expediente matches the requested filter.",
            default_message_hu="Ugy nem talalhato.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.aeat.sede._errors.JustificanteFetchError",
        ErrorCode(
            code="FAIL_SEDE_JUSTIFICANTE_FETCH",
            category=ErrorCategory.FAIL,
            default_message_es="Error de justificante descarga.",
            default_message_en="Raised when the CSV-keyed PDF download fails or is malformed.",
            default_message_hu="Igazolas letoltes hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.aeat.sede._errors.SedeError",
        ErrorCode(
            code="ERROR_SEDE",
            category=ErrorCategory.ERROR,
            default_message_es="Error de sede.",
            default_message_en="Base class for post-auth AEAT sede errors.",
            default_message_hu="Sede hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.aeat.sede._errors.SedeNavigationError",
        ErrorCode(
            code="ERROR_SEDE_NAVIGATION",
            category=ErrorCategory.ERROR,
            default_message_es="Error de sede navegacion.",
            default_message_en="Raised when a navigation step fails (goto, click, wait).",
            default_message_hu="Sede navigacio hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.outbound.aeat.sede._errors.SedeParseError",
        ErrorCode(
            code="FAIL_SEDE_PARSE",
            category=ErrorCategory.FAIL,
            default_message_es="No se pudo analizar sede.",
            default_message_en="Raised when the captured HTML cannot be parsed to a record.",
            default_message_hu="Sede feldolgozasa sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.inbound.sanitizer._errors.AlreadySanitizedError",
        ErrorCode(
            code="REFUSED_SANITIZER_ALREADY_SANITIZED",
            category=ErrorCategory.REFUSED,
            default_message_es="El PDF ya esta sanitizado.",
            default_message_en=(
                "Raised when the source SHA already lives in SANITIZED_SHAS; bypass with --allow-already-sanitized."
            ),
            default_message_hu="A PDF mar sanitizalt.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.inbound.sanitizer._errors.SanitizationError",
        ErrorCode(
            code="ERROR_SANITIZER",
            category=ErrorCategory.ERROR,
            default_message_es="Error del sanitizador.",
            default_message_en="Base class for the AEAT PDF sanitiser failures.",
            default_message_hu="Sanitizalo hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.inbound.sanitizer._errors.SanitizerSourceParseError",
        ErrorCode(
            code="FAIL_SANITIZER_SOURCE_PARSE",
            category=ErrorCategory.FAIL,
            default_message_es="No se pudo abrir el PDF de origen.",
            default_message_en="Raised when pikepdf cannot open the source PDF (corrupt or password-protected).",
            default_message_hu="Forras PDF megnyitas sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.inbound.sanitizer._errors.SignaturePresentError",
        ErrorCode(
            code="REFUSED_SANITIZER_SIGNATURE_PRESENT",
            category=ErrorCategory.REFUSED,
            default_message_es="El PDF tiene una firma digital y no se puede sanitizar.",
            default_message_en=(
                "Raised when the source PDF carries a digital signature; sanitisation would invalidate it."
            ),
            default_message_hu="A PDF digitalis alairast tartalmaz.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.inbound.sanitizer._errors.UnknownSurfaceError",
        ErrorCode(
            code="ERROR_SANITIZER_UNKNOWN_SURFACE",
            category=ErrorCategory.ERROR,
            default_message_es="Superficie del sanitizador desconocida.",
            default_message_en=(
                "Raised when a TokenMap entry references a surface category the pipeline does not handle."
            ),
            default_message_hu="Ismeretlen sanitizalo felulet.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.BlobIntegrityError",
        ErrorCode(
            code="INTEGRITY_STORAGE_BLOB",
            category=ErrorCategory.INTEGRITY,
            default_message_es="Integridad del blob comprometida.",
            default_message_en="A blob's on-disk SHA-256 disagrees with its manifest.",
            default_message_hu="Blob integritasa serult.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.BlobNotFoundError",
        ErrorCode(
            code="FAIL_STORAGE_BLOB_NOT_FOUND",
            category=ErrorCategory.FAIL,
            default_message_es="Blob no encontrado.",
            default_message_en="No blob exists at the requested reference.",
            default_message_hu="A blob nem talalhato.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.ClassificationError",
        ErrorCode(
            code="INTEGRITY_STORAGE_CLASSIFICATION",
            category=ErrorCategory.INTEGRITY,
            default_message_es="Clase de sensibilidad incompatible con el repositorio.",
            default_message_en="The declared sensitivity class is incompatible with this repository.",
            default_message_hu="Erzekenysegi osztaly nem kompatibilis.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.DecryptionError",
        ErrorCode(
            code="INTEGRITY_STORAGE_DECRYPTION",
            category=ErrorCategory.INTEGRITY,
            default_message_es="Error al descifrar el registro almacenado.",
            default_message_en="AEAD decryption failed (tag mismatch or malformed ciphertext).",
            default_message_hu="A tarolt rekord visszafejtese sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.EncryptionError",
        ErrorCode(
            code="INTEGRITY_STORAGE_ENCRYPTION",
            category=ErrorCategory.INTEGRITY,
            default_message_es="Error de cifrado de almacenamiento.",
            default_message_en="Base class for AEAD encryption / decryption failures.",
            default_message_hu="Titkositasi hiba a tarolasban.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.EnvelopeVersionError",
        ErrorCode(
            code="INTEGRITY_STORAGE_ENVELOPE_VERSION",
            category=ErrorCategory.INTEGRITY,
            default_message_es="Version de envoltura incompatible.",
            default_message_en="The on-disk envelope schema version is incompatible with this consumer.",
            default_message_hu="A boriték verzioja nem kompatibilis.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.KeyDerivationError",
        ErrorCode(
            code="INTEGRITY_STORAGE_KEY_DERIVATION",
            category=ErrorCategory.INTEGRITY,
            default_message_es="Error al derivar la clave de cifrado.",
            default_message_en="Key derivation (HKDF or scrypt) failed.",
            default_message_hu="A kulcsszarmaztatas sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.KeyringUnavailableError",
        ErrorCode(
            code="AUTH_STORAGE_KEYRING_UNAVAILABLE",
            category=ErrorCategory.AUTH,
            default_message_es="El llavero del sistema operativo no esta disponible.",
            default_message_en="The OS keychain backend is unusable; no master key could be retrieved.",
            default_message_hu="Az operacios rendszer kulcskezeloje nem elerheto.",
            default_suggestion="aeat setup status",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.MasterKeyUnavailableError",
        ErrorCode(
            code="AUTH_STORAGE_MASTER_KEY_UNAVAILABLE",
            category=ErrorCategory.AUTH,
            default_message_es="No se puede acceder a la clave maestra de almacenamiento.",
            default_message_en="No master key could be acquired from the configured backend.",
            default_message_hu="Nem sikerult mester kulcsot beszerezni.",
            default_suggestion="aeat setup status",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.MasterKeyKdfVersionError",
        ErrorCode(
            code="AUTH_STORAGE_MASTER_KEY_KDF_VERSION",
            category=ErrorCategory.AUTH,
            default_message_es=(
                "El archivo master.kdf usa una version de KDF que esta build no admite; ejecute la migracion."
            ),
            default_message_en=("master.kdf declares a KDF version this build cannot consume; run the migration tool."),
            default_message_hu=("A master.kdf egy nem tamogatott KDF-verziot deklaral; futtassa a migracios eszkozt."),
            default_suggestion="aeat setup status",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.MasterKeyKeychainLockedError",
        ErrorCode(
            code="AUTH_STORAGE_MASTER_KEY_KEYCHAIN_LOCKED",
            category=ErrorCategory.AUTH,
            default_message_es=("El llavero del sistema esta bloqueado; desbloquee el llavero y reintente."),
            default_message_en=("OS keychain is locked; unlock it (Touch ID / Hello / desktop-wallet) and retry."),
            default_message_hu=("Az operacios rendszer kulcstartoja zarolva; oldja fel es probalja ujra."),
            # No CLI command can unlock the OS keychain on the operator's
            # behalf; the runbook hint lives in the message itself.
            default_suggestion=None,
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.MasterKeyPassphraseMismatchError",
        ErrorCode(
            code="AUTH_STORAGE_MASTER_KEY_PASSPHRASE_MISMATCH",
            category=ErrorCategory.AUTH,
            default_message_es=("La frase de paso no desbloqueo la clave maestra; verifique e intente de nuevo."),
            default_message_en=("Passphrase did not unlock the master key; verify and retry."),
            default_message_hu=("A jelszo nem oldotta fel a mester kulcsot; ellenorizze es probalja ujra."),
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.MasterKeyMaterialMissingError",
        ErrorCode(
            code="AUTH_STORAGE_MASTER_KEY_MATERIAL_MISSING",
            category=ErrorCategory.AUTH,
            default_message_es=("No existe material de clave maestra; ejecute la provision."),
            default_message_en=("No master-key material exists; run the security-provisioning command."),
            default_message_hu=("Nincs mester kulcs anyag; futtassa a biztonsagi provisioning parancsot."),
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.UnsecuredModeRefusedError",
        ErrorCode(
            code="REFUSED_STORAGE_UNSECURED_MODE",
            category=ErrorCategory.REFUSED,
            default_message_es=(
                "Modo no cifrado rechazado: requiere AEAT_ALLOW_UNENCRYPTED=1 y es incompatible con un NIF real."
            ),
            default_message_en=(
                "Unsecured mode refused: requires AEAT_ALLOW_UNENCRYPTED=1 and is incompatible with a real NIF."
            ),
            default_message_hu=(
                "Nem biztonsagos mod elutasitva: AEAT_ALLOW_UNENCRYPTED=1 szukseges es nem hasznalhato valodi NIF-fel."
            ),
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.MigrationError",
        ErrorCode(
            code="FAIL_STORAGE_MIGRATION",
            category=ErrorCategory.FAIL,
            default_message_es="Error de migracion.",
            default_message_en="Raised when an Alembic migration operation fails.",
            default_message_hu="Migracio hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.NonceCollisionError",
        ErrorCode(
            code="INTEGRITY_STORAGE_NONCE_COLLISION",
            category=ErrorCategory.INTEGRITY,
            default_message_es="Colision de nonce detectada.",
            default_message_en="Defensive AEAD nonce-uniqueness invariant violation.",
            default_message_hu="Nonce utkozes eszlelve.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.PathContainmentError",
        ErrorCode(
            code="INTEGRITY_STORAGE_PATH_CONTAINMENT",
            category=ErrorCategory.INTEGRITY,
            default_message_es="La ruta computada se sale de su raiz configurada.",
            default_message_en="A computed path escapes its configured root directory.",
            default_message_hu="A szamitott utvonal kilep a konfiguralt gyokerbol.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.PersistenceError",
        ErrorCode(
            code="FAIL_STORAGE_PERSISTENCE",
            category=ErrorCategory.FAIL,
            default_message_es="Error de persistencia segura.",
            default_message_en="Base class for the secure-persistence-foundation error tree.",
            default_message_hu="Biztonsagos tarolasi hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.RepositoryError",
        ErrorCode(
            code="FAIL_STORAGE_REPOSITORY",
            category=ErrorCategory.FAIL,
            default_message_es="Error de repositorio.",
            default_message_en="A repository operation failed due to lookup, integrity, or persistence errors.",
            default_message_hu="Tarolo hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.RetentionPolicyError",
        ErrorCode(
            code="INTEGRITY_STORAGE_RETENTION_POLICY",
            category=ErrorCategory.INTEGRITY,
            default_message_es="Politica de retencion violada por el registro.",
            default_message_en="A persisted record's retention metadata violates its classification policy.",
            default_message_hu="A megorzesi szabalyzat sertese.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.SecretAlreadyExistsError",
        ErrorCode(
            code="REFUSED_STORAGE_SECRET_ALREADY_EXISTS",
            category=ErrorCategory.REFUSED,
            default_message_es="Ya existe un secreto con esa clave.",
            default_message_en="A secret already exists for the given key; pass overwrite=True to replace it.",
            default_message_hu="Mar letezik a titkos kulcs.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.SecretNotFoundError",
        ErrorCode(
            code="FAIL_STORAGE_SECRET_NOT_FOUND",
            category=ErrorCategory.FAIL,
            default_message_es="Secreto no encontrado.",
            default_message_en="No secret exists at the requested key.",
            default_message_hu="A titkos kulcs nem talalhato.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.SecretStoreError",
        ErrorCode(
            code="FAIL_STORAGE_SECRET_STORE",
            category=ErrorCategory.FAIL,
            default_message_es="Error del almacen de secretos.",
            default_message_en="Base class for secret-store I/O failures.",
            default_message_hu="Titokkezelo hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.adapters.persistence.storage.errors.StorageError",
        ErrorCode(
            code="FAIL_STORAGE",
            category=ErrorCategory.FAIL,
            default_message_es="Error de almacenamiento.",
            default_message_en="Base class for storage-related errors.",
            default_message_hu="Tarolas hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
)
