"""Error code registry for aeat.application."""

from aeat.core.errors._registry import ErrorCategory, ErrorCode

_DECLARED_ERROR_CODES: tuple[tuple[str, ErrorCode], ...] = (
    (
        "aeat.application.aggregation._errors.AggregationError",
        ErrorCode(
            code="ERROR_FINANCIAL_AGGREGATION",
            category=ErrorCategory.ERROR,
            default_message_es="Error de agregacion financiera.",
            default_message_en="Base class for financial aggregation failures.",
            default_message_hu="Penzugyi osszesitesi hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.aggregation._errors.AggregationPeriodError",
        ErrorCode(
            code="ERROR_FINANCIAL_AGGREGATION_PERIOD",
            category=ErrorCategory.ERROR,
            default_message_es="El periodo de agregacion no es valido.",
            default_message_en="The aggregation period is invalid or ambiguous.",
            default_message_hu="Az osszesitesi idoszak ervenytelen vagy ketertelmu.",
            default_suggestion="aeat app declaration calculate --modelo 130 --period 2025-Q1",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.aggregation._errors.AggregationUnsupportedModeloError",
        ErrorCode(
            code="REFUSED_FINANCIAL_AGGREGATION_UNSUPPORTED_MODELO",
            category=ErrorCategory.REFUSED,
            default_message_es="Este modelo no admite agregacion financiera.",
            default_message_en="This modelo does not support financial aggregation.",
            default_message_hu="Ez a nyomtatvany nem tamogat penzugyi osszesitest.",
            default_suggestion="aeat app declaration calculate --modelo 130 --period 2025-Q1",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.aggregation._errors.AggregationMissingClassificationError",
        ErrorCode(
            code="REFUSED_FINANCIAL_AGGREGATION_MISSING_CLASSIFICATION",
            category=ErrorCategory.REFUSED,
            default_message_es="Faltan clasificaciones de transacciones.",
            default_message_en="One or more transactions still need classification.",
            default_message_hu="Egy vagy tobb tranzakcio meg besorolasra var.",
            default_suggestion="aeat app ledger review --filter status=pending",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.aggregation._errors.AggregationCategoryCoverageError",
        ErrorCode(
            code="REFUSED_FINANCIAL_AGGREGATION_CATEGORY_COVERAGE",
            category=ErrorCategory.REFUSED,
            default_message_es="Una transaccion no tiene cobertura de categoria fiscal.",
            default_message_en="A transaction has no fiscal category coverage.",
            default_message_hu="Egy tranzakciohoz nincs adozasi kategoria-lefedettseg.",
            default_suggestion="aeat app ledger review",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.aggregation._errors.AggregationCasillaMappingError",
        ErrorCode(
            code="REFUSED_FINANCIAL_AGGREGATION_CASILLA_MAPPING",
            category=ErrorCategory.REFUSED,
            default_message_es="No hay mapeo de casilla util para la agregacion.",
            default_message_en="No usable casilla mapping exists for the aggregation.",
            default_message_hu="Nincs hasznalhato casilla-lekepezes az osszesiteshez.",
            default_suggestion="aeat app ledger review",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.review._errors.ReviewError",
        ErrorCode(
            code="ERROR_REVIEW",
            category=ErrorCategory.ERROR,
            default_message_es="Error de revision.",
            default_message_en="Base class for review-related errors.",
            default_message_hu="Ellenorzes hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.review._errors.ReviewKindReservedError",
        ErrorCode(
            code="REFUSED_REVIEW_KIND_RESERVED",
            category=ErrorCategory.REFUSED,
            default_message_es="El tipo de revisi\xf3n solicitado est\xe1 reservado.",
            default_message_en="The requested review kind is reserved.",
            default_message_hu="A k\xe9rt ellen\u0151rz\xe9si t\xedpus fenntartott.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.review._errors.ReviewSourceLoadError",
        ErrorCode(
            code="FAIL_REVIEW_SOURCE_LOAD",
            category=ErrorCategory.FAIL,
            default_message_es="No se pudo cargar revision origen.",
            default_message_en="Raised when a source disk file is present but cannot be parsed.",
            default_message_hu="Ellenorzes forras betoltese sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.review._errors.FilterParseError",
        ErrorCode(
            code="REFUSED_REVIEW_FILTER_PARSE",
            category=ErrorCategory.REFUSED,
            default_message_es="Error al procesar el filtro de revision.",
            default_message_en="Raised when a review filter token cannot be parsed.",
            default_message_hu="Ellenorzes szuro hiba.",
            default_suggestion="aeat app ledger review --filter status=pending",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.review._errors.EditParseError",
        ErrorCode(
            code="REFUSED_REVIEW_EDIT_PARSE",
            category=ErrorCategory.REFUSED,
            default_message_es="Error al procesar la edicion de revision.",
            default_message_en="Raised when a review edit token cannot be parsed.",
            default_message_hu="Ellenorzes szerkesztes hiba.",
            default_suggestion="aeat app ledger edit --id ID --set category=V-01 --reason reason",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.setup._errors.SetupAbortedError",
        ErrorCode(
            code="REFUSED_SETUP_ABORTED",
            category=ErrorCategory.REFUSED,
            default_message_es="La configuracion fue cancelada por el usuario.",
            default_message_en="Raised when the user explicitly aborts the wizard.",
            default_message_hu="A beallitasi varazslo megszakadt.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.setup._errors.SetupAnswersError",
        ErrorCode(
            code="ERROR_SETUP_ANSWERS",
            category=ErrorCategory.ERROR,
            default_message_es="Error de configuracion respuestas.",
            default_message_en="The setup answers payload could not be loaded or validated.",
            default_message_hu="Beallitas valaszok hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.setup._errors.SetupError",
        ErrorCode(
            code="ERROR_SETUP",
            category=ErrorCategory.ERROR,
            default_message_es="Error de configuracion.",
            default_message_en="Base class for every setup-wizard error.",
            default_message_hu="Beallitas hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.setup._errors.SetupVerifyError",
        ErrorCode(
            code="ERROR_SETUP_VERIFY",
            category=ErrorCategory.ERROR,
            default_message_es="Error de configuracion verificar.",
            default_message_en="Raised when the verify step finds an ERROR-severity problem.",
            default_message_hu="Beallitas ellenoriz hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.verification._errors.VerificationError",
        ErrorCode(
            code="INTEGRITY_VERIFICATION",
            category=ErrorCategory.INTEGRITY,
            default_message_es="La verificacion de verificacion fallo.",
            default_message_en="Raised on catastrophic verification failures (not ordinary discrepancies).",
            default_message_hu="Ellenorzes ellenorzese sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.workflow._errors.WorkflowAbortedError",
        ErrorCode(
            code="REFUSED_WORKFLOW_ABORTED",
            category=ErrorCategory.REFUSED,
            default_message_es="El flujo de trabajo fue abortado por el solicitante.",
            default_message_en="Raised only when a caller explicitly opts in to exception-on-abort.",
            default_message_hu="A munkafolyamatot a hivo megszakitotta.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.workflow._errors.WorkflowComponentError",
        ErrorCode(
            code="ERROR_WORKFLOW_COMPONENT",
            category=ErrorCategory.ERROR,
            default_message_es="Error de flujo de trabajo componente.",
            default_message_en="Raised when a cross-module component raises an unexpected exception.",
            default_message_hu="Munkafolyamat komponens hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.workflow._errors.WorkflowError",
        ErrorCode(
            code="ERROR_WORKFLOW",
            category=ErrorCategory.ERROR,
            default_message_es="Error de flujo de trabajo.",
            default_message_en="Base class for workflow errors.",
            default_message_hu="Munkafolyamat hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.workflow._errors.WorkflowAbortSignal",
        ErrorCode(
            code="INTERNAL_WORKFLOW_ABORT_SIGNAL",
            category=ErrorCategory.INTERNAL,
            default_message_es="Senal interna de aborto del flujo de trabajo.",
            default_message_en="Internal control-flow signal raised by a stage method to bail out.",
            default_message_hu="Belso munkafolyamat-megszakitasi jelzes.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
)
