"""Error code registry for aeat.application."""

from aeat.core.errors._registry import ErrorCategory, ErrorCode

_DECLARED_ERROR_CODES: tuple[tuple[str, ErrorCode], ...] = (
    (
        "aeat.application.auth._acquisition_lock.AuthAcquisitionLockedError",
        ErrorCode(
            code="LOCKED_AUTH_ACQUISITION",
            category=ErrorCategory.LOCKED,
            message_key="errors.locked.locked_auth_acquisition",
            default_suggestion="aeat setup auth status --format json",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.aggregation._errors.AggregationError",
        ErrorCode(
            code="ERROR_FINANCIAL_AGGREGATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_aggregation",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.aggregation._errors.AggregationPeriodError",
        ErrorCode(
            code="ERROR_FINANCIAL_AGGREGATION_PERIOD",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_aggregation_period",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.aggregation._errors.AggregationUnsupportedModeloError",
        ErrorCode(
            code="REFUSED_FINANCIAL_AGGREGATION_UNSUPPORTED_MODELO",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_financial_aggregation_unsupported_modelo",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.aggregation._errors.AggregationMissingClassificationError",
        ErrorCode(
            code="REFUSED_FINANCIAL_AGGREGATION_MISSING_CLASSIFICATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_financial_aggregation_missing_classification",
            default_suggestion="aeat app ledger review --filter status=pending",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.aggregation._errors.AggregationCategoryCoverageError",
        ErrorCode(
            code="REFUSED_FINANCIAL_AGGREGATION_CATEGORY_COVERAGE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_financial_aggregation_category_coverage",
            default_suggestion="aeat app ledger review",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.review._errors.ReviewError",
        ErrorCode(
            code="ERROR_REVIEW",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_review",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.review._errors.ReviewKindReservedError",
        ErrorCode(
            code="REFUSED_REVIEW_KIND_RESERVED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_review_kind_reserved",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.review._errors.ReviewSourceLoadError",
        ErrorCode(
            code="FAIL_REVIEW_SOURCE_LOAD",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_review_source_load",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.review._errors.FilterParseError",
        ErrorCode(
            code="REFUSED_REVIEW_FILTER_PARSE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_review_filter_parse",
            default_suggestion="aeat app ledger review --filter status=pending",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.review._errors.EditParseError",
        ErrorCode(
            code="REFUSED_REVIEW_EDIT_PARSE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_review_edit_parse",
            default_suggestion="aeat app ledger edit --id ID --set category=V-01 --reason reason",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.setup._errors.SetupAbortedError",
        ErrorCode(
            code="REFUSED_SETUP_ABORTED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_setup_aborted",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.setup._errors.SetupAnswersError",
        ErrorCode(
            code="ERROR_SETUP_ANSWERS",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_setup_answers",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.setup._errors.SetupError",
        ErrorCode(
            code="ERROR_SETUP",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_setup",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.setup._errors.SetupVerifyError",
        ErrorCode(
            code="ERROR_SETUP_VERIFY",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_setup_verify",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.verification._errors.VerificationError",
        ErrorCode(
            code="INTEGRITY_VERIFICATION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_verification",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.workflow._errors.WorkflowAbortedError",
        ErrorCode(
            code="REFUSED_WORKFLOW_ABORTED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_workflow_aborted",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.workflow._errors.WorkflowComponentError",
        ErrorCode(
            code="ERROR_WORKFLOW_COMPONENT",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_workflow_component",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.workflow._errors.WorkflowError",
        ErrorCode(
            code="ERROR_WORKFLOW",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_workflow",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.workflow._errors.WorkflowAbortSignal",
        ErrorCode(
            code="INTERNAL_WORKFLOW_ABORT_SIGNAL",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.internal_workflow_abort_signal",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.archive._errors.ArchiveError",
        ErrorCode(
            code="ERROR_ARCHIVE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_archive",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.archive._errors.ArchiveAdapterMissingError",
        ErrorCode(
            code="REFUSED_ARCHIVE_ADAPTER_MISSING",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_archive_adapter_missing",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.archive._errors.ArchiveBundleSchemaError",
        ErrorCode(
            code="REFUSED_ARCHIVE_BUNDLE_SCHEMA",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_archive_bundle_schema",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.archive._errors.ArchiveConflictError",
        ErrorCode(
            code="REFUSED_ARCHIVE_CONFLICT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_archive_conflict",
            default_suggestion="aeat archive import <path> --conflict overwrite",
            retryable=False,
            runbook_id=None,
        ),
    ),
)
