"""Error code registry for aeat.core."""

from aeat.core.errors._registry import ErrorCategory, ErrorCode

_DECLARED_ERROR_CODES: tuple[tuple[str, ErrorCode], ...] = (
    (
        "aeat.core.json_contract.OutputSchemaError",
        ErrorCode(
            code="INTEGRITY_CLI_OUTPUT_SCHEMA",
            category=ErrorCategory.INTEGRITY,
            default_message_es="El registro de esquemas JSON del CLI no es valido.",
            default_message_en="The CLI JSON schema registry is invalid.",
            default_message_hu="A CLI JSON sema regisztere ervenytelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.core.errors.AeatObservabilityError",
        ErrorCode(
            code="ERROR_AEAT_OBSERVABILITY",
            category=ErrorCategory.ERROR,
            default_message_es="Error de aeat observabilidad.",
            default_message_en="Base class for observability-layer errors.",
            default_message_hu="Aeat megfigyelhetoseg hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.core.errors.FilingFixtureError",
        ErrorCode(
            code="INTEGRITY_FILING_FIXTURE",
            category=ErrorCategory.INTEGRITY,
            default_message_es="Error de presentacion fixture.",
            default_message_en="Raised when a synthetic filing-history fixture cannot be loaded.",
            default_message_hu="Beadas fixeles hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.core.errors.FixtureProvisioningError",
        ErrorCode(
            code="ERROR_FIXTURE_PROVISIONING",
            category=ErrorCategory.ERROR,
            default_message_es="Error de fixture aprovisionamiento.",
            default_message_en="Raised when Google Workspace test-fixture provisioning fails.",
            default_message_hu="Fixeles letrehozas hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.core.errors.McpLaunchError",
        ErrorCode(
            code="FAIL_MCP_LAUNCH",
            category=ErrorCategory.FAIL,
            default_message_es="Error de mcp launch.",
            default_message_en="Raised when a repo-managed MCP process cannot be launched safely.",
            default_message_hu="Mcp launch hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.core.errors.SiteHealthError",
        ErrorCode(
            code="FAIL_SITE_HEALTH",
            category=ErrorCategory.FAIL,
            default_message_es="Error de estado del sitio de AEAT.",
            default_message_en="Raised when AEAT site-health detection classifies a non-OK state.",
            default_message_hu="Az AEAT oldalallapota hibas.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.core.i18n.TranslationError",
        ErrorCode(
            code="ERROR_I18N_TRANSLATION",
            category=ErrorCategory.ERROR,
            default_message_es="Error de traduccion.",
            default_message_en="Raised when a required translation is missing or invalid.",
            default_message_hu="Forditas hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.core.observability._errors.AeatCorpusDriftError",
        ErrorCode(
            code="INTEGRITY_OBSERVABILITY_AEAT_CORPUS_DRIFT",
            category=ErrorCategory.INTEGRITY,
            default_message_es="Error de aeat corpus drift.",
            default_message_en="The normative corpus fingerprint no longer matches the replay metadata.",
            default_message_hu="Aeat korpusz drift hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.core.observability._errors.RunContextMissingError",
        ErrorCode(
            code="INTERNAL_OBSERVABILITY_RUN_CONTEXT_MISSING",
            category=ErrorCategory.INTERNAL,
            default_message_es="Error de ejecucion contexto faltante.",
            default_message_en="Raised when an observability call is made outside an active run context.",
            default_message_hu="Futas kontextus hianyzik hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.core.observability._errors.RunTraceValidationError",
        ErrorCode(
            code="INTEGRITY_OBSERVABILITY_RUN_TRACE_VALIDATION",
            category=ErrorCategory.INTEGRITY,
            default_message_es="La validacion de ejecucion traza fallo.",
            default_message_en="The persisted run trace artifacts failed validation.",
            default_message_hu="Futas nyomvonal ervenyesitese sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.core.identity._documents.IdentityError",
        ErrorCode(
            code="INTEGRITY_IDENTITY_DOCUMENT",
            category=ErrorCategory.INTEGRITY,
            default_message_es="Documento de identidad no valido.",
            default_message_en="The candidate string is not a valid NIF, NIE, or CIF.",
            default_message_hu="Ervenytelen azonosito okmany.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.core.locks_errors.LockAcquisitionError",
        ErrorCode(
            code="LOCKED_STORAGE_LOCK_ACQUISITION",
            category=ErrorCategory.LOCKED,
            default_message_es="No se pudo adquirir el bloqueo de archivo exclusivo.",
            default_message_en="Failed to acquire the exclusive file lock within the configured timeout.",
            default_message_hu="A fajl zarolas nem sikerult.",
            default_suggestion=None,
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "aeat.core.corpus_manifest._errors.CorpusManifestError",
        ErrorCode(
            code="INTEGRITY_STORAGE_CORPUS_MANIFEST",
            category=ErrorCategory.INTEGRITY,
            default_message_es="Manifiesto de corpus invalido o estructuralmente roto.",
            default_message_en="A corpus manifest is structurally invalid or its version is unsupported.",
            default_message_hu="A korpusz manifeszt strukturalisan ervenytelen.",
            default_suggestion="aeat setup status",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.core.corpus_manifest._errors.CorpusManifestTamperError",
        ErrorCode(
            code="INTEGRITY_STORAGE_CORPUS_MANIFEST_TAMPER",
            category=ErrorCategory.INTEGRITY,
            default_message_es="Digesto autodeclarado del manifiesto no coincide con el cuerpo.",
            default_message_en=(
                "A corpus manifest's recorded sha256 does not match its body; the manifest may have been tampered with."
            ),
            default_message_hu="A manifeszt onaltal jelolt SHA-256 nem egyezik a tartalommal.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.core.corpus_manifest._errors.CorpusManifestDriftError",
        ErrorCode(
            code="INTEGRITY_STORAGE_CORPUS_MANIFEST_DRIFT",
            category=ErrorCategory.INTEGRITY,
            default_message_es="El corpus en disco no coincide con el manifiesto.",
            default_message_en="The on-disk corpus diverges from its manifest (added / removed / changed files).",
            default_message_hu="A lemezen levo korpusz elter a manifeszttol.",
            default_suggestion="aeat setup status",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.core.access_gate._errors.AccessGateSubmissionError",
        ErrorCode(
            code="ERROR_ACCESS_GATE_SUBMISSION",
            category=ErrorCategory.ERROR,
            default_message_es="Error de política de envío.",
            default_message_en="Base class for access-gate submission policy errors.",
            default_message_hu="Hozzáférési kapu beküldési hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.core.access_gate._errors.AccessGateSubmissionPreflightError",
        ErrorCode(
            code="ERROR_ACCESS_GATE_SUBMISSION_PREFLIGHT",
            category=ErrorCategory.ERROR,
            default_message_es="La política previa de envío rechazó la operación.",
            default_message_en="Raised when access-gate preflight rejects a submission operation.",
            default_message_hu="A hozzáférési kapu előzetes ellenőrzése elutasította a beküldést.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.core.access_gate._errors.LiveSubmitForbiddenError",
        ErrorCode(
            code="LOCKED_ACCESS_GATE_LIVE_SUBMIT_FORBIDDEN",
            category=ErrorCategory.LOCKED,
            default_message_es="El envío en vivo a AEAT está permanentemente prohibido.",
            default_message_en="Live AEAT submission is permanently forbidden by the access gate.",
            default_message_hu="Az élő AEAT beküldést a hozzáférési kapu véglegesen tiltja.",
            default_suggestion="aeat app declaration export --id DRAFT_ID --output PATH",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.core.access_gate._errors.AeatLiveReadNotEnabledError",
        ErrorCode(
            code="REFUSED_ACCESS_GATE_LIVE_READ_NOT_ENABLED",
            category=ErrorCategory.REFUSED,
            default_message_es="La lectura en vivo de AEAT no está habilitada.",
            default_message_en="Live AEAT read access is not enabled.",
            default_message_hu="Az élő AEAT olvasás nincs engedélyezve.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
)
