"""Error code registry for aeat.domain."""

from aeat.core.errors._registry import ErrorCategory, ErrorCode

_DECLARED_ERROR_CODES: tuple[tuple[str, ErrorCode], ...] = (
    (
        "aeat.domain.justificante._errors.PdfFilingImportError",
        ErrorCode(
            code="ERROR_PDF_IMPORT_PDF_FILING_IMPORT",
            category=ErrorCategory.ERROR,
            default_message_es="Error de pdf presentacion importacion.",
            default_message_en="Base class for every PDF-import parsing error.",
            default_message_hu="Pdf beadas importalas hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.casillas.errors.CasillaError",
        ErrorCode(
            code="ERROR_CASILLAS_CASILLA",
            category=ErrorCategory.ERROR,
            default_message_es="Error de casilla.",
            default_message_en="Base class for casilla-related errors.",
            default_message_hu="Casilla hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.casillas.errors.CasillaParseError",
        ErrorCode(
            code="FAIL_CASILLAS_CASILLA_PARSE",
            category=ErrorCategory.FAIL,
            default_message_es="No se pudo analizar casilla.",
            default_message_en="Raised when a casilla catalogue file cannot be parsed or validated.",
            default_message_hu="Casilla feldolgozasa sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.casillas.errors.CrossReferenceError",
        ErrorCode(
            code="ERROR_CASILLAS_CROSS_REFERENCE",
            category=ErrorCategory.ERROR,
            default_message_es="Error de cruce referencia.",
            default_message_en="Raised when a record references another casilla that does not exist.",
            default_message_hu="Kereszt hivatkozas hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.casillas.errors.MissingFieldError",
        ErrorCode(
            code="ERROR_CASILLAS_MISSING_FIELD",
            category=ErrorCategory.ERROR,
            default_message_es="Error de faltante campo.",
            default_message_en="Raised when a record is missing a required logical field.",
            default_message_hu="Hianyzik mezo hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.casillas.errors.UnreviewedRecordError",
        ErrorCode(
            code="ERROR_CASILLAS_UNREVIEWED_RECORD",
            category=ErrorCategory.ERROR,
            default_message_es="Error de sin revisar registro.",
            default_message_en="Raised when a canonical record lacks required review metadata.",
            default_message_hu="Ellenorizetlen rekord hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.casillas.errors.VerifyError",
        ErrorCode(
            code="ERROR_CASILLAS_VERIFY",
            category=ErrorCategory.ERROR,
            default_message_es="Error de verificar.",
            default_message_en="Base class for structured verification failures.",
            default_message_hu="Ellenoriz hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.deadlines._errors.DeadlineError",
        ErrorCode(
            code="ERROR_DEADLINES_DEADLINE",
            category=ErrorCategory.ERROR,
            default_message_es="Error de plazo.",
            default_message_en="Base class for deadline-related errors.",
            default_message_hu="Hatarido hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.deadlines._errors.ProfileError",
        ErrorCode(
            code="ERROR_DEADLINES_PROFILE",
            category=ErrorCategory.ERROR,
            default_message_es="Error de perfil.",
            default_message_en="The autonomo profile could not be loaded or validated.",
            default_message_hu="Profil hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.deadlines._errors.ScheduleComputationError",
        ErrorCode(
            code="ERROR_DEADLINES_SCHEDULE_COMPUTATION",
            category=ErrorCategory.ERROR,
            default_message_es="Error de planificacion calculo.",
            default_message_en="The deadline schedule could not be computed.",
            default_message_hu="Utemezes szamitas hiba.",
            default_suggestion="aeat app overview status --period 2024Q1",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.filing._errors.FilingAmendmentError",
        ErrorCode(
            code="ERROR_FILING_AMENDMENT",
            category=ErrorCategory.ERROR,
            default_message_es="Error de presentacion rectificacion.",
            default_message_en="Base class for every amendment-related filing error.",
            default_message_hu="Beadas helyesbites hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.filing._errors.FilingAmendmentValidationError",
        ErrorCode(
            code="INTEGRITY_FILING_AMENDMENT_VALIDATION",
            category=ErrorCategory.INTEGRITY,
            default_message_es="La validacion de presentacion rectificacion fallo.",
            default_message_en="Raised when an amendment violates legal or shape invariants.",
            default_message_hu="Beadas helyesbites ervenyesitese sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.filing._errors.FilingBuilderError",
        ErrorCode(
            code="ERROR_FILING_BUILDER",
            category=ErrorCategory.ERROR,
            default_message_es="Error de presentacion builder.",
            default_message_en="Raised when builder selection or execution fails.",
            default_message_hu="Beadas builder hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.filing._errors.FilingComputationError",
        ErrorCode(
            code="ERROR_FILING_COMPUTATION",
            category=ErrorCategory.ERROR,
            default_message_es="Error de presentacion calculo.",
            default_message_en="Raised when a builder cannot evaluate a formula casilla.",
            default_message_hu="Beadas szamitas hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.filing._errors.FilingDraftError",
        ErrorCode(
            code="ERROR_FILING_DRAFT",
            category=ErrorCategory.ERROR,
            default_message_es="Error del borrador de presentacion.",
            default_message_en="Base class for filing-draft errors.",
            default_message_hu="Beadasi tervezet hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.filing._errors.FilingImportError",
        ErrorCode(
            code="FAIL_FILING_IMPORT",
            category=ErrorCategory.FAIL,
            default_message_es="Error de presentacion importacion.",
            default_message_en="Raised when importing a filing from a justificante PDF fails.",
            default_message_hu="Beadas importalas hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.filing._errors.FilingValidationError",
        ErrorCode(
            code="INTEGRITY_FILING_VALIDATION",
            category=ErrorCategory.INTEGRITY,
            default_message_es="La validacion de presentacion fallo.",
            default_message_en="Raised when validation surfaces a blocking finding.",
            default_message_hu="Beadas ervenyesitese sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.attachments._errors.AttachmentError",
        ErrorCode(
            code="ERROR_FINANCIAL_ATTACHMENTS_ATTACHMENT",
            category=ErrorCategory.ERROR,
            default_message_es="Error de adjunto.",
            default_message_en="Base error for every attachment-service failure.",
            default_message_hu="Melleklet hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.attachments._errors.AttachmentNotFoundError",
        ErrorCode(
            code="ERROR_FINANCIAL_ATTACHMENTS_ATTACHMENT_NOT_FOUND",
            category=ErrorCategory.ERROR,
            default_message_es="No se encontro adjunto.",
            default_message_en="Raised when a manifest or blob lookup targets a missing attachment.",
            default_message_hu="Melleklet nem talalhato.",
            default_suggestion="aeat app ledger review",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.attachments._errors.AttachmentPersistenceError",
        ErrorCode(
            code="FAIL_FINANCIAL_ATTACHMENTS_ATTACHMENT_PERSISTENCE",
            category=ErrorCategory.FAIL,
            default_message_es="No se pudo persistir adjunto.",
            default_message_en="The attachment store could not read or write attachment bytes or manifests.",
            default_message_hu="Melleklet mentese sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.attachments._errors.AttachmentValidationError",
        ErrorCode(
            code="INTEGRITY_FINANCIAL_ATTACHMENTS_ATTACHMENT_VALIDATION",
            category=ErrorCategory.INTEGRITY,
            default_message_es="La validacion de adjunto fallo.",
            default_message_en="Raised when an attachment payload fails domain validation.",
            default_message_hu="Melleklet ervenyesitese sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.invoices._errors.InvoiceCatalogueError",
        ErrorCode(
            code="ERROR_FINANCIAL_INVOICES_INVOICE_CATALOGUE",
            category=ErrorCategory.ERROR,
            default_message_es="Error de factura catalogo.",
            default_message_en="Raised when an invoice catalogue is invalid or inconsistent.",
            default_message_hu="Szamla katalogus hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.invoices._errors.InvoiceError",
        ErrorCode(
            code="ERROR_FINANCIAL_INVOICES_INVOICE",
            category=ErrorCategory.ERROR,
            default_message_es="Error de factura.",
            default_message_en="Base error for every invoice-catalogue failure.",
            default_message_hu="Szamla hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.invoices._errors.InvoiceLinkError",
        ErrorCode(
            code="ERROR_FINANCIAL_INVOICES_INVOICE_LINK",
            category=ErrorCategory.ERROR,
            default_message_es="Error de factura enlace.",
            default_message_en="Raised when a bidirectional invoice/transaction link cannot proceed.",
            default_message_hu="Szamla kapcsolat hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.invoices._errors.InvoiceLinkInconsistencyError",
        ErrorCode(
            code="ERROR_FINANCIAL_INVOICES_INVOICE_LINK_INCONSISTENCY",
            category=ErrorCategory.ERROR,
            default_message_es="Error de factura enlace inconsistencia.",
            default_message_en="Raised when a bidirectional link leaves the two catalogues out of sync.",
            default_message_hu="Szamla kapcsolat kovetkezetlenseg hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.invoices._errors.InvoiceNotFoundError",
        ErrorCode(
            code="ERROR_FINANCIAL_INVOICES_INVOICE_NOT_FOUND",
            category=ErrorCategory.ERROR,
            default_message_es="No se encontro factura.",
            default_message_en="Raised when a catalogue lookup targets a missing invoice.",
            default_message_hu="Szamla nem talalhato.",
            default_suggestion="aeat app invoice review",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.invoices._errors.InvoicePersistenceError",
        ErrorCode(
            code="FAIL_FINANCIAL_INVOICES_INVOICE_PERSISTENCE",
            category=ErrorCategory.FAIL,
            default_message_es="No se pudo persistir factura.",
            default_message_en="Raised when invoice catalogue persistence cannot be completed.",
            default_message_hu="Szamla mentese sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.transactions._errors.TransactionCatalogueError",
        ErrorCode(
            code="ERROR_FINANCIAL_TRANSACTIONS_TRANSACTION_CATALOGUE",
            category=ErrorCategory.ERROR,
            default_message_es="Error de transaccion catalogo.",
            default_message_en="Raised when a transaction catalogue is invalid or inconsistent.",
            default_message_hu="Tranzakcio katalogus hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.transactions._errors.TransactionError",
        ErrorCode(
            code="ERROR_FINANCIAL_TRANSACTIONS_TRANSACTION",
            category=ErrorCategory.ERROR,
            default_message_es="Error de transaccion.",
            default_message_en="Base error for every transaction-catalogue failure.",
            default_message_hu="Tranzakcio hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.transactions._errors.TransactionNotFoundError",
        ErrorCode(
            code="ERROR_FINANCIAL_TRANSACTIONS_TRANSACTION_NOT_FOUND",
            category=ErrorCategory.ERROR,
            default_message_es="No se encontro transaccion.",
            default_message_en="Raised when a catalogue lookup targets a missing transaction.",
            default_message_hu="Tranzakcio nem talalhato.",
            default_suggestion="aeat app ledger review",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.transactions._errors.TransactionPersistenceError",
        ErrorCode(
            code="FAIL_FINANCIAL_TRANSACTIONS_TRANSACTION_PERSISTENCE",
            category=ErrorCategory.FAIL,
            default_message_es="No se pudo persistir transaccion.",
            default_message_en="Raised when catalogue persistence cannot be completed.",
            default_message_hu="Tranzakcio mentese sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.transactions._errors.LLMClassifierError",
        ErrorCode(
            code="FAIL_TRANSACTION_LLM_CLASSIFIER",
            category=ErrorCategory.FAIL,
            default_message_es="El clasificador LLM falló al evaluar la transacción.",
            default_message_en="LLM classifier failed to evaluate the transaction.",
            default_message_hu="Az LLM osztályozó nem tudta kiértékelni a tranzakciót.",
            default_suggestion=None,
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.usage_ratios._errors.UsageRatioError",
        ErrorCode(
            code="ERROR_FINANCIAL_USAGE_RATIOS_USAGE_RATIO",
            category=ErrorCategory.ERROR,
            default_message_es="Error de uso ratio.",
            default_message_en="Base error for every usage-ratio profile failure.",
            default_message_hu="Hasznalat arany hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.usage_ratios._errors.UsageRatioPersistenceError",
        ErrorCode(
            code="FAIL_FINANCIAL_USAGE_RATIOS_USAGE_RATIO_PERSISTENCE",
            category=ErrorCategory.FAIL,
            default_message_es="No se pudo persistir uso ratio.",
            default_message_en="The usage-ratio profile could not be read or written.",
            default_message_hu="Hasznalat arany mentese sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.vat.errors.VatCatalogueError",
        ErrorCode(
            code="ERROR_FINANCIAL_VAT_CATALOGUE",
            category=ErrorCategory.ERROR,
            default_message_es="Error de iva catalogo.",
            default_message_en="Raised when a VAT catalogue cannot be loaded or is malformed.",
            default_message_hu="Afa katalogus hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.vat.errors.VatCategoryNotFoundError",
        ErrorCode(
            code="ERROR_FINANCIAL_VAT_CATEGORY_NOT_FOUND",
            category=ErrorCategory.ERROR,
            default_message_es="No se encontro la categoria de IVA solicitada.",
            default_message_en="The requested VAT category could not be found in the catalogue.",
            default_message_hu="A kert afa kategoria nem talalhato.",
            default_suggestion="aeat app invoice review",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.vat.errors.VatClassificationError",
        ErrorCode(
            code="ERROR_FINANCIAL_VAT_CLASSIFICATION",
            category=ErrorCategory.ERROR,
            default_message_es="Error de iva clasificacion.",
            default_message_en="The VAT classifier could not produce a deterministic match.",
            default_message_hu="Afa besorolas hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.vat.errors.VatError",
        ErrorCode(
            code="ERROR_FINANCIAL_VAT",
            category=ErrorCategory.ERROR,
            default_message_es="Error de iva.",
            default_message_en="Base class for VAT-related errors.",
            default_message_hu="Afa hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.vat.errors.VatRateNotFoundError",
        ErrorCode(
            code="ERROR_FINANCIAL_VAT_RATE_NOT_FOUND",
            category=ErrorCategory.ERROR,
            default_message_es="No se encontro iva tipo.",
            default_message_en="The requested VAT rate could not be resolved.",
            default_message_hu="Afa kulcs nem talalhato.",
            default_suggestion="aeat app invoice review",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.vat.errors.VatRateOverlapError",
        ErrorCode(
            code="ERROR_FINANCIAL_VAT_RATE_OVERLAP",
            category=ErrorCategory.ERROR,
            default_message_es="Error de iva tipo solapamiento.",
            default_message_en="Two VAT rate records overlap in an active time window.",
            default_message_hu="Afa kulcs atfedes hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.justificante._errors.JustificanteCsvNotFoundError",
        ErrorCode(
            code="ERROR_JUSTIFICANTE_CSV_NOT_FOUND",
            category=ErrorCategory.ERROR,
            default_message_es="No se encontro justificante csv.",
            default_message_en="Raised when a PDF does not contain a C\xf3digo Seguro de Verificaci\xf3n.",
            default_message_hu="Igazolas csv nem talalhato.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.justificante._errors.JustificanteError",
        ErrorCode(
            code="ERROR_JUSTIFICANTE",
            category=ErrorCategory.ERROR,
            default_message_es="Error de justificante.",
            default_message_en="Base class for every justificante-related failure.",
            default_message_hu="Igazolas hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.justificante._errors.JustificanteParseError",
        ErrorCode(
            code="FAIL_JUSTIFICANTE_PARSE",
            category=ErrorCategory.FAIL,
            default_message_es="No se pudo analizar justificante.",
            default_message_en="The PDF could not be parsed into a justificante record.",
            default_message_hu="Igazolas feldolgozasa sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.justificante._errors.JustificanteVerificationError",
        ErrorCode(
            code="INTEGRITY_JUSTIFICANTE_VERIFICATION",
            category=ErrorCategory.INTEGRITY,
            default_message_es="La verificacion de justificante fallo.",
            default_message_en="Raised when the live CSV verification round-trip fails.",
            default_message_hu="Igazolas ellenorzese sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.manuals.errors.ManifestError",
        ErrorCode(
            code="INTEGRITY_MANUALS_MANIFEST",
            category=ErrorCategory.INTEGRITY,
            default_message_es="Error de manifiesto.",
            default_message_en="The manuals manifest could not be parsed.",
            default_message_hu="Manifestum hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.manuals.errors.ManualError",
        ErrorCode(
            code="ERROR_MANUALS_MANUAL",
            category=ErrorCategory.ERROR,
            default_message_es="Error de manual.",
            default_message_en="Base class for manual-corpus errors.",
            default_message_hu="Kezikonyv hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.manuals.errors.ManualNotFoundError",
        ErrorCode(
            code="ERROR_MANUALS_MANUAL_NOT_FOUND",
            category=ErrorCategory.ERROR,
            default_message_es="No se encontro manual.",
            default_message_en="Raised when a requested manual/year/part is missing on disk.",
            default_message_hu="Kezikonyv nem talalhato.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.manuals.errors.ManualParseError",
        ErrorCode(
            code="FAIL_MANUALS_MANUAL_PARSE",
            category=ErrorCategory.FAIL,
            default_message_es="No se pudo analizar manual.",
            default_message_en="Raised when a committed manual record fails schema validation.",
            default_message_hu="Kezikonyv feldolgozasa sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.manuals.errors.ManualReviewRequiredError",
        ErrorCode(
            code="ERROR_MANUALS_MANUAL_REVIEW_REQUIRED",
            category=ErrorCategory.ERROR,
            default_message_es="Error de manual revision requerido.",
            default_message_en="Raised when a persisted record lacks reviewer metadata.",
            default_message_hu="Kezikonyv ellenorzes szukseges hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.manuals.errors.RuleExtractionError",
        ErrorCode(
            code="ERROR_MANUALS_RULE_EXTRACTION",
            category=ErrorCategory.ERROR,
            default_message_es="Error de regla extraction.",
            default_message_en="The rule-extraction step is not available yet in this CLI phase.",
            default_message_hu="Szabaly extraction hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.modelos._errors.ModeloRegistryError",
        ErrorCode(
            code="ERROR_MODELS_MODELO_REGISTRY",
            category=ErrorCategory.ERROR,
            default_message_es="Error de modelo registro.",
            default_message_en="Base class for modelo-registry errors.",
            default_message_hu="Modelo jegyzek hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.modelos._errors.RegistryIntegrityError",
        ErrorCode(
            code="INTEGRITY_MODELS_REGISTRY_INTEGRITY",
            category=ErrorCategory.INTEGRITY,
            default_message_es="Error de registro integridad.",
            default_message_en="Raised at import time when the registry fails a structural check.",
            default_message_hu="Jegyzek integritas hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.modelos._errors.UnknownModeloError",
        ErrorCode(
            code="ERROR_MODELS_UNKNOWN_MODELO",
            category=ErrorCategory.ERROR,
            default_message_es="Modelo desconocido.",
            default_message_en="The requested modelo is unknown.",
            default_message_hu="Ismeretlen modelo.",
            default_suggestion="aeat app declaration status",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.normatives.errors.NormativeError",
        ErrorCode(
            code="ERROR_NORMATIVES_NORMATIVE",
            category=ErrorCategory.ERROR,
            default_message_es="Error de normativa.",
            default_message_en="Base class for normative lookup errors.",
            default_message_hu="Jogszabaly hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.normatives.errors.NormativeNotFoundError",
        ErrorCode(
            code="ERROR_NORMATIVES_NORMATIVE_NOT_FOUND",
            category=ErrorCategory.ERROR,
            default_message_es="No se encontro normativa.",
            default_message_en="Raised when a requested normative or article is missing.",
            default_message_hu="Jogszabaly nem talalhato.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.normatives.errors.NormativeParseError",
        ErrorCode(
            code="FAIL_NORMATIVES_NORMATIVE_PARSE",
            category=ErrorCategory.FAIL,
            default_message_es="No se pudo analizar normativa.",
            default_message_en="Raised when a committed normative JSON fails schema validation.",
            default_message_hu="Jogszabaly feldolgozasa sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.portals._errors.PortalIntegrityError",
        ErrorCode(
            code="INTEGRITY_PORTALS_PORTAL_INTEGRITY",
            category=ErrorCategory.INTEGRITY,
            default_message_es="Error de portal integridad.",
            default_message_en="Raised at import time when the registry fails a structural check.",
            default_message_hu="Portal integritas hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.portals._errors.PortalRegistryError",
        ErrorCode(
            code="ERROR_PORTALS_PORTAL_REGISTRY",
            category=ErrorCategory.ERROR,
            default_message_es="Error de portal registro.",
            default_message_en="Base class for portal-registry errors.",
            default_message_hu="Portal jegyzek hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.portals._errors.UnknownPortalError",
        ErrorCode(
            code="ERROR_PORTALS_UNKNOWN_PORTAL",
            category=ErrorCategory.ERROR,
            default_message_es="Portal desconocido.",
            default_message_en="The requested portal is unknown.",
            default_message_hu="Ismeretlen portal.",
            default_suggestion="aeat setup auth status",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.profile.errors.AssetRecordError",
        ErrorCode(
            code="ERROR_PROFILE_ASSET_RECORD",
            category=ErrorCategory.ERROR,
            default_message_es="El registro de activo no es valido.",
            default_message_en="The asset record is invalid.",
            default_message_hu="Az eszkozrekord ervenytelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.profile.errors.AmortizationLedgerError",
        ErrorCode(
            code="ERROR_PROFILE_AMORTIZATION_LEDGER",
            category=ErrorCategory.ERROR,
            default_message_es="El libro de amortizacion no es valido.",
            default_message_en="The amortization ledger is invalid.",
            default_message_hu="Az amortizacios naplo ervenytelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.profile.errors.InventoryLedgerError",
        ErrorCode(
            code="ERROR_PROFILE_INVENTORY_LEDGER",
            category=ErrorCategory.ERROR,
            default_message_es="El libro de inventario no es valido.",
            default_message_en="The inventory ledger is invalid.",
            default_message_hu="A keszletnaplo ervenytelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.profile.errors.LIFOForbiddenError",
        ErrorCode(
            code="REFUSED_PROFILE_INVENTORY_LIFO",
            category=ErrorCategory.REFUSED,
            default_message_es="LIFO no esta admitido para este libro fiscal.",
            default_message_en="LIFO is not admitted for this tax ledger.",
            default_message_hu="A LIFO nem engedelyezett ebben az adonaploban.",
            default_suggestion="aeat app ledger review",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.profile.errors.BasisCapExceededError",
        ErrorCode(
            code="INTEGRITY_PROFILE_AMORTIZATION_BASIS_CAP",
            category=ErrorCategory.INTEGRITY,
            default_message_es="La amortizacion acumulada supera la base de coste.",
            default_message_en="Cumulative amortization exceeds the cost basis.",
            default_message_hu="A halmozott amortizacio meghaladja a bekerulesi erteket.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.schema._errors.SchemaCacheError",
        ErrorCode(
            code="FAIL_SCHEMA_CACHE",
            category=ErrorCategory.FAIL,
            default_message_es="Error de cache del esquema.",
            default_message_en="Raised when on-disk schema persistence fails.",
            default_message_hu="A sema gyorsitotar hibas.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.schema._errors.SchemaError",
        ErrorCode(
            code="ERROR_SCHEMA",
            category=ErrorCategory.ERROR,
            default_message_es="Error de esquema.",
            default_message_en="Base class for schema-processing errors.",
            default_message_hu="Sema hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.schema._errors.SchemaEvaluationError",
        ErrorCode(
            code="ERROR_SCHEMA_EVALUATION",
            category=ErrorCategory.ERROR,
            default_message_es="Error de esquema evaluacion.",
            default_message_en="The schema formula AST could not be evaluated.",
            default_message_hu="Sema ertekeles hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.schema._errors.SchemaExtractionError",
        ErrorCode(
            code="ERROR_SCHEMA_EXTRACTION",
            category=ErrorCategory.ERROR,
            default_message_es="Error de extraccion de esquema.",
            default_message_en="The schema extractor could not parse its source.",
            default_message_hu="A sema kinyerese sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.schema._errors.SchemaValidationError",
        ErrorCode(
            code="INTEGRITY_SCHEMA_VALIDATION",
            category=ErrorCategory.INTEGRITY,
            default_message_es="La validacion de esquema fallo.",
            default_message_en="A cached modelo JSON document failed validation.",
            default_message_hu="Sema ervenyesitese sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.profile._errors.TaxResidenceProfileError",
        ErrorCode(
            code="ERROR_PROFILE_TAX_RESIDENCE",
            category=ErrorCategory.ERROR,
            default_message_es="Error del perfil de residencia fiscal.",
            default_message_en="Tax-residence profile error.",
            default_message_hu="Adoilletosegi profil hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.profile._errors.ProfileNotConfiguredError",
        ErrorCode(
            code="REFUSED_PROFILE_NOT_CONFIGURED",
            category=ErrorCategory.REFUSED,
            default_message_es="No hay perfil de residencia fiscal configurado para RENTA.",
            default_message_en="No tax-residence profile is configured for RENTA.",
            default_message_hu="Nincs beallitva RENTA adoilletosegi profil.",
            default_suggestion="aeat setup profile set tax.region ccaa",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.profile._errors.ForalRegimeError",
        ErrorCode(
            code="REFUSED_PROFILE_FORAL_REGIME",
            category=ErrorCategory.REFUSED,
            default_message_es="El regimen foral solicitado queda fuera del alcance de este perfil.",
            default_message_en="The requested foral regime is outside the scope of this profile.",
            default_message_hu="A kert foralis rendszer e profil hatokoren kivul esik.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.submission._errors.SubmissionError",
        ErrorCode(
            code="ERROR_DOMAIN_SUBMISSION",
            category=ErrorCategory.ERROR,
            default_message_es="Error de dominio de envío.",
            default_message_en="Base class for submission-domain failures.",
            default_message_hu="Domain beküldési hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.submission._errors.SubmissionPreflightError",
        ErrorCode(
            code="ERROR_DOMAIN_SUBMISSION_PREFLIGHT",
            category=ErrorCategory.ERROR,
            default_message_es="La validación previa de envío falló.",
            default_message_en="Raised when a draft cannot pass local submission preflight.",
            default_message_hu="A domain beküldési előellenőrzés sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.sync._errors.SyncError",
        ErrorCode(
            code="ERROR_DOMAIN_SYNC",
            category=ErrorCategory.ERROR,
            default_message_es="Error de sincronización de dominio.",
            default_message_en="Base class for domain sync errors.",
            default_message_hu="Domain szinkron hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.sync._errors.WireValidationError",
        ErrorCode(
            code="INTEGRITY_DOMAIN_SYNC_WIRE_VALIDATION",
            category=ErrorCategory.INTEGRITY,
            default_message_es="La validación wire de dominio falló.",
            default_message_en="Raised when a domain sync payload fails strict validation.",
            default_message_hu="A domain sync wire érvényesítése sikertelen.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.sync._errors.DivergenceClassificationError",
        ErrorCode(
            code="ERROR_DOMAIN_SYNC_DIVERGENCE_CLASSIFICATION",
            category=ErrorCategory.ERROR,
            default_message_es="Error de clasificación de divergencia de dominio.",
            default_message_en="Raised when the domain sync classifier cannot classify a divergence.",
            default_message_hu="Domain sync eltérés besorolási hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.sync._errors.HealingError",
        ErrorCode(
            code="ERROR_DOMAIN_SYNC_HEALING",
            category=ErrorCategory.ERROR,
            default_message_es="Error al reparar una divergencia de dominio.",
            default_message_en="Raised when a domain sync healing strategy cannot apply.",
            default_message_hu="Domain sync javítási hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.sync._errors.DivergenceRepositoryError",
        ErrorCode(
            code="ERROR_DOMAIN_SYNC_DIVERGENCE_REPOSITORY",
            category=ErrorCategory.ERROR,
            default_message_es="Error del repositorio de divergencias de dominio.",
            default_message_en="Raised when the domain sync divergence repository cannot persist or load.",
            default_message_hu="Domain sync eltérés tár hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.rental._errors.RentalRegisterError",
        ErrorCode(
            code="ERROR_RENTAL_REGISTER",
            category=ErrorCategory.ERROR,
            default_message_es="Error del registro de alquileres.",
            default_message_en="Base class for rental-register errors.",
            default_message_hu="Bérleti nyilvántartás hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.rental._errors.FincaNotFoundError",
        ErrorCode(
            code="ERROR_RENTAL_FINCA_NOT_FOUND",
            category=ErrorCategory.ERROR,
            default_message_es="Finca no encontrada en el registro.",
            default_message_en="Raised when a referenced finca id is not present in the rental register.",
            default_message_hu="A bérleti ingatlan nem található a nyilvántartásban.",
            default_suggestion="aeat app declaration status",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.rental._errors.ContractNotFoundError",
        ErrorCode(
            code="ERROR_RENTAL_CONTRACT_NOT_FOUND",
            category=ErrorCategory.ERROR,
            default_message_es="Contrato no encontrado en el registro.",
            default_message_en="Raised when a referenced rental contract id is not present in the register.",
            default_message_hu="A bérleti szerződés nem található a nyilvántartásban.",
            default_suggestion="aeat app declaration status",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.rental._errors.TierResolutionError",
        ErrorCode(
            code="ERROR_RENTAL_TIER_RESOLUTION",
            category=ErrorCategory.ERROR,
            default_message_es="No se puede resolver el tramo de reducción art. 23.2.",
            default_message_en=(
                "Raised when contract metadata is inconsistent and the LIRPF art. 23.2 tier cannot be resolved."
            ),
            default_message_hu="A 23.2 cikk csökkentési szint nem oldható fel.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.rental._errors.AmortizationLedgerCapExceededError",
        ErrorCode(
            code="ERROR_RENTAL_AMORTIZATION_CAP_EXCEEDED",
            category=ErrorCategory.ERROR,
            default_message_es=("El acumulado de amortización supera el coste de adquisición de la construcción."),
            default_message_en=(
                "Raised in strict mode when cumulative amortización would exceed the per-finca "
                "construction-cost basis cap."
            ),
            default_message_hu="A halmozott amortizáció meghaladja az építmény bekerülési értékét.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.domain.rental._errors.AnexoCAggregationError",
        ErrorCode(
            code="ERROR_RENTAL_ANEXO_C_AGGREGATION",
            category=ErrorCategory.ERROR,
            default_message_es="Error al agregar el Anexo C desde el registro de alquileres.",
            default_message_en="Raised when the rental register cannot produce a coherent Anexo C aggregate set.",
            default_message_hu="Anexo C aggregálási hiba.",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
)
