"""Error code registry for aeat.entrypoints."""

from aeat.core.errors._registry import ErrorCategory, ErrorCode

_DECLARED_ERROR_CODES: tuple[tuple[str, ErrorCode], ...] = (
    (
        "aeat.entrypoints.cli._errors.CliValidationBoundaryError",
        ErrorCode(
            code="INTEGRITY_CLI_VALIDATION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_cli_validation",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.entrypoints.cli._errors.CliUnexpectedBoundaryError",
        ErrorCode(
            code="INTERNAL_CLI_UNEXPECTED_EXCEPTION",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.internal_cli_unexpected_exception",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.entrypoints.cli._errors.CliRefusedBoundaryError",
        ErrorCode(
            code="REFUSED_CLI_BOUNDARY",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_cli_boundary",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.entrypoints.cli._log_levels.LogLevelResolutionError",
        ErrorCode(
            code="REFUSED_CLI_LOG_LEVEL_RESOLUTION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_cli_log_level_resolution",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.entrypoints.cli._tty.NonTtyRefusedError",
        ErrorCode(
            code="REFUSED_CLI_TTY_REQUIRED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_cli_tty_required",
            default_suggestion=None,
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.entrypoints.cli.auth._registry.NoConfiguredProviderError",
        ErrorCode(
            code="AUTH_CLI_AUTH_REGISTRY_NO_CONFIGURED_PROVIDER",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_cli_auth_registry_no_configured_provider",
            default_suggestion="aeat setup auth configure",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.entrypoints.cli.auth._registry.ProviderUnavailableError",
        ErrorCode(
            code="AUTH_CLI_AUTH_REGISTRY_PROVIDER_UNAVAILABLE",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_cli_auth_registry_provider_unavailable",
            default_suggestion="aeat setup auth providers",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.entrypoints.cli.auth._registry.UnknownProviderError",
        ErrorCode(
            code="AUTH_CLI_AUTH_REGISTRY_UNKNOWN_PROVIDER",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_cli_auth_registry_unknown_provider",
            default_suggestion="aeat setup auth providers",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.auth._sessions.CorruptAuthSessionError",
        ErrorCode(
            code="INTEGRITY_CLI_AUTH_SESSION_CORRUPT_AUTH_SESSION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_cli_auth_session_corrupt_auth_session",
            default_suggestion="aeat setup auth login",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "aeat.application.auth._sessions.AuthSessionUnavailableError",
        ErrorCode(
            code="AUTH_CLI_AUTH_SESSION_UNAVAILABLE",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_cli_auth_session_unavailable",
            default_suggestion="aeat auth login",
            retryable=True,
            runbook_id=None,
        ),
    ),
)
