"""Persistence layer public API.

Public API of the storage subpackage. Callers outside
:mod:`adapters.persistence.storage` must import only from here; internal
modules (``sql._orm``, ``sql.engine``, ``sql.session``, ``sql.repository``,
and the encryption substrate under ``crypto``,
``envelope``, ``master_key``, ``blob_store``, ``secret_store``) are
implementation details.

The phrase **encryption substrate** denotes the layered crypto stack
(master-key provider → envelope wrapper → encrypted blob store →
typed column helpers) that every persisted record passes through.
Throughout the package, "substrate" without a qualifier refers to
this stack.

The public surface is grouped by contract:

- SQL and secure-object persistence — engine/session helpers, typed catalogue
  repositories, :class:`SecureObjectRepository`, and the secure-object work
  records :class:`SecureObjectWrite`, :class:`SecureObjectDeletion`, and
  :class:`SecureObjectNamespaceIntegrity`.
- Inner-envelope version contract — :func:`inner_envelope_version_is_current`,
  the non-raising equality predicate every persisted read path applies to the
  ``schema_version`` of the :class:`Envelope` inside a decrypted payload. The
  layer-one row gate ``ensure_schema_version_readable`` is deliberately absent
  from this facade: it is a ceiling, and advertising it here would offer
  layer-two callers the wrong contract.
- Inner-envelope classification contract — :func:`inner_envelope_classification_is_expected`,
  the version predicate's non-raising sibling, applied to the ``classification``
  of the :class:`Envelope` inside a decrypted payload against the caller's own
  declared :class:`SensitivityClass`.
- Encryption substrate — :class:`Envelope`, :class:`CipherEnvelope`,
  :class:`EncryptedBlobStore`, :class:`SecretStore`, :func:`get_secret_store`
  (the route-canonical store factory), :class:`MasterKeyProvider`, and the
  column-level helpers :class:`EncryptedString`, :class:`EncryptedBytes`,
  :class:`EncryptedJSON`, and :class:`HashedLookup`.
- Runtime and custody boundary — :class:`StorageRuntime`,
  :class:`StorageRuntimeReadiness`, runtime repository factories,
  :func:`activate_session`, :func:`get_active_master_key`,
  :func:`~cadrumo.adapters.persistence.storage.resolve_attachment_store`, the one place a caller holding an optional
  injected :class:`~domain.attachments.AttachmentStoreProtocol` turns it into a
  concrete :class:`AttachmentStore`.
- Recovery — the low-level BIP-39 recovery helpers. The shared-master
  wrapping primitives are gone, and so is the master-key rotation sweep that
  re-wrapped every envelope between two providers: recovery and passphrase
  rotation are both per-profile custody operations.
- Secure-object hierarchy registry — :data:`STORAGE_NAMESPACE_REGISTRY`,
  :data:`STORAGE_PATH_DEFINITIONS`, namespace constants, and
  :func:`secure_object_logical_path` /
  :func:`secure_object_namespace_logical_path`; callers must use these
  exported symbols instead of constructing persisted secure-storage locations
  by hand.
- Governance helpers — :class:`SensitivityClass`, classification policies,
  redaction helpers, corpus manifests, path-safety helpers, and file-lock
  primitives.
"""

from __future__ import annotations

from collections.abc import Callable
from functools import partial
from importlib import import_module
from types import ModuleType
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ....core.classification import (
        AtRestTreatment,
        ClassificationPolicy,
        RedactionRule,
        RedactionStrategy,
        SensitivityClass,
        default_policy_for,
    )
    from ....core.corpus_manifest import (
        CorpusEntry,
        CorpusManifest,
        assert_corpus_clean,
        build_corpus_manifest,
        load_corpus_manifest,
        manifest_path_for,
        save_corpus_manifest,
        verify_corpus_manifest,
    )
    from ....core.locks_errors import LockAcquisitionError
    from ....core.redaction import (
        default_rules,
        default_rules_for,
        default_rules_for_class,
        redact,
        redact_for_log,
        redact_structured,
    )
    from ._kdf_salt import KDF_SALT_BYTES
    from ._namespace_registry import (
        AEAT_BROWSER_SESSION_NAMESPACE,
        AEAT_FILED_DECLARATION_ARTEFACTS_NAMESPACE,
        AEAT_FILED_DECLARATION_OBSERVATIONS_NAMESPACE,
        AEAT_IVA_WALLET_OBSERVATIONS_NAMESPACE,
        APPLICATION_EVIDENCE_BUNDLE_NAMESPACE,
        APPLICATION_FILING_HISTORY_NAMESPACE,
        ATTACHMENT_BLOB_NAMESPACE,
        ATTACHMENT_MANIFEST_NAMESPACE,
        AUTH_APODERADO_CONFIGURATION_NAMESPACE,
        BUCKET_EVENT_HISTORY_NAMESPACE,
        CALCULATION_OBSERVATIONS_NAMESPACE,
        CLAVE_MOVIL_DIAGNOSTICS_NAMESPACE,
        DOMAIN_NAMESPACE_DEFINITIONS,
        FILING_AMENDMENTS_NAMESPACE,
        FILING_DRAFTS_NAMESPACE,
        GOOGLE_CREDENTIAL_SOURCE_NAMESPACE,
        GOOGLE_DRIVE_CONFIG_NAMESPACE,
        GOOGLE_OAUTH_CLIENT_NAMESPACE,
        GOOGLE_OAUTH_METADATA_NAMESPACE,
        GOOGLE_OAUTH_TOKEN_NAMESPACE,
        INVOICE_CATALOGUE_NAMESPACE,
        IVA_COMPENSATION_HISTORY_NAMESPACE,
        IVA_WALLET_RECONCILIATION_DECISION_EVENTS_NAMESPACE,
        IVA_WALLET_RECONCILIATION_DECISIONS_NAMESPACE,
        JUSTIFICANTE_METADATA_NAMESPACE,
        LEDGER_CLASSIFICATION_RULES_NAMESPACE,
        LEDGER_CONFIRMATION_RECORD_NAMESPACE,
        LEDGER_CONFIRMED_COUNTERPARTY_FACTS_NAMESPACE,
        LEDGER_EXTRACTED_DOCUMENT_CACHE_NAMESPACE,
        LEDGER_EXTRACTION_DRAFT_NAMESPACE,
        LEDGER_PURCHASE_INVOICE_EVIDENCE_NAMESPACE,
        LIVE_BORRADOR_100_SNAPSHOT_NAMESPACE,
        LIVE_DEUDAS_SNAPSHOT_NAMESPACE,
        LIVE_EXPEDIENTES_SNAPSHOT_NAMESPACE,
        LIVE_IVA_REMOTE_STATE_ACQUISITIONS_NAMESPACE,
        LIVE_JUSTIFICANTE_CAPTURE_SNAPSHOT_NAMESPACE,
        LIVE_M036_DECLARATION_NAMESPACE,
        LIVE_NOTIFICATION_DOCUMENT_NAMESPACE,
        LIVE_NOTIFICATIONS_SNAPSHOT_NAMESPACE,
        LIVE_VERIFY_OBSERVATION_NAMESPACE,
        LLM_CACHE_NAMESPACE,
        LLM_EVIDENCE_CONSENT_LEDGER_NAMESPACE,
        LLM_RUN_TELEMETRY_NAMESPACE,
        LLM_USAGE_NAMESPACE,
        M145_COMMUNICATION_RECORD_NAMESPACE,
        MODELO_CALCULATION_REVISION_CATALOGUE_NAMESPACE,
        MODELO_FILING_RECORD_CATALOGUE_NAMESPACE,
        MODELO_RECONCILIATION_RECORDS_NAMESPACE,
        MODELO_REVIEW_PACKAGE_RECIPIENT_ENCRYPTION_KEY_NAMESPACE,
        MODELO_REVIEW_PACKAGE_RECIPIENT_FINGERPRINT_REGISTRY_NAMESPACE,
        MODELO_REVIEW_PACKAGE_RECIPIENT_REPLAY_GUARD_NAMESPACE,
        MODELO_REVIEW_PACKAGE_SIGNING_KEY_NAMESPACE,
        MODELO_VERIFICATION_REPORT_CATALOGUE_NAMESPACE,
        MODELO_WORK_UNIT_CATALOGUE_NAMESPACE,
        OPERATION_SECURE_REFERENCE_NAMESPACE,
        PROFILE_ASSETS_AMORTIZATION_LEDGER_NAMESPACE,
        PROFILE_ASSETS_LEDGER_NAMESPACE,
        PROFILE_BIENES_INVERSION_IVA_REGISTER_NAMESPACE,
        PROFILE_INVENTORY_LEDGER_NAMESPACE,
        PROFILE_PRORRATA_REGISTER_NAMESPACE,
        REPAIR_INTEGRITY_DECISION_NAMESPACE,
        RETENCION_OBSERVATIONS_NAMESPACE,
        SECURE_OBJECT_CATALOGUE_KEY,
        SECURE_OBJECT_DEFAULT_KEY,
        SECURE_OBJECT_SCHEMA_VERSION_V1,
        SECURE_OBJECT_SCHEMA_VERSION_V2,
        SECURE_OBJECT_SCHEMA_VERSION_V4,
        SECURE_OBJECT_WORKFLOW_STATE_KEY,
        STORAGE_NAMESPACE_REGISTRY,
        SUBMISSION_RECORDS_NAMESPACE,
        SYNC_RUN_RECORDS_NAMESPACE,
        TEST_SECURE_BOUND_CONTRACT_NAMESPACE,
        TEST_SESSION_LIFECYCLE_NAMESPACE,
        TEST_SNAPSHOT_BASE_PROBE_NAMESPACE,
        TRANSACTION_CATALOGUE_NAMESPACE,
        TRANSACTION_PARTICIPATION_INDEX_NAMESPACE,
        USAGE_RATIO_PROFILE_NAMESPACE,
        USER_PROFILE_SNAPSHOT_NAMESPACE,
        USER_PROFILE_VALUE_NAMESPACE,
        WITHHOLDING_OBSERVATIONS_NAMESPACE,
        WORKFLOW_RUN_NAMESPACE,
        WORKFLOW_STATE_NAMESPACE,
        SecureObjectNamespaceDefinition,
        StorageCustodyDisposition,
        StorageCustodyProfile,
        StorageHierarchyRegistry,
        StorageNamespaceScope,
        StoragePathAnchor,
        StoragePathKind,
        StorageRemoteMirrorPolicy,
        secure_object_logical_path,
        secure_object_namespace_logical_path,
    )
    from ._path_safety import safe_repository_id
    from ._profile_custody import build_profile_custody_port
    from ._profile_login_session import build_profile_login_session_port
    from ._recovery_key import (
        RecoveryKey,
        decode_mnemonic,
        encode_mnemonic,
        generate_recovery_key,
    )
    from ._runtime_readiness import (
        StorageRuntimeReadiness,
        StorageRuntimeReadinessCode,
        StorageRuntimeReadinessIssue,
        StorageRuntimeSession,
    )
    from ._schema_lineage import inner_envelope_classification_is_expected, inner_envelope_version_is_current
    from ._storage_path_definitions import (
        BLOB_MANIFEST_SCHEMA_VERSION,
        BUCKET_BLOBS_DIRNAME,
        BUCKET_DATABASE_FILENAME,
        BUCKET_DB_DIRNAME,
        BUCKET_LOCK_FILENAME,
        BUCKET_MANIFEST_FILENAME,
        BUCKETS_DIRNAME,
        CONFIG_RESET_JOURNAL_DIRNAME,
        KEYSTORE_DIRNAME,
        LOGIN_THROTTLE_FILENAME,
        SECRET_INDEX_FILENAME,
        SECRET_RECORD_SCHEMA_VERSION,
        STORAGE_PATH_DEFINITIONS,
        StoragePathDefinition,
    )
    from .attachment import AttachmentStore, resolve_attachment_store, unwrap_blob_payload
    from .blob_store import (
        BlobManifest,
        BlobReference,
        EncryptedBlobStore,
        get_secret_store,
    )
    from .bucket import RecoveryVerificationError
    from .crypto import (
        GCM_TAG_SIZE,
        KEY_SIZE,
        NONCE_SIZE,
        EncryptedBlob,
        EncryptedBytes,
        EncryptedJSON,
        EncryptedString,
        HashedLookup,
        decrypt_record,
        derive_key,
        encrypt_record,
    )
    from .custody import (
        PROFILE_CUSTODY_ENVELOPE_MAX_BYTES,
        PROFILE_CUSTODY_ENVELOPE_SCHEMA_VERSION,
        PROFILE_CUSTODY_KDF_ITERATIONS,
        PROFILE_CUSTODY_KDF_MEMORY_MIB,
        PROFILE_CUSTODY_KDF_PARALLELISM,
        PROFILE_CUSTODY_PASSWORD_GENERATION_MAX,
        ProfileCustodyEnvelope,
        ProfileCustodyError,
        ProfileCustodyKdfParameters,
        ProfileCustodyPasswordError,
        ProfileCustodyRecordError,
        ProfileCustodyRecoverySecretError,
        ProfileCustodyRefusal,
        ProfileCustodyRefusedError,
        ProfileCustodyWrappedDek,
        parse_profile_custody_envelope,
        profile_custody_path,
    )
    from .envelope import (
        AeadAlgorithm,
        CipherEnvelope,
        EncryptionMetadata,
        Envelope,
        SecureBoundRepository,
        load_encrypted_envelope,
        load_envelope,
        reencrypt_envelope_file,
        save_encrypted_envelope,
        save_envelope,
    )
    from .errors import (
        BlobIntegrityError,
        BlobNotFoundError,
        ClassificationError,
        DecryptionError,
        EncryptionError,
        EnvelopeVersionError,
        KeyDerivationError,
        KeyringUnavailableError,
        MasterKeyMaterialMissingError,
        MasterKeyUnavailableError,
        NonceCollisionError,
        PathContainmentError,
        PersistenceError,
        RepositoryError,
        RetentionPolicyError,
        SecretAlreadyExistsError,
        SecretNotFoundError,
        SecretStoreError,
        SecureObjectRevisionConflictError,
        SecureObjectRowIdentityError,
        StorageError,
        StorageValidationError,
        UnsecuredModeRefusedError,
    )
    from .master_key import (
        ARGON2_VERSION,
        MasterKeyProvider,
        NoActiveBucketSessionError,
        UnsecuredMasterKeyProvider,
        activate_session,
        active_bucket_session_serves,
        bind_active_bucket_session,
        close_active_bucket_session,
        close_all_live_bucket_sessions,
        current_active_bucket_session,
        get_active_master_key,
        has_active_bucket_session,
        looks_like_real_tax_id,
        refuse_unsecured_with_real_nif,
        suspend_active_session,
    )
    from .runtime import (
        StorageRuntime,
        inspect_bucket_storage_runtime,
        inspect_storage_runtime,
    )
    from .runtime_repository import (
        secure_object_repository_for_active_bucket,
        secure_object_repository_for_active_bucket_or_default_route,
        secure_object_repository_for_bucket,
        secure_object_repository_for_cold_bootstrap_state,
        secure_object_repository_for_staged_bucket,
    )
    from .secret_store import (
        SecretRecord,
        SecretStore,
    )
    from .sql import (
        Base,
        SecureObjectDeletion,
        SecureObjectMigrationTarget,
        SecureObjectNamespaceIntegrity,
        SecureObjectRepository,
        SecureObjectWrite,
    )
    from .sql.engine import (
        create_engine_from_settings,
        dispose_engine,
        dispose_engine_handle,
        dispose_engines_for_bucket,
        get_engine,
    )
    from .sql.records import CorpusArtifactRecord, ModeloCatalogueRecord, PortalAuthMethod, PortalRecord
    from .sql.repository import CorpusArtifactRepository, ModeloRepository, PortalRepository, SqlRecordRepository
    from .sql.session import get_sessionmaker, session_scope


# Name -> the one submodule that owns it. Import-time cost of this facade was
# 2.35 s because it eagerly pulled SQLAlchemy, the ORM, the encrypted-column
# helpers and the blob store for every caller, including the supervised
# key-derivation child process, which needs none of them and performs a single
# Argon2id hash. Ownership is unchanged: every name still has exactly one
# canonical home and one import path. Only WHEN the owning submodule executes
# has moved.
_LAZY_EXPORTS: dict[str, str] = {
    "AEAT_BROWSER_SESSION_NAMESPACE": "._namespace_registry",
    "AEAT_FILED_DECLARATION_ARTEFACTS_NAMESPACE": "._namespace_registry",
    "AEAT_FILED_DECLARATION_OBSERVATIONS_NAMESPACE": "._namespace_registry",
    "AEAT_IVA_WALLET_OBSERVATIONS_NAMESPACE": "._namespace_registry",
    "APPLICATION_EVIDENCE_BUNDLE_NAMESPACE": "._namespace_registry",
    "APPLICATION_FILING_HISTORY_NAMESPACE": "._namespace_registry",
    "ARGON2_VERSION": ".master_key",
    "ATTACHMENT_BLOB_NAMESPACE": "._namespace_registry",
    "ATTACHMENT_MANIFEST_NAMESPACE": "._namespace_registry",
    "AUTH_APODERADO_CONFIGURATION_NAMESPACE": "._namespace_registry",
    "AeadAlgorithm": ".envelope",
    "AtRestTreatment": "....core.classification",
    "AttachmentStore": ".attachment",
    "BLOB_MANIFEST_SCHEMA_VERSION": "._storage_path_definitions",
    "BUCKETS_DIRNAME": "._storage_path_definitions",
    "BUCKET_BLOBS_DIRNAME": "._storage_path_definitions",
    "BUCKET_DATABASE_FILENAME": "._storage_path_definitions",
    "BUCKET_DB_DIRNAME": "._storage_path_definitions",
    "BUCKET_EVENT_HISTORY_NAMESPACE": "._namespace_registry",
    "BUCKET_LOCK_FILENAME": "._storage_path_definitions",
    "BUCKET_MANIFEST_FILENAME": "._storage_path_definitions",
    "Base": ".sql",
    "BlobIntegrityError": ".errors",
    "BlobManifest": ".blob_store",
    "BlobNotFoundError": ".errors",
    "BlobReference": ".blob_store",
    "CALCULATION_OBSERVATIONS_NAMESPACE": "._namespace_registry",
    "CLAVE_MOVIL_DIAGNOSTICS_NAMESPACE": "._namespace_registry",
    "CONFIG_RESET_JOURNAL_DIRNAME": "._storage_path_definitions",
    "CipherEnvelope": ".envelope",
    "ClassificationError": ".errors",
    "ClassificationPolicy": "....core.classification",
    "CorpusArtifactRecord": ".sql.records",
    "CorpusArtifactRepository": ".sql.repository",
    "CorpusEntry": "....core.corpus_manifest",
    "CorpusManifest": "....core.corpus_manifest",
    "DOMAIN_NAMESPACE_DEFINITIONS": "._namespace_registry",
    "DecryptionError": ".errors",
    "EncryptedBlob": ".crypto",
    "EncryptedBlobStore": ".blob_store",
    "EncryptedBytes": ".crypto",
    "EncryptedJSON": ".crypto",
    "EncryptedString": ".crypto",
    "EncryptionError": ".errors",
    "EncryptionMetadata": ".envelope",
    "Envelope": ".envelope",
    "EnvelopeVersionError": ".errors",
    "FILING_AMENDMENTS_NAMESPACE": "._namespace_registry",
    "FILING_DRAFTS_NAMESPACE": "._namespace_registry",
    "GCM_TAG_SIZE": ".crypto",
    "GOOGLE_CREDENTIAL_SOURCE_NAMESPACE": "._namespace_registry",
    "GOOGLE_DRIVE_CONFIG_NAMESPACE": "._namespace_registry",
    "GOOGLE_OAUTH_CLIENT_NAMESPACE": "._namespace_registry",
    "GOOGLE_OAUTH_METADATA_NAMESPACE": "._namespace_registry",
    "GOOGLE_OAUTH_TOKEN_NAMESPACE": "._namespace_registry",
    "HashedLookup": ".crypto",
    "INVOICE_CATALOGUE_NAMESPACE": "._namespace_registry",
    "IVA_COMPENSATION_HISTORY_NAMESPACE": "._namespace_registry",
    "IVA_WALLET_RECONCILIATION_DECISIONS_NAMESPACE": "._namespace_registry",
    "IVA_WALLET_RECONCILIATION_DECISION_EVENTS_NAMESPACE": "._namespace_registry",
    "JUSTIFICANTE_METADATA_NAMESPACE": "._namespace_registry",
    "KEYSTORE_DIRNAME": "._storage_path_definitions",
    "KEY_SIZE": ".crypto",
    "KeyDerivationError": ".errors",
    "KDF_SALT_BYTES": "._kdf_salt",
    "KeyringUnavailableError": ".errors",
    "LEDGER_CLASSIFICATION_RULES_NAMESPACE": "._namespace_registry",
    "LEDGER_CONFIRMATION_RECORD_NAMESPACE": "._namespace_registry",
    "LEDGER_CONFIRMED_COUNTERPARTY_FACTS_NAMESPACE": "._namespace_registry",
    "LEDGER_EXTRACTED_DOCUMENT_CACHE_NAMESPACE": "._namespace_registry",
    "LEDGER_EXTRACTION_DRAFT_NAMESPACE": "._namespace_registry",
    "LEDGER_PURCHASE_INVOICE_EVIDENCE_NAMESPACE": "._namespace_registry",
    "LIVE_BORRADOR_100_SNAPSHOT_NAMESPACE": "._namespace_registry",
    "LIVE_DEUDAS_SNAPSHOT_NAMESPACE": "._namespace_registry",
    "LIVE_EXPEDIENTES_SNAPSHOT_NAMESPACE": "._namespace_registry",
    "LIVE_IVA_REMOTE_STATE_ACQUISITIONS_NAMESPACE": "._namespace_registry",
    "LIVE_JUSTIFICANTE_CAPTURE_SNAPSHOT_NAMESPACE": "._namespace_registry",
    "LIVE_M036_DECLARATION_NAMESPACE": "._namespace_registry",
    "LIVE_NOTIFICATIONS_SNAPSHOT_NAMESPACE": "._namespace_registry",
    "LIVE_NOTIFICATION_DOCUMENT_NAMESPACE": "._namespace_registry",
    "LIVE_VERIFY_OBSERVATION_NAMESPACE": "._namespace_registry",
    "LLM_CACHE_NAMESPACE": "._namespace_registry",
    "LLM_EVIDENCE_CONSENT_LEDGER_NAMESPACE": "._namespace_registry",
    "LLM_RUN_TELEMETRY_NAMESPACE": "._namespace_registry",
    "LLM_USAGE_NAMESPACE": "._namespace_registry",
    "LOGIN_THROTTLE_FILENAME": "._storage_path_definitions",
    "LockAcquisitionError": "....core.locks_errors",
    "M145_COMMUNICATION_RECORD_NAMESPACE": "._namespace_registry",
    "MODELO_CALCULATION_REVISION_CATALOGUE_NAMESPACE": "._namespace_registry",
    "MODELO_FILING_RECORD_CATALOGUE_NAMESPACE": "._namespace_registry",
    "MODELO_RECONCILIATION_RECORDS_NAMESPACE": "._namespace_registry",
    "MODELO_REVIEW_PACKAGE_RECIPIENT_ENCRYPTION_KEY_NAMESPACE": "._namespace_registry",
    "MODELO_REVIEW_PACKAGE_RECIPIENT_FINGERPRINT_REGISTRY_NAMESPACE": "._namespace_registry",
    "MODELO_REVIEW_PACKAGE_RECIPIENT_REPLAY_GUARD_NAMESPACE": "._namespace_registry",
    "MODELO_REVIEW_PACKAGE_SIGNING_KEY_NAMESPACE": "._namespace_registry",
    "OPERATION_SECURE_REFERENCE_NAMESPACE": "._namespace_registry",
    "MODELO_VERIFICATION_REPORT_CATALOGUE_NAMESPACE": "._namespace_registry",
    "MODELO_WORK_UNIT_CATALOGUE_NAMESPACE": "._namespace_registry",
    "MasterKeyMaterialMissingError": ".errors",
    "MasterKeyProvider": ".master_key",
    "MasterKeyUnavailableError": ".errors",
    "ModeloCatalogueRecord": ".sql.records",
    "ModeloRepository": ".sql.repository",
    "NONCE_SIZE": ".crypto",
    "NoActiveBucketSessionError": ".master_key",
    "NonceCollisionError": ".errors",
    "PROFILE_ASSETS_AMORTIZATION_LEDGER_NAMESPACE": "._namespace_registry",
    "PROFILE_ASSETS_LEDGER_NAMESPACE": "._namespace_registry",
    "PROFILE_BIENES_INVERSION_IVA_REGISTER_NAMESPACE": "._namespace_registry",
    "PROFILE_CUSTODY_ENVELOPE_MAX_BYTES": ".custody",
    "PROFILE_CUSTODY_ENVELOPE_SCHEMA_VERSION": ".custody",
    "PROFILE_CUSTODY_KDF_ITERATIONS": ".custody",
    "PROFILE_CUSTODY_KDF_MEMORY_MIB": ".custody",
    "PROFILE_CUSTODY_KDF_PARALLELISM": ".custody",
    "PROFILE_CUSTODY_PASSWORD_GENERATION_MAX": ".custody",
    "PROFILE_INVENTORY_LEDGER_NAMESPACE": "._namespace_registry",
    "PROFILE_PRORRATA_REGISTER_NAMESPACE": "._namespace_registry",
    "PathContainmentError": ".errors",
    "PersistenceError": ".errors",
    "PortalAuthMethod": ".sql.records",
    "PortalRecord": ".sql.records",
    "PortalRepository": ".sql.repository",
    "ProfileCustodyEnvelope": ".custody",
    "ProfileCustodyError": ".custody",
    "ProfileCustodyKdfParameters": ".custody",
    "ProfileCustodyPasswordError": ".custody",
    "ProfileCustodyRecordError": ".custody",
    "ProfileCustodyRecoverySecretError": ".custody",
    "ProfileCustodyRefusal": ".custody",
    "ProfileCustodyRefusedError": ".custody",
    "ProfileCustodyWrappedDek": ".custody",
    "REPAIR_INTEGRITY_DECISION_NAMESPACE": "._namespace_registry",
    "RETENCION_OBSERVATIONS_NAMESPACE": "._namespace_registry",
    "RecoveryKey": "._recovery_key",
    "RecoveryVerificationError": ".bucket",
    "RedactionRule": "....core.classification",
    "RedactionStrategy": "....core.classification",
    "RepositoryError": ".errors",
    "RetentionPolicyError": ".errors",
    "SECRET_INDEX_FILENAME": "._storage_path_definitions",
    "SECRET_RECORD_SCHEMA_VERSION": "._storage_path_definitions",
    "SECURE_OBJECT_CATALOGUE_KEY": "._namespace_registry",
    "SECURE_OBJECT_DEFAULT_KEY": "._namespace_registry",
    "SECURE_OBJECT_SCHEMA_VERSION_V1": "._namespace_registry",
    "SECURE_OBJECT_SCHEMA_VERSION_V2": "._namespace_registry",
    "SECURE_OBJECT_SCHEMA_VERSION_V4": "._namespace_registry",
    "SECURE_OBJECT_WORKFLOW_STATE_KEY": "._namespace_registry",
    "STORAGE_NAMESPACE_REGISTRY": "._namespace_registry",
    "STORAGE_PATH_DEFINITIONS": "._storage_path_definitions",
    "SUBMISSION_RECORDS_NAMESPACE": "._namespace_registry",
    "SYNC_RUN_RECORDS_NAMESPACE": "._namespace_registry",
    "SecretAlreadyExistsError": ".errors",
    "SecretNotFoundError": ".errors",
    "SecretRecord": ".secret_store",
    "SecretStore": ".secret_store",
    "SecretStoreError": ".errors",
    "SecureBoundRepository": ".envelope",
    "SecureObjectDeletion": ".sql",
    "SecureObjectMigrationTarget": ".sql",
    "SecureObjectNamespaceDefinition": "._namespace_registry",
    "SecureObjectNamespaceIntegrity": ".sql",
    "SecureObjectRepository": ".sql",
    "SecureObjectRevisionConflictError": ".errors",
    "SecureObjectRowIdentityError": ".errors",
    "SecureObjectWrite": ".sql",
    "SensitivityClass": "....core.classification",
    "SqlRecordRepository": ".sql.repository",
    "StorageCustodyDisposition": "._namespace_registry",
    "StorageCustodyProfile": "._namespace_registry",
    "StorageError": ".errors",
    "StorageHierarchyRegistry": "._namespace_registry",
    "StorageNamespaceScope": "._namespace_registry",
    "StoragePathAnchor": "._namespace_registry",
    "StoragePathDefinition": "._storage_path_definitions",
    "StoragePathKind": "._namespace_registry",
    "StorageRemoteMirrorPolicy": "._namespace_registry",
    "StorageRuntime": ".runtime",
    "StorageRuntimeReadiness": "._runtime_readiness",
    "StorageRuntimeReadinessCode": "._runtime_readiness",
    "StorageRuntimeReadinessIssue": "._runtime_readiness",
    "StorageRuntimeSession": "._runtime_readiness",
    "StorageValidationError": ".errors",
    "TEST_SECURE_BOUND_CONTRACT_NAMESPACE": "._namespace_registry",
    "TEST_SESSION_LIFECYCLE_NAMESPACE": "._namespace_registry",
    "TEST_SNAPSHOT_BASE_PROBE_NAMESPACE": "._namespace_registry",
    "TRANSACTION_CATALOGUE_NAMESPACE": "._namespace_registry",
    "TRANSACTION_PARTICIPATION_INDEX_NAMESPACE": "._namespace_registry",
    "USAGE_RATIO_PROFILE_NAMESPACE": "._namespace_registry",
    "USER_PROFILE_SNAPSHOT_NAMESPACE": "._namespace_registry",
    "USER_PROFILE_VALUE_NAMESPACE": "._namespace_registry",
    "UnsecuredMasterKeyProvider": ".master_key",
    "UnsecuredModeRefusedError": ".errors",
    "WITHHOLDING_OBSERVATIONS_NAMESPACE": "._namespace_registry",
    "WORKFLOW_RUN_NAMESPACE": "._namespace_registry",
    "WORKFLOW_STATE_NAMESPACE": "._namespace_registry",
    "activate_session": ".master_key",
    "active_bucket_session_serves": ".master_key",
    "assert_corpus_clean": "....core.corpus_manifest",
    "bind_active_bucket_session": ".master_key",
    "build_corpus_manifest": "....core.corpus_manifest",
    "build_profile_custody_port": "._profile_custody",
    "build_profile_login_session_port": "._profile_login_session",
    "close_active_bucket_session": ".master_key",
    "close_all_live_bucket_sessions": ".master_key",
    "create_engine_from_settings": ".sql.engine",
    "current_active_bucket_session": ".master_key",
    "decode_mnemonic": "._recovery_key",
    "decrypt_record": ".crypto",
    "default_policy_for": "....core.classification",
    "default_rules": "....core.redaction",
    "default_rules_for": "....core.redaction",
    "default_rules_for_class": "....core.redaction",
    "derive_key": ".crypto",
    "dispose_engine": ".sql.engine",
    "dispose_engine_handle": ".sql.engine",
    "dispose_engines_for_bucket": ".sql.engine",
    "encode_mnemonic": "._recovery_key",
    "encrypt_record": ".crypto",
    "generate_recovery_key": "._recovery_key",
    "get_active_master_key": ".master_key",
    "get_engine": ".sql.engine",
    "get_secret_store": ".blob_store",
    "get_sessionmaker": ".sql.session",
    "has_active_bucket_session": ".master_key",
    "inner_envelope_classification_is_expected": "._schema_lineage",
    "inner_envelope_version_is_current": "._schema_lineage",
    "inspect_bucket_storage_runtime": ".runtime",
    "inspect_storage_runtime": ".runtime",
    "load_corpus_manifest": "....core.corpus_manifest",
    "load_encrypted_envelope": ".envelope",
    "load_envelope": ".envelope",
    "looks_like_real_tax_id": ".master_key",
    "manifest_path_for": "....core.corpus_manifest",
    "parse_profile_custody_envelope": ".custody",
    "profile_custody_path": ".custody",
    "redact": "....core.redaction",
    "redact_for_log": "....core.redaction",
    "redact_structured": "....core.redaction",
    "reencrypt_envelope_file": ".envelope",
    "refuse_unsecured_with_real_nif": ".master_key",
    "resolve_attachment_store": ".attachment",
    "safe_repository_id": "._path_safety",
    "save_corpus_manifest": "....core.corpus_manifest",
    "save_encrypted_envelope": ".envelope",
    "save_envelope": ".envelope",
    "secure_object_logical_path": "._namespace_registry",
    "secure_object_namespace_logical_path": "._namespace_registry",
    "secure_object_repository_for_active_bucket": ".runtime_repository",
    "secure_object_repository_for_active_bucket_or_default_route": ".runtime_repository",
    "secure_object_repository_for_bucket": ".runtime_repository",
    "secure_object_repository_for_cold_bootstrap_state": ".runtime_repository",
    "secure_object_repository_for_staged_bucket": ".runtime_repository",
    "session_scope": ".sql.session",
    "suspend_active_session": ".master_key",
    "unwrap_blob_payload": ".attachment",
    "verify_corpus_manifest": "....core.corpus_manifest",
}


# Every loader target is a closed literal from the map above.  The attribute
# name selects one of these pre-bound loaders; it never becomes an import path.
_LAZY_MODULE_LOADERS: dict[str, Callable[[], ModuleType]] = {
    module_path: partial(import_module, module_path, __name__) for module_path in frozenset(_LAZY_EXPORTS.values())
}


def __getattr__(name: str) -> object:
    """Resolve one public name by importing only the submodule that owns it.

    The resolved value is written into module globals, so only the first
    access to a name goes through this hook; every later one is an ordinary
    global lookup with no import machinery in the path.
    """
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    loader = _LAZY_MODULE_LOADERS.get(module_name)
    if loader is None:
        raise RuntimeError(f"missing lazy loader for {module_name!r}")
    value = getattr(loader(), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Report the full public surface, including names not yet resolved."""
    return sorted(set(__all__) | set(globals()))


__all__ = [
    "AEAT_BROWSER_SESSION_NAMESPACE",
    "AEAT_FILED_DECLARATION_ARTEFACTS_NAMESPACE",
    "AEAT_FILED_DECLARATION_OBSERVATIONS_NAMESPACE",
    "AEAT_IVA_WALLET_OBSERVATIONS_NAMESPACE",
    "APPLICATION_EVIDENCE_BUNDLE_NAMESPACE",
    "APPLICATION_FILING_HISTORY_NAMESPACE",
    "ARGON2_VERSION",
    "ATTACHMENT_BLOB_NAMESPACE",
    "ATTACHMENT_MANIFEST_NAMESPACE",
    "AUTH_APODERADO_CONFIGURATION_NAMESPACE",
    "BLOB_MANIFEST_SCHEMA_VERSION",
    "BUCKETS_DIRNAME",
    "BUCKET_BLOBS_DIRNAME",
    "BUCKET_DATABASE_FILENAME",
    "BUCKET_DB_DIRNAME",
    "BUCKET_EVENT_HISTORY_NAMESPACE",
    "BUCKET_LOCK_FILENAME",
    "BUCKET_MANIFEST_FILENAME",
    "CALCULATION_OBSERVATIONS_NAMESPACE",
    "CLAVE_MOVIL_DIAGNOSTICS_NAMESPACE",
    "CONFIG_RESET_JOURNAL_DIRNAME",
    "DOMAIN_NAMESPACE_DEFINITIONS",
    "FILING_AMENDMENTS_NAMESPACE",
    "FILING_DRAFTS_NAMESPACE",
    "GCM_TAG_SIZE",
    "GOOGLE_CREDENTIAL_SOURCE_NAMESPACE",
    "GOOGLE_DRIVE_CONFIG_NAMESPACE",
    "GOOGLE_OAUTH_CLIENT_NAMESPACE",
    "GOOGLE_OAUTH_METADATA_NAMESPACE",
    "GOOGLE_OAUTH_TOKEN_NAMESPACE",
    "INVOICE_CATALOGUE_NAMESPACE",
    "IVA_COMPENSATION_HISTORY_NAMESPACE",
    "IVA_WALLET_RECONCILIATION_DECISIONS_NAMESPACE",
    "IVA_WALLET_RECONCILIATION_DECISION_EVENTS_NAMESPACE",
    "JUSTIFICANTE_METADATA_NAMESPACE",
    "KDF_SALT_BYTES",
    "KEYSTORE_DIRNAME",
    "KEY_SIZE",
    "LEDGER_CLASSIFICATION_RULES_NAMESPACE",
    "LEDGER_CONFIRMATION_RECORD_NAMESPACE",
    "LEDGER_CONFIRMED_COUNTERPARTY_FACTS_NAMESPACE",
    "LEDGER_EXTRACTED_DOCUMENT_CACHE_NAMESPACE",
    "LEDGER_EXTRACTION_DRAFT_NAMESPACE",
    "LEDGER_PURCHASE_INVOICE_EVIDENCE_NAMESPACE",
    "LIVE_BORRADOR_100_SNAPSHOT_NAMESPACE",
    "LIVE_DEUDAS_SNAPSHOT_NAMESPACE",
    "LIVE_EXPEDIENTES_SNAPSHOT_NAMESPACE",
    "LIVE_IVA_REMOTE_STATE_ACQUISITIONS_NAMESPACE",
    "LIVE_JUSTIFICANTE_CAPTURE_SNAPSHOT_NAMESPACE",
    "LIVE_M036_DECLARATION_NAMESPACE",
    "LIVE_NOTIFICATIONS_SNAPSHOT_NAMESPACE",
    "LIVE_NOTIFICATION_DOCUMENT_NAMESPACE",
    "LIVE_VERIFY_OBSERVATION_NAMESPACE",
    "LLM_CACHE_NAMESPACE",
    "LLM_EVIDENCE_CONSENT_LEDGER_NAMESPACE",
    "LLM_RUN_TELEMETRY_NAMESPACE",
    "LLM_USAGE_NAMESPACE",
    "LOGIN_THROTTLE_FILENAME",
    "M145_COMMUNICATION_RECORD_NAMESPACE",
    "MODELO_CALCULATION_REVISION_CATALOGUE_NAMESPACE",
    "MODELO_FILING_RECORD_CATALOGUE_NAMESPACE",
    "MODELO_RECONCILIATION_RECORDS_NAMESPACE",
    "MODELO_REVIEW_PACKAGE_RECIPIENT_ENCRYPTION_KEY_NAMESPACE",
    "MODELO_REVIEW_PACKAGE_RECIPIENT_FINGERPRINT_REGISTRY_NAMESPACE",
    "MODELO_REVIEW_PACKAGE_RECIPIENT_REPLAY_GUARD_NAMESPACE",
    "MODELO_REVIEW_PACKAGE_SIGNING_KEY_NAMESPACE",
    "MODELO_VERIFICATION_REPORT_CATALOGUE_NAMESPACE",
    "MODELO_WORK_UNIT_CATALOGUE_NAMESPACE",
    "NONCE_SIZE",
    "OPERATION_SECURE_REFERENCE_NAMESPACE",
    "PROFILE_ASSETS_AMORTIZATION_LEDGER_NAMESPACE",
    "PROFILE_ASSETS_LEDGER_NAMESPACE",
    "PROFILE_BIENES_INVERSION_IVA_REGISTER_NAMESPACE",
    "PROFILE_CUSTODY_ENVELOPE_MAX_BYTES",
    "PROFILE_CUSTODY_ENVELOPE_SCHEMA_VERSION",
    "PROFILE_CUSTODY_KDF_ITERATIONS",
    "PROFILE_CUSTODY_KDF_MEMORY_MIB",
    "PROFILE_CUSTODY_KDF_PARALLELISM",
    "PROFILE_CUSTODY_PASSWORD_GENERATION_MAX",
    "PROFILE_INVENTORY_LEDGER_NAMESPACE",
    "PROFILE_PRORRATA_REGISTER_NAMESPACE",
    "REPAIR_INTEGRITY_DECISION_NAMESPACE",
    "RETENCION_OBSERVATIONS_NAMESPACE",
    "SECRET_INDEX_FILENAME",
    "SECRET_RECORD_SCHEMA_VERSION",
    "SECURE_OBJECT_CATALOGUE_KEY",
    "SECURE_OBJECT_DEFAULT_KEY",
    "SECURE_OBJECT_SCHEMA_VERSION_V1",
    "SECURE_OBJECT_SCHEMA_VERSION_V2",
    "SECURE_OBJECT_SCHEMA_VERSION_V4",
    "SECURE_OBJECT_WORKFLOW_STATE_KEY",
    "STORAGE_NAMESPACE_REGISTRY",
    "STORAGE_PATH_DEFINITIONS",
    "SUBMISSION_RECORDS_NAMESPACE",
    "SYNC_RUN_RECORDS_NAMESPACE",
    "TEST_SECURE_BOUND_CONTRACT_NAMESPACE",
    "TEST_SESSION_LIFECYCLE_NAMESPACE",
    "TEST_SNAPSHOT_BASE_PROBE_NAMESPACE",
    "TRANSACTION_CATALOGUE_NAMESPACE",
    "TRANSACTION_PARTICIPATION_INDEX_NAMESPACE",
    "USAGE_RATIO_PROFILE_NAMESPACE",
    "USER_PROFILE_SNAPSHOT_NAMESPACE",
    "USER_PROFILE_VALUE_NAMESPACE",
    "WITHHOLDING_OBSERVATIONS_NAMESPACE",
    "WORKFLOW_RUN_NAMESPACE",
    "WORKFLOW_STATE_NAMESPACE",
    "AeadAlgorithm",
    "AtRestTreatment",
    "AttachmentStore",
    "Base",
    "BlobIntegrityError",
    "BlobManifest",
    "BlobNotFoundError",
    "BlobReference",
    "CipherEnvelope",
    "ClassificationError",
    "ClassificationPolicy",
    "CorpusArtifactRecord",
    "CorpusArtifactRepository",
    "CorpusEntry",
    "CorpusManifest",
    "DecryptionError",
    "EncryptedBlob",
    "EncryptedBlobStore",
    "EncryptedBytes",
    "EncryptedJSON",
    "EncryptedString",
    "EncryptionError",
    "EncryptionMetadata",
    "Envelope",
    "EnvelopeVersionError",
    "HashedLookup",
    "KeyDerivationError",
    "KeyringUnavailableError",
    "LockAcquisitionError",
    "MasterKeyMaterialMissingError",
    "MasterKeyProvider",
    "MasterKeyUnavailableError",
    "ModeloCatalogueRecord",
    "ModeloRepository",
    "NoActiveBucketSessionError",
    "NonceCollisionError",
    "PathContainmentError",
    "PersistenceError",
    "PortalAuthMethod",
    "PortalRecord",
    "PortalRepository",
    "ProfileCustodyEnvelope",
    "ProfileCustodyError",
    "ProfileCustodyKdfParameters",
    "ProfileCustodyPasswordError",
    "ProfileCustodyRecordError",
    "ProfileCustodyRecoverySecretError",
    "ProfileCustodyRefusal",
    "ProfileCustodyRefusedError",
    "ProfileCustodyWrappedDek",
    "RecoveryKey",
    "RecoveryVerificationError",
    "RedactionRule",
    "RedactionStrategy",
    "RepositoryError",
    "RetentionPolicyError",
    "SecretAlreadyExistsError",
    "SecretNotFoundError",
    "SecretRecord",
    "SecretStore",
    "SecretStoreError",
    "SecureBoundRepository",
    "SecureObjectDeletion",
    "SecureObjectMigrationTarget",
    "SecureObjectNamespaceDefinition",
    "SecureObjectNamespaceIntegrity",
    "SecureObjectRepository",
    "SecureObjectRevisionConflictError",
    "SecureObjectRowIdentityError",
    "SecureObjectWrite",
    "SensitivityClass",
    "SqlRecordRepository",
    "StorageCustodyDisposition",
    "StorageCustodyProfile",
    "StorageError",
    "StorageHierarchyRegistry",
    "StorageNamespaceScope",
    "StoragePathAnchor",
    "StoragePathDefinition",
    "StoragePathKind",
    "StorageRemoteMirrorPolicy",
    "StorageRuntime",
    "StorageRuntimeReadiness",
    "StorageRuntimeReadinessCode",
    "StorageRuntimeReadinessIssue",
    "StorageRuntimeSession",
    "StorageValidationError",
    "UnsecuredMasterKeyProvider",
    "UnsecuredModeRefusedError",
    "activate_session",
    "active_bucket_session_serves",
    "assert_corpus_clean",
    "bind_active_bucket_session",
    "build_corpus_manifest",
    "build_profile_custody_port",
    "build_profile_login_session_port",
    "close_active_bucket_session",
    "close_all_live_bucket_sessions",
    "create_engine_from_settings",
    "current_active_bucket_session",
    "decode_mnemonic",
    "decrypt_record",
    "default_policy_for",
    "default_rules",
    "default_rules_for",
    "default_rules_for_class",
    "derive_key",
    "dispose_engine",
    "dispose_engine_handle",
    "dispose_engines_for_bucket",
    "encode_mnemonic",
    "encrypt_record",
    "generate_recovery_key",
    "get_active_master_key",
    "get_engine",
    "get_secret_store",
    "get_sessionmaker",
    "has_active_bucket_session",
    "inner_envelope_classification_is_expected",
    "inner_envelope_version_is_current",
    "inspect_bucket_storage_runtime",
    "inspect_storage_runtime",
    "load_corpus_manifest",
    "load_encrypted_envelope",
    "load_envelope",
    "looks_like_real_tax_id",
    "manifest_path_for",
    "parse_profile_custody_envelope",
    "profile_custody_path",
    "redact",
    "redact_for_log",
    "redact_structured",
    "reencrypt_envelope_file",
    "refuse_unsecured_with_real_nif",
    "resolve_attachment_store",
    "safe_repository_id",
    "save_corpus_manifest",
    "save_encrypted_envelope",
    "save_envelope",
    "secure_object_logical_path",
    "secure_object_namespace_logical_path",
    "secure_object_repository_for_active_bucket",
    "secure_object_repository_for_active_bucket_or_default_route",
    "secure_object_repository_for_bucket",
    "secure_object_repository_for_cold_bootstrap_state",
    "secure_object_repository_for_staged_bucket",
    "session_scope",
    "suspend_active_session",
    "unwrap_blob_payload",
    "verify_corpus_manifest",
]
