"""Read-only walker over AEAT's *Consultar declaraciones presentadas* surface.

The expediente-tree walker (`_walker.walk_expedientes_tree`) walks
``Mis Expedientes`` (``/wlpl/TEWV-CORE/ResumenVlt``) which is a
*procedures* surface — sanciones, recursos, gestión recaudación —
not the canonical filings register. To read the operator's actual
filing history across supported periodic, annual, retention, and
informative declarations, we drive the
``Consultar declaraciones presentadas`` form at
``/wlpl/SCEJ-MANT/CONSUL/index.zul``.

The form is built on the ZK framework. Input ids are generated by the
server and are not stable selectors; automation binds on label text
and visible row structure. The submit action is a real ``Buscar``
button issuing a ZK AJAX RPC; URL parameters alone do not drive
results.

The walker drives the form for one ``(modelo, ejercicio)`` query at
a time. Multi-modelo or multi-year callers invoke the helper once per
query.
"""

from __future__ import annotations

import hashlib
import json
import re
from collections.abc import AsyncIterator, Callable, Mapping
from contextlib import asynccontextmanager
from dataclasses import dataclass
from datetime import UTC, datetime
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import TYPE_CHECKING, Final, Literal
from urllib.parse import parse_qs, urlsplit

from bs4 import BeautifulSoup
from pydantic import AnyHttpUrl, AnyUrl, BaseModel, ConfigDict, Field

from .....core.config import Settings
from .....core.logging import get_logger
from .....core.resources import bundled_path
from .....domain.calculations.registry import (
    CasillaObservation,
    ExportFieldDefinition,
    ParsedExportFieldValue,
    RegistryModeloObservation,
    RegistrySnapshot,
    RegistryValidationError,
    RemoteOperation,
    RemoteStateGuardPolicy,
    assert_remote_operation_allowed,
    build_snapshot,
    load_registry_tree,
    parse_export_payload,
    previous_filing_observation_requirements,
    relation_source_requirements,
    remote_state_policy_from_cross_reference,
    resolve_export_layout,
    resolve_previous_filing_binding_values,
    resolve_relation_values_from_observations,
)
from ....inbound.declaracion import DeclaracionParseError, parse_declaracion_bytes
from .._playwright import BrowserContext, Page, Playwright, PlaywrightError
from ..browser import Profile, opened_browser_page, shared_playwright_runtime
from ._adapter_utils import normalize_response_text
from ._auth_state import storage_state_for_session
from ._errors import (
    JustificanteFetchError,
    SedeNavigationError,
    SedeParseError,
    SedeValidationError,
)
from ._schema import (
    FiledDeclaracionArtefact,
    FiledDeclaracionObservation,
    JustificanteRef,
    ObservedCasillaValue,
    SedeCapture,
)

if TYPE_CHECKING:
    from .....domain.calculations.registry import ModeloRevision
    from ..auth._authenticator import AeatSession


log = get_logger(__name__)


_EXTERNAL = Settings.external_constants()
_DEFAULTS = Settings()
_SEDE_BASE = _EXTERNAL.aeat.domains.www6
_LISTING_URL = f"{_SEDE_BASE}{_EXTERNAL.aeat.sede_paths.declarations_listing}"
_COTEJO_VIEW = f"{_SEDE_BASE}{_EXTERNAL.aeat.sede_paths.cotejo_query}"
_COTEJO_DOC = f"{_SEDE_BASE}{_EXTERNAL.aeat.sede_paths.cotejo_document}"
_COTEJO_PATH_PREFIX = _EXTERNAL.aeat.sede_paths.cotejo_query
_NAVIGATION_TIMEOUT_MS = _DEFAULTS.aeat_browser_navigation_timeout_ms
_FORM_INTERACTION_TIMEOUT_MS = _DEFAULTS.aeat_browser_form_interaction_timeout_ms
_BUSCAR_SETTLE_MS = _DEFAULTS.aeat_browser_buscar_settle_ms
_VER_CLICK_TIMEOUT_MS = _DEFAULTS.aeat_browser_ver_click_timeout_ms
_READ_GUARD_POLICY = RemoteStateGuardPolicy(
    id="aeat-sede-declarations-read",
    evidence_tier="official_source_guidance",
    classification="authenticated_read_surface",
    allowed_hosts=("www6.agenciatributaria.gob.es",),
    synthetic_data_allowed=False,
    requires_authentication=True,
    requires_aeat_authorization=True,
)

# AEAT CSV shape: 8-24 uppercase alphanumeric characters. Mirror
# of ``_CSV_LABEL_RE`` in :mod:`aeat.adapters.inbound.justificante._extract`. Used
# to shape-validate the CSV extracted from a cotejo URL so a
# malformed AEAT response cannot land arbitrary text in the
# downstream :class:`JustificanteRef.pdf_url`.
_CSV_SHAPE_RE = re.compile(r"^[A-Z0-9]{8,24}$")

_STRICT_FROZEN: Final[ConfigDict] = ConfigDict(
    strict=True,
    frozen=True,
    extra="forbid",
)

type FiledDeclaracionArtefactSink = Callable[
    [tuple[str, int, str, str], FiledDeclaracionArtefact, bytes],
    FiledDeclaracionArtefact,
]


class Declaracion(BaseModel):
    """One row from *Consultar declaraciones presentadas*.

    Attributes:
        modelo: AEAT modelo code selected by the caller.
        ejercicio: Tax year (``2024``).
        period: Period token as printed on the row (``"0A"`` for
            annual, ``"1T"``-``"4T"`` for quarterly, ``"01"``-``"12"``
            for monthly modelos).
        expediente_id: AEAT expediente identifier — same shape used
            by the per-modelo capture flow.
        estado: Row state (``"ALTA"``, ``"BAJA"``, ...).
        tipo_solicitud: Optional "Tipo de solicitud" cell (free-text;
            empty for routine filings).
        observaciones: Optional observations cell.
        presented_at: Timestamp of the filing's submission as printed
            in the row (Europe/Madrid, parsed naive then UTC-tagged).
        justificante_link_text: ``"Ver"`` when AEAT exposes the
            justificante PDF directly, ``None`` otherwise.
        archive_link_text: Same for the archived presentation file.
        declaration_copy_link_text: Same for the declaration-copy PDF.
        mode: Structural read-only marker.
    """

    model_config = _STRICT_FROZEN

    modelo: str = Field(min_length=1, max_length=8)
    ejercicio: int = Field(ge=2000, le=2099)
    period: str = Field(min_length=1, max_length=8)
    expediente_id: str = Field(min_length=12, max_length=32)
    estado: str = Field(min_length=1, max_length=16)
    tipo_solicitud: str | None = Field(default=None, max_length=128)
    observaciones: str | None = Field(default=None, max_length=512)
    presented_at: datetime
    justificante_link_text: str | None = Field(default=None, max_length=32)
    archive_link_text: str | None = Field(default=None, max_length=32)
    declaration_copy_link_text: str | None = Field(default=None, max_length=32)
    justificante_cell_index: int = Field(default=7, ge=0)
    archive_cell_index: int | None = Field(default=8, ge=0)
    declaration_copy_cell_index: int | None = Field(default=None, ge=0)
    mode: Literal["read"] = "read"


@asynccontextmanager
async def shared_playwright(
    session: AeatSession,
) -> AsyncIterator[Playwright]:
    """Yield a long-lived Playwright instance for bulk register sweeps.

    `walk_declarations_register` and `capture_declaration` each spin
    up their own Playwright + BrowserSession when called standalone,
    which is fine for one-shot use. Bulk callers
    (e.g. ``aeat sede capture-corpus``) pay ~1s per iteration on
    Playwright startup; wrapping repeated reads in this helper amortises
    that cost across the entire run.

    Usage:

    .. code-block:: python

        async with shared_playwright(session) as pw:
            for modelo in modelos:
                rows = await walk_declarations_register(
                    session, modelo=modelo, ejercicio=ejercicio,
                    playwright=pw,
                )
                for declaration in rows:
                    capture = await capture_declaration(
                        session, declaration, playwright=pw,
                    )

    Args:
        session: Authenticated AEAT session. Validated upfront so
            bulk reads fail fast rather than per-iteration.

    Yields:
        A live :class:`Playwright` instance. Cleaned up automatically
        on exit.

    Raises:
        SedeNavigationError: When the session has no encrypted browser state.
    """
    storage_state_for_session(session)
    async with shared_playwright_runtime() as pw:
        yield pw


class DeclaracionesRegisterSession:
    """Reusable read-only session for AEAT's filed-declarations register."""

    def __init__(self, session: AeatSession, page: Page, context: BrowserContext) -> None:
        self._session = session
        self._page = page
        self._context = context

    async def walk(self, *, modelo: str, ejercicio: int) -> tuple[Declaracion, ...]:
        """Return filed-declaration rows for one ``(modelo, ejercicio)`` query."""

        if not await _drive_search(self._page, modelo=modelo, ejercicio=ejercicio):
            log.info(
                "DeclaracionesRegisterSession.walk: ejercicio unavailable modelo=%s ejercicio=%d",
                modelo,
                ejercicio,
            )
            return ()
        results = _parse_listbox(await self._page.content(), modelo=modelo, ejercicio=ejercicio)
        log.info(
            "DeclaracionesRegisterSession.walk: found %d declaration(s) modelo=%s ejercicio=%d",
            len(results),
            modelo,
            ejercicio,
        )
        return results

    async def capture_observation(
        self,
        declaration: Declaracion,
        *,
        registry_snapshot: RegistrySnapshot | None = None,
        artefact_sink: FiledDeclaracionArtefactSink | None = None,
    ) -> FiledDeclaracionObservation:
        """Capture a normalized filed-declaration observation using the active page."""

        snapshot = registry_snapshot or _registry_snapshot_for_declaration(declaration)
        read_policy = _read_guard_policy_from_snapshot(snapshot)
        if not await _drive_search(
            self._page,
            modelo=declaration.modelo,
            ejercicio=declaration.ejercicio,
            read_policy=read_policy,
        ):
            raise SedeNavigationError(
                f"AEAT declarations register does not offer ejercicio {declaration.ejercicio} "
                f"for modelo {declaration.modelo}",
            )
        row_locator = _row_locator_for_expediente(
            self._page,
            expediente_id=declaration.expediente_id,
        )
        return await _capture_filed_declaration_observation_from_row(
            self._session,
            declaration,
            row_locator=row_locator,
            page=self._page,
            context=self._context,
            registry_snapshot=snapshot,
            artefact_sink=artefact_sink,
        )


@asynccontextmanager
async def open_declarations_register(
    session: AeatSession,
    *,
    settings: Settings | None = None,
    playwright: Playwright | None = None,
) -> AsyncIterator[DeclaracionesRegisterSession]:
    """Open one browser context for repeated filed-declaration register reads."""

    async with _open_register_page(session, settings=settings, playwright=playwright) as (
        page,
        context,
    ):
        yield DeclaracionesRegisterSession(session, page, context)


@asynccontextmanager
async def _open_register_page(
    session: AeatSession,
    *,
    settings: Settings | None = None,
    playwright: Playwright | None = None,
) -> AsyncIterator[tuple[Page, BrowserContext]]:
    """Yield a Playwright ``(page, context)`` bound to the AEAT session.

    Both :func:`walk_declarations_register` and :func:`capture_declaration`
    need the same bringup: validate persisted session state,
    build a :class:`Profile`, spin up Playwright, and create a
    context preloaded with the session cookies. Centralising the
    helper keeps the two callers structurally identical and
    fixes a latent leak where the walker did not close the
    underlying :class:`BrowserSession` after use.

    Args:
        session: Authenticated AEAT session.
        settings: Optional :class:`Settings` override.
        playwright: Optional pre-started :class:`Playwright` instance
            (typically produced by :func:`shared_playwright`). When
            provided, the helper reuses it instead of starting its
            own — saves ~1s per iteration in bulk sweeps. Caller owns
            the lifetime; this helper does not stop a passed-in
            instance.

    Yields:
        A ``(page, context)`` pair. The page is a fresh
        :class:`Page` inside the storage-state-loaded context.

    Raises:
        SedeNavigationError: When the session has no encrypted browser state.
    """
    settings = settings or Settings()
    storage_state = storage_state_for_session(session)
    storage_state_path = session.storage_state_path
    if storage_state_path is None:
        raise SedeNavigationError("AeatSession has no persisted auth session; run `aeat config auth status` first")
    from .....application.workflow._models import require_active_bucket_id

    profile = Profile(
        name=require_active_bucket_id(),
        storage_state_path=storage_state_path,
    )
    if playwright is not None:
        async with _opened_browser_session(playwright, settings, profile, storage_state) as (page, context):
            yield page, context
        return
    async with (
        shared_playwright_runtime() as pw,
        _opened_browser_session(pw, settings, profile, storage_state) as (page, context),
    ):
        yield page, context


@asynccontextmanager
async def _opened_browser_session(
    pw: Playwright,
    settings: Settings,
    profile: Profile,
    storage_state: dict[str, object],
) -> AsyncIterator[tuple[Page, BrowserContext]]:
    """Inner helper: create + tear down a BrowserSession + context."""
    async with opened_browser_page(pw, settings, profile, storage_state=storage_state) as (page, context):
        yield page, context


async def walk_declarations_register(
    session: AeatSession,
    *,
    modelo: str,
    ejercicio: int,
    settings: Settings | None = None,
    playwright: Playwright | None = None,
) -> tuple[Declaracion, ...]:
    """Drive the *Consultar declaraciones presentadas* form for one query.

    Args:
        session: Authenticated AEAT session whose
            ``storage_state_path`` carries valid cookies.
        modelo: Modelo code to query. The form's modelo combobox is matched on the leading
            ``"<modelo> -"`` text.
        ejercicio: Tax year to query (``2024``).
        settings: Optional :class:`Settings` override.
        playwright: Optional pre-started Playwright instance
            (typically from :func:`shared_playwright`). Reused
            across the call to amortise the ~1s startup cost in
            bulk sweeps. When ``None``, a fresh instance is started
            and torn down per call.

    Returns:
        Tuple of :class:`Declaracion` records, one per filing row.
        Empty when AEAT returns "No se han encontrado resultados".

    Raises:
        SedeNavigationError: When the form fails to load, the
            modelo / ejercicio cannot be selected, or Buscar does not
            settle within the timeout.
        SedeParseError: When the result table cannot be parsed.
    """
    async with _open_register_page(session, settings=settings, playwright=playwright) as (
        page,
        _context,
    ):
        if not await _drive_search(page, modelo=modelo, ejercicio=ejercicio):
            log.info(
                "walk_declarations_register: ejercicio unavailable modelo=%s ejercicio=%d",
                modelo,
                ejercicio,
            )
            return ()
        results = _parse_listbox(await page.content(), modelo=modelo, ejercicio=ejercicio)
    log.info(
        "walk_declarations_register: found %d declaration(s) modelo=%s ejercicio=%d",
        len(results),
        modelo,
        ejercicio,
    )
    return results


async def _drive_search(
    page: Page,
    *,
    modelo: str,
    ejercicio: int,
    read_policy: RemoteStateGuardPolicy = _READ_GUARD_POLICY,
) -> bool:
    """Fill the form and click Buscar.

    Raises :class:`SedeNavigationError` early when AEAT redirects to
    the login wall instead of the form (session expired) so callers
    get an actionable error rather than an opaque combobox click
    timeout.
    """
    try:
        _assert_read_http("GET", _LISTING_URL, policy=read_policy)
        await page.goto(
            _LISTING_URL,
            wait_until="networkidle",
            timeout=_NAVIGATION_TIMEOUT_MS,
        )
    except PlaywrightError as exc:
        raise SedeNavigationError(f"goto {_LISTING_URL!r} failed: {exc}") from exc
    await page.wait_for_timeout(1500)
    await _continue_alert_modal(page, read_policy=read_policy)

    final_url = page.url
    if "/wlpl/SCEJ-MANT/CONSUL" not in final_url:
        log.warning(
            "declaraciones register did not load; session may have expired (final_url=%r)",
            final_url,
        )
        raise SedeNavigationError(
            f"declaraciones register did not load (final URL: {final_url!r}); "
            "session likely expired — run `aeat config auth test` and retry",
        )
    # Defensive: even when the URL matches, AEAT sometimes serves a
    # blank shell with no Modelo label until the JS finishes booting.
    try:
        await page.get_by_text("Modelo (*)", exact=True).first.wait_for(
            state="visible",
            timeout=_FORM_INTERACTION_TIMEOUT_MS,
        )
    except PlaywrightError as exc:
        raise SedeNavigationError(
            "declaraciones register form did not render the 'Modelo (*)' "
            f"label within {_FORM_INTERACTION_TIMEOUT_MS}ms; "
            "session likely expired or AEAT served a maintenance page",
        ) from exc

    if not await _select_combobox_value(
        page,
        label_text="Modelo (*)",
        option_match=f"{modelo} -",
        read_policy=read_policy,
    ):
        raise SedeNavigationError(
            f"AEAT declarations register does not offer modelo {modelo!r}",
        )
    if not await _select_combobox_value(
        page,
        label_text="Ejercicio (*)",
        option_match=str(ejercicio),
        read_policy=read_policy,
    ):
        return False

    try:
        _assert_read_browser_action("Buscar", policy=read_policy)
        await (
            page.locator("button.z-button")
            .filter(has_text="Buscar")
            .click(
                timeout=_FORM_INTERACTION_TIMEOUT_MS,
            )
        )
    except PlaywrightError as exc:
        raise SedeNavigationError(f"clicking Buscar failed: {exc}") from exc
    await page.wait_for_timeout(_BUSCAR_SETTLE_MS)
    return True


async def _select_combobox_value(
    page: Page,
    *,
    label_text: str,
    option_match: str,
    read_policy: RemoteStateGuardPolicy = _READ_GUARD_POLICY,
) -> bool:
    """Open the combobox after ``label_text`` and pick an option matching ``option_match``."""
    label = page.get_by_text(label_text, exact=True).first
    button = label.locator('xpath=following::a[contains(@class,"z-combobox-button")][1]')
    try:
        _assert_read_browser_action(label_text, policy=read_policy)
        await button.click(timeout=_FORM_INTERACTION_TIMEOUT_MS)
    except PlaywrightError as exc:
        raise SedeNavigationError(f"opening combobox after label {label_text!r} failed: {exc}") from exc
    await page.wait_for_timeout(400)

    options = page.locator(".z-comboitem-text")
    matching_options = options.filter(has_text=option_match)
    if await matching_options.count() == 0:
        log.info(
            "AEAT combobox option unavailable label=%s option=%s",
            label_text,
            option_match,
        )
        return False

    target = matching_options.first
    try:
        _assert_read_browser_action(option_match, policy=read_policy)
        await target.click(timeout=_FORM_INTERACTION_TIMEOUT_MS)
    except PlaywrightError as exc:
        raise SedeNavigationError(f"selecting option {option_match!r} for {label_text!r} failed: {exc}") from exc
    await page.wait_for_timeout(300)
    return True


async def _continue_alert_modal(
    page: Page,
    *,
    read_policy: RemoteStateGuardPolicy = _READ_GUARD_POLICY,
) -> None:
    """Dismiss AEAT's informational alert modal without opening alert actions."""
    try:
        _assert_read_browser_action("Continuar", policy=read_policy)
        result = await page.evaluate(
            """
            () => {
              const modal = document.querySelector("#alertsModal");
              if (!modal) return "absent";
              const style = window.getComputedStyle(modal);
              if (style.display === "none" || style.visibility === "hidden") return "hidden";
              const buttons = [...modal.querySelectorAll("button")];
              const continueButton = buttons.find((button) =>
                (button.textContent || "").trim().toLowerCase() === "continuar"
              );
              if (!continueButton) {
                throw new Error("AEAT alert modal has no Continuar button");
              }
              continueButton.click();
              return "continued";
            }
            """
        )
    except PlaywrightError as exc:
        raise SedeNavigationError(f"continuing AEAT alert modal failed: {exc}") from exc
    if result == "continued":
        await page.wait_for_timeout(500)


_NO_RESULTS_TEXT = "No se han encontrado resultados para la consulta realizada."


def _has_class(target: str):
    """Return a bs4 ``class_=`` matcher that yields ``True`` when ``target`` is present.

    bs4's ``find`` / ``find_all`` accept a callable for the ``class_``
    keyword that must return ``bool``. Returning a truthy non-bool
    value (e.g. ``str``) trips ty's ``Tag.find`` overload checks.
    """

    def _matcher(value: str | list[str] | None) -> bool:
        if not value:
            return False
        classes = value if isinstance(value, list) else [value]
        return target in classes

    return _matcher


def _parse_listbox(
    html: str,
    *,
    modelo: str,
    ejercicio: int,
) -> tuple[Declaracion, ...]:
    """Parse the post-Buscar listbox into typed Declaracion records.

    The listbox columns, in order:

    0. Desistir          (action button — ignored)
    1. Tipo de solicitud (free text)
    2. Observaciones     (free text)
    3. Expediente
    4. Periodo
    5. Estado
    6. Fecha y Hora de presentación
    7. Obtención de Justificante (anchor / "Ver")
    8. Descarga fichero presentado (anchor / "Ver")
    """
    try:
        soup = BeautifulSoup(html, "html.parser")
    except Exception as exc:
        raise SedeParseError(f"failed to parse declaraciones HTML: {exc}") from exc

    listbox = soup.find(class_=_has_class("z-listbox"))
    if listbox is None:
        raise SedeParseError("declaraciones response missing .z-listbox container")

    action_indexes = _listbox_action_indexes(listbox)
    if action_indexes is None:
        justificante_index: int | None = 7
        archive_index: int | None = 8
        declaration_copy_index: int | None = None
    else:
        justificante_index = action_indexes.justificante
        archive_index = action_indexes.submitted_file
        declaration_copy_index = action_indexes.declaration_pdf
    if justificante_index is None:
        raise SedeParseError("declaraciones response missing justificante column")
    items = listbox.find_all(class_=_has_class("z-listitem"))

    rows: list[Declaracion] = []
    for item in items:
        cells = item.find_all(class_=_has_class("z-listcell"))
        cell_texts = [cell.get_text(" ", strip=True) for cell in cells]

        if len(cell_texts) == 1 and cell_texts[0] == _NO_RESULTS_TEXT:
            return ()

        if len(cell_texts) < 7:
            # Defensive: skip malformed rows; AEAT layout changes
            # would manifest here. The grep guard at the
            # subpackage level catches forbidden mutation verbs
            # so this is structural-shape only.
            log.debug("_parse_listbox: skipping malformed row with %d cell(s)", len(cell_texts))
            continue

        try:
            presented_at = _parse_presented_at(cell_texts[6])
        except ValueError as exc:
            raise SedeParseError(f"failed to parse presented_at {cell_texts[6]!r}: {exc}") from exc

        rows.append(
            Declaracion(
                modelo=modelo,
                ejercicio=ejercicio,
                period=cell_texts[4],
                expediente_id=cell_texts[3],
                estado=cell_texts[5],
                tipo_solicitud=cell_texts[1] or None,
                observaciones=cell_texts[2] or None,
                presented_at=presented_at,
                justificante_link_text=_cell_text(cell_texts, justificante_index),
                archive_link_text=_cell_text(cell_texts, archive_index),
                declaration_copy_link_text=_cell_text(cell_texts, declaration_copy_index),
                justificante_cell_index=justificante_index,
                archive_cell_index=archive_index,
                declaration_copy_cell_index=declaration_copy_index,
            )
        )
    return tuple(rows)


@dataclass(slots=True, frozen=True)
class _ListboxActionIndexes:
    """Column indexes for the three action links in the declaraciones listbox."""

    justificante: int | None = None
    submitted_file: int | None = None
    declaration_pdf: int | None = None


def _listbox_action_indexes(listbox) -> _ListboxActionIndexes | None:
    headers = listbox.find_all(class_=_has_class("z-listheader"))
    if not headers:
        return None
    justificante: int | None = None
    submitted_file: int | None = None
    declaration_pdf: int | None = None
    for index, header in enumerate(headers):
        label = normalize_response_text(header.get_text(" ", strip=True))
        if "justificante" in label:
            justificante = index
        elif "fichero presentado" in label or ("descarga" in label and "fichero" in label):
            submitted_file = index
        elif "copia" in label and "declaracion" in label:
            declaration_pdf = index
    return _ListboxActionIndexes(
        justificante=justificante,
        submitted_file=submitted_file,
        declaration_pdf=declaration_pdf,
    )


def _cell_text(cell_texts: list[str], index: int | None) -> str | None:
    if index is None or index >= len(cell_texts):
        return None
    return cell_texts[index] or None


_PRESENTED_AT_RE = re.compile(
    r"^(?P<day>\d{2})/(?P<month>\d{2})/(?P<year>\d{4})\s+"
    r"(?P<hour>\d{2}):(?P<minute>\d{2}):(?P<second>\d{2})$",
)


def _parse_presented_at(value: str) -> datetime:
    """Parse ``"01/02/2024 19:15:34"`` → UTC-tagged datetime.

    AEAT prints the timestamp in Europe/Madrid local time. The
    sede walker stores naive datetimes as the wall-clock observed
    on the row and tags them UTC for type discipline; downstream
    callers that need strict timezone alignment should convert via
    Europe/Madrid → UTC outside this module.
    """
    match = _PRESENTED_AT_RE.match(value)
    if match is None:
        raise SedeValidationError(f"unexpected presented_at shape: {value!r}")
    return datetime(
        year=int(match["year"]),
        month=int(match["month"]),
        day=int(match["day"]),
        hour=int(match["hour"]),
        minute=int(match["minute"]),
        second=int(match["second"]),
        tzinfo=UTC,
    )


async def capture_declaration(
    session: AeatSession,
    declaration: Declaracion,
    *,
    settings: Settings | None = None,
    playwright: Playwright | None = None,
) -> SedeCapture:
    """Fetch the raw justificante PDF behind a :class:`Declaracion`.

    Drives the declaraciones register the same way
    :func:`walk_declarations_register` does, locates the row whose
    ``expediente_id`` matches ``declaration.expediente_id``, clicks
    that row's *Obtención de Justificante* button, captures the
    CSV from the resulting cotejo URL, and downloads the PDF via
    :class:`APIRequestContext` (so Chrome's PDF viewer never
    intercepts the response).

    Args:
        session: Authenticated AEAT session.
        declaration: The Declaracion row to capture, typically
            obtained from :func:`walk_declarations_register`.
        settings: Optional :class:`Settings` override.
        playwright: Optional pre-started Playwright instance
            (typically from :func:`shared_playwright`). Reused
            across the call to amortise the ~1s startup cost in
            bulk sweeps. When ``None``, a fresh instance is started
            and torn down per call.

    Returns:
        A :class:`SedeCapture` whose ``ref`` carries the resolved
        CSV / cotejo URL / PDF URL and whose ``pdf_bytes`` carries
        the raw response body.

    Raises:
        SedeNavigationError: When the form drive or row click fails.
        SedeParseError: When the cotejo URL cannot be parsed for
            its CSV.
        JustificanteFetchError: When the PDF GET returns non-2xx,
        an empty body, or a non-PDF content type.
    """
    read_policy = _read_guard_policy_from_snapshot(_registry_snapshot_for_declaration(declaration))
    async with _open_register_page(session, settings=settings, playwright=playwright) as (
        page,
        context,
    ):
        if not await _drive_search(
            page,
            modelo=declaration.modelo,
            ejercicio=declaration.ejercicio,
            read_policy=read_policy,
        ):
            raise SedeNavigationError(
                f"AEAT declarations register does not offer ejercicio {declaration.ejercicio} "
                f"for modelo {declaration.modelo}",
            )

        row_locator = _row_locator_for_expediente(
            page,
            expediente_id=declaration.expediente_id,
        )
        ver_button = row_locator.locator(
            '.z-listcell:has-text("Ver") .z-button',
        ).first

        try:
            async with context.expect_page(
                timeout=_VER_CLICK_TIMEOUT_MS,
            ) as new_page_info:
                _assert_read_browser_action("Ver", policy=read_policy)
                await ver_button.click(timeout=_FORM_INTERACTION_TIMEOUT_MS)
            cotejo_page = await new_page_info.value
        except PlaywrightError as exc:
            raise SedeNavigationError(
                f"clicking Ver for {declaration.expediente_id!r} failed: {exc}",
            ) from exc

        try:
            await cotejo_page.wait_for_load_state(
                "domcontentloaded",
                timeout=_NAVIGATION_TIMEOUT_MS,
            )
        except PlaywrightError as exc:
            raise SedeNavigationError(
                f"cotejo page did not settle for {declaration.expediente_id!r}: {exc}",
            ) from exc

        cotejo_url = cotejo_page.url
        if _COTEJO_PATH_PREFIX not in cotejo_url:
            raise SedeNavigationError(
                f"Ver button for {declaration.expediente_id!r} did not land on a "
                f"cotejo URL (final URL: {cotejo_url!r}); "
                "session likely expired mid-walk — run `aeat config auth test` and retry",
            )

        csv = _extract_csv_from_url(cotejo_url)

        ref = JustificanteRef(
            csv=csv,
            expediente_id=declaration.expediente_id,
            cotejo_url=AnyHttpUrl(f"{_COTEJO_VIEW}?CSV={csv}"),
            pdf_url=AnyHttpUrl(f"{_COTEJO_DOC}?CSV={csv}"),
        )

        _assert_read_http("GET", str(ref.pdf_url), policy=read_policy)
        pdf_response = await context.request.get(str(ref.pdf_url))
        if not (200 <= pdf_response.status < 300):
            raise JustificanteFetchError(
                f"pdf fetch for CSV={csv!r} returned HTTP {pdf_response.status}",
            )
        content_type = pdf_response.headers.get("content-type", "")
        body = await pdf_response.body()
        if not body:
            raise JustificanteFetchError(f"empty PDF body for CSV={csv!r}")
        if "pdf" not in content_type.lower():
            raise JustificanteFetchError(
                f"unexpected content-type {content_type!r} for CSV={csv!r}",
            )

        from ._schema import Expediente

        sha256 = hashlib.sha256(body).hexdigest()
        log.info(
            "capture_declaration: captured PDF expediente=%s CSV=%s size=%d sha256=%s",
            declaration.expediente_id,
            csv,
            len(body),
            sha256[:16],
        )
        return SedeCapture(
            expediente=Expediente(
                expediente_id=declaration.expediente_id,
                modelo=declaration.modelo,
                ejercicio=declaration.ejercicio,
                category_path=("Declaraciones presentadas",),
                detail_url=AnyHttpUrl(
                    f"{_LISTING_URL}?MODELO={declaration.modelo}&EJERCICIO={declaration.ejercicio}",
                ),
            ),
            ref=ref,
            pdf_bytes=body,
            pdf_sha256=sha256,
            captured_at=datetime.now(UTC),
        )


async def capture_filed_declaration_observation(
    session: AeatSession,
    declaration: Declaracion,
    *,
    registry_snapshot: RegistrySnapshot | None = None,
    settings: Settings | None = None,
    playwright: Playwright | None = None,
    artefact_sink: FiledDeclaracionArtefactSink | None = None,
) -> FiledDeclaracionObservation:
    """Capture normalized read-only evidence for one filed declaration.

    The observation begins with the register row and then captures every
    AEAT-served artefact this backend knows how to read from the row:
    the justificante/declaration PDF and, when exposed by AEAT, the
    submitted file download. Submitted files are parsed through the
    registry export layout selected for the declaration snapshot.
    """
    authenticated_identity = (session.identity_nif or "").strip()
    if not authenticated_identity:
        raise SedeNavigationError("AeatSession.identity_nif is empty; cannot bind live filing observation")
    snapshot = registry_snapshot or _registry_snapshot_for_declaration(declaration)
    read_policy = _read_guard_policy_from_snapshot(snapshot)
    async with _open_register_page(session, settings=settings, playwright=playwright) as (
        page,
        context,
    ):
        if not await _drive_search(
            page,
            modelo=declaration.modelo,
            ejercicio=declaration.ejercicio,
            read_policy=read_policy,
        ):
            raise SedeNavigationError(
                f"AEAT declarations register does not offer ejercicio {declaration.ejercicio} "
                f"for modelo {declaration.modelo}",
            )

        row_locator = _row_locator_for_expediente(
            page,
            expediente_id=declaration.expediente_id,
        )
        return await _capture_filed_declaration_observation_from_row(
            session,
            declaration,
            row_locator=row_locator,
            page=page,
            context=context,
            registry_snapshot=snapshot,
            artefact_sink=artefact_sink,
        )


async def _capture_filed_declaration_observation_from_row(
    session: AeatSession,
    declaration: Declaracion,
    *,
    row_locator,
    page: Page,
    context: BrowserContext,
    registry_snapshot: RegistrySnapshot | None,
    artefact_sink: FiledDeclaracionArtefactSink | None,
) -> FiledDeclaracionObservation:
    authenticated_identity = (session.identity_nif or "").strip()
    if not authenticated_identity:
        raise SedeNavigationError("AeatSession.identity_nif is empty; cannot bind live filing observation")
    snapshot = registry_snapshot or _registry_snapshot_for_declaration(declaration)
    read_policy = _read_guard_policy_from_snapshot(snapshot)
    observation_key = (
        declaration.modelo,
        declaration.ejercicio,
        declaration.period,
        declaration.expediente_id,
    )
    listing_url = AnyHttpUrl(f"{_LISTING_URL}?MODELO={declaration.modelo}&EJERCICIO={declaration.ejercicio}")

    register_row, register_row_body = _register_row_artefact(declaration, source_url=listing_url)
    artefacts: list[FiledDeclaracionArtefact] = [
        _store_artefact(
            artefact_sink,
            observation_key=observation_key,
            artefact=register_row,
            body=register_row_body,
        ),
    ]
    casillas: tuple[ObservedCasillaValue, ...] = ()
    extraction_coverage: dict[str, float] = {}
    metadata = {
        "tipo_solicitud": declaration.tipo_solicitud or "",
        "observaciones": declaration.observaciones or "",
    }

    justificante, justificante_body = await _capture_row_pdf_artefact(
        context=context,
        row_locator=row_locator,
        declaration=declaration,
        cell_index=declaration.justificante_cell_index,
        kind="justificante_pdf",
        read_policy=read_policy,
    )
    artefacts.append(
        _store_artefact(
            artefact_sink,
            observation_key=observation_key,
            artefact=justificante,
            body=justificante_body,
        )
    )

    declaration_pdf_body: bytes | None = None
    if declaration.declaration_copy_link_text and declaration.declaration_copy_cell_index is not None:
        declaration_pdf, declaration_pdf_body = await _capture_row_pdf_artefact(
            context=context,
            row_locator=row_locator,
            declaration=declaration,
            cell_index=declaration.declaration_copy_cell_index,
            kind="declaration_pdf",
            read_policy=read_policy,
        )
        artefacts.append(
            _store_artefact(
                artefact_sink,
                observation_key=observation_key,
                artefact=declaration_pdf,
                body=declaration_pdf_body,
            )
        )

    if declaration.archive_link_text and declaration.archive_cell_index is not None:
        try:
            submitted_artefact, submitted_body = await _capture_submitted_file_artefact(
                page=page,
                row_locator=row_locator,
                declaration=declaration,
                cell_index=declaration.archive_cell_index,
                read_policy=read_policy,
            )
        except (JustificanteFetchError, SedeNavigationError) as exc:
            metadata["submitted_file_capture_error"] = str(exc)
        else:
            submitted_artefact = _store_artefact(
                artefact_sink,
                observation_key=observation_key,
                artefact=submitted_artefact,
                body=submitted_body,
            )
            artefacts.append(submitted_artefact)
            try:
                casillas = _observed_casillas_from_submitted_file(
                    snapshot=snapshot,
                    declaration=declaration,
                    body=submitted_body,
                    artefact=submitted_artefact,
                )
                try:
                    resolved_layout = resolve_export_layout(snapshot)
                except RegistryValidationError as exc:
                    if snapshot.modelo.id == "303" and "has no exports" in str(exc):
                        extraction_coverage["submitted_file"] = 1.0
                    else:
                        raise
                else:
                    if resolved_layout.layout.format == "xml_dictionary":
                        extraction_coverage["submitted_file"] = 1.0
                    else:
                        expected_casillas = len(resolved_layout.fields_by_casilla)
                        extraction_coverage["submitted_file"] = (
                            len(casillas) / expected_casillas if expected_casillas else 0.0
                        )
            except (RegistryValidationError, SedeParseError) as exc:
                metadata["submitted_file_extraction_error"] = str(exc)

    if not casillas and declaration_pdf_body is not None:
        casillas = _observed_casillas_from_declaration_pdf(
            snapshot=snapshot,
            declaration=declaration,
            body=declaration_pdf_body,
        )
        extraction_coverage["declaration_pdf"] = 1.0
    elif not casillas and not declaration.archive_link_text and declaration_pdf_body is None:
        raise SedeParseError(
            f"AEAT declaration {declaration.expediente_id!r} did not expose submitted-file or declaration-copy data"
        )

    return FiledDeclaracionObservation(
        modelo=declaration.modelo,
        ejercicio=declaration.ejercicio,
        period=declaration.period,
        expediente_id=declaration.expediente_id,
        status=declaration.estado,
        presented_at=declaration.presented_at,
        authenticated_identity=authenticated_identity,
        artefacts=tuple(artefacts),
        casillas=casillas,
        metadata=metadata,
        extraction_coverage=extraction_coverage,
        registry_snapshot_id=f"{snapshot.modelo.id}:{snapshot.revision.id}:{declaration.ejercicio}:{declaration.period}",
    )


async def capture_previous_filing_observations(
    session: AeatSession,
    revision: ModeloRevision,
    *,
    filing_year: int,
    period: str,
    settings: Settings | None = None,
    playwright: Playwright | None = None,
    artefact_sink: FiledDeclaracionArtefactSink | None = None,
) -> tuple[FiledDeclaracionObservation, ...]:
    """Capture filed declarations required by registry previous-filing bindings."""

    observations: list[FiledDeclaracionObservation] = []
    async with open_declarations_register(session, settings=settings, playwright=playwright) as register:
        for requirement in previous_filing_observation_requirements(revision, filing_year=filing_year, period=period):
            rows = await register.walk(modelo=requirement.modelo, ejercicio=requirement.filing_year)
            matches = tuple(row for row in rows if row.period == requirement.period)
            declaration = _select_authoritative_declaration(
                matches,
                modelo=requirement.modelo,
                ejercicio=requirement.filing_year,
                period=requirement.period,
                context="previous-filing requirement",
            )
            observation = await register.capture_observation(declaration, artefact_sink=artefact_sink)
            observation = _with_derived_303_compensation_available_observation(observation)
            observed_casillas = {casilla.casilla_id for casilla in observation.casillas}
            missing = sorted(set(requirement.source_casillas).difference(observed_casillas))
            if missing:
                raise SedeParseError(
                    f"previous-filing requirement {requirement.modelo!r}/"
                    f"{requirement.filing_year}/{requirement.period!r} missing observed casillas {missing!r}"
                )
            observations.append(observation)
    return tuple(observations)


async def capture_relation_source_observations(
    session: AeatSession,
    revision: ModeloRevision,
    *,
    filing_year: int,
    period: str,
    settings: Settings | None = None,
    playwright: Playwright | None = None,
    artefact_sink: FiledDeclaracionArtefactSink | None = None,
) -> tuple[FiledDeclaracionObservation, ...]:
    """Capture filed declarations required by registry cross-model relations."""

    required_outputs: dict[tuple[str, int, str], set[str]] = {}
    for requirement in relation_source_requirements(revision, filing_year=filing_year, period=period):
        for source_period in requirement.periods:
            key = (requirement.source_modelo, requirement.filing_year, source_period)
            required_outputs.setdefault(key, set()).add(requirement.source_output)

    observations: list[FiledDeclaracionObservation] = []
    async with open_declarations_register(session, settings=settings, playwright=playwright) as register:
        for (modelo, source_year, source_period), source_outputs in sorted(required_outputs.items()):
            rows = await register.walk(modelo=modelo, ejercicio=source_year)
            matches = tuple(row for row in rows if row.period == source_period)
            declaration = _select_authoritative_declaration(
                matches,
                modelo=modelo,
                ejercicio=source_year,
                period=source_period,
                context="relation source requirement",
            )
            observation = await register.capture_observation(declaration, artefact_sink=artefact_sink)
            observation = _with_derived_303_compensation_available_observation(observation)
            observed_casillas = {casilla.casilla_id for casilla in observation.casillas}
            missing = sorted(source_outputs.difference(observed_casillas))
            if missing:
                raise SedeParseError(
                    f"relation source requirement {modelo!r}/{source_year}/{source_period!r} "
                    f"missing observed casillas {missing!r}"
                )
            observations.append(observation)
    return tuple(observations)


def _select_authoritative_declaration(
    declarations: tuple[Declaracion, ...],
    *,
    modelo: str,
    ejercicio: int,
    period: str,
    context: str,
) -> Declaracion:
    """Select the latest accepted register row for one filed period."""

    if not declarations:
        raise SedeParseError(f"{context} {modelo!r}/{ejercicio}/{period!r} found no filed declaration")
    active = tuple(row for row in declarations if row.estado.upper() == "ALTA")
    candidates = active or declarations
    return max(candidates, key=lambda row: (row.presented_at, row.expediente_id))


def _register_row_artefact(
    declaration: Declaracion,
    *,
    source_url: AnyHttpUrl,
) -> tuple[FiledDeclaracionArtefact, bytes]:
    payload = json.dumps(
        declaration.model_dump(mode="json"),
        ensure_ascii=True,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    captured_at = datetime.now(UTC)
    return (
        FiledDeclaracionArtefact(
            kind="register_row",
            source_url=source_url,
            content_type="application/json",
            byte_count=len(payload),
            sha256=hashlib.sha256(payload).hexdigest(),
            captured_at=captured_at,
        ),
        payload,
    )


def _store_artefact(
    artefact_sink: FiledDeclaracionArtefactSink | None,
    *,
    observation_key: tuple[str, int, str, str],
    artefact: FiledDeclaracionArtefact,
    body: bytes,
) -> FiledDeclaracionArtefact:
    if artefact_sink is None:
        return artefact
    return artefact_sink(observation_key, artefact, body)


def _registry_snapshot_for_declaration(declaration: Declaracion) -> RegistrySnapshot:
    modelos, catalogues = load_registry_tree(bundled_path("registry", "aeat"))
    modelo = next((candidate for candidate in modelos if candidate.id == declaration.modelo), None)
    if modelo is None:
        raise SedeParseError(f"registry has no modelo definition for AEAT declaration {declaration.modelo!r}")
    return build_snapshot(
        modelo,
        catalogues,
        source_root=bundled_path(),
        filing_year=declaration.ejercicio,
        period=declaration.period,
    )


def _read_guard_policy_from_snapshot(snapshot: RegistrySnapshot) -> RemoteStateGuardPolicy:
    listing_host = urlsplit(_LISTING_URL).hostname
    if listing_host is None:
        raise RegistryValidationError(f"invalid declarations listing URL: {_LISTING_URL!r}")
    matching_decisions = tuple(
        decision
        for decision in snapshot.live_cross_references.values()
        if decision.surface == "authenticated_read_surface"
        and listing_host.lower() in {host.lower() for host in decision.allowed_hosts}
    )
    if len(matching_decisions) != 1:
        decision_ids = ", ".join(sorted(decision.id for decision in matching_decisions)) or "none"
        raise RegistryValidationError(
            f"expected exactly one authenticated declarations read surface for modelo "
            f"{snapshot.modelo.id} revision {snapshot.revision.id}; found {decision_ids}"
        )
    return remote_state_policy_from_cross_reference(matching_decisions[0])


def _observed_casillas_from_submitted_file(
    *,
    snapshot: RegistrySnapshot,
    declaration: Declaracion,
    body: bytes,
    artefact: FiledDeclaracionArtefact,
) -> tuple[ObservedCasillaValue, ...]:
    try:
        resolved = resolve_export_layout(snapshot)
    except RegistryValidationError as exc:
        if snapshot.modelo.id == "303" and "has no exports" in str(exc):
            return _observed_modelo_303_casillas_from_submitted_file(declaration=declaration, body=body)
        raise
    parsed = parse_export_payload(
        resolved.layout,
        body,
        source_root=bundled_path(),
        sources=snapshot.sources,
    )
    _verify_submitted_file_context(resolved.fields_by_id, parsed.fields, declaration=declaration)
    observations: list[ObservedCasillaValue] = []
    for casilla in parsed.casillas:
        if casilla.casilla_id is None or casilla.value is None:
            continue
        observations.append(
            ObservedCasillaValue(
                casilla_id=casilla.casilla_id,
                value=str(casilla.value),
                source_artefact_kind="submitted_file",
                source_locator=casilla.source_locator,
                confidence=1.0,
            )
        )
    if not observations:
        raise SedeParseError(f"submitted-file artefact {artefact.sha256[:16]} did not yield casilla observations")
    return tuple(observations)


_MODELO_303_PAGE_03_TAG = "<T30303000>"
_MODELO_303_PAGE_03_END_TAG = "</T30303000>"
_MODELO_303_PAGE_03_RECORD_LENGTH = 1017
_MODELO_303_PAGE_03_MONEY_FIELDS: Final[Mapping[str, tuple[int, int]]] = {
    "110": (255, 17),
    "78": (272, 17),
    "87": (289, 17),
    "69": (323, 17),
    "71": (374, 17),
}


def _observed_modelo_303_casillas_from_submitted_file(
    *,
    declaration: Declaracion,
    body: bytes,
) -> tuple[ObservedCasillaValue, ...]:
    """Parse official Modelo 303 page-03 fixed-width result fields."""

    text = body.decode("latin-1", errors="replace")
    page_start = text.find(_MODELO_303_PAGE_03_TAG)
    if page_start < 0:
        raise SedeParseError(f"submitted Modelo 303 file for {declaration.expediente_id!r} has no page-03 record")
    page = text[page_start : page_start + _MODELO_303_PAGE_03_RECORD_LENGTH]
    if len(page) != _MODELO_303_PAGE_03_RECORD_LENGTH:
        raise SedeParseError(
            f"submitted Modelo 303 file for {declaration.expediente_id!r} has truncated page-03 record"
        )
    if not page.startswith(_MODELO_303_PAGE_03_TAG):
        raise SedeParseError(f"submitted Modelo 303 file for {declaration.expediente_id!r} has invalid page-03 header")
    if page[1005:1017] != _MODELO_303_PAGE_03_END_TAG:
        raise SedeParseError(f"submitted Modelo 303 file for {declaration.expediente_id!r} has invalid page-03 footer")
    observations: list[ObservedCasillaValue] = []
    for casilla_id, (position, width) in _MODELO_303_PAGE_03_MONEY_FIELDS.items():
        raw = page[position - 1 : position - 1 + width]
        if len(raw) != width:
            raise SedeParseError(
                f"submitted Modelo 303 file for {declaration.expediente_id!r} has truncated casilla {casilla_id}"
            )
        value = _parse_modelo_303_money(raw, casilla_id=casilla_id)
        observations.append(
            ObservedCasillaValue(
                casilla_id=casilla_id,
                value=str(value),
                source_artefact_kind="submitted_file",
                source_locator=f"record:T30303:pos:{position}:width:{width}",
                confidence=1.0,
            )
        )
    return tuple(observations)


def _parse_modelo_303_money(raw: str, *, casilla_id: str) -> Decimal:
    """Parse AEAT fixed-width 15+2 money, with leading ``N`` for negatives."""

    value = raw.strip()
    if not value:
        return Decimal("0.00")
    sign = Decimal("-1") if value.startswith("N") else Decimal("1")
    digits = value[1:] if value.startswith("N") else value
    if not digits.isdigit():
        raise SedeParseError(f"submitted Modelo 303 casilla {casilla_id} is not numeric: {raw!r}")
    return sign * (Decimal(digits) / Decimal("100"))


def _observed_casillas_from_declaration_pdf(
    *,
    snapshot: RegistrySnapshot,
    declaration: Declaracion,
    body: bytes,
) -> tuple[ObservedCasillaValue, ...]:
    try:
        filing = parse_declaracion_bytes(
            body,
            source_label=f"secure declaration PDF {declaration.expediente_id}",
            modelo_override=declaration.modelo,
            año_override=declaration.ejercicio,
            period_override=declaration.period,
            registry_snapshot=snapshot,
        )
    except DeclaracionParseError as exc:
        raise SedeParseError(
            f"declaration PDF for {declaration.expediente_id!r} did not yield registry casilla observations"
        ) from exc

    observations: list[ObservedCasillaValue] = []
    for casilla in filing.values:
        if casilla.printed_value is None:
            continue
        observations.append(
            ObservedCasillaValue(
                casilla_id=casilla.casilla_id,
                value=str(casilla.printed_value),
                source_artefact_kind="declaration_pdf",
                source_locator=f"page:{casilla.source_page}:casilla:{casilla.casilla_id}",
                confidence=casilla.extraction_confidence,
            )
        )
    if not observations:
        raise SedeParseError(f"declaration PDF for {declaration.expediente_id!r} did not yield casilla observations")
    return tuple(observations)


def _verify_submitted_file_context(
    fields_by_id: Mapping[str, ExportFieldDefinition],
    parsed_fields: tuple[ParsedExportFieldValue, ...],
    *,
    declaration: Declaracion,
) -> None:
    expected = {
        "modelo": declaration.modelo,
        "filing_year": str(declaration.ejercicio),
        "period_code": declaration.period,
    }
    for parsed in parsed_fields:
        field = fields_by_id.get(parsed.field_id)
        if field is None or field.kind != "draft" or field.draft_attribute not in expected:
            continue
        observed = "" if parsed.value is None else str(parsed.value)
        if observed != expected[field.draft_attribute]:
            raise SedeParseError(
                f"submitted-file field {parsed.field_id!r} does not match declaration {declaration.expediente_id!r}"
            )


def registry_observation_from_filed_declaration(
    observation: FiledDeclaracionObservation,
) -> RegistryModeloObservation:
    """Convert a filed-declaration observation into registry binding input."""

    if not observation.extraction_coverage:
        raise SedeParseError(
            f"filed declaration {observation.modelo!r}/{observation.ejercicio}/{observation.period!r} "
            "has no extraction coverage"
        )
    incomplete = {
        artefact_kind: coverage for artefact_kind, coverage in observation.extraction_coverage.items() if coverage < 1.0
    }
    if incomplete:
        raise SedeParseError(
            f"filed declaration {observation.modelo!r}/{observation.ejercicio}/{observation.period!r} "
            "has incomplete extraction coverage"
        )
    casilla_values: dict[str, Decimal] = {}
    for casilla in observation.casillas:
        if casilla.source_artefact_kind == "justificante_pdf":
            raise SedeParseError("justificante metadata cannot populate registry casilla values")
        try:
            value = Decimal(casilla.value)
        except InvalidOperation as exc:
            raise SedeParseError(f"observed casilla {casilla.casilla_id!r} is not decimal-valued") from exc
        previous = casilla_values.get(casilla.casilla_id)
        if previous is not None and previous != value:
            raise SedeParseError(f"observed casilla {casilla.casilla_id!r} has contradictory values")
        casilla_values[casilla.casilla_id] = value
    if not casilla_values:
        raise SedeParseError(
            f"filed declaration {observation.modelo!r}/{observation.ejercicio}/{observation.period!r} "
            "has no registry casilla observations"
        )
    return RegistryModeloObservation(
        modelo=observation.modelo,
        filing_year=observation.ejercicio,
        period=observation.period,
        observations=tuple(CasillaObservation(casilla_id=cid, value=val) for cid, val in casilla_values.items()),
    )


def _with_derived_303_compensation_available_observation(
    observation: FiledDeclaracionObservation,
) -> FiledDeclaracionObservation:
    """Add Modelo 303 carry-forward availability derived from filed casillas 87 and 69."""

    target_id = "iva.compensacion-disponible-fin-periodo"
    if observation.modelo != "303" or any(casilla.casilla_id == target_id for casilla in observation.casillas):
        return observation
    values: dict[str, Decimal] = {}
    for casilla in observation.casillas:
        if casilla.casilla_id not in {"87", "69"} or casilla.source_artefact_kind == "justificante_pdf":
            continue
        try:
            values[casilla.casilla_id] = Decimal(casilla.value)
        except InvalidOperation as exc:
            raise SedeParseError(f"observed casilla {casilla.casilla_id!r} is not decimal-valued") from exc
    if "87" not in values or "69" not in values:
        return observation
    available = values["87"] + max(Decimal("0"), -values["69"])
    derived = ObservedCasillaValue(
        casilla_id=target_id,
        value=str(available),
        source_artefact_kind="derived_registry_formula",
        source_locator="formula:87+max(0,-69)",
        confidence=1.0,
    )
    return observation.model_copy(update={"casillas": (*observation.casillas, derived)})


def resolve_previous_filing_bindings_from_filed_declarations(
    revision: ModeloRevision,
    observations: tuple[FiledDeclaracionObservation, ...],
    *,
    filing_year: int,
    period: str,
) -> dict[str, Decimal]:
    """Resolve registry previous-filing bindings from filed AEAT observations."""

    return resolve_previous_filing_binding_values(
        revision,
        (registry_observation_from_filed_declaration(observation) for observation in observations),
        filing_year=filing_year,
        period=period,
    )


def resolve_relation_values_from_filed_declarations(
    revision: ModeloRevision,
    observations: tuple[FiledDeclaracionObservation, ...],
    *,
    filing_year: int,
    period: str,
) -> dict[str, Decimal]:
    """Resolve registry cross-model relation values from filed AEAT observations."""

    return resolve_relation_values_from_observations(
        revision,
        (registry_observation_from_filed_declaration(observation) for observation in observations),
        filing_year=filing_year,
        period=period,
    )


async def _capture_row_pdf_artefact(
    *,
    context: BrowserContext,
    row_locator,
    declaration: Declaracion,
    cell_index: int,
    kind: Literal["justificante_pdf", "declaration_pdf"],
    read_policy: RemoteStateGuardPolicy,
) -> tuple[FiledDeclaracionArtefact, bytes]:
    button = row_locator.locator(".z-listcell").nth(cell_index).locator(".z-button").first
    try:
        async with context.expect_page(timeout=_VER_CLICK_TIMEOUT_MS) as new_page_info:
            _assert_read_browser_action("Ver", policy=read_policy)
            await button.click(timeout=_FORM_INTERACTION_TIMEOUT_MS)
        cotejo_page = await new_page_info.value
    except PlaywrightError as exc:
        raise SedeNavigationError(
            f"clicking PDF artefact for {declaration.expediente_id!r} failed: {exc}",
        ) from exc

    try:
        await cotejo_page.wait_for_load_state("domcontentloaded", timeout=_NAVIGATION_TIMEOUT_MS)
    except PlaywrightError as exc:
        raise SedeNavigationError(
            f"PDF artefact page did not settle for {declaration.expediente_id!r}: {exc}",
        ) from exc

    cotejo_url = cotejo_page.url
    if _COTEJO_PATH_PREFIX not in cotejo_url:
        raise SedeNavigationError(
            f"PDF artefact for {declaration.expediente_id!r} did not land on a cotejo URL (final URL: {cotejo_url!r})",
        )

    csv = _extract_csv_from_url(cotejo_url)
    pdf_url = AnyHttpUrl(f"{_COTEJO_DOC}?CSV={csv}")
    _assert_read_http("GET", str(pdf_url), policy=read_policy)
    response = await context.request.get(str(pdf_url))
    if not (200 <= response.status < 300):
        raise JustificanteFetchError(f"PDF fetch for CSV={csv!r} returned HTTP {response.status}")
    content_type = response.headers.get("content-type", "")
    body = await response.body()
    if not body:
        raise JustificanteFetchError(f"empty PDF body for CSV={csv!r}")
    if "pdf" not in content_type.lower():
        raise JustificanteFetchError(f"unexpected content-type {content_type!r} for CSV={csv!r}")
    return (
        FiledDeclaracionArtefact(
            kind=kind,
            source_url=pdf_url,
            content_type=content_type,
            byte_count=len(body),
            sha256=hashlib.sha256(body).hexdigest(),
            captured_at=datetime.now(UTC),
        ),
        body,
    )


async def _capture_submitted_file_artefact(
    *,
    page: Page,
    row_locator,
    declaration: Declaracion,
    cell_index: int,
    read_policy: RemoteStateGuardPolicy,
) -> tuple[FiledDeclaracionArtefact, bytes]:
    button = row_locator.locator(".z-listcell").nth(cell_index).locator(".z-button").first
    try:
        async with page.expect_download(timeout=_VER_CLICK_TIMEOUT_MS) as download_info:
            _assert_read_browser_action("Descarga fichero presentado", policy=read_policy)
            await button.click(timeout=_FORM_INTERACTION_TIMEOUT_MS)
        download = await download_info.value
        path = await download.path()
    except PlaywrightError as exc:
        raise SedeNavigationError(
            f"submitted-file download for {declaration.expediente_id!r} failed: {exc}",
        ) from exc

    if path is None:
        raise SedeNavigationError(
            f"submitted-file download for {declaration.expediente_id!r} did not expose a local path",
        )
    body = Path(path).read_bytes()
    if not body:
        raise JustificanteFetchError(
            f"submitted-file download for {declaration.expediente_id!r} returned an empty body",
        )
    download_url = getattr(download, "url", None)
    source_url = download_url if isinstance(download_url, str) else None
    if not source_url:
        source_url = str(AnyHttpUrl(f"{_LISTING_URL}?MODELO={declaration.modelo}&EJERCICIO={declaration.ejercicio}"))
    _assert_read_http("GET", source_url, policy=read_policy)
    return (
        FiledDeclaracionArtefact(
            kind="submitted_file",
            source_url=AnyHttpUrl(source_url),
            content_type="application/octet-stream",
            byte_count=len(body),
            sha256=hashlib.sha256(body).hexdigest(),
            captured_at=datetime.now(UTC),
        ),
        body,
    )


def _assert_read_http(
    method: str,
    url: str,
    *,
    policy: RemoteStateGuardPolicy = _READ_GUARD_POLICY,
) -> None:
    assert_remote_operation_allowed(
        policy,
        RemoteOperation(kind="http", method=method, url=AnyUrl(url)),
    )


def _assert_read_browser_action(
    action: str,
    *,
    policy: RemoteStateGuardPolicy = _READ_GUARD_POLICY,
) -> None:
    assert_remote_operation_allowed(
        policy,
        RemoteOperation(kind="browser_action", action=action),
    )


def _row_locator_for_expediente(page: Page, *, expediente_id: str):
    """Return a Playwright locator pointing at the listitem whose
    ``Expediente`` cell text equals ``expediente_id``.
    """
    return page.locator(".z-listitem").filter(
        has=page.locator(".z-listcell").filter(has_text=expediente_id),
    )


def _extract_csv_from_url(url: str) -> str:
    """Extract the ``CSV`` query parameter from a cotejo URL.

    Args:
        url: Final URL after the Ver-button click landed on
            ``/wlpl/KATA-APLI/cotejo/CotejoIdSv?CSV=<csv>``.

    Returns:
        The CSV identifier, validated against the canonical AEAT
        8-24 uppercase-alphanumeric shape.

    Raises:
        SedeParseError: When the URL does not carry a ``CSV``
            query parameter, or when the value does not match
            the canonical AEAT CSV shape.
    """
    parsed = urlsplit(url)
    qs = parse_qs(parsed.query)
    csv_values = qs.get("CSV", [])
    if not csv_values:
        raise SedeParseError(f"cotejo URL missing CSV query: {url!r}")
    if len(csv_values) > 1:
        # AEAT never repeats the CSV parameter; multiple values
        # indicate a malformed response or an attacker-crafted URL
        # smuggling extra state past the parser. Refuse rather
        # than silently picking the first value.
        raise SedeParseError(
            f"cotejo URL has {len(csv_values)} CSV values; AEAT only emits one: {url!r}",
        )
    csv = csv_values[0]
    if not _CSV_SHAPE_RE.match(csv):
        raise SedeParseError(
            f"cotejo URL CSV {csv!r} does not match AEAT shape (expected 8-24 uppercase alphanumeric chars)",
        )
    return csv


__all__ = [
    "Declaracion",
    "DeclaracionesRegisterSession",
    "capture_declaration",
    "capture_filed_declaration_observation",
    "capture_previous_filing_observations",
    "capture_relation_source_observations",
    "open_declarations_register",
    "registry_observation_from_filed_declaration",
    "resolve_previous_filing_bindings_from_filed_declarations",
    "resolve_relation_values_from_filed_declarations",
    "shared_playwright",
    "walk_declarations_register",
]
