"""Read-only walker over AEAT's *Consultar declaraciones presentadas* surface.

The expediente-tree walker (`_walker.walk_expedientes_tree`) walks
``Mis Expedientes`` (``/wlpl/TEWV-CORE/ResumenVlt``) which is a
*procedures* surface — sanciones, recursos, gestión recaudación —
not the canonical filings register. To read the operator's actual
filing history across supported periodic, annual, retention, and
informative declarations, we drive the
``Consultar declaraciones presentadas`` form at
``/wlpl/SCEJ-MANT/CONSUL/index.zul``.

The form is built on the ZK framework. Input ids are generated by the
server and are not stable selectors; automation binds on label text
and visible row structure. The submit action is a real ``Buscar``
button issuing a ZK AJAX RPC; URL parameters alone do not drive
results.

Parsed filings are grounded against the registry: each declaration is
resolved to its :class:`ModeloRevision` and a :class:`RegistrySnapshot`
(loaded through :class:`ValidatedRegistryAuthority`), and reported casilla
values are surfaced as :class:`CasillaObservation` rows carrying their
legal and source references.
"""

from __future__ import annotations

import hashlib
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from pathlib import Path
from typing import TYPE_CHECKING, Literal
from urllib.parse import urlsplit

from pydantic import AnyHttpUrl

from .....core.config import Settings, load_settings
from .....core.external_constants import BINARY_MIME_TYPE as _BINARY_MIME_TYPE
from .....core.external_constants import JSON_MIME_TYPE as _JSON_MIME_TYPE
from .....core.external_constants import PDF_MIME_TYPE as _PDF_MIME_TYPE
from .....core.i18n import tr
from .....core.logging import get_logger
from .....core.time import now

# Importing the renta package registers the first-slice routing
# cross-domain snapshot check with the registry validator. build_snapshot
# of a Modelo 100 revision fails loudly if that check is unregistered, so
# the M100 routing referential-integrity gate runs on this declarations path.
from .....domain.calculations.registry import (
    RegistrySnapshot,
    RegistryValidationError,
    RemoteStateGuardPolicy,
    previous_filing_observation_requirements,
    relation_source_requirements,
)
from .._playwright import BrowserContext, Page, Playwright, PlaywrightError
from ..browser import Profile, opened_browser_page, shared_playwright_runtime
from ._auth_state import storage_state_for_session
from ._browser_constants import (
    PLAYWRIGHT_WAIT_DOMCONTENTLOADED as _WAIT_DOMCONTENTLOADED,
)
from ._browser_constants import (
    PLAYWRIGHT_WAIT_NETWORKIDLE as _WAIT_NETWORKIDLE,
)
from ._declarations_diagnostics import (
    declarations_page_shape_context as _declarations_page_shape_context,
)
from ._declarations_diagnostics import (
    declarations_page_shape_context_from_page as _declarations_page_shape_context_from_page,
)
from ._declarations_listbox import _parse_listbox, _parse_presented_at
from ._declarations_observations import (
    FiledDeclaracionArtefactSink,
    _observed_casillas_from_declaration_pdf,
    _observed_casillas_from_submitted_file,
    _read_guard_policy_from_snapshot,
    _register_row_artefact,
    _registry_snapshot_for_declaration,
    _store_artefact,
    _submitted_file_coverage_for_casillas,
    _temporary_sensitive_pdf_path,
    _verify_submitted_file_context,
    _with_derived_303_compensation_available_observation,
    registry_observation_from_filed_declaration,
    resolve_previous_filing_bindings_from_filed_declarations,
    resolve_relation_values_from_filed_declarations,
)
from ._declarations_remote import assert_read_browser_action as _remote_assert_read_browser_action
from ._declarations_remote import assert_read_http as _remote_assert_read_http
from ._declarations_remote import extract_csv_from_url as _extract_csv_from_url
from ._declarations_schema import Declaracion
from ._errors import (
    JustificanteFetchError,
    SedeFailureMode,
    SedeNavigationError,
    SedeParseError,
)
from ._schema import (
    FiledDeclaracionArtefact,
    FiledDeclaracionObservation,
    JustificanteRef,
    ObservedCasillaValue,
    SedeCapture,
)

if TYPE_CHECKING:
    from .....domain.calculations.registry import ModeloRevision
    from ..auth._authenticator import AeatSession


log = get_logger(__name__)


_EXTERNAL = Settings.external_constants()
_SEDE_BASE = _EXTERNAL.aeat.domains.www6
_SEDE_HOST = urlsplit(_SEDE_BASE).netloc
_LISTING_URL = f"{_SEDE_BASE}{_EXTERNAL.aeat.sede_paths.declarations_listing}"
_COTEJO_VIEW = f"{_SEDE_BASE}{_EXTERNAL.aeat.sede_paths.cotejo_query}"
_COTEJO_DOC = f"{_SEDE_BASE}{_EXTERNAL.aeat.sede_paths.cotejo_document}"
_COTEJO_PATH_PREFIX = _EXTERNAL.aeat.sede_paths.cotejo_query
_DECLARATIONS_LISTING_PATH_PREFIX = _EXTERNAL.aeat.sede_paths.declarations_listing.removesuffix("/index.zul")

DEFAULT_NAVIGATION_TIMEOUT_MS: int = 30_000
DEFAULT_FORM_INTERACTION_TIMEOUT_MS: int = 10_000
DEFAULT_BUSCAR_SETTLE_MS: int = 2_000
DEFAULT_VER_CLICK_TIMEOUT_MS: int = 5_000


def _get_navigation_timeout_ms() -> int:
    return load_settings().aeat_browser_navigation_timeout_ms


def _get_form_interaction_timeout_ms() -> int:
    return load_settings().aeat_browser_form_interaction_timeout_ms


def _get_buscar_settle_ms() -> int:
    return load_settings().aeat_browser_buscar_settle_ms


def _get_ver_click_timeout_ms() -> int:
    return load_settings().aeat_browser_ver_click_timeout_ms


_READ_GUARD_POLICY = RemoteStateGuardPolicy(
    id="aeat-sede-declarations-read",
    evidence_tier="official_source_guidance",
    classification="authenticated_read_surface",
    allowed_hosts=(_SEDE_HOST,),
    allowed_browser_action_patterns=_EXTERNAL.aeat.live_safety.declarations_browser_action_patterns,
    synthetic_data_allowed=False,
    requires_authentication=True,
    requires_aeat_authorization=True,
)


@asynccontextmanager
async def shared_playwright(
    session: AeatSession,
) -> AsyncIterator[Playwright]:
    """Yield a long-lived Playwright instance for bulk register sweeps.

    `walk_declarations_register` and `capture_declaration` each spin
    up their own Playwright + BrowserSession when called standalone,
    which is fine for one-shot use. Bulk callers
    (e.g. ``aeat sede capture-corpus``) pay ~1s per iteration on
    Playwright startup; wrapping repeated reads in this helper amortises
    that cost across the entire run.

    Usage:

    .. code-block:: python

        async with shared_playwright(session) as pw:
            for modelo in modelos:
                rows = await walk_declarations_register(
                    session, modelo=modelo, ejercicio=ejercicio,
                    playwright=pw,
                )
                for declaration in rows:
                    capture = await capture_declaration(
                        session, declaration, playwright=pw,
                    )

    Args:
        session: Authenticated AEAT session. Validated upfront so
            bulk reads fail fast rather than per-iteration.

    Yields:
        A live :class:`Playwright` instance. Cleaned up automatically
        on exit.
    """
    storage_state_for_session(session)
    async with shared_playwright_runtime() as pw:
        yield pw


class DeclaracionesRegisterSession:
    """Reusable read-only session for AEAT's filed-declarations register."""

    def __init__(self, session: AeatSession, page: Page, context: BrowserContext) -> None:
        self._session = session
        self._page = page
        self._context = context

    async def walk(self, *, modelo: str, ejercicio: int) -> tuple[Declaracion, ...]:
        """Return :class:`Declaracion` rows for one ``(modelo, ejercicio)`` query."""
        if not await _drive_search(self._page, modelo=modelo, ejercicio=ejercicio):
            log.info(
                "DeclaracionesRegisterSession.walk: ejercicio unavailable modelo=%s ejercicio=%d",
                modelo,
                ejercicio,
            )
            return ()
        results = _parse_listbox(await self._page.content(), modelo=modelo, ejercicio=ejercicio)
        log.info(
            "DeclaracionesRegisterSession.walk: found %d declaration(s) modelo=%s ejercicio=%d",
            len(results),
            modelo,
            ejercicio,
        )
        return results

    async def capture_observation(
        self,
        declaration: Declaracion,
        *,
        registry_snapshot: RegistrySnapshot | None = None,
        artefact_sink: FiledDeclaracionArtefactSink | None = None,
    ) -> FiledDeclaracionObservation:
        """Capture a normalized :class:`FiledDeclaracionObservation` using the active page.

        Args:
            declaration: The :class:`Declaracion` row to observe.
            registry_snapshot: Optional pre-built :class:`RegistrySnapshot`. When
                omitted, the snapshot is resolved from the declaration coordinates.
            artefact_sink: Optional callable storing each captured artefact.
        """
        snapshot = registry_snapshot or _registry_snapshot_for_declaration(declaration)
        read_policy = _read_guard_policy_from_snapshot(snapshot)
        if not await _drive_search(
            self._page,
            modelo=declaration.modelo,
            ejercicio=declaration.ejercicio,
            read_policy=read_policy,
        ):
            raise SedeNavigationError(
                f"AEAT declarations register does not offer ejercicio {declaration.ejercicio} "
                f"for modelo {declaration.modelo}",
                translated_message=tr("adapters.sede.errors.ejercicio_unavailable"),
            )
        row_locator = _row_locator_for_expediente(
            self._page,
            expediente_id=declaration.expediente_id,
        )
        return await _capture_filed_declaration_observation_from_row(
            self._session,
            declaration,
            row_locator=row_locator,
            page=self._page,
            context=self._context,
            registry_snapshot=snapshot,
            artefact_sink=artefact_sink,
        )


@asynccontextmanager
async def open_declarations_register(
    session: AeatSession,
    *,
    settings: Settings | None = None,
    playwright: Playwright | None = None,
) -> AsyncIterator[DeclaracionesRegisterSession]:
    """Open a :class:`DeclaracionesRegisterSession` for repeated filed-declaration register reads."""
    async with _open_register_page(session, settings=settings, playwright=playwright) as (
        page,
        context,
    ):
        yield DeclaracionesRegisterSession(session, page, context)


@asynccontextmanager
async def _open_register_page(
    session: AeatSession,
    *,
    settings: Settings | None = None,
    playwright: Playwright | None = None,
) -> AsyncIterator[tuple[Page, BrowserContext]]:
    """Yield a Playwright ``(page, context)`` bound to the AEAT session.

    Both :func:`walk_declarations_register` and :func:`capture_declaration`
    need the same bringup: validate persisted session state,
    build a :class:`Profile`, spin up Playwright, and create a
    context preloaded with the session cookies. Centralising the
    helper keeps the two callers structurally identical and
    fixes a latent leak where the walker did not close the
    underlying :class:`BrowserSession` after use.

    Args:
        session: Authenticated AEAT session.
        settings: Optional :class:`Settings` override.
        playwright: Optional pre-started :class:`Playwright` instance
            (typically produced by :func:`shared_playwright`). When
            provided, the helper reuses it instead of starting its
            own — saves ~1s per iteration in bulk sweeps. Caller owns
            the lifetime; this helper does not stop a passed-in
            instance.

    Yields:
        A ``(page, context)`` pair. The page is a fresh
        :class:`Page` inside the storage-state-loaded context.

    Raises:
        SedeNavigationError: When the session has no encrypted browser state.
    """
    settings = settings or Settings()
    storage_state = storage_state_for_session(session)
    storage_state_path = session.storage_state_path
    if storage_state_path is None:
        raise SedeNavigationError(
            "AeatSession has no persisted auth session; run `aeat config auth status` first",
            translated_message=tr("adapters.sede.errors.no_auth_session"),
        )
    from .....core import require_active_bucket_id

    profile = Profile(
        name=require_active_bucket_id(),
        storage_state_path=storage_state_path,
    )
    if playwright is not None:
        async with _opened_browser_session(playwright, settings, profile, storage_state) as (page, context):
            yield page, context
        return
    async with (
        shared_playwright_runtime() as pw,
        _opened_browser_session(pw, settings, profile, storage_state) as (page, context),
    ):
        yield page, context


@asynccontextmanager
async def _opened_browser_session(
    pw: Playwright,
    settings: Settings,
    profile: Profile,
    storage_state: dict[str, object],
) -> AsyncIterator[tuple[Page, BrowserContext]]:
    """Inner helper: create + tear down a BrowserSession + context."""
    async with opened_browser_page(pw, settings, profile, storage_state=storage_state) as (page, context):
        yield page, context


async def walk_declarations_register(
    session: AeatSession,
    *,
    modelo: str,
    ejercicio: int,
    settings: Settings | None = None,
    playwright: Playwright | None = None,
) -> tuple[Declaracion, ...]:
    """Drive the *Consultar declaraciones presentadas* form for one query.

    Args:
        session: Authenticated AEAT session whose
            ``storage_state_path`` carries valid cookies.
        modelo: Modelo code to query. The form's modelo combobox is matched on the leading
            ``"<modelo> -"`` text.
        ejercicio: Tax year to query (``2024``).
        settings: Optional :class:`Settings` override.
        playwright: Optional pre-started Playwright instance
            (typically from :func:`shared_playwright`). Reused
            across the call to amortise the ~1s startup cost in
            bulk sweeps. When ``None``, a fresh instance is started
            and torn down per call.

    Returns:
        Tuple of :class:`Declaracion` records, one per filing row.
        Empty when AEAT returns "No se han encontrado resultados".
    """
    async with _open_register_page(session, settings=settings, playwright=playwright) as (
        page,
        _context,
    ):
        if not await _drive_search(page, modelo=modelo, ejercicio=ejercicio):
            log.info(
                "walk_declarations_register: ejercicio unavailable modelo=%s ejercicio=%d",
                modelo,
                ejercicio,
            )
            return ()
        results = _parse_listbox(await page.content(), modelo=modelo, ejercicio=ejercicio)
    log.info(
        "walk_declarations_register: found %d declaration(s) modelo=%s ejercicio=%d",
        len(results),
        modelo,
        ejercicio,
    )
    return results


async def _drive_search(
    page: Page,
    *,
    modelo: str,
    ejercicio: int,
    read_policy: RemoteStateGuardPolicy = _READ_GUARD_POLICY,
) -> bool:
    """Fill the form and click Buscar.

    Raises :class:`SedeNavigationError` early when AEAT redirects to
    the login wall instead of the form (session expired) so callers
    get an actionable error rather than an opaque combobox click
    timeout.
    """
    try:
        _assert_read_http("GET", _LISTING_URL, policy=read_policy)
        await page.goto(
            _LISTING_URL,
            wait_until=_WAIT_NETWORKIDLE,
            timeout=_get_navigation_timeout_ms(),
        )
    except PlaywrightError as exc:
        raise SedeNavigationError(
            f"goto {_LISTING_URL!r} failed: {exc}",
            translated_message=tr("adapters.sede.errors.listing_nav_failed"),
            failure_mode=SedeFailureMode.LIVE_NAVIGATION_FAILED,
            context=await _declarations_page_shape_context_from_page(
                page,
                stage="listing_goto",
                modelo=modelo,
                ejercicio=ejercicio,
            ),
        ) from exc
    await page.wait_for_timeout(1500)
    await _continue_alert_modal(page, read_policy=read_policy)

    final_url = page.url
    if _DECLARATIONS_LISTING_PATH_PREFIX not in final_url:
        log.warning(
            "declaraciones register did not load; session may have expired (final_url=%r)",
            final_url,
        )
        raise SedeNavigationError(
            f"declaraciones register did not load (final URL: {final_url!r}); "
            "session likely expired — run `aeat config auth test` and retry",
            translated_message=tr("adapters.sede.errors.session_expired_nav_failed"),
            failure_mode=SedeFailureMode.LIVE_NAVIGATION_FAILED,
            context=await _declarations_page_shape_context_from_page(
                page,
                stage="listing_final_url",
                modelo=modelo,
                ejercicio=ejercicio,
            ),
        )
    # Defensive: even when the URL matches, AEAT sometimes serves a
    # blank shell with no Modelo label until the JS finishes booting.
    try:
        await page.get_by_text("Modelo (*)", exact=True).first.wait_for(
            state="visible",
            timeout=_get_form_interaction_timeout_ms(),
        )
    except PlaywrightError as exc:
        raise SedeNavigationError(
            "declaraciones register form did not render the 'Modelo (*)' "
            f"label within {_get_form_interaction_timeout_ms()}ms; "
            "session likely expired or AEAT served a maintenance page",
            translated_message=tr("adapters.sede.errors.form_render_timeout"),
            failure_mode=SedeFailureMode.LIVE_NAVIGATION_FAILED,
            context=await _declarations_page_shape_context_from_page(
                page,
                stage="form_render",
                modelo=modelo,
                ejercicio=ejercicio,
            ),
        ) from exc

    if not await _select_combobox_value(
        page,
        label_text="Modelo (*)",
        option_match=f"{modelo} -",
        read_policy=read_policy,
    ):
        raise SedeNavigationError(
            f"AEAT declarations register does not offer modelo {modelo!r}",
            translated_message=tr("adapters.sede.errors.modelo_unavailable"),
            failure_mode=SedeFailureMode.EXTERNAL_SHAPE_CHANGED,
            context=await _declarations_page_shape_context_from_page(
                page,
                stage="modelo_option_missing",
                modelo=modelo,
                ejercicio=ejercicio,
            ),
        )
    if not await _select_combobox_value(
        page,
        label_text="Ejercicio (*)",
        option_match=str(ejercicio),
        read_policy=read_policy,
    ):
        return False

    try:
        _assert_read_browser_action("buscar-declaraciones-presentadas", policy=read_policy)
        await (
            page.locator("button.z-button")
            .filter(has_text="Buscar")
            .click(
                timeout=_get_form_interaction_timeout_ms(),
            )
        )
    except PlaywrightError as exc:
        raise SedeNavigationError(
            f"clicking Buscar failed: {exc}",
            translated_message="adapters.sede.errors.playwright_buscar_click_failed",
            failure_mode=SedeFailureMode.LIVE_NAVIGATION_FAILED,
            context=await _declarations_page_shape_context_from_page(
                page,
                stage="buscar_click",
                modelo=modelo,
                ejercicio=ejercicio,
            ),
        ) from exc
    await page.wait_for_timeout(_get_buscar_settle_ms())
    log.info(
        "declarations register search completed modelo=%s ejercicio=%d shape=%s",
        modelo,
        ejercicio,
        _declarations_page_shape_context(
            await page.content(),
            landing_url=getattr(page, "url", "") or "",
            stage="post_buscar",
            modelo=modelo,
            ejercicio=ejercicio,
        ),
    )
    return True


async def _select_combobox_value(
    page: Page,
    *,
    label_text: str,
    option_match: str,
    read_policy: RemoteStateGuardPolicy = _READ_GUARD_POLICY,
) -> bool:
    """Open the combobox after ``label_text`` and pick an option matching ``option_match``."""
    label = page.get_by_text(label_text, exact=True).first
    button = label.locator('xpath=following::a[contains(@class,"z-combobox-button")][1]')
    try:
        _assert_read_browser_action(f"select-{label_text.split()[0].lower()}", policy=read_policy)
        await button.click(timeout=_get_form_interaction_timeout_ms())
    except PlaywrightError as exc:
        raise SedeNavigationError(
            f"opening combobox after label {label_text!r} failed: {exc}",
            translated_message="adapters.sede.errors.playwright_combobox_open_failed",
        ) from exc
    await page.wait_for_timeout(400)

    options = page.locator(".z-comboitem-text")
    matching_options = options.filter(has_text=option_match)
    if await matching_options.count() == 0:
        log.info(
            "AEAT combobox option unavailable label=%s option=%s",
            label_text,
            option_match,
        )
        return False

    target = matching_options.first
    try:
        _assert_read_browser_action(f"select-option-{option_match}", policy=read_policy)
        await target.click(timeout=_get_form_interaction_timeout_ms())
    except PlaywrightError as exc:
        raise SedeNavigationError(
            f"selecting option {option_match!r} for {label_text!r} failed: {exc}",
            translated_message="adapters.sede.errors.playwright_combobox_select_failed",
        ) from exc
    await page.wait_for_timeout(300)
    return True


async def _continue_alert_modal(
    page: Page,
    *,
    read_policy: RemoteStateGuardPolicy = _READ_GUARD_POLICY,
) -> None:
    """Dismiss AEAT's informational alert modal without opening alert actions."""
    try:
        _assert_read_browser_action("alert-modal-continuar", policy=read_policy)
        result = await page.evaluate(
            """
            () => {
              const modal = document.querySelector("#alertsModal");
              if (!modal) return "absent";
              const style = window.getComputedStyle(modal);
              if (style.display === "none" || style.visibility === "hidden") return "hidden";
              const buttons = [...modal.querySelectorAll("button")];
              const continueButton = buttons.find((button) =>
                (button.textContent || "").trim().toLowerCase() === "continuar"
              );
              if (!continueButton) {
                throw new Error("AEAT alert modal has no Continuar button");
              }
              continueButton.click();
              return "continued";
            }
            """,
        )
    except PlaywrightError as exc:
        raise SedeNavigationError(
            f"continuing AEAT alert modal failed: {exc}",
            translated_message="adapters.sede.errors.playwright_alert_modal_failed",
        ) from exc
    if result == "continued":
        await page.wait_for_timeout(500)


async def capture_declaration(
    session: AeatSession,
    declaration: Declaracion,
    *,
    settings: Settings | None = None,
    playwright: Playwright | None = None,
) -> SedeCapture:
    """Fetch the raw justificante PDF behind a :class:`Declaracion`.

    Drives the declaraciones register the same way
    :func:`walk_declarations_register` does, locates the row whose
    ``expediente_id`` matches ``declaration.expediente_id``, clicks
    that row's *Obtención de Justificante* button, captures the
    CSV from the resulting cotejo URL, and downloads the PDF via
    :class:`APIRequestContext` (so Chrome's PDF viewer never
    intercepts the response).

    Args:
        session: Authenticated AEAT session.
        declaration: The Declaracion row to capture, typically obtained from
            :func:`walk_declarations_register`.
        settings: Optional :class:`Settings` override.
        playwright: Optional pre-started Playwright instance (typically from
            :func:`shared_playwright`). When ``None`` a fresh instance is started
            and torn down per call.

    Returns:
        A :class:`SedeCapture` whose ``ref`` carries the resolved CSV / cotejo URL /
        PDF URL and whose ``pdf_bytes`` carries the raw response body.

    Raises:
        SedeNavigationError: When the form drive or row click fails.
        JustificanteFetchError: When the PDF GET returns a non-2xx status code,
            an empty body, or an unexpected content type.
    """
    read_policy = _read_guard_policy_from_snapshot(_registry_snapshot_for_declaration(declaration))
    async with _open_register_page(session, settings=settings, playwright=playwright) as (
        page,
        context,
    ):
        if not await _drive_search(
            page,
            modelo=declaration.modelo,
            ejercicio=declaration.ejercicio,
            read_policy=read_policy,
        ):
            raise SedeNavigationError(
                f"AEAT declarations register does not offer ejercicio {declaration.ejercicio} "
                f"for modelo {declaration.modelo}",
                translated_message=tr("adapters.sede.errors.ejercicio_unavailable"),
            )

        row_locator = _row_locator_for_expediente(
            page,
            expediente_id=declaration.expediente_id,
        )
        ver_button = row_locator.locator(
            '.z-listcell:has-text("Ver") .z-button',
        ).first

        try:
            async with context.expect_page(
                timeout=_get_ver_click_timeout_ms(),
            ) as new_page_info:
                _assert_read_browser_action("open-cotejo-pdf", policy=read_policy)
                await ver_button.click(timeout=_get_form_interaction_timeout_ms())
            cotejo_page = await new_page_info.value
        except PlaywrightError as exc:
            raise SedeNavigationError(
                f"clicking Ver for {declaration.expediente_id!r} failed: {exc}",
                translated_message=tr("adapters.sede.errors.cotejo_nav_failed"),
            ) from exc

        try:
            await cotejo_page.wait_for_load_state(
                _WAIT_DOMCONTENTLOADED,
                timeout=_get_navigation_timeout_ms(),
            )
        except PlaywrightError as exc:
            raise SedeNavigationError(
                f"cotejo page did not settle for {declaration.expediente_id!r}: {exc}",
                translated_message=tr("adapters.sede.errors.cotejo_nav_failed"),
            ) from exc

        cotejo_url = cotejo_page.url
        if _COTEJO_PATH_PREFIX not in cotejo_url:
            raise SedeNavigationError(
                f"Ver button for {declaration.expediente_id!r} did not land on a "
                f"cotejo URL (final URL: {cotejo_url!r}); "
                "session likely expired mid-walk — run `aeat config auth test` and retry",
                translated_message=tr("adapters.sede.errors.cotejo_nav_failed"),
            )

        csv = _extract_csv_from_url(cotejo_url)

        ref = JustificanteRef(
            csv=csv,
            expediente_id=declaration.expediente_id,
            cotejo_url=AnyHttpUrl(f"{_COTEJO_VIEW}?CSV={csv}"),
            pdf_url=AnyHttpUrl(f"{_COTEJO_DOC}?CSV={csv}"),
        )

        _assert_read_http("GET", str(ref.pdf_url), policy=read_policy)
        pdf_response = await context.request.get(str(ref.pdf_url))
        if not (200 <= pdf_response.status < 300):
            raise JustificanteFetchError(
                f"pdf fetch for CSV={csv!r} returned HTTP {pdf_response.status}",
            )
        content_type = pdf_response.headers.get("content-type", "")
        body = await pdf_response.body()
        if not body:
            raise JustificanteFetchError(f"empty PDF body for CSV={csv!r}")
        if _PDF_MIME_TYPE not in content_type.lower():
            raise JustificanteFetchError(
                f"unexpected content-type {content_type!r} for CSV={csv!r}",
            )

        from ._schema import Expediente

        sha256 = hashlib.sha256(body).hexdigest()
        log.info(
            "capture_declaration: captured PDF expediente=%s CSV=%s size=%d sha256=%s",
            declaration.expediente_id,
            csv,
            len(body),
            sha256[:16],
        )
        return SedeCapture(
            expediente=Expediente(
                expediente_id=declaration.expediente_id,
                modelo=declaration.modelo,
                ejercicio=declaration.ejercicio,
                category_path=("Declaraciones presentadas",),
                detail_url=AnyHttpUrl(
                    f"{_LISTING_URL}?MODELO={declaration.modelo}&EJERCICIO={declaration.ejercicio}",
                ),
            ),
            ref=ref,
            pdf_bytes=body,
            pdf_sha256=sha256,
            captured_at=now(),
        )


async def capture_filed_declaration_observation(
    session: AeatSession,
    declaration: Declaracion,
    *,
    registry_snapshot: RegistrySnapshot | None = None,
    settings: Settings | None = None,
    playwright: Playwright | None = None,
    artefact_sink: FiledDeclaracionArtefactSink | None = None,
) -> FiledDeclaracionObservation:
    """Capture a :class:`FiledDeclaracionObservation` with read-only evidence for one filed declaration.

    The observation begins with the register row and then captures every
    AEAT-served artefact this backend knows how to read from the row:
    the justificante/declaration PDF and, when exposed by AEAT, the
    submitted file download. Submitted files are parsed through the
    registry export layout selected for the declaration snapshot.

    Args:
        session: Authenticated AEAT session.
        declaration: The :class:`Declaracion` row to observe.
        registry_snapshot: Optional pre-built :class:`RegistrySnapshot`. When
            omitted, the snapshot is resolved from the declaration's modelo,
            ejercicio, and period via the bundled registry authority.
        settings: Optional :class:`Settings` override.
        playwright: Optional pre-started Playwright instance.
        artefact_sink: Optional callable that stores each captured artefact
            and returns the (possibly updated) artefact record.
    """
    authenticated_identity = (session.identity_nif or "").strip()
    if not authenticated_identity:
        raise SedeNavigationError(
            "AeatSession.identity_nif is empty; cannot bind live filing observation",
            translated_message=tr("adapters.sede.errors.empty_identity_nif"),
        )
    snapshot = registry_snapshot or _registry_snapshot_for_declaration(declaration)
    read_policy = _read_guard_policy_from_snapshot(snapshot)
    async with _open_register_page(session, settings=settings, playwright=playwright) as (
        page,
        context,
    ):
        if not await _drive_search(
            page,
            modelo=declaration.modelo,
            ejercicio=declaration.ejercicio,
            read_policy=read_policy,
        ):
            raise SedeNavigationError(
                f"AEAT declarations register does not offer ejercicio {declaration.ejercicio} "
                f"for modelo {declaration.modelo}",
            )

        row_locator = _row_locator_for_expediente(
            page,
            expediente_id=declaration.expediente_id,
        )
        return await _capture_filed_declaration_observation_from_row(
            session,
            declaration,
            row_locator=row_locator,
            page=page,
            context=context,
            registry_snapshot=snapshot,
            artefact_sink=artefact_sink,
        )


async def _capture_filed_declaration_observation_from_row(
    session: AeatSession,
    declaration: Declaracion,
    *,
    row_locator,
    page: Page,
    context: BrowserContext,
    registry_snapshot: RegistrySnapshot | None,
    artefact_sink: FiledDeclaracionArtefactSink | None,
) -> FiledDeclaracionObservation:
    authenticated_identity = (session.identity_nif or "").strip()
    if not authenticated_identity:
        raise SedeNavigationError(
            "AeatSession.identity_nif is empty; cannot bind live filing observation",
            translated_message=tr("adapters.sede.errors.empty_identity_nif"),
        )
    snapshot = registry_snapshot or _registry_snapshot_for_declaration(declaration)
    read_policy = _read_guard_policy_from_snapshot(snapshot)
    observation_key = (
        declaration.modelo,
        declaration.ejercicio,
        declaration.period,
        declaration.expediente_id,
    )
    listing_url = AnyHttpUrl(f"{_LISTING_URL}?MODELO={declaration.modelo}&EJERCICIO={declaration.ejercicio}")

    register_row, register_row_body = _register_row_artefact(declaration, source_url=listing_url)
    artefacts: list[FiledDeclaracionArtefact] = [
        _store_artefact(
            artefact_sink,
            observation_key=observation_key,
            artefact=register_row,
            body=register_row_body,
        ),
    ]
    casillas: tuple[ObservedCasillaValue, ...] = ()
    extraction_coverage: dict[str, float] = {}
    metadata = {
        "tipo_solicitud": declaration.tipo_solicitud or "",
        "observaciones": declaration.observaciones or "",
    }

    justificante, justificante_body = await _capture_row_pdf_artefact(
        context=context,
        row_locator=row_locator,
        declaration=declaration,
        cell_index=declaration.justificante_cell_index,
        kind="justificante_pdf",
        read_policy=read_policy,
    )
    artefacts.append(
        _store_artefact(
            artefact_sink,
            observation_key=observation_key,
            artefact=justificante,
            body=justificante_body,
        ),
    )

    declaration_pdf_body: bytes | None = None
    if declaration.declaration_copy_link_text and declaration.declaration_copy_cell_index is not None:
        declaration_pdf, declaration_pdf_body = await _capture_row_pdf_artefact(
            context=context,
            row_locator=row_locator,
            declaration=declaration,
            cell_index=declaration.declaration_copy_cell_index,
            kind="declaration_pdf",
            read_policy=read_policy,
        )
        artefacts.append(
            _store_artefact(
                artefact_sink,
                observation_key=observation_key,
                artefact=declaration_pdf,
                body=declaration_pdf_body,
            ),
        )

    if declaration.archive_link_text and declaration.archive_cell_index is not None:
        try:
            submitted_artefact, submitted_body = await _capture_submitted_file_artefact(
                page=page,
                row_locator=row_locator,
                declaration=declaration,
                cell_index=declaration.archive_cell_index,
                read_policy=read_policy,
            )
        except (JustificanteFetchError, SedeNavigationError) as exc:
            metadata["submitted_file_capture_error"] = str(exc)
        else:
            submitted_artefact = _store_artefact(
                artefact_sink,
                observation_key=observation_key,
                artefact=submitted_artefact,
                body=submitted_body,
            )
            artefacts.append(submitted_artefact)
            try:
                casillas = _observed_casillas_from_submitted_file(
                    snapshot=snapshot,
                    declaration=declaration,
                    body=submitted_body,
                    artefact=submitted_artefact,
                )
                extraction_coverage["submitted_file"] = _submitted_file_coverage_for_casillas(
                    snapshot=snapshot,
                    body=submitted_body,
                    casillas=casillas,
                )
            except (RegistryValidationError, SedeParseError) as exc:
                metadata["submitted_file_extraction_error"] = str(exc)

    if not casillas and declaration_pdf_body is not None:
        casillas = _observed_casillas_from_declaration_pdf(
            snapshot=snapshot,
            declaration=declaration,
            body=declaration_pdf_body,
        )
        extraction_coverage["declaration_pdf"] = 1.0
    elif not casillas and not declaration.archive_link_text and declaration_pdf_body is None:
        raise SedeParseError(
            f"AEAT declaration {declaration.expediente_id!r} did not expose submitted-file or declaration-copy data",
        )

    return FiledDeclaracionObservation(
        modelo=declaration.modelo,
        ejercicio=declaration.ejercicio,
        period=declaration.period,
        expediente_id=declaration.expediente_id,
        status=declaration.estado,
        presented_at=declaration.presented_at,
        authenticated_identity=authenticated_identity,
        artefacts=tuple(artefacts),
        casillas=casillas,
        metadata=metadata,
        extraction_coverage=extraction_coverage,
        registry_snapshot_id=f"{snapshot.modelo.id}:{snapshot.revision.id}:{declaration.ejercicio}:{declaration.period}",
    )


async def capture_previous_filing_observations(
    session: AeatSession,
    revision: ModeloRevision,
    *,
    filing_year: int,
    period: str,
    settings: Settings | None = None,
    playwright: Playwright | None = None,
    artefact_sink: FiledDeclaracionArtefactSink | None = None,
) -> tuple[FiledDeclaracionObservation, ...]:
    """Capture :class:`FiledDeclaracionObservation` records required by registry previous-filing bindings.

    Args:
        session: Authenticated AEAT session.
        revision: The :class:`ModeloRevision` whose previous-filing binding
            requirements determine which declarations are fetched.
        filing_year: Tax year of the current filing.
        period: Period code of the current filing.
        settings: Optional :class:`Settings` override.
        playwright: Optional pre-started Playwright instance.
        artefact_sink: Optional callable storing each captured artefact.
    """
    observations: list[FiledDeclaracionObservation] = []
    async with open_declarations_register(session, settings=settings, playwright=playwright) as register:
        for requirement in previous_filing_observation_requirements(revision, filing_year=filing_year, period=period):
            rows = await register.walk(modelo=requirement.modelo, ejercicio=requirement.filing_year)
            matches = tuple(row for row in rows if row.period == requirement.period)
            declaration = _select_authoritative_declaration(
                matches,
                modelo=requirement.modelo,
                ejercicio=requirement.filing_year,
                period=requirement.period,
                context="previous-filing requirement",
            )
            observation = await register.capture_observation(declaration, artefact_sink=artefact_sink)
            observation = _with_derived_303_compensation_available_observation(observation)
            observed_casillas = {casilla.casilla_id for casilla in observation.casillas}
            missing = sorted(set(requirement.source_casillas).difference(observed_casillas))
            if missing:
                raise SedeParseError(
                    f"previous-filing requirement {requirement.modelo!r}/"
                    f"{requirement.filing_year}/{requirement.period!r} missing observed casillas {missing!r}",
                )
            observations.append(observation)
    return tuple(observations)


async def capture_relation_source_observations(
    session: AeatSession,
    revision: ModeloRevision,
    *,
    filing_year: int,
    period: str,
    settings: Settings | None = None,
    playwright: Playwright | None = None,
    artefact_sink: FiledDeclaracionArtefactSink | None = None,
) -> tuple[FiledDeclaracionObservation, ...]:
    """Capture :class:`FiledDeclaracionObservation` records required by registry cross-model relations.

    Args:
        session: Authenticated AEAT session.
        revision: The :class:`ModeloRevision` whose cross-model relation
            requirements determine which source declarations are fetched.
        filing_year: Tax year of the current filing.
        period: Period code of the current filing.
        settings: Optional :class:`Settings` override.
        playwright: Optional pre-started Playwright instance.
        artefact_sink: Optional callable storing each captured artefact.
    """
    required_outputs: dict[tuple[str, int, str], set[str]] = {}
    for requirement in relation_source_requirements(revision, filing_year=filing_year, period=period):
        for source_period in requirement.periods:
            key = (requirement.source_modelo, requirement.filing_year, source_period)
            required_outputs.setdefault(key, set()).add(requirement.source_output)

    observations: list[FiledDeclaracionObservation] = []
    async with open_declarations_register(session, settings=settings, playwright=playwright) as register:
        for (modelo, source_year, source_period), source_outputs in sorted(required_outputs.items()):
            rows = await register.walk(modelo=modelo, ejercicio=source_year)
            matches = tuple(row for row in rows if row.period == source_period)
            declaration = _select_authoritative_declaration(
                matches,
                modelo=modelo,
                ejercicio=source_year,
                period=source_period,
                context="relation source requirement",
            )
            observation = await register.capture_observation(declaration, artefact_sink=artefact_sink)
            observation = _with_derived_303_compensation_available_observation(observation)
            observed_casillas = {casilla.casilla_id for casilla in observation.casillas}
            missing = sorted(source_outputs.difference(observed_casillas))
            if missing:
                raise SedeParseError(
                    f"relation source requirement {modelo!r}/{source_year}/{source_period!r} "
                    f"missing observed casillas {missing!r}",
                )
            observations.append(observation)
    return tuple(observations)


def _select_authoritative_declaration(
    declarations: tuple[Declaracion, ...],
    *,
    modelo: str,
    ejercicio: int,
    period: str,
    context: str,
) -> Declaracion:
    """Select the latest accepted register row for one filed period."""
    if not declarations:
        raise SedeParseError(f"{context} {modelo!r}/{ejercicio}/{period!r} found no filed declaration")
    active = tuple(row for row in declarations if row.estado.upper() == "ALTA")
    candidates = active or declarations
    return max(candidates, key=lambda row: (row.presented_at, row.expediente_id))


async def _capture_row_pdf_artefact(
    *,
    context: BrowserContext,
    row_locator,
    declaration: Declaracion,
    cell_index: int,
    kind: Literal["justificante_pdf", "declaration_pdf"],
    read_policy: RemoteStateGuardPolicy,
) -> tuple[FiledDeclaracionArtefact, bytes]:
    button = row_locator.locator(".z-listcell").nth(cell_index).locator(".z-button").first
    try:
        async with context.expect_page(timeout=_get_ver_click_timeout_ms()) as new_page_info:
            _assert_read_browser_action("open-cotejo-pdf", policy=read_policy)
            await button.click(timeout=_get_form_interaction_timeout_ms())
        cotejo_page = await new_page_info.value
    except PlaywrightError as exc:
        raise SedeNavigationError(
            f"clicking PDF artefact for {declaration.expediente_id!r} failed: {exc}",
        ) from exc

    try:
        await cotejo_page.wait_for_load_state(_WAIT_DOMCONTENTLOADED, timeout=_get_navigation_timeout_ms())
    except PlaywrightError as exc:
        raise SedeNavigationError(
            f"PDF artefact page did not settle for {declaration.expediente_id!r}: {exc}",
        ) from exc

    cotejo_url = cotejo_page.url
    if _COTEJO_PATH_PREFIX not in cotejo_url:
        raise SedeNavigationError(
            f"PDF artefact for {declaration.expediente_id!r} did not land on a cotejo URL (final URL: {cotejo_url!r})",
        )

    csv = _extract_csv_from_url(cotejo_url)
    pdf_url = AnyHttpUrl(f"{_COTEJO_DOC}?CSV={csv}")
    _assert_read_http("GET", str(pdf_url), policy=read_policy)
    response = await context.request.get(str(pdf_url))
    if not (200 <= response.status < 300):
        raise JustificanteFetchError(f"PDF fetch for CSV={csv!r} returned HTTP {response.status}")
    content_type = response.headers.get("content-type", "")
    body = await response.body()
    if not body:
        raise JustificanteFetchError(f"empty PDF body for CSV={csv!r}")
    if "pdf" not in content_type.lower():
        raise JustificanteFetchError(f"unexpected content-type {content_type!r} for CSV={csv!r}")
    return (
        FiledDeclaracionArtefact(
            kind=kind,
            source_url=pdf_url,
            content_type=content_type,
            byte_count=len(body),
            sha256=hashlib.sha256(body).hexdigest(),
            captured_at=now(),
        ),
        body,
    )


async def _capture_submitted_file_artefact(
    *,
    page: Page,
    row_locator,
    declaration: Declaracion,
    cell_index: int,
    read_policy: RemoteStateGuardPolicy,
) -> tuple[FiledDeclaracionArtefact, bytes]:
    button = row_locator.locator(".z-listcell").nth(cell_index).locator(".z-button").first
    try:
        async with page.expect_download(timeout=_get_ver_click_timeout_ms()) as download_info:
            _assert_read_browser_action("download-filed-data-file", policy=read_policy)
            await button.click(timeout=_get_form_interaction_timeout_ms())
        download = await download_info.value
        path = await download.path()
    except PlaywrightError as exc:
        raise SedeNavigationError(
            f"submitted-file download for {declaration.expediente_id!r} failed: {exc}",
        ) from exc

    if path is None:
        raise SedeNavigationError(
            f"submitted-file download for {declaration.expediente_id!r} did not expose a local path",
        )
    body = Path(path).read_bytes()
    if not body:
        raise JustificanteFetchError(
            f"submitted-file download for {declaration.expediente_id!r} returned an empty body",
        )
    download_url = getattr(download, "url", None)
    source_url = download_url if isinstance(download_url, str) else None
    if not source_url:
        source_url = str(AnyHttpUrl(f"{_LISTING_URL}?MODELO={declaration.modelo}&EJERCICIO={declaration.ejercicio}"))
    _assert_read_http("GET", source_url, policy=read_policy)
    return (
        FiledDeclaracionArtefact(
            kind="submitted_file",
            source_url=AnyHttpUrl(source_url),
            content_type=_BINARY_MIME_TYPE,
            byte_count=len(body),
            sha256=hashlib.sha256(body).hexdigest(),
            captured_at=now(),
        ),
        body,
    )


def _row_locator_for_expediente(page: Page, *, expediente_id: str):
    """Return a Playwright locator pointing at the listitem whose ``Expediente`` cell text equals ``expediente_id``."""
    return page.locator(".z-listitem").filter(
        has=page.locator(".z-listcell").filter(has_text=expediente_id),
    )


def _assert_read_http(
    method: str,
    url: str,
    *,
    policy: RemoteStateGuardPolicy = _READ_GUARD_POLICY,
) -> None:
    _remote_assert_read_http(method, url, policy=policy)


def _assert_read_browser_action(
    action: str,
    *,
    policy: RemoteStateGuardPolicy = _READ_GUARD_POLICY,
) -> None:
    _remote_assert_read_browser_action(action, policy=policy)


__all__ = [
    "_JSON_MIME_TYPE",
    "Declaracion",
    "DeclaracionesRegisterSession",
    "_parse_presented_at",
    "_temporary_sensitive_pdf_path",
    "_verify_submitted_file_context",
    "capture_declaration",
    "capture_filed_declaration_observation",
    "capture_previous_filing_observations",
    "capture_relation_source_observations",
    "open_declarations_register",
    "registry_observation_from_filed_declaration",
    "resolve_previous_filing_bindings_from_filed_declarations",
    "resolve_relation_values_from_filed_declarations",
    "shared_playwright",
    "walk_declarations_register",
]
