//! Release checks against externally supplied build expectations and manifest identity.
use super::{PackageInspection, PackageManifest, Readiness};
use crate::{
    error::Error,
    filesystem,
    value::{RelativePath, Sha256Digest},
};
use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::{collections::BTreeSet, path::Path};

/// Generated by the release owner, never inferred from the package under inspection.
/// The manifest digest binds bytes to that input; it does not authenticate its publisher.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ReleaseExpectation {
    pub manifest_sha256: Sha256Digest,
    /// Physical layout spelling, which can differ from the canonical release target.
    pub platform: String,
    pub abi: u32,
    pub target: String,
    pub python: String,
    pub version: String,
    pub channel: String,
    /// Canonical first-party distribution names, all required at `version`.
    pub cohort: Vec<String>,
}

#[derive(Deserialize)]
struct ReleaseDocument {
    build: BuildIdentity,
    layout: Layout,
}

#[derive(Deserialize)]
struct BuildIdentity {
    version: String,
    python: String,
    layout_abi: u32,
    target: String,
    channel: String,
}

#[derive(Deserialize)]
struct Layout {
    files: Locations,
}

#[derive(Deserialize)]
struct Locations {
    build_metadata: RelativePath,
}

/// Effect-free release admission using the assembler's single inventory.
///
/// Existing low-level inventory inspection remains available separately. All inputs are
/// required: callers cannot accidentally turn this into a self-reported version check.
pub fn inspect_release(
    root: &Path,
    manifest_path: &RelativePath,
    expected: &ReleaseExpectation,
) -> Result<PackageInspection, Error> {
    filesystem::absolute_root(root)?;
    if [
        &expected.platform,
        &expected.target,
        &expected.python,
        &expected.version,
        &expected.channel,
    ]
    .iter()
    .any(|value| value.is_empty())
        || expected.cohort.is_empty()
        || expected.cohort.iter().any(|name| name.is_empty())
        || expected.cohort.iter().collect::<BTreeSet<_>>().len() != expected.cohort.len()
    {
        return Err(Error::Invalid("incomplete release expectations".into()));
    }
    let bytes = filesystem::json_bytes(&manifest_path.under(root))?;
    if format!("{:x}", Sha256::digest(&bytes)) != expected.manifest_sha256.as_str() {
        return Err(Error::Integrity("package manifest differs".into()));
    }
    let manifest: PackageManifest = serde_json::from_slice(&bytes)?;
    let document: ReleaseDocument = serde_json::from_slice(&bytes)?;
    let mut inspection = manifest.inspect(root, manifest_path, &expected.platform, expected.abi)?;
    if inspection.readiness != Readiness::Ready {
        return Ok(inspection);
    }
    let build = document.build;
    if build.target != expected.target
        || build.layout_abi != expected.abi
        || build.version != expected.version
        || build.channel != expected.channel
        || build.python != expected.python
        || inspection.manifest.python != expected.python
    {
        inspection.readiness = Readiness::Incompatible("package release identity differs".into());
        return Ok(inspection);
    }
    for name in &expected.cohort {
        match inspection.manifest.distributions.get(name) {
            None => {
                inspection.readiness = Readiness::Missing(format!("release distribution: {name}"));
                return Ok(inspection);
            }
            Some(version) if version != &expected.version => {
                inspection.readiness =
                    Readiness::Incompatible(format!("release distribution: {name}"));
                return Ok(inspection);
            }
            Some(_) => {}
        }
    }
    let metadata = document.layout.files.build_metadata;
    if !inspection.manifest.files.contains_key(&metadata) {
        return Err(Error::Invalid(
            "build metadata is absent from package inventory".into(),
        ));
    }
    let metadata_bytes = filesystem::json_bytes(&metadata.under(root))?;
    if format!("{:x}", Sha256::digest(&metadata_bytes))
        != inspection.manifest.files[&metadata].as_str()
    {
        return Err(Error::Integrity(
            "build metadata changed during inspection".into(),
        ));
    }
    let recorded: serde_json::Value = serde_json::from_slice(&metadata_bytes)?;
    let manifest_value: serde_json::Value = serde_json::from_slice(&bytes)?;
    if recorded != manifest_value["build"] {
        inspection.readiness = Readiness::Incompatible("manifest and build metadata differ".into());
    }
    Ok(inspection)
}
