"""The closed, hand-reviewed classification table the Modelo action denominator reads.

This module is a declaration, not mechanism. It holds one reviewed row per
live modelo action candidate and nothing else, so that adding an action is a
data change with a visible diff rather than an edit inside a gate.

The vocabulary these rows are written in is defined by the sibling
classification module; the gate that consumes them is the denominator module.
Neither is imported here beyond the types, because a data declaration that
reaches into mechanism stops being reviewable as data.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Final

from cadrumo.entrypoints.cli.command_spec import TuiCapability

from .modelo_workspace_action_classification import (
    ModeloWorkspaceActionClassificationV1,
    ModeloWorkspaceActionDisposition,
    modelo_action_classification,
)

# Closed, hand-reviewed classification table. Every row was generated once from
# the mechanical rule documented in the module docstring and then reviewed;
# regenerating it is a deliberate act, never an implicit side effect of
# validation. See `dev/tests/test_modelo_workspace_action_denominator.py` for
# the anti-vacuity proof that a live candidate missing from this table reds.
MODELO_ACTION_CLASSIFICATIONS: Final[Mapping[str, ModeloWorkspaceActionClassificationV1]] = {
    "modelo.aggregate": modelo_action_classification(
        "modelo.aggregate",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_aggregate",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.audit.check": modelo_action_classification(
        "modelo.audit.check",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_audit_check",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.audit.export": modelo_action_classification(
        "modelo.audit.export",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_audit_export",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.audit.view": modelo_action_classification(
        "modelo.audit.view",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_audit_view",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.bindings.list": modelo_action_classification(
        "modelo.bindings.list",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_bindings_list",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=True,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.bindings.resolve": modelo_action_classification(
        "modelo.bindings.resolve",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_bindings_resolve",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.casilla": modelo_action_classification(
        "modelo.casilla",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_casilla",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.casillas": modelo_action_classification(
        "modelo.casillas",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_casillas",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.compare": modelo_action_classification(
        "modelo.compare",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_compare",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.describe": modelo_action_classification(
        "modelo.describe",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_describe",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=True,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.export": modelo_action_classification(
        "modelo.export",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_export",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=True,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.filing_record.import": modelo_action_classification(
        "modelo.filing_record.import",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_filing_record_import",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.filing_record.list": modelo_action_classification(
        "modelo.filing_record.list",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_filing_record_list",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=True,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.filing_record.observe_local": modelo_action_classification(
        "modelo.filing_record.observe_local",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_filing_record_observe_local",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.filing_record.view": modelo_action_classification(
        "modelo.filing_record.view",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_filing_record_view",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.formulas": modelo_action_classification(
        "modelo.formulas",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_formulas",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.history": modelo_action_classification(
        "modelo.history",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_history",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.iva_wallet.balance": modelo_action_classification(
        "modelo.iva_wallet.balance",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_iva_wallet_balance",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.iva_wallet.correct": modelo_action_classification(
        "modelo.iva_wallet.correct",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_iva_wallet_correct",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.iva_wallet.override": modelo_action_classification(
        "modelo.iva_wallet.override",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_iva_wallet_override",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.iva_wallet.seed": modelo_action_classification(
        "modelo.iva_wallet.seed",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_iva_wallet_seed",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.list": modelo_action_classification(
        "modelo.list",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_list",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.m036.alta": modelo_action_classification(
        "modelo.m036.alta",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_m036_alta",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.m036.baja": modelo_action_classification(
        "modelo.m036.baja",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_m036_baja",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.m036.list": modelo_action_classification(
        "modelo.m036.list",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_m036_list",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.m036.modificacion": modelo_action_classification(
        "modelo.m036.modificacion",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_m036_modificacion",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.m036.view": modelo_action_classification(
        "modelo.m036.view",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_m036_view",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.m145.create": modelo_action_classification(
        "modelo.m145.create",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_m145_create",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.m145.export": modelo_action_classification(
        "modelo.m145.export",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_m145_export",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.m145.mark_delivered_to_payer": modelo_action_classification(
        "modelo.m145.mark_delivered_to_payer",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_m145_mark_delivered_to_payer",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.m145.mark_locally_completed": modelo_action_classification(
        "modelo.m145.mark_locally_completed",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_m145_mark_locally_completed",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.m145.validate": modelo_action_classification(
        "modelo.m145.validate",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_m145_validate",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.project": modelo_action_classification(
        "modelo.project",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_project",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.readiness": modelo_action_classification(
        "modelo.readiness",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_readiness",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.reconcile.list": modelo_action_classification(
        "modelo.reconcile.list",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_reconcile_list",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.reconcile.import": modelo_action_classification(
        "modelo.reconcile.import",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_reconcile_import",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.reconcile.pull": modelo_action_classification(
        "modelo.reconcile.pull",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_reconcile_pull",
        write_route="profile-bound",
        side_effects=("browser", "local-state", "network"),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.requires": modelo_action_classification(
        "modelo.requires",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_requires",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.review_package.build": modelo_action_classification(
        "modelo.review_package.build",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_review_package_build",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.review_package.counter_sign": modelo_action_classification(
        "modelo.review_package.counter_sign",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_review_package_counter_sign",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.review_package.decrypt": modelo_action_classification(
        "modelo.review_package.decrypt",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_review_package_decrypt",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.review_package.encrypt_feedback": modelo_action_classification(
        "modelo.review_package.encrypt_feedback",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_review_package_encrypt_feedback",
        write_route="none",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.review_package.encrypt_for_recipient": modelo_action_classification(
        "modelo.review_package.encrypt_for_recipient",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_review_package_encrypt_for_recipient",
        write_route="none",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.review_package.import_feedback": modelo_action_classification(
        "modelo.review_package.import_feedback",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_review_package_import_feedback",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.review_package.sign": modelo_action_classification(
        "modelo.review_package.sign",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_review_package_sign",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.review_package.verify": modelo_action_classification(
        "modelo.review_package.verify",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_review_package_verify",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.review_package.verify_receipt": modelo_action_classification(
        "modelo.review_package.verify_receipt",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_review_package_verify_receipt",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.review_package.verify_signature": modelo_action_classification(
        "modelo.review_package.verify_signature",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_review_package_verify_signature",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.spreadsheet.calculate": modelo_action_classification(
        "modelo.spreadsheet.calculate",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_spreadsheet_calculate",
        write_route="profile-bound",
        side_effects=("google", "local-state"),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.spreadsheet.pull": modelo_action_classification(
        "modelo.spreadsheet.pull",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_spreadsheet_pull",
        write_route="profile-bound",
        side_effects=("google", "local-state"),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.spreadsheet.push": modelo_action_classification(
        "modelo.spreadsheet.push",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_spreadsheet_push",
        write_route="profile-bound",
        side_effects=("google", "local-state"),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.spreadsheet.verify": modelo_action_classification(
        "modelo.spreadsheet.verify",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_spreadsheet_verify",
        write_route="none",
        side_effects=("google",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.support_matrix": modelo_action_classification(
        "modelo.support_matrix",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_support_matrix",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.verification_report.list": modelo_action_classification(
        "modelo.verification_report.list",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_verification_report_list",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=True,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.verification_report.view": modelo_action_classification(
        "modelo.verification_report.view",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_verification_report_view",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.work.amend": modelo_action_classification(
        "modelo.work.amend",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_work_amend",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=True,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.work.amend_wizard": modelo_action_classification(
        "modelo.work.amend_wizard",
        ModeloWorkspaceActionDisposition.FLOW_OWNED,
        command_key="app_modelo_work_amend_wizard",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-architecture guided flows",
        reason="guided-wizard command; owned by a flow renderer, not a Workspace destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens only if C4 assigns this wizard a distinct disposition",
    ),
    "modelo.work.calculate": modelo_action_classification(
        "modelo.work.calculate",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_work_calculate",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=True,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.work.compare_taxation": modelo_action_classification(
        "modelo.work.compare_taxation",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_work_compare_taxation",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.work.create": modelo_action_classification(
        "modelo.work.create",
        ModeloWorkspaceActionDisposition.DEFERRED,
        command_key="app_modelo_work_create",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=True,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="work-lifecycle ownership",
        reason="work-unit lifecycle creation is owned outside this interface plan",
        evidence_reference="work-unit lifecycle creation ownership, tracked outside this interface effort",
        reopening_condition="reopens only if a future accepted decision moves this into scope",
    ),
    "modelo.work.dependencies": modelo_action_classification(
        "modelo.work.dependencies",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_work_dependencies",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.work.discard": modelo_action_classification(
        "modelo.work.discard",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_work_discard",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=True,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.work.file": modelo_action_classification(
        "modelo.work.file",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_work_file",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=True,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=True,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.work.history": modelo_action_classification(
        "modelo.work.history",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_work_history",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.work.list": modelo_action_classification(
        "modelo.work.list",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_work_list",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=True,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.work.observations": modelo_action_classification(
        "modelo.work.observations",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_work_observations",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.work.preview_maritime_exemption": modelo_action_classification(
        "modelo.work.preview_maritime_exemption",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_work_preview_maritime_exemption",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.work.rename": modelo_action_classification(
        "modelo.work.rename",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_work_rename",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=True,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.work.resume": modelo_action_classification(
        "modelo.work.resume",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_work_resume",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.work.review": modelo_action_classification(
        "modelo.work.review",
        ModeloWorkspaceActionDisposition.C1_BOUNDED_REVIEW,
        command_key="app_modelo_work_review",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.AVAILABLE,
        is_surface_dispatchable=False,
        owning_authority="tui-architecture W04.P10.S104",
        reason="canonically relocated to the C1 bounded-review destination",
        evidence_reference="the independently verified modelo.work.review relocation review",
        reopening_condition="never reopens: terminal C1 disposition",
    ),
    "modelo.work.select": modelo_action_classification(
        "modelo.work.select",
        ModeloWorkspaceActionDisposition.C1_BOUNDED_REVIEW,
        command_key="app_modelo_work_select",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.AVAILABLE,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10.S24",
        reason="the sole C1 work-unit picker entrance into modelo.work.review",
        evidence_reference="src/cadrumo/entrypoints/tui/modelo/view/work_select.py",
        reopening_condition="never reopens: terminal C1 disposition",
    ),
    "modelo.work.revision": modelo_action_classification(
        "modelo.work.revision",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_work_revision",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.work.revisions": modelo_action_classification(
        "modelo.work.revisions",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_work_revisions",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=True,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.work.run": modelo_action_classification(
        "modelo.work.run",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_work_run",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.work.run_details": modelo_action_classification(
        "modelo.work.run_details",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_work_run_details",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.work.runs": modelo_action_classification(
        "modelo.work.runs",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_work_runs",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.work.status": modelo_action_classification(
        "modelo.work.status",
        ModeloWorkspaceActionDisposition.C1_OR_C2_READ_PENDING,
        command_key="app_modelo_work_status",
        write_route="none",
        side_effects=("none",),
        has_action_catalogue_entry=True,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-interface W05.P10/W05.P11",
        reason="read-only query, not yet migrated to a C1 or C2 destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens on migration to a numbered C1/C2 destination in the same commit",
    ),
    "modelo.work.verify": modelo_action_classification(
        "modelo.work.verify",
        ModeloWorkspaceActionDisposition.C4_MUTATION_PENDING,
        command_key="app_modelo_work_verify",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=True,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=True,
        owning_authority="tui-interface W06.P12c",
        reason="direct-effect mutation; no lifecycle control before the C3/C4 conformance suites are green",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens once the C3/C4 conformance suites are green and this is enrolled as a C4 action",
    ),
    "modelo.work.wizard": modelo_action_classification(
        "modelo.work.wizard",
        ModeloWorkspaceActionDisposition.FLOW_OWNED,
        command_key="app_modelo_work_wizard",
        write_route="profile-bound",
        side_effects=("local-state",),
        has_action_catalogue_entry=False,
        tui_capability=TuiCapability.NOT_IMPLEMENTED,
        is_surface_dispatchable=False,
        owning_authority="tui-architecture guided flows",
        reason="guided-wizard command; owned by a flow renderer, not a Workspace destination",
        evidence_reference="the accepted Modelo Workspace interface decision's C1-C4 cohort disposition framing",
        reopening_condition="reopens only if C4 assigns this wizard a distinct disposition",
    ),
}


__all__: tuple[str, ...] = ("MODELO_ACTION_CLASSIFICATIONS",)
