from collections.abc import Iterator

class Authenticator:
    def __init__(self, enable_fds: bool = False, inc_null_byte: bool = True) -> None: ...
    def __iter__(self) -> Iterator[bytes]: ...
    def feed(self, data: bytes) -> None: ...
