[[revisions."2024-y-siguientes".export_layouts]]
id = "modelo-200-fichero-boe"

[[revisions."2024-y-siguientes".export_layouts.records]]
id = "modelo-200-page-001b"
record_type = "page_001b"
order = 2
encoding = "latin-1"
line_ending = "none"

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-filler-pos-1"
offset = 1
length = 2
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-filler-pos-3"
offset = 3
length = 3
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-filler-pos-6"
offset = 6
length = 5
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-filler-pos-11"
offset = 11
length = 1
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-filler-pos-12"
offset = 12
length = 1
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-casilla-00040"
offset = 13
length = 7
kind = "casilla"
casilla_id = "00040"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-filler-pos-20"
offset = 20
length = 9
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-filler-pos-29"
offset = 29
length = 15
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-filler-pos-44"
offset = 44
length = 15
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-filler-pos-59"
offset = 59
length = 40
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-filler-pos-99"
offset = 99
length = 40
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-filler-pos-139"
offset = 139
length = 2
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-draft-profile_tax_id-pos-141"
offset = 141
length = 15
kind = "draft"
draft_attribute = "profile_tax_id"
data_type = "text"
required = true
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-filler-pos-156"
offset = 156
length = 1
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-filler-pos-157"
offset = 157
length = 1
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-filler-pos-158"
offset = 158
length = 1
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-casilla-00061"
offset = 159
length = 1
kind = "casilla"
casilla_id = "00061"
data_type = "decimal"
required = false
padding = "left_zero"
justification = "right"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-casilla-00068"
offset = 160
length = 1
kind = "casilla"
casilla_id = "00068"
data_type = "decimal"
required = false
padding = "left_zero"
justification = "right"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-filler-pos-161"
offset = 161
length = 1
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-casilla-00041"
offset = 162
length = 9
kind = "casilla"
casilla_id = "00041"
data_type = "decimal"
required = false
padding = "left_zero"
justification = "right"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-casilla-00042"
offset = 171
length = 9
kind = "casilla"
casilla_id = "00042"
data_type = "decimal"
required = false
padding = "left_zero"
justification = "right"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-filler-pos-180"
offset = 180
length = 200
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-001b-filler-pos-380"
offset = 380
length = 12
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]
