[[revisions."2024-y-siguientes".export_layouts]]
id = "modelo-200-fichero-boe"

[[revisions."2024-y-siguientes".export_layouts.records]]
id = "modelo-200-page-002b"

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-002b-filler-pos-2150"
offset = 2150
length = 9
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-002b-filler-pos-2159"
offset = 2159
length = 9
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-002b-filler-pos-2168"
offset = 2168
length = 9
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-002b-filler-pos-2177"
offset = 2177
length = 9
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-002b-filler-pos-2186"
offset = 2186
length = 9
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-002b-filler-pos-2195"
offset = 2195
length = 9
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-002b-filler-pos-2204"
offset = 2204
length = 9
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-002b-filler-pos-2214"
offset = 2214
length = 1
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-002b-filler-pos-2215"
offset = 2215
length = 18
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-002b-filler-pos-2233"
offset = 2233
length = 40
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-002b-filler-pos-2273"
offset = 2273
length = 2
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-002b-filler-pos-2275"
offset = 2275
length = 8
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-002b-filler-pos-2283"
offset = 2283
length = 2
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-002b-filler-pos-2285"
offset = 2285
length = 2
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-002b-filler-pos-2512"
offset = 2512
length = 200
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-002b-filler-pos-2712"
offset = 2712
length = 12
kind = "filler"
data_type = "text"
required = false
padding = "right_space"
justification = "left"
signed = false
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]
