"""Ordered adapter :class:`~cadrumo.core.errors.ErrorCode` registry shard.

Rows map adapter-layer exception qualnames to stable
:class:`~cadrumo.core.errors.ErrorCategory` values and locale message keys.
"""

from .._registry import ErrorCategory, ErrorCode

_DECLARED_ERROR_CODES: tuple[tuple[str, ErrorCode], ...] = (
    (
        "cadrumo.adapters.outbound.aeat.auth._errors.AeatLoginAssertionError",
        ErrorCode(
            code="AUTH_AEAT_LOGIN_ASSERTION",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_aeat_login_assertion",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.auth._errors.AeatSessionExpiredError",
        ErrorCode(
            code="AUTH_AEAT_SESSION_EXPIRED",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_aeat_session_expired",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.auth._session_store.FormerProductAuthSessionStateError",
        ErrorCode(
            code="AUTH_FORMER_PRODUCT_SESSION_STATE",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_former_product_session_state",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.export._errors.ExportError",
        ErrorCode(
            code="FAIL_EXPORT",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_export",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.inbound.financial.providers._base.FinancialProviderError",
        ErrorCode(
            code="ERROR_FINANCIAL_PROVIDER",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_provider",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.inbound.financial.providers._base.UnsupportedFinancialSourceError",
        ErrorCode(
            code="REFUSED_FINANCIAL_PROVIDER_UNSUPPORTED_SOURCE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_financial_provider_unsupported_source",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.inbound.financial.providers._base.InvalidFinancialSourceError",
        ErrorCode(
            code="REFUSED_FINANCIAL_PROVIDER_INVALID_SOURCE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_financial_provider_invalid_source",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.inbound.financial.providers._base.FinancialValidationError",
        ErrorCode(
            code="REFUSED_FINANCIAL_PROVIDER_VALIDATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_financial_provider_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.inbound.financial.providers._base.BankStatementParseError",
        ErrorCode(
            code="REFUSED_FINANCIAL_BANK_STATEMENT_PARSE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_financial_bank_statement_parse",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.inbound.einvoice._xml.EInvoiceXmlParseError",
        ErrorCode(
            code="REFUSED_EINVOICE_XML_PARSE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_einvoice_xml_parse",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.llm._errors.LLMError",
        ErrorCode(
            code="ERROR_LLM",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_llm",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.llm._errors.LLMProviderError",
        ErrorCode(
            code="FAIL_LLM_PROVIDER",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_llm_provider",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.llm._errors.LLMTransientTransportError",
        ErrorCode(
            code="FAIL_LLM_TRANSIENT_TRANSPORT",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_llm_transient_transport",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.llm._errors.LLMPdfRasterisationError",
        ErrorCode(
            code="FAIL_LLM_PDF_RASTERISATION",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_llm_pdf_rasterisation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.llm._errors.LLMCacheError",
        ErrorCode(
            code="FAIL_LLM_CACHE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_llm_cache",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.llm._errors.LLMRateLimitError",
        ErrorCode(
            code="FAIL_LLM_RATE_LIMIT",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_llm_rate_limit",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.llm._errors.LLMConfigError",
        ErrorCode(
            code="REFUSED_LLM_CONFIG",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_llm_config",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.llm._errors.LLMContentionError",
        ErrorCode(
            code="REFUSED_LLM_CONTENTION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_llm_contention",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.llm._errors.LLMBusyError",
        ErrorCode(
            code="REFUSED_LLM_BUSY",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_llm_busy",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.llm._errors.LLMConsentError",
        ErrorCode(
            code="REFUSED_LLM_CONSENT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_llm_consent",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.llm._errors.LLMValidationError",
        ErrorCode(
            code="REFUSED_LLM_VALIDATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_llm_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.google._errors.GoogleAuthError",
        ErrorCode(
            code="AUTH_GOOGLE",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_google",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.google._errors.GoogleAuthValidationError",
        ErrorCode(
            code="REFUSED_GOOGLE_VALIDATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_google_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.google._errors.GoogleAuthClientNotRegisteredError",
        ErrorCode(
            code="AUTH_GOOGLE_CLIENT_NOT_REGISTERED",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_google_client_not_registered",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.google._errors.GoogleAuthClientRevokedError",
        ErrorCode(
            code="AUTH_GOOGLE_CLIENT_REVOKED",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_google_client_revoked",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.google._errors.GoogleAuthRevokedError",
        ErrorCode(
            code="AUTH_GOOGLE_REVOKED",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_google_revoked",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.google._errors.GoogleAuthExpiredError",
        ErrorCode(
            code="AUTH_GOOGLE_EXPIRED",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_google_expired",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.google._errors.GoogleAuthScopeInsufficientError",
        ErrorCode(
            code="AUTH_GOOGLE_SCOPE_INSUFFICIENT",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_google_scope_insufficient",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.google._errors.GoogleAuthNetworkError",
        ErrorCode(
            code="FAIL_GOOGLE_NETWORK",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_google_network",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.google._errors.GoogleAuthLoopbackBindError",
        ErrorCode(
            code="FAIL_GOOGLE_LOOPBACK_BIND",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_google_loopback_bind",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.google._errors.GoogleAuthBrowserOpenError",
        ErrorCode(
            code="FAIL_GOOGLE_BROWSER_OPEN",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_google_browser_open",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.google._errors.GoogleAuthNonInteractiveError",
        ErrorCode(
            code="REFUSED_GOOGLE_NON_INTERACTIVE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_google_non_interactive",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.google._errors.GoogleAuthUnsecuredModeRefusedError",
        ErrorCode(
            code="REFUSED_GOOGLE_UNSECURED_MODE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_google_unsecured_mode",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.google._errors.GoogleAuthKeychainLockedError",
        ErrorCode(
            code="LOCKED_GOOGLE_KEYCHAIN",
            category=ErrorCategory.LOCKED,
            message_key="errors.locked.locked_google_keychain",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.google._errors.GoogleAuthProfileUnboundError",
        ErrorCode(
            code="REFUSED_GOOGLE_PROFILE_UNBOUND",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_google_profile_unbound",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.google._impersonation.GoogleAuthAdcUnavailableError",
        ErrorCode(
            code="FAIL_GOOGLE_ADC_UNAVAILABLE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_google_adc_unavailable",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.google._impersonation.GoogleAuthAdcStaleError",
        ErrorCode(
            code="FAIL_GOOGLE_ADC_STALE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_google_adc_stale",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.google._impersonation.GoogleAuthImpersonationRefusedError",
        ErrorCode(
            code="REFUSED_GOOGLE_IMPERSONATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_google_impersonation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.storage._errors.OutboundStorageError",
        ErrorCode(
            code="FAIL_OUTBOUND_STORAGE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_outbound_storage",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.storage._errors.OutboundStorageValidationError",
        ErrorCode(
            code="REFUSED_OUTBOUND_STORAGE_VALIDATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_outbound_storage_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.storage._errors.OutboundStorageNotFoundError",
        ErrorCode(
            code="ERROR_OUTBOUND_STORAGE_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_outbound_storage_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.storage._errors.OutboundStorageConflictError",
        ErrorCode(
            code="REFUSED_OUTBOUND_STORAGE_CONFLICT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_outbound_storage_conflict",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.storage._errors.OutboundStoragePermissionError",
        ErrorCode(
            code="AUTH_OUTBOUND_STORAGE_PERMISSION",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_outbound_storage_permission",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.storage._errors.OutboundStoragePathTooLongError",
        ErrorCode(
            code="ERROR_OUTBOUND_STORAGE_PATH_TOO_LONG",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_outbound_storage_path_too_long",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.storage._errors.OutboundStorageQuotaError",
        ErrorCode(
            code="REFUSED_OUTBOUND_STORAGE_QUOTA",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_outbound_storage_quota",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.storage._errors.OutboundStorageNetworkError",
        ErrorCode(
            code="FAIL_OUTBOUND_STORAGE_NETWORK",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_outbound_storage_network",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.storage._errors.OutboundStorageIntegrityError",
        ErrorCode(
            code="INTEGRITY_OUTBOUND_STORAGE",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_outbound_storage",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.storage._errors.OutboundStorageUnavailableError",
        ErrorCode(
            code="FAIL_OUTBOUND_STORAGE_UNAVAILABLE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_outbound_storage_unavailable",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.storage._errors.StorageCorruptionError",
        ErrorCode(
            code="INTEGRITY_OUTBOUND_STORAGE_CORRUPTION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_outbound_storage_corruption",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.master_key._active_session.NoActiveBucketSessionError",
        ErrorCode(
            code="REFUSED_STORAGE_MASTER_KEY_NO_ACTIVE_SESSION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_storage_master_key_no_active_session",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.bucket._errors.BucketError",
        ErrorCode(
            code="ERROR_STORAGE_BUCKET",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_storage_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.bucket._errors.NoActiveBucketError",
        ErrorCode(
            code="REFUSED_STORAGE_BUCKET_NO_ACTIVE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_storage_bucket_no_active",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.bucket._errors.BucketBusyError",
        ErrorCode(
            code="LOCKED_STORAGE_BUCKET_BUSY",
            category=ErrorCategory.LOCKED,
            message_key="errors.locked.locked_storage_bucket_busy",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.bucket._errors.BucketAlreadyPresentError",
        ErrorCode(
            code="REFUSED_STORAGE_BUCKET_ALREADY_PRESENT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_storage_bucket_already_present",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.bucket._errors.BucketPathTooLongError",
        ErrorCode(
            code="ERROR_STORAGE_BUCKET_PATH_TOO_LONG",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_storage_bucket_path_too_long",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.bucket._errors.BucketLockedError",
        ErrorCode(
            code="LOCKED_STORAGE_BUCKET_SESSION",
            category=ErrorCategory.LOCKED,
            message_key="errors.locked.locked_storage_bucket_session",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.bucket._errors.BucketValidationError",
        ErrorCode(
            code="INTEGRITY_STORAGE_BUCKET_VALIDATION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_bucket_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.bucket._errors.RecoveryUnavailableError",
        ErrorCode(
            code="FAIL_STORAGE_BUCKET_RECOVERY_UNAVAILABLE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_storage_bucket_recovery_unavailable",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.bucket._errors.RecoveryVerificationError",
        ErrorCode(
            code="AUTH_STORAGE_BUCKET_RECOVERY_VERIFICATION",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_storage_bucket_recovery_verification",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.NamespaceRegistryError",
        ErrorCode(
            code="INTEGRITY_STORAGE_NAMESPACE_REGISTRY",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_namespace_registry",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.master_key._errors.MasterKeyReentrantError",
        ErrorCode(
            code="INTERNAL_MASTER_KEY_REENTRANT",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.internal_master_key_reentrant",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.custody._errors.WipeTypeError",
        ErrorCode(
            code="INTERNAL_WIPE_TYPE",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.internal_wipe_type",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.custody._errors.ProfileCustodyError",
        ErrorCode(
            code="FAIL_STORAGE_PROFILE_CUSTODY",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_storage_profile_custody",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.custody._errors.ProfileCustodyRecordError",
        ErrorCode(
            code="INTEGRITY_STORAGE_PROFILE_CUSTODY_RECORD",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_profile_custody_record",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.custody._errors.ProfileCustodyPasswordError",
        ErrorCode(
            code="REFUSED_STORAGE_PROFILE_CUSTODY_PASSWORD",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_storage_profile_custody_password",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.custody._errors.ProfileCustodyRecoverySecretError",
        ErrorCode(
            code="REFUSED_STORAGE_PROFILE_CUSTODY_RECOVERY_SECRET",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_storage_profile_custody",
            retryable=False,
            runbook_id=None,
        ),
    ),
    # `retryable=False` is a considered value, not an oversight, and it has been
    # questioned once already. Two of the four refusals this class carries DO have
    # transient causes -- the KDF resource limit fires on insufficient available
    # memory, and supervision-unavailable on a worker that could not be spawned --
    # so `True` looks defensible in isolation. It is not, because the class spans
    # 38 raise sites whose causes are genuinely mixed: worker ATTESTATION failures,
    # Windows job-object capability failures, and permanent host limits sit beside
    # the transient ones, and retry is actively wrong for the first group. The
    # asymmetry decides it: `False` on a transient failure costs one operation the
    # operator can repeat by hand, while `True` on a permanent one hands an
    # autonomous agent an unbounded loop against a host that will never succeed.
    # The operator-facing messages carry the recurrence-keyed guidance the boolean
    # cannot ("retry when the machine is less loaded; if it persists ...").
    (
        "cadrumo.adapters.persistence.storage.custody._errors.ProfileCustodyRefusedError",
        ErrorCode(
            code="REFUSED_STORAGE_PROFILE_CUSTODY",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_storage_profile_custody",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.inbound.financial.providers._base.FinancialProviderConfigError",
        ErrorCode(
            code="ERROR_FINANCIAL_PROVIDER_CONFIG",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_provider_config",
            retryable=False,
            runbook_id=None,
        ),
    ),
)
