"""Ordered adapter :class:`~cadrumo.core.errors.ErrorCode` registry shard.

Rows map adapter-layer exception qualnames to stable
:class:`~cadrumo.core.errors.ErrorCategory` values and locale message keys.
"""

from ..error_codes import ErrorCategory, ErrorCode

DECLARED_ERROR_CODES: tuple[tuple[str, ErrorCode], ...] = (
    (
        "cadrumo.adapters.outbound.aeat.auth.authenticator_types.PersistedSessionInvalidError",
        ErrorCode(
            code="AUTH_AUTH_AUTHENTICATOR_PERSISTED_SESSION_INVALID",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_auth_authenticator_persisted_session_invalid",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.auth.clave_movil_support.ClaveMovilApprovalTimeoutError",
        ErrorCode(
            code="AUTH_AUTH_CLAVE_MOVIL_CLAVE_MOVIL_APPROVAL_TIMEOUT",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_auth_clave_movil_clave_movil_approval_timeout",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.auth.clave_movil_support.ClaveMovilConfigurationError",
        ErrorCode(
            code="AUTH_AUTH_CLAVE_MOVIL_CLAVE_MOVIL_CONFIGURATION",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_auth_clave_movil_clave_movil_configuration",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.auth.certificate.CertificateError",
        ErrorCode(
            code="AUTH_AUTH_CERTIFICATE",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_auth_certificate",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.auth.certificate.CertificateExpiredError",
        ErrorCode(
            code="AUTH_AUTH_CERTIFICATE_EXPIRED",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_auth_certificate_expired",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.auth.certificate.CertificateLoadError",
        ErrorCode(
            code="AUTH_AUTH_CERTIFICATE_LOAD",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_auth_certificate_load",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.auth.certificate.CertificateNifParseError",
        ErrorCode(
            code="AUTH_AUTH_CERTIFICATE_NIF_PARSE",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_auth_certificate_nif_parse",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.auth.certificate.CertificatePasswordError",
        ErrorCode(
            code="AUTH_AUTH_CERTIFICATE_PASSWORD",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_auth_certificate_password",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.auth.certificate.CertificatePreExpiryError",
        ErrorCode(
            code="AUTH_AUTH_CERTIFICATE_PRE_EXPIRY",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_auth_certificate_pre_expiry",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.inbound.borrador.errors.ArtefactNotRecognisedError",
        ErrorCode(
            code="ERROR_BORRADOR_ARTEFACT_NOT_RECOGNISED",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_borrador_artefact_not_recognised",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.inbound.borrador.errors.BorradorParseError",
        ErrorCode(
            code="FAIL_BORRADOR_PARSE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_borrador_parse",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.inbound.notificacion.errors.NotificacionParseError",
        ErrorCode(
            code="FAIL_NOTIFICACION_PARSE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_notificacion_parse",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.inbound.notificacion.errors.SancionParseError",
        ErrorCode(
            code="FAIL_SANCION_PARSE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_sancion_parse",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.inbound.notificacion.errors.SancionArithmeticError",
        ErrorCode(
            code="FAIL_SANCION_ARITHMETIC",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_sancion_arithmetic",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.browser.errors.BrowserError",
        ErrorCode(
            code="FAIL_BROWSER_SESSION_BROWSER",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_browser_session_browser",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.browser.errors.BrowserEvasionError",
        ErrorCode(
            code="FAIL_BROWSER_EVASION",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_browser_evasion",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.inbound.declaracion.errors.DeclaracionParseError",
        ErrorCode(
            code="FAIL_DECLARACION_PARSE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_declaracion_parse",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.inbound.declaracion.errors.TemplateNotDetectedError",
        ErrorCode(
            code="ERROR_DECLARACION_TEMPLATE_NOT_DETECTED",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_declaracion_template_not_detected",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.sede.errors.ExpedienteNotFoundError",
        ErrorCode(
            code="ERROR_SEDE_EXPEDIENTE_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_sede_expediente_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.sede.errors.JustificanteFetchError",
        ErrorCode(
            code="FAIL_SEDE_JUSTIFICANTE_FETCH",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_sede_justificante_fetch",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.sede.errors.SedeError",
        ErrorCode(
            code="ERROR_SEDE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_sede",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.sede.errors.SedeNavigationError",
        ErrorCode(
            code="ERROR_SEDE_NAVIGATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_sede_navigation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.sede.errors.SedeParseError",
        ErrorCode(
            code="FAIL_SEDE_PARSE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_sede_parse",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.BlobIntegrityError",
        ErrorCode(
            code="INTEGRITY_STORAGE_BLOB",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_blob",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.BlobNotFoundError",
        ErrorCode(
            code="FAIL_STORAGE_BLOB_NOT_FOUND",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_storage_blob_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.ClassificationError",
        ErrorCode(
            code="INTEGRITY_STORAGE_CLASSIFICATION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_classification",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.DecryptionError",
        ErrorCode(
            code="INTEGRITY_STORAGE_DECRYPTION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_decryption",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.SecureStorageError",
        ErrorCode(
            code="FAIL_SECURE_STORAGE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_secure_storage",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.SecureObjectUnreadableError",
        ErrorCode(
            code="INTEGRITY_STORAGE_SECURE_OBJECT_UNREADABLE",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_secure_object_unreadable",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.SecureObjectRowIdentityError",
        ErrorCode(
            code="INTEGRITY_STORAGE_SECURE_OBJECT_ROW_IDENTITY",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_secure_object_row_identity",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.EncryptionError",
        ErrorCode(
            code="INTEGRITY_STORAGE_ENCRYPTION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_encryption",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.EnvelopeVersionError",
        ErrorCode(
            code="INTEGRITY_STORAGE_ENVELOPE_VERSION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_envelope_version",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.KeyDerivationError",
        ErrorCode(
            code="INTEGRITY_STORAGE_KEY_DERIVATION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_key_derivation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.KeyringUnavailableError",
        ErrorCode(
            code="AUTH_STORAGE_KEYRING_UNAVAILABLE",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_storage_keyring_unavailable",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.custody.acceleration_receipt.AccelerationReceiptRevocationError",
        ErrorCode(
            code="FAIL_ACCELERATION_RECEIPT_REVOCATION",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_acceleration_receipt_revocation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.MasterKeyUnavailableError",
        ErrorCode(
            code="AUTH_STORAGE_MASTER_KEY_UNAVAILABLE",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_storage_master_key_unavailable",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.MasterKeyMaterialMissingError",
        ErrorCode(
            code="AUTH_STORAGE_MASTER_KEY_MATERIAL_MISSING",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_storage_master_key_material_missing",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.UnsecuredModeRefusedError",
        ErrorCode(
            code="REFUSED_STORAGE_UNSECURED_MODE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_storage_unsecured_mode",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.NonceCollisionError",
        ErrorCode(
            code="INTEGRITY_STORAGE_NONCE_COLLISION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_nonce_collision",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.PathContainmentError",
        ErrorCode(
            code="INTEGRITY_STORAGE_PATH_CONTAINMENT",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_path_containment",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.PersistenceError",
        ErrorCode(
            code="FAIL_STORAGE_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_storage_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.RepositoryError",
        ErrorCode(
            code="FAIL_STORAGE_REPOSITORY",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_storage_repository",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.RepositorySetupError",
        ErrorCode(
            code="FAIL_STORAGE_REPOSITORY_SETUP",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_storage_repository_setup",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.SecureObjectRevisionConflictError",
        ErrorCode(
            code="FAIL_STORAGE_SECURE_OBJECT_REVISION_CONFLICT",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_storage_secure_object_revision_conflict",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.RetentionPolicyError",
        ErrorCode(
            code="INTEGRITY_STORAGE_RETENTION_POLICY",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_retention_policy",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.SecretAlreadyExistsError",
        ErrorCode(
            code="REFUSED_STORAGE_SECRET_ALREADY_EXISTS",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_storage_secret_already_exists",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.SecretNotFoundError",
        ErrorCode(
            code="FAIL_STORAGE_SECRET_NOT_FOUND",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_storage_secret_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.SessionExpiredError",
        ErrorCode(
            code="REFUSED_STORAGE_SESSION_EXPIRED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_storage_session_expired",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.SecretStoreError",
        ErrorCode(
            code="FAIL_STORAGE_SECRET_STORE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_storage_secret_store",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.StorageError",
        ErrorCode(
            code="FAIL_STORAGE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_storage",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.errors.StorageValidationError",
        ErrorCode(
            code="INTEGRITY_STORAGE_VALIDATION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.export.errors.AeatExportFormatError",
        ErrorCode(
            code="FAIL_EXPORT_FORMAT",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_export_format",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.auth.errors.AuthValidationError",
        ErrorCode(
            code="AUTH_AUTH_VALIDATION",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_auth_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.browser.errors.BrowserValidationError",
        ErrorCode(
            code="FAIL_BROWSER_VALIDATION",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_browser_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.sede.errors.SedeValidationError",
        ErrorCode(
            code="FAIL_SEDE_VALIDATION",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_sede_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.sede.errors.BrowserAdapterTypeError",
        ErrorCode(
            code="ERROR_SEDE_BROWSER_ADAPTER_TYPE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_sede_browser_adapter_type",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.errors.hierarchy.AuthError",
        ErrorCode(
            code="AUTH_AUTH",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_auth",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.auth.errors.AuthProviderCleanupError",
        ErrorCode(
            code="AUTH_AUTH_PROVIDER_CLEANUP",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_auth_provider_cleanup",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.outbound.aeat.auth.errors.AuthConfigurationError",
        ErrorCode(
            code="AUTH_AUTH_CONFIGURATION",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_auth_configuration",
            retryable=False,
            runbook_id=None,
        ),
    ),
)
