"""Ordered application :class:`~cadrumo.core.errors.ErrorCode` registry shard.

Rows map application-layer exception qualnames to stable
:class:`~cadrumo.core.errors.ErrorCategory` values and locale message keys.
"""

from .._registry import ErrorCategory, ErrorCode

_DECLARED_ERROR_CODES: tuple[tuple[str, ErrorCode], ...] = (
    (
        "cadrumo.application.state_projection.ProjectionModeloReadinessCaptureError",
        ErrorCode(
            code="REFUSED_MODELO_READINESS_CAPTURE_NOT_CURRENT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_readiness_capture_not_current",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.calculation.ModeloCalculationCaptureError",
        ErrorCode(
            code="REFUSED_MODELO_CALCULATION_CAPTURE_NOT_CURRENT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_calculation_capture_not_current",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.work_review.ModeloWorkReviewCaptureError",
        ErrorCode(
            code="REFUSED_MODELO_WORK_REVIEW_CAPTURE_NOT_CURRENT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_work_review_capture_not_current",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.work_addressing.ModeloWorkCaptureError",
        ErrorCode(
            code="REFUSED_MODELO_WORK_CAPTURE_NOT_CURRENT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_work_capture_not_current",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.work_addressing.ModeloWorkNoActiveBucketError",
        ErrorCode(
            code="REFUSED_MODELO_WORK_SELECTOR_NO_ACTIVE_BUCKET",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_work_selector_no_active_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.work_addressing.ModeloWorkUnitNotFoundError",
        ErrorCode(
            code="ERROR_MODELO_WORK_SELECTOR_UNIT_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.modelo_work_selector_unit_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.work_addressing.ModeloWorkSelectorContradictionError",
        ErrorCode(
            code="REFUSED_MODELO_WORK_SELECTOR_CONTRADICTION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_work_selector_contradiction",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.work_addressing.ModeloWorkVisibleTargetAmbiguousError",
        ErrorCode(
            code="REFUSED_MODELO_WORK_SELECTOR_AMBIGUOUS",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_work_selector_ambiguous",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.work_addressing.ModeloWorkRevisionConflictError",
        ErrorCode(
            code="REFUSED_MODELO_WORK_SELECTOR_REVISION_CONFLICT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_work_selector_revision_conflict",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._selectors.ModeloCalculationRevisionSelectorError",
        ErrorCode(
            code="ERROR_MODELO_CALCULATION_REVISION_SELECTOR",
            category=ErrorCategory.ERROR,
            message_key="errors.error.modelo_calculation_revision_selector",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._selectors.ModeloCalculationRevisionSelectorNotFoundError",
        ErrorCode(
            code="ERROR_MODELO_CALCULATION_REVISION_SELECTOR_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.modelo_calculation_revision_selector_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._selectors.ModeloCalculationRevisionSelectorStateError",
        ErrorCode(
            code="REFUSED_MODELO_CALCULATION_REVISION_SELECTOR_STATE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_calculation_revision_selector_state",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._selectors.ModeloCalculationRevisionSelectorAmbiguousError",
        ErrorCode(
            code="REFUSED_MODELO_CALCULATION_REVISION_SELECTOR_AMBIGUOUS",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_calculation_revision_selector_ambiguous",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.work_addressing.ModeloWorkAddressNotFoundError",
        ErrorCode(
            code="ERROR_MODELO_WORK_ADDRESS_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.modelo_work_address_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.work_addressing.ModeloWorkRegistryYearMismatchError",
        ErrorCode(
            code="REFUSED_MODELO_WORK_REGISTRY_YEAR_MISMATCH",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_work_registry_year_mismatch",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.work_addressing.ModeloWorkPeriodTokenError",
        ErrorCode(
            code="REFUSED_MODELO_WORK_PERIOD_TOKEN",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_work_period_token",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.work_addressing.ModeloRevisionPickError",
        ErrorCode(
            code="REFUSED_MODELO_REVISION_PICK",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_revision_pick",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._calculate_input.ModeloCalculateInputError",
        ErrorCode(
            code="REFUSED_MODELO_CALCULATE_INPUT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_calculate_input",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._calculate_input.ModeloCalculateDetailRowsError",
        ErrorCode(
            code="REFUSED_MODELO_CALCULATE_DETAIL_ROWS",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_calculate_detail_rows",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._calculate_input.ModeloCalculateDecimalInputError",
        ErrorCode(
            code="REFUSED_MODELO_CALCULATE_DECIMAL_INPUT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_calculate_decimal_input",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._calculate_input.ModeloCalculateTextInputError",
        ErrorCode(
            code="REFUSED_MODELO_CALCULATE_TEXT_INPUT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_calculate_text_input",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._calculate_input.ModeloCalculateCasillaInputError",
        ErrorCode(
            code="REFUSED_MODELO_CALCULATE_CASILLA_INPUT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_calculate_casilla_input",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._calculate_input.ModeloCalculateBindingInputError",
        ErrorCode(
            code="REFUSED_MODELO_CALCULATE_BINDING_INPUT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_calculate_binding_input",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._calculate_input.ModeloCalculateRelationInputError",
        ErrorCode(
            code="REFUSED_MODELO_CALCULATE_RELATION_INPUT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_calculate_relation_input",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._calculate_input.ModeloCalculateShortcutInputError",
        ErrorCode(
            code="REFUSED_MODELO_CALCULATE_SHORTCUT_INPUT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_calculate_shortcut_input",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._calculate_input.ModeloCalculateSemanticRoleError",
        ErrorCode(
            code="REFUSED_MODELO_CALCULATE_SEMANTIC_ROLE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_calculate_semantic_role",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._export.ModeloExportCrossBucketRefusedError",
        ErrorCode(
            code="REFUSED_MODELO_EXPORT_CROSS_BUCKET",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_export_cross_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._export.ModeloExportEvidenceMissingError",
        ErrorCode(
            code="REFUSED_MODELO_EXPORT_EVIDENCE_MISSING",
            category=ErrorCategory.REFUSED,
            message_key="errors.fail.modelo_export",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._filing_actions.ModeloFilingEvidenceMissingError",
        ErrorCode(
            code="REFUSED_MODELO_FILING_EVIDENCE_MISSING",
            category=ErrorCategory.REFUSED,
            message_key="errors.error.error_modelos",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._export.ModeloExportNoActiveBucketError",
        ErrorCode(
            code="REFUSED_MODELO_EXPORT_NO_ACTIVE_BUCKET",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_export_no_active_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._export.ModeloExportUnsupportedError",
        ErrorCode(
            code="REFUSED_MODELO_EXPORT_UNSUPPORTED",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.errors.export_unsupported",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._export.ModeloExportOutputPathError",
        ErrorCode(
            code="REFUSED_MODELO_EXPORT_OUTPUT_PATH",
            category=ErrorCategory.REFUSED,
            message_key="errors.fail.modelo_export",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.overview.errors.OverviewError",
        ErrorCode(
            code="FAIL_OVERVIEW",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.overview",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.overview.errors.OverviewCalendarError",
        ErrorCode(
            code="FAIL_OVERVIEW_CALENDAR",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.overview_calendar",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.overview.errors.OverviewAgendaError",
        ErrorCode(
            code="FAIL_OVERVIEW_AGENDA",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.overview_agenda",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.overview.errors.OverviewBacklogError",
        ErrorCode(
            code="FAIL_OVERVIEW_BACKLOG",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.overview_backlog",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.overview.errors.OverviewExplainError",
        ErrorCode(
            code="FAIL_OVERVIEW_EXPLAIN",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.overview_explain",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.censo_errors.CensoSyncError",
        ErrorCode(
            code="FAIL_CENSO_SYNC",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.censo_sync",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.censo_sync.CensalIdentityMismatchError",
        ErrorCode(
            code="REFUSED_CENSAL_READ_IDENTITY",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.censal_read_identity",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.profile_pointer.ActiveProfilePointerTransactionError",
        ErrorCode(
            code="INTERNAL_ACTIVE_PROFILE_POINTER_TRANSACTION",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.internal_active_profile_pointer_transaction",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.custody_transactions.ProfileCustodyTransactionError",
        ErrorCode(
            code="FAIL_PROFILE_CUSTODY_TRANSACTION",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_storage_profile_custody",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.custody_transactions.ProfileCustodyTransactionConflictError",
        ErrorCode(
            code="REFUSED_PROFILE_CUSTODY_TRANSACTION_CONFLICT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_storage_profile_custody",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.custody_transactions.ProfileCustodyDuplicateLabelError",
        ErrorCode(
            code="REFUSED_PROFILE_CUSTODY_DUPLICATE_LABEL",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_storage_profile_custody",
            # NOT retryable, unlike the conflict class it extends: that one
            # reports a stale witness a re-read fixes, while a label already
            # bound to a committed capsule can never be taken by the identical
            # command. Publishing it as retryable invites a machine caller
            # into a loop that cannot terminate.
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.custody_service.ProfileCustodyDisplacedSessionRetirementError",
        ErrorCode(
            code="REFUSED_PROFILE_CUSTODY_DISPLACED_SESSION_RETIREMENT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_profile_displaced_session_retirement",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.custody_transactions.ProfileCustodyTransactionRefusalError",
        ErrorCode(
            code="REFUSED_PROFILE_CUSTODY_TRANSACTION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_storage_profile_custody",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.custody_transactions.ProfileCustodyTransactionCorruptError",
        ErrorCode(
            code="INTEGRITY_PROFILE_CUSTODY_TRANSACTION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_profile_custody_record",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.authentication.ProfileAuthenticationRefusedError",
        ErrorCode(
            code="REFUSED_PROFILE_AUTHENTICATION",
            category=ErrorCategory.REFUSED,
            message_key="application.user_profile.errors.profile_authentication_refused",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.registration.ProfileRegistrationConflictError",
        ErrorCode(
            code="REFUSED_PROFILE_REGISTRATION_CONFLICT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_storage_profile_custody",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.registration.ProfileRegistrationError",
        ErrorCode(
            code="REFUSED_PROFILE_REGISTRATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.profile_registration",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.capsule_archive.ProfileCapsuleArchiveError",
        ErrorCode(
            code="REFUSED_PROFILE_CAPSULE_ARCHIVE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.profile_capsule_archive",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.capsule_restore.ProfileCapsuleSourceError",
        ErrorCode(
            code="REFUSED_PROFILE_CAPSULE_SOURCE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.profile_capsule_source",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.passphrase_rotation.ProfilePassphraseRotationError",
        ErrorCode(
            code="REFUSED_PROFILE_PASSPHRASE_ROTATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.profile_passphrase_rotation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.login_session.ProfileLoginThrottledError",
        ErrorCode(
            code="REFUSED_PROFILE_LOGIN_THROTTLED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_profile_login_throttled",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.modelos.errors.PensionReduccionError",
        ErrorCode(
            code="REFUSED_PENSION_REDUCCION_COMPUTATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_pension_reduccion_computation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.calculations.errors.IvaCompensationModeloError",
        ErrorCode(
            code="REFUSED_IVA_COMPENSATION_MODELO",
            category=ErrorCategory.REFUSED,
            message_key="application.calculations.iva_compensation.errors.modelo_303_only",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.calculations.errors.BindingPrefillTypeError",
        ErrorCode(
            code="REFUSED_BINDING_PREFILL_TYPE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_calculations_casilla_constraint",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.calculations.errors.ObservationKeyError",
        ErrorCode(
            code="ERROR_OBSERVATION_KEY",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_observation_key",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.calculations.errors.ObservationEvidenceDisplacementError",
        ErrorCode(
            code="REFUSED_OBSERVATION_EVIDENCE_DISPLACEMENT",
            category=ErrorCategory.REFUSED,
            message_key="application.calculations.errors.observation_displaces_official_evidence_manual",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.calculations.errors.ObservationCasillaReferenceError",
        ErrorCode(
            code="REFUSED_OBSERVATION_CASILLA_REFERENCE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_calculations_casilla_constraint",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.calculations._m303_carry_ingress.M303CarryIngressError",
        ErrorCode(
            code="REFUSED_M303_CARRY_INGRESS",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_calculations_casilla_constraint",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.calculations._m303_regimen_simplificado.M303RegimenSimplificadoCalculationError",
        ErrorCode(
            code="ERROR_M303_REGIMEN_SIMPLIFICADO_CALCULATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_iva",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.calculations._m303_regimen_simplificado_annual_summary."
        "M303RegimenSimplificadoAnnualSummaryHandoffError",
        ErrorCode(
            code="FAIL_M303_REGIMEN_SIMPLIFICADO_ANNUAL_SUMMARY_HANDOFF",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.reconciliation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.custody_ports.ProfileRecordCryptoError",
        ErrorCode(
            code="INTEGRITY_PROFILE_RECORD_CRYPTO",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_encryption",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.custody_ports.ProfileCustodyRecordIntegrityError",
        ErrorCode(
            code="INTEGRITY_PROFILE_CUSTODY_PORT_RECORD",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_profile_custody_record",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.custody_ports.ProfileCustodyConcurrentChangeError",
        ErrorCode(
            code="LOCKED_PROFILE_CUSTODY_PORT_CAPSULE_GENERATION",
            category=ErrorCategory.LOCKED,
            message_key="errors.locked.locked_storage_profile_custody_capsule_generation",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.capsule_record.ProfileRecordConflictError",
        ErrorCode(
            code="FAIL_PROFILE_RECORD_CONFLICT",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_storage_secure_object_revision_conflict",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.capsule_record.ProfileRecordIntegrityError",
        ErrorCode(
            code="INTEGRITY_PROFILE_RECORD",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_profile_custody_record",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.iva_compensation.errors.IvaWalletReconciliationError",
        ErrorCode(
            code="REFUSED_IVA_WALLET_RECONCILIATION_INVARIANT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_iva_wallet_reconciliation_invariant",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.iva_compensation.errors.IvaCompensationYearRangeError",
        ErrorCode(
            code="REFUSED_IVA_COMPENSATION_YEAR_RANGE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_iva_compensation_year_range",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.iva_compensation.errors.IvaCompensationDecimalParseError",
        ErrorCode(
            code="REFUSED_IVA_COMPENSATION_DECIMAL_PARSE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_iva_compensation_decimal_parse",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.iva_compensation.errors.IvaCompensationCasillaReferenceError",
        ErrorCode(
            code="REFUSED_IVA_COMPENSATION_CASILLA_REFERENCE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_calculations_casilla_constraint",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.iva_compensation.errors.IvaCompensationCarryForwardPolicyError",
        ErrorCode(
            code="REFUSED_IVA_COMPENSATION_CARRY_FORWARD_POLICY",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_filing_calculate",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.iva_compensation.errors.IvaCompensationSeedConflictError",
        ErrorCode(
            code="REFUSED_IVA_COMPENSATION_SEED_CONFLICT",
            category=ErrorCategory.REFUSED,
            message_key="application.calculations.iva_compensation.errors.seed_conflict",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.iva_compensation.errors.IvaCompensationReconciliationInputError",
        ErrorCode(
            code="REFUSED_IVA_COMPENSATION_RECONCILIATION_INPUT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.reconciliation_evidence_invalid",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.storage.calc_sheets._translator.TranslationError",
        ErrorCode(
            code="ERROR_CALC_SHEETS_TRANSLATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_calculations_registry",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.calculations._multi_year.EnrollmentEvidenceError",
        ErrorCode(
            code="ERROR_CALCULATIONS_ENROLLMENT_EVIDENCE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_calculations_registry",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.bundle.UnsupportedBundleSchemaVersionError",
        ErrorCode(
            code="REFUSED_USER_PROFILE_BUNDLE_SCHEMA_VERSION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_application_registry_input",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.workflow.errors.WorkflowInputMismatchError",
        ErrorCode(
            code="REFUSED_WORKFLOW_INPUT_MISMATCH",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_workflow_input_mismatch",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._m145_communication_records.M145CommunicationServiceError",
        ErrorCode(
            code="ERROR_M145_COMMUNICATION_SERVICE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.m145_communication_service",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._m145_communication_records.M145CommunicationRecordNotFoundError",
        ErrorCode(
            code="ERROR_M145_COMMUNICATION_RECORD_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.m145_communication_record_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._m145_communication_records.M145CommunicationRecordAmbiguousError",
        ErrorCode(
            code="REFUSED_M145_COMMUNICATION_RECORD_AMBIGUOUS",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.m145_communication_record_ambiguous",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._m145_communication_records.M145CommunicationRecordValidationError",
        ErrorCode(
            code="REFUSED_M145_COMMUNICATION_RECORD_VALIDATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.m145_communication_record_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._m145_communication_records.M145CommunicationRecordExportError",
        ErrorCode(
            code="REFUSED_M145_COMMUNICATION_RECORD_EXPORT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.m145_communication_record_export",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._m145_communication_records.M145CommunicationRecordTransitionError",
        ErrorCode(
            code="REFUSED_M145_COMMUNICATION_RECORD_TRANSITION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.m145_communication_record_transition",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._action_errors.StoredCalculationDriftError",
        ErrorCode(
            code="INTEGRITY_STORED_CALCULATION_DRIFT",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.storage.stored_data_validation_boundary",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._action_errors.ModeloApplicabilityFilterError",
        ErrorCode(
            code="REFUSED_MODELO_APPLICABILITY_FILTER",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_modelo_applicability_filter",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._action_errors.M303FilingEvidenceError",
        ErrorCode(
            code="REFUSED_MODELO_M303_FILING_EVIDENCE",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.errors.m303_filing_evidence_invalid",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._action_errors.ModeloProfileReadinessError",
        ErrorCode(
            code="REFUSED_MODELO_PROFILE_READINESS",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.errors.profile_readiness_missing",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._action_errors.ModeloRequiredBindingsMissingError",
        ErrorCode(
            code="REFUSED_MODELO_REQUIRED_BINDINGS_MISSING",
            category=ErrorCategory.REFUSED,
            message_key="errors.error.error_modelo_aggregation_binding",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.errors.DiagnosticModelError",
        ErrorCode(
            code="REFUSED_DIAGNOSTIC_MODEL_INVARIANT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_diagnostic_model_invariant",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.export.errors.ExportFormatError",
        ErrorCode(
            code="REFUSED_EXPORT_FORMAT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_export_format",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.export.errors.ExportFieldError",
        ErrorCode(
            code="REFUSED_EXPORT_FIELD",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_export_field",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.storage.calc_sheets.errors.CalcSheetsEngineError",
        ErrorCode(
            code="ERROR_CALC_SHEETS_ENGINE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_calc_sheets_engine",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.storage.calc_sheets.errors.CalcSheetsRecordError",
        ErrorCode(
            code="ERROR_CALC_SHEETS_RECORD",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_calc_sheets_record",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.storage.calc_sheets.errors.CalcSheetsParityError",
        ErrorCode(
            code="ERROR_CALC_SHEETS_PARITY",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_calc_sheets_parity",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._review_package.ReviewPackageError",
        ErrorCode(
            code="ERROR_MODELO_REVIEW_PACKAGE",
            category=ErrorCategory.ERROR,
            message_key="application.modelo.errors.review_package_generic",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._review_package.ReviewPackageRevisionStateError",
        ErrorCode(
            code="REFUSED_MODELO_REVIEW_PACKAGE_REVISION_STATE",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.errors.review_package_revision_state",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._review_package.ReviewPackageIntegrityError",
        ErrorCode(
            code="REFUSED_MODELO_REVIEW_PACKAGE_INTEGRITY",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.errors.review_package_integrity",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._review_package_signing.ReviewPackageSigningError",
        ErrorCode(
            code="ERROR_MODELO_REVIEW_PACKAGE_SIGNING",
            category=ErrorCategory.ERROR,
            message_key="application.modelo.errors.review_package_generic",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._review_package_signing.ReviewPackageSigningKeyNotFoundError",
        ErrorCode(
            code="REFUSED_MODELO_REVIEW_PACKAGE_SIGNING_KEY_NOT_FOUND",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.errors.review_package_generic",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._review_package_counter_sign.ReviewPackageCounterSigningError",
        ErrorCode(
            code="ERROR_MODELO_REVIEW_PACKAGE_COUNTER_SIGNING",
            category=ErrorCategory.ERROR,
            message_key="application.modelo.errors.review_package_generic",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._review_package_recipient_registry.RecipientFingerprintRegistryError",
        ErrorCode(
            code="ERROR_MODELO_RECIPIENT_FINGERPRINT_REGISTRY",
            category=ErrorCategory.ERROR,
            message_key="application.modelo.errors.recipient_registry_generic",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._review_package_recipient_registry.RecipientAlreadyRegisteredError",
        ErrorCode(
            code="REFUSED_MODELO_RECIPIENT_ALREADY_REGISTERED",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.errors.recipient_registry_already_exists",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._review_package_recipient_registry.RecipientNotRegisteredError",
        ErrorCode(
            code="REFUSED_MODELO_RECIPIENT_NOT_REGISTERED",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.errors.recipient_registry_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._review_package_recipient_encryption.RecipientEncryptionError",
        ErrorCode(
            code="ERROR_MODELO_RECIPIENT_ENCRYPTION",
            category=ErrorCategory.ERROR,
            message_key="application.modelo.errors.recipient_encryption_invalid_key",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._review_package_recipient_encryption.RecipientDecryptionError",
        ErrorCode(
            code="REFUSED_MODELO_RECIPIENT_DECRYPTION",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.errors.recipient_decryption_failed",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._review_package_recipient_encryption.RecipientPackageExpiredError",
        ErrorCode(
            code="REFUSED_MODELO_RECIPIENT_PACKAGE_EXPIRED",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.errors.recipient_decryption_failed",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._review_package_recipient_encryption.RecipientEncryptionKeyNotFoundError",
        ErrorCode(
            code="REFUSED_MODELO_RECIPIENT_ENCRYPTION_KEY_NOT_FOUND",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.errors.recipient_encryption_key_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.profile.recipient_replay_guard.RecipientReplayGuardError",
        ErrorCode(
            code="ERROR_MODELO_RECIPIENT_REPLAY_GUARD",
            category=ErrorCategory.ERROR,
            message_key="application.modelo.errors.recipient_registry_load_failed",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.profile.recipient_replay_guard.RecipientPackageReplayedError",
        ErrorCode(
            code="REFUSED_MODELO_RECIPIENT_PACKAGE_REPLAYED",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.errors.recipient_decryption_failed",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._review_package_review_only_workspace.ReviewOnlyWorkspaceError",
        ErrorCode(
            code="ERROR_MODELO_REVIEW_ONLY_WORKSPACE",
            category=ErrorCategory.ERROR,
            message_key="application.modelo.errors.review_only_workspace_no_authority",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._review_package_review_only_workspace.ReviewOnlyWorkspaceAuthorityError",
        ErrorCode(
            code="REFUSED_MODELO_REVIEW_ONLY_WORKSPACE_AUTHORITY",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.errors.review_only_workspace_no_authority",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._review_package_feedback.ReviewPackageFeedbackError",
        ErrorCode(
            code="ERROR_MODELO_REVIEW_PACKAGE_FEEDBACK",
            category=ErrorCategory.ERROR,
            message_key="application.modelo.errors.review_package_generic",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._review_package_feedback.FeedbackCounterSignatureInvalidError",
        ErrorCode(
            code="REFUSED_MODELO_REVIEW_PACKAGE_FEEDBACK_COUNTERSIGN_INVALID",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.errors.review_package_generic",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.bundle_export_operation.ProfileBundleExportJournalError",
        ErrorCode(
            code="ERROR_PROFILE_EXPORT_JOURNAL",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_config_boundary",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.bundle_export_operation.ProfileBundleExportJournalNotFoundError",
        ErrorCode(
            code="ERROR_PROFILE_EXPORT_JOURNAL_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_cadrumo_core_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.user_profile.bundle_export_operation.ProfileBundleExportJournalCorruptError",
        ErrorCode(
            code="ERROR_PROFILE_EXPORT_JOURNAL_CORRUPT",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_config_boundary",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.storage_management.errors.StorageManagementError",
        ErrorCode(
            code="ERROR_STORAGE_MANAGEMENT",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_storage_management",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.storage_management.errors.StorageReclaimRefusedError",
        ErrorCode(
            code="REFUSED_STORAGE_RECLAIM",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_storage_reclaim",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.storage_management.errors.StorageReclaimUnconfirmedError",
        ErrorCode(
            code="REFUSED_STORAGE_RECLAIM_UNCONFIRMED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_storage_reclaim_unconfirmed",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.operations.errors.OperationDeclarationError",
        ErrorCode(
            code="INTERNAL_OPERATION_DECLARATION_BREACH",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.internal_operation_declaration_breach",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.workspace_manifest.ModeloWorkspaceManifestCaptureError",
        ErrorCode(
            code="REFUSED_MODELO_WORKSPACE_MANIFEST_CAPTURE_NOT_CURRENT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_workspace_manifest_capture_not_current",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.registry.closure_capture.RegistryClosureCaptureError",
        ErrorCode(
            code="REFUSED_REGISTRY_CLOSURE_CAPTURE_NOT_CURRENT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.registry_closure_capture_not_current",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.operation_definitions.ModeloWorkDiscardApprovalStaleError",
        ErrorCode(
            code="REFUSED_MODELO_WORK_DISCARD_APPROVAL_STALE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_work_discard_approval_stale",
            retryable=False,
            runbook_id=None,
        ),
    ),
)
