"""Ordered application :class:`~cadrumo.core.errors.ErrorCode` registry shard.

Rows map application-layer exception qualnames to stable
:class:`~cadrumo.core.errors.ErrorCategory` values and locale message keys.
"""

from .._registry import ErrorCategory, ErrorCode

_DECLARED_ERROR_CODES: tuple[tuple[str, ErrorCode], ...] = (
    (
        "cadrumo.application.operator_surface.errors.OperatorSurfaceContractError",
        ErrorCode(
            code="REFUSED_OPERATOR_SURFACE_CONTRACT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_operator_surface_contract",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.registry.errors.RegistryApplicationError",
        ErrorCode(
            code="ERROR_APPLICATION_REGISTRY",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_application_registry",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.registry.errors.RegistryApplicationInputError",
        ErrorCode(
            code="REFUSED_APPLICATION_REGISTRY_INPUT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_application_registry_input",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.corpus_search.errors.CorpusSearchError",
        ErrorCode(
            code="ERROR_CORPUS_SEARCH",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_corpus_search",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.corpus_search.errors.CorpusSearchInputError",
        ErrorCode(
            code="REFUSED_CORPUS_SEARCH_INPUT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_corpus_search_input",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.live.errors.LiveApplicationError",
        ErrorCode(
            code="ERROR_APPLICATION_LIVE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_application_live",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.live.errors.LiveApplicationInputError",
        ErrorCode(
            code="REFUSED_APPLICATION_LIVE_INPUT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_application_live_input",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.live.errors.LiveIvaSurfaceTimeoutError",
        ErrorCode(
            code="ERROR_APPLICATION_LIVE_IVA_SURFACE_TIMEOUT",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_application_live_iva_surface_timeout",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.operator_results.AuthProviderReservedError",
        ErrorCode(
            code="REFUSED_AUTH_PROVIDER_RESERVED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_auth_provider_reserved",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.operator_results.AuthConfigureNoActiveBucketError",
        ErrorCode(
            code="REFUSED_AUTH_CONFIGURE_NO_ACTIVE_BUCKET",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.auth_configure_no_active_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.operator_results.AuthConfigureDanglingActiveProfileError",
        ErrorCode(
            code="REFUSED_AUTH_CONFIGURE_DANGLING_ACTIVE_PROFILE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_auth_configure_dangling_active_profile",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.operator_results.AuthLoginNotEnabledError",
        ErrorCode(
            code="REFUSED_AUTH_LOGIN_LIVE_TESTS_DISABLED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_auth_login_live_tests_disabled",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.operator_results.AuthLoginPreconditionError",
        ErrorCode(
            code="REFUSED_AUTH_LOGIN_PRECONDITION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_auth_login_precondition",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.operator_results.AuthCleanupInProgressError",
        ErrorCode(
            code="LOCKED_AUTH_CLEANUP_IN_PROGRESS",
            category=ErrorCategory.LOCKED,
            message_key="application.auth.operator.errors.cleanup_in_progress",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.operator_results.CertificateSecretMutationInProgressError",
        ErrorCode(
            code="LOCKED_CERTIFICATE_SECRET_MUTATION_IN_PROGRESS",
            category=ErrorCategory.LOCKED,
            message_key="application.auth.operator.errors.certificate_secret_mutation_in_progress",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.operator_results.AuthOperationScopeConflictError",
        ErrorCode(
            code="REFUSED_AUTH_OPERATION_SCOPE_CONFLICT",
            category=ErrorCategory.REFUSED,
            message_key="application.auth.operator.errors.scope_conflict",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.operator_results.AuthOperationRequiresCustodySessionError",
        ErrorCode(
            code="REFUSED_AUTH_OPERATION_REQUIRES_CUSTODY_SESSION",
            category=ErrorCategory.REFUSED,
            message_key="application.auth.operator.errors.requires_custody_session",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.operator_results.AuthProviderNotConfiguredError",
        ErrorCode(
            code="REFUSED_AUTH_PROVIDER_NOT_CONFIGURED",
            category=ErrorCategory.REFUSED,
            message_key="application.auth.operator.errors.provider_not_configured",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.operator_results.CertificateSourceNotFoundError",
        ErrorCode(
            code="REFUSED_AUTH_CERTIFICATE_SOURCE_NOT_FOUND",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_auth_certificate_source_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.acquisition_lock.AuthAcquisitionLockedError",
        ErrorCode(
            code="LOCKED_AUTH_ACQUISITION",
            category=ErrorCategory.LOCKED,
            message_key="errors.locked.locked_auth_acquisition",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.errors.AuthDiagnosticPayloadError",
        ErrorCode(
            code="REFUSED_AUTH_DIAGNOSTIC_PAYLOAD",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_auth_diagnostic_payload",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.errors.AuthDiagnosticPhoneStateError",
        ErrorCode(
            code="REFUSED_AUTH_DIAGNOSTIC_PHONE_STATE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_auth_diagnostic_phone_state",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.config_reset.ConfigResetError",
        ErrorCode(
            code="ERROR_CONFIG_RESET",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_config_boundary",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.config_reset.ConfigResetConfirmationRequiredError",
        ErrorCode(
            code="REFUSED_CONFIG_RESET_CONFIRMATION_REQUIRED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_config_reset_unconfirmed",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.config_reset.ConfigResetAlreadyRunningError",
        ErrorCode(
            code="LOCKED_CONFIG_RESET_ALREADY_RUNNING",
            category=ErrorCategory.LOCKED,
            message_key="errors.locked.locked_storage_lock_acquisition",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.config_reset.ConfigResetOperationNotFoundError",
        ErrorCode(
            code="ERROR_CONFIG_RESET_OPERATION_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_cadrumo_core_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application._config_reset_repository.ConfigResetJournalError",
        ErrorCode(
            code="ERROR_CONFIG_RESET_JOURNAL",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_config_boundary",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application._config_reset_repository.ConfigResetJournalAlreadyExistsError",
        ErrorCode(
            code="ERROR_CONFIG_RESET_JOURNAL_ALREADY_EXISTS",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_config_boundary",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application._config_reset_repository.ConfigResetJournalNotFoundError",
        ErrorCode(
            code="ERROR_CONFIG_RESET_JOURNAL_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_cadrumo_core_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application._config_reset_repository.ConfigResetJournalCorruptError",
        ErrorCode(
            code="ERROR_CONFIG_RESET_JOURNAL_CORRUPT",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_config_boundary",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application._config_reset_repository.ConfigResetJournalOwnershipError",
        ErrorCode(
            code="ERROR_CONFIG_RESET_JOURNAL_OWNERSHIP",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_config_boundary",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application._config_reset_repository.ConfigResetJournalIncompleteError",
        ErrorCode(
            code="ERROR_CONFIG_RESET_JOURNAL_INCOMPLETE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_config_boundary",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.topics.TopicNotFoundError",
        ErrorCode(
            code="REFUSED_TOPIC_NOT_FOUND",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_topic_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.topics.TopicCatalogueEmptyError",
        ErrorCode(
            code="REFUSED_TOPIC_CATALOGUE_EMPTY",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_topic_catalogue_empty",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.aggregation._source_mesh.SourceMeshError",
        ErrorCode(
            code="REFUSED_SOURCE_MESH_INVARIANT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_source_mesh_invariant",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.aggregation.errors.AggregationConfigError",
        ErrorCode(
            code="ERROR_AGGREGATION_CONFIG",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_aggregation_config",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.aggregation.errors.AggregationError",
        ErrorCode(
            code="ERROR_FINANCIAL_AGGREGATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_aggregation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.aggregation.errors.AggregationPeriodError",
        ErrorCode(
            code="ERROR_FINANCIAL_AGGREGATION_PERIOD",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_aggregation_period",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.aggregation.errors.AggregationUnsupportedModeloError",
        ErrorCode(
            code="REFUSED_FINANCIAL_AGGREGATION_UNSUPPORTED_MODELO",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_financial_aggregation_unsupported_modelo",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.aggregation.errors.AggregationMissingClassificationError",
        ErrorCode(
            code="REFUSED_FINANCIAL_AGGREGATION_MISSING_CLASSIFICATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_financial_aggregation_missing_classification",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.aggregation.errors.AggregationCategoryCoverageError",
        ErrorCode(
            code="REFUSED_FINANCIAL_AGGREGATION_CATEGORY_COVERAGE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_financial_aggregation_category_coverage",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.review.errors.ReviewError",
        ErrorCode(
            code="ERROR_REVIEW",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_review",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.review.errors.ReviewKindReservedError",
        ErrorCode(
            code="REFUSED_REVIEW_KIND_RESERVED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_review_kind_reserved",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.review.errors.ReviewSourceLoadError",
        ErrorCode(
            code="FAIL_REVIEW_SOURCE_LOAD",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_review_source_load",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.review.errors.FilterParseError",
        ErrorCode(
            code="REFUSED_REVIEW_FILTER_PARSE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_review_filter_parse",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.review.errors.EditParseError",
        ErrorCode(
            code="REFUSED_REVIEW_EDIT_PARSE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_review_edit_parse",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.workflow.errors.BootstrapAlreadyCompleteError",
        ErrorCode(
            code="REFUSED_BOOTSTRAP_ALREADY_COMPLETE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.bootstrap_already_complete",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.workflow.errors.ProfileNameCollisionError",
        ErrorCode(
            code="REFUSED_PROFILE_NAME_COLLISION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.profile_name_collision",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.workflow.errors.ProfileLockedError",
        ErrorCode(
            code="REFUSED_PROFILE_LOCKED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.profile_locked",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.workflow.errors.WorkflowAbortedError",
        ErrorCode(
            code="REFUSED_WORKFLOW_ABORTED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_workflow_aborted",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.workflow.errors.WorkflowComponentError",
        ErrorCode(
            code="ERROR_WORKFLOW_COMPONENT",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_workflow_component",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.workflow.errors.WorkflowError",
        ErrorCode(
            code="ERROR_WORKFLOW",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_workflow",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.workflow.resume.WorkflowResumeRefusedError",
        ErrorCode(
            code="REFUSED_WORKFLOW_RESUME",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_workflow_resume",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.workflow.resume.WorkflowResumeRunAmbiguousError",
        ErrorCode(
            code="REFUSED_WORKFLOW_RESUME_RUN_AMBIGUOUS",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_workflow_resume",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.live.snapshot_base.SnapshotNotFoundError",
        ErrorCode(
            code="FAIL_SNAPSHOT_NOT_FOUND",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_snapshot_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.repair_integrity.RepairIntegrityError",
        ErrorCode(
            code="INTEGRITY_REPAIR_INTEGRITY",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_repair_integrity",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.repair_integrity.RepairDecisionNotFoundError",
        ErrorCode(
            code="FAIL_REPAIR_DECISION_NOT_FOUND",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_repair_decision_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.workflow.errors.ProfileLabelAmbiguousError",
        ErrorCode(
            code="REFUSED_PROFILE_LABEL_AMBIGUOUS",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_profile_label_ambiguous",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.workflow.errors.WorkflowAbortSignalError",
        ErrorCode(
            code="INTERNAL_WORKFLOW_ABORT_SIGNAL",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.internal_workflow_abort_signal",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.workflow.errors.UnhandledWorkflowError",
        ErrorCode(
            code="INTERNAL_WORKFLOW_UNHANDLED",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.internal_workflow_unhandled",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.sessions.CorruptAuthSessionError",
        ErrorCode(
            code="AUTH_SESSION_CORRUPT",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_session_corrupt",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.sessions.AuthSessionUnavailableError",
        ErrorCode(
            code="AUTH_SESSION_UNAVAILABLE",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_session_unavailable",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.sessions.AuthProfileIdentityMismatchError",
        ErrorCode(
            code="REFUSED_AUTH_PROFILE_IDENTITY_MISMATCH",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.auth_profile_identity_mismatch",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.sessions.ClaveCredentialsIncompleteError",
        ErrorCode(
            code="REFUSED_CLAVE_CREDENTIALS_INCOMPLETE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.clave_credentials_incomplete",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.sessions.SessionDeserializationError",
        ErrorCode(
            code="AUTH_SESSION_DESERIALIZATION",
            category=ErrorCategory.AUTH,
            message_key="errors.auth.auth_session_deserialization",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.aggregation.errors.AggregationValidationError",
        ErrorCode(
            code="ERROR_FINANCIAL_AGGREGATION_VALIDATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_aggregation_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.filing.errors.ModeloApplicationError",
        ErrorCode(
            code="ERROR_FILING_APPLICATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_filing_application",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.filing.errors.ModeloCalculateError",
        ErrorCode(
            code="REFUSED_FILING_CALCULATE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_filing_calculate",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.wizard.errors.WizardError",
        ErrorCode(
            code="ERROR_WIZARD",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_wizard",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.wizard.errors.WizardValidationError",
        ErrorCode(
            code="REFUSED_WIZARD_VALIDATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_wizard_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.wizard.errors.WizardMissingFlagError",
        ErrorCode(
            code="REFUSED_WIZARD_MISSING_FLAG",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_wizard_missing_flag",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.wizard.errors.WizardCompileError",
        ErrorCode(
            code="ERROR_WIZARD_COMPILE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_wizard_compile",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.wizard.errors.WizardAnswerTypeError",
        ErrorCode(
            code="REFUSED_WIZARD_ANSWER_TYPE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_wizard_answer_type",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.wizard.errors.WizardUnsupportedConsoleError",
        ErrorCode(
            code="REFUSED_WIZARD_UNSUPPORTED_CONSOLE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_wizard_unsupported_console",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.wizard.errors.WizardEditUnsupportedConsoleError",
        ErrorCode(
            code="REFUSED_WIZARD_EDIT_UNSUPPORTED_CONSOLE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_wizard_unsupported_console",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.wizard.status.WizardStatusError",
        ErrorCode(
            code="REFUSED_WIZARD_STATUS",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_wizard_status",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._taxation_comparison.TaxationComparisonError",
        ErrorCode(
            code="REFUSED_TAXATION_COMPARISON",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_taxation_comparison",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._borrador_binding.Modelo100BorradorBindingError",
        ErrorCode(
            code="REFUSED_MODELO_100_BORRADOR_BINDING",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_modelo_100_borrador_binding",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._profile_binding.ProfileBindingResolutionError",
        ErrorCode(
            code="REFUSED_PROFILE_BINDING_RESOLUTION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_profile_binding_resolution",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._projection.ModeloProjectionError",
        ErrorCode(
            code="ERROR_MODELO_PROJECTION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.modelo_projection",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._projection.ModeloProjectNoM130UnitsError",
        ErrorCode(
            code="ERROR_MODELO_PROJECT_NO_M130_UNITS",
            category=ErrorCategory.ERROR,
            message_key="errors.error.modelo_project_no_m130_units",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._projection.ModeloProjectNoM130RevisionsError",
        ErrorCode(
            code="ERROR_MODELO_PROJECT_NO_M130_REVISIONS",
            category=ErrorCategory.ERROR,
            message_key="errors.error.modelo_project_no_m130_revisions",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._projection.ModeloProjectInvalidDecimalOverrideError",
        ErrorCode(
            code="REFUSED_MODELO_PROJECT_INVALID_DECIMAL_OVERRIDE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_project_invalid_decimal_override",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._projection.ModeloCompareNeedTwoYearsError",
        ErrorCode(
            code="REFUSED_MODELO_COMPARE_NEED_TWO_YEARS",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_compare_need_two_years",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._projection.ModeloCompareNoWorkUnitsError",
        ErrorCode(
            code="ERROR_MODELO_COMPARE_NO_WORK_UNITS",
            category=ErrorCategory.ERROR,
            message_key="errors.error.modelo_compare_no_work_units",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._projection.ModeloCompareNoRevisionsError",
        ErrorCode(
            code="ERROR_MODELO_COMPARE_NO_REVISIONS",
            category=ErrorCategory.ERROR,
            message_key="errors.error.modelo_compare_no_revisions",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._projection.ModeloCompareNoUsableRevisionsError",
        ErrorCode(
            code="ERROR_MODELO_COMPARE_NO_USABLE_REVISIONS",
            category=ErrorCategory.ERROR,
            message_key="errors.error.modelo_compare_no_usable_revisions",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._semantic_role_resolution.AmbiguousSemanticRoleCasillaError",
        ErrorCode(
            code="REFUSED_MODELO_AMBIGUOUS_SEMANTIC_ROLE_CASILLA",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_ambiguous_semantic_role_casilla",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._reconcile.ReconciliationEvidenceInvalidError",
        ErrorCode(
            code="REFUSED_RECONCILIATION_EVIDENCE_INVALID",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.reconciliation_evidence_invalid",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._reconcile.ReconciliationDeclaracionSourceUnsupportedError",
        ErrorCode(
            code="REFUSED_RECONCILIATION_DECLARATION_SOURCE_UNSUPPORTED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.reconciliation_declaration_source_unsupported",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._reconcile.ReconciliationCrossBucketRefusedError",
        ErrorCode(
            code="REFUSED_RECONCILIATION_CROSS_BUCKET",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.reconciliation_cross_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo._selectors.ModeloWorkSelectorError",
        ErrorCode(
            code="ERROR_MODELO_WORK_SELECTOR",
            category=ErrorCategory.ERROR,
            message_key="errors.error.modelo_work_selector",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.flows.errors.FlowError",
        ErrorCode(
            code="ERROR_FLOW",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_flow",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.flows.errors.FlowValidatorRegistryError",
        ErrorCode(
            code="INTERNAL_FLOW_VALIDATOR_REGISTRY",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.internal_flow_validator_registry",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.flows.errors.FlowNavigationError",
        ErrorCode(
            code="REFUSED_FLOW_NAVIGATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_flow_navigation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.flows.errors.FlowAnswerError",
        ErrorCode(
            code="REFUSED_FLOW_ANSWER",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_flow_answer",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.flows.errors.FlowSubmitError",
        ErrorCode(
            code="REFUSED_FLOW_SUBMIT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_flow_submit",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.flows.errors.FlowCheckpointError",
        ErrorCode(
            code="REFUSED_FLOW_CHECKPOINT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_flow_checkpoint",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.flows.errors.FlowCopyResolutionError",
        ErrorCode(
            code="INTERNAL_FLOW_COPY_RESOLUTION",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.internal_flow_copy_resolution",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.flows.errors.FlowUnsupportedConsoleError",
        ErrorCode(
            code="REFUSED_FLOW_UNSUPPORTED_CONSOLE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_flow_unsupported_console",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.flows.errors.FlowRunAbandonedError",
        ErrorCode(
            code="REFUSED_FLOW_RUN_ABANDONED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_flow_run_abandoned",
            retryable=False,
            runbook_id=None,
        ),
    ),
)
