"""Ordered application :class:`~core.errors.ErrorCode` registry shard.

Rows map Modelo, operations, operator-surface, and prorrata application
exception qualnames to stable categories and canonical locale message keys.
"""

from ..error_codes import ErrorCategory, ErrorCode

DECLARED_ERROR_CODES: tuple[tuple[str, ErrorCode], ...] = (
    (
        "cadrumo.application.modelo.declarations_calendar.DeclarationsCalendarProjectionError",
        ErrorCode(
            code="INTEGRITY_DECLARATIONS_CALENDAR_PROJECTION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.canonical_declarations_calendar_projection",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.declarations_workspace.DeclarationsWorkspaceProjectionError",
        ErrorCode(
            code="INTEGRITY_DECLARATIONS_WORKSPACE_PROJECTION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.canonical_declarations_workspace_projection",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.edit_receipt_ports.ModeloEditReceiptPersistenceError",
        ErrorCode(
            code="FAIL_MODELO_EDIT_RECEIPT_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.canonical_modelo_edit_receipt_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.m036_lifecycle.M036DeclarationNotFoundError",
        ErrorCode(
            code="REFUSED_M036_DECLARATION_NOT_FOUND",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_m036_declaration_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.m036_lifecycle.M036DeclarationAmbiguousError",
        ErrorCode(
            code="REFUSED_M036_DECLARATION_AMBIGUOUS",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_m036_declaration_ambiguous",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.m036_lifecycle_ports.M036DeclarationPersistenceError",
        ErrorCode(
            code="FAIL_M036_DECLARATION_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.canonical_m036_declaration_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.m145_communication_records_ports.M145CommunicationRecordPersistenceError",
        ErrorCode(
            code="FAIL_M145_COMMUNICATION_RECORD_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.canonical_m145_communication_record_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.settlement_casilla.AmbiguousDeclarationResultError",
        ErrorCode(
            code="REFUSED_AMBIGUOUS_DECLARATION_RESULT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_ambiguous_declaration_result",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.taxation_comparison_ports.TaxationComparisonPersistenceError",
        ErrorCode(
            code="FAIL_TAXATION_COMPARISON_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.canonical_taxation_comparison_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.workflow_gate_ports.WorkflowGatePersistenceError",
        ErrorCode(
            code="FAIL_WORKFLOW_GATE_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.canonical_workflow_gate_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.workspace.ModeloWorkspaceAbsentRegistryProjectionError",
        ErrorCode(
            code="INTEGRITY_MODELO_WORKSPACE_ABSENT_REGISTRY_PROJECTION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.canonical_modelo_workspace_absent_registry_projection",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.workspace.ModeloWorkspaceUnresolvedWorkError",
        ErrorCode(
            code="REFUSED_MODELO_WORKSPACE_UNRESOLVED_WORK",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_modelo_workspace_unresolved_work",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.workspace.ModeloWorkspaceStaleCursorError",
        ErrorCode(
            code="REFUSED_MODELO_WORKSPACE_STALE_CURSOR",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_modelo_workspace_stale_cursor",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.operations.financial_operand_custody.OperationFinancialOperandCustodyError",
        ErrorCode(
            code="INTERNAL_OPERATION_FINANCIAL_OPERAND_CUSTODY",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.canonical_operation_financial_operand_custody",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.operations.observation._DefinitionContractMismatchError",
        ErrorCode(
            code="INTERNAL_OPERATION_DEFINITION_CONTRACT_MISMATCH",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.canonical_operation_definition_contract_mismatch",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.operations.persistence.financial_operand_custody.OperationFinancialOperandCustodyConflictError",
        ErrorCode(
            code="LOCKED_OPERATION_FINANCIAL_OPERAND_CUSTODY_CONFLICT",
            category=ErrorCategory.LOCKED,
            message_key="errors.locked.canonical_operation_financial_operand_custody_conflict",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.operations.persistence.journal.OperationObservationUnknownOperationError",
        ErrorCode(
            code="REFUSED_OPERATION_OBSERVATION_UNKNOWN_OPERATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_operation_observation_unknown_operation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.operations.persistence.journal.OperationObservationCursorAheadError",
        ErrorCode(
            code="REFUSED_OPERATION_OBSERVATION_CURSOR_AHEAD",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_operation_observation_cursor_ahead",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.operator_surface.command_ports.SchemaResolutionError",
        ErrorCode(
            code="INTERNAL_SCHEMA_RESOLUTION",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.canonical_schema_resolution",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.prorrata_register.election.ProrrataElectionError",
        ErrorCode(
            code="REFUSED_PRORRATA_ELECTION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_prorrata_election",
            retryable=False,
            runbook_id=None,
        ),
    ),
)
