"""Canonical registrations for the selected application error contracts."""

from ..error_codes import ErrorCategory, ErrorCode

DECLARED_ERROR_CODES: tuple[tuple[str, ErrorCode], ...] = (
    (
        "cadrumo.application.diagnostics_run_health_ports.DiagnosticRunTelemetryError",
        ErrorCode(
            code="FAIL_DIAGNOSTIC_RUN_TELEMETRY",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.canonical_diagnostic_run_telemetry",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.persistence_errors.PersistenceDegradationError",
        ErrorCode(
            code="FAIL_PERSISTENCE_DEGRADATION",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.canonical_persistence_degradation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.state_projection_ports.StateProjectionReadError",
        ErrorCode(
            code="FAIL_STATE_PROJECTION_READ",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.canonical_state_projection_read",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.aeat_sync.workspace.AeatSyncWorkspaceProjectionError",
        ErrorCode(
            code="INTEGRITY_AEAT_SYNC_WORKSPACE_PROJECTION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.canonical_aeat_sync_workspace_projection",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.aggregation.percepciones_observations_repository.PercepcionObservationPersistenceError",
        ErrorCode(
            code="FAIL_PERCEPCION_OBSERVATION_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.canonical_percepcion_observation_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.aggregation.retencion_observations_repository.RetencionObservationPersistenceError",
        ErrorCode(
            code="FAIL_RETENCION_OBSERVATION_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.canonical_retencion_observation_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.aggregation.invoice_retencion.InvoiceWithholdingEvidenceError",
        ErrorCode(
            code="REFUSED_INVOICE_WITHHOLDING_EVIDENCE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_invoice_withholding_evidence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.aggregation.ledger_payment_withholding.LedgerPaymentWithholdingEvidenceError",
        ErrorCode(
            code="REFUSED_LEDGER_PAYMENT_WITHHOLDING_EVIDENCE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_ledger_payment_withholding_evidence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.aggregation.m193_phase_materialization.Modelo193PhaseMaterializationError",
        ErrorCode(
            code="REFUSED_M193_PHASE_MATERIALIZATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_m193_phase_materialization",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.aggregation.withholding_observation_service.WithholdingObservationMutationError",
        ErrorCode(
            code="REFUSED_WITHHOLDING_OBSERVATION_MUTATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_withholding_observation_mutation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.aggregation.withholding_producer.WithholdingProducerError",
        ErrorCode(
            code="REFUSED_WITHHOLDING_PRODUCER",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_withholding_producer",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.aggregation.withholding_recognition.WithholdingRecognitionError",
        ErrorCode(
            code="REFUSED_WITHHOLDING_RECOGNITION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_withholding_recognition",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.diagnostics_ports.AuthDiagnosticPersistenceError",
        ErrorCode(
            code="FAIL_AUTH_DIAGNOSTIC_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.canonical_auth_diagnostic_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.operator_scope_ports.OperatorScopeStorageError",
        ErrorCode(
            code="FAIL_OPERATOR_SCOPE_STORAGE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.canonical_operator_scope_storage",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.operator_scope_ports.OperatorScopeSessionError",
        ErrorCode(
            code="FAIL_OPERATOR_SCOPE_SESSION",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.canonical_operator_scope_session",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.bienes_inversion.declare_command.BienInversionDisposalIncompleteError",
        ErrorCode(
            code="REFUSED_BIEN_INVERSION_DISPOSAL_INCOMPLETE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_bien_inversion_disposal_incomplete",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.evidence.ports.EvidenceBundlePersistenceError",
        ErrorCode(
            code="FAIL_EVIDENCE_BUNDLE_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.canonical_evidence_bundle_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.filing.producer_snapshot.FilingProducerSnapshotError",
        ErrorCode(
            code="INTEGRITY_FILING_PRODUCER_SNAPSHOT",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.canonical_filing_producer_snapshot",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.inventory.errors.InventoryClosingAuthorityConflictError",
        ErrorCode(
            code="REFUSED_INVENTORY_CLOSING_AUTHORITY_CONFLICT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_inventory_closing_authority_conflict",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.invoices.bulk_import._RowParseError",
        ErrorCode(
            code="INTERNAL_INVOICE_ROW_PARSE",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.canonical_invoice_row_parse",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.invoices.catalogue_creation_ports.CatalogueInvoicePersistenceError",
        ErrorCode(
            code="FAIL_CATALOGUE_INVOICE_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.canonical_catalogue_invoice_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.invoices.catalogue_creation_ports.CatalogueInvoiceRateError",
        ErrorCode(
            code="FAIL_CATALOGUE_INVOICE_RATE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.canonical_catalogue_invoice_rate",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.invoices.catalogue_reads_ports.InvoiceCatalogueReadPersistenceError",
        ErrorCode(
            code="FAIL_INVOICE_CATALOGUE_READ_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.canonical_invoice_catalogue_read_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.invoices.creation_wizard._WizardFieldError",
        ErrorCode(
            code="INTERNAL_INVOICE_WIZARD_FIELD",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.canonical_invoice_wizard_field",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.invoices.source_resolver_ports.InvoiceSourcePersistenceError",
        ErrorCode(
            code="FAIL_INVOICE_SOURCE_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.canonical_invoice_source_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
)
