"""Core-layer :class:`~core.errors.ErrorCode` registry declarations.

Rows map core exception qualnames to stable
:class:`~core.errors.ErrorCategory` values and locale message keys.
"""

from .._registry import ErrorCategory, ErrorCode

_DECLARED_ERROR_CODES: tuple[tuple[str, ErrorCode], ...] = (
    (
        "cadrumo.core.output_rendering.OutputRenderingError",
        ErrorCode(
            code="INTERNAL_OUTPUT_RENDERING",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.internal_output_rendering",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.output_rendering.OutputFormatRefusedError",
        ErrorCode(
            code="REFUSED_OUTPUT_FORMAT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_output_format",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.json_contract.OutputSchemaError",
        ErrorCode(
            code="INTEGRITY_CLI_OUTPUT_SCHEMA",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_cli_output_schema",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.errors.CoreError",
        ErrorCode(
            code="ERROR_CADRUMO_CORE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_cadrumo_core",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.async_cleanup.AsyncResourceCleanupError",
        ErrorCode(
            code="ERROR_CADRUMO_ASYNC_RESOURCE_CLEANUP",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_cadrumo_async_resource_cleanup",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.corpus_text.CorpusAnchorResolutionError",
        ErrorCode(
            code="INTEGRITY_CORPUS_ANCHOR_RESOLUTION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_corpus_anchor_resolution",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.errors.DecimalFormatError",
        ErrorCode(
            code="ERROR_DECIMAL_FORMAT",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_decimal_format",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.errors.RedactionError",
        ErrorCode(
            code="ERROR_REDACTION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_redaction",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.errors._not_found.CoreNotFoundError",
        ErrorCode(
            code="ERROR_CADRUMO_CORE_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_cadrumo_core_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.errors.CoreValidationError",
        ErrorCode(
            code="INTEGRITY_CADRUMO_CORE_VALIDATION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_cadrumo_core_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.tabular.TabularSourceError",
        ErrorCode(
            code="REFUSED_TABULAR_SOURCE_UNREADABLE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_tabular_source_unreadable",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core._optional_extras.MissingOptionalExtraError",
        ErrorCode(
            code="ERROR_OPTIONAL_EXTRA_MISSING",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_cadrumo_core",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core._period.PeriodError",
        ErrorCode(
            code="INTEGRITY_PERIOD",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_period",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.errors.ProfileAnswerTypeError",
        ErrorCode(
            code="INTEGRITY_PROFILE_ANSWER_TYPE",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_profile_answer_type",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.errors.CadrumoObservabilityError",
        ErrorCode(
            code="ERROR_CADRUMO_OBSERVABILITY",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_cadrumo_observability",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.errors.SiteHealthError",
        ErrorCode(
            code="FAIL_SITE_HEALTH",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_site_health",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.i18n._render.MissingTranslationError",
        ErrorCode(
            code="INTERNAL_I18N_MISSING_TRANSLATION",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.internal_output_rendering",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.i18n._render.UnmatchedPlaceholderError",
        ErrorCode(
            code="INTERNAL_I18N_UNMATCHED_PLACEHOLDER",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.internal_output_rendering",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.observability.errors.AeatCorpusDriftError",
        ErrorCode(
            code="INTEGRITY_OBSERVABILITY_AEAT_CORPUS_DRIFT",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_observability_aeat_corpus_drift",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.observability.errors.GoldenCaptureError",
        ErrorCode(
            code="INTEGRITY_OBSERVABILITY_GOLDEN_CAPTURE",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_observability_run_trace_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.observability.errors.GoldenReplayMismatchError",
        ErrorCode(
            code="INTEGRITY_OBSERVABILITY_GOLDEN_REPLAY_MISMATCH",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_observability_run_trace_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.observability.errors.RunContextMissingError",
        ErrorCode(
            code="INTERNAL_OBSERVABILITY_RUN_CONTEXT_MISSING",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.internal_observability_run_context_missing",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.observability.errors.RunTraceValidationError",
        ErrorCode(
            code="INTEGRITY_OBSERVABILITY_RUN_TRACE_VALIDATION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_observability_run_trace_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.observability.errors.RunTracePersistenceError",
        ErrorCode(
            code="FAIL_OBSERVABILITY_RUN_TRACE_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_observability_run_trace_persistence",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.identity._documents.IdentityError",
        ErrorCode(
            code="INTEGRITY_IDENTITY_DOCUMENT",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_identity_document",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.locks_errors.LockAcquisitionError",
        ErrorCode(
            code="LOCKED_STORAGE_LOCK_ACQUISITION",
            category=ErrorCategory.LOCKED,
            message_key="errors.locked.locked_storage_lock_acquisition",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.corpus_manifest.errors.CorpusManifestError",
        ErrorCode(
            code="INTEGRITY_STORAGE_CORPUS_MANIFEST",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_corpus_manifest",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.corpus_manifest.errors.CorpusManifestTamperError",
        ErrorCode(
            code="INTEGRITY_STORAGE_CORPUS_MANIFEST_TAMPER",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_corpus_manifest_tamper",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.corpus_manifest.errors.CorpusManifestDriftError",
        ErrorCode(
            code="INTEGRITY_STORAGE_CORPUS_MANIFEST_DRIFT",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_corpus_manifest_drift",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.corpus_manifest.errors.CorpusBundleError",
        ErrorCode(
            code="INTEGRITY_STORAGE_CORPUS_BUNDLE",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_corpus_bundle",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.corpus_manifest.errors.CorpusBundleVerificationError",
        ErrorCode(
            code="INTEGRITY_STORAGE_CORPUS_BUNDLE_VERIFICATION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_corpus_bundle_verification",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.corpus_manifest._bundle_signing.CorpusBundleSigningError",
        ErrorCode(
            code="INTEGRITY_STORAGE_CORPUS_BUNDLE_SIGNATURE",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_corpus_bundle_signature",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.corpus_manifest._bundle_signing.CorpusBundleSigningKeyNotFoundError",
        ErrorCode(
            code="INTEGRITY_STORAGE_CORPUS_BUNDLE_SIGNING_KEY_NOT_FOUND",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_storage_corpus_bundle_signing_key_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.access_gate.errors.AccessGateSubmissionError",
        ErrorCode(
            code="ERROR_ACCESS_GATE_SUBMISSION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_access_gate_submission",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.access_gate.errors.AccessGateSubmissionPreflightError",
        ErrorCode(
            code="ERROR_ACCESS_GATE_SUBMISSION_PREFLIGHT",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_access_gate_submission_preflight",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.access_gate.errors.LiveSubmitForbiddenError",
        ErrorCode(
            code="LOCKED_ACCESS_GATE_LIVE_SUBMIT_FORBIDDEN",
            category=ErrorCategory.LOCKED,
            message_key="errors.locked.locked_access_gate_live_submit_forbidden",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.access_gate.errors.AeatLiveReadNotEnabledError",
        ErrorCode(
            code="REFUSED_ACCESS_GATE_LIVE_READ_NOT_ENABLED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_access_gate_live_read_not_enabled",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.access_gate.errors.AuthorizationManifestError",
        ErrorCode(
            code="FAIL_ACCESS_GATE_AUTHORIZATION_MANIFEST",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_access_gate_authorization_manifest",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.resources.errors.ResourceLoadError",
        ErrorCode(
            code="ERROR_RESOURCES_LOAD",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_resources_load",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.resources.errors.ResourceNotFoundError",
        ErrorCode(
            code="ERROR_RESOURCES_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_resources_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.resources.errors.ResourceValidationError",
        ErrorCode(
            code="ERROR_RESOURCES_VALIDATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_resources_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.resources.errors.ResourceBackendError",
        ErrorCode(
            code="ERROR_RESOURCES_BACKEND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_resources_backend",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.setup_answers.ProjectAnswersRegistrationError",
        ErrorCode(
            code="INTERNAL_PROFILE_REGISTRATION",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.internal_profile_registration",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.setup_answers.ProjectAnswersNotRegisteredError",
        ErrorCode(
            code="INTERNAL_PROFILE_PROJECT_ANSWERS_NOT_REGISTERED",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.internal_profile_project_answers_not_registered",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.wizard_catalogue.WizardCatalogueNotRegisteredError",
        ErrorCode(
            code="INTERNAL_WIZARD_CATALOGUE_NOT_REGISTERED",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.internal_wizard_catalogue_not_registered",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.wizard_catalogue.WizardCatalogueAlreadyRegisteredError",
        ErrorCode(
            code="INTERNAL_WIZARD_CATALOGUE_ALREADY_REGISTERED",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.internal_wizard_catalogue_already_registered",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.errors.NoActiveProfileError",
        ErrorCode(
            code="REFUSED_NO_ACTIVE_PROFILE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_no_active_profile",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.errors.ActiveProfilePointerError",
        ErrorCode(
            code="INTEGRITY_ACTIVE_PROFILE_POINTER",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_active_profile_pointer",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.core.telemetry.errors.TelemetrySchemaError",
        ErrorCode(
            code="ERROR_TELEMETRY_SCHEMA",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_telemetry_schema",
            retryable=False,
            runbook_id=None,
        ),
    ),
)
