"""Ordered domain :class:`~core.errors.ErrorCode` registry shard.

Rows map domain-layer exception qualnames to stable
:class:`~core.errors.ErrorCategory` values and locale message keys.
"""

from .._registry import ErrorCategory, ErrorCode

_DECLARED_ERROR_CODES: tuple[tuple[str, ErrorCode], ...] = (
    (
        "cadrumo.domain.buckets._errors.BucketsError",
        ErrorCode(
            code="ERROR_DOMAIN_BUCKETS",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_storage_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.buckets._errors.BucketEventValidationError",
        ErrorCode(
            code="INTEGRITY_DOMAIN_BUCKET_EVENT_VALIDATION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.error.error_storage_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.buckets._errors.BucketMaintenanceError",
        ErrorCode(
            code="ERROR_DOMAIN_BUCKET_MAINTENANCE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_storage_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.buckets._errors.BucketBrowseError",
        ErrorCode(
            code="FAIL_DOMAIN_BUCKET_BROWSE",
            category=ErrorCategory.FAIL,
            message_key="errors.error.error_storage_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.buckets._errors.BucketExportError",
        ErrorCode(
            code="FAIL_DOMAIN_BUCKET_EXPORT",
            category=ErrorCategory.FAIL,
            message_key="errors.error.error_storage_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.buckets._errors.BucketImportError",
        ErrorCode(
            code="REFUSED_DOMAIN_BUCKET_IMPORT",
            category=ErrorCategory.REFUSED,
            message_key="errors.error.error_storage_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.buckets._errors.BucketRenameError",
        ErrorCode(
            code="REFUSED_DOMAIN_BUCKET_RENAME",
            category=ErrorCategory.REFUSED,
            message_key="errors.error.error_storage_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.buckets._errors.BucketDeleteRefusedError",
        ErrorCode(
            code="REFUSED_DOMAIN_BUCKET_DELETE",
            category=ErrorCategory.REFUSED,
            message_key="errors.error.error_storage_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.buckets._errors.BucketArchiveRefusedError",
        ErrorCode(
            code="REFUSED_DOMAIN_BUCKET_ARCHIVE",
            category=ErrorCategory.REFUSED,
            message_key="errors.error.error_storage_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.buckets._errors.BucketRestoreRefusedError",
        ErrorCode(
            code="REFUSED_DOMAIN_BUCKET_RESTORE",
            category=ErrorCategory.REFUSED,
            message_key="errors.error.error_storage_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.retention._errors.RetentionError",
        ErrorCode(
            code="ERROR_DOMAIN_RETENTION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_retention",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.retention._errors.RetentionFloorError",
        ErrorCode(
            code="REFUSED_DOMAIN_RETENTION_FLOOR",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_retention_floor",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.buckets._event_repository.BucketEventHistoryPersistenceError",
        ErrorCode(
            code="FAIL_DOMAIN_BUCKET_EVENT_HISTORY_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.error.error_storage_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.bucket._sealed_archive_errors.SealedArchiveLayoutError",
        ErrorCode(
            code="REFUSED_ADAPTER_SEALED_ARCHIVE_LAYOUT",
            category=ErrorCategory.REFUSED,
            message_key="errors.error.error_storage_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.bucket._sealed_archive_errors.SealedArchiveHeaderError",
        ErrorCode(
            code="REFUSED_ADAPTER_SEALED_ARCHIVE_HEADER",
            category=ErrorCategory.REFUSED,
            message_key="errors.error.error_storage_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.bucket._sealed_archive_errors.SealedArchivePayloadError",
        ErrorCode(
            code="REFUSED_ADAPTER_SEALED_ARCHIVE_PAYLOAD",
            category=ErrorCategory.REFUSED,
            message_key="errors.error.error_storage_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.adapters.persistence.storage.bucket._sealed_archive_errors.SealedArchiveWriteError",
        ErrorCode(
            code="FAIL_ADAPTER_SEALED_ARCHIVE_WRITE",
            category=ErrorCategory.FAIL,
            message_key="errors.error.error_storage_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.live._notifications.NotificationsSnapshotNotFoundError",
        ErrorCode(
            code="REFUSED_LIVE_NOTIFICATIONS_SNAPSHOT_NOT_FOUND",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_live_notifications_snapshot_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.live._notification_documents.NotificationDocumentNotFoundError",
        ErrorCode(
            code="REFUSED_LIVE_NOTIFICATION_DOCUMENT_NOT_FOUND",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_live_notification_document_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.live._expedientes.ExpedientesSnapshotNotFoundError",
        ErrorCode(
            code="REFUSED_LIVE_EXPEDIENTES_SNAPSHOT_NOT_FOUND",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_live_expedientes_snapshot_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.live._deudas.DeudasSnapshotNotFoundError",
        ErrorCode(
            code="REFUSED_LIVE_DEUDAS_SNAPSHOT_NOT_FOUND",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_live_deudas_snapshot_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.live._borrador_100.BorradorSnapshotNotFoundError",
        ErrorCode(
            code="REFUSED_LIVE_BORRADOR_SNAPSHOT_NOT_FOUND",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_live_borrador_snapshot_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.live._justificante.JustificanteCaptureSnapshotNotFoundError",
        ErrorCode(
            code="REFUSED_LIVE_JUSTIFICANTE_CAPTURE_SNAPSHOT_NOT_FOUND",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_live_justificante_capture_snapshot_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.live._verify.VerifyObservationNotFoundError",
        ErrorCode(
            code="REFUSED_LIVE_VERIFY_OBSERVATION_NOT_FOUND",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_live_verify_observation_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.portals._service.PortalNotFoundError",
        ErrorCode(
            code="REFUSED_LIVE_PORTAL_NOT_FOUND",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_live_portal_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.justificante._errors.PdfModeloImportError",
        ErrorCode(
            code="ERROR_PDF_IMPORT_PDF_MODELO_IMPORT",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_pdf_import_pdf_modelo_import",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.deadlines._errors.DeadlineError",
        ErrorCode(
            code="ERROR_DEADLINES_DEADLINE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_deadlines_deadline",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.deadlines._errors.ProfileError",
        ErrorCode(
            code="ERROR_DEADLINES_PROFILE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_deadlines_profile",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.deadlines._errors.ScheduleComputationError",
        ErrorCode(
            code="ERROR_DEADLINES_SCHEDULE_COMPUTATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_deadlines_schedule_computation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.deadlines._errors.NoDeadlineWindowsError",
        ErrorCode(
            code="ERROR_DEADLINES_MISSING_WINDOWS",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_deadlines_missing_windows",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.filing._errors.ModeloAmendmentError",
        ErrorCode(
            code="ERROR_FILING_AMENDMENT",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_filing_amendment",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.filing._errors.ModeloAmendmentValidationError",
        ErrorCode(
            code="INTEGRITY_FILING_AMENDMENT_VALIDATION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_filing_amendment_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.filing._errors.ModeloBuilderError",
        ErrorCode(
            code="ERROR_FILING_BUILDER",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_filing_builder",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.filing._errors.ModeloComputationError",
        ErrorCode(
            code="ERROR_FILING_COMPUTATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_filing_computation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.filing._errors.ModeloDraftError",
        ErrorCode(
            code="ERROR_FILING_DRAFT",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_filing_draft",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.filing._errors.ModeloImportError",
        ErrorCode(
            code="FAIL_FILING_IMPORT",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_filing_import",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.filing._errors.FilingValidationError",
        ErrorCode(
            code="INTEGRITY_FILING_VALIDATION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_filing_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.attachments._errors.AttachmentError",
        ErrorCode(
            code="ERROR_FINANCIAL_ATTACHMENTS_ATTACHMENT",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_attachments_attachment",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.attachments._errors.AttachmentNotFoundError",
        ErrorCode(
            code="ERROR_FINANCIAL_ATTACHMENTS_ATTACHMENT_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_attachments_attachment_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.attachments._errors.AttachmentPersistenceError",
        ErrorCode(
            code="FAIL_FINANCIAL_ATTACHMENTS_ATTACHMENT_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_financial_attachments_attachment_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.attachments._errors.AttachmentValidationError",
        ErrorCode(
            code="INTEGRITY_FINANCIAL_ATTACHMENTS_ATTACHMENT_VALIDATION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_financial_attachments_attachment_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.invoices._errors.InvoiceCatalogueError",
        ErrorCode(
            code="ERROR_FINANCIAL_INVOICES_INVOICE_CATALOGUE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_invoices_invoice_catalogue",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.invoices._errors.InvoiceError",
        ErrorCode(
            code="ERROR_FINANCIAL_INVOICES_INVOICE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_invoices_invoice",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.invoices._errors.InvoiceLinkError",
        ErrorCode(
            code="ERROR_FINANCIAL_INVOICES_INVOICE_LINK",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_invoices_invoice_link",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.invoices._errors.InvoiceNotFoundError",
        ErrorCode(
            code="ERROR_FINANCIAL_INVOICES_INVOICE_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_invoices_invoice_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.invoices._errors.InvoicePersistenceError",
        ErrorCode(
            code="FAIL_FINANCIAL_INVOICES_INVOICE_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_financial_invoices_invoice_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.transactions._errors.TransactionError",
        ErrorCode(
            code="ERROR_FINANCIAL_TRANSACTIONS_TRANSACTION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_transactions_transaction",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.transactions._errors.LedgerStorageError",
        ErrorCode(
            code="FAIL_FINANCIAL_LEDGER_STORAGE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_financial_ledger_storage",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.ledger._aeat_record_projection.AeatRecordProjectionError",
        ErrorCode(
            code="REFUSED_AEAT_RECORD_MULTI_RECIPIENT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_aeat_record_multi_recipient",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.ledger._confirmation_gate.ConfirmationBlockedError",
        ErrorCode(
            code="REFUSED_LEDGER_CONFIRMATION_BLOCKED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_ledger_confirmation_blocked",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.ledger._counterparty_establishment.ConfirmedCounterpartyFactsInputError",
        ErrorCode(
            code="REFUSED_LEDGER_COUNTERPARTY_ESTABLISHMENT_INPUT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_ledger_counterparty_establishment_input",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.ledger._counterparty_establishment.CounterpartyEstablishmentConflictError",
        ErrorCode(
            code="REFUSED_LEDGER_COUNTERPARTY_ESTABLISHMENT_CONFLICT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_ledger_counterparty_establishment_conflict",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.ledger._evidence.PurchaseInvoiceEvidenceInputError",
        ErrorCode(
            code="REFUSED_LEDGER_EVIDENCE_INPUT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_ledger_evidence_input",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.ledger._consent_withdrawal.ConsentRederivationError",
        ErrorCode(
            code="REFUSED_LEDGER_CONSENT_REDERIVATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_ledger_evidence_input",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.ledger._evidence.PurchaseInvoiceEvidenceNotFoundError",
        ErrorCode(
            code="REFUSED_LEDGER_EVIDENCE_NOT_FOUND",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_ledger_evidence_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.evidence._models.EvidenceBundleNotFoundError",
        ErrorCode(
            code="REFUSED_EVIDENCE_BUNDLE_NOT_FOUND",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_evidence_bundle_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.evidence._models.EvidenceBundleVerificationError",
        ErrorCode(
            code="REFUSED_EVIDENCE_BUNDLE_VERIFICATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_evidence_bundle_verification",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.inventory._errors.InventoryServiceInputError",
        ErrorCode(
            code="REFUSED_INVENTORY_SERVICE_INPUT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_inventory_service_input",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.inventory._errors.InventoryActividadNotFoundError",
        ErrorCode(
            code="REFUSED_INVENTORY_ACTIVIDAD_NOT_FOUND",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_inventory_actividad_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.inventory._errors.InventoryActividadConflictError",
        ErrorCode(
            code="REFUSED_INVENTORY_ACTIVIDAD_CONFLICT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_inventory_actividad_conflict",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.auth.apoderamientos._catalogue.UnknownScopeError",
        ErrorCode(
            code="REFUSED_APODERADO_UNKNOWN_SCOPE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_apoderado_unknown_scope",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.apoderado_service.ApoderadoConfigurationIdentityError",
        ErrorCode(
            code="INTEGRITY_APODERADO_CONFIGURATION_IDENTITY",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_apoderado_configuration_identity",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.apoderado_service.ApoderadoConfigurationNotSetError",
        ErrorCode(
            code="REFUSED_APODERADO_NOT_CONFIGURED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_apoderado_not_configured",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.apoderado_service.ApoderadoLiveCheckUnavailableError",
        ErrorCode(
            code="REFUSED_APODERADO_LIVE_CHECK_UNAVAILABLE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_apoderado_live_check_unavailable",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.auth.apoderado_service.ApoderadoRepresentedNifInvalidError",
        ErrorCode(
            code="REFUSED_APODERADO_INVALID_REPRESENTED_NIF",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_apoderado_invalid_represented_nif",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.transactions._errors.TransactionIdPrefixError",
        ErrorCode(
            code="REFUSED_FINANCIAL_LEDGER_TRANSACTION_ID_PREFIX",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_financial_ledger_transaction_id_prefix",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.transactions._errors.LedgerNoActiveBucketError",
        ErrorCode(
            code="REFUSED_FINANCIAL_LEDGER_NO_ACTIVE_BUCKET",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_financial_ledger_no_active_bucket",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.usage_ratios._errors.UsageRatioError",
        ErrorCode(
            code="ERROR_FINANCIAL_USAGE_RATIOS_USAGE_RATIO",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_usage_ratios_usage_ratio",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.usage_ratios._errors.UsageRatioPersistenceError",
        ErrorCode(
            code="FAIL_FINANCIAL_USAGE_RATIOS_USAGE_RATIO_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_financial_usage_ratios_usage_ratio_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.usage_ratios._errors.CensoRatioMismatchError",
        ErrorCode(
            code="REFUSED_FINANCIAL_USAGE_RATIOS_CENSO_MISMATCH",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_financial_usage_ratios_censo_mismatch",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.iva._errors.IvaCatalogueError",
        ErrorCode(
            code="ERROR_FINANCIAL_IVA_CATALOGUE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_iva_catalogue",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.iva._errors.IvaCategoryNotFoundError",
        ErrorCode(
            code="ERROR_FINANCIAL_IVA_CATEGORY_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_iva_category_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.iva._errors.IvaClassificationError",
        ErrorCode(
            code="ERROR_FINANCIAL_IVA_CLASSIFICATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_iva_classification",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.iva._errors.IvaError",
        ErrorCode(
            code="ERROR_FINANCIAL_IVA",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_iva",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.iva._errors.IvaRateNotFoundError",
        ErrorCode(
            code="ERROR_FINANCIAL_IVA_RATE_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_iva_rate_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.iva._errors.IvaRateOverlapError",
        ErrorCode(
            code="ERROR_FINANCIAL_IVA_RATE_OVERLAP",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_financial_iva_rate_overlap",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.justificante._errors.JustificanteCsvNotFoundError",
        ErrorCode(
            code="ERROR_JUSTIFICANTE_CSV_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_justificante_csv_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.censo._certificado.CertificadoCensalError",
        ErrorCode(
            code="ERROR_CERTIFICADO_CENSAL",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_certificado_censal",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.censo._certificado.CertificadoCensalParseError",
        ErrorCode(
            code="FAIL_CERTIFICADO_CENSAL_PARSE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_certificado_censal_parse",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.justificante._errors.JustificanteError",
        ErrorCode(
            code="ERROR_JUSTIFICANTE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_justificante",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.justificante._errors.JustificanteParseError",
        ErrorCode(
            code="FAIL_JUSTIFICANTE_PARSE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_justificante_parse",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.justificante._errors.JustificanteVerificationError",
        ErrorCode(
            code="INTEGRITY_JUSTIFICANTE_VERIFICATION",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_justificante_verification",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.manuals._errors.ManifestError",
        ErrorCode(
            code="INTEGRITY_MANUALS_MANIFEST",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_manuals_manifest",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.manuals._errors.ManualError",
        ErrorCode(
            code="ERROR_MANUALS_MANUAL",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_manuals_manual",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.manuals._errors.ManualNotFoundError",
        ErrorCode(
            code="ERROR_MANUALS_MANUAL_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_manuals_manual_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.manuals._errors.ManualParseError",
        ErrorCode(
            code="FAIL_MANUALS_MANUAL_PARSE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_manuals_manual_parse",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.manuals._errors.ManualReviewRequiredError",
        ErrorCode(
            code="ERROR_MANUALS_MANUAL_REVIEW_REQUIRED",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_manuals_manual_review_required",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.manuals._errors.RuleExtractionError",
        ErrorCode(
            code="ERROR_MANUALS_RULE_EXTRACTION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_manuals_rule_extraction",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.portals._errors.PortalIntegrityError",
        ErrorCode(
            code="INTEGRITY_PORTALS_PORTAL_INTEGRITY",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_portals_portal_integrity",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.portals._errors.PortalRegistryError",
        ErrorCode(
            code="ERROR_PORTALS_PORTAL_REGISTRY",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_portals_portal_registry",
            retryable=False,
            runbook_id=None,
        ),
    ),
)
