"""Ordered domain :class:`~core.errors.ErrorCode` registry shard.

Rows map domain-layer exception qualnames to stable
:class:`~core.errors.ErrorCategory` values and locale message keys.
"""

from ..error_codes import ErrorCategory, ErrorCode

DECLARED_ERROR_CODES: tuple[tuple[str, ErrorCode], ...] = (
    (
        "cadrumo.domain.portals.errors.PortalValidationError",
        ErrorCode(
            code="ERROR_PORTALS_VALIDATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_portals_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.usage_ratios.errors.UsageRatioValidationError",
        ErrorCode(
            code="ERROR_USAGE_RATIOS_VALIDATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_usage_ratios_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.deadlines.errors.DeadlineValidationError",
        ErrorCode(
            code="ERROR_DEADLINES_VALIDATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_deadlines_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.submission.errors.SubmissionValidationError",
        ErrorCode(
            code="ERROR_SUBMISSION_VALIDATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_submission_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.manuals.errors.ManualValidationError",
        ErrorCode(
            code="ERROR_MANUALS_VALIDATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_manuals_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.contribuyente.assets.records.AssetRecordError",
        ErrorCode(
            code="ERROR_PROFILE_ASSET_RECORD",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_profile_asset_record",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.contribuyente.assets.records.AssetValidationError",
        ErrorCode(
            code="REFUSED_PROFILE_ASSET_VALIDATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_profile_asset_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.bienes_inversion.register.BienInversionRecordError",
        ErrorCode(
            code="ERROR_PROFILE_BIENES_INVERSION_RECORD",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_profile_bienes_inversion_record",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.bienes_inversion.register.BienInversionValidationError",
        ErrorCode(
            code="REFUSED_PROFILE_BIENES_INVERSION_VALIDATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_profile_bienes_inversion_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.prorrata_register.register.ProrrataRegisterError",
        ErrorCode(
            code="ERROR_PROFILE_PRORRATA_REGISTER_RECORD",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_profile_prorrata_register_record",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.prorrata_register.register.ProrrataRegisterValidationError",
        ErrorCode(
            code="REFUSED_PROFILE_PRORRATA_REGISTER_VALIDATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_profile_prorrata_register_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.contribuyente.inventory.records.AmortizacionLedgerError",
        ErrorCode(
            code="ERROR_PROFILE_AMORTIZATION_LEDGER",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_profile_amortization_ledger",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.contribuyente.inventory.records.InventoryLedgerError",
        ErrorCode(
            code="ERROR_PROFILE_INVENTORY_LEDGER",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_profile_inventory_ledger",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.contribuyente.inventory.records.InventoryValidationError",
        ErrorCode(
            code="REFUSED_PROFILE_INVENTORY_VALIDATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_profile_inventory_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.contribuyente.inventory.records.LIFOForbiddenError",
        ErrorCode(
            code="REFUSED_PROFILE_LIFO_FORBIDDEN",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_profile_lifo_forbidden",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.contribuyente.inventory.records.BasisCapExceededError",
        ErrorCode(
            code="REFUSED_PROFILE_BASIS_CAP_EXCEEDED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_profile_basis_cap_exceeded",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.user_profile.errors.UserProfileError",
        ErrorCode(
            code="ERROR_USER_PROFILE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_user_profile",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.user_profile.errors.UserProfileSchemaLoadError",
        ErrorCode(
            code="FAIL_USER_PROFILE_SCHEMA_LOAD",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_user_profile_schema_load",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.user_profile.errors.UserProfileValidationError",
        ErrorCode(
            code="REFUSED_USER_PROFILE_VALIDATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_user_profile_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.user_profile.errors.UserProfileNotFoundError",
        ErrorCode(
            code="FAIL_USER_PROFILE_NOT_FOUND",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_user_profile_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.user_profile.errors.ProfileNotFoundError",
        ErrorCode(
            code="REFUSED_PROFILE_NOT_FOUND",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_profile_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.user_profile.errors.ProfileAlreadyExistsError",
        ErrorCode(
            code="REFUSED_PROFILE_ALREADY_EXISTS",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_profile_already_exists",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.user_profile.errors.ProfileSchemaValidationError",
        ErrorCode(
            code="REFUSED_PROFILE_SCHEMA_VALIDATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_profile_schema_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.user_profile.errors.ProfilePreflightMissingError",
        ErrorCode(
            code="REFUSED_PROFILE_PREFLIGHT_MISSING",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_profile_preflight_missing",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.user_profile.errors.ProfileSnapshotHashMismatchError",
        ErrorCode(
            code="INTEGRITY_PROFILE_SNAPSHOT_HASH_MISMATCH",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_profile_snapshot_hash_mismatch",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.user_profile.errors.ProfileBucketMismatchError",
        ErrorCode(
            code="INTEGRITY_PROFILE_BUCKET_MISMATCH",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_profile_bucket_mismatch",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.user_profile.errors.ProfileSnapshotNotFoundError",
        ErrorCode(
            code="INTEGRITY_PROFILE_SNAPSHOT_NOT_FOUND",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.integrity_profile_snapshot_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.user_profile.errors.ProfileSnapshotClassificationError",
        ErrorCode(
            code="INTEGRITY_PROFILE_SNAPSHOT_CLASSIFICATION",
            category=ErrorCategory.INTEGRITY,
            message_key="application.user_profile.errors.repository_classification_mismatch",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.user_profile.errors.ProfileSnapshotVersionError",
        ErrorCode(
            code="INTEGRITY_PROFILE_SNAPSHOT_VERSION",
            category=ErrorCategory.INTEGRITY,
            message_key="application.user_profile.errors.repository_profile_snapshot_version_unsupported",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.user_profile.errors.StoredProfileDriftError",
        ErrorCode(
            code="INTEGRITY_STORED_PROFILE_DRIFT",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.storage.stored_data_validation_boundary",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.transactions.errors.StoredTransactionDriftError",
        ErrorCode(
            code="INTEGRITY_STORED_TRANSACTION_DRIFT",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.storage.stored_data_validation_boundary",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.user_profile.errors.ProfileExportError",
        ErrorCode(
            code="FAIL_PROFILE_EXPORT",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.profile_export",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.user_profile.errors.ProfileImportError",
        ErrorCode(
            code="FAIL_PROFILE_IMPORT",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.profile_import",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.user_profile.errors.ProfileImportSignatureError",
        ErrorCode(
            code="INTEGRITY_PROFILE_IMPORT_SIGNATURE",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.integrity.profile_import_signature",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.user_profile.errors.ProfileImportCollisionError",
        ErrorCode(
            code="REFUSED_PROFILE_IMPORT_COLLISION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.profile_import_collision",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.currency.errors.CurrencyError",
        ErrorCode(
            code="FAIL_CURRENCY_ERROR",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.currency_error",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.currency.errors.MissingExchangeRateError",
        ErrorCode(
            code="FAIL_MISSING_EXCHANGE_RATE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.missing_exchange_rate",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.currency.errors.UnsupportedCurrencyError",
        ErrorCode(
            code="REFUSED_UNSUPPORTED_CURRENCY",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.unsupported_currency",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.currency.errors.ExchangeRateProviderError",
        ErrorCode(
            code="FAIL_EXCHANGE_RATE_PROVIDER",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.exchange_rate_provider",
            retryable=True,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.currency.errors.StaleExchangeRateError",
        ErrorCode(
            code="FAIL_STALE_EXCHANGE_RATE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.stale_exchange_rate",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.filing.reconciliation.errors.ReconciliationError",
        ErrorCode(
            code="FAIL_RECONCILIATION",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.reconciliation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.calculations.registry.fixed_width_codec.FixedWidthRecordRenderError",
        ErrorCode(
            code="FAIL_FIXED_WIDTH_RECORD_RENDER",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fixed_width_record_render",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.modelos.errors.ModeloExportError",
        ErrorCode(
            code="FAIL_MODELO_EXPORT",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.modelo_export",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.modelos.errors.ModeloExportManifestError",
        ErrorCode(
            code="FAIL_MODELO_EXPORT_MANIFEST",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.modelo_export_manifest",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.modelos.errors.Modelo036LifecycleError",
        ErrorCode(
            code="FAIL_MODELO_036_LIFECYCLE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.modelo_036_lifecycle",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.modelos.errors.Modelo036PriorAltaRequiredError",
        ErrorCode(
            code="REFUSED_MODELO_036_PRIOR_ALTA_REQUIRED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_036_prior_alta_required",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.modelos.errors.Modelo036TerminalStateError",
        ErrorCode(
            code="REFUSED_MODELO_036_TERMINAL_STATE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_036_terminal_state",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.filing.reconciliation.errors.ReconciliationDeclaracionParseError",
        ErrorCode(
            code="FAIL_DECLARATION_PARSE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.declaration_parse",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.filing.reconciliation.errors.ReconciliationDriftError",
        ErrorCode(
            code="REFUSED_RECONCILIATION_DRIFT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.reconciliation_drift",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.modelos.row_models.Modelo349CountryPrefixContextError",
        ErrorCode(
            code="REFUSED_MODELO_349_COUNTRY_PREFIX_CONTEXT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_349_country_prefix_context",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.modelos.row_models.Modelo347ThresholdError",
        ErrorCode(
            code="REFUSED_MODELO_347_THRESHOLD",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_347_threshold",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.modelos.row_models.Modelo184ShareSumError",
        ErrorCode(
            code="REFUSED_MODELO_184_SHARE_SUM",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_184_share_sum",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.modelos.row_models.Modelo210AgrupacionRentaRowsError",
        ErrorCode(
            code="REFUSED_MODELO_210_AGRUPACION_RENTA_ROWS",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.modelo_210_agrupacion_renta_rows",
            retryable=False,
            runbook_id=None,
        ),
    ),
)
