"""Ordered domain :class:`~cadrumo.core.errors.ErrorCode` registry shard.

Rows map domain-layer exception qualnames to stable
:class:`~cadrumo.core.errors.ErrorCategory` values and locale message keys.
"""

from ..error_codes import ErrorCategory, ErrorCode

DECLARED_ERROR_CODES: tuple[tuple[str, ErrorCode], ...] = (
    (
        "cadrumo.domain.portals.errors.UnknownPortalError",
        ErrorCode(
            code="ERROR_PORTALS_UNKNOWN_PORTAL",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_portals_unknown_portal",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.contribuyente.errors.TaxResidenceProfileError",
        ErrorCode(
            code="ERROR_PROFILE_TAX_RESIDENCE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_profile_tax_residence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.contribuyente.errors.ProfileNotConfiguredError",
        ErrorCode(
            code="REFUSED_PROFILE_NOT_CONFIGURED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_profile_not_configured",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.contribuyente.errors.ForalRegimeError",
        ErrorCode(
            code="REFUSED_PROFILE_FORAL_REGIME",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_profile_foral_regime",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.submission.errors.SubmissionError",
        ErrorCode(
            code="ERROR_DOMAIN_SUBMISSION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_domain_submission",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.submission.errors.SubmissionPreflightError",
        ErrorCode(
            code="ERROR_DOMAIN_SUBMISSION_PREFLIGHT",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_domain_submission_preflight",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.fincas.errors.FincaRegisterError",
        ErrorCode(
            code="ERROR_RENTAL_REGISTER",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_rental_register",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.fincas.errors.FincaNotFoundError",
        ErrorCode(
            code="ERROR_RENTAL_FINCA_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_rental_finca_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.fincas.errors.ContractNotFoundError",
        ErrorCode(
            code="ERROR_RENTAL_CONTRACT_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_rental_contract_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.fincas.errors.TierResolutionError",
        ErrorCode(
            code="ERROR_RENTAL_TIER_RESOLUTION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_rental_tier_resolution",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.fincas.errors.AmortizationLedgerCapExceededError",
        ErrorCode(
            code="ERROR_RENTAL_AMORTIZATION_CAP_EXCEEDED",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_rental_amortization_cap_exceeded",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.fincas.errors.FincaAggregationError",
        ErrorCode(
            code="ERROR_RENTAL_AGGREGATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_rental_register",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.calculations.registry.errors.RegistryError",
        ErrorCode(
            code="ERROR_CALCULATIONS_REGISTRY",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_calculations_registry",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.calculations.registry.errors.RegistryLoadError",
        ErrorCode(
            code="ERROR_CALCULATIONS_REGISTRY_LOAD",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_calculations_registry_load",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.calculations.registry.errors.RegistryValidationError",
        ErrorCode(
            code="ERROR_CALCULATIONS_REGISTRY_VALIDATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_calculations_registry_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.calculations.registry.errors.RegistrySnapshotError",
        ErrorCode(
            code="ERROR_CALCULATIONS_REGISTRY_SNAPSHOT",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_calculations_registry_snapshot",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.calculations.registry.formula_runtime_ops.UnresolvedFormulaDependencyError",
        ErrorCode(
            code="ERROR_CALCULATIONS_REGISTRY_UNRESOLVED_FORMULA_DEPENDENCY",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_calculations_registry_snapshot",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.calculations.registry.formula_runtime_ops.UnresolvedFormulaOutcomeError",
        ErrorCode(
            code="ERROR_CALCULATIONS_REGISTRY_UNRESOLVED_FORMULA_OUTCOME",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_calculations_registry_snapshot",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.calculations.registry.errors.NoRevisionForPeriodError",
        ErrorCode(
            code="ERROR_CALCULATIONS_REGISTRY_NO_REVISION_FOR_PERIOD",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_calculations_registry_snapshot",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.calculations.registry.errors.AmbiguousRevisionSelectionError",
        ErrorCode(
            code="ERROR_CALCULATIONS_REGISTRY_AMBIGUOUS_REVISION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_calculations_registry_snapshot",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.calculations.registry.errors.CasillaConstraintViolationError",
        ErrorCode(
            code="REFUSED_CALCULATIONS_CASILLA_CONSTRAINT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_calculations_casilla_constraint",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.renta.errors.RentaError",
        ErrorCode(
            code="ERROR_RENTA",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_renta",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.renta.errors.RentaValidationError",
        ErrorCode(
            code="ERROR_RENTA_VALIDATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_renta_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.renta.maritime_exemption.MaritimeExemptionInactiveError",
        ErrorCode(
            code="REFUSED_RENTA_MARITIME_EXEMPTION_INACTIVE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_renta_maritime_exemption_inactive",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.renta.maritime_exemption.ProfileCompletenessError",
        ErrorCode(
            code="ERROR_RENTA_PROFILE_COMPLETENESS_WARNING",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_renta_profile_completeness_warning",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.modelos.errors.ModeloError",
        ErrorCode(
            code="ERROR_MODELOS",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_modelos",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.modelos.errors.ModeloValidationError",
        ErrorCode(
            code="ERROR_MODELOS_VALIDATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_modelos_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.modelos.repository.WorkUnitPersistenceError",
        ErrorCode(
            code="FAIL_MODELO_WORK_UNIT_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_modelo_work_unit_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.ModeloWorkflowGateError",
        ErrorCode(
            code="REFUSED_MODELO_WORKFLOW_GATE",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.errors.workflow_gate_no_pending_obligation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.ModeloRefundElectionNotEligibleError",
        ErrorCode(
            code="REFUSED_MODELO_REFUND_ELECTION_NOT_ELIGIBLE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_modelo_refund_election_not_eligible",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.ModeloPaymentElectionIncompatibleError",
        ErrorCode(
            code="REFUSED_MODELO_PAYMENT_ELECTION_INCOMPATIBLE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_modelo_payment_election_incompatible",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.ModeloPaymentElectionCapabilityRefusedError",
        ErrorCode(
            code="REFUSED_MODELO_PAYMENT_ELECTION_CAPABILITY",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_modelo_payment_election_capability",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.ModeloPriorDomiciliationElectionRefusedError",
        ErrorCode(
            code="REFUSED_MODELO_PRIOR_DOMICILIATION_ELECTION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_modelo_prior_domiciliation_election",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.ModeloRefundAccountMissingError",
        ErrorCode(
            code="REFUSED_MODELO_REFUND_ACCOUNT_MISSING",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_modelo_refund_account_missing",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.ModeloChargeAccountMissingError",
        ErrorCode(
            code="REFUSED_MODELO_CHARGE_ACCOUNT_MISSING",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_modelo_charge_account_missing",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.WorkUnitNotFoundError",
        ErrorCode(
            code="ERROR_MODELO_WORK_UNIT_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_modelo_work_unit_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.WorkUnitAlreadyDiscardedError",
        ErrorCode(
            code="REFUSED_MODELO_WORK_UNIT_ALREADY_DISCARDED",
            category=ErrorCategory.REFUSED,
            message_key="errors.error.error_modelo_work_unit_already_discarded",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.WorkUnitMutationRefusedError",
        ErrorCode(
            code="REFUSED_MODELO_WORK_UNIT_MUTATION_REFUSED",
            category=ErrorCategory.REFUSED,
            message_key="errors.error.error_modelo_work_unit_mutation_refused",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.CalculationRevisionNotFoundError",
        ErrorCode(
            code="ERROR_MODELO_CALCULATION_REVISION_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_modelo_calculation_revision_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.CalculationRevisionStateError",
        ErrorCode(
            code="ERROR_MODELO_CALCULATION_REVISION_STATE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_modelo_calculation_revision_state",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.CalculationRegistryUnavailableError",
        ErrorCode(
            code="ERROR_MODELO_CALCULATION_REGISTRY_UNAVAILABLE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_modelo_calculation_registry_unavailable",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.CasillaProvenanceMissingError",
        ErrorCode(
            code="ERROR_MODELO_CASILLA_PROVENANCE_MISSING",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_modelo_casilla_provenance_missing",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.ModeloAggregationBindingError",
        ErrorCode(
            code="ERROR_MODELO_AGGREGATION_BINDING",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_modelo_aggregation_binding",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.iva_wallet_gate.ModeloIvaWalletReconciliationBlockedError",
        ErrorCode(
            code="ERROR_MODELO_IVA_WALLET_RECONCILIATION_BLOCKED",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_modelo_iva_wallet_reconciliation_blocked",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.ModeloCrossPeriodCleanStateError",
        ErrorCode(
            code="REFUSED_MODELO_CROSS_PERIOD_CLEAN_STATE",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.errors.cross_period_clean_state_incomplete",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.WorkUnitRevisionDivergenceError",
        ErrorCode(
            code="REFUSED_MODELO_WORK_UNIT_REVISION_DIVERGENCE",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.errors.work_unit_revision_divergence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.iva_wallet_seed.ModeloIvaWalletSeedError",
        ErrorCode(
            code="ERROR_MODELO_IVA_WALLET_SEED",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_modelos",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.iva_wallet_seed.ModeloIvaWalletSeedNoTaxpayerError",
        ErrorCode(
            code="REFUSED_MODELO_IVA_WALLET_SEED_NO_TAXPAYER",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.iva_wallet.seed_no_nif",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.iva_wallet_seed.ModeloIvaWalletSeedNegativeAmountError",
        ErrorCode(
            code="REFUSED_MODELO_IVA_WALLET_SEED_NEGATIVE_AMOUNT",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.iva_wallet.seed_negative_amount",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.iva_wallet_seed.ModeloIvaWalletCorrectionNoRecordError",
        ErrorCode(
            code="REFUSED_MODELO_IVA_WALLET_CORRECTION_NO_RECORD",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.iva_wallet.correct_no_record",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.iva_wallet_seed.ModeloIvaWalletCorrectionSealedError",
        ErrorCode(
            code="REFUSED_MODELO_IVA_WALLET_CORRECTION_SEALED",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.iva_wallet.correct_sealed_blocked",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.iva_wallet_seed.ModeloIvaWalletOverrideSealedError",
        ErrorCode(
            code="REFUSED_MODELO_IVA_WALLET_OVERRIDE_SEALED",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.iva_wallet.override_sealed_blocked",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.iva_wallet_seed.ModeloIvaWalletOverrideFreshWalletError",
        ErrorCode(
            code="REFUSED_MODELO_IVA_WALLET_OVERRIDE_FRESH_WALLET",
            category=ErrorCategory.REFUSED,
            message_key="application.modelo.iva_wallet.override_fresh_wallet_blocked",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.ModeloRecordNotFoundError",
        ErrorCode(
            code="ERROR_MODELO_FILING_RECORD_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_modelo_filing_record_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.AmendmentEvidenceMissingError",
        ErrorCode(
            code="ERROR_MODELO_AMENDMENT_EVIDENCE_MISSING",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_modelo_amendment_evidence_missing",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.AmendmentM303RectificativaMotiveError",
        ErrorCode(
            code="REFUSED_MODELO_M303_RECTIFICATIVA_MOTIVE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_modelo_m303_rectificativa_motive",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.AmendmentTargetStateError",
        ErrorCode(
            code="ERROR_MODELO_AMENDMENT_TARGET_STATE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_modelo_amendment_target_state",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.AmendmentOverrideCasillaError",
        ErrorCode(
            code="REFUSED_MODELO_AMENDMENT_OVERRIDE_CASILLA",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_modelo_amendment_override_casilla",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.AmendmentVerificationRefusedError",
        ErrorCode(
            code="REFUSED_MODELO_AMENDMENT_VERIFICATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_modelo_amendment_verification",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.AmendmentKindNotPermittedError",
        ErrorCode(
            code="REFUSED_MODELO_AMENDMENT_KIND_NOT_PERMITTED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_modelo_amendment_kind_not_permitted",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.AmendmentComplementariaLiabilityDecreaseError",
        ErrorCode(
            code="REFUSED_MODELO_AMENDMENT_COMPLEMENTARIA_LIABILITY_DECREASE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_modelo_amendment_complementaria_liability_decrease",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.ExternalModeloImportError",
        ErrorCode(
            code="ERROR_MODELO_EXTERNAL_FILING_IMPORT",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_modelo_external_filing_import",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.ModeloLocalObservationError",
        ErrorCode(
            code="REFUSED_MODELO_LOCAL_OBSERVATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.error.error_modelos",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.modelos.calculation_repository.CalculationRevisionPersistenceError",
        ErrorCode(
            code="FAIL_MODELO_CALCULATION_REVISION_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_modelo_calculation_revision_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.modelos.participation_index.TransactionParticipationIndexPersistenceError",
        ErrorCode(
            code="FAIL_MODELO_PARTICIPATION_INDEX_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_modelo_calculation_revision_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.modelos.calculation_revision.LedgerFilingCoverageError",
        ErrorCode(
            code="FAIL_MODELO_LEDGER_FILING_COVERAGE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_modelo_calculation_revision_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.modelos.filing_repository.ModeloRecordPersistenceError",
        ErrorCode(
            code="FAIL_MODELO_FILING_RECORD_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_modelo_filing_record_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.application.modelo.action_errors.VerificationReportNotFoundError",
        ErrorCode(
            code="ERROR_MODELO_VERIFICATION_REPORT_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_modelo_verification_report_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.modelos.verification_repository.VerificationReportPersistenceError",
        ErrorCode(
            code="FAIL_MODELO_VERIFICATION_REPORT_PERSISTENCE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_modelo_verification_report_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.period.RegistryPeriodError",
        ErrorCode(
            code="ERROR_PERIOD",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_period",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.period.PeriodValidationError",
        ErrorCode(
            code="ERROR_PERIOD_VALIDATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_period_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.categories.errors.CategoryError",
        ErrorCode(
            code="ERROR_CATEGORIES",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_categories",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.categories.errors.CategoryValidationError",
        ErrorCode(
            code="ERROR_CATEGORIES_VALIDATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_categories_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.errors.DomainValidationError",
        ErrorCode(
            code="ERROR_DOMAIN_VALIDATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_domain_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.contribuyente.errors.ProfileValidationError",
        ErrorCode(
            code="ERROR_PROFILE_VALIDATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_profile_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.contribuyente.errors.ProfileKeysRegistrationError",
        ErrorCode(
            code="INTERNAL_PROFILE_KEYS_REGISTRATION",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.internal_profile_keys_registration",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.filing.errors.FilingExportError",
        ErrorCode(
            code="ERROR_FILING_EXPORT",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_filing_export",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.filing.errors.FilingExportValidationError",
        ErrorCode(
            code="ERROR_FILING_EXPORT_VALIDATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_filing_export_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.invoices.errors.InvoiceLinkInconsistencyError",
        ErrorCode(
            code="ERROR_INVOICE_LINK_INCONSISTENCY",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_invoice_link_inconsistency",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.invoices.errors.InvoiceValidationError",
        ErrorCode(
            code="ERROR_INVOICE_VALIDATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_invoice_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.transactions.errors.TransactionCatalogueError",
        ErrorCode(
            code="ERROR_TRANSACTION_CATALOGUE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_transaction_catalogue",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.transactions.errors.TransactionPersistenceError",
        ErrorCode(
            code="ERROR_TRANSACTION_PERSISTENCE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_transaction_persistence",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.transactions.errors.TransactionNotFoundError",
        ErrorCode(
            code="ERROR_TRANSACTION_NOT_FOUND",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_transaction_not_found",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.transactions.errors.LLMClassifierError",
        ErrorCode(
            code="ERROR_TRANSACTION_LLM_CLASSIFIER",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_transaction_llm_classifier",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.transactions.errors.TransactionValidationError",
        ErrorCode(
            code="ERROR_TRANSACTION_VALIDATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_transaction_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.transactions.errors.LedgerLinkError",
        ErrorCode(
            code="FAIL_LEDGER_LINK",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.ledger_link",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.transactions.errors.LedgerCheckError",
        ErrorCode(
            code="FAIL_LEDGER_CHECK",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.ledger_check",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.transactions.errors.LedgerPreflightError",
        ErrorCode(
            code="REFUSED_LEDGER_PREFLIGHT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.ledger_preflight",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.transactions.errors.ClassificationRuleError",
        ErrorCode(
            code="ERROR_TRANSACTION_CLASSIFICATION_RULE",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_transaction_classification_rule",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.fincas.errors.FincaValidationError",
        ErrorCode(
            code="ERROR_RENTAL_VALIDATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_rental_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.iva.errors.IvaValidationError",
        ErrorCode(
            code="ERROR_IVA_VALIDATION",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_iva_validation",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.iva.errors.ProrrataError",
        ErrorCode(
            code="ERROR_IVA_PRORRATA",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_iva_prorrata",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.iva.errors.ProrrataInputError",
        ErrorCode(
            code="ERROR_IVA_PRORRATA_INPUT",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_iva_prorrata_input",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.domain.iva.errors.ProrrataSectorError",
        ErrorCode(
            code="ERROR_IVA_PRORRATA_SECTOR",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_iva_prorrata_sector",
            retryable=False,
            runbook_id=None,
        ),
    ),
)
