"""Entrypoint-layer :class:`~core.errors.ErrorCode` registry declarations.

Rows map CLI boundary exception qualnames to stable
:class:`~core.errors.ErrorCategory` values and locale message keys.
"""

from .._registry import ErrorCategory, ErrorCode

_DECLARED_ERROR_CODES: tuple[tuple[str, ErrorCode], ...] = (
    (
        "cadrumo.entrypoints.cli._config.errors.ConfigBoundaryError",
        ErrorCode(
            code="ERROR_CONFIG_BOUNDARY",
            category=ErrorCategory.ERROR,
            message_key="errors.error.error_config_boundary",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.cli.errors.CliCommandGroupUnavailableError",
        ErrorCode(
            code="FAIL_CLI_COMMAND_GROUP_UNAVAILABLE",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.fail_cli_command_group_unavailable",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.cli.errors.CliRefusedBoundaryError",
        ErrorCode(
            code="REFUSED_CLI_BOUNDARY",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_cli_boundary",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.cli.errors.CliTuiNotImplementedError",
        ErrorCode(
            code="TUI_NOT_IMPLEMENTED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_tui_not_implemented",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.cli.errors.CliOutboundPayloadBoundaryError",
        ErrorCode(
            code="INTERNAL_CLI_OUTBOUND_PAYLOAD_BOUNDARY",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.cli_outbound_payload_boundary",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.cli.errors.CliStoredDataValidationBoundaryError",
        ErrorCode(
            code="INTEGRITY_STORED_DATA_VALIDATION_BOUNDARY",
            category=ErrorCategory.INTEGRITY,
            message_key="errors.storage.stored_data_validation_boundary",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.cli.errors.CliValidationBoundaryError",
        ErrorCode(
            code="REFUSED_CLI_VALIDATION_BOUNDARY",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_cli_validation_boundary",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.cli.errors.CliUnexpectedBoundaryError",
        ErrorCode(
            code="INTERNAL_CLI_UNEXPECTED_BOUNDARY",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.internal_cli_unexpected_boundary",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.cli._log_levels.LogLevelResolutionError",
        ErrorCode(
            code="REFUSED_CLI_LOG_LEVEL_RESOLUTION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_cli_log_level_resolution",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.cli._tty.NonTtyRefusedError",
        ErrorCode(
            code="REFUSED_CLI_NON_TTY",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.refused_cli_non_tty",
            retryable=False,
            runbook_id=None,
        ),
    ),
)
