"""Ordered TUI-entrypoint :class:`~core.errors.error_codes.ErrorCode` registry shard.

Rows map TUI boundary exception qualnames to stable
:class:`~core.errors.error_codes.ErrorCategory` values and locale message keys.
"""

from ..error_codes import ErrorCategory, ErrorCode

DECLARED_ERROR_CODES: tuple[tuple[str, ErrorCode], ...] = (
    (
        "cadrumo.entrypoints.tui.launcher.TuiModuleArgumentError",
        ErrorCode(
            code="REFUSED_TUI_MODULE_ARGUMENT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_tui_module_argument",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.tui.account.AccountSessionExpiredError",
        ErrorCode(
            code="FAIL_TUI_ACCOUNT_SESSION_EXPIRED",
            category=ErrorCategory.FAIL,
            message_key="errors.fail.canonical_tui_account_session_expired",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.tui.components.theme.UnknownDesignTokenError",
        ErrorCode(
            code="REFUSED_TUI_UNKNOWN_DESIGN_TOKEN",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_tui_unknown_design_token",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.tui.modelo.installed_workspace.ModeloWorkspaceDeclarationAdmissionError",
        ErrorCode(
            code="REFUSED_TUI_MODELO_WORKSPACE_DECLARATION_ADMISSION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_tui_modelo_workspace_declaration_admission",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.tui.modelo.view.controller.ModeloWorkspaceSessionAdmissionError",
        ErrorCode(
            code="REFUSED_TUI_MODELO_WORKSPACE_SESSION_ADMISSION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_tui_modelo_workspace_session_admission",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.tui.navigation.NavigationContractError",
        ErrorCode(
            code="REFUSED_TUI_NAVIGATION_CONTRACT",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_tui_navigation_contract",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.tui.navigation.UnknownDestinationError",
        ErrorCode(
            code="REFUSED_TUI_UNKNOWN_DESTINATION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_tui_unknown_destination",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.tui.navigation.DestinationAdmissionError",
        ErrorCode(
            code="REFUSED_TUI_DESTINATION_ADMISSION",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_tui_destination_admission",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.tui.navigation.DestinationUnavailableError",
        ErrorCode(
            code="REFUSED_TUI_DESTINATION_UNAVAILABLE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_tui_destination_unavailable",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.tui.navigation.UnresolvedActionCandidateError",
        ErrorCode(
            code="REFUSED_TUI_UNRESOLVED_ACTION_CANDIDATE",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_tui_unresolved_action_candidate",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.tui.navigation.DestinationFactoryError",
        ErrorCode(
            code="REFUSED_TUI_DESTINATION_FACTORY",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_tui_destination_factory",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.tui.search.TuiSearchHostError",
        ErrorCode(
            code="INTERNAL_TUI_SEARCH_HOST",
            category=ErrorCategory.INTERNAL,
            message_key="errors.internal.canonical_tui_search_host",
            retryable=False,
            runbook_id=None,
        ),
    ),
    (
        "cadrumo.entrypoints.tui.secret.registration.RecoveryHandoverDeclinedError",
        ErrorCode(
            code="REFUSED_TUI_RECOVERY_HANDOVER_CANCELLED",
            category=ErrorCategory.REFUSED,
            message_key="errors.refused.canonical_tui_recovery_handover_cancelled",
            retryable=False,
            runbook_id=None,
        ),
    ),
)
