[[revisions.2024.casillas]]
id = '02471'
number = '02471'
data_type = 'money'
semantic_role = 'is_deduccion_donativos_general'
required = false
input_kind = 'manual'
section = [
    'deduccion_donativos_entidades_sin_fines_lucro',
    'donaciones_de_caracter_general',
]
legal_refs = [
    'ley-49-2002:art-20',
]
source_refs = [
    'aeat-dr-200-2024',
    'aeat-modelo-200-manual-2024',
]


