"""The territory table's citation resolves, and the statute says what it claims.

The table maps Spanish postal-code prefixes to IVA territories and cites Ley
37/1992 art. 3.Dos for the exclusions it enumerates. Two things can go wrong with
a citation like that and only one of them is visible from the table: the
identifier can name a provision nobody defined, and the provision can fail to say
what the row rests on. This module checks both against the bundled consolidated
text rather than against a literal typed beside the row, because an expectation
copied from the row would pass whatever the row said.

The Balears carry their own case deliberately. "Islands are outside the TAI" is
the plausible wrong generalisation -- Canarias is islands and is outside -- and
the table places the Balears inside by leaving prefix 07 out of the excluded set
rather than by naming them. Nothing in art. 3 names them either, so the case below
pins the mechanism that actually puts them inside: adjacency plus non-exclusion.

The prefix-to-province correspondence is administrative geography rather than tax
law, so no BOE text grounds it and none is checked here.

Every assertion below runs against the ANCHORED ARTICLE UNIT rather than the
whole consolidated law, and resolves that unit the way the registry's own legal
evidence gate resolves one: through the cited catalogue entry's ``corpus_ref``,
against the json sidecar, with :func:`~core.resolve_anchored_extracted_unit`.
Both halves of that matter. Asserting a statute phrase against six hundred
thousand characters of law is non-vacuous only while the phrase happens to occur
once, so a consolidation repeating an exclusion phrase in an unrelated article
would quietly turn a discriminating check into a passing one; and the silence
claim about the Balears is the same defect mirrored, since read law-wide it reds
on any future amendment that mentions the islands for reasons having nothing to
do with territorial scope. Reading the same artefact the catalogue reads closes
a third gap at the same time: the markdown and json sidecars are regenerated by
different paths, so a test reading one while the catalogue reads the other can
stay green over bytes nobody checked.

See Also:
    :class:`~domain.iva.IvaTerritorialScope`
        The closed territorial classification these rows resolve into.
    :func:`~core.resolve_anchored_extracted_unit`
        The resolver the registry's legal evidence gate uses, shared here so
        both surfaces read one artefact.
"""

from __future__ import annotations

import tomllib
from functools import lru_cache
from typing import Final

import pytest

from ....core.corpus_text import normalise_corpus_text, resolve_anchored_extracted_unit
from ....core.resources.bundled_data import bundled_path
from ..classification import IvaTerritorialScope

pytestmark = [pytest.mark.unit, pytest.mark.hex_domain]

# Every legal catalogue a territory row is allowed to cite into. Listed rather
# than globbed so a row citing a provision parked in some unrelated tree fails
# here instead of resolving by accident.
_CATALOGUE_FILES = (
    "registry/aeat/legal/tax-framework.toml",
    "registry/aeat/legal/iva.toml",
    "registry/aeat/legal/iva-flow.toml",
)

#: The provision the whole table rests on. Named once so the article-scoped
#: cases below cannot silently start reading a different entry's text.
_TERRITORIAL_EXCLUSION_REFERENCE: Final[str] = "ley-37-1992:art-3.dos"

#: Wording from a distant article of the same law, used to prove the anchor
#: really scoped. Without it a resolver regression returning the whole document
#: would satisfy every positive assertion here and quietly restore exactly the
#: law-wide reading this module was rewritten to remove.
_WORDING_FROM_ANOTHER_ARTICLE: Final[str] = "El impuesto se exigirá al tipo del 21 por ciento"


def _territory_records() -> list[dict[str, object]]:
    payload = tomllib.loads(
        bundled_path("registry", "aeat", "iva", "territories.toml").read_text(encoding="utf-8"),
    )
    records = payload["territory"]
    assert records, "the territory registry enumerates no excluded territory"
    return list(records)


def _string_list(record: dict[str, object], field: str) -> list[str]:
    """Return ``field`` as a list of strings, refusing anything else.

    TOML hands back ``object``, and narrowing it with a cast would assert the
    shape rather than check it. A malformed table is a real failure mode here --
    a prefix written as a bare integer would silently never match a string
    comparison -- so the shape is verified rather than declared.
    """
    value = record[field]

    assert isinstance(value, list), f"{field} is not a list: {value!r}"
    for item in value:
        assert isinstance(item, str), f"{field} carries a non-string entry: {item!r}"
    return list(value)


def _catalogue_entries() -> dict[str, dict[str, object]]:
    """Return every catalogue entry a territory row may cite, parsed as TOML.

    Parsed rather than string-searched. A substring test for the table header
    answers "do these bytes appear somewhere", which is true of an entry
    commented out, an entry inside an unrelated table, and an entry whose
    ``corpus_ref`` the reader never looks at -- and the ``corpus_ref`` is
    precisely what the cases below need in order to read the statute.
    """
    merged: dict[str, dict[str, object]] = {}
    for name in _CATALOGUE_FILES:
        payload = tomllib.loads((bundled_path() / name).read_text(encoding="utf-8"))
        entries = payload.get("legal", {})
        assert isinstance(entries, dict), f"{name} carries no legal table"
        for key, entry in entries.items():
            assert isinstance(entry, dict), f"{name} entry {key!r} is not a table"
            merged[str(key)] = entry
    return merged


@lru_cache(maxsize=1)
def _cited_article_text() -> str:
    """Return the anchored article unit the territorial exclusion citation names.

    Resolved from the catalogue's own ``corpus_ref`` rather than from a path
    written here, so a re-anchored or relocated citation moves this gate with it
    instead of leaving it reading a file the catalogue abandoned.

    Cached because it is a constant of the bundled corpus and every case below
    reads it; the resolution and its normalisation are the expensive half of
    this module.
    """
    entry = _catalogue_entries()[_TERRITORIAL_EXCLUSION_REFERENCE]
    corpus_ref = entry["corpus_ref"]
    assert isinstance(corpus_ref, str), f"{_TERRITORIAL_EXCLUSION_REFERENCE} carries no corpus_ref string"

    path_text, separator, anchor = corpus_ref.partition("#")
    assert separator and anchor, f"{corpus_ref!r} names no anchor, so it cannot scope to one article"

    document = bundled_path() / path_text
    sidecar = document.with_name(document.name + ".extracted.json")
    assert sidecar.is_file(), f"the cited corpus has no extracted sidecar at {sidecar}"

    # ``include_title`` mirrors the registry's legal evidence gate exactly. The
    # heading is part of what that gate reads, and reading a narrower slice here
    # would reintroduce the divergence this rewrite closed.
    return normalise_corpus_text(resolve_anchored_extracted_unit(sidecar, anchor=anchor, include_title=True))


def _article_states(phrase: str) -> bool:
    """Return whether the cited article carries ``phrase``, comparison-normalised.

    Every statute check goes through this rather than asserting the membership
    expression directly, so a failure reports the PHRASE and never the corpus.
    Asserting ``normalise(phrase) in article`` inline reads better until it
    fails: pytest renders both operands, and under exactly the regression these
    cases exist to catch -- a resolver handing back the whole consolidated law --
    the operand is six hundred thousand characters and the runner stops being
    able to report the failure at all. A gate nobody can read the output of is
    not much better than one that did not fire.
    """
    return normalise_corpus_text(phrase) in _cited_article_text()


def test_every_cited_provision_resolves_in_the_legal_catalogue() -> None:
    """A row citing an article nobody defined is ungrounded and must not ship.

    This is the property the table could not previously assert: the citation
    parsed as an identifier while no catalogue entry carried a ``corpus_ref``, so
    nothing checked it against the statute.
    """
    defined = _catalogue_entries()
    cited = {ref for record in _territory_records() for ref in _string_list(record, "legal_refs")}

    assert cited, "no territory row cites a provision; this case would pass vacuously"
    for reference in cited:
        assert reference in defined, f"the territory table cites {reference}, which no legal catalogue entry defines"
        assert defined[reference].get("corpus_ref"), (
            f"the catalogue defines {reference} but points it at no corpus text, so nothing grounds it"
        )


def test_the_citation_resolves_to_one_article_rather_than_the_whole_law() -> None:
    """The scoping the cases below depend on, asserted rather than assumed.

    Every statute assertion in this module is a substring test, and a substring
    test is discriminating only in proportion to how narrow the text under it
    is. If the resolver ever returned the whole consolidated document -- a
    duplicated anchor collapsing to a single-unit fallback would do it -- each
    of those assertions would still pass while checking almost nothing. So the
    scope is pinned here directly, at both ends: the article's own wording is
    present, and wording from a different article of the same law is not.
    """
    assert _article_states("Territorialidad"), "the resolved unit is not the territoriality article"
    assert not _article_states(_WORDING_FROM_ANOTHER_ARTICLE), (
        "the citation resolved to more than its own article, so every phrase check here is weakened"
    )


def test_the_cited_article_excludes_exactly_the_territories_the_table_enumerates() -> None:
    """Checked against the statute, not against the row.

    Art. 3.Dos.1.o excludes Ceuta y Melilla under letter a) and Canarias under
    letter b), on two different grounds -- outside the customs union, and outside
    turnover-tax harmonisation. Both limbs are asserted, so a table that kept one
    exclusion and dropped the other cannot pass.
    """
    assert _article_states(
        "en el Reino de España, Ceuta y Melilla y en la República Italiana, Livigno, "
        "en cuanto territorios no comprendidos en la Unión Aduanera",
    ), "the cited article no longer excludes Ceuta y Melilla as territory outside the customs union"
    assert _article_states("En el Reino de España, Canarias"), (
        "the cited article no longer excludes Canarias from turnover-tax harmonisation"
    )

    scopes = {IvaTerritorialScope(str(record["scope"])) for record in _territory_records()}

    assert scopes == {IvaTerritorialScope.ES_CANARIAS, IvaTerritorialScope.ES_CEUTA_MELILLA}, (
        "the table excludes a territory the cited article does not, or drops one it does"
    )


def test_the_balears_are_inside_by_non_exclusion_and_the_statute_never_names_them() -> None:
    """The generalisation this table is shaped to refuse, pinned at both ends.

    The statute end: apartado Uno reaches the adjacent islands and apartado Dos
    excludes no Spanish territory beyond Canarias, Ceuta and Melilla, so nothing
    in art. 3 mentions the Balears at all. The table end: prefix 07 is absent from
    the excluded set, and absence is what places a prefix inside the TAI.

    Asserting the statute is SILENT is the load-bearing half. A future reader who
    finds no mention of the Balears has no way to tell a deliberate absence from
    an incomplete corpus, and would be one plausible edit away from "correcting"
    the table to put the islands outside.

    The silence is asserted of ART. 3, never of the law. "The Balears appear
    nowhere in Ley 37/1992" is a claim about the whole statute that this table
    does not rest on and cannot keep true: any future amendment naming the
    islands for an unrelated reason -- a régimen, a deadline, a transitional
    disposition -- would red this case with a message about territorial scope,
    which is a false report and an expensive one to diagnose. What the table
    actually rests on is that the article defining the ámbito espacial does not
    name them, and that is what is checked.
    """
    assert _article_states("incluyendo en él las islas adyacentes"), (
        "the article no longer reaches the adjacent islands, which is what places the Balears inside"
    )
    for name in ("Baleares", "Balears"):
        assert not _article_states(name), (
            f"the ámbito espacial article now names the {name}, so the table's non-exclusion reasoning no longer holds"
        )

    excluded_prefixes = {
        prefix for record in _territory_records() for prefix in _string_list(record, "postal_prefixes")
    }

    assert "07" not in excluded_prefixes, "the Balears are excluded from the TAI, which art. 3 does not do"
