"""Current-format, profile-scoped password custody contracts."""

from __future__ import annotations

from collections.abc import Callable
from functools import partial
from importlib import import_module
from types import ModuleType
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ._acceleration_receipt import (
        PROFILE_SESSION_KEYCHAIN_SERVICE,
        PROFILE_SESSION_SCHEMA_VERSION,
        PersistedProfileSession,
        ProfileSessionResumeOutcome,
        advance_persisted_profile_session_idle_deadline,
        advance_profile_session_idle_deadline,
        delete_profile_session,
        mint_profile_session,
        profile_session_path,
        resume_profile_session,
        unwrap_profile_session_dek,
        wrap_profile_session_dek,
    )
    from ._capsule import (
        PROFILE_CUSTODY_INVENTORY_MAX_ENTRIES,
        PROFILE_CUSTODY_INVENTORY_MAX_TOTAL_BYTES,
        PROFILE_CUSTODY_PROFILE_RECORD_MAX_BYTES,
        ProfileCustodyCapsuleSummaryWitness,
        ProfileCustodyInventory,
        ProfileCustodyInventoryEntry,
        inventory_committed_profile_custody_capsule,
        inventory_staged_profile_custody_capsule,
        list_current_profile_custody_capsule_ids,
        list_current_profile_custody_capsule_summary_witnesses,
        load_committed_profile_custody_data_file,
        load_committed_profile_custody_label_record,
        load_committed_profile_custody_summary_witness,
        load_committed_profile_password_material,
        load_staged_profile_custody_label_record,
        profile_custody_deletion_path,
        profile_custody_staging_path,
        publish_profile_custody_capsule,
        publish_staged_profile_custody_capsule,
        recognize_current_profile_capsule,
        remove_profile_custody_deletion_tombstone,
        rename_profile_custody_capsule_for_deletion,
        replace_committed_profile_custody_data_file,
        replace_committed_profile_custody_envelope,
        verify_profile_custody_deletion_marker,
        verify_profile_custody_deletion_tombstone,
        write_profile_custody_deletion_marker,
    )
    from ._capsule_discovery import (
        PROFILE_CUSTODY_RETIRED_BUCKET_MEMBER_PATHS,
        PROFILE_CUSTODY_RETIRED_KEYSTORE_MEMBER_PATHS,
        detect_retired_profile_custody_member_paths,
        refuse_retired_profile_custody_paths,
    )
    from ._capsule_records import (
        PROFILE_CUSTODY_COMMIT_MAX_BYTES,
        PROFILE_CUSTODY_COMMIT_SCHEMA_VERSION,
        PROFILE_CUSTODY_DELETION_FILENAME,
        PROFILE_CUSTODY_LABEL_FILENAME,
        PROFILE_CUSTODY_LABEL_MAX_BYTES,
        PROFILE_CUSTODY_LAYOUT_VERSION,
        ProfileCustodyCapsuleLabel,
        ProfileCustodyCommit,
        ProfileCustodyDeletionMarker,
        ProfileCustodyPasswordMaterial,
        parse_profile_custody_capsule_label,
        parse_profile_custody_commit,
    )
    from ._envelope import create_profile_custody_password_envelope
    from ._filesystem import (
        PROFILE_CUSTODY_COMMIT_FILENAME,
        PROFILE_CUSTODY_DATA_FILE_MAX_BYTES,
        clear_profile_custody_local_record,
        compare_and_clear_profile_custody_local_record,
        compare_and_replace_profile_custody_local_record,
        compare_and_replace_same_or_predecessor_profile_custody_local_record,
        ensure_profile_custody_local_directory,
        profile_custody_local_lock,
        profile_custody_root_lock,
        read_optional_profile_custody_local_record,
        read_profile_custody_local_record,
        write_profile_custody_local_record,
    )
    from ._kdf_supervision import (
        PROFILE_CUSTODY_KDF_CALIBRATION_VERSION,
        PROFILE_CUSTODY_KDF_SAMPLE_COUNT,
        PROFILE_CUSTODY_KDF_SAMPLE_DEADLINE_SECONDS,
        PROFILE_CUSTODY_KDF_TARGET_MAX_SECONDS,
        PROFILE_CUSTODY_KDF_TARGET_MIN_SECONDS,
        PROFILE_CUSTODY_KDF_TOTAL_DEADLINE_SECONDS,
        PROFILE_CUSTODY_KDF_WARMUP_COUNT,
        ProfileCustodyKdfCalibration,
        ProfileCustodyKdfRatchetProposal,
        ProfileCustodyKdfResources,
        ProfileCustodyUnlock,
        calibrate_profile_kdf,
        fixed_profile_kdf_fallback,
        profile_kdf_grid,
        profile_kdf_is_eligible,
        profile_kdf_lease,
        profile_kdf_resources,
        profile_password_wrap_aad,
        propose_profile_kdf_ratchet,
        unlock_profile_custody,
        unlock_profile_custody_password_material,
        unlock_profile_custody_recovery_material,
        wrap_profile_custody_password_material,
        wrap_profile_custody_recovery_material,
    )
    from ._label_head_models import (
        LABEL_HEAD_MAX_BYTES,
        ProfileLabelHead,
        ProfileLabelHeadPendingAdvance,
    )
    from ._label_head_repository import ProfileLabelHeadRepository
    from ._paths import profile_custody_path
    from ._records import (
        PROFILE_CUSTODY_ENVELOPE_MAX_BYTES,
        PROFILE_CUSTODY_ENVELOPE_SCHEMA_VERSION,
        PROFILE_CUSTODY_KDF_ITERATIONS,
        PROFILE_CUSTODY_KDF_MEMORY_MIB,
        PROFILE_CUSTODY_KDF_PARALLELISM,
        PROFILE_CUSTODY_PASSWORD_GENERATION_MAX,
        ProfileCustodyEnvelope,
        ProfileCustodyKdfParameters,
        ProfileCustodyWrappedDek,
        parse_profile_custody_envelope,
    )
    from ._recovery import (
        PROFILE_CUSTODY_RECOVERY_FILENAME,
        PROFILE_CUSTODY_RECOVERY_MAX_BYTES,
        PROFILE_CUSTODY_RECOVERY_SCHEMA_VERSION,
        ProfileCustodyRecoveryAad,
        ProfileCustodyRecoveryEnvelope,
        ProfileCustodyRecoveryUnlock,
        create_profile_custody_recovery_envelope,
        parse_profile_custody_recovery_envelope,
        profile_custody_recovery_aad,
        unlock_profile_custody_recovery,
    )
    from ._recovery_artifact import (
        PROFILE_CUSTODY_RECOVERY_ARTIFACT_MAX_BYTES,
        PROFILE_CUSTODY_RECOVERY_ARTIFACT_SCHEMA,
        ProfileCustodyRecoveryArtifact,
        ProfileCustodyRecoveryArtifactExportReceipt,
        ProfileCustodyRecoveryArtifactWarning,
        export_profile_custody_recovery_artifact,
        import_profile_custody_recovery_artifact,
        parse_profile_custody_recovery_artifact,
        refuse_hostile_recovery_artifact_destination,
        unlock_imported_profile_custody_recovery_artifact,
    )
    from ._sentinel import (
        PROFILE_CUSTODY_SENTINEL_FILENAME,
        PROFILE_CUSTODY_SENTINEL_MAX_BYTES,
        create_profile_custody_sentinel,
        write_profile_custody_sentinel,
    )
    from ._sentinel_contract import (
        ProfileCustodySentinelRecord,
        parse_profile_custody_sentinel_record,
        profile_custody_sentinel_aad,
        profile_custody_sentinel_aad_for,
        profile_custody_sentinel_plaintext,
        verify_profile_custody_sentinel,
    )
    from ._zeroise import zeroise
    from .errors import (
        ProfileCustodyConcurrentCapsuleChangeError,
        ProfileCustodyError,
        ProfileCustodyPasswordError,
        ProfileCustodyRecordError,
        ProfileCustodyRecoveryGuidance,
        ProfileCustodyRecoverySecretError,
        ProfileCustodyRefusal,
        ProfileCustodyRefusedError,
        WipeTypeError,
    )


# Name -> the one submodule that owns it. Binding these eagerly cost 1.02 s,
# nearly all of it the capsule machinery and its settings graph, and every
# importer of any sibling module paid it -- including the supervised
# key-derivation child, which runs one Argon2id hash and touches no capsule.
# Ownership is unchanged: every name still has exactly one canonical home and
# one import path. Only WHEN the owning submodule executes has moved.
_LAZY_EXPORTS: dict[str, str] = {
    "LABEL_HEAD_MAX_BYTES": "._label_head_models",
    "PROFILE_SESSION_KEYCHAIN_SERVICE": "._acceleration_receipt",
    "PROFILE_SESSION_SCHEMA_VERSION": "._acceleration_receipt",
    "PersistedProfileSession": "._acceleration_receipt",
    "ProfileSessionResumeOutcome": "._acceleration_receipt",
    "advance_persisted_profile_session_idle_deadline": "._acceleration_receipt",
    "advance_profile_session_idle_deadline": "._acceleration_receipt",
    "delete_profile_session": "._acceleration_receipt",
    "mint_profile_session": "._acceleration_receipt",
    "profile_session_path": "._acceleration_receipt",
    "resume_profile_session": "._acceleration_receipt",
    "unwrap_profile_session_dek": "._acceleration_receipt",
    "wrap_profile_session_dek": "._acceleration_receipt",
    "WipeTypeError": ".errors",
    "zeroise": "._zeroise",
    "PROFILE_CUSTODY_COMMIT_FILENAME": "._filesystem",
    "PROFILE_CUSTODY_COMMIT_MAX_BYTES": "._capsule_records",
    "PROFILE_CUSTODY_COMMIT_SCHEMA_VERSION": "._capsule_records",
    "PROFILE_CUSTODY_DELETION_FILENAME": "._capsule_records",
    "PROFILE_CUSTODY_DATA_FILE_MAX_BYTES": "._filesystem",
    "PROFILE_CUSTODY_ENVELOPE_MAX_BYTES": "._records",
    "PROFILE_CUSTODY_ENVELOPE_SCHEMA_VERSION": "._records",
    "PROFILE_CUSTODY_INVENTORY_MAX_ENTRIES": "._capsule",
    "PROFILE_CUSTODY_INVENTORY_MAX_TOTAL_BYTES": "._capsule",
    "PROFILE_CUSTODY_KDF_CALIBRATION_VERSION": "._kdf_supervision",
    "PROFILE_CUSTODY_KDF_ITERATIONS": "._records",
    "PROFILE_CUSTODY_KDF_MEMORY_MIB": "._records",
    "PROFILE_CUSTODY_KDF_PARALLELISM": "._records",
    "PROFILE_CUSTODY_KDF_SAMPLE_COUNT": "._kdf_supervision",
    "PROFILE_CUSTODY_KDF_SAMPLE_DEADLINE_SECONDS": "._kdf_supervision",
    "PROFILE_CUSTODY_KDF_TARGET_MAX_SECONDS": "._kdf_supervision",
    "PROFILE_CUSTODY_KDF_TARGET_MIN_SECONDS": "._kdf_supervision",
    "PROFILE_CUSTODY_KDF_TOTAL_DEADLINE_SECONDS": "._kdf_supervision",
    "PROFILE_CUSTODY_KDF_WARMUP_COUNT": "._kdf_supervision",
    "PROFILE_CUSTODY_LABEL_FILENAME": "._capsule_records",
    "PROFILE_CUSTODY_LABEL_MAX_BYTES": "._capsule_records",
    "PROFILE_CUSTODY_LAYOUT_VERSION": "._capsule_records",
    "PROFILE_CUSTODY_PASSWORD_GENERATION_MAX": "._records",
    "PROFILE_CUSTODY_PROFILE_RECORD_MAX_BYTES": "._capsule",
    "PROFILE_CUSTODY_RECOVERY_ARTIFACT_MAX_BYTES": "._recovery_artifact",
    "PROFILE_CUSTODY_RECOVERY_ARTIFACT_SCHEMA": "._recovery_artifact",
    "PROFILE_CUSTODY_RECOVERY_FILENAME": "._recovery",
    "PROFILE_CUSTODY_RECOVERY_MAX_BYTES": "._recovery",
    "PROFILE_CUSTODY_RECOVERY_SCHEMA_VERSION": "._recovery",
    "PROFILE_CUSTODY_RETIRED_BUCKET_MEMBER_PATHS": "._capsule_discovery",
    "PROFILE_CUSTODY_RETIRED_KEYSTORE_MEMBER_PATHS": "._capsule_discovery",
    "PROFILE_CUSTODY_SENTINEL_FILENAME": "._sentinel",
    "PROFILE_CUSTODY_SENTINEL_MAX_BYTES": "._sentinel",
    "ProfileCustodyCapsuleLabel": "._capsule_records",
    "ProfileCustodyCapsuleSummaryWitness": "._capsule",
    "ProfileCustodyCommit": "._capsule_records",
    "ProfileCustodyConcurrentCapsuleChangeError": ".errors",
    "ProfileCustodyDeletionMarker": "._capsule_records",
    "ProfileCustodyEnvelope": "._records",
    "ProfileCustodyError": ".errors",
    "ProfileCustodyInventory": "._capsule",
    "ProfileCustodyInventoryEntry": "._capsule",
    "ProfileCustodyKdfCalibration": "._kdf_supervision",
    "ProfileCustodyKdfParameters": "._records",
    "ProfileCustodyKdfRatchetProposal": "._kdf_supervision",
    "ProfileCustodyKdfResources": "._kdf_supervision",
    "ProfileCustodyPasswordError": ".errors",
    "ProfileCustodyPasswordMaterial": "._capsule_records",
    "ProfileCustodyRecordError": ".errors",
    "ProfileCustodyRecoverySecretError": ".errors",
    "ProfileCustodyRecoveryAad": "._recovery",
    "ProfileCustodyRecoveryArtifact": "._recovery_artifact",
    "ProfileCustodyRecoveryArtifactExportReceipt": "._recovery_artifact",
    "ProfileCustodyRecoveryArtifactWarning": "._recovery_artifact",
    "ProfileCustodyRecoveryEnvelope": "._recovery",
    "ProfileCustodyRecoveryGuidance": ".errors",
    "ProfileCustodyRecoveryUnlock": "._recovery",
    "ProfileCustodyRefusal": ".errors",
    "ProfileCustodyRefusedError": ".errors",
    "ProfileCustodySentinelRecord": "._sentinel_contract",
    "ProfileCustodyUnlock": "._kdf_supervision",
    "ProfileCustodyWrappedDek": "._records",
    "ProfileLabelHead": "._label_head_models",
    "ProfileLabelHeadPendingAdvance": "._label_head_models",
    "ProfileLabelHeadRepository": "._label_head_repository",
    "calibrate_profile_kdf": "._kdf_supervision",
    "clear_profile_custody_local_record": "._filesystem",
    "compare_and_clear_profile_custody_local_record": "._filesystem",
    "compare_and_replace_profile_custody_local_record": "._filesystem",
    "compare_and_replace_same_or_predecessor_profile_custody_local_record": "._filesystem",
    "create_profile_custody_password_envelope": "._envelope",
    "create_profile_custody_recovery_envelope": "._recovery",
    "create_profile_custody_sentinel": "._sentinel",
    "detect_retired_profile_custody_member_paths": "._capsule_discovery",
    "ensure_profile_custody_local_directory": "._filesystem",
    "export_profile_custody_recovery_artifact": "._recovery_artifact",
    "fixed_profile_kdf_fallback": "._kdf_supervision",
    "import_profile_custody_recovery_artifact": "._recovery_artifact",
    "inventory_committed_profile_custody_capsule": "._capsule",
    "inventory_staged_profile_custody_capsule": "._capsule",
    "list_current_profile_custody_capsule_ids": "._capsule",
    "list_current_profile_custody_capsule_summary_witnesses": "._capsule",
    "load_committed_profile_custody_data_file": "._capsule",
    "load_committed_profile_custody_label_record": "._capsule",
    "load_committed_profile_custody_summary_witness": "._capsule",
    "load_committed_profile_password_material": "._capsule",
    "load_staged_profile_custody_label_record": "._capsule",
    "parse_profile_custody_capsule_label": "._capsule_records",
    "parse_profile_custody_commit": "._capsule_records",
    "parse_profile_custody_envelope": "._records",
    "parse_profile_custody_recovery_artifact": "._recovery_artifact",
    "parse_profile_custody_recovery_envelope": "._recovery",
    "parse_profile_custody_sentinel_record": "._sentinel_contract",
    "profile_custody_deletion_path": "._capsule",
    "profile_custody_local_lock": "._filesystem",
    "profile_custody_path": "._paths",
    "profile_custody_recovery_aad": "._recovery",
    "profile_custody_root_lock": "._filesystem",
    "profile_custody_sentinel_aad": "._sentinel_contract",
    "profile_custody_sentinel_aad_for": "._sentinel_contract",
    "profile_custody_sentinel_plaintext": "._sentinel_contract",
    "profile_custody_staging_path": "._capsule",
    "profile_kdf_grid": "._kdf_supervision",
    "profile_kdf_is_eligible": "._kdf_supervision",
    "profile_kdf_lease": "._kdf_supervision",
    "profile_kdf_resources": "._kdf_supervision",
    "profile_password_wrap_aad": "._kdf_supervision",
    "propose_profile_kdf_ratchet": "._kdf_supervision",
    "publish_profile_custody_capsule": "._capsule",
    "publish_staged_profile_custody_capsule": "._capsule",
    "read_optional_profile_custody_local_record": "._filesystem",
    "read_profile_custody_local_record": "._filesystem",
    "recognize_current_profile_capsule": "._capsule",
    "refuse_hostile_recovery_artifact_destination": "._recovery_artifact",
    "refuse_retired_profile_custody_paths": "._capsule_discovery",
    "remove_profile_custody_deletion_tombstone": "._capsule",
    "rename_profile_custody_capsule_for_deletion": "._capsule",
    "replace_committed_profile_custody_data_file": "._capsule",
    "replace_committed_profile_custody_envelope": "._capsule",
    "unlock_imported_profile_custody_recovery_artifact": "._recovery_artifact",
    "unlock_profile_custody": "._kdf_supervision",
    "unlock_profile_custody_password_material": "._kdf_supervision",
    "unlock_profile_custody_recovery_material": "._kdf_supervision",
    "unlock_profile_custody_recovery": "._recovery",
    "verify_profile_custody_deletion_marker": "._capsule",
    "verify_profile_custody_deletion_tombstone": "._capsule",
    "verify_profile_custody_sentinel": "._sentinel_contract",
    "wrap_profile_custody_password_material": "._kdf_supervision",
    "wrap_profile_custody_recovery_material": "._kdf_supervision",
    "write_profile_custody_deletion_marker": "._capsule",
    "write_profile_custody_local_record": "._filesystem",
    "write_profile_custody_sentinel": "._sentinel",
}


# Every loader target is a closed literal from the map above.  The attribute
# name selects one of these pre-bound loaders; it never becomes an import path.
_LAZY_MODULE_LOADERS: dict[str, Callable[[], ModuleType]] = {
    module_path: partial(import_module, module_path, __name__) for module_path in frozenset(_LAZY_EXPORTS.values())
}


def __getattr__(name: str) -> object:
    """Resolve one public name by importing only the submodule that owns it.

    The resolved value is written into module globals, so only the first
    access to a name goes through this hook; every later one is an ordinary
    global lookup with no import machinery in the path.
    """
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    loader = _LAZY_MODULE_LOADERS.get(module_name)
    if loader is None:
        raise RuntimeError(f"missing lazy loader for {module_name!r}")
    value = getattr(loader(), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Report the full public surface, including names not yet resolved."""
    return sorted(set(__all__) | set(globals()))


__all__ = [
    "LABEL_HEAD_MAX_BYTES",
    "PROFILE_CUSTODY_COMMIT_FILENAME",
    "PROFILE_CUSTODY_COMMIT_MAX_BYTES",
    "PROFILE_CUSTODY_COMMIT_SCHEMA_VERSION",
    "PROFILE_CUSTODY_DATA_FILE_MAX_BYTES",
    "PROFILE_CUSTODY_DELETION_FILENAME",
    "PROFILE_CUSTODY_ENVELOPE_MAX_BYTES",
    "PROFILE_CUSTODY_ENVELOPE_SCHEMA_VERSION",
    "PROFILE_CUSTODY_INVENTORY_MAX_ENTRIES",
    "PROFILE_CUSTODY_INVENTORY_MAX_TOTAL_BYTES",
    "PROFILE_CUSTODY_KDF_CALIBRATION_VERSION",
    "PROFILE_CUSTODY_KDF_ITERATIONS",
    "PROFILE_CUSTODY_KDF_MEMORY_MIB",
    "PROFILE_CUSTODY_KDF_PARALLELISM",
    "PROFILE_CUSTODY_KDF_SAMPLE_COUNT",
    "PROFILE_CUSTODY_KDF_SAMPLE_DEADLINE_SECONDS",
    "PROFILE_CUSTODY_KDF_TARGET_MAX_SECONDS",
    "PROFILE_CUSTODY_KDF_TARGET_MIN_SECONDS",
    "PROFILE_CUSTODY_KDF_TOTAL_DEADLINE_SECONDS",
    "PROFILE_CUSTODY_KDF_WARMUP_COUNT",
    "PROFILE_CUSTODY_LABEL_FILENAME",
    "PROFILE_CUSTODY_LABEL_MAX_BYTES",
    "PROFILE_CUSTODY_LAYOUT_VERSION",
    "PROFILE_CUSTODY_PASSWORD_GENERATION_MAX",
    "PROFILE_CUSTODY_PROFILE_RECORD_MAX_BYTES",
    "PROFILE_CUSTODY_RECOVERY_ARTIFACT_MAX_BYTES",
    "PROFILE_CUSTODY_RECOVERY_ARTIFACT_SCHEMA",
    "PROFILE_CUSTODY_RECOVERY_FILENAME",
    "PROFILE_CUSTODY_RECOVERY_MAX_BYTES",
    "PROFILE_CUSTODY_RECOVERY_SCHEMA_VERSION",
    "PROFILE_CUSTODY_RETIRED_BUCKET_MEMBER_PATHS",
    "PROFILE_CUSTODY_RETIRED_KEYSTORE_MEMBER_PATHS",
    "PROFILE_CUSTODY_SENTINEL_FILENAME",
    "PROFILE_CUSTODY_SENTINEL_MAX_BYTES",
    "PROFILE_SESSION_KEYCHAIN_SERVICE",
    "PROFILE_SESSION_SCHEMA_VERSION",
    "PersistedProfileSession",
    "ProfileCustodyCapsuleLabel",
    "ProfileCustodyCapsuleSummaryWitness",
    "ProfileCustodyCommit",
    "ProfileCustodyConcurrentCapsuleChangeError",
    "ProfileCustodyDeletionMarker",
    "ProfileCustodyEnvelope",
    "ProfileCustodyError",
    "ProfileCustodyInventory",
    "ProfileCustodyInventoryEntry",
    "ProfileCustodyKdfCalibration",
    "ProfileCustodyKdfParameters",
    "ProfileCustodyKdfRatchetProposal",
    "ProfileCustodyKdfResources",
    "ProfileCustodyPasswordError",
    "ProfileCustodyPasswordMaterial",
    "ProfileCustodyRecordError",
    "ProfileCustodyRecoveryAad",
    "ProfileCustodyRecoveryArtifact",
    "ProfileCustodyRecoveryArtifactExportReceipt",
    "ProfileCustodyRecoveryArtifactWarning",
    "ProfileCustodyRecoveryEnvelope",
    "ProfileCustodyRecoveryGuidance",
    "ProfileCustodyRecoverySecretError",
    "ProfileCustodyRecoveryUnlock",
    "ProfileCustodyRefusal",
    "ProfileCustodyRefusedError",
    "ProfileCustodySentinelRecord",
    "ProfileCustodyUnlock",
    "ProfileCustodyWrappedDek",
    "ProfileLabelHead",
    "ProfileLabelHeadPendingAdvance",
    "ProfileLabelHeadRepository",
    "ProfileSessionResumeOutcome",
    "WipeTypeError",
    "advance_persisted_profile_session_idle_deadline",
    "advance_profile_session_idle_deadline",
    "calibrate_profile_kdf",
    "clear_profile_custody_local_record",
    "compare_and_clear_profile_custody_local_record",
    "compare_and_replace_profile_custody_local_record",
    "compare_and_replace_same_or_predecessor_profile_custody_local_record",
    "create_profile_custody_password_envelope",
    "create_profile_custody_recovery_envelope",
    "create_profile_custody_sentinel",
    "delete_profile_session",
    "detect_retired_profile_custody_member_paths",
    "ensure_profile_custody_local_directory",
    "export_profile_custody_recovery_artifact",
    "fixed_profile_kdf_fallback",
    "import_profile_custody_recovery_artifact",
    "inventory_committed_profile_custody_capsule",
    "inventory_staged_profile_custody_capsule",
    "list_current_profile_custody_capsule_ids",
    "list_current_profile_custody_capsule_summary_witnesses",
    "load_committed_profile_custody_data_file",
    "load_committed_profile_custody_label_record",
    "load_committed_profile_custody_summary_witness",
    "load_committed_profile_password_material",
    "load_staged_profile_custody_label_record",
    "mint_profile_session",
    "parse_profile_custody_capsule_label",
    "parse_profile_custody_commit",
    "parse_profile_custody_envelope",
    "parse_profile_custody_recovery_artifact",
    "parse_profile_custody_recovery_envelope",
    "parse_profile_custody_sentinel_record",
    "profile_custody_deletion_path",
    "profile_custody_local_lock",
    "profile_custody_path",
    "profile_custody_recovery_aad",
    "profile_custody_root_lock",
    "profile_custody_sentinel_aad",
    "profile_custody_sentinel_aad_for",
    "profile_custody_sentinel_plaintext",
    "profile_custody_staging_path",
    "profile_kdf_grid",
    "profile_kdf_is_eligible",
    "profile_kdf_lease",
    "profile_kdf_resources",
    "profile_password_wrap_aad",
    "profile_session_path",
    "propose_profile_kdf_ratchet",
    "publish_profile_custody_capsule",
    "publish_staged_profile_custody_capsule",
    "read_optional_profile_custody_local_record",
    "read_profile_custody_local_record",
    "recognize_current_profile_capsule",
    "refuse_hostile_recovery_artifact_destination",
    "refuse_retired_profile_custody_paths",
    "remove_profile_custody_deletion_tombstone",
    "rename_profile_custody_capsule_for_deletion",
    "replace_committed_profile_custody_data_file",
    "replace_committed_profile_custody_envelope",
    "resume_profile_session",
    "unlock_imported_profile_custody_recovery_artifact",
    "unlock_profile_custody",
    "unlock_profile_custody_password_material",
    "unlock_profile_custody_recovery",
    "unlock_profile_custody_recovery_material",
    "unwrap_profile_session_dek",
    "verify_profile_custody_deletion_marker",
    "verify_profile_custody_deletion_tombstone",
    "verify_profile_custody_sentinel",
    "wrap_profile_custody_password_material",
    "wrap_profile_custody_recovery_material",
    "wrap_profile_session_dek",
    "write_profile_custody_deletion_marker",
    "write_profile_custody_local_record",
    "write_profile_custody_sentinel",
    "zeroise",
]
