[[revisions."2024-y-siguientes".export_layouts]]
id = "modelo-200-fichero-boe"

[[revisions."2024-y-siguientes".export_layouts.records]]
id = "modelo-200-page-026e"

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-026e-casilla-03114"
offset = 2070
length = 17
kind = "casilla"
casilla_id = "03114"
data_type = "money"
required = false
padding = "left_zero"
justification = "right"
signed = true
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

[[revisions."2024-y-siguientes".export_layouts.records.fields]]
id = "modelo-200-page-026e-casilla-03111"
offset = 2087
length = 17
kind = "casilla"
casilla_id = "03111"
data_type = "money"
required = false
padding = "left_zero"
justification = "right"
signed = true
legal_refs = ["ley-27-2014:art-40", "ley-27-2014:art-41", "ley-27-2014:art-29", "ley-27-2014:art-30", "ley-27-2014:art-39", "ley-27-2014:art-19", "ley-27-2014:art-36", "ley-27-2014:art-100", "rd-634-2015:art-3", "ley-27-2014:art-12", "ley-27-2014:art-15", "ley-27-2014:art-21", "ley-27-2014:art-22", "ley-27-2014:art-31", "ley-27-2014:art-32", "ley-27-2014:art-13", "ley-27-2014:art-16", "ley-27-2014:art-25", "ley-27-2014:art-26"]
source_refs = ["aeat-dr-200-2025"]

