"""Independently adjudicated semantic policy partition for live callbacks.

The oracle normally keys by callback ownership, not command path. Generated
callbacks can share one qualname across distinct live nodes, so every repeated
owner explicitly adds its live path. This preserves one adjudicated row per
node and makes a future helper-generated group enlarge the exact set. Changes
require semantic review, never snapshot refresh.
"""

from __future__ import annotations

PolicySignature = tuple[tuple[str, ...], tuple[str, ...], str, str, bool, bool, bool]

REPEATED_CALLBACK_OWNERS = frozenset(
    {
        "cadrumo.application.wizard._commands:build_wizard_command.<locals>._command",
        "cadrumo.entrypoints.cli._app_execution_policies:declare_metadata_group.<locals>._metadata_group",
        "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group",
        "cadrumo.entrypoints.cli._ledger_execution_policies:declare_metadata_group.<locals>._metadata_group",
        "cadrumo.entrypoints.cli._modelo_execution_policies:declare_metadata_group.<locals>._metadata_group",
    }
)

EXPECTED_CALLBACK_POLICY: dict[str, PolicySignature] = {
    "cadrumo.application.wizard._commands:build_wizard_command.<locals>._command @ aeat config profile create": (
        ("profile-custody",),
        ("local-state",),
        "local-io",
        "bootstrap-root",
        False,
        False,
        False,
    ),
    "cadrumo.application.wizard._commands:build_wizard_command.<locals>._command @ aeat config profile edit": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_diagnostics:_diagnostics_root": (
        ("local-storage",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_diagnostics:diagnostics_errors": (
        ("local-storage",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_diagnostics:diagnostics_latency": (
        ("local-storage",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_diagnostics:diagnostics_llm_usage": (
        ("local-storage",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_diagnostics:diagnostics_run_health": (
        ("local-storage",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_diagnostics:diagnostics_runs": (
        ("local-storage",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_diagnostics_telemetry:diagnostics_telemetry_flush": (
        ("local-storage",),
        ("local-state",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_diagnostics_telemetry:diagnostics_telemetry_status": (
        ("local-storage",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app diagnostics telemetry": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app live": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app live borrador": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app live borrador 100": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app live deudas": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app live expedientes": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app live filed": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app live iva-wallet": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app live justificante": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app live notifications": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app live notifications document": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app live portals": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app live verify": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app overview": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app registry": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app registry citations": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app registry manuals": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app review": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live:filed_discover_cmd": (
        ("encrypted-facts", "network"),
        ("network",),
        "external-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live:filed_list_cmd": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live:filed_pull_all_cmd": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live:filed_pull_cmd": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live:filed_pull_sources_cmd": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live:iva_wallet_history_cmd": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live:iva_wallet_pull_cmd": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live:iva_wallet_pull_evidence_cmd": (
        ("browser", "encrypted-facts", "subprocess"),
        ("browser", "local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live:iva_wallet_pull_history_cmd": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_borrador_cli:register_borrador_commands.<locals>.borrador_100_latest": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_borrador_cli:register_borrador_commands.<locals>.borrador_100_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_borrador_cli:register_borrador_commands.<locals>.borrador_100_show": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_deudas_cli:deudas_latest": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_deudas_cli:deudas_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_deudas_cli:deudas_view": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_expedientes_cli:expedientes_latest": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_expedientes_cli:expedientes_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_expedientes_cli:expedientes_pull": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_expedientes_cli:expedientes_show": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_justificante_cli:justificante_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_justificante_cli:justificante_pull": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_justificante_cli:justificante_view": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_notifications_cli:notifications_document_history": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_notifications_cli:notifications_document_pull": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_notifications_cli:notifications_document_view": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_notifications_cli:notifications_latest": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_notifications_cli:notifications_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_notifications_cli:notifications_pull": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_notifications_cli:notifications_show": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_portals_cli:portals_list": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_portals_cli:portals_show": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_verify_cli:verify_latest": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_verify_cli:verify_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_verify_cli:verify_nif_iva": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_verify_cli:verify_show": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_live_verify_cli:verify_tgvi": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_maintenance:app_maintenance_reconcile": (
        ("profile-custody",),
        ("local-state",),
        "local-io",
        "profile-bound",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_maintenance:maintenance": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._app_quickfile:quickfile": (
        ("calculation", "encrypted-facts", "filing"),
        ("local-state",),
        "compute",
        "profile-bound",
        False,
        True,
        False,
    ),
    "cadrumo.entrypoints.cli._bienes_inversion_cli:bienes_inversion_declare": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._bienes_inversion_cli:bienes_inversion_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._apoderado:apoderado_check": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._apoderado:apoderado_clear": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._apoderado:apoderado_configure": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._apoderado:apoderado_scopes_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._apoderado:apoderado_status": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._archive_cli:register_archive_commands.<locals>.archive_export": (
        ("profile-custody",),
        ("local-state",),
        "local-io",
        "bootstrap-root",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._archive_cli:register_archive_commands.<locals>.archive_inspect": (
        ("profile-custody",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._auth:auth_configure": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._auth:auth_login": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._auth:auth_logout": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._auth:auth_providers": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._auth:auth_reset": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._auth:auth_status": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._auth:auth_test": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._auth_diagnostics:auth_diagnostics_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._auth_diagnostics:auth_diagnostics_report": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._auth_diagnostics:auth_diagnostics_show": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._bucket_history:register_bucket_history_commands.<locals>.profile_history": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._capabilities_cli:_register_set.<locals>.capabilities_set": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._capabilities_cli:_register_show.<locals>.capabilities_show": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._censo_file:censo_file": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._censo_file:censo_pull": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._certificate:certificate_check": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._certificate:certificate_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._certificate:certificate_register": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._certificate:certificate_remove": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._certificate:certificate_secret_remove": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._certificate:certificate_secret_set": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._certificate:certificate_select": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._check_cli:register.<locals>.config_check": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._collab:collab_recipient_add": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._collab:collab_recipient_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._collab:collab_recipient_remove": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._complete_setup_cli:register.<locals>.profile_complete_setup": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._custody:_register_login_command.<locals>.config_login": (
        ("profile-custody",),
        ("local-state",),
        "local-io",
        "bootstrap-root",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._custody:_register_logout_command.<locals>.config_logout": (
        ("profile-custody",),
        ("local-state",),
        "local-io",
        "bootstrap-root",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._descendiente:descendiente_add": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._descendiente:descendiente_door": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._descendiente:descendiente_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._descendiente:descendiente_remove": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config auth": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config auth apoderado": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config auth apoderado scopes": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config auth certificate": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config auth certificate secret": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config auth diagnostics": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config collab": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config collab recipient": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config google": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config google credential-source": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config google folder": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config google sync": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config google sync calc": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config passphrase": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config profile": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config profile archive": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config profile capabilities": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config profile censo": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config provision": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config repair integrity": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config reset": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat config storage": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._google:google_login": (
        ("encrypted-facts", "google"),
        ("google", "local-state"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._google:google_logout": (
        ("encrypted-facts", "google"),
        ("google", "local-state"),
        "external-io",
        "profile-bound",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._google:google_register": (
        ("encrypted-facts", "google"),
        ("google", "local-state"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._google:google_status": (
        ("encrypted-facts", "google"),
        ("google",),
        "external-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._google:google_sync_probe": (
        ("encrypted-facts", "google"),
        ("google",),
        "external-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._google:google_sync_push": (
        ("encrypted-facts", "google"),
        ("google", "local-state"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._google_credential_source_cli:google_credential_source_set": (
        ("encrypted-facts", "google"),
        ("google", "local-state"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._google_credential_source_cli:google_credential_source_show": (
        ("encrypted-facts", "google"),
        ("google",),
        "external-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._google_folder:register_google_folder_commands.<locals>.google_folder_get": (
        ("encrypted-facts", "google"),
        ("google",),
        "external-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._google_folder:register_google_folder_commands.<locals>.google_folder_set": (
        ("encrypted-facts", "google"),
        ("google", "local-state"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._google_sync_calc:google_sync_calc_compute": (
        ("calculation", "encrypted-facts", "google"),
        ("google", "local-state"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._google_sync_calc:google_sync_calc_export": (
        ("calculation", "encrypted-facts", "filing", "google"),
        ("google", "local-state"),
        "external-io",
        "profile-bound",
        False,
        True,
        False,
    ),
    "cadrumo.entrypoints.cli._config._google_sync_calc:google_sync_calc_pull": (
        ("calculation", "encrypted-facts", "google"),
        ("google", "local-state"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._google_sync_calc:google_sync_calc_verify": (
        ("calculation", "encrypted-facts", "google"),
        ("google",),
        "external-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._passphrase:register_passphrase_commands.<locals>.passphrase_change": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._profile_delete:register_profile_delete_command.<locals>.config_profile_delete": (
        ("profile-custody",),
        ("local-state",),
        "local-io",
        "bootstrap-root",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._profile_inspect:_register_preflight_command.<locals>.config_profile_preflight": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._profile_inspect:_register_show_command.<locals>.config_profile_show": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._profile_inspect:_register_validate_command.<locals>.config_profile_validate": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._provision_cli:register_provision_commands.<locals>.provision_pull": (
        ("network",),
        ("local-state", "network"),
        "external-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._provision_cli:register_provision_commands.<locals>.provision_report": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._provision_cli:register_provision_commands.<locals>.provision_verify": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._repair_cli:_register_repair_connectivity_command.<locals>.repair_connectivity": (
        ("browser",),
        ("browser",),
        "interactive",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._repair_cli:_register_repair_integrity_commands.<locals>.repair_integrity_objects": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._repair_cli:_register_repair_integrity_commands.<locals>.repair_integrity_registry": (
        ("calculation",),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._repair_cli:_register_repair_logs_command.<locals>.repair_logs": (
        ("state-free",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._repair_cli:_register_repair_quarantine_command.<locals>.repair_quarantine": (
        ("profile-custody",),
        ("local-state",),
        "local-io",
        "bootstrap-root",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._repair_cli:_register_repair_reset_progress_command.<locals>.repair_reset_progress": (
        ("profile-custody",),
        ("local-state",),
        "local-io",
        "bootstrap-root",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._repair_cli:_register_repair_root_callback.<locals>.repair": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._repair_profile:register_repair_profile_command.<locals>.repair_profile": (
        ("profile-custody",),
        ("local-state",),
        "local-io",
        "bootstrap-root",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._reset_cli:config_reset_resume": (
        ("profile-custody",),
        ("local-state",),
        "local-io",
        "bootstrap-root",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._reset_cli:config_reset_start": (
        ("profile-custody",),
        ("local-state",),
        "local-io",
        "bootstrap-root",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._reset_cli:config_reset_status_command": (
        ("profile-custody",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._restore_cli:register_restore_commands.<locals>.profile_restore": (
        ("profile-custody",),
        ("local-state",),
        "local-io",
        "bootstrap-root",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._storage_cli:config_storage_check": (
        ("profile-custody",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._storage_cli:config_storage_init": (
        ("profile-custody",),
        ("local-state",),
        "local-io",
        "bootstrap-root",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._storage_cli:config_storage_list": (
        ("profile-custody",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._storage_cli:config_storage_reclaim": (
        ("profile-custody",),
        ("local-state",),
        "local-io",
        "bootstrap-root",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config._storage_cli:config_storage_show": (
        ("profile-custody",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config:config_list": (
        ("profile-custody",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config:config_root": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._config:config_status": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger:ledger_add": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger:ledger_allocate": (
        ("calculation", "encrypted-facts"),
        ("local-state",),
        "compute",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger:ledger_classify": (
        ("calculation", "encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger:ledger_link": (
        ("calculation", "encrypted-facts"),
        ("local-state",),
        "compute",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger:ledger_update": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_business_invoice_cli:invoice_add": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_business_invoice_cli:invoice_import": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_business_invoice_cli:invoice_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_business_invoice_cli:invoice_remove": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_business_invoice_cli:invoice_update": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_business_invoice_cli:invoice_view": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_business_invoice_cli:invoice_wizard": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_counterparty_cli:counterparty_confirm": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_counterparty_cli:counterparty_show": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_counterparty_cli:counterparty_withdraw": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_evidence_batch_cli:register_evidence_batch_command.<locals>.evidence_batch": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_evidence_cli:_register_evidence_add_command.<locals>.evidence_add": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_evidence_cli:_register_attachment_review_commands.<locals>.attachment_queue": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_evidence_cli:_register_attachment_review_commands.<locals>.attachment_view": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_evidence_cli:_register_evidence_confirm_command.<locals>.evidence_confirm": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_evidence_cli:_register_evidence_extract_command.<locals>.evidence_extract": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_evidence_cli:_register_evidence_list_command.<locals>.evidence_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_evidence_cli:_register_evidence_remove_command.<locals>.evidence_remove": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_evidence_cli:_register_evidence_update_command.<locals>.evidence_update": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_evidence_cli:_register_evidence_view_command.<locals>.evidence_view": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_evidence_consent_cli:_register_consent_list_command.<locals>.consent_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_evidence_consent_cli:_register_consent_rederive_command.<locals>.consent_rederive": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_evidence_review_cli:_register_review_list_command.<locals>.review_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_evidence_review_cli:_register_review_show_command.<locals>.review_show": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app ledger": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app ledger bienes-inversion": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app ledger counterparty": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app ledger evidence": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app ledger evidence consent": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app ledger evidence review": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app ledger inventory": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app ledger inventory movement": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app ledger inventory valuation": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app ledger invoice": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app ledger prorrata": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app ledger ratios": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app ledger rule": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_import_cli:register_import_commands.<locals>.ledger_import": (
        ("encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_inventory_cli:inventory_create": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_inventory_cli:inventory_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_inventory_cli:inventory_movement_add": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_inventory_cli:inventory_valuation_preview": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_lifecycle_cli:ledger_archive": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_lifecycle_cli:ledger_attach": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_lifecycle_cli:ledger_detach": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_lifecycle_cli:ledger_doclink": (
        ("encrypted-facts", "google"),
        ("google", "local-state"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_lifecycle_cli:ledger_exclude": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_lifecycle_cli:ledger_merge": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_lifecycle_cli:ledger_pull_folder": (
        ("encrypted-facts", "google"),
        ("google", "local-state"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_lifecycle_cli:ledger_remove": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_lifecycle_cli:ledger_reset": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_lifecycle_cli:ledger_restore": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_lifecycle_cli:ledger_split": (
        ("calculation", "encrypted-facts", "network"),
        ("local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_lifecycle_cli:ledger_stash": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_ratios_cli:ratios_eligible": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_ratios_cli:ratios_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_ratios_cli:ratios_set": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_ratios_cli:ratios_unset": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_ratios_cli:ratios_validate": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_read_cli:_register_ledger_categories_command.<locals>.ledger_categories": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_read_cli:_register_ledger_check_command.<locals>.ledger_check": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_read_cli:_register_ledger_export_command.<locals>.ledger_export": (
        ("encrypted-facts", "filing"),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        True,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_read_cli:_register_ledger_history_command.<locals>.ledger_history": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_read_cli:_register_ledger_list_command.<locals>.ledger_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_read_cli:_register_ledger_llm_diagnostics_command.<locals>.ledger_llm_diagnostics": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_read_cli:_register_ledger_preflight_command.<locals>.ledger_preflight": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_read_cli:_register_ledger_status_command.<locals>.ledger_status": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_read_cli:_register_ledger_track_command.<locals>.ledger_track": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_read_cli:_register_ledger_view_command.<locals>.ledger_view": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_review_cli:register_ledger_review_command.<locals>.ledger_review": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_rules_cli:rule_add": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_rules_cli:rule_apply": (
        ("calculation", "encrypted-facts"),
        ("local-state",),
        "compute",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._ledger_rules_cli:rule_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo:modelo_history": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo:work_amend": (
        ("calculation", "encrypted-facts"),
        ("local-state",),
        "compute",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo:work_compare_taxation": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo:work_history": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_aggregate_cli:register_aggregate_commands.<locals>.aggregate_modelo": (
        ("calculation", "encrypted-facts"),
        ("local-state",),
        "compute",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_amend_wizard_cli:register_amend_wizard_commands.<locals>.work_amend_wizard": (
        ("calculation", "encrypted-facts"),
        ("local-state",),
        "interactive",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_audit_cli:audit_check": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_audit_cli:audit_export": (
        ("encrypted-facts", "filing"),
        ("local-state",),
        "compute",
        "profile-bound",
        False,
        True,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_audit_cli:audit_show": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_discovery_cli:_register_bindings_list_command.<locals>.bindings_list": (
        ("encrypted-facts", "registry"),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_discovery_cli:_register_bindings_resolve_command.<locals>.bindings_resolve": (
        ("encrypted-facts", "registry"),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_discovery_cli:_register_casilla_command.<locals>.casilla": (
        ("registry",),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_discovery_cli:_register_casillas_command.<locals>.casillas": (
        ("registry",),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_discovery_cli:_register_describe_command.<locals>.describe_modelo": (
        ("registry",),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_discovery_cli:_register_formulas_command.<locals>.formulas": (
        ("registry",),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_discovery_cli:_register_list_command.<locals>.list_modelos": (
        ("registry",),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_discovery_cli:_register_requires_command.<locals>.requires": (
        ("encrypted-facts", "registry"),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_discovery_cli:_register_support_matrix_command.<locals>.support_matrix": (
        ("registry",),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app modelo": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app modelo audit": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app modelo bindings": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app modelo filing-record": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app modelo iva-wallet": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app modelo m036": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app modelo m145": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app modelo reconcile": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app modelo review-package": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app modelo verification-report": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_execution_policies:declare_metadata_group.<locals>._metadata_group @ aeat app modelo work": (
        ("state-free",),
        ("none",),
        "metadata",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_export_cli:register_export_commands.<locals>.modelo_export_verb": (
        ("encrypted-facts", "filing"),
        ("local-state",),
        "compute",
        "profile-bound",
        False,
        True,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_iva_wallet_cli:_register_iva_wallet_balance_command.<locals>.iva_wallet_balance_cmd": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_iva_wallet_cli:_register_iva_wallet_correct_command.<locals>.iva_wallet_correct_cmd": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_iva_wallet_cli:_register_iva_wallet_override_command.<locals>.iva_wallet_override_cmd": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_iva_wallet_cli:_register_iva_wallet_seed_command.<locals>.iva_wallet_seed_cmd": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_m036_cli:_register_m036_readback_commands.<locals>.m036_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_m036_cli:_register_m036_readback_commands.<locals>.m036_view": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_m036_cli:register_m036_commands.<locals>.m036_alta": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_m036_cli:register_m036_commands.<locals>.m036_baja": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_m036_cli:register_m036_commands.<locals>.m036_modificacion": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_m145_cli:_register_m145_transition_commands.<locals>.m145_mark_delivered_to_payer": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_m145_cli:_register_m145_transition_commands.<locals>.m145_mark_locally_completed": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_m145_cli:register_m145_communication_commands.<locals>.m145_create": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_m145_cli:register_m145_communication_commands.<locals>.m145_export": (
        ("encrypted-facts", "filing"),
        ("local-state",),
        "compute",
        "profile-bound",
        False,
        True,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_m145_cli:register_m145_communication_commands.<locals>.m145_validate": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_maritime_cli:register_maritime_commands.<locals>.work_preview_maritime_exemption": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_projection_cli:_register_modelo_compare_command.<locals>.modelo_compare": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_projection_cli:_register_modelo_project_command.<locals>.modelo_project": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_readiness_cli:register_readiness_commands.<locals>.modelo_readiness": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_reconcile_cli:reconcile_file_verb": (
        ("encrypted-facts", "filing"),
        ("local-state",),
        "compute",
        "profile-bound",
        False,
        True,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_reconcile_cli:reconcile_history_verb": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_reconcile_cli:reconcile_pull_verb": (
        ("browser", "encrypted-facts", "registry"),
        ("browser", "local-state", "network"),
        "external-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_records_cli:filing_record_import": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_records_cli:filing_record_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_records_cli:filing_record_observe_local": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_records_cli:filing_record_show": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_records_cli:verification_report_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_records_cli:verification_report_show": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_review_package_cli:review_package_build": (
        ("calculation", "encrypted-facts"),
        ("local-state",),
        "compute",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_review_package_cli:review_package_counter_sign": (
        ("crypto", "encrypted-facts"),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_review_package_cli:review_package_decrypt": (
        ("crypto", "encrypted-facts"),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_review_package_cli:review_package_encrypt_feedback": (
        ("crypto", "encrypted-facts"),
        ("local-state",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_review_package_cli:review_package_encrypt_for_recipient": (
        ("crypto", "encrypted-facts"),
        ("local-state",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_review_package_cli:review_package_import_feedback": (
        ("crypto", "encrypted-facts"),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_review_package_cli:review_package_sign": (
        ("crypto", "encrypted-facts"),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_review_package_cli:review_package_verify": (
        ("crypto",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_review_package_cli:review_package_verify_receipt": (
        ("crypto",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_review_package_cli:review_package_verify_signature": (
        ("crypto",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_work_calculate_cli:register_work_calculate_commands.<locals>.work_calculate": (
        ("calculation", "encrypted-facts"),
        ("local-state",),
        "compute",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_work_lifecycle_cli:_register_work_create_command.<locals>.work_create": (
        ("encrypted-facts", "registry"),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_work_lifecycle_cli:_register_work_discard_command.<locals>.work_discard": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        True,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_work_lifecycle_cli:_register_work_list_command.<locals>.work_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_work_lifecycle_cli:_register_work_rename_command.<locals>.work_rename": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_work_lifecycle_cli:_register_work_status_command.<locals>.work_status": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_work_review_cli:register_work_review_command.<locals>.work_review": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_work_revision_cli:_register_work_observations_command.<locals>.work_observations": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_work_revision_cli:_register_work_revision_command.<locals>.work_revision": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_work_revision_cli:_register_work_revisions_command.<locals>.work_revisions": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_work_runs_cli:register_work_run_commands.<locals>.work_resume": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_work_runs_cli:register_work_run_commands.<locals>.work_runs": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_work_verification_cli:_register_work_dependencies_command.<locals>.work_dependencies": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_work_verification_cli:_register_work_file_command.<locals>.work_file": (
        ("encrypted-facts", "filing"),
        ("local-state",),
        "compute",
        "profile-bound",
        False,
        True,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_work_verification_cli:_register_work_verify_command.<locals>.work_verify": (
        ("calculation", "encrypted-facts"),
        ("local-state",),
        "compute",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._modelo_work_wizard_cli:register_work_wizard_commands.<locals>.work_wizard": (
        ("calculation", "encrypted-facts"),
        ("local-state",),
        "interactive",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._overview:overview_agenda": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._overview:overview_backlog": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._overview:overview_calendar": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._overview:overview_explain": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._overview:overview_pipeline": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._overview:overview_prepare": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._overview:overview_status": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._participation_cli:_register_rebuild_command.<locals>.participation_rebuild": (
        ("calculation", "encrypted-facts"),
        ("local-state",),
        "compute",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._participation_cli:register_participation_commands.<locals>.participation_lookup": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._prorrata_register_cli:prorrata_declare_sector": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._prorrata_register_cli:prorrata_elect_especial": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._prorrata_register_cli:prorrata_elect_general": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._prorrata_register_cli:prorrata_list": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._prorrata_register_cli:prorrata_revoke_especial": (
        ("encrypted-facts",),
        ("local-state",),
        "local-io",
        "profile-bound",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._registry_corpus:list_citations_cmd": (
        ("registry",),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._registry_corpus:list_manual_rules_cmd": (
        ("registry",),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._registry_corpus:list_manuals_cmd": (
        ("registry",),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._registry_corpus:show_citation_cmd": (
        ("registry",),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._registry_corpus:show_manual_cmd": (
        ("registry",),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._registry_corpus:verify_citations_cmd": (
        ("registry",),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._registry_corpus:verify_manual_cmd": (
        ("registry",),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._review:review_queue": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli._review:review_show": (
        ("encrypted-facts",),
        ("none",),
        "local-io",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli.registry:diff_revisions_cmd": (
        ("registry",),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli.registry:inspect_registry_cmd": (
        ("registry",),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli.registry:verify_filed_state_cmd": (
        ("registry",),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli.registry:verify_registry_cmd": (
        ("registry",),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
    "cadrumo.entrypoints.cli:_app_root": (("state-free",), ("none",), "metadata", "none", False, False, False),
    "cadrumo.entrypoints.cli:_root": (
        ("calculation", "encrypted-facts"),
        ("none",),
        "compute",
        "none",
        False,
        False,
        False,
    ),
}

__all__ = ["EXPECTED_CALLBACK_POLICY", "REPEATED_CALLBACK_OWNERS", "PolicySignature"]
