"""Application services for bucket-scoped ledger transaction workflows.

Owns the operator-facing ledger lifecycle: importing bank statements and
records, classifying transactions for tax, splitting and merging entries,
attaching evidence, and checking a period's tax-readiness before a modelo
calculation consumes it. Every service operates on the active profile's
bucket.

Major declarations:

* :func:`import_ledger_source` and :func:`bulk_classify_from_csv` — the
  ingest and batch-classification entry points.
* :func:`create_manual_transaction`, :func:`split_transaction`, and
  :func:`merge_transactions` — manual ledger edits.
* :func:`preflight_ledger_tax_readiness` with :class:`LedgerPreflightReport`
  and :class:`LedgerPreflightIssue` — the readiness gate that reports rows
  missing a category, base, IVA rate, currency, or prorrata reference.
* :func:`resolve_transaction_id` — the unambiguous-prefix id resolver.
* The typed command and result records (:class:`LedgerSourceImportCommand`,
  :class:`LedgerImportOperationResult`, :class:`LedgerReviewQueryResult`,
  :class:`LedgerStatusReport`, and siblings) that carry each operation
  across the CLI boundary.
"""

from __future__ import annotations

from ...core.external_constants import CLASSIFIED_BY_MANUAL
from ._actions import (
    LedgerProviderID,
    add_classification_rule,
    apply_classification_rules,
    archive_manual_transaction,
    attach_manual_transaction_evidence,
    bulk_classify_from_csv,
    create_manual_transaction,
    export_ledger_transactions,
    get_manual_transaction,
    import_ledger_source,
    import_ledger_transactions,
    ledger_transaction_payload,
    ledger_transaction_result_payload,
    ledger_transaction_review_payload,
    ledger_transaction_review_status,
    ledger_transaction_tracking_payload,
    list_manual_transactions,
    merge_transactions,
    query_ledger_review_rows,
    remove_manual_transaction,
    reset_ledger_catalogue,
    restore_manual_transaction,
    split_transaction,
    stash_manual_transaction,
    summarize_manual_transactions,
    update_manual_transaction,
    update_manual_transaction_fields,
)
from ._business_operation_invoice import (
    BusinessOperationInvoice,
    BusinessOperationInvoiceDocument,
    BusinessOperationInvoiceInputError,
    BusinessOperationInvoiceNotFoundError,
    BusinessOperationInvoicePatch,
    BusinessOperationInvoiceRepository,
    BusinessOperationInvoiceResult,
    BusinessOperationInvoiceSourceKind,
    CollectibleInvoiceService,
    IntracomOperationType,
    PayableInvoiceService,
    validate_eu_iva_id,
)
from ._evidence import (
    PurchaseInvoiceEvidence,
    PurchaseInvoiceEvidenceInputError,
    PurchaseInvoiceEvidenceNotFoundError,
    PurchaseInvoiceEvidencePatch,
    PurchaseInvoiceEvidenceService,
)
from ._id_resolution import (
    MINIMUM_DISPLAY_ID_WIDTH,
    compute_display_id_width,
    resolve_transaction_id,
)
from ._llm_classification import (
    LLMClassificationSuggestion,
    LLMProvider,
    LLMProviderAvailability,
    apply_llm_classification,
    available_llm_providers,
    is_llm_provider_available,
    suggest_llm_classification,
)
from ._models import (
    BULK_CLASSIFY_ALLOWED_COLUMNS,
    ApplyRulesAppliedRow,
    ApplyRulesResult,
    BulkClassifyFailure,
    BulkClassifyResult,
    BulkClassifyRow,
    LedgerCatalogueResetReport,
    LedgerExportCommand,
    LedgerExportResult,
    LedgerExportRow,
    LedgerImportDiagnosticReport,
    LedgerImportOperationResult,
    LedgerRemovalBlocker,
    LedgerReviewQuery,
    LedgerReviewQueryResult,
    LedgerReviewRow,
    LedgerSourceImportCommand,
    LedgerSourceImportResult,
    LedgerSourceValidationReport,
    LedgerSourceVerificationReport,
    LedgerStatusReport,
    LedgerTransactionPayload,
    LedgerTransactionRemovalReport,
    LedgerTransactionResultPayload,
    LedgerTransactionReviewPayload,
    LedgerTransactionTrackingPayload,
    ManualLedgerTransactionCommand,
    ManualLedgerTransactionPatch,
    ManualLedgerTransactionResult,
    MergeTransactionsResult,
    SplitChildCommand,
    SplitTransactionResult,
)
from ._preflight import (
    LedgerPreflightIssue,
    LedgerPreflightIssueReason,
    LedgerPreflightReport,
    preflight_ledger_tax_readiness,
    preflight_transaction_catalogue,
)
from ._ratios import (
    EligibleCategoryRow,
    RatiosCensoOverrideWarning,
    RatiosValidationFinding,
    RatiosValidationReport,
    censo_business_pct_for,
    censo_override_warning,
    eligible_ratio_categories,
    list_eligible_ratios_for_bucket,
    set_usage_ratio,
    unset_usage_ratio,
    validate_ratios_for_bucket,
    validate_ratios_profile,
)
from ._rule_repository import LedgerClassificationRuleRepository

__all__ = [
    "BULK_CLASSIFY_ALLOWED_COLUMNS",
    "CLASSIFIED_BY_MANUAL",
    "MINIMUM_DISPLAY_ID_WIDTH",
    "ApplyRulesAppliedRow",
    "ApplyRulesResult",
    "BulkClassifyFailure",
    "BulkClassifyResult",
    "BulkClassifyRow",
    "BusinessOperationInvoice",
    "BusinessOperationInvoiceDocument",
    "BusinessOperationInvoiceInputError",
    "BusinessOperationInvoiceNotFoundError",
    "BusinessOperationInvoicePatch",
    "BusinessOperationInvoiceRepository",
    "BusinessOperationInvoiceResult",
    "BusinessOperationInvoiceSourceKind",
    "CollectibleInvoiceService",
    "EligibleCategoryRow",
    "IntracomOperationType",
    "LLMClassificationSuggestion",
    "LLMProvider",
    "LLMProviderAvailability",
    "LedgerCatalogueResetReport",
    "LedgerClassificationRuleRepository",
    "LedgerExportCommand",
    "LedgerExportResult",
    "LedgerExportRow",
    "LedgerImportDiagnosticReport",
    "LedgerImportOperationResult",
    "LedgerPreflightIssue",
    "LedgerPreflightIssueReason",
    "LedgerPreflightReport",
    "LedgerProviderID",
    "LedgerRemovalBlocker",
    "LedgerReviewQuery",
    "LedgerReviewQueryResult",
    "LedgerReviewRow",
    "LedgerSourceImportCommand",
    "LedgerSourceImportResult",
    "LedgerSourceValidationReport",
    "LedgerSourceVerificationReport",
    "LedgerStatusReport",
    "LedgerTransactionPayload",
    "LedgerTransactionRemovalReport",
    "LedgerTransactionResultPayload",
    "LedgerTransactionReviewPayload",
    "LedgerTransactionTrackingPayload",
    "ManualLedgerTransactionCommand",
    "ManualLedgerTransactionPatch",
    "ManualLedgerTransactionResult",
    "MergeTransactionsResult",
    "PayableInvoiceService",
    "PurchaseInvoiceEvidence",
    "PurchaseInvoiceEvidenceInputError",
    "PurchaseInvoiceEvidenceNotFoundError",
    "PurchaseInvoiceEvidencePatch",
    "PurchaseInvoiceEvidenceService",
    "RatiosCensoOverrideWarning",
    "RatiosValidationFinding",
    "RatiosValidationReport",
    "SplitChildCommand",
    "SplitTransactionResult",
    "add_classification_rule",
    "apply_classification_rules",
    "apply_llm_classification",
    "archive_manual_transaction",
    "attach_manual_transaction_evidence",
    "available_llm_providers",
    "bulk_classify_from_csv",
    "censo_business_pct_for",
    "censo_override_warning",
    "compute_display_id_width",
    "create_manual_transaction",
    "eligible_ratio_categories",
    "export_ledger_transactions",
    "get_manual_transaction",
    "import_ledger_source",
    "import_ledger_transactions",
    "is_llm_provider_available",
    "ledger_transaction_payload",
    "ledger_transaction_result_payload",
    "ledger_transaction_review_payload",
    "ledger_transaction_review_status",
    "ledger_transaction_tracking_payload",
    "list_eligible_ratios_for_bucket",
    "list_manual_transactions",
    "merge_transactions",
    "preflight_ledger_tax_readiness",
    "preflight_transaction_catalogue",
    "query_ledger_review_rows",
    "remove_manual_transaction",
    "reset_ledger_catalogue",
    "resolve_transaction_id",
    "restore_manual_transaction",
    "set_usage_ratio",
    "split_transaction",
    "stash_manual_transaction",
    "suggest_llm_classification",
    "summarize_manual_transactions",
    "unset_usage_ratio",
    "update_manual_transaction",
    "update_manual_transaction_fields",
    "validate_eu_iva_id",
    "validate_ratios_for_bucket",
    "validate_ratios_profile",
]
