"""Mul/Div scalar-leaf mutation harness.

For every :class:`aeat.domain.formulas._formula.MulFormula` and
:class:`aeat.domain.formulas._formula.DivFormula` node whose direct
operand is a :class:`aeat.domain.formulas._formula.Literal` scalar in a
landed ruleset, the harness multiplies the literal by 1.01 / 0.99 and
asserts the engine surfaces a discrepancy ``>= 0.02 €``.

Currently populated surface:

- Modelo 303 casilla 66 (2024 + 2025) — ``div_op(percent(...), lit("100"))``
  is the explicit ``/100`` normaliser of the % atribuible al estado.
- Modelo 200 casilla 00562 — ``percent_from_whole(ref("00558"), ref("00552"))``
  expands to ``percent(div_op(ref("00558"), Literal("100"), ...), ref("00552"))``;
  the inner ``Literal("100")`` is the whole-percent normaliser.
- Modelo 202 casilla 18 — same shape as M200 via ``percent_from_whole``.

A future ruleset that introduces additional ``MulFormula`` /
``DivFormula`` leaves automatically extends this harness because the
parameter table is generated by walking ``_FORMULAS`` of the imported
rulesets at import time.
"""

from __future__ import annotations

from collections.abc import Callable, Iterator
from dataclasses import dataclass
from decimal import Decimal

import pytest

from .._engine import Engine
from .._ruleset import Ruleset
from . import (
    MODELO_100_2024,
    MODELO_100_2025,
    MODELO_100_2026,
    MODELO_200_2024,
    MODELO_200_2025,
    MODELO_200_2026,
    MODELO_202_2025,
    MODELO_303_2024,
    MODELO_303_2025,
    MODELO_303_2026,
)
from ._mutators import iter_scalar_leaf_paths, mutate_scalar_leaf

pytestmark = [pytest.mark.unit, pytest.mark.domain_model]


@dataclass(frozen=True)
class _ScalarCase:
    """One enumerated mutation case for the mul/div scalar mutator."""

    ruleset: Ruleset
    casilla_id: str
    formula_id: str
    leaf_path: tuple[int, ...]
    parent_op: str
    factor: Decimal
    fixture: dict[str, Decimal]
    direction_id: str


def _f303_general_for_scalar() -> dict[str, Decimal]:
    """Modelo 303 — drives casilla 66 = (65/100) * 64 = 21 €.

    Casilla 09 = 21% * 07 = 21 € on base 100 €. 45 = 21 + 0 + 0 -
    44 = 21. 64 = 45 + 0 = 21. 66 = (65/100) * 64 = (100/100) * 21
    = 21. After mutating the ``Literal("100")`` denominator by ±1 %:
    66 = (100 / 99) * 21 ≈ 21.21 (vs 21.00 baseline) — delta ≥ 0.21 €
    on casilla 66, well above the floor.
    """
    return {
        "01": Decimal("0.00"),
        "04": Decimal("0.00"),
        "07": Decimal("100.00"),
        "65": Decimal("100"),
        "67": Decimal("0.00"),
    }


def _f200_for_scalar() -> dict[str, Decimal]:
    """Modelo 200 — drives casilla 00562 = (00558/100) * 00552.

    With 00552=100 000 € (base) and 00558=25 (rate-as-whole-percent),
    casilla 00562 baseline = 25 000 €. Mutating the inner ``Literal("100")``
    by ±1 % moves 00562 by ~250 €.
    """
    return {
        "00547": Decimal("0.00"),
        "00550": Decimal("100000.00"),
        "00552": Decimal("100000.00"),
        "00558": Decimal("25.00"),
        "00560": Decimal("0.00"),
        "00582": Decimal("0.00"),
        "00592": Decimal("0.00"),
        "00599": Decimal("0.00"),
        "00601": Decimal("0.00"),
        "00603": Decimal("0.00"),
        "00605": Decimal("0.00"),
        "00615": Decimal("0.00"),
        "00619": Decimal("0.00"),
    }


def _f202_for_scalar() -> dict[str, Decimal]:
    """Modelo 202 — drives casilla 18 = (17/100) * 16 with an asymmetric base.

    With 16=200 000 € and 17=17 (rate-as-whole-percent), casilla 18
    baseline = 34 000 €. Mutating the inner Literal("100") by ±1 %
    moves casilla 18 by ~340 €.
    """
    return {
        "16": Decimal("200000.00"),
        "17": Decimal("17.00"),
        "27": Decimal("0.00"),
        "28": Decimal("0.00"),
        "30": Decimal("0.00"),
        "33": Decimal("0.00"),
    }


# -- Comprehensive Modelo 100 scalar coverage --------------------------
#
# Every Mul/Div literal leaf in every M100 year is enumerated. The
# comprehensive sub_op fixtures from :mod:`test_operand_swap_mutation`
# drive BLG / BLA / minimo into the top brackets of the LIRPF art. 63
# and art. 66 progressive scales, so 18 of the 20 leaves per year —
# 6 in 0540 + 6 in 0542 + 5 in 0560 + 1 in 0225 — are detectable with
# the same fixtures used by the sub_op harness. The remaining 2
# leaves per year (LIRPF art. 20 piece_a slope 1.75 + piece_b slope
# 1.14, both nested in casilla 0021) need targeted fixtures because
# the two pieces share a ``max_op`` so only the active one is
# observable for any given rendimiento.


def _f100_art20_piece_a_slope_for_scalar() -> dict[str, Decimal]:
    """Drive M100 Anexo B1 art. 20 piece_a (slope 1.75) at rendimiento 16 000 €.

    With 0001 = 16 000 € (sueldo bruto, no irregulares 0019=0, no
    gastos 0008..0010=0), the engine derives 0020 (rendimiento neto
    previo) = 16 000 €. Inside [14 852, 17 673,52] piece_a is active:
    reducción art. 20 = 7 302 - 1.75 x (16 000 - 14 852) = 5 293 €.
    Capped by ``min(0020, …) = min(16 000, 5 293) = 5 293 €``. A ±1 %
    factor on the 1.75 literal shifts the reducción by ±20 € (well
    above the 0,02 € floor).
    """
    return {
        "0001": Decimal("16000.00"),
        "0020": Decimal("16000.00"),
        "0021": Decimal("5293.00"),
        "0022": Decimal("10707.00"),
    }


def _f100_art20_piece_b_slope_for_scalar() -> dict[str, Decimal]:
    """Drive M100 Anexo B1 art. 20 piece_b (slope 1.14) at rendimiento 18 500 €.

    With 0001 = 18 500 € the engine derives 0020 = 18 500 €. Inside
    (17 673,52, 19 747,50) piece_b wins the ``max_op`` (piece_b =
    1 422,15 € > piece_a = 918 €). A ±1 % factor on the 1.14
    literal shifts piece_b's reducción by ~3,72 € — above the floor.
    """
    return {
        "0001": Decimal("18500.00"),
        "0020": Decimal("18500.00"),
        "0021": Decimal("1422.15"),
        "0022": Decimal("17077.85"),
    }


def _modelo_100_full_fixture_2024_for_scalar() -> dict[str, Decimal]:
    """Re-export of the comprehensive M100 2024 sub_op fixture for scalar use.

    Identical to the operand-swap module's ``_modelo_100_full_fixture_2024``
    — drives every input + computed casilla so audit_against is clean
    and a Mul/Div rate-literal mutation produces a delta on the
    affected casilla. Imported via direct call rather than re-export
    so the two modules share a single source of truth.
    """
    from .test_operand_swap_mutation import _modelo_100_full_fixture_2024

    return _modelo_100_full_fixture_2024()


def _modelo_100_full_fixture_post_2025_for_scalar() -> dict[str, Decimal]:
    """Re-export of the comprehensive M100 post-2025 sub_op fixture for scalar use."""
    from .test_operand_swap_mutation import _modelo_100_full_fixture_post_2025

    return _modelo_100_full_fixture_post_2025()


# All M100 scalar leaf paths per year — 20 each. Inspected via
# :func:`iter_scalar_leaf_paths` (see
# :func:`test_m100_selective_paths_match_walker`).
_M100_LEAF_PATHS: dict[str, tuple[tuple[int, ...], ...]] = {
    "0021": (
        (0, 1, 0, 0, 1, 0),  # piece_a slope 1.75
        (0, 1, 1, 0, 1, 0),  # piece_b slope 1.14
    ),
    "0225": ((0, 0, 0),),  # 0.05 cap
    "0540": (
        (0, 0, 0),  # bracket 1 rate 0.095
        (0, 1, 0),  # bracket 2 rate 0.12
        (0, 2, 0),  # bracket 3 rate 0.15
        (0, 3, 0),  # bracket 4 rate 0.185
        (0, 4, 0),  # bracket 5 rate 0.225
        (0, 5, 0),  # bracket 6 rate 0.245
    ),
    "0542": (
        (0, 0, 0),
        (0, 1, 0),
        (0, 2, 0),
        (0, 3, 0),
        (0, 4, 0),
        (0, 5, 0),
    ),
    "0560": (
        (0, 0, 0),  # bracket 1 rate 0.095
        (0, 1, 0),  # bracket 2 rate 0.105
        (0, 2, 0),  # bracket 3 rate 0.115
        (0, 3, 0),  # bracket 4 rate 0.135
        (0, 4, 0),  # bracket 5 rate 0.14 (2024) / 0.15 (post-2025)
    ),
}


def _modelo_100_archetypes() -> tuple[
    tuple[Ruleset, str, tuple[int, ...], Callable[[], dict[str, Decimal]]],
    ...,
]:
    """Return every M100 (ruleset, casilla, leaf_path, fixture_factory) entry.

    Comprehensive enumeration: 20 leaves per year x 3 years = 60
    entries. Per-leaf fixture routing:

    - ``0021`` piece_a slope (1.75) — uses
      :func:`_f100_art20_piece_a_slope_for_scalar` (rendimiento 16 000).
    - ``0021`` piece_b slope (1.14) — uses
      :func:`_f100_art20_piece_b_slope_for_scalar` (rendimiento 18 500).
    - ``0225``, ``0540``, ``0542``, ``0560`` — comprehensive M100
      sub_op fixture (BLG/BLA/minimo span all tarifa brackets).
    """
    entries: list[tuple[Ruleset, str, tuple[int, ...], Callable[[], dict[str, Decimal]]]] = []
    rulesets_by_year = (
        (MODELO_100_2024, _modelo_100_full_fixture_2024_for_scalar),
        (MODELO_100_2025, _modelo_100_full_fixture_post_2025_for_scalar),
        (MODELO_100_2026, _modelo_100_full_fixture_post_2025_for_scalar),
    )
    for ruleset, comprehensive in rulesets_by_year:
        for casilla_id, paths in _M100_LEAF_PATHS.items():
            for path in paths:
                if casilla_id == "0021" and path == (0, 1, 0, 0, 1, 0):
                    fixture: Callable[[], dict[str, Decimal]] = _f100_art20_piece_a_slope_for_scalar
                elif casilla_id == "0021" and path == (0, 1, 1, 0, 1, 0):
                    fixture = _f100_art20_piece_b_slope_for_scalar
                else:
                    fixture = comprehensive
                entries.append((ruleset, casilla_id, path, fixture))
    return tuple(entries)


def _build_test_params() -> list:
    """Generate one pytest.param per (ruleset * leaf * direction).

    Two layered enumerations:

    1. **Walked enumeration** — for the rulesets where every Mul/Div
       leaf has a single ruleset-wide fixture, walk
       :func:`iter_scalar_leaf_paths` and emit one case per leaf
       (M303 / M200 / M202).

    2. **Selective enumeration** — for the M100 full-form rulesets the
       ``progressive_tarifa`` constructions yield 20 leaves per year
       and a single ruleset-wide fixture cannot drive each leaf into
       its target bracket. Three archetypes per year are enumerated
       (TARIFA_ESTATAL_GENERAL, TARIFA_ESTATAL_AHORRO, LIRPF art. 20
       slope) via :func:`_modelo_100_archetypes`. The remaining 17
       leaves per year are catalogued as ``mul_div_scalar_deferred`` in
       :mod:`aeat.domain.formulas._rulesets.test_mutator_kill_rate` and
       tracked separately.
    """
    params: list = []

    # 1. Walked enumeration for M303 / M200 / M202.
    fixture_for_ruleset: dict[str, dict[str, Decimal]] = {
        MODELO_303_2024.ruleset_id: _f303_general_for_scalar(),
        MODELO_303_2025.ruleset_id: _f303_general_for_scalar(),
        MODELO_303_2026.ruleset_id: _f303_general_for_scalar(),
        MODELO_200_2024.ruleset_id: _f200_for_scalar(),
        MODELO_200_2025.ruleset_id: _f200_for_scalar(),
        MODELO_200_2026.ruleset_id: _f200_for_scalar(),
        MODELO_202_2025.ruleset_id: _f202_for_scalar(),
    }
    walked_rulesets = (
        MODELO_303_2024,
        MODELO_303_2025,
        MODELO_303_2026,
        MODELO_200_2024,
        MODELO_200_2025,
        MODELO_200_2026,
        MODELO_202_2025,
    )
    for ruleset in walked_rulesets:
        for fd in ruleset.formulas:
            for leaf_path, _leaf, parent_op in iter_scalar_leaf_paths(fd.formula):
                for direction_id, factor in (("plus_1pct", Decimal("1.01")), ("minus_1pct", Decimal("0.99"))):
                    params.append(
                        pytest.param(
                            _ScalarCase(
                                ruleset=ruleset,
                                casilla_id=fd.casilla_id,
                                formula_id=fd.formula_id,
                                leaf_path=leaf_path,
                                parent_op=parent_op,
                                factor=factor,
                                fixture=fixture_for_ruleset[ruleset.ruleset_id],
                                direction_id=direction_id,
                            ),
                            id=(f"{ruleset.ruleset_id}:casilla_{fd.casilla_id}:{parent_op}_leaf:{direction_id}"),
                        )
                    )

    # 2. Selective enumeration for M100 archetypes.
    for ruleset, casilla_id, leaf_path, fixture_factory in _modelo_100_archetypes():
        fd = ruleset.formula_for(casilla_id)
        assert fd is not None, f"M100 ruleset {ruleset.ruleset_id} missing formula for casilla {casilla_id}"
        # Resolve the leaf at the declared path so we can record the
        # parent_op slug consistently with the walked-enumeration cases.
        leaves_at_casilla = {p: op for p, _leaf, op in iter_scalar_leaf_paths(fd.formula)}
        assert leaf_path in leaves_at_casilla, (
            f"M100 archetype path {leaf_path} on {ruleset.ruleset_id} casilla {casilla_id} "
            f"is not enumerated by iter_scalar_leaf_paths — declared leaves: "
            f"{sorted(leaves_at_casilla)}"
        )
        parent_op = leaves_at_casilla[leaf_path]
        for direction_id, factor in (("plus_1pct", Decimal("1.01")), ("minus_1pct", Decimal("0.99"))):
            params.append(
                pytest.param(
                    _ScalarCase(
                        ruleset=ruleset,
                        casilla_id=casilla_id,
                        formula_id=fd.formula_id,
                        leaf_path=leaf_path,
                        parent_op=parent_op,
                        factor=factor,
                        fixture=fixture_factory(),
                        direction_id=direction_id,
                    ),
                    id=(f"{ruleset.ruleset_id}:casilla_{casilla_id}:{parent_op}_leaf:{direction_id}"),
                )
            )

    return params


def _iter_scalar_targets() -> Iterator[tuple[str, str, tuple[int, ...]]]:
    """Yield ``(ruleset_id, casilla_id, leaf_path)`` for every mutated scalar target.

    Imported by :mod:`test_mutator_kill_rate` to compute the empirical
    mul/div scalar coverage. Mirrors the unique target set behind
    :func:`_build_test_params` (the +1 % / -1 % directions count as a
    single covered target).
    """
    seen: set[tuple[str, str, tuple[int, ...]]] = set()
    walked_rulesets = (
        MODELO_303_2024,
        MODELO_303_2025,
        MODELO_303_2026,
        MODELO_200_2024,
        MODELO_200_2025,
        MODELO_200_2026,
        MODELO_202_2025,
    )
    for ruleset in walked_rulesets:
        for fd in ruleset.formulas:
            for leaf_path, _leaf, _parent_op in iter_scalar_leaf_paths(fd.formula):
                key = (ruleset.ruleset_id, fd.casilla_id, leaf_path)
                if key in seen:
                    continue
                seen.add(key)
                yield key
    for ruleset, casilla_id, leaf_path, _fixture_factory in _modelo_100_archetypes():
        key = (ruleset.ruleset_id, casilla_id, leaf_path)
        if key in seen:
            continue
        seen.add(key)
        yield key


def test_landed_rulesets_expose_some_scalar_leaves() -> None:
    """Smoke-check the harness has a non-empty parameter table.

    Today's expected surface: at least one ``Mul`` or ``Div`` leaf
    per ruleset across the four rulesets registered above.
    """
    assert _build_test_params(), "expected at least one scalar-leaf mutation case"


@pytest.mark.parametrize("case", _build_test_params())
def test_scalar_leaf_mutation_is_detected(case: _ScalarCase) -> None:
    """Mutating a Mul/Div literal leaf MUST produce a downstream discrepancy."""
    engine = Engine()
    user_inputs = {cid: v for cid, v in case.fixture.items() if not case.ruleset.casilla(cid).computed}
    baseline_ledger = engine.derive(ruleset=case.ruleset, inputs=user_inputs)
    baseline_values = {entry.casilla_id: entry.value for entry in baseline_ledger.entries}
    full_baseline = {**case.fixture, **baseline_values}

    baseline = engine.audit_against(
        ruleset=case.ruleset,
        provided=full_baseline,
        tolerance=Decimal("0.01"),
    )
    assert baseline.is_clean(), (
        f"baseline must be clean before mutation; saw {[d.casilla_id for d in baseline.discrepancies]}"
    )

    mutated = mutate_scalar_leaf(
        case.ruleset,
        case.casilla_id,
        case.leaf_path,
        factor=case.factor,
    )
    report = engine.audit_against(
        ruleset=mutated,
        provided=full_baseline,
        tolerance=Decimal("0.01"),
    )
    affected = {d.casilla_id for d in report.discrepancies}
    assert affected, (
        f"scalar-leaf {case.parent_op} mutation on {case.ruleset.ruleset_id} "
        f"casilla {case.casilla_id} ({case.direction_id}) was NOT detected"
    )
    max_delta = max(abs(d.delta) for d in report.discrepancies)
    assert max_delta >= Decimal("0.02"), (
        f"scalar-leaf {case.parent_op} mutation on {case.ruleset.ruleset_id} "
        f"casilla {case.casilla_id} produced max |delta|={max_delta}, below "
        f"the 0.02 € detection floor"
    )


def test_iter_scalar_leaf_paths_finds_div_leaves_in_modelo_303() -> None:
    """Modelo 303 casilla 66 has exactly one Div literal leaf (the /100)."""
    fd = MODELO_303_2025.formula_for("66")
    assert fd is not None
    leaves = list(iter_scalar_leaf_paths(fd.formula))
    # The body is ``RoundFormula(DivFormula(PercentFormula, Literal("100")))``.
    # Walker descends RoundFormula → DivFormula and yields the
    # ``Literal("100")`` at index 1.
    assert len(leaves) == 1
    leaf_path, leaf, parent_op = leaves[0]
    assert parent_op == "div"
    assert leaf.value == Decimal("100")
    assert leaf_path == (0, 1)


def test_m100_selective_paths_match_walker() -> None:
    """Every selectively-enumerated M100 leaf appears in the walker's enumeration.

    The selective M100 enumeration declares ``(casilla, leaf_path)``
    pairs explicitly. If a future M100 ruleset refactor changes the
    formula tree shape so the declared path no longer points at a
    Mul/Div literal, the harness must fail loudly rather than silently
    skipping the archetype.
    """
    for ruleset, casilla_id, leaf_path, _fixture_factory in _modelo_100_archetypes():
        fd = ruleset.formula_for(casilla_id)
        assert fd is not None, f"{ruleset.ruleset_id}: missing formula for casilla {casilla_id}"
        leaves = {path: op for path, _leaf, op in iter_scalar_leaf_paths(fd.formula)}
        assert leaf_path in leaves, (
            f"{ruleset.ruleset_id} casilla {casilla_id}: declared archetype path {leaf_path} "
            f"is not enumerated by iter_scalar_leaf_paths; available leaves: {sorted(leaves)}"
        )


def test_mutate_scalar_leaf_rejects_non_literal_path() -> None:
    """Harness integrity: targeting a non-Literal raises TypeError."""
    fd = MODELO_303_2025.formula_for("66")
    assert fd is not None
    # Path (0, 0) inside casilla 66 is the PercentFormula numerator —
    # a compound node, not a literal. The mutator must refuse.
    with pytest.raises(TypeError):
        mutate_scalar_leaf(
            MODELO_303_2025,
            "66",
            (0, 0),
            factor=Decimal("1.01"),
        )
