# Native rewriting tools belong to the selected builder and never to runtime paths.
set(native_tools "{}")
set(native_tool_hashes "{}")
set(native_tool_names)
if(target_system STREQUAL "Linux")
  set(native_tool_names readelf patchelf)
elseif(target_system STREQUAL "Darwin")
  set(native_tool_names install_name_tool codesign)
endif()
foreach(name IN LISTS native_tool_names)
  string(TOUPPER "${name}" variable_suffix)
  set(variable "CADRUMO_${variable_suffix}")
  set(${variable} "" CACHE FILEPATH "Reviewed absolute ${name} tool for package assembly")
  if(NOT IS_ABSOLUTE "${${variable}}" OR NOT EXISTS "${${variable}}" OR IS_DIRECTORY "${${variable}}")
    message(FATAL_ERROR "Supply ${variable} as an absolute existing tool path for ${CADRUMO_TARGET}")
  endif()
  file(SHA256 "${${variable}}" tool_hash)
  string(JSON native_tools SET "${native_tools}" "${name}" "\"${${variable}}\"")
  string(JSON native_tool_hashes SET "${native_tool_hashes}" "${name}" "\"${tool_hash}\"")
endforeach()
string(JSON build_toolchain SET "${build_toolchain}" native_tools "${native_tools}")
string(JSON build_toolchain SET "${build_toolchain}" native_tool_sha256 "${native_tool_hashes}")
if(target_system STREQUAL "Darwin")
  set(CADRUMO_NATIVE_SIGNING_IDENTITY "" CACHE STRING "Explicit identity for signing assembled native images")
  if(CADRUMO_NATIVE_SIGNING_IDENTITY STREQUAL "")
    message(FATAL_ERROR "Supply CADRUMO_NATIVE_SIGNING_IDENTITY for macOS package assembly")
  endif()
  string(JSON build_toolchain SET "${build_toolchain}" native_signing_identity "\"${CADRUMO_NATIVE_SIGNING_IDENTITY}\"")
endif()
