include_guard(GLOBAL)
function(cadrumo_cached_command output name)
  cmake_parse_arguments(ACTION "SHARED" "" "INPUTS;OUTPUTS;ENVIRONMENT" ${ARGN})
  set(spec "{}")
  foreach(key inputs outputs environment)
    string(TOUPPER "${key}" upper)
    set(array "[]")
    set(index 0)
    foreach(value IN LISTS ACTION_${upper})
      string(REPLACE "\\" "\\\\" value "${value}")
      string(REPLACE "\"" "\\\"" value "${value}")
      string(JSON array SET "${array}" ${index} "\"${value}\"")
      math(EXPR index "${index} + 1")
    endforeach()
    string(JSON spec SET "${spec}" ${key} "${array}")
  endforeach()
  if(ACTION_SHARED)
    set(configuration shared)
  else()
    set(configuration "$<CONFIG>")
  endif()
  set(marker "${CMAKE_BINARY_DIR}/generated/action-${name}-${configuration}.json")
  string(JSON spec SET "${spec}" marker "\"${marker}\"")
  string(JSON spec SET "${spec}" name "\"${name}\"")
  set(spec_file "${CMAKE_BINARY_DIR}/action-${name}-${configuration}.json")
  file(GENERATE OUTPUT "${spec_file}" CONTENT "${spec}\n")
  get_filename_component(repository "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../.." ABSOLUTE)
  set(${output} "${CMAKE_COMMAND}" -E chdir "${repository}"
    "${CADRUMO_DEV_PYTHON}" -B -m dev.packaging.native.cached_command
    --build "${CMAKE_BINARY_DIR}" --spec "${spec_file}" -- PARENT_SCOPE)
  cadrumo_register_clean(TARGET "${name}" PATHS "${marker}" ${ACTION_OUTPUTS})
endfunction()
