include_guard(GLOBAL)

# PATHS are outputs owned exclusively by TARGET. DEPENDS enrolls children of an
# aggregate clean target, never ordinary build prerequisites (which may be shared).
function(cadrumo_register_clean)
  cmake_parse_arguments(CLEAN "" "TARGET" "PATHS;DEPENDS" ${ARGN})
  if(NOT CLEAN_TARGET)
    message(FATAL_ERROR "Cleanup enrollment requires TARGET")
  endif()
  set_property(GLOBAL APPEND PROPERTY "CADRUMO_CLEAN_PATHS_${CLEAN_TARGET}" ${CLEAN_PATHS})
  set_property(GLOBAL APPEND PROPERTY "CADRUMO_CLEAN_DEPENDS_${CLEAN_TARGET}" ${CLEAN_DEPENDS})
  set_property(GLOBAL APPEND PROPERTY CADRUMO_CLEAN_REGISTERED_TARGETS "${CLEAN_TARGET}")
endfunction()

function(_cadrumo_collect_build_targets directory result)
  get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
  get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
  foreach(child IN LISTS children)
    _cadrumo_collect_build_targets("${child}" child_targets)
    list(APPEND targets ${child_targets})
  endforeach()
  set(${result} "${targets}" PARENT_SCOPE)
endfunction()

function(_cadrumo_cleanup_json_array result)
  set(array "[]")
  set(index 0)
  foreach(value IN LISTS ARGN)
    string(REPLACE "\\" "/" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(JSON array SET "${array}" ${index} "\"${value}\"")
    math(EXPR index "${index} + 1")
  endforeach()
  set(${result} "${array}" PARENT_SCOPE)
endfunction()

function(cadrumo_finalize_clean_targets)
  get_property(finalized GLOBAL PROPERTY CADRUMO_CLEAN_FINALIZED)
  if(finalized)
    return()
  endif()
  set_property(GLOBAL PROPERTY CADRUMO_CLEAN_FINALIZED TRUE)
  if(NOT CADRUMO_DEV_PYTHON)
    find_program(CADRUMO_DEV_PYTHON NAMES python3 python REQUIRED)
  endif()
  get_filename_component(repository "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../.." ABSOLUTE)
  _cadrumo_collect_build_targets("${CMAKE_SOURCE_DIR}" targets)
  get_property(registered GLOBAL PROPERTY CADRUMO_CLEAN_REGISTERED_TARGETS)
  foreach(target IN LISTS registered)
    if(NOT TARGET "${target}")
      message(FATAL_ERROR "Cleanup enrollment has no build target: ${target}")
    endif()
  endforeach()
  set(document "{\"targets\":{}}")
  string(JSON document SET "${document}" source "\"${CMAKE_SOURCE_DIR}\"")
  foreach(target IN LISTS targets)
    if(target MATCHES "^clean-")
      continue()
    endif()
    get_target_property(type "${target}" TYPE)
    get_property(paths GLOBAL PROPERTY "CADRUMO_CLEAN_PATHS_${target}")
    get_property(dependencies GLOBAL PROPERTY "CADRUMO_CLEAN_DEPENDS_${target}")
    foreach(dependency IN LISTS dependencies)
      if(NOT dependency IN_LIST targets OR dependency MATCHES "^clean-")
        message(FATAL_ERROR "Cleanup dependency has no build target: ${dependency}")
      endif()
    endforeach()
    if(type MATCHES "^(EXECUTABLE|STATIC_LIBRARY|SHARED_LIBRARY|MODULE_LIBRARY|OBJECT_LIBRARY)$")
      list(APPEND paths "$<TARGET_OBJECTS:${target}>")
      if(NOT type STREQUAL "OBJECT_LIBRARY")
        list(APPEND paths "$<TARGET_FILE:${target}>")
      endif()
      if(WIN32 AND type STREQUAL "SHARED_LIBRARY")
        list(APPEND paths "$<TARGET_LINKER_FILE:${target}>")
      endif()
    endif()
    list(REMOVE_DUPLICATES paths)
    _cadrumo_cleanup_json_array(path_json ${paths})
    _cadrumo_cleanup_json_array(dependency_json ${dependencies})
    string(JSON document SET "${document}" targets "${target}"
      "{\"paths\":${path_json},\"depends\":${dependency_json}}")
    if(paths)
      set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES ${paths})
    endif()
    # Bootstrap supplies a CMake-only cleanup for its own interpreter; retain it
    # rather than routing the operation through the interpreter being removed.
    if(NOT TARGET "clean-${target}")
      add_custom_target("clean-${target}"
        COMMAND "${CADRUMO_DEV_PYTHON}" -B -m dev.packaging.native.cleanup
          "${CMAKE_BINARY_DIR}" "${target}" --target --config "$<CONFIG>"
        WORKING_DIRECTORY "${repository}" VERBATIM)
    endif()
  endforeach()
  # TARGET_OBJECTS expands to a list only during generation. Turn its separators
  # into JSON member separators after string(JSON) has finished quoting values.
  string(REGEX REPLACE "(\\$<TARGET_OBJECTS:[^>]+>)" "$<JOIN:\\1,\",\">" document "${document}")
  file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/cleanup-$<CONFIG>.json" CONTENT "${document}\n")
  foreach(group IN LISTS CADRUMO_CLEANUP_GROUPS)
    if(NOT TARGET "clean-${group}")
      add_custom_target("clean-${group}"
        COMMAND "${CADRUMO_DEV_PYTHON}" -B -m dev.packaging.native.cleanup
          "${CMAKE_BINARY_DIR}" "${group}"
        WORKING_DIRECTORY "${repository}" VERBATIM)
    endif()
  endforeach()
endfunction()
