# The builder cannot execute Python while removing its own interpreter.
if(NOT IS_ABSOLUTE "${BUILD}" OR NOT IS_ABSOLUTE "${SOURCE}")
  message(FATAL_ERROR "Builder cleanup requires absolute build and source paths")
endif()
cmake_path(NORMAL_PATH BUILD)
cmake_path(NORMAL_PATH SOURCE)
if(BUILD STREQUAL SOURCE OR NOT EXISTS "${BUILD}/CMakeCache.txt")
  message(FATAL_ERROR "Builder cleanup requires an existing out-of-source CMake build")
endif()
file(STRINGS "${BUILD}/CMakeCache.txt" owners REGEX "^CMAKE_HOME_DIRECTORY:INTERNAL=")
if(NOT owners STREQUAL "CMAKE_HOME_DIRECTORY:INTERNAL=${SOURCE}")
  message(FATAL_ERROR "Builder cleanup source does not own this CMake build")
endif()
set(builder "${BUILD}/_deps/builder")
foreach(path "${BUILD}" "${BUILD}/_deps" "${builder}" "${BUILD}/builder-state.cmake")
  if(IS_SYMLINK "${path}")
    message(FATAL_ERROR "Builder cleanup refuses linked path: ${path}")
  endif()
endforeach()
file(REAL_PATH "${BUILD}" resolved_build)
file(REAL_PATH "${builder}" resolved_builder)
cmake_path(APPEND resolved_build "_deps/builder" OUTPUT_VARIABLE expected_builder)
if(NOT resolved_builder STREQUAL expected_builder)
  message(FATAL_ERROR "Builder cleanup path escapes its declared build ownership")
endif()
# Invalidate configure before deletion, including if deletion is interrupted.
string(RANDOM LENGTH 24 nonce)
file(WRITE "${BUILD}/builder-state.cmake" "# Restore managed builder after cleanup ${nonce}.\n")
file(REMOVE_RECURSE "${builder}")
