include(CheckCCompilerFlag)
include(CheckLinkerFlag)

function(cadrumo_compile_policy target)
  set_target_properties(${target} PROPERTIES
    C_STANDARD 17 C_STANDARD_REQUIRED YES C_EXTENSIONS NO
    POSITION_INDEPENDENT_CODE YES)
  if(MSVC)
    target_compile_options(${target} PRIVATE "$<$<COMPILE_LANGUAGE:C>:/W4;/sdl;/guard:cf>")
    target_compile_definitions(${target} PRIVATE WINVER=0x0A00 _WIN32_WINNT=0x0A00)
    target_link_options(${target} PRIVATE /DYNAMICBASE /NXCOMPAT /HIGHENTROPYVA /guard:cf)
  else()
    foreach(flag -Wall -Wextra -Wformat=2 -fstack-protector-strong)
      string(MAKE_C_IDENTIFIER "CADRUMO_C_${flag}" supported)
      check_c_compiler_flag("${flag}" ${supported})
      if(${supported})
        target_compile_options(${target} PRIVATE "$<$<COMPILE_LANGUAGE:C>:${flag}>")
      endif()
    endforeach()
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
      target_compile_definitions(${target} PRIVATE "$<$<CONFIG:Release>:_FORTIFY_SOURCE=2>")
      foreach(flag "LINKER:-z,relro" "LINKER:-z,now" "LINKER:-z,noexecstack")
        string(MAKE_C_IDENTIFIER "CADRUMO_LINK_${flag}" supported)
        check_linker_flag(C "${flag}" ${supported})
        if(${supported})
          target_link_options(${target} PRIVATE "${flag}")
        endif()
      endforeach()
    endif()
  endif()
endfunction()
