# Execute npm's admitted CLI with the selected Node binary, bypassing wrapper
# prefix/PATH dispatch. The wrapper remains recorded as the discovery input.
file(REAL_PATH "${CADRUMO_NPM}" resolved_npm)
get_filename_component(npm_directory "${resolved_npm}" DIRECTORY)
get_filename_component(node_directory "${CADRUMO_NODE}" DIRECTORY)
cmake_path(NATIVE_PATH node_directory native_node_directory)
set(desktop_node_path_arguments --modify "PATH=path_list_prepend:${native_node_directory}")
if(resolved_npm MATCHES "/npm-cli\\.js$")
  set(npm_cli_default "${resolved_npm}")
elseif(EXISTS "${npm_directory}/node_modules/npm/bin/npm-cli.js")
  set(npm_cli_default "${npm_directory}/node_modules/npm/bin/npm-cli.js")
else()
  set(npm_cli_default "${node_directory}/node_modules/npm/bin/npm-cli.js")
endif()
set(CADRUMO_NPM_CLI "${npm_cli_default}" CACHE FILEPATH "Explicit npm CLI executed with CADRUMO_NODE")
if(NOT IS_ABSOLUTE "${CADRUMO_NPM_CLI}" OR NOT EXISTS "${CADRUMO_NPM_CLI}")
  message(FATAL_ERROR "Set CADRUMO_NPM_CLI to an existing absolute npm/bin/npm-cli.js")
endif()
get_filename_component(npm_bin "${CADRUMO_NPM_CLI}" DIRECTORY)
get_filename_component(npm_root "${npm_bin}" DIRECTORY)
file(READ "${npm_root}/package.json" npm_package)
string(JSON npm_name GET "${npm_package}" name)
string(JSON npm_version GET "${npm_package}" version)
if(NOT npm_name STREQUAL "npm")
  message(FATAL_ERROR "CADRUMO_NPM_CLI does not select an npm implementation")
endif()
if(COMMAND cadrumo_record_builder_file)
  cadrumo_record_builder_file("desktop/node" "${CADRUMO_NODE}")
  cadrumo_record_builder_file("desktop/npm-wrapper" "${CADRUMO_NPM}")
  cadrumo_record_builder_file("desktop/npm-cli" "${CADRUMO_NPM_CLI}")
  cadrumo_record_builder_file("desktop/npm-package" "${npm_root}/package.json")
  cadrumo_record_builder_file("desktop/npm-lock" "${desktop_frontend}/package-lock.json")
  set(desktop_tools "{}")
  set(desktop_tool_pairs node CADRUMO_NODE npm_wrapper CADRUMO_NPM npm_cli CADRUMO_NPM_CLI
      npm_root npm_root lockfile desktop_frontend npm_version npm_version)
  while(desktop_tool_pairs)
    list(POP_FRONT desktop_tool_pairs key variable)
    set(value "${${variable}}")
    if(key STREQUAL "lockfile")
      set(value "${value}/package-lock.json")
    endif()
    cadrumo_json_string(quoted "${value}")
    string(JSON desktop_tools SET "${desktop_tools}" "${key}" "${quoted}")
  endwhile()
  string(JSON build_toolchain SET "${build_toolchain}" builder_files "${builder_files}")
  string(JSON build_toolchain SET "${build_toolchain}" desktop_tools "${desktop_tools}")
  if(NOT CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
    set(build_toolchain "${build_toolchain}" PARENT_SCOPE)
  endif()
endif()
