function(cadrumo_package_bootstrap output layout source_root)
  string(JSON bootstrap_relative GET "${layout}" bootstrap)
  set(bootstrap "${source_root}/native/${bootstrap_relative}")
  if(NOT EXISTS "${bootstrap}" OR IS_DIRECTORY "${bootstrap}")
    message(FATAL_ERROR "Declared package bootstrap is missing: ${bootstrap_relative}")
  endif()
  set(${output} "${bootstrap}" PARENT_SCOPE)
endfunction()

function(cadrumo_provision_helpers output source_root)
  file(GLOB_RECURSE helpers CONFIGURE_DEPENDS "${source_root}/dev/packaging/native/*.py")
  list(FILTER helpers EXCLUDE REGEX "/tests/")
  set(${output} "${helpers}" PARENT_SCOPE)
endfunction()
