# Record only selected builder files and explicitly selected target SDK resources.
function(cadrumo_json_string output value)
  string(REPLACE "\\" "\\\\" quoted "${value}")
  string(REPLACE "\"" "\\\"" quoted "${quoted}")
  string(REPLACE "\n" "\\n" quoted "${quoted}")
  string(REPLACE "\r" "\\r" quoted "${quoted}")
  set(${output} "\"${quoted}\"" PARENT_SCOPE)
endfunction()

function(cadrumo_record_builder_file label path)
  if(NOT IS_ABSOLUTE "${path}" OR NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
    message(FATAL_ERROR "Selected ${label} must name an existing absolute builder file")
  endif()
  file(REAL_PATH "${path}" absolute)
  file(SHA256 "${absolute}" hash)
  cadrumo_json_string(quoted_path "${path}")
  cadrumo_json_string(quoted_resolved "${absolute}")
  set(link_text "")
  if(IS_SYMLINK "${path}")
    file(READ_SYMLINK "${path}" link_text)
  endif()
  cadrumo_json_string(quoted_link "${link_text}")
  set(record "{}")
  string(JSON record SET "${record}" path "${quoted_path}")
  string(JSON record SET "${record}" resolved "${quoted_resolved}")
  string(JSON record SET "${record}" link_text "${quoted_link}")
  string(JSON record SET "${record}" sha256 "\"${hash}\"")
  string(JSON builder_files SET "${builder_files}" "${label}" "${record}")
  set(builder_files "${builder_files}" PARENT_SCOPE)
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}" "${absolute}")
endfunction()

set(builder_files "{}")
set(sysroots "{}")
get_filename_component(builder_source_root "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
foreach(name CMAKE_C_COMPILER CMAKE_LINKER CMAKE_AR CMAKE_TOOLCHAIN_FILE CADRUMO_RUST_LINKER CADRUMO_UV)
  if(NOT "${${name}}" STREQUAL "")
    cadrumo_record_builder_file("${name}" "${${name}}")
  endif()
endforeach()
foreach(name rustc cargo rustdoc)
  if(CADRUMO_RUST_ROOT)
    cadrumo_record_builder_file("rust/${name}" "${CADRUMO_RUST_ROOT}/bin/${name}${CMAKE_EXECUTABLE_SUFFIX}")
  endif()
endforeach()
foreach(name CMAKE_SYSROOT CMAKE_SYSROOT_COMPILE CMAKE_SYSROOT_LINK CMAKE_OSX_SYSROOT)
  if(NOT "${${name}}" STREQUAL "")
    if(NOT IS_ABSOLUTE "${${name}}" OR NOT IS_DIRECTORY "${${name}}")
      message(FATAL_ERROR "Selected ${name} must be an absolute target SDK directory")
    endif()
    file(REAL_PATH "${${name}}" selected_sysroot)
    cmake_path(GET selected_sysroot ROOT_PATH filesystem_root)
    if(selected_sysroot STREQUAL filesystem_root)
      message(FATAL_ERROR "Selected ${name} must not be the builder filesystem root")
    endif()
    if(NOT CADRUMO_DEV_PYTHON)
      message(FATAL_ERROR "Selected SDK identity requires CADRUMO_DEV_PYTHON")
    endif()
    if(CADRUMO_PATH_GENERATED)
      set(inventory "${CADRUMO_PATH_GENERATED}/sysroot-${name}.json")
    else()
      set(inventory "${CMAKE_BINARY_DIR}/generated/sysroot-${name}.json")
    endif()
    execute_process(COMMAND "${CADRUMO_DEV_PYTHON}" -B -m dev.packaging.native.build_toolchain
      "${selected_sysroot}" "${inventory}"
      WORKING_DIRECTORY "${builder_source_root}" OUTPUT_VARIABLE sdk_identity
      OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
    string(JSON sysroots SET "${sysroots}" "${name}" "${sdk_identity}")
    string(JSON sdk_inputs GET "${sdk_identity}" inputs)
    file(STRINGS "${sdk_inputs}" selected_inputs ENCODING UTF-8)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${selected_inputs})
    # The glob tracks additions/removals without following SDK directory links.
    file(GLOB_RECURSE sysroot_members CONFIGURE_DEPENDS LIST_DIRECTORIES TRUE "${selected_sysroot}/*")
  endif()
endforeach()
include("${CMAKE_CURRENT_LIST_DIR}/LinuxCppAbi.cmake")
set(target_configuration "{}")
foreach(name CMAKE_SYSTEM_NAME CMAKE_SYSTEM_PROCESSOR CMAKE_C_COMPILER_TARGET
    CMAKE_C_COMPILER_ARG1 CMAKE_C_COMPILER_EXTERNAL_TOOLCHAIN
    CMAKE_SYSROOT CMAKE_SYSROOT_COMPILE CMAKE_SYSROOT_LINK CMAKE_OSX_SYSROOT
    CMAKE_OSX_ARCHITECTURES CMAKE_OSX_DEPLOYMENT_TARGET CMAKE_C_FLAGS
    CMAKE_C_FLAGS_DEBUG CMAKE_C_FLAGS_RELEASE CMAKE_EXE_LINKER_FLAGS
    CMAKE_EXE_LINKER_FLAGS_DEBUG CMAKE_EXE_LINKER_FLAGS_RELEASE)
  cadrumo_json_string(quoted "${${name}}")
  string(JSON target_configuration SET "${target_configuration}" "${name}" "${quoted}")
endforeach()
string(JSON build_toolchain SET "${build_toolchain}" builder_files "${builder_files}")
string(JSON build_toolchain SET "${build_toolchain}" sysroots "${sysroots}")
string(JSON build_toolchain SET "${build_toolchain}" target_configuration "${target_configuration}")
