"""Generate the error-code reference document from the live registry."""

from __future__ import annotations

import argparse
import importlib
import pkgutil
from pathlib import Path

import aeat
from aeat.core.errors import ERROR_REGISTRY

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = PROJECT_ROOT / "docs" / "error-codes.md"


def _import_all_aeat_modules() -> None:
    for info in pkgutil.walk_packages(aeat.__path__, prefix="aeat."):
        name = info.name
        if ".test_" in name or "._test_" in name:
            continue
        importlib.import_module(name)


def _escape_cell(value: object | None) -> str:
    if value is None:
        return "-"
    return str(value).replace("|", "\\|").replace("\n", "<br>")


def build_document() -> str:
    """Render the live registry as a Markdown table."""

    _import_all_aeat_modules()
    lines = [
        "# Error Codes",
        "",
        "_Generated by `scripts/generate_error_codes_doc.py` from `aeat.errors.ERROR_REGISTRY`._",
        "",
        "This reference is generated from the live registry after "
        "`scripts/generate_error_codes_doc.py` import-walks `aeat.*`, so the table reflects "
        "the fully populated `aeat.errors.ERROR_REGISTRY` at build time.",
        "",
        f"- The current live registry contains {len(ERROR_REGISTRY)} codes.",
        "- `Category` is the stable stderr prefix family for the error.",
        "- `Suggestion` is the exact copy-paste recovery command shown on the `-> Run` line.",
        "- Under `--json`, the same registry feeds the structured error envelope on stderr while stdout stays clean.",
        "- `runbook_id` is currently empty for all live codes.",
        "",
        "| Code | Category | ES | EN | HU | Suggestion | Runbook ID |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for code in sorted(ERROR_REGISTRY.values(), key=lambda item: item.code):
        lines.append(
            "| "
            + " | ".join(
                [
                    _escape_cell(code.code),
                    _escape_cell(code.category.value),
                    _escape_cell(code.default_message_es),
                    _escape_cell(code.default_message_en),
                    _escape_cell(code.default_message_hu),
                    _escape_cell(code.default_suggestion),
                    _escape_cell(code.runbook_id),
                ]
            )
            + " |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    """Generate the error-code Markdown file."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Path to the generated Markdown document.",
    )
    args = parser.parse_args()

    output_path = args.output if args.output.is_absolute() else (PROJECT_ROOT / args.output).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_document(), encoding="utf-8")


if __name__ == "__main__":
    main()
