//! Inputs are generated by cli_contract_fixtures.py using the Python producers.
use super::*;
use serde_json::{Value, json};
use zeroize::Zeroizing;

fn fixture(name: &str) -> Value {
    let fixtures: Value = serde_json::from_str(include_str!("cli_contract_fixtures.json")).unwrap();
    fixtures.get(name).unwrap().clone()
}

fn from_document(document: Value) -> Result<Outcome> {
    let success = document["status"] != "error";
    let leaf = document["command"]
        .as_str()
        .unwrap()
        .strip_prefix("config.")
        .unwrap();
    let bytes = Zeroizing::new(serde_json::to_vec(&document).unwrap());
    let empty = Zeroizing::new(Vec::new());
    let (stdout, stderr) = if success {
        (bytes, empty)
    } else {
        (empty, bytes)
    };
    decode(
        leaf,
        &Output {
            success,
            stdout,
            stderr,
        },
    )
}

#[test]
fn python_login_refusals_project_only_the_shell_code_and_typed_countdown() {
    for (case, code, seconds) in [
        ("credential-rejected", "CREDENTIAL_REJECTED", None),
        ("runtime-throttled", "THROTTLED", Some(23)),
        ("direct-throttled", "THROTTLED", Some(7)),
        ("authentication-required", "authentication_required", None),
    ] {
        let result = login(from_document(fixture(case)).unwrap()).unwrap();
        assert_eq!(
            serde_json::to_value(result).unwrap(),
            json!({
                "kind": "refused", "code": code, "retryAfterSeconds": seconds
            }),
            "{case}"
        );
    }
}

#[test]
fn throttle_metadata_is_required_and_never_inferred_from_a_message_or_wait_alone() {
    for seconds in [
        Value::Null,
        json!("-1"),
        json!("1.5"),
        json!("18446744073709551616"),
    ] {
        let mut document = fixture("runtime-throttled");
        document["error"]["context"]["seconds"] = seconds;
        assert!(from_document(document).is_err());
    }
    let mut missing = fixture("runtime-throttled");
    missing["error"]["context"]
        .as_object_mut()
        .unwrap()
        .remove("seconds");
    assert!(from_document(missing).is_err());
    let mut zero = fixture("runtime-throttled");
    zero["error"]["context"]["seconds"] = json!("0");
    assert_eq!(
        serde_json::to_value(login(from_document(zero).unwrap()).unwrap()).unwrap()["retryAfterSeconds"],
        0
    );
    let mut ordinary = fixture("authentication-required");
    ordinary["error"]["context"]["seconds"] = json!("23");
    ordinary["error"]["message"] = json!("throttled CREDENTIAL_REJECTED private diagnostic");
    assert_eq!(
        serde_json::to_value(login(from_document(ordinary).unwrap()).unwrap()).unwrap(),
        json!({
            "kind":"refused", "code":"authentication_required", "retryAfterSeconds":null
        })
    );
}

#[test]
fn python_status_distinguishes_presence_unavailability_and_untrusted_runtime() {
    for (case, presence, available, refusal) in [
        ("status-present", "present", true, Value::Null),
        ("status-absent", "absent", true, Value::Null),
        ("status-unknown", "unknown", true, Value::Null),
        (
            "runtime-unavailable",
            "unknown",
            false,
            json!({"code":"runtime_unavailable","retryAfterSeconds":null}),
        ),
        (
            "runtime-untrusted",
            "unknown",
            true,
            json!({"code":"runtime_peer_untrusted","retryAfterSeconds":null}),
        ),
    ] {
        assert_eq!(
            serde_json::to_value(status(from_document(fixture(case)).unwrap()).unwrap()).unwrap(),
            json!({
                "supported":true, "state":presence, "active_profile":"Test profile",
                "runtimeAvailable":available, "refusal":refusal
            }),
            "{case}"
        );
    }
}

#[test]
fn python_login_warning_does_not_claim_a_persisted_session() {
    assert_eq!(
        serde_json::to_value(login(from_document(fixture("login-true")).unwrap()).unwrap())
            .unwrap(),
        json!({
            "kind":"signed-in",
            "status": {
                "supported":true,
                "state":"present",
                "active_profile":"Test profile",
                "runtimeAvailable":true,
                "refusal":null
            }
        })
    );
    assert_eq!(
        serde_json::to_value(login(from_document(fixture("login-false")).unwrap()).unwrap())
            .unwrap(),
        json!({
            "kind":"refused", "code":"session_not_persisted", "retryAfterSeconds":null
        })
    );
}

#[test]
fn persisted_login_observation_requires_a_coherent_authenticated_label() {
    let mut absent_outer = fixture("login-true");
    absent_outer["active_profile"] = Value::Null;
    let accepted = login(from_document(absent_outer).unwrap()).unwrap();
    assert_eq!(
        serde_json::to_value(accepted).unwrap()["status"]["active_profile"],
        "Test profile"
    );

    for label in [Value::Null, json!(""), json!("x".repeat(161)), json!(12)] {
        let mut document = fixture("login-true");
        document["result"]["active_profile"] = label;
        assert!(login(from_document(document).unwrap()).is_err());
    }
    let mut missing = fixture("login-true");
    missing["result"]
        .as_object_mut()
        .unwrap()
        .remove("active_profile");
    assert!(login(from_document(missing).unwrap()).is_err());

    let mut different_outer = fixture("login-true");
    different_outer["active_profile"] = json!("Another profile");
    assert!(login(from_document(different_outer).unwrap()).is_err());
    for persisted in [Value::Null, json!("true"), json!(1)] {
        let mut document = fixture("login-true");
        document["result"]["session_persisted"] = persisted;
        assert!(login(from_document(document).unwrap()).is_err());
    }

    let mut boundary = fixture("login-true");
    boundary["active_profile"] = Value::Null;
    boundary["result"]["active_profile"] = json!("漢".repeat(160));
    assert!(matches!(
        login(from_document(boundary).unwrap()).unwrap(),
        SignInResult::SignedIn { .. }
    ));
}

#[test]
fn python_logout_keeps_known_and_unknown_automation_separate_and_propagates_refusal() {
    for (case, enabled) in [
        ("logout-true", json!(true)),
        ("logout-false", json!(false)),
        ("logout-none", Value::Null),
    ] {
        let outcome = logout(from_document(fixture(case)).unwrap()).ok().unwrap();
        assert_eq!(
            serde_json::to_value(outcome).unwrap(),
            json!({
                "remainingAccess":{"automationEnabled":enabled,"automationRevoked":false}
            })
        );
    }
    let refusal = logout(from_document(fixture("logout-refused")).unwrap())
        .err()
        .unwrap();
    assert_eq!(
        serde_json::to_value(refusal).unwrap(),
        json!({"code":"absent","retryAfterSeconds":null})
    );
    let mut revoked = fixture("logout-true");
    revoked["result"]["automation_revoked"] = json!(true);
    assert!(logout(from_document(revoked).unwrap()).is_err());
}

fn output_of(document: Value) -> Output {
    let success = document["status"] != "error";
    let bytes = Zeroizing::new(serde_json::to_vec(&document).unwrap());
    let empty = Zeroizing::new(Vec::new());
    let (stdout, stderr) = if success {
        (bytes, empty)
    } else {
        (empty, bytes)
    };
    Output {
        success,
        stdout,
        stderr,
    }
}

#[test]
fn python_profile_list_crosses_as_labels_and_the_selection_only() {
    let listed = profiles(&output_of(fixture("profile-list"))).ok().unwrap();
    assert_eq!(
        serde_json::to_value(listed).unwrap(),
        json!({
            "profiles": [
                {"name": "Another profile", "active": false},
                {"name": "Test profile", "active": true}
            ],
            "complete": true
        })
    );
    let none = profiles(&output_of(fixture("profile-list-empty")))
        .ok()
        .unwrap();
    assert_eq!(
        serde_json::to_value(none).unwrap(),
        json!({"profiles": [], "complete": true})
    );
}

#[test]
fn a_listing_the_product_could_not_trust_is_not_an_empty_one() {
    let listed = profiles(&output_of(fixture("profile-list-incoherent")))
        .ok()
        .unwrap();
    assert_eq!(
        serde_json::to_value(listed).unwrap(),
        json!({"profiles": [], "complete": false})
    );
}

#[test]
fn a_listing_with_an_unnamed_profile_or_two_selected_is_refused() {
    let mut unnamed = fixture("profile-list");
    unnamed["result"]["profiles"][0]["name"] = json!("");
    assert!(profiles(&output_of(unnamed)).is_err());
    let mut two = fixture("profile-list");
    two["result"]["profiles"][0]["active"] = json!(true);
    assert!(profiles(&output_of(two)).is_err());
    let mut other = fixture("profile-list");
    other["command"] = json!("config.profile.status");
    assert!(profiles(&output_of(other)).is_err());
}

#[test]
fn python_profile_creation_reports_the_label_and_only_a_creation() {
    assert_eq!(
        serde_json::to_value(created(from_document(fixture("profile-create")).unwrap()).unwrap())
            .unwrap(),
        json!({"kind": "created", "name": "Test profile"})
    );
    for status in ["updated", "unchanged", "abandoned"] {
        let mut document = fixture("profile-create");
        document["result"]["status"] = json!(status);
        assert!(
            created(from_document(document).unwrap()).is_err(),
            "{status}"
        );
    }
}

#[test]
fn python_profile_creation_refusals_keep_their_reason_and_name_a_taken_label() {
    for (case, code) in [
        ("profile-create-taken", "profile_already_exists"),
        ("profile-create-short-password", "too_few_scalars"),
        ("profile-create-boundary", "REFUSED_CLI_BOUNDARY"),
    ] {
        assert_eq!(
            serde_json::to_value(created(from_document(fixture(case)).unwrap()).unwrap()).unwrap(),
            json!({"kind": "refused", "code": code, "retryAfterSeconds": null}),
            "{case}"
        );
    }
    // A registration refusal that says more than the label is not that one.
    let mut other = fixture("profile-create-taken");
    other["error"]["context"]["detail"] = json!("x");
    assert_eq!(
        serde_json::to_value(created(from_document(other).unwrap()).unwrap()).unwrap()["code"],
        "REFUSED_PROFILE_REGISTRATION"
    );
}
