"""Catalogue entry for the AEAT *Consulta de pagos / NRC* procedure page.

Exposes :data:`ENTRY`, a frozen :class:`aeat.domain.portals.PortalMetadata`
under :attr:`aeat.domain.portals.PortalCategory.PAYMENT`. Used to query
the status of past payments and recover the NRC tokens generated by
each settlement.
"""

from __future__ import annotations

from .._categories import AuthMethod, PortalCategory, Subdomain, UrlStability
from .._codes import Portal
from .._metadata import PortalMetadata
from ._common import build_entry

ENTRY: PortalMetadata = build_entry(
    portal=Portal.PORTAL_CONSULTA_PAGOS,
    path="/Sede/procedimientoini/ES09.shtml",
    subdomain=Subdomain.SEDE,
    category=PortalCategory.PAYMENT,
    auth_methods=(
        AuthMethod.CERTIFICATE,
        AuthMethod.CLAVE_PIN,
        AuthMethod.CLAVE_PERMANENTE,
        AuthMethod.DNIE,
    ),
    url_stability=UrlStability.STABLE_WITHIN_CAMPAIGN,
    label="entries.portal_consulta_pagos.label",
    purpose="entries.portal_consulta_pagos.purpose",
)
"""Frozen :class:`aeat.domain.portals.PortalMetadata` for the payment / NRC enquiry page."""
