# Run with cmake -DTEST_OUTPUT_DIR=<isolated absolute path> -P this-file.
include("${CMAKE_CURRENT_LIST_DIR}/../RustLinker.cmake")
if(DEFINED TEST_CASE)
  set(CMAKE_C_COMPILER "${CMAKE_COMMAND}")
  if(TEST_CASE STREQUAL "native")
    set(expected "${CMAKE_COMMAND}")
  elseif(TEST_CASE STREQUAL "explicit")
    set(CMAKE_SYSROOT "/declared/sysroot")
    set(CADRUMO_RUST_LINKER "${CMAKE_COMMAND}")
    set(expected "${CMAKE_COMMAND}")
  elseif(TEST_CASE STREQUAL "cross")
    set(CMAKE_CROSSCOMPILING TRUE)
  elseif(TEST_CASE STREQUAL "relative")
    set(CADRUMO_RUST_LINKER "relative-linker")
  elseif(TEST_CASE STREQUAL "missing")
    set(CADRUMO_RUST_LINKER "${TEST_OUTPUT_DIR}/nonexistent-linker")
  elseif(TEST_CASE STREQUAL "directory")
    set(CADRUMO_RUST_LINKER "${TEST_OUTPUT_DIR}")
  else()
    set("${TEST_CASE}" "/explicit/target-argument")
  endif()
  cadrumo_posix_rust_linker(actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Unexpected linker selection: ${actual}")
  endif()
  return()
endif()
if(NOT IS_ABSOLUTE "${TEST_OUTPUT_DIR}")
  message(FATAL_ERROR "Supply an isolated absolute TEST_OUTPUT_DIR")
endif()
file(MAKE_DIRECTORY "${TEST_OUTPUT_DIR}")
foreach(case native explicit cross relative missing directory CMAKE_SYSROOT
    CMAKE_SYSROOT_LINK CMAKE_C_COMPILER_TARGET CMAKE_C_COMPILER_EXTERNAL_TOOLCHAIN
    CMAKE_C_COMPILER_ARG1 CMAKE_OSX_SYSROOT CMAKE_C_FLAGS CMAKE_EXE_LINKER_FLAGS)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DTEST_CASE=${case}"
    "-DTEST_OUTPUT_DIR=${TEST_OUTPUT_DIR}" -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE status OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
  file(WRITE "${TEST_OUTPUT_DIR}/${case}.log" "${stdout}${stderr}")
  if(case STREQUAL "native" OR case STREQUAL "explicit")
    if(NOT status EQUAL 0)
      message(FATAL_ERROR "${case} refused a valid configuration: ${stderr}")
    endif()
  elseif(status EQUAL 0 OR NOT stderr MATCHES "CADRUMO_RUST_LINKER")
    message(FATAL_ERROR "${case} did not produce the expected linker refusal: ${stderr}")
  endif()
endforeach()
message(STATUS "All 14 Rust linker admission cases passed")
