"""Publish generated bytes without invalidating consumers of unchanged output."""

from pathlib import Path


def write_bytes(path: Path, content: bytes) -> None:
    """Keep existing timestamps when the generated content is identical."""
    if not path.is_file() or path.read_bytes() != content:
        path.write_bytes(content)


def write_text(path: Path, content: str) -> None:
    """Write deterministic UTF-8 bytes, independent of the builder's newline mode."""
    write_bytes(path, content.encode("utf-8"))
