"""Tests for the committed miss-rate report writer.

`dev.quality.module_test_reach` listed `dev/docs/terminology/miss_rate.py` as
unreached and writing to the tree. Its sibling `_miss_rate.py` - the evaluator -
is well covered by `test_miss_rate.py`; the writer that turns an evaluation into
the committed artifact had nothing.

The module exists because the report artifacts were once produced ad hoc, and
its docstring makes a reproducibility claim: a report regenerates byte-comparably
from the committed mapping and held-out corpus alone. That claim is the thing
worth pinning, because an artifact nobody can regenerate is indistinguishable
from one that was edited by hand.

The command used to measure twice - once to write and once to print - so the
numbers on the console were not read from the file they described. Those two
reads could disagree whenever the mapping or the corpus was regenerated between
them, and the second walk was paid for nothing. The writer now returns its
evaluation and the command prints that; the agreement is asserted here.
"""

from __future__ import annotations

import json
import pathlib

import pytest
from typer.testing import CliRunner

from ..miss_rate import app, write_miss_rate_report

pytestmark = [pytest.mark.unit, pytest.mark.hex_core, pytest.mark.docs]


def _written(target: pathlib.Path) -> dict[str, object]:
    return json.loads(target.read_text(encoding="utf-8"))


def test_the_writer_returns_the_evaluation_it_wrote(tmp_path: pathlib.Path) -> None:
    """The return value is what lets a caller report without measuring again."""
    target = tmp_path / "report.json"

    evaluation = write_miss_rate_report(target, note="provenance")

    written = _written(target)["evaluation"]
    assert isinstance(written, dict)
    assert written["case_count"] == evaluation.case_count
    assert written["hit_count"] == evaluation.hit_count
    assert written["miss_rate"] == evaluation.miss_rate


def test_the_note_is_carried_into_the_document_verbatim(tmp_path: pathlib.Path) -> None:
    """Provenance is the one field a caller supplies, so it must survive intact."""
    target = tmp_path / "report.json"
    note = "Regenerated from the committed mapping; see the held-out corpus."

    write_miss_rate_report(target, note=note)

    assert _written(target)["note"] == note


def test_the_document_is_sorted_json_with_a_final_newline(tmp_path: pathlib.Path) -> None:
    """A committed artifact is read as a diff, so ordering is part of its contract."""
    target = tmp_path / "report.json"

    write_miss_rate_report(target, note="ordering")

    text = target.read_text(encoding="utf-8")
    assert text.endswith(chr(10))
    assert list(_written(target)) == sorted(_written(target))


def test_regenerating_the_report_reproduces_it_byte_for_byte(tmp_path: pathlib.Path) -> None:
    """The module's reason for existing, asserted rather than described.

    An artifact that cannot be regenerated byte-comparably from committed inputs
    cannot be distinguished from one that was hand-edited, which is the ad-hoc
    production this writer replaced.
    """
    first = tmp_path / "first.json"
    second = tmp_path / "second.json"

    write_miss_rate_report(first, note="same note")
    write_miss_rate_report(second, note="same note")

    assert first.read_bytes() == second.read_bytes()


def test_a_different_note_is_the_only_difference_between_two_reports(
    tmp_path: pathlib.Path,
) -> None:
    """Determinism must be a property of the measurement, not of the whole file.

    Asserting only that two identical calls match would also pass if the writer
    echoed its input and measured nothing.
    """
    first = tmp_path / "first.json"
    second = tmp_path / "second.json"

    write_miss_rate_report(first, note="one")
    write_miss_rate_report(second, note="two")

    assert _written(first)["evaluation"] == _written(second)["evaluation"]
    assert _written(first)["note"] != _written(second)["note"]


def test_the_command_prints_the_numbers_it_wrote(tmp_path: pathlib.Path) -> None:
    """The console and the file are one measurement, and this is what says so.

    Before the writer returned its evaluation the command measured a second
    time, so a regeneration of the mapping or corpus between the two reads left
    a report on disk that its own console output contradicted.
    """
    target = tmp_path / "report.json"

    result = CliRunner().invoke(app, ["report", "--output", str(target), "--note", "console parity"])

    assert result.exit_code == 0, result.output
    evaluation = _written(target)["evaluation"]
    assert isinstance(evaluation, dict)
    assert f"cases {evaluation['case_count']}" in result.output
    assert f"hits {evaluation['hit_count']}" in result.output
    assert f"miss-rate {evaluation['miss_rate']:.4f}" in result.output


def test_the_command_names_the_path_it_wrote(tmp_path: pathlib.Path) -> None:
    """An operator regenerating an artifact needs to see where it landed."""
    target = tmp_path / "nested" / "report.json"
    target.parent.mkdir()

    result = CliRunner().invoke(app, ["report", "--output", str(target), "--note", "path"])

    assert result.exit_code == 0, result.output
    assert str(target) in result.output
    assert target.is_file()
