from .models import _Casilla, CasillaDataType, SelectOption

CENSAL_CASILLAS: tuple[_Casilla, ...] = (
    _Casilla(
        casilla_id="100",
        label_es="Solicitud de alta en el censo de empresarios",
        label_en="Request to enrol in the census of business operators",
        label_hu="Bejelentkezés a vállalkozói nyilvántartásba",
        help_es="Marque esta casilla para comunicar el inicio de la actividad económica.",
        help_en="Tick this box to report the start of the economic activity.",
        help_hu="Jelölje be a gazdasági tevékenység megkezdésének bejelentéséhez.",
        data_type=CasillaDataType.BOOLEAN,
        section="A. Causas de presentación",
    ),
    _Casilla(
        casilla_id="120",
        label_es="Modificación de datos relativos al IVA",
        label_en="Update of VAT-related data",
        label_hu="Az ÁFA-adatok módosítása",
        help_es="Marque para modificar los datos relativos al régimen de IVA.",
        help_en="Tick this box when changing the VAT regime data.",
        help_hu="Jelölje be az ÁFA-rendszer adatainak módosításához.",
        data_type=CasillaDataType.BOOLEAN,
        section="A. Causas de presentación",
    ),
    _Casilla(
        casilla_id="150",
        label_es="Baja en el censo de empresarios",
        label_en="Removal from the census of business operators",
        label_hu="Kijelentkezés a vállalkozói nyilvántartásból",
        help_es="Marque esta casilla para comunicar el cese de la actividad económica.",
        help_en="Tick this box to report the cessation of the economic activity.",
        help_hu="Jelölje be a gazdasági tevékenység megszüntetésének bejelentéséhez.",
        data_type=CasillaDataType.BOOLEAN,
        section="A. Causas de presentación",
    ),
    _Casilla(
        casilla_id="402",
        label_es="Régimen general del IVA",
        label_en="General VAT regime",
        label_hu="Általános ÁFA-rendszer",
        help_es="Marque si tributa por el régimen general del IVA (LIVA art. 90/91).",
        help_en="Tick if you fall under the general VAT regime (Spanish VAT Act art. 90/91).",
        help_hu="Jelölje be, ha az általános ÁFA-rendszer alá tartozik (LIVA 90/91. cikk).",
        data_type=CasillaDataType.BOOLEAN,
        section="C. Régimen IVA",
    ),
    _Casilla(
        casilla_id="403",
        label_es="Régimen simplificado del IVA",
        label_en="Simplified VAT regime",
        label_hu="Egyszerűsített ÁFA-rendszer",
        help_es="Marque si tributa por el régimen simplificado del IVA.",
        help_en="Tick if you fall under the simplified VAT regime.",
        help_hu="Jelölje be, ha az egyszerűsített ÁFA-rendszer alá tartozik.",
        data_type=CasillaDataType.BOOLEAN,
        section="C. Régimen IVA",
    ),
)

M232_CASILLAS: tuple[_Casilla, ...] = (
    _Casilla(
        casilla_id="01",
        label_es="N.º registros — operaciones con personas o entidades vinculadas",
        label_en="Records — transactions with related parties",
        label_hu="Kapcsolt vállalkozásokkal folytatott ügyletek rekordjainak száma",
        help_es="Total de registros de operaciones con personas o entidades vinculadas declarados.",
        help_en="Total related-party transaction records declared.",
        help_hu="A bejelentett kapcsolt vállalkozásokkal folytatott ügyletek rekordjainak száma.",
        data_type=CasillaDataType.INTEGER,
        section="Cuadro I. Operaciones con personas o entidades vinculadas",
    ),
    _Casilla(
        casilla_id="02",
        label_es="N.º registros — operaciones con activos intangibles",
        label_en="Records — intangible asset transactions",
        label_hu="Immateriális eszközökkel kapcsolatos ügyletek rekordjainak száma",
        help_es="Total de registros de operaciones con activos intangibles que se han acogido al beneficio fiscal del art. 23 LIS.",
        help_en="Total intangible-asset operation records that benefit from the LIS art. 23 incentive.",
        help_hu="Az LIS 23. cikke szerinti kedvezményt igénylő ügyletek rekordjainak száma.",
        data_type=CasillaDataType.INTEGER,
        section="Cuadro II. Operaciones con activos intangibles",
    ),
    _Casilla(
        casilla_id="03",
        label_es="N.º registros — operaciones con paraísos fiscales",
        label_en="Number of tax-haven transaction records",
        label_hu="Adóparadicsomokkal folytatott ügyletek rekordjainak száma",
        help_es="Total de registros de operaciones realizadas con países o territorios calificados como paraísos fiscales.",
        help_en="Total operation records with countries classified as tax havens.",
        help_hu="Az adóparadicsomnak minősített országokkal folytatott ügyletek rekordjainak száma.",
        data_type=CasillaDataType.INTEGER,
        section="Cuadro III. Operaciones con paraísos fiscales",
    ),
)

M369_CASILLAS: tuple[_Casilla, ...] = (
    _Casilla(
        casilla_id="01",
        label_es="Total bases imponibles",
        label_en="Total taxable bases",
        label_hu="Összes adóalap",
        help_es="Suma de las bases imponibles declaradas para cada Estado miembro de consumo y tipo aplicable.",
        help_en="Sum of taxable bases declared for each Member State of consumption and applicable rate.",
        help_hu="A bejelentett adóalapok összege fogyasztási tagállam és alkalmazandó kulcs szerint.",
        section="Resumen",
    ),
    _Casilla(
        casilla_id="02",
        label_es="Total cuotas IVA devengadas",
        label_en="Total output VAT",
        label_hu="Összes felszámított ÁFA",
        help_es="Suma de las cuotas de IVA devengadas en los Estados miembros de consumo en el régimen OSS / IOSS.",
        help_en="Sum of output VAT due in the Member States of consumption under OSS / IOSS.",
        help_hu="A fogyasztási tagállamokban felszámított ÁFA összege OSS / IOSS rendszerben.",
        section="Resumen",
    ),
    _Casilla(
        casilla_id="03",
        label_es="Total a ingresar",
        label_en="Total payable",
        label_hu="Fizetendő összeg",
        help_es="Importe total que debe ingresarse al erario español, equivalente a la suma de cuotas devengadas (no se admiten deducciones en este régimen).",
        help_en="Total amount payable to the Spanish treasury — equal to the output VAT sum (deductions are not allowed under this regime).",
        help_hu="A spanyol kincstárnak fizetendő teljes összeg, ami megegyezik a felszámított ÁFA-val (e rendszerben levonás nem alkalmazható).",
        section="Resumen",
    ),
)

M720_CASILLAS: tuple[_Casilla, ...] = (
    _Casilla(
        casilla_id="01",
        label_es="N.º registros — clave C (cuentas en entidades financieras)",
        label_en="Records — key C (accounts in financial institutions)",
        label_hu="Rekordok — C kulcs (külföldi pénzintézeti számlák)",
        help_es="Total de cuentas en entidades financieras situadas en el extranjero declaradas (clave C, DA 18ª LGT).",
        help_en="Total accounts at foreign financial institutions declared (key C, DA 18 LGT).",
        help_hu="A bejelentett külföldi pénzintézeti számlák száma (C kulcs, LGT 18. kiegészítő rendelkezés).",
        data_type=CasillaDataType.INTEGER,
        section="Resumen — clave C",
    ),
    _Casilla(
        casilla_id="02",
        label_es="N.º registros — clave V (valores, seguros, rentas)",
        label_en="Records — key V (securities, insurance, annuities)",
        label_hu="Rekordok — V kulcs (értékpapírok, biztosítások, járadékok)",
        help_es="Total de valores, seguros y rentas situados en el extranjero declarados (clave V).",
        help_en="Total securities, insurance contracts and annuities held abroad (key V).",
        help_hu="A bejelentett külföldi értékpapírok, biztosítások és járadékok száma (V kulcs).",
        data_type=CasillaDataType.INTEGER,
        section="Resumen — clave V",
    ),
    _Casilla(
        casilla_id="03",
        label_es="N.º registros — clave I (bienes inmuebles en el extranjero)",
        label_en="Records — key I (foreign real estate)",
        label_hu="Rekordok — I kulcs (külföldi ingatlanok)",
        help_es="Total de bienes inmuebles y derechos sobre ellos situados en el extranjero declaradas (clave I).",
        help_en="Total foreign real estate and rights thereon declared (key I).",
        help_hu="A bejelentett külföldi ingatlanok és ingatlanjogok száma (I kulcs).",
        data_type=CasillaDataType.INTEGER,
        section="Resumen — clave I",
    ),
)

M111_AUGMENT: tuple[_Casilla, ...] = (
    _Casilla(
        casilla_id="01",
        label_es="N.º perceptores — rendimientos del trabajo",
        label_en="Recipients — work income",
        label_hu="Munkajövedelem-kedvezményezettek",
        help_es="Número de perceptores con rendimientos del trabajo en el trimestre.",
        help_en="Number of recipients of work income in the quarter.",
        help_hu="A negyedévben munkajövedelemben részesülők száma.",
        data_type=CasillaDataType.INTEGER,
        section="Apartado I — Rendimientos del trabajo",
    ),
    _Casilla(
        casilla_id="02",
        label_es="Importe de las percepciones — rendimientos del trabajo",
        label_en="Perceptions amount — work income",
        label_hu="Munkajövedelem összege",
        help_es="Suma de las percepciones íntegras satisfechas por rendimientos del trabajo en el trimestre.",
        help_en="Sum of gross perceptions paid as work income in the quarter.",
        help_hu="A negyedévben munkajövedelemként kifizetett bruttó jövedelmek összege.",
        section="Apartado I — Rendimientos del trabajo",
    ),
    _Casilla(
        casilla_id="04",
        label_es="N.º perceptores — actividades económicas",
        label_en="Recipients — business income",
        label_hu="Vállalkozói-jövedelem kedvezményezettek",
        help_es="Número de perceptores con rendimientos de actividades económicas en el trimestre.",
        help_en="Number of recipients of business income in the quarter.",
        help_hu="A negyedévben vállalkozói jövedelemben részesülők száma.",
        data_type=CasillaDataType.INTEGER,
        section="Apartado II — Actividades económicas",
    ),
    _Casilla(
        casilla_id="05",
        label_es="Importe de las percepciones — actividades económicas",
        label_en="Perceptions amount — business income",
        label_hu="Vállalkozói jövedelem összege",
        help_es="Suma de las percepciones íntegras satisfechas por actividades económicas en el trimestre.",
        help_en="Sum of gross perceptions paid as business income in the quarter.",
        help_hu="A negyedévi vállalkozói bruttó jövedelmek összege.",
        section="Apartado II — Actividades económicas",
    ),
    _Casilla(
        casilla_id="07",
        label_es="N.º perceptores — premios",
        label_en="Recipients — prizes",
        label_hu="Nyeremény-kedvezményezettek",
        help_es="Número de perceptores de premios sujetos a retención (LIRPF art. 101.7).",
        help_en="Number of prize recipients subject to withholding (LIRPF art. 101.7).",
        help_hu="A nyereményadó-köteles kedvezményezettek száma.",
        data_type=CasillaDataType.INTEGER,
        section="Apartado III — Premios",
    ),
    _Casilla(
        casilla_id="10",
        label_es="N.º perceptores — ganancias patrimoniales",
        label_en="Recipients — capital gains",
        label_hu="Vagyonnyereség-kedvezményezettek",
        help_es="Número de perceptores con ganancias patrimoniales por aprovechamientos forestales en montes públicos.",
        help_en="Number of recipients of capital gains from forestry on public lands.",
        help_hu="Az állami erdőkben elért vagyonnyereségben részesülők száma.",
        data_type=CasillaDataType.INTEGER,
        section="Apartado IV — Ganancias patrimoniales",
    ),
    _Casilla(
        casilla_id="13",
        label_es="N.º perceptores — contraprestaciones en especie",
        label_en="Recipients — in-kind perceptions",
        label_hu="Természetbeni jövedelmek kedvezményezettjei",
        help_es="Número de perceptores de contraprestaciones en especie en el trimestre.",
        help_en="Number of in-kind perception recipients in the quarter.",
        help_hu="A természetbeni juttatásban részesülők száma a negyedévben.",
        data_type=CasillaDataType.INTEGER,
        section="Apartado V — Contraprestaciones en especie",
    ),
    _Casilla(
        casilla_id="14",
        label_es="Valoración percepciones — contraprestaciones en especie",
        label_en="Valuation — in-kind perceptions",
        label_hu="Természetbeni juttatások értéke",
        help_es="Valor fiscal de las contraprestaciones en especie satisfechas en el trimestre.",
        help_en="Tax-valuation of in-kind perceptions paid in the quarter.",
        help_hu="A természetbeni juttatások adóértéke a negyedévben.",
        section="Apartado V — Contraprestaciones en especie",
    ),
    _Casilla(
        casilla_id="16",
        label_es="N.º perceptores — cesión de derechos de imagen",
        label_en="Recipients — image-rights assignment",
        label_hu="Képmás-jog átruházás kedvezményezettjei",
        help_es="Número de perceptores por imputación de rentas por cesión de derechos de imagen (LIRPF art. 92).",
        help_en="Number of recipients of imputed image-rights income (LIRPF art. 92).",
        help_hu="Képmás-jog jövedelemben részesülők száma.",
        data_type=CasillaDataType.INTEGER,
        section="Apartado VI — Cesión derechos imagen",
    ),
    _Casilla(
        casilla_id="17",
        label_es="Importe percepciones — cesión de derechos de imagen",
        label_en="Perceptions amount — image rights",
        label_hu="Képmás-jog jövedelem",
        help_es="Suma de las imputaciones de rentas por cesión de derechos de imagen en el trimestre.",
        help_en="Sum of imputed image-rights income in the quarter.",
        help_hu="Képmás-jog átruházás miatti jövedelmek negyedévi összege.",
        section="Apartado VI — Cesión derechos imagen",
    ),
)

M190_CASILLAS: tuple[_Casilla, ...] = (
    _Casilla(
        casilla_id="01",
        label_es="N.º perceptores — rendimientos del trabajo",
        label_en="Recipients — work income",
        label_hu="Munkajövedelem-kedvezményezettek",
        help_es="Total acumulado anual de perceptores con rendimientos del trabajo (LIRPF art. 17).",
        help_en="Annual cumulative number of recipients of work income (LIRPF art. 17).",
        help_hu="Munkajövedelem-kedvezményezettek éves száma (LIRPF 17. cikk).",
        data_type=CasillaDataType.INTEGER,
        section="Apartado I — Rendimientos del trabajo",
    ),
    _Casilla(
        casilla_id="02",
        label_es="Importe percepciones — rendimientos del trabajo",
        label_en="Perceptions amount — work income",
        label_hu="Munkajövedelem összege",
        help_es="Suma anual de las percepciones íntegras satisfechas por rendimientos del trabajo.",
        help_en="Annual sum of gross perceptions paid as work income.",
        help_hu="A munkajövedelemként kifizetett bruttó jövedelmek éves összege.",
        section="Apartado I — Rendimientos del trabajo",
    ),
    _Casilla(
        casilla_id="03",
        label_es="Retenciones — rendimientos del trabajo",
        label_en="Withholdings — work income",
        label_hu="Munkajövedelem-levonás",
        help_es="Suma anual de las retenciones e ingresos a cuenta practicados sobre rendimientos del trabajo.",
        help_en="Annual sum of withholdings and payments on account on work income.",
        help_hu="Munkajövedelem után visszatartott és befizetett összegek éves összege.",
        section="Apartado I — Rendimientos del trabajo",
    ),
    _Casilla(
        casilla_id="04",
        label_es="N.º perceptores — actividades económicas",
        label_en="Recipients — business income",
        label_hu="Vállalkozói-jövedelem kedvezményezettek",
        help_es="Total acumulado anual de perceptores con rendimientos de actividades económicas.",
        help_en="Annual cumulative number of recipients of business income.",
        help_hu="Vállalkozói jövedelemben részesülő személyek éves száma.",
        data_type=CasillaDataType.INTEGER,
        section="Apartado II — Actividades económicas",
    ),
    _Casilla(
        casilla_id="05",
        label_es="Importe percepciones — actividades económicas",
        label_en="Perceptions amount — business income",
        label_hu="Vállalkozói jövedelem összege",
        help_es="Suma anual de las percepciones íntegras satisfechas por actividades económicas.",
        help_en="Annual sum of gross perceptions paid as business income.",
        help_hu="Vállalkozási jövedelem éves bruttó összege.",
        section="Apartado II — Actividades económicas",
    ),
    _Casilla(
        casilla_id="06",
        label_es="Retenciones — actividades económicas",
        label_en="Withholdings — business income",
        label_hu="Vállalkozói-jövedelem levonás",
        help_es="Suma anual de las retenciones practicadas a profesionales y actividades económicas (15%/7%).",
        help_en="Annual sum of withholdings on professionals and business activities (15% / 7%).",
        help_hu="Szakemberek és vállalkozók után visszatartott összegek éves összege (15% / 7%).",
        section="Apartado II — Actividades económicas",
    ),
    _Casilla(
        casilla_id="07",
        label_es="N.º perceptores — premios",
        label_en="Recipients — prizes",
        label_hu="Nyeremény-kedvezményezettek",
        help_es="Total anual de perceptores de premios sujetos a retención (LIRPF art. 101.7).",
        help_en="Annual number of recipients of prizes subject to withholding (LIRPF art. 101.7).",
        help_hu="A levonás alá eső nyereményekben részesülők éves száma.",
        data_type=CasillaDataType.INTEGER,
        section="Apartado III — Premios",
    ),
    _Casilla(
        casilla_id="08",
        label_es="Importe percepciones — premios",
        label_en="Perceptions amount — prizes",
        label_hu="Nyeremény összege",
        help_es="Suma anual de los premios satisfechos sometidos a retención.",
        help_en="Annual sum of taxable prizes paid.",
        help_hu="A levonás alá eső nyeremények éves összege.",
        section="Apartado III — Premios",
    ),
    _Casilla(
        casilla_id="09",
        label_es="Retenciones — premios",
        label_en="Withholdings — prizes",
        label_hu="Nyeremény-levonás",
        help_es="Suma anual de las retenciones practicadas sobre premios al tipo fijo del 19%.",
        help_en="Annual sum of withholdings on prizes at the fixed 19% rate.",
        help_hu="A nyeremények után 19%-os fix kulccsal levont összegek éves összege.",
        section="Apartado III — Premios",
    ),
    _Casilla(
        casilla_id="10",
        label_es="N.º perceptores — ganancias patrimoniales (aprovechamientos forestales)",
        label_en="Recipients — capital gains (forestry)",
        label_hu="Erdészeti vagyonnyereség-kedvezményezettek",
        help_es="Total anual de perceptores de ganancias derivadas de aprovechamientos forestales en montes públicos.",
        help_en="Annual number of recipients of forestry-derived capital gains on public lands.",
        help_hu="Az állami erdőkben elért vagyonnyereségben részesülők éves száma.",
        data_type=CasillaDataType.INTEGER,
        section="Apartado IV — Ganancias patrimoniales",
    ),
    _Casilla(
        casilla_id="11",
        label_es="Importe percepciones — ganancias patrimoniales (aprovechamientos forestales)",
        label_en="Perceptions amount — forestry capital gains",
        label_hu="Erdészeti vagyonnyereség összege",
        help_es="Suma anual de las percepciones por aprovechamientos forestales en montes públicos.",
        help_en="Annual sum of forestry capital gains on public lands.",
        help_hu="Az erdészeti vagyonnyereségek éves összege.",
        section="Apartado IV — Ganancias patrimoniales",
    ),
    _Casilla(
        casilla_id="12",
        label_es="Retenciones — ganancias patrimoniales",
        label_en="Withholdings — capital gains",
        label_hu="Vagyonnyereség-levonás",
        help_es="Suma anual de las retenciones practicadas sobre ganancias patrimoniales por aprovechamientos forestales (19%).",
        help_en="Annual sum of withholdings on forestry-related capital gains (19%).",
        help_hu="Az erdészeti vagyonnyereségek után 19%-kal levont összegek éves összege.",
        section="Apartado IV — Ganancias patrimoniales",
    ),
    _Casilla(
        casilla_id="13",
        label_es="N.º perceptores — contraprestaciones en especie",
        label_en="Recipients — in-kind perceptions",
        label_hu="Természetbeni-jövedelem kedvezményezettek",
        help_es="Total anual de perceptores de retribuciones en especie sujetas a ingreso a cuenta.",
        help_en="Annual number of recipients of in-kind perceptions subject to a payment on account.",
        help_hu="A természetbeni juttatásban részesülők éves száma.",
        data_type=CasillaDataType.INTEGER,
        section="Apartado V — Contraprestaciones en especie",
    ),
    _Casilla(
        casilla_id="14",
        label_es="Valoración percepciones — contraprestaciones en especie",
        label_en="Valuation — in-kind perceptions",
        label_hu="Természetbeni juttatások értéke",
        help_es="Suma anual del valor fiscal de las contraprestaciones en especie satisfechas.",
        help_en="Annual sum of the tax-valuation of in-kind perceptions paid.",
        help_hu="A természetbeni juttatások adóértékének éves összege.",
        section="Apartado V — Contraprestaciones en especie",
    ),
    _Casilla(
        casilla_id="15",
        label_es="Ingresos a cuenta — contraprestaciones en especie",
        label_en="Payments on account — in-kind",
        label_hu="Természetbeni-előlegek",
        help_es="Suma anual de los ingresos a cuenta practicados sobre contraprestaciones en especie.",
        help_en="Annual sum of payments on account on in-kind perceptions.",
        help_hu="Természetbeni juttatásokra alkalmazott éves előlegek összege.",
        section="Apartado V — Contraprestaciones en especie",
    ),
    _Casilla(
        casilla_id="16",
        label_es="N.º perceptores — cesión de derechos de imagen",
        label_en="Recipients — image-rights assignment",
        label_hu="Képmás-jog átruházás kedvezményezettek",
        help_es="Total anual de perceptores por imputación de rentas por cesión de derechos de imagen (LIRPF art. 92).",
        help_en="Annual number of recipients of imputed image-rights income (LIRPF art. 92).",
        help_hu="Képmás-jog átruházás miatti beszámított jövedelmekben részesülők éves száma.",
        data_type=CasillaDataType.INTEGER,
        section="Apartado VI — Cesión derechos imagen",
    ),
    _Casilla(
        casilla_id="17",
        label_es="Importe percepciones — cesión de derechos de imagen",
        label_en="Perceptions amount — image rights",
        label_hu="Képmás-jog átruházás jövedelme",
        help_es="Suma anual de las imputaciones de rentas por cesión de derechos de imagen.",
        help_en="Annual sum of imputed image-rights income.",
        help_hu="Képmás-jog átruházás miatti éves jövedelem összege.",
        section="Apartado VI — Cesión derechos imagen",
    ),
    _Casilla(
        casilla_id="18",
        label_es="Retenciones — cesión de derechos de imagen",
        label_en="Withholdings — image rights",
        label_hu="Képmás-jog átruházás levonás",
        help_es="Suma anual de las retenciones e ingresos a cuenta por imputación de rentas por cesión de derechos de imagen.",
        help_en="Annual sum of withholdings on imputed image-rights income.",
        help_hu="Képmás-jog jövedelemre alkalmazott éves levonás összege.",
        section="Apartado VI — Cesión derechos imagen",
    ),
    _Casilla(
        casilla_id="19",
        label_es="Total perceptores",
        label_en="Total recipients",
        label_hu="Összes kedvezményezett",
        help_es="Suma global de perceptores declarados en el modelo 190.",
        help_en="Global sum of recipients declared in form 190.",
        help_hu="A 190-es nyomtatványban szereplő összes kedvezményezett.",
        data_type=CasillaDataType.INTEGER,
        computed=True,
        formula_expression="(01 + 04 + 07 + 10 + 13 + 16)",
        formula_refs=("01", "04", "07", "10", "13", "16"),
        section="Resumen — Totales",
    ),
    _Casilla(
        casilla_id="20",
        label_es="Total percepciones",
        label_en="Total perceptions",
        label_hu="Összes jövedelem",
        help_es="Suma global de las percepciones íntegras declaradas en el modelo 190.",
        help_en="Global sum of gross perceptions declared in form 190.",
        help_hu="A 190-es nyomtatványban szereplő bruttó jövedelmek összege.",
        computed=True,
        formula_expression="(02 + 05 + 08 + 11 + 14 + 17)",
        formula_refs=("02", "05", "08", "11", "14", "17"),
        section="Resumen — Totales",
    ),
    _Casilla(
        casilla_id="21",
        label_es="Total retenciones e ingresos a cuenta",
        label_en="Total withholdings and payments on account",
        label_hu="Összes levonás és előleg",
        help_es="Suma global de las retenciones e ingresos a cuenta declarados en el modelo 190.",
        help_en="Global sum of withholdings and payments on account declared in form 190.",
        help_hu="A 190-es nyomtatványban szereplő levonások és előlegek összege.",
        computed=True,
        formula_expression="(03 + 06 + 09 + 12 + 15 + 18)",
        formula_refs=("03", "06", "09", "12", "15", "18"),
        section="Resumen — Totales",
    ),
)

M193_CASILLAS: tuple[_Casilla, ...] = (
    _Casilla(
        casilla_id="01",
        label_es="N.º total perceptores",
        label_en="Total recipients",
        label_hu="Összes kedvezményezett",
        help_es="Total acumulado anual de perceptores de rendimientos del capital mobiliario sujetos a retención (LIRPF art. 25).",
        help_en="Annual cumulative number of recipients of investment income subject to withholding (LIRPF art. 25).",
        help_hu="Tőkejövedelemben részesülők éves száma.",
        data_type=CasillaDataType.INTEGER,
        section="Resumen anual",
    ),
    _Casilla(
        casilla_id="02",
        label_es="Base retenciones",
        label_en="Withholding base",
        label_hu="Levonási alap",
        help_es="Suma anual de las bases sujetas a retención sobre rendimientos del capital mobiliario.",
        help_en="Annual sum of bases subject to withholding on investment income.",
        help_hu="A tőkejövedelmek éves levonási alapjának összege.",
        section="Resumen anual",
    ),
    _Casilla(
        casilla_id="03",
        label_es="Retenciones e ingresos a cuenta",
        label_en="Withholdings and payments on account",
        label_hu="Levonások és előlegek",
        help_es="Suma anual de las retenciones e ingresos a cuenta practicadas al tipo del 19% (LIRPF art. 101.4).",
        help_en="Annual sum of withholdings and payments on account at the 19% rate (LIRPF art. 101.4).",
        help_hu="A tőkejövedelmekre alkalmazott 19%-os éves levonás összege.",
        section="Resumen anual",
    ),
)

M347_CASILLAS: tuple[_Casilla, ...] = (
    _Casilla(
        casilla_id="01",
        label_es="N.º total declarados",
        label_en="Total declared parties",
        label_hu="Összes bejelentett fél",
        help_es="Número de personas o entidades respecto de las cuales se ha realizado declaración por superar 3.005,06 € (Orden EHA/3012/2008).",
        help_en="Number of parties for which a declaration is filed because the threshold of €3,005.06 was exceeded.",
        help_hu="A 3 005,06 €-os küszöb átlépése miatt bejelentett személyek száma.",
        data_type=CasillaDataType.INTEGER,
        section="Resumen",
    ),
    _Casilla(
        casilla_id="02",
        label_es="Importe total anual de operaciones declaradas",
        label_en="Annual total of declared operations",
        label_hu="A bejelentett ügyletek éves teljes összege",
        help_es="Suma agregada anual de las operaciones con terceros declaradas en el modelo 347.",
        help_en="Aggregate annual sum of third-party operations declared on form 347.",
        help_hu="A 347. nyomtatványban bejelentett ügyletek éves összege.",
        section="Resumen",
    ),
    _Casilla(
        casilla_id="03",
        label_es="N.º total registros — cobros en metálico",
        label_en="Records — cash payments received",
        label_hu="Készpénzes-bevétel rekordok",
        help_es="Número de registros declarados respecto de cobros en metálico superiores a 6.000 € (art. 7 RGAT).",
        help_en="Records declared for cash receipts exceeding €6,000 (RGAT art. 7).",
        help_hu="6 000 € feletti készpénzes bevétel rekordjainak száma.",
        data_type=CasillaDataType.INTEGER,
        section="Resumen — Metálico",
    ),
    _Casilla(
        casilla_id="04",
        label_es="Importe total — cobros en metálico",
        label_en="Total cash payments received",
        label_hu="Készpénzes-bevétel összege",
        help_es="Suma anual de los cobros en metálico superiores a 6.000 € declarados.",
        help_en="Annual sum of cash receipts exceeding €6,000 declared.",
        help_hu="A 6 000 € feletti készpénzes bevételek éves összege.",
        section="Resumen — Metálico",
    ),
)

M349_CASILLAS: tuple[_Casilla, ...] = (
    _Casilla(
        casilla_id="01",
        label_es="N.º total operadores intracomunitarios",
        label_en="Intra-Community operators",
        label_hu="Közösségi gazdasági szereplők",
        help_es="Número de operadores intracomunitarios declarados en el período (entregas y/o adquisiciones, LIVA art. 25 y 26).",
        help_en="Number of intra-Community operators declared in the period (supplies and/or acquisitions, Spanish VAT Act arts. 25-26).",
        help_hu="A bejelentett közösségi szereplők száma az időszakban (LIVA 25-26. cikk).",
        data_type=CasillaDataType.INTEGER,
        section="Resumen",
    ),
    _Casilla(
        casilla_id="02",
        label_es="Importe total operaciones",
        label_en="Total operation amount",
        label_hu="Ügyletek teljes összege",
        help_es="Importe total de las operaciones intracomunitarias declaradas (entregas + adquisiciones + servicios).",
        help_en="Total amount of intra-Community operations declared (supplies + acquisitions + services).",
        help_hu="A közösségi ügyletek teljes összege.",
        section="Resumen",
    ),
    _Casilla(
        casilla_id="03",
        label_es="N.º operadores con rectificaciones",
        label_en="Operators with rectifications",
        label_hu="Helyesbítéssel érintett szereplők",
        help_es="Operadores cuyas operaciones se rectifican respecto de períodos anteriores.",
        help_en="Operators whose operations are rectifying earlier periods.",
        help_hu="Korábbi időszakok helyesbítésében érintett szereplők száma.",
        data_type=CasillaDataType.INTEGER,
        section="Resumen — Rectificaciones",
    ),
    _Casilla(
        casilla_id="04",
        label_es="Importe rectificaciones",
        label_en="Rectifications amount",
        label_hu="Helyesbítések összege",
        help_es="Importe total de las rectificaciones declaradas en el período (signo positivo = aumento).",
        help_en="Total amount of rectifications declared in the period (positive sign = increase).",
        help_hu="Az időszakban bejelentett helyesbítések teljes összege (pozitív jel = növekedés).",
        section="Resumen — Rectificaciones",
    ),
)

M840_CASILLAS: tuple[_Casilla, ...] = (
    _Casilla(
        casilla_id="14",
        label_es="Ejercicio",
        label_en="Tax year",
        label_hu="Adóév",
        help_es="Ejercicio al que se refiere la declaración del IAE.",
        help_en="Tax year covered by the IAE declaration.",
        help_hu="Az IAE-bevallás vonatkozó adóéve.",
        data_type=CasillaDataType.TEXT,
        section="Datos generales",
    ),
    _Casilla(
        casilla_id="15",
        label_es="Causa de presentación",
        label_en="Filing cause",
        label_hu="Bejelentés oka",
        help_es="Acto censal que motiva la declaración: alta, variación o baja en el Impuesto sobre Actividades Económicas.",
        help_en="Census act prompting the declaration: enrolment, change, or removal in the IAE.",
        help_hu="A bejelentést indokoló esemény: beiratkozás, módosítás vagy kijelentkezés.",
        data_type=CasillaDataType.TEXT,
        section="Datos generales",
    ),
    _Casilla(
        casilla_id="33",
        label_es="Clase de cuota",
        label_en="Quota class",
        label_hu="Adóosztály",
        help_es="Clase de cuota del IAE: municipal, provincial o nacional.",
        help_en="IAE quota class: municipal, provincial or national.",
        help_hu="IAE-adóosztály: önkormányzati, tartományi vagy országos.",
        data_type=CasillaDataType.TEXT,
        section="Cuota",
    ),
    _Casilla(
        casilla_id="34",
        label_es="Tipo de actividad",
        label_en="Activity type",
        label_hu="Tevékenység típusa",
        help_es="Tipo de actividad: empresarial, profesional o artística.",
        help_en="Activity type: business, professional or artistic.",
        help_hu="Tevékenység típusa: vállalkozói, szakmai vagy művészi.",
        data_type=CasillaDataType.TEXT,
        section="Actividad",
    ),
    _Casilla(
        casilla_id="37",
        label_es="Grupo o epígrafe",
        label_en="Group or heading",
        label_hu="Csoport vagy tételszám",
        help_es="Grupo o epígrafe del IAE asignado a la actividad económica del sujeto pasivo.",
        help_en="IAE group or heading assigned to the taxpayer's economic activity.",
        help_hu="A tevékenységhez rendelt IAE-csoport vagy tételszám.",
        data_type=CasillaDataType.TEXT,
        section="Actividad",
    ),
    _Casilla(
        casilla_id="38",
        label_es="Municipio",
        label_en="Municipality",
        label_hu="Település",
        help_es="Municipio en el que se ejerce la actividad declarada.",
        help_en="Municipality where the declared activity is carried out.",
        help_hu="A tevékenység végzésének helye szerinti település.",
        data_type=CasillaDataType.TEXT,
        section="Localización",
    ),
    _Casilla(
        casilla_id="40",
        label_es="Provincia",
        label_en="Province",
        label_hu="Tartomány",
        help_es="Provincia en la que se ejerce la actividad declarada.",
        help_en="Province where the declared activity is carried out.",
        help_hu="A tevékenység végzésének helye szerinti tartomány.",
        data_type=CasillaDataType.TEXT,
        section="Localización",
    ),
    _Casilla(
        casilla_id="62",
        label_es="Fecha de efectos",
        label_en="Effective date",
        label_hu="Hatálybalépés dátuma",
        help_es="Fecha desde la que produce efectos la presente declaración del IAE.",
        help_en="Date from which this IAE declaration takes effect.",
        help_hu="A bejelentés hatálybalépésének dátuma.",
        data_type=CasillaDataType.TEXT,
        section="Datos finales",
    ),
)
