import re

_ES_TO_CA_LEMMAS: tuple[tuple[str, str], ...] = (
    (
        "Marque esta casilla para comunicar el inicio de la actividad económica.",
        "Marqueu aquesta casella per comunicar l'inici de l'activitat econòmica.",
    ),
    (
        "Marque esta casilla para comunicar el cese de la actividad económica.",
        "Marqueu aquesta casella per comunicar l'inici de l'activitat econòmica.",
    ),
    (
        "Marque para modificar los datos relativos al régimen de IVA.",
        "Marqueu per modificar les dades relatives al règim d'IVA.",
    ),
    ("Adquisiciones intracomunitarias", "Adquisicions intracomunitàries"),
    ("Entregas intracomunitarias", "Lliuraments intracomunitaris"),
    ("Operaciones interiores corrientes", "Operacions interiors corrents"),
    ("Operaciones interiores", "Operacions interiors"),
    ("Inversión del sujeto pasivo", "Inversió del subjecte passiu"),
    ("Recargo de equivalencia", "Recàrrec d'equivalència"),
    ("Régimen simplificado del IVA", "Règim simplificat de l'IVA"),
    ("Régimen general del IVA", "Règim general de l'IVA"),
    ("Régimen de estimación directa del IRPF", "Règim d'estimació directa de l'IRPF"),
    ("Régimen de estimación objetiva del IRPF", "Règim d'estimació objetiva de l'IRPF"),
    ("Régimen simplificado", "Règim simplificat"),
    ("Régimen general", "Règim general"),
    ("Régimen especial", "Règim especial"),
    ("Tipo superreducido", "Tipus superreduït"),
    ("Tipo reducido", "Tipus reduït"),
    ("Tipo general", "Tipus general"),
    ("Tipo impositivo", "Tipus impositiu"),
    ("IVA devengado", "IVA meritat"),
    ("IVA repercutido", "IVA repercutit"),
    ("IVA soportado", "IVA suportat"),
    ("IVA deducible", "IVA deduïble"),
    ("Base imponible gravada al tipo superreducido", "Base imposable gravada al tipus superreduït"),
    ("Base imponible gravada al tipo reducido", "Base imposable gravada al tipus reduït"),
    ("Base imponible", "Base imposable"),
    ("Base liquidable general", "Base liquidable general"),
    ("Base liquidable del ahorro", "Base liquidable de l'estalvi"),
    ("Base liquidable", "Base liquidable"),
    ("Cuota líquida", "Quota líquida"),
    ("Cuota tributaria", "Quota tributària"),
    ("Cuota íntegra", "Quota íntegra"),
    ("Cuota a ingresar", "Quota a ingressar"),
    ("Cuota a devolver", "Quota a retornar"),
    ("Rendimientos del trabajo", "Rendiments del treball"),
    ("Rendimientos de actividades económicas", "Rendiments d'activitats econòmiques"),
    ("Rendimientos del capital mobiliario", "Rendiments del capital mobiliari"),
    ("Rendimientos del capital inmobiliario", "Rendiments del capital immobiliari"),
    ("Rendimiento neto previo del trabajo", "Rendiment net previ del treball"),
    ("Rendimiento neto reducido del trabajo", "Rendiment net reduït del treball"),
    ("Rendimiento neto previo capital mobiliario", "Rendiment net previ capital mobiliari"),
    ("Rendimiento neto reducido capital mobiliario", "Rendiment net reduït capital mobiliari"),
    ("Rendimiento neto previo capital inmobiliario", "Rendiment net previ capital immobiliari"),
    ("Rendimiento neto reducido capital inmobiliario", "Rendiment net reduït capital immobiliari"),
    ("Rendimiento neto previo", "Rendiment net previ"),
    ("Rendimiento neto reducido", "Rendiment net reduït"),
    ("Rendimiento neto", "Rendiment net"),
    ("Rendimiento íntegre", "Rendiment íntegre"),
    ("Rendimientos", "Rendiments"),
    ("Ganancias y pérdidas patrimoniales", "Guanys i pèrdues patrimonials"),
    ("Mínimo personal y familiar", "Mínim personal i familiar"),
    ("Retención", "Retenció"),
    ("Retenciones", "Retencions"),
    ("Ingreso a cuenta", "Ingrés a compte"),
    ("Ingresos a cuenta", "Ingressos a compte"),
    ("Pago fraccionado", "Pagament fraccionat"),
    ("Pagos fraccionados", "Pagaments fraccionats"),
    ("Solicitud de alta en el censo de empresarios", "Sol·licitud d'alta al cens d'empresaris"),
    ("Modificación de datos relativos al IVA", "Modificació de dades relatives a l'IVA"),
    ("Baja en el censo de empresarios", "Baixa al cens d'empresaris"),
    (
        "Código de epígrafe del Impuesto sobre Actividades Económicas",
        "Codi d'epígraf de l'Impost sobre Activitats Econòmiques",
    ),
    ("Epígrafe IAE", "Epígraf IAE"),
    ("declaración censal", "declaració censal"),
    ("Declaración censal", "Declaració censal"),
    ("declaración informativa", "declaració informativa"),
    ("Declaración informativa", "Declaració informativa"),
    ("declaraciones informativas", "declaracions informatives"),
    ("Declaraciones informativas", "Declaracions informatives"),
    ("declaración", "declaració"),
    ("Declaración", "Declaració"),
    ("declaraciones", "declaracions"),
    ("Declaraciones", "Declaracions"),
    ("autoliquidación", "autoliquidació"),
    ("Autoliquidación", "Autoliquidació"),
    ("autoliquidaciones", "autoliquidacions"),
    ("Autoliquidaciones", "Autoliquidacions"),
    ("liquidación", "liquidació"),
    ("Liquidación", "Liquidació"),
    ("presentación", "presentació"),
    ("Presentación", "Presentació"),
    ("complementaria", "complementària"),
    ("Complementaria", "Complementària"),
    ("sustitutiva", "substitutiva"),
    ("Sustitutiva", "Substitutiva"),
    ("rectificación", "rectificació"),
    ("Rectificación", "Rectificació"),
    ("ejercicio", "exercici"),
    ("Ejercicio", "Exercici"),
    ("período impositivo", "període impositiu"),
    ("Período impositivo", "Período impositivo"),
    ("Ingresos de explotación", "Ingressos d'explotació"),
    ("Variación de existencias", "Variació d'existències"),
    ("Gastos de personal", "Despeses de personal"),
    ("Servicios exteriores, tributos y otros", "Serveis exteriors, tributs i altres"),
    ("Amortización del inmovilizado", "Amortització de l'immobilitzat"),
    ("Provisiones y deterioros", "Provisions i deterioraments"),
    ("Total gastos computables", "Total despeses computables"),
    ("Total ingresos computables", "Total ingressos computables"),
    ("Gasto deducible cotización Seguridad Social", "Despesa deduïble cotització Seguretat Social"),
    ("Otros gastos deducibles del trabajo", "Altres despeses deduïbles del treball"),
    ("Gasto adicional movilidad geográfica", "Despesa addicional mobilitat geogràfica"),
    ("Saldo neto patrimonial total", "Saldo net patrimonial total"),
    ("Mínimo personal y familiar total", "Mínim personal i familiar total"),
    ("Total deducciones autonómicas", "Total deduccions autonòmiques"),
    ("Total deducciones (estatales + autonómicas)", "Total deduccions (estatals + autonòmiques)"),
    ("deducciones autonómicas", "deduccions autonòmiques"),
    ("Deducciones autonómicas", "Deduccions autonòmiques"),
    ("deducciones estatales", "deduccions estatals"),
    ("Deducciones estatales", "Deduccions estatals"),
    ("Total deducciones autonómicas (suma per-CCAA)", "Total deduccions autonòmiques (suma per CCAA)"),
    ("Andalucía", "Andalusia"),
    ("Aragón", "Aragó"),
    ("Principado de Asturias", "Principat d'Astúries"),
    ("Asturias", "Astúries"),
    ("Canarias", "Canàries"),
    ("Cantabria", "Cantàbria"),
    ("Castilla-La Mancha", "Castella-la Manxa"),
    ("Castilla y León", "Castella i Lleó"),
    ("Cataluña", "Catalunya"),
    ("Comunidad Valenciana", "Comunitat Valenciana"),
    ("Galicia", "Galícia"),
    ("Comunidad de Madrid", "Comunitat de Madrid"),
    ("Región de Murcia", "Regió de Múrcia"),
    ("País Vasco", "País Basc"),
    ("Municipio", "Municipi"),
    ("municipio", "municipi"),
    ("municipios", "municipis"),
    ("Municipios", "Municipis"),
    ("Provincia", "Província"),
    ("provincia", "província"),
    ("provincias", "províncies"),
    ("Provincias", "Províncies"),
    ("Cuadro", "Quadre"),
    ("cuadro", "quadre"),
    ("Núm. registros", "Núm. registres"),
    ("núm. registros", "núm. registres"),
    ("número de registros", "nombre de registres"),
    ("Número de registros", "Nombre de registres"),
    ("personas o entidades vinculadas", "persones o entitats vinculades"),
    ("entidades vinculadas", "entitats vinculades"),
    ("activos intangibles", "actius intangibles"),
    ("activos", "actius"),
    ("Activos", "Actius"),
    ("activo", "actiu"),
    ("Activo", "Actiu"),
    ("beneficio fiscal", "benefici fiscal"),
    ("beneficios fiscales", "beneficis fiscals"),
    ("sujeto pasivo", "subjecte passiu"),
    ("Sujeto pasivo", "Subjecte passiu"),
    ("empresarial, profesional o artística", "empresarial, professional o artística"),
    ("profesional", "professional"),
    ("Profesional", "Professional"),
    ("artística", "artística"),
    ("artístico", "artístic"),
    ("se ejerce la actividad", "s'exerceix l'activitat"),
    ("ejerce la actividad", "exerceix l'activitat"),
    ("Marque si tributa por", "Marqueu si tributeu per"),
    ("Marque si tributa", "Marqueu si tributeu"),
    ("Marque si", "Marqueu si"),
    ("Marque para", "Marqueu per"),
    ("Marque la casilla", "Marqueu la casella"),
    ("Marque", "Marqueu"),
    ("Indique", "Indiqueu"),
    ("Consulte", "Consulteu"),
    ("Introduzca", "Introduïu"),
    ("Anote", "Anoteu"),
    ("Cumplimente", "Empleneu"),
    ("Detalle", "Detalleu"),
    ("ingresos", "ingressos"),
    ("Ingresos", "Ingressos"),
    ("ingreso", "ingrés"),
    ("Ingreso", "Ingrés"),
    ("gastos deducibles", "despeses deduïbles"),
    ("Gastos deducibles", "Despeses deduïbles"),
    ("gastos no deducibles", "despeses no deduïbles"),
    ("Gastos no deducibles", "Despeses no deduïbles"),
    ("gastos", "despeses"),
    ("Gastos", "Despeses"),
    ("gasto", "despesa"),
    ("Gasto", "Despesa"),
    ("amortización", "amortització"),
    ("Amortización", "Amortització"),
    ("provisión", "provisió"),
    ("Provisión", "Provisió"),
    ("inmovilizado", "immobilitzat"),
    ("Inmovilizado", "Immobilitzat"),
    ("explotación", "explotació"),
    ("Explotación", "Explotació"),
    ("variación", "variació"),
    ("Variación", "Variació"),
    ("existencias", "existències"),
    ("Existencias", "Existències"),
    ("inmuebles", "immobles"),
    ("Inmuebles", "Immobles"),
    ("inmueble", "immoble"),
    ("Inmueble", "Immoble"),
    ("arrendamiento", "arrendament"),
    ("Arrendamiento", "Arrendament"),
    ("intereses", "interessos"),
    ("Intereses", "Interessos"),
    ("dividendos", "dividends"),
    ("Dividendos", "Dividends"),
    ("cuentas", "comptes"),
    ("Cuentas", "Comptes"),
    ("depósitos", "dipòsits"),
    ("Depósitos", "Dipòsits"),
    ("Seguridad Social", "Seguretat Social"),
    ("cotización", "cotització"),
    ("Cotización", "Cotització"),
    ("administración", "administració"),
    ("Administración", "Administració"),
    ("custodia", "custòdia"),
    ("Custodia", "Custòdia"),
    ("imputación", "imputació"),
    ("Imputación", "Imputació"),
    ("renta", "renda"),
    ("Renta", "Renda"),
    ("rentas", "rendes"),
    ("Rentas", "Rendes"),
    ("ahorro", "estalvi"),
    ("Ahorro", "Estalvi"),
    ("autonómica", "autonòmica"),
    ("Autonómica", "Autonòmica"),
    ("autonómicas", "autonòmiques"),
    ("Autonómicas", "Autonòmiques"),
    ("autonómico", "autonòmic"),
    ("Autonómico", "Autonòmic"),
    ("autonómicos", "autonòmics"),
    ("Autonómicos", "Autonòmics"),
    ("Comunidad Autónoma", "Comunitat Autònoma"),
    ("comunidad autónoma", "comunitat autònoma"),
    ("Comunidades Autónomas", "Comunitats Autònomes"),
    ("estatal", "estatal"),
    ("Estatal", "Estatal"),
    ("estatales", "estatals"),
    ("Estatales", "Estatals"),
    ("Real Decreto-Ley", "Reial Decret-Llei"),
    ("Real Decreto-ley", "Reial Decret-llei"),
    ("Real Decreto", "Reial Decret"),
    ("Reglamento", "Reglament"),
    ("reglamento", "reglament"),
    ("Reglamentos", "Reglaments"),
    ("reglaments", "reglaments"),
    ("Orden Ministerial", "Ordre Ministerial"),
    ("orden ministerial", "ordre ministerial"),
    ("Órdenes", "Ordres"),
    ("órdenes", "ordres"),
    ("Orden", "Ordre"),
    ("orden", "ordre"),
    ("Ley", "Llei"),
    ("Leyes", "Lleis"),
    ("artículo", "article"),
    ("Artículo", "Article"),
    ("artículos", "articles"),
    ("Artículos", "Articles"),
    ("Anexo", "Annex"),
    ("anexo", "annex"),
    ("según", "segons"),
    ("Según", "Segons"),
    ("vigente", "vigent"),
    ("aplicable", "aplicable"),
    ("correspondiente", "corresponent"),
    ("Casilla", "Casella"),
    ("casilla", "casella"),
    ("Casillas", "Caselles"),
    ("casillas", "caselles"),
    ("Importe", "Import"),
    ("importe", "import"),
    ("Total", "Total"),
    ("total", "total"),
    ("totales", "totals"),
    ("Retenciones e ingresos a cuenta", "Retencions i ingressos a compte"),
    ("Total retenciones", "Total retencions"),
    ("Retenciones rendimientos del trabajo", "Retencions rendiments del treball"),
    ("Retenciones actividades económicas", "Retencions activitats econòmiques"),
    ("Retenciones contraprestaciones en especie", "Retencions contraprestacions en espècie"),
    ("Retenciones cesión de imagen", "Retencions cessió d'imatge"),
    ("Retenciones dividendos", "Retencions dividends"),
    ("Retenciones otras rentas", "Retencions altres rendes"),
    ("Percepciones premios", "Percepcions premis"),
    ("Percepciones ganancias patrimoniales", "Percepcions guanys patrimonials"),
    ("Perceptores dividendos", "Perceptors dividends"),
    ("Perceptores otras rentas", "Perceptors altres rendes"),
    ("Base de retención", "Base de retenció"),
    ("Base retenciones dividendos", "Base retencions dividends"),
    ("Base retenciones otras rentas", "Base retencions altres rendes"),
    ("Ingresos a cuenta por retribución en especie", "Ingressos a compte per retribució en espècie"),
    ("Nº de arrendadores", "Nre. d'arrendadors"),
    ("N.º de arrendadores", "Nre. d'arrendadors"),
    ("número de arrendadores", "nombre d'arrendadors"),
    ("A deducir: exclusivamente en declaración complementaria", "A deduir: exclusivament en declaració complementària"),
    ("Resultado a ingresar", "Resultat a ingressar"),
    ("Resultado a devolver", "Resultat a retornar"),
    ("Resultado declaracion anterior (complementaria)", "Resultat declaració anterior (complementària)"),
    ("Resultado declaración anterior (complementaria)", "Resultat declaració anterior (complementària)"),
    (
        "Resultado a ingresar de autoliquidaciones anteriores (complementaria)",
        "Resultat a ingressar d'autoliquidacions anteriors (complementària)",
    ),
    ("Resultados negativos autoliquidaciones anteriores", "Resultats negatius autoliquidacions anteriors"),
    ("A deduir autoliquidaciones anteriores", "A deduir autoliquidacions anteriors"),
    ("Suma rendimientos netos modulos", "Suma rendiments nets mòduls"),
    ("Suma rendimientos netos módulos", "Suma rendiments nets mòduls"),
    ("Pago fraccionado del trimestre", "Pagament fraccionat del trimestre"),
    ("Volumen ventas sin datos-base", "Volum vendes sense dades-base"),
    ("Volumen ingresos agricolas/ganaderas/forestales", "Volum ingressos agrícoles/ramaderes/forestals"),
    ("Volumen ingresos agrícolas/ganaderas/forestales", "Volum ingressos agrícoles/ramaderes/forestals"),
    ("Minoracion rendimientos ano anterior", "Minoració rendiments any anterior"),
    ("Minoración rendimientos año anterior", "Minoració rendiments any anterior"),
    ("Deduccion vivienda habitual", "Deducció habitatge habitual"),
    ("Deducción vivienda habitual", "Deducció habitatge habitual"),
    ("Base del pago fraccionado", "Base del pagament fraccionat"),
    ("a deducir", "a deduir"),
    ("A deducir", "A deduir"),
    ("a ingresar", "a ingressar"),
    ("a devolver", "a retornar"),
    ("declaración anterior", "declaració anterior"),
    ("Declaración anterior", "Declaración anterior"),
    ("autoliquidación anterior", "autoliquidació anterior"),
    ("autoliquidaciones anteriores", "autoliquidacions anteriors"),
    ("Autoliquidaciones anteriores", "Autoliquidacions anteriors"),
    ("contraprestación", "contraprestació"),
    ("Contraprestación", "Contraprestació"),
    ("contraprestaciones", "contraprestacions"),
    ("Contraprestaciones", "Contraprestacions"),
    ("retribución", "retribució"),
    ("Retribución", "Retribució"),
    ("retribuciones", "retribucions"),
    ("Retribuciones", "Retribucions"),
    ("en especie", "en espècie"),
    ("En especie", "En espècie"),
    ("cesión de imagen", "cessió d'imatge"),
    ("Cesión de imagen", "Cessió d'imatge"),
    ("cesión", "cessió"),
    ("Cesión", "Cessió"),
    ("cesiones", "cessions"),
    ("Cesiones", "Cessions"),
    ("imagen", "imatge"),
    ("Imagen", "Imatge"),
    ("perceptores", "perceptors"),
    ("Perceptores", "Perceptors"),
    ("perceptor", "perceptor"),
    ("Perceptor", "Perceptor"),
    ("percepciones", "percepcions"),
    ("Percepciones", "Percepcions"),
    ("percepción", "percepció"),
    ("Percepción", "Percepció"),
    ("premios", "premis"),
    ("Premios", "Premis"),
    ("premio", "premi"),
    ("Premio", "Premi"),
    ("arrendadores", "arrendadors"),
    ("Arrendadores", "Arrendadors"),
    ("arrendador", "arrendador"),
    ("Arrendador", "Arrendador"),
    ("rendimientos netos", "rendiments nets"),
    ("Rendimientos nets", "Rendiments nets"),
    ("rendimiento neto", "rendiment net"),
    ("módulos", "mòduls"),
    ("modulos", "mòduls"),
    ("Modulos", "Mòduls"),
    ("Módulos", "Mòduls"),
    ("trimestre", "trimestre"),
    ("Trimestre", "Trimestre"),
    ("mensual", "mensual"),
    ("Mensual", "Mensual"),
    ("anual", "anual"),
    ("Anual", "Anual"),
    ("habitual", "habitual"),
    ("Habitual", "Habitual"),
    ("vivienda", "habitatge"),
    ("Vivienda", "Habitatge"),
    ("agricolas", "agrícoles"),
    ("agrícolas", "agrícoles"),
    ("ganaderas", "ramaderes"),
    ("ganaderías", "ramaderies"),
    ("Ganaderías", "Ramaderies"),
    ("ganadería", "ramaderia"),
    ("Ganadería", "Ramaderia"),
    ("forestales", "forestals"),
    ("Forestales", "Forestals"),
    ("ventas", "vendes"),
    ("Ventas", "Vendes"),
    ("venta", "venda"),
    ("Venta", "Venda"),
    ("volumen", "volum"),
    ("Volumen", "Volum"),
    ("base de", "base de"),
    ("Base de", "Base de"),
    ("año anterior", "any anterior"),
    ("año", "any"),
    ("Año", "Any"),
    ("años", "anys"),
    ("Años", "Anys"),
    ("anterior", "anterior"),
    ("Anterior", "Anterior"),
    ("anteriores", "anteriors"),
    ("Anteriores", "Anteriors"),
    ("siguiente", "següent"),
    ("Siguiente", "Següent"),
    ("siguientes", "següents"),
    ("Siguientes", "Següents"),
    ("trimestral", "trimestral"),
    ("Trimestral", "Trimestral"),
    ("trimestres", "trimestres"),
    ("Trimestres", "Trimestres"),
    ("minoración", "minoració"),
    ("Minoración", "Minoració"),
    ("minoraciones", "minoracions"),
    ("Minoraciones", "Minoracions"),
    ("agrícola", "agrícola"),
    ("Agrícola", "Agrícola"),
    ("agrícolas/ganaderas", "agrícoles/ramaderes"),
    ("número", "nombre"),
    ("Número", "Nombre"),
    ("números", "nombres"),
    ("Tipo de gravamen aplicable", "Tipus de gravamen aplicable"),
    ("Tipo de gravamen", "Tipus de gravamen"),
    ("tipo de gravamen", "tipus de gravamen"),
    ("Bonificaciones", "Bonificacions"),
    ("bonificaciones", "bonificacions"),
    ("Bonificación", "Bonificació"),
    ("bonificación", "bonificació"),
    ("Resultado régimen general", "Resultat règim general"),
    ("resultado régimen general", "resultat règim general"),
    ("Resultado parcial Apartado I", "Resultat parcial Apartat I"),
    ("Resultado parcial Apartado II", "Resultat parcial Apartat II"),
    ("Resultado parcial Apartado III", "Resultat parcial Apartat III"),
    ("Resultado parcial Apartado", "Resultat parcial Apartat"),
    ("Resultado parcial", "Resultat parcial"),
    ("Apartado", "Apartat"),
    ("apartado", "apartat"),
    ("Apartados", "Apartats"),
    ("apartados", "apartats"),
    ("Suma de resultados parciales", "Suma de resultats parcials"),
    ("resultados parciales", "resultats parcials"),
    ("Resultados parciales", "Resultats parcials"),
    ("Diferencia", "Diferència"),
    ("diferencia", "diferència"),
    ("Resultado final", "Resultat final"),
    ("resultado final", "resultat final"),
    ("Resultado", "Resultat"),
    ("resultado", "resultat"),
    ("Total bases imponibles", "Total bases imposables"),
    ("bases imponibles", "bases imposables"),
    ("Bases imponibles", "Bases imponibles"),
    ("Base total retenciones", "Base total retencions"),
    ("base total retenciones", "base total retencions"),
    ("Cuota integra", "Quota íntegra"),
    ("cuota integra", "quota íntegra"),
    ("Cuota devengada", "Quota meritada"),
    ("cuota devengada", "quota meritada"),
    ("Cuota deducible", "Quota deduïble"),
    ("cuota deducible", "quota deduïble"),
    ("Cuota", "Quota"),
    ("cuota", "quota"),
    ("Tipo 4 %", "Tipus 4 %"),
    ("Tipo 10 %", "Tipus 10 %"),
    ("Tipo 21 %", "Tipus 21 %"),
    ("Cuota devengada al", "Quota meritada al"),
    ("Base — operaciones interiores corrientes", "Base — operacions interiors corrents"),
    ("Cuota deducible — operaciones interiores corrientes", "Quota deduïble — operacions interiors corrents"),
    ("Regularización bienes de inversión", "Regularització béns d'inversió"),
    ("regularización", "regularització"),
    ("Regularización", "Regularització"),
    ("bienes de inversión", "béns d'inversió"),
    ("Bienes de inversión", "Béns d'inversió"),
    ("bienes", "béns"),
    ("Bienes", "Béns"),
    ("Bien", "Bé"),
    ("Total 02+04+06", "Total 02+04+06"),
    ("Resultado 07-08-09", "Resultat 07-08-09"),
    ("Resultado 10-11-12", "Resultat 10-11-12"),
    ("ámbito territorial", "àmbit territorial"),
    ("territorial", "territorial"),
    ("territorial común", "territorial comú"),
    ("territorio común", "territori comú"),
    ("Territorio común", "Territori comú"),
    ("territorio foral", "territori foral"),
    ("Territorio foral", "Territori foral"),
    ("operaciones realizadas", "operacions realitzades"),
    ("operaciones interiores", "operacions interiors"),
    ("Operaciones interiores", "Operacions interiors"),
    ("operaciones intracomunitarias", "operacions intracomunitàries"),
    ("Operaciones intracomunitarias", "Operacions intracomunitàries"),
    ("operaciones exteriores", "operacions exteriors"),
    ("Operaciones exteriores", "Operacions exteriors"),
    ("importaciones", "importacions"),
    ("Importaciones", "Importacions"),
    ("exportaciones", "exportacions"),
    ("Exportaciones", "Exportacions"),
    ("autoconsumo", "autoconsum"),
    ("Autoconsumo", "Autoconsum"),
    ("inversión del sujeto pasivo", "inversió del subjecte passiu"),
    ("Inversión del sujeto pasivo", "Inversió del subjecte passiu"),
    ("repercusión", "repercussió"),
    ("Repercusión", "Repercussió"),
    ("deducción del IVA soportado", "deducció de l'IVA soportat"),
    ("Deducción del IVA soportado", "Deducció de l'IVA soportat"),
    ("legal", "legal"),
    ("Legal", "Legal"),
    ("base legal", "base legal"),
    ("Base legal", "Base legal"),
    ("Ley, art.", "Llei, art."),
    ("Base — adquisiciones intracomunitarias corrientes", "Base — adquisicions intracomunitàries corrents"),
    ("Base — adquisiciones intracomunitarias de inversión", "Base — adquisicions intracomunitàries d'inversió"),
    ("Compensaciones régimen especial A.G.P.", "Compensacions règim especial A.G.P."),
    ("compensaciones", "compensacions"),
    ("Compensaciones", "Compensacions"),
    ("compensación", "compensació"),
    ("Compensación", "Compensació"),
    ("Suma de resultados", "Suma de resultats"),
    ("suma de resultados", "suma de resultats"),
    ("% atribuible al Estado", "% atribuïble a l'Estat"),
    ("Atribuible al Estado", "Atribuïble a l'Estat"),
    ("atribuible", "atribuïble"),
    ("Atribuible", "Atribuïble"),
    ("Estado", "Estat"),
    ("estado", "estat"),
    ("N.º total operadores intracomunitarios", "Nre. total operadors intracomunitaris"),
    ("N.º operadores con rectificaciones", "Nre. operadors amb rectificacions"),
    ("operadores", "operadors"),
    ("Operadores", "Operadors"),
    ("operador", "operador"),
    ("Operador", "Operador"),
    ("rectificaciones", "rectificacions"),
    ("Rectificaciones", "Rectificacions"),
    ("rectificación", "rectificació"),
    ("Rectificación", "Rectificació"),
    ("intracomunitarios", "intracomunitaris"),
    ("Intracomunitarios", "Intracomunitaris"),
    ("intracomunitario", "intracomunitari"),
    ("Intracomunitario", "Intracomunitari"),
    (
        "Suma de las cuotas de IVA devengadas en los Estados miembros de consumo",
        "Suma de les quotes d'IVA meritades als Estats membres de consum",
    ),
    ("Estados miembros de consumo", "Estats membres de consum"),
    ("estados miembros", "estats membres"),
    ("Estados miembros", "Estats membres"),
    ("Estado miembro", "Estat membre"),
    ("Total cuotas IVA devengadas", "Total quotes IVA meritades"),
    ("cuotas IVA", "quotes IVA"),
    ("Cuotas IVA", "Quotes IVA"),
    ("cuotas", "quotes"),
    ("Cuotas", "Quotes"),
    ("Fecha de efectos", "Data d'efectes"),
    ("fecha de efectos", "data d'efectes"),
    ("Reducción art. 18 — rendimientos irregulares", "Reducció art. 18 — rendiments irregulars"),
    ("Reducción art. 20 rendimientos del trabajo", "Reducció art. 20 rendiments del treball"),
    ("Reducción art. 26.2 — irregularidad capital mobiliario", "Reducció art. 26.2 — irregularitat capital mobiliari"),
    ("Reducción art. 23.2 — tramos 50/60/70/90 %", "Reducció art. 23.2 — trams 50/60/70/90 %"),
    ("Reducción LIRPF art. 32 — E.D. simplificada", "Reducció LIRPF art. 32 — E.D. simplificada"),
    ("Reducción LIRPF art. 32", "Reducció LIRPF art. 32"),
    ("rendimientos irregulares", "rendiments irregulars"),
    ("Rendimientos irregulares", "Rendiments irregulars"),
    ("Otros rendimientos del capital mobiliario", "Altres rendiments del capital mobiliari"),
    ("Ganancias patrimoniales brutas", "Guanys patrimonials bruts"),
    ("Pérdidas patrimoniales brutas", "Pèrdues patrimonials brutes"),
    (
        "Reducción por aportaciones a sistemas de previsión social",
        "Reducció per aportacions a sistemes de previsió social",
    ),
    ("Reducción por tributación conjunta", "Reducció per tributació conjunta"),
    ("Mínimo del contribuyente", "Mínim del contribuent"),
    ("Mínimo por descendientes", "Mínim per descendents"),
    ("Mínimo por ascendientes", "Mínim per ascendents"),
    ("Mínimo por discapacidad", "Mínim per discapacitat"),
    ("Mínimo del cónyuge", "Mínim del cònjuge"),
    ("aportaciones", "aportacions"),
    ("Aportaciones", "Aportacions"),
    ("aportación", "aportació"),
    ("Aportación", "Aportació"),
    ("sistemas de previsión social", "sistemes de previsió social"),
    ("previsión social", "previsió social"),
    ("Previsión social", "Previsión social"),
    ("tributación", "tributació"),
    ("Tributación", "Tributació"),
    ("tributación conjunta", "tributació conjunta"),
    ("Tributación conjunta", "Tributación conjunta"),
    ("discapacidad", "discapacitat"),
    ("Discapacidad", "Discapacidad"),
    ("contribuyentes", "contribuents"),
    ("Contribuyentes", "Contribuents"),
    ("contribuyente", "contribuent"),
    ("Contribuyente", "Contribuent"),
    ("descendientes", "descendents"),
    ("Descendientes", "Descendents"),
    ("descendiente", "descendent"),
    ("Descendiente", "Descendent"),
    ("ascendientes", "ascendents"),
    ("Ascendientes", "Ascendents"),
    ("ascendiente", "ascendent"),
    ("Ascendiente", "Ascendent"),
    ("cónyuge", "cònjuge"),
    ("Cónyuge", "Cònjuge"),
    ("irregulares", "irregulars"),
    ("Irregulares", "Irregulars"),
    ("irregularidad", "irregularitat"),
    ("Irregularidad", "Irregularidad"),
    ("simplificada", "simplificada"),
    ("Simplificada", "Simplificada"),
    ("brutas", "brutes"),
    ("Brutas", "Brutes"),
    ("bruta", "bruta"),
    ("Bruta", "Bruta"),
    ("brutos", "bruts"),
    ("Brutos", "Bruts"),
    ("bruto", "brut"),
    ("Bruto", "Brut"),
    ("netas", "netes"),
    ("Netas", "Netes"),
    ("neta", "neta"),
    ("Neta", "Neta"),
    ("netos", "nets"),
    ("Netos", "Nets"),
    ("neto", "net"),
    ("Neto", "Net"),
    ("tramos", "tramos"),
    ("Tramos", "Tramos"),
    ("tramo", "tram"),
    ("Tramo", "Tram"),
    ("Minimo personal y familiar total", "Mínim personal i familiar total"),
    ("Total base retencion", "Total base retenció"),
    ("Base retenciones", "Base retencions"),
    ("Compensacion BINs", "Compensació BINs"),
    ("Compensación BINs", "Compensació BINs"),
    ("Abono de deducciones", "Abonament de deduccions"),
    ("abono de deducciones", "abonament de deduccions"),
    ("Incremento por perdida beneficios fiscales", "Increment per pèrdua beneficis fiscals"),
    ("Incremento por pérdida beneficios fiscales", "Increment per pèrdua beneficis fiscals"),
    ("incremento", "increment"),
    ("Incremento", "Increment"),
    (
        "Total de registros de operaciones con personas o entidades vinculadas declarados",
        "Total de registres d'operacions amb persones o entitats vinculades declarats",
    ),
    ("operaciones con personas o entidades vinculadas", "operacions amb persones o entitats vinculades"),
    ("personas o entidades vinculadas", "persones o entitats vinculades"),
    (
        "Total de registros de operaciones con activos intangibles",
        "Total de registres d'operacions amb actius intangibles",
    ),
    ("operaciones con activos intangibles", "operacions amb actius intangibles"),
    ("activos intangibles", "actius intangibles"),
    ("Activos intangibles", "Activos intangibles"),
    ("activos", "actius"),
    ("Activos", "Actius"),
    ("activo", "actiu"),
    ("Activo", "Actiu"),
    ("intangible", "intangible"),
    ("Intangible", "Intangible"),
    ("intangibles", "intangibles"),
    ("Intangibles", "Intangibles"),
    ("operaciones con paraísos fiscales", "operacions amb paradisos fiscals"),
    ("paraísos fiscales", "paradisos fiscals"),
    ("Paraísos fiscales", "Paraísos fiscales"),
    ("paraíso", "paradís"),
    ("Paraíso", "Paradís"),
    ("paraísos", "paradisos"),
    ("Paraísos", "Paraísos"),
    ("registros", "registres"),
    ("Registros", "Registres"),
    ("registro", "registre"),
    ("Registro", "Registre"),
    ("vinculadas", "vinculades"),
    ("Vinculadas", "Vinculadas"),
    ("vinculados", "vinculats"),
    ("Vinculados", "Vinculats"),
    ("vinculada", "vinculada"),
    ("vinculado", "vinculat"),
    ("vinculación", "vinculació"),
    ("Vinculación", "Vinculació"),
    ("entidades", "entitats"),
    ("Entidades", "Entitats"),
    ("entidad", "entitat"),
    ("Entidad", "Entitat"),
    ("personas", "persones"),
    ("Personas", "Persones"),
    ("persona", "persona"),
    ("Persona", "Persona"),
    ("acogido al", "acollit al"),
    ("se han acogido", "s'han acollit"),
    (
        "Suma agregada anual de las operaciones con terceros declaradas en el modelo 347.",
        "Suma agregada anual de les operacions amb tercers declarades al model 347.",
    ),
    ("operaciones con terceros", "operacions amb tercers"),
    ("Operaciones con terceros", "Operaciones con terceros"),
    ("terceros", "tercers"),
    ("Terceros", "Tercers"),
    ("tercero", "tercer"),
    ("Tercero", "Tercer"),
    ("declaradas", "declarades"),
    ("Declaradas", "Declarades"),
    ("declarados", "declarats"),
    ("Declarados", "Declarats"),
    ("declarada", "declarada"),
    ("Declarada", "Declarada"),
    ("declarado", "declarat"),
    ("Declarado", "Declarat"),
    ("agregada", "agregada"),
    ("agregado", "agregat"),
    ("modelo", "model"),
    ("modelos", "models"),
    ("Modelos", "Models"),
    ("N.º total registros — cobros en metálico", "Nre. total registres — cobraments en metàl·lic"),
    ("cobros en metálico", "cobraments en metàl·lic"),
    ("Cobros en metálico", "Cobraments en metàl·lic"),
    ("Suma anual de los cobros en metálico superiores a", "Suma anual dels cobraments en metàl·lic superiors a"),
    ("cobros", "cobraments"),
    ("Cobros", "Cobraments"),
    ("cobro", "cobrament"),
    ("Cobro", "Cobrament"),
    ("metálico", "metàl·lic"),
    ("Metálico", "Metàl·lic"),
    ("superiores a", "superiors a"),
    ("Superiores a", "Superiors a"),
    ("superior a", "superior a"),
    ("Superior a", "Superior a"),
    (
        "Suma de las cuotas de IVA devengadas en los Estados miembros de consumo",
        "Suma de les quotes d'IVA meritades als Estats membres de consum",
    ),
    ("Total cuotas repercutidas", "Total quotes repercutides"),
    ("cuotas repercutidas", "quotes repercutides"),
    ("Cuotas repercutidas", "Quotes repercutides"),
    (
        "Tipo de actividad: empresarial, profesional o artística.",
        "Tipus d'activitat: empresarial, professional o artística.",
    ),
    ("Tipo de actividad", "Tipus d'activitat"),
    ("tipo de actividad", "tipus d'activitat"),
    ("empresarial", "empresarial"),
    ("Empresarial", "Empresarial"),
    ("profesional", "professional"),
    ("Profesional", "Professional"),
    ("artística", "artística"),
    ("Artística", "Artística"),
    ("artístico", "artístic"),
    ("Artístico", "Artístic"),
    (
        "Grupo o epígrafe del IAE asignado a la actividad económica del sujeto pasivo.",
        "Grup o epígraf de l'IAE assignat a l'activitat econòmica del subjecte passiu.",
    ),
    ("Grupo o epígrafe", "Grup o epígraf"),
    ("grupo o epígrafe", "grup o epígraf"),
    ("Grupo", "Grup"),
    ("grupo", "grup"),
    ("epígrafe", "epígraf"),
    ("Epígrafe", "Epígraf"),
    ("asignado", "assignat"),
    ("Asignado", "Assignat"),
    ("asignada", "assignada"),
    ("Asignada", "Asignada"),
)

_ES_TO_CA_LEMMAS_ORDERED: tuple[tuple[str, str], ...] = tuple(sorted(_ES_TO_CA_LEMMAS, key=lambda pair: -len(pair[0])))


def _es_to_ca_via_lemmas(es_text: str) -> str:
    if not es_text:
        return es_text
    out = es_text
    for old, new in _ES_TO_CA_LEMMAS_ORDERED:
        if old == new:
            continue
        pattern = r"(?<![A-Za-zÀ-ɏ])" + re.escape(old) + r"(?![A-Za-zÀ-ɏ])"
        out = re.sub(pattern, new, out)
    return out


_HU_DIACRITIC_LEMMAS: tuple[tuple[str, str], ...] = (
    ("autonom", "autonóm"),
    ("Autonom", "Autonóm"),
    ("levonasok", "levonások"),
    ("Levonasok", "Levonások"),
    ("levonas", "levonás"),
    ("Levonas", "Levonás"),
    ("osszesen", "összesen"),
    ("Osszesen", "Összesen"),
    ("osszeg", "összeg"),
    ("Osszeg", "Összeg"),
    ("brutto", "bruttó"),
    ("Brutto", "Bruttó"),
    ("netto", "nettó"),
    ("Netto", "Nettó"),
    ("altalanos", "általános"),
    ("Altalanos", "Általános"),
    ("allami", "állami"),
    ("Allami", "Állami"),
    ("megtakaritasi", "megtakarítási"),
    ("Megtakaritasi", "Megtakarítási"),
    ("megtakaritas", "megtakarítás"),
    ("teljes", "teljes"),
    ("adoalap", "adóalap"),
    ("Adoalap", "Adóalap"),
    ("szemelyi", "személyi"),
    ("Szemelyi", "Személyi"),
    ("alapba", "alapba"),
    ("szamitando", "számítandó"),
    ("Szamitando", "Számítandó"),
    ("egyenleg", "egyenleg"),
    ("csokkentes", "csökkentés"),
    ("Csokkentes", "Csökkentés"),
    ("szerinti", "szerinti"),
    ("likvidalt", "likvidált"),
    ("tarifa", "tarifa"),
    ("ccaafuggo", "ccaafüggő"),
    ("kozosseg", "közösség"),
    ("Kozosseg", "Közösség"),
    ("kozossegi", "közösségi"),
    ("Kozossegi", "Közösségi"),
    ("keszletvaltozas", "készletváltozás"),
    ("Keszletvaltozas", "Készletváltozás"),
    ("keszlet", "készlet"),
    ("Keszlet", "Készlet"),
    ("nyito", "nyitó"),
    ("Nyito", "Nyitó"),
    ("zaro", "záró"),
    ("Zaro", "Záró"),
    ("vagyongyarapodas", "vagyongyarapodás"),
    ("vagyonveszteseg", "vagyonveszteség"),
    ("vagyon", "vagyon"),
    ("veszteseg", "veszteség"),
    ("Veszteseg", "Veszteség"),
    ("leszarmazok", "leszármazók"),
    ("Leszarmazok", "Leszármazók"),
    ("felmenok", "felmenők"),
    ("Felmenok", "Felmenők"),
    ("fogyatekossagi", "fogyatékossági"),
    ("Fogyatekossagi", "Fogyatékossági"),
    ("csaladi", "családi"),
    ("Csaladi", "Családi"),
    ("hivo", "hívó"),
    ("Hivo", "Hívó"),
    ("szolgaltatja", "szolgáltatja"),
    ("eloleg", "előleg"),
    ("Eloleg", "Előleg"),
    ("befizetesek", "befizetések"),
    ("Befizetesek", "Befizetések"),
    ("befizetes", "befizetés"),
    ("reszletfizetesek", "részletfizetések"),
    ("Reszletfizetesek", "Részletfizetések"),
    ("reszletfizetes", "részletfizetés"),
    ("modell", "modell"),
    ("egyuttes", "együttes"),
    ("Egyuttes", "Együttes"),
    ("adobevallasi", "adóbevallási"),
    ("Adobevallasi", "Adóbevallási"),
    ("adobevallas", "adóbevallás"),
    ("Adobevallas", "Adóbevallás"),
    ("eredmenye", "eredménye"),
    ("Eredmenye", "Eredménye"),
    ("eredmeny", "eredmény"),
    ("Eredmeny", "Eredmény"),
    ("kulonbozeti", "különbözeti"),
    ("Kulonbozeti", "Különbözeti"),
    ("kulonbozet", "különbözet"),
    ("Kulonbozet", "Különbözet"),
    ("onbevallas", "önbevallás"),
    ("Onbevallas", "Önbevallás"),
    ("kulcs", "kulcs"),
    ("jogalap", "jogalap"),
    ("minimum", "minimum"),
    ("nyugdijrendszer", "nyugdíjrendszer"),
    ("Nyugdijrendszer", "Nyugdíjrendszer"),
    ("hozzajarulasi", "hozzájárulási"),
    ("Hozzajarulasi", "Hozzájárulási"),
    ("ado-bevallasi", "adó-bevallási"),
    ("Ado-bevallasi", "Adó-bevallási"),
    ("blgre", "BL-re"),
)


def _hu_restore_diacritics(hu_text: str) -> str:
    if not hu_text:
        return hu_text
    out = hu_text
    for old, new in _HU_DIACRITIC_LEMMAS:
        if old == new:
            continue
        pattern = r"(?<![A-Za-zÀ-ɏ])" + re.escape(old) + r"(?![A-Za-zÀ-ɏ])"
        out = re.sub(pattern, new, out)
    return out
