[[revisions."2018-y-siguientes".bindings]]
id = "modelo-232-2018.page_02.913-962.paraiso-operacion-7-descripcion"
source = "manual_input"
selector = { record = "page_02", field = "paraiso-operacion-7-descripcion", offset = 913, length = 50, data_type = "text" }
legal_refs = ["orden-hfp-816-2017:art-3", "ley-27-2014:art-19", "ley-58-2003:art-93"]
source_refs = ["aeat-dr-232-2018"]
