"""Fixture-metadata verification gate for verification_source tags.

The ``verification_source`` field on ``ExtractionProfileDefinition`` is an
honor-system declaration today — a profile can claim
``verification_source = "real_aeat_corpus_pdf"`` while the fixture at
``justificantes/<modelo_id>/`` is a reportlab-generated synthetic PDF, and no
structural gate catches the mismatch.

The synthetic fixture generator pins reportlab's ``setProducer`` to the literal
``"aeat-test-fixture-generator"`` for every synthetic fixture.  The tests in
this module read the ``/Producer`` DocInfo field from the committed fixture PDFs
and assert that the enum tag matches the physical evidence in the file.

Discriminator contract:

- ``real_aeat_corpus_pdf`` → ALL fixture PDFs for that modelo must NOT carry
  the ``"aeat-test-fixture-generator"`` producer.  Real AEAT PDFs are either
  produced by AEAT's own PDF toolchain or have no ``/Producer`` entry at all.

- ``synthetic_from_aeat_published_text`` → ALL fixture PDFs for that modelo
  MUST carry the ``"aeat-test-fixture-generator"`` producer.

- ``historical_suppression`` / ``not_applicable`` → no fixture-level assertion;
  these values have no discriminating signal in the PDF metadata.

Edge-case honesty:
  A real PDF without a ``/Producer`` field is indistinguishable from a
  hypothetical synthetic generator that also omits the producer.  The gate
  therefore relies on the project invariant that every synthetic fixture
  generated by ``_generate.py`` sets ``setProducer("aeat-test-fixture-generator")``.
  As long as that invariant holds, an absent producer is strong evidence for
  real provenance.  If a future generator skips ``setProducer``, this gate
  loses its ability to detect that class of mis-tag.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from .....core.directory_scan import scan_directory
from .....core.resources._boundary import bundled_path
from .....tests.fixtures.provenance import (
    FIXTURE_PROVENANCE_REAL,
    FIXTURE_PROVENANCE_SYNTHETIC,
    provenance_mismatches,
    sidecar_provenance,
)
from ._registry_schema_support import _committed_registry_tree

pytestmark = [pytest.mark.unit, pytest.mark.hex_domain]

# bundled_path() resolves to src/cadrumo/_data; the fixture tree lives one level
# up at src/cadrumo/tests/fixtures/justificantes — mirror the derivation in
# RegistryValidator.justificante_corpus_root.
_FIXTURE_ROOT = bundled_path().resolve().parents[0] / "tests" / "fixtures" / "justificantes"

_TAG_TO_PROVENANCE = {
    "real_aeat_corpus_pdf": FIXTURE_PROVENANCE_REAL,
    "synthetic_from_aeat_published_text": FIXTURE_PROVENANCE_SYNTHETIC,
}


def _all_fixture_pdfs(modelo_id: str) -> tuple[Path, ...]:
    """Return every ``*.pdf`` under justificantes/<modelo_id>/, sorted."""
    return scan_directory(_FIXTURE_ROOT / modelo_id, pattern="*.pdf")


def _verified_declaracion_pdf_profiles() -> list[tuple[str, str, str, str | None]]:
    """Return (modelo_id, revision_id, profile_id, verification_source) for
    every declaracion_pdf profile with corpus_round_trip_verified=true."""
    modelos, _ = _committed_registry_tree()
    rows: list[tuple[str, str, str, str | None]] = []
    for modelo in modelos:
        for rev_id, rev in modelo.revisions.items():
            for profile in rev.extraction_profiles:
                if profile.surface == "declaracion_pdf" and profile.corpus_round_trip_verified:
                    rows.append((modelo.id, rev_id, profile.id, profile.verification_source))
    return rows


def _dedup_by_modelo(
    rows: list[tuple[str, str, str, str | None]],
) -> list[tuple[str, str, str | None]]:
    """Collapse multi-revision profiles to one row per modelo_id+verification_source pair.

    Multiple revisions for the same modelo share the same fixture directory.
    We only need one producer-check per (modelo_id, verification_source) pair —
    the fixture pool is identical for every revision.
    """
    seen: set[tuple[str, str | None]] = set()
    deduped: list[tuple[str, str, str | None]] = []
    for modelo_id, _rev_id, profile_id, vs in rows:
        key = (modelo_id, vs)
        if key not in seen:
            seen.add(key)
            deduped.append((modelo_id, profile_id, vs))
    return deduped


_PROFILES = _verified_declaracion_pdf_profiles()
_DEDUPED = _dedup_by_modelo(_PROFILES)

# Parametrize only profiles where the fixture directory has at least one PDF
# and verification_source is one of the two discriminated values.
_DISCRIMINATED = [
    (modelo_id, profile_id, vs)
    for modelo_id, profile_id, vs in _DEDUPED
    if vs in {"real_aeat_corpus_pdf", "synthetic_from_aeat_published_text"} and bool(_all_fixture_pdfs(modelo_id))
]


@pytest.mark.parametrize(
    "modelo_id,profile_id,verification_source",
    _DISCRIMINATED,
    ids=[f"M{m}-{vs[:8]}" for m, _p, vs in _DISCRIMINATED],
)
def test_verification_source_matches_fixture_producer(
    modelo_id: str,
    profile_id: str,
    verification_source: str,
) -> None:
    """Each fixture's sidecar provenance must agree with its physical /Producer.

    The honesty check is per-fixture and sidecar-driven: every gated fixture
    self-declares ``provenance`` (``real_corpus`` | ``synthetic_generated``) in
    its ``.json`` sidecar, cross-checked against the ``/Producer`` DocInfo
    evidence — ``synthetic_generated`` must carry the
    ``aeat-test-fixture-generator`` signature, ``real_corpus`` must not. A real
    parser-corpus anchor kept in an otherwise-synthetic pool needs no allowlist;
    it simply declares ``real_corpus`` in its own sidecar. The per-modelo
    ``verification_source`` tag must still be backed by at least one fixture of
    the matching provenance, so the tag cannot be a lie.
    """
    fixture_pdfs = _all_fixture_pdfs(modelo_id)
    assert fixture_pdfs, (
        f"M{modelo_id} profile {profile_id!r} is corpus_round_trip_verified=true with "
        f"verification_source={verification_source!r} but no fixture PDFs found at "
        f"{_FIXTURE_ROOT / modelo_id}; add fixture PDFs or correct the profile tag"
    )

    mismatches: list[str] = []
    seen_provenances: set[str] = set()
    for pdf_path in fixture_pdfs:
        provenance = sidecar_provenance(pdf_path)
        if provenance is not None:
            seen_provenances.add(provenance)
        mismatches.extend(provenance_mismatches(pdf_path))

    expected = _TAG_TO_PROVENANCE[verification_source]
    if expected not in seen_provenances:
        mismatches.append(
            f"profile tag {verification_source!r} expects at least one "
            f"{expected!r} fixture, but none of {sorted(seen_provenances)} match",
        )

    if mismatches:
        joined = "\n  ".join(mismatches)
        pytest.fail(
            f"M{modelo_id} profile {profile_id!r} fixture provenance contradicts "
            f"physical /Producer evidence or the {verification_source!r} tag:\n  {joined}",
        )


def test_all_real_corpus_profiles_have_fixture_pdfs() -> None:
    """Every real_aeat_corpus_pdf profile must have at least one fixture PDF on disk.

    This prevents the silent class where a profile is tagged real_aeat_corpus_pdf
    but the fixture directory is empty or missing — the parametrized test above
    would be dormant and never catch a mis-tag introduced later.
    """
    missing: list[str] = []
    for modelo_id, profile_id, vs in _DEDUPED:
        if vs == "real_aeat_corpus_pdf" and not _all_fixture_pdfs(modelo_id):
            missing.append(f"M{modelo_id} profile {profile_id!r}: no fixture PDFs at {_FIXTURE_ROOT / modelo_id}")
    if missing:
        pytest.fail("real_aeat_corpus_pdf profiles without fixture PDFs (gate dormant):\n  " + "\n  ".join(missing))


def test_all_synthetic_profiles_have_fixture_pdfs() -> None:
    """Every synthetic_from_aeat_published_text profile must have at least one fixture PDF.

    Mirrors test_all_real_corpus_profiles_have_fixture_pdfs for synthetic profiles.
    """
    missing: list[str] = []
    for modelo_id, profile_id, vs in _DEDUPED:
        if vs == "synthetic_from_aeat_published_text" and not _all_fixture_pdfs(modelo_id):
            missing.append(f"M{modelo_id} profile {profile_id!r}: no fixture PDFs at {_FIXTURE_ROOT / modelo_id}")
    if missing:
        pytest.fail(
            "synthetic_from_aeat_published_text profiles without fixture PDFs (gate dormant):\n  "
            + "\n  ".join(missing),
        )
